# Devolution and the law of diminishing returns

> "What is bloated beyond its proportions inevitable collapses. ... What is concentrated, coherent, and connected to its past has power. What is dissipated, divided, and distended rots and falls to the ground. The bigger it bloats, the harder it falls." --- Robert Greene and Joost Elffers, *The 48 Laws of Power*[^507]

Hertofore, the history of human societies is that they have tended to evolve in the direction of greater "complexity" or sociopolitical control. Small hunting and gathering bands evolved into agricultural states, which gave way to larger-scale industrial nation-states. As archeologist and historian Joseph A. Tainer writes in *The Collapse of Complex Societies*, "Human history as a whole has been characterized by a seemingly inexorable trend toward higher levels of complexity, specialization, and sociopolitical control. ..."[^508] Now, however, the emergence of the next stage of economic development, the Information Society, promises to reverse the apparently "inexorable trend" toward greater levels of centralization.

Tainer's work raises many interesting questions pertinent to the themes of this book. For example, if Tainer is correct in supposing that devolution of centralized control and less redistribution of resources imply collapse, then it is unlikely that the industrial nation-state in its current form could long coexist with devolved microstates hosting Sovereign Individuals. The nation-states may be incapable of surviving on a diet of stable, much less dimished, resources. As Tainer details, when hypertrophied systems have exhausted their potential, as we believe nation-states have today, "the Law of Diminishing Marginal Returns" frequently sets in. In "many crucial spheres" the returns for increased investments in centralized sociopolitical control decline, or even become negative. Hence, the phenomenon of "Parkinson's Law," in which the number of employees and expense of operating the British Admiralty skyrocketed over the twentieth century, while the number of ships in the British Navy shrank dramatically.

Similar manifestations of the "Law of Diminishing Returns" are certainly in evidence in the United States and other leading economies as the twentieth century draws to a close. As Roger Lane, Professor of Social Sciences at Haverford College, wrote in "On the Social Meaning of Homicide Trends in America," "the old insitutions of social control -- law, schools, police, prisons -- have lost their effectiveness, despite frequent infusions of manpower and money."[^509] There is unambiguous evidence of increasing costs for the overall burdens of government. For example, total taxes rose from 27.8 percent of U.S. median income in 1957 to 37.6 percent in 1997.[^510] This is a strong hint, if not absolute proof, of diminishing marginal returns on the whole range of government activity in the United States.

In the past, sharply diminishing marginal returns have been a prelude to collapse. The argument of this book is that the increased capacity of individuals to protect their transactions and their assets from predatory taxation implies a decline in the redistribution of resources, along with less centralized social control, less regulation and regimentation, and, ultimately, devolution of territory. All these developments have historically been manifested in "collapse." In Tainter's terms, "collapse" is what happens when a centralized control system is no longer worth what it costs.

> "Whenever we have a threshold phenomenon, whether in physical, biological or social systems, the configuration of the system at the moment when the threshold is reached becomes unstable and the slightest, even infinitesimal displacement in the configuration of the system. Therefore a change in the behavior of a single individual, no matter how small, may precipitate in an unstable social configurational process that leads to a finite and sometimes radical change." --- Nicholas Rashevsky, *Looking at History Through Mathematics*

While most individual adaptations to change are admittedly marginal and evolutionary in character, there can be revolutionary "paradigmn shifts." Sometimes, even great empires tumble as a consequence. The marginal returns from further investment in centralized control can become so overwhelmingly negative that it is no longer economically rational for most individuals to continue to support the old system. Tainer explain the fall of the Roman Empire in these terms. In his words, "If accounts are to be believed, at least a portion of the overtaxed peasantry openly welcomes the relief they thought the barbarians would bring from the burdens of the Roman rule. And a much larger portion were evidently apathetic to the impending collapase. ... The costs of empire had risen dramatically, while in the face of barbarians' successes the protection that the State could offer to many of its citizens proved increasingly ineffectual. To many, there were simply no remaining benefits to the Empire, as both barbarians and tax collectors crossed and ravaged their land. As Gunderson notes, '... the net value of local autonomy exceeded that of membership in the Empire.' Complexity was no longer yielding benefits superior to disintegration, and yet it cost so much more."[^511]

Tainer quotes other authorities in support of his thesis that collapse can bring "with it a corresponding rise in the marginal return on social investment:"

> Zosimus, a writer of the second half of the fifth century A.D., wrote of Thessaly and Macedonia that, '... as a result of this exaction of taxes city and countryside were full of laments and complaints and all invoked the barbarians and sought the help of the barbarians.' ... '[B]y the fifth century,' concludes R.M. Adams, 'men were ready to abandon civilization itself in order to escape the fearful load of taxes.'"[^512]

Rashevsky's analysis of the "role of determinism versus indeterminism" in history emphasizes the vulnerability of systems to radical change that can be precipitaed even by a single individual when the system becomes unstable and reaches a "threshold" condition. When conditions are ripe for change (such as when diminishing marginal returns for supporting a centralized system no longer yield "benefits superior to disintegration"), then the opportunity for a radical change is so robust that practically anyone can precipitate it. Rashevsky write, "The individual who precipitates a finite change does not have to be an *exceptional* individual. He may be *any* individual. The situation is analogous to that in a physical system, where at a point of instability an accidental displacement of any one of the trillions of *identical* molecules precipitates a finite transition to a stable state."[^513]

We cannot specify who will precipitate the collapse of the overgrown nation-state system, or when it will happen. But extrapolating from Tainter's and Rashevsky's analyses of the dynamics of social change, we can foresee collapse coming. The most developed and heretofore succesful nation-states are all characterized by dwindling populations and massive, unfunded old-age pension liabilities. Absent unprecedented immigration from underdeveloped countries, or an unexpected influx of angels willing to work overtime and pay confiscatory tax rates, leading states in Europe, North America and Australasia will fall far short of the revenues needed to maintain the social benefits currently delivered. Actuaries forecast rising traxes nd lower benefits, i.e., diminishing marginal returns, especially for entrepreneurs who shoulder a disproportionate share of the tax burden.

IRS figures show that one-tenth of one percent of Americans paid a majority of income taxes in the United States as of 1997. These are precisely the persons to whom efficient minisovereignties can offer new opportunities for domicile at a negligible cost in taxes. The difference between the protection costs of a commercialized sovereignty and the predatory taxes imposed by the old nation-states could amount to the equivalent of many millions or even billions of dollars in lifetime income.

Conventional microeconomics is based upon the proposition that individuals who spot a $100 bill in the street will pick it up. Opportunities to save millions or billions would be tens of thousands or millions of times more compelling. People will act in the indicated way when faced with choice between confirming their costly allegiance to institutions beset by declining marginal returns, or shifting to new arrangements that demand less and promise more.

> "Of all 36 ways to get out of trouble, the best way is --- leave." --- Chinese proverb

The argument of this book clearly informs the decision to redeploy your capital, if you have any. Citizenship is obsolete. To optimize your lifetime earnings and become a Sovereign Individual you will need to become a customer of government or protection service rather than a citizen. Instead of paying whatever tax burden is imposed upon you by grasping politicians, you will be better positioned to prosper in the Information Age by freeing yourself to negotiate a private tax treaty that obliges you to pay no more for services of government than they are actually worth to you.

Based upon the history of other dominant systems facing collapse, those who opt for the *ultimum refugium* and get out early will be better off for having done so. This is already evident in the rash of laws passed during the 1990s to penalize Americans renouncing citizenship. The dangers of a nationalist reaction to the crisis of the nation-state make it important not to underestimate the scope for tyranny and mischief. Not withstanding the fact that the right to expatriate is enshrined in the U.S. Declaration of Independence, the U.S. is likely to be one of the more tyrannical jurisdictions blocking the emergence of commercialized sovereignty. You should aim never to leave your money in any jurisdiction that claims the right to conscript you, your children, or your grandchildren.

Whatever your current residence or nationality, to optimize your wealth you should aim to primarily reside in a country other than that from which you hold your first passport, while keeping the bulk of your money in a yet third jurisdiction, preferably a tax haven.

To better acquaint yourself with the alternatives, we recommend that you travel widely to visit attractive locales where you might wish to secure the right to reside in an emergency.

If you are truly ambitious, you may even wish to cave out a minisovereignty of your own. We provide contacts in the appendices who can help you negotiate your own tax-free zone, or zona franca, from a recognized government that is prepared to sublet it sovereignty under the right circumstances.

Suppose you are just starting out...

But suppose you agree with the premises of this book and are excited by the prospect of the Information Age, but lack the ready capital to deploy in order to take advantage of opportunities to benefit from commercialized sovereignty? What do you do?

Any recipe for easy success is bound to dissapoint. Opportunities to succeed abound as a consequence of the Information Revolution. Which one is right for you to capture is beyond our scope to say. If you are intent in accumulating capital in order to realize your full potential as a Sovereign Individual, you should make it one of your priorities to study and evaluate the works of the various gurus who attempted to teach useful hints about how to succeed.

Any good business bookstore or one of the on-line booksellers, like Amazon.com, can offer you a wide selection of manuals on success. Read as many as you can, not with the idea that any one set of rules will automatically make you a financially independent, but with the understanding that success is a choice. If you re to succeed, you must arm yourself with the perspective and habits that characterize succesful persons.

If you are still at the stage of selecting a career, resist the temptation of jumping to an easy conclusion that the best route to success in the Information Age is to become a computer programmer. Yes, it is true that programmers have been in great demand as the Information Revolution unfolded in the last quarter of the twentieth century. But as computational power has increased, artificial intelligence has developed apace. A company called Authorgeneics has already demonstrated the capacity to create object-oriented software without programmers. You won't be highly paid by studying to do something that can be done with Alladin's Lamp. The problem with specializing in software or any other rapidly evolving field at the center of the Information Revolution is that your area of expertise could soon be outdated.

This underscores the wisdom of the traditional liberal education, which aimed to encourage students to develop their critical faculties and thinking skills. Success in business, as in most areas of life, depends upon being able to solve problems. If you can teach yourself how to solve problems, you have a bright career ahead of yourself. No matter where you live, you will find problems galore in need of solving. In most cases, those who would benefit from solutions or their problems will pay you handsomely to effect them.
