project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  title: "Das souveräne Individuum"
  output-file: main
  subtitle: "Der Übergang zum Informationszeitalter"
  author: "James Dale Davidson & Lord William Rees-Mogg"
  translator: Andreas Tank
  date: "9/10/2024"
  image: cover.png
  image-alt: "Das souveräne Individuum"
  isbn: 978-3-16-123450-0
  license: CC-BY-4.0
  language: de
  original-title: "The Sovereign Individual"
  publisher: Konsensus Network
  original-publisher: Simon and Schuster
  favicon: /figures/freestarfish.png
  repo-url: https://github.com/konsensusnetwork/TSI_DE
  repo-actions: [edit, source]
  search:
    location: navbar
    type: overlay
  sidebar:
    style: floating
    border: true
  navbar:
    left:
      - icon: book
        text: "Read online"
        href: index.qmd
        aria-label: Book
      - icon: shop
        text: "Get the paperback in Presale!"
        href: https://bitcoinbook.shop/products/das-souverane-individuum
        aria-label: Shop
  page-footer:
    left:
      - text: "© 2024 Konsensus Network"
    center:
      - text: "License"
        href: index.qmd
      - text: "About the publisher"
        href: publisher.qmd
      - text: "Presale"
        href: presale.qmd
    right:
      - icon: twitter
        href: https://twitter.com/konsensusn
        aria-label: Twitter
      - icon: github
        href: https://github.com/konsensusnetwork
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/konsensusnetwork
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/konsensusnetwork
        aria-label: YouTube
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/TSI_DE_CH01.qmd
    - chapters/TSI_DE_CH02.qmd
    - chapters/TSI_DE_CH03.qmd
    - chapters/TSI_DE_CH04.qmd
    - chapters/TSI_DE_CH05.qmd
    - chapters/TSI_DE_CH06.qmd
    - chapters/TSI_DE_CH07.qmd
    - chapters/TSI_DE_CH08.qmd
    - chapters/TSI_DE_CH09.qmd
    - chapters/TSI_DE_CH10.qmd
    - chapters/TSI_DE_CH11.qmd
  

format:
  html:
    lang: de
    theme:
      light: [lux, theme.scss, theme-light.scss]
      dark: [lux, theme.scss, theme-dark.scss]
    number-depth: 2
    grid:
      sidebar-width: 500px
      body-width: 900px
      margin-width: 350px
      gutter-width: 4em
    toc: true
    toc-location: left
    reference-location: margin
  pdf:
    lang: de
    documentclass: memoir
    classoption: smalldemyvopaper,10pt,twoside,onecolumn,openright,extrafontsizes,hidelinks
    papersize: a5
    toc-depth: 1
    toc-title: Inhalt
    keep-tex: true
    colorlinks: false
    include-in-header:
      - preamble.tex
  epub:
    cover-image: cover.png
    cover-image-alt: Das souveräne Individuum
    creator: Konsensus Network
    toc: true
    toc-depth: 1
    toc-title: Inhalt
    lang: "de-DE"



