project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  title: "Das souveräne Individuum"
  output-file: main
  subtitle: "Der Übergang zum Informationszeitalter"
  author: "James Dale Davidson & Lord William Rees-Mogg"
  translator: Andreas Tank
  date: "11/25/2024"
  image: cover.png
  image-alt: "Das souveräne Individuum"
  isbn: 978-9916-749-26-5
  license: CC-BY-4.0
  language: de
  site-url: https://souveräneindividuum.de
  original-title: "The Sovereign Individual"
  publisher: Konsensus Network
  original-publisher: Simon & Schuster
  favicon: cover.png
  # repo-url: https://github.com/konsensusnetwork/TSI_DE
  # repo-actions: [edit, source]
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    border: true
  navbar:
    left:
      - icon: book
        text: "Read online"
        href: index.qmd
        aria-label: Book
      - icon: shop
        text: "Buy the book!"
        href: buy.qmd
        aria-label: Shop
  page-footer:
    left:
      - text: "© 2024 Konsensus Network"
    center:
      - text: "License"
        href: index.qmd
      - text: "About the publisher"
        href: publisher.qmd
      - text: "Buy the book!"
        href: buy.qmd
      - text: "Blog"
        href: blog
    right:
      - icon: twitter
        href: https://twitter.com/konsensusn
        aria-label: Twitter
      - icon: github
        href: https://github.com/konsensusnetwork
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/konsensusnetwork
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/konsensusnetwork
        aria-label: YouTube
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - kapitel/00b.qmd
    - kapitel/00.qmd
    - kapitel/01.qmd
    # - kapitel/02.qmd
    # - kapitel/03.qmd
    # - kapitel/04.qmd
    # - kapitel/05.qmd
    # - kapitel/06.qmd
    # - kapitel/07.qmd
    # - kapitel/08.qmd
    # - kapitel/09.qmd
    # - kapitel/10.qmd
    # - kapitel/11.qmd
    - kapitel/Z0.qmd
    - kapitel/Z1.qmd

format:
  html:
    lang: de
    theme:
      light: [flatly, theme.scss, theme-light.scss]
    number-depth: 2
    grid:
      sidebar-width: 500px
      body-width: 900px
      margin-width: 350px
      gutter-width: 1em
    toc: true
    toc-location: left
    reference-location: margin
  pdf:
    lang: de
    documentclass: memoir
    classoption: smalldemyvopaper,10pt,twoside,onecolumn,openright,extrafontsizes,hidelinks
    papersize: a5
    toc-depth: 1
    toc-title: Inhalt
    keep-tex: true
    colorlinks: false
    include-in-header:
      - preamble.tex
  epub:
    cover-image: cover.png
    cover-image-alt: |
      Das souveräne Individuum book cover
    creator: Konsensus Network
    toc: true
    toc-depth: 1
    toc-title: Inhalt
    lang: "de-DE"
    css: epub.css
    number-depth: 2