# DIE MEGAPOLITIK DES INFORMATIONSZEITALTERS

*Der Triumph der Effizienz über die Macht*

> „...es ist die computergestützte Information, nicht die Arbeitskraft oder die Massenproduktion, die zunehmend die US-Wirtschaft antreibt und die in einer Welt, die für 500 Fernsehkanäle verdrahtet ist, Kriege gewinnen wird. Die computergestützte Information existiert im Cyberspace - die neue Dimension, die durch die endlose Reproduktion von Computernetzwerken, Satelliten, Modems, Datenbanken und dem öffentlichen Internet geschaffen wurde.“ [^187] - Neil Munro

Am 30. Dezember 1936 besetzten Automobilarbeiter, die höhere Löhne forderten, gewaltsam zwei der Hauptwerke von General Motors in Flint, Michigan. Sie legten die Maschinen still, schalteten die Fließbänder ab und machten es sich gemütlich. Die Arbeiter, die für den Betrieb der Fabriken eingestellt worden waren, setzten sich in einem Streik zusammen, der viele Wochen dauern sollte. Es war ein Drama, das von gewalttätigen Ausschreitungen und den schwankenden Loyalitäten der Polizei, der Miliz von Michigan und politischen Persönlichkeiten auf allen Regierungsebenen geprägt war. Da die Gewerkschaft bei der Durchsetzung ihrer Forderungen kaum Fortschritte machte, streikte sie am 1. Februar 1937 erneut.

Gewerkschaften übernahmen gewaltsam die Chevrolet-Fabrik von GM in Flint. Indem sie die wichtigsten Fabriken von General Motors besetzten und schlossen, lähmten die Arbeiter effektiv die Produktionskapazität des Unternehmens. In den zehn Tagen nach der Besetzung der dritten Fabrik produzierte GM in den USA nur 153 Autos.

Wir greifen diese Kurzmeldung von vor sechzig Jahren wieder auf, um die Revolution in den megapolitischen Verhältnissen, die jetzt stattfindet, in einen klareren Bezug zu setzen. Der GM-Sitzstreik ereignete sich innerhalb der Lebenszeiten einiger Leser dieses Buches. Doch wir glauben, dass Sitzstreiks im Informationszeitalter genauso veraltet sein werden wie Sklaven, die mit riesigen Steinen durch die Wüste ziehen, um Bestattungspyramiden für die Pharaonen zu errichten. Während Gewerkschaften und ihre Einschüchterungstaktiken in der Industriezeit so vertraut wurden, dass sie als unbestrittener Teil der sozialen Landschaft gelten, waren sie auf spezielle megapolitische Bedingungen angewiesen, die schnell verblassen. Auf der Autobahn der Informationen wird es weder Chevrolets noch Gewerkschaften zum Bestreiken geben.

Die Schicksale von Regierungen werden denen ihrer Gegenstücke, den Gewerkschaften, in den Niedergang folgen. Institutionalisierter Zwang, der eine wesentliche Rolle in der Gesellschaft des zwanzigsten Jahrhunderts spielte, wird nicht mehr möglich sein. Technologie führt zu einer tiefgreifenden Veränderung in der Logik von Erpressung und Schutz.

> „\... es gibt keinen Privatbesitz, keine Herrschaft, kein Meins und Deins als Unterscheidung; sondern nur, dass jedem das gehört, was er sich erarbeiten kann, und nur so lange, wie er es behalten kann.“ [^188] - Thomas Hobbes

### Erpressung und Schutz

Im Laufe der Geschichte war Gewalt stets ein Dolch, der das Herz der Wirtschaft bedrohte. Wie Thomas Schelling treffend sagte: „Die Macht zu verletzen - Dinge zu zerstören, die jemand schätzt, Schmerz und Leid zuzufügen - ist eine Art von Verhandlungsmacht, nicht leicht einzusetzen, aber oft eingesetzt. In der Unterwelt ist es die Basis für Erpressung, Raub und Entführung, in der Geschäftswelt für Boykott, Streiks und Aussperrungen\... Es ist oft die Basis für Disziplin, zivil und militärisch; und die Götter benutzen es, um Disziplin einzufordern.“ [^189] Die Fähigkeit einer Regierung, zu besteuern, hängt von denselben Schwachstellen ab wie private Erpressung und Raub. Obwohl wir es nicht in diesen Begriffen wahrnehmen, bietet der Anteil der Vermögenswerte, die durch Kriminalität und Regierung kontrolliert und zwangsweise ausgegeben werden, eine grobe Messung des megapolitischen Gleichgewichts zwischen Erpressung und Schutz. Wenn Technologie den Schutz von Vermögenswerten erschwerte, wäre Kriminalität weit verbreitet, ebenso wie Gewerkschaftstätigkeiten. Unter solchen Umständen würde der Schutz durch die Regierung daher einen Aufschlag verlangen. Die Steuern wären hoch. Wo Steuern niedriger sind und Lohnsätze am Arbeitsplatz durch Marktkräfte und nicht durch politische Eingriffe oder Zwang bestimmt werden, hat die Technologie das Gleichgewicht in Richtung Schutz gekippt.

Das technologische Ungleichgewicht zwischen Erpressung und Schutz erreichte im letzten Drittel des zwanzigsten Jahrhunderts ein Extrem. In einigen fortschrittlichen westlichen Gesellschaften wurden mehr als die Hälfte der Ressourcen von den Regierungen in Anspruch genommen. Die Einkommen eines großen Teils der Bevölkerung wurden entweder per Erlass festgelegt oder unter dem Einfluss von Zwang bestimmt, zum Beispiel durch Streiks und Gewaltandrohungen in anderen Formen. Der Wohlfahrtsstaat und die Gewerkschaft waren beides technologische Artefakte, die sich als Triumph der Macht über die Effizienz im zwanzigsten Jahrhundert die Beute teilten. Sie hätten ohne die Technologien, sowohl militärische als auch zivile, die den Ertrag von Gewalt während des Industriezeitalters erhöhten, nicht existieren können.

Die Fähigkeit, Vermögenswerte zu schaffen, hat schon immer eine gewisse Anfälligkeit für Erpressung mit sich gebracht. Je größer die geschaffenen oder besessenen Vermögenswerte, desto höher der zu zahlende Preis, auf die eine oder andere Weise. Entweder man bezahlte jeden, der die Hebelwirkung besaß, Gewalt für Erpressungszwecke einzusetzen, oder man investierte in militärische Macht, die in der Lage war, jeglichen Versuch einer Erpressung mit roher Gewalt zu vereiteln.

> „Man soll nicht mehr von Frevel hören in deinem Lande noch von Schaden oder Verderben in deinen Grenzen\...\“ - Jesaja 60:18

### Die Mathematik des Schutzes

Nun könnte die Klinge der Gewalt bald stumpf gemacht werden. Die Informationstechnologie verspricht, das Gleichgewicht zwischen Schutz und Erpressung dramatisch zu ändern und in vielen Fällen den Schutz von Vermögenswerten zu erleichtern und die Erpressung zu erschweren. Die Technologie des Informationszeitalters ermöglicht es, Vermögenswerte zu schaffen, die vielen Formen von Zwang unzugänglich sind. Diese neue Asymmetrie zwischen Schutz und Erpressung basiert auf einer Grundwahrheit der Mathematik. Es ist einfacher zu multiplizieren als zu teilen. Auch wenn diese Wahrheit grundlegend ist, waren ihre weitreichenden Folgen vor dem Aufkommen von Mikroprozessoren verschleiert. Hochgeschwindigkeitscomputer haben in den letzten zehn Jahren viele Milliarden Mal mehr Berechnungen ermöglicht als in der gesamten vorangegangenen Geschichte der Welt. Dieser Sprung in der Berechnung hat es uns zum ersten Mal ermöglicht, einige der universellen Eigenschaften der Komplexität zu erfassen. Was die Computer zeigen, ist, dass komplexe Systeme nur von unten nach oben aufgebaut und verstanden werden können. Primzahlen zu multiplizieren ist einfach. Aber die Komplexität aufzuschlüsseln, indem man versucht, das Produkt großer Primzahlen zu zerlegen, ist so gut wie unmöglich. Kevin Kelly, der Herausgeber von Wired, bringt es so auf den Punkt: „Mehrere Primzahlen in ein größeres Produkt zu multiplizieren, ist einfach; jedes Grundschulkind kann das. Aber die Supercomputer der Welt ersticken beim Versuch, ein Produkt in seine einfachen Primzahlen zu zerlegen.“ [^190]

### Die Logik von komplexen Systemen

Die Cyber-Ökonomie wird unvermeidlich durch diese tiefe mathematische Wahrheit geformt. Sie hat bereits einen offensichtlichen Ausdruck in leistungsstarken Verschlüsselungsalgorithmen. Wie wir später in diesem Kapitel erkunden werden, ermöglichen diese Algorithmen die Schaffung eines neuen, geschützten Bereichs des Cyber-Handels, in dem der Hebel der Gewalt stark reduziert sein wird. Das Gleichgewicht zwischen Erpressung und Schutz wird sich drastisch in Richtung Schutz verschieben. Dies wird das Aufkommen einer Wirtschaft erleichtern, die mehr auf spontanen Anpassungsmechanismen beruht und weniger auf bewusster Entscheidungsfindung und Ressourcenzuweisung durch Bürokratie. Das neue System, in dem der Schutz im Vordergrund steht, wird sich stark von dem unterscheiden, was aus der Dominanz von Zwang in der industriellen Periode hervorging.

### Befehls- und Kontrollsysteme sind primitiv.

In *The Great Reckoning* haben wir geschrieben, dass der Computer uns ermöglicht, die bisher unsichtbare Komplexität zu „sehen“, die in einer Vielzahl von Systemen inhärent ist.[^243] Nicht nur erweitert die fortgeschrittene Rechenfähigkeit unser Verständnis über die Dynamik komplexer Systeme, sie ermöglicht uns auch, diese Komplexitäten auf produktive Weise zu nutzen. In gewisser Weise ist dies nicht einmal eine Wahl, sondern eine Unvermeidlichkeit, wenn die Wirtschaft über die unflexible Phase der zentralen Kontrolle hinaus fortgeschritten sein soll. Ein solches System, das auf linearen Beziehungen basiert, ist grundsätzlich primitiv. Die staatliche Aneignung von Ressourcen lenkt diese zwangsläufig von hochwertigen, komplexen Nutzungen hin zu primitiven, geringwertigen Nutzungen. Es ist ein Prozess, der durch die gleiche mathematische Asymmetrie begrenzt ist, die das Aufspüren des Produkts großer Primzahlen verhindert. Das Teilen der Beute kann nie etwas anderes als primitiv sein.

### Alles wird komplexer

Überall wo man im Universum hinschaut, sieht man Systeme, die mit ihrer Evolution zunehmend komplexer werden. Das gilt in der Astrophysik. Das gilt in einer Pfütze. Lässt man Regenwasser an einer niedrigen Stelle stehen, wird es komplexer. Fortgeschrittene Systeme jeder Art sind komplexe adaptive Systeme ohne eine leitende Autorität. Jedes komplexe System in der Natur, wovon die Marktwirtschaft die offensichtlichste soziale Ausdrucksform ist, beruht auf verteilten Fähigkeiten. Systeme, die unter der breitesten Palette von Bedingungen am effektivsten arbeiten, sind für ihre Widerstandsfähigkeit auf spontane Ordnung angewiesen, die neuartige Möglichkeiten aufnimmt. Das Leben selbst ist ein solches komplexes System. Milliarden potenzieller Kombinationen von Genen ergeben ein einzelnes menschliches Individuum. Die Auswahl unter ihnen würde jede Bürokratie überfordern.

Vor fünfundzwanzig Jahren wäre das nur eine Intuition gewesen. Heute ist es nachweisbar. Je näher uns Computer dem Verständnis der Mathematik künstlichen Lebens bringen, desto besser verstehen wir die Mathematik des realen Lebens, die der biologischen Komplexität. Diese Geheimnisse der Komplexität, durch Informationstechnologie genutzt, ermöglichen es, Volkswirtschaften in komplexere Formen umzugestalten. Das Internet und das World Wide Web haben bereits Eigenschaften eines organischen Systems angenommen, wie Kevin Kelly in „Out of Control: The New Biology of Machines, Social Systems, and the Economic World“ vorschlägt.[^191] In seinen Worten ist die Natur „eine Ideenfabrik. Lebenswichtige, postindustrielle Paradigmen sind in jedem Ameisenhügel im Dschungel verborgen\... Die Großhandelsübertragung von Biologie in Maschinen sollte uns mit Ehrfurcht erfüllen. Wenn die Einheit von Geborenem und Gemachtem vollständig ist, werden unsere Fabrikationen lernen, sich anpassen, sich selbst heilen und sich entwickeln. Dies ist eine Macht, von der wir bisher kaum geträumt haben.“ [^192]

Tatsächlich dürften die Folgen der „großflächigen Übertragung von Biologie in Maschinen“ weitreichend sein. Es hat schon immer eine starke Tendenz gegeben, dass soziale Systeme die Eigenschaften der vorherrschenden Technologie nachbilden. Dies ist etwas, das Marx richtig erkannt hat. Gigantische Fabriken fielen mit dem Zeitalter der großen Regierungen zusammen. Mikroprozessoren machen Institutionen kleiner. Wenn unsere Analyse zutrifft, wird die Technologie des Informationszeitalters letztendlich eine Wirtschaft schaffen, die besser geeignet ist, die Vorteile von Komplexität zu nutzen.

Die megapolitischen Dimensionen einer solchen Veränderung sind so wenig verstanden, dass selbst die meisten von denen, die ihre mathematische Bedeutung erkannt haben, dies auf eine anachronistische Weise getan haben. Es fällt einfach schwer, vollständig zu begreifen und zu verinnerlichen, dass der technologische Wandel in den nächsten Jahren wahrscheinlich die meisten politischen Formen und Konzepte der modernen Welt überholen wird. Zum Beispiel schrieb der verstorbene Physiker Heinz Pagels in seinem weitsichtigen Buch *Die Träume der Vernunft*: „Ich bin davon überzeugt, dass die Nationen und Menschen, die die neue Wissenschaft der Komplexität beherrschen, die wirtschaftlichen, kulturellen und politischen Supermächte des nächsten Jahrhunderts werden.“ [^193] Es ist eine beeindruckende Prognose. Aber wir glauben, dass sie zwangsläufig falsch sein muss, nicht weil sie falsch wahrgenommen wird, sondern gerade weil sie sich als richtiger herausstellen wird, als Dr. Pagels zu äußern wagte. Gesellschaften, die sich selbst so umgestalten, dass sie komplexere adaptive Systeme werden, werden in der Tat prosperieren. Aber wenn sie es tun, werden sie wahrscheinlich keine Nationen und erst recht keine „politischen Supermächte“ mehr sein. Die wahrscheinlich unmittelbaren Nutznießer der erhöhten Komplexität sozialer Systeme werden vielmehr die souveränen Einzelpersonen des neuen Jahrtausends sein.

So wie Pagels Vorhersage dasteht, ist es, als ob ein Schamane einer Jagdgruppe von vor fünfhundert Generationen seinen Männern erzählt, während sie um das Lagerfeuer kauern: „Ich bin überzeugt, dass die erste Jagdgruppe, die die neue Wissenschaft des bewässerten Pflanzens beherrscht, mehr Freizeit für Geschichtenerzählen haben wird, als sogar jene Kerle am See, die die großen Fische fangen.“ So richtig er auch über die Bedeutung der Komplexität lag, Pagels hat die grundlegendste Tatsache von allen übersehen. Wenn sich die Logik der Gewalt ändert, verändert sich die Gesellschaft.

## DIE LOGIK DER GEWALT

Um zu verstehen, wie und warum, ist es notwendig, sich auf mehrere Aspekte der Megapolitik zu konzentrieren, die selten in Betracht gezogen werden. Dies sind Themen, die der Historiker Frederic C. Lane untersucht hat, dessen Arbeit über Gewalt und die wirtschaftliche Bedeutung des Krieges an anderer Stelle in diesem Band besprochen wird. Als Lane in der Mitte dieses Jahrhunderts schrieb, war die Informationsgesellschaft noch nirgends in Sicht. Unter den gegebenen Umständen könnte er durchaus angenommen haben, dass der Wettbewerb um Gewaltanwendung in der Welt, mit dem Erscheinen des Nationalstaats seine letzte Phase erreicht hatte. In seinen Werken gibt es keinen Hinweis darauf, dass er die Mikroverarbeitung vorhergesehen hat oder glaubte, dass es technologisch machbar wäre, Vermögenswerte im Cyberspace zu schaffen, einem Bereich ohne physische Existenz. Lane hatte nichts über die Auswirkungen der Möglichkeit zu sagen, dass große Massen an Handel nahezu immun gegen die Hebelwirkung der Gewalt gemacht werden könnten.

Obwohl Lane die derzeit ablaufenden technologischen Revolutionen nicht vorhersehen konnte, waren seine Erkenntnisse über die verschiedenen Stufen der Monopolisierung von Gewalt in der Vergangenheit so klar, dass sie offensichtliche Anwendung auf die aufkommende Informationsrevolution finden. Lanes Untersuchung der gewalttätigen mittelalterlichen Welt lenkte seine Aufmerksamkeit auf Themen, die konventionelle Ökonomen und Historiker tendenziell vernachlässigen. Er erkannte, dass die Organisation und Kontrolle von Gewalt eine große Rolle dabei spielt, welche Verwendung von knappen Ressourcen gemacht wird.[^194] Lane erkannte auch, dass die Produktion von Gewalt in der Regel nicht als Teil des wirtschaftlichen Outputs betrachtet wird, die Kontrolle von Gewalt jedoch für die Wirtschaft von entscheidender Bedeutung ist. Die Hauptaufgabe der Regierung besteht darin, Schutz vor Gewalt zu gewährleisten. Wie er es ausdrückte:

„Jedes wirtschaftliche Unternehmen benötigt und bezahlt für Schutz. Schutz vor der Zerstörung oder bewaffneten Übernahme seines Kapitals und der gewaltsamen Störung seiner Arbeit. In hochorganisierten Gesellschaften ist die Bereitstellung dieser Dienstleistung, des Schutzes, eine der Funktionen einer besonderen Vereinigung oder eines Unternehmens, das man Regierung nennt. Tatsächlich ist eine der auffälligsten Eigenschaften von Regierungen ihr Versuch, Recht und Ordnung zu schaffen, indem sie selbst Gewalt anwenden und durch verschiedene Mittel die Anwendung von Gewalt durch andere kontrollieren.“ [^195]

Das ist ein Punkt, der offenbar zu grundlegend ist, um in Lehrbüchern zu erscheinen oder Teil der staatsbürgerlichen Diskussion zu sein, die vermutlich den Verlauf der Politik bestimmt. Aber er ist auch zu grundlegend, um ignoriert zu werden, wenn man die sich entfaltende Informationsrevolution verstehen will. Der Schutz von Leben und Eigentum ist in der Tat ein entscheidendes Bedürfnis, das jede Gesellschaft, die jemals existiert hat, geplagt hat. Wie man gewalttätige Aggression abwehren kann, ist das zentrale Dilemma der Geschichte. Es kann nicht leicht gelöst werden, trotz der Tatsache, dass Schutz auf mehr als eine Weise bereitgestellt werden kann.

### Das Ende einer Ära

Während wir schreiben, beginnen die megapolitischen Folgen des Informationszeitalters gerade erst spürbar zu werden. Der wirtschaftliche Wandel der letzten Jahrzehnte hat dazu geführt, dass Informations- und Rechenleistung das primäre Gut ist, weit vor Maschinenkraft. Es findet eine Verlagerung statt von der Fabrik zum Arbeitsplatz, von der Massenproduktion zu kleineren Teams oder sogar zu Einzelpersonen, die alleine arbeiten. Mit der Abnahme hoch organisierter Großunternehmen sinkt auch das Potential für Sabotage und Erpressungen am Arbeitsplatz. Kleinere Betriebseinheiten sind zudem deutlich schwerer von Gewerkschaften zu organisieren.

Mikrotechnologie ermöglicht es Unternehmen, kleiner und mobiler zu sein. Viele handeln mit Dienstleistungen oder Produkten, die kaum natürliche Ressourcen enthalten. Prinzipiell könnten diese Geschäfte fast überall auf dem Planeten betrieben werden. Sie sind nicht an einen bestimmten Ort gebunden, wie eine Mine oder ein Hafen. Daher werden sie im Laufe der Zeit weit weniger anfällig dafür sein, entweder von Gewerkschaften oder von Politikern besteuert zu werden. Eine alte chinesische Volksweisheit besagt: „Von den sechsunddreißig Möglichkeiten, sich aus Schwierigkeiten herauszuwinden, ist die beste - zu gehen.“ [^196]

Im Informationszeitalter wird diese östliche Weisheit leicht anwendbar sein. Wenn Betriebe aufgrund übermäßiger Anforderungen an einem Ort unbequem werden, wird es wesentlich leichter sein, umzuziehen. Tatsächlich wird es im Informationszeitalter, wie wir weiter unten ausführen, möglich sein, virtuelle Unternehmen zu gründen, deren Domizil in jeder Rechtsordnung vollständig vom aktuellen Markt abhängt. Über Nacht zunehmende Erpressungsversuche, sei es durch Regierungen oder andere Organisationen, könnten dazu führen, dass die Aktivitäten und Vermögenswerte des virtuellen Unternehmens mit Lichtgeschwindigkeit aus dem Rechtsgebiet fliehen.

Die zunehmende Integration von Mikrotechnologie in industrielle Prozesse bedeutet, dass selbst solche Firmen, die noch mit groß angelegten, hergestellten Produkten handeln, nicht mehr so anfällig für Gewalt sind, wie sie es einmal waren. Ein Beispiel, das diesen Punkt veranschaulicht, ist der Zusammenbruch des langwierigen Streiks der eingeschränkten Autoarbeitergewerkschaft gegen Caterpillar, der in den letzten Tagen des Jahres 1995 nach fast zwei Jahren abgebrochen wurde. Im Gegensatz zu den Montagelinien der 1930er Jahre beschäftigt das heutige Caterpillar-Werk weit mehr qualifizierte Arbeiter. Durch ausländischen Wettbewerb unter Druck gesetzt, lagerte Caterpillar einen Großteil seiner gering qualifizierten Arbeit aus, schloss ineffiziente Anlagen und investierte fast 2 Milliarden Dollar in die Automatisierung von Maschinenwerkzeugen durch Computer und die Installation von Montagerobotern. Sogar der Streik selbst trug dazu bei, arbeitssparende Effizienzsteigerungen anzuspornen. Das Unternehmen behauptet nun, 2000 Mitarbeiter weniger zu benötigen als zu Beginn des Streiks.[^197]

Die Megapolitik des Produktionsprozesses hat sich drastischer verändert, als es die meisten Menschen realisieren. Diese Veränderung ist noch nicht klar ersichtlich, teilweise weil es immer eine Verzögerung zwischen einer Revolution in den megapolitischen Bedingungen und den unvermeidbaren, darauffolgenden institutionellen Veränderungen gibt. Darüber hinaus bedeutet die rasche Evolution der Mikroprozessortechnologie, dass jetzt Produkte am Horizont auftauchen, deren megapolitische Konsequenzen sogar vor ihrer Existenz antizipiert werden können. Sie werden eine völlig neue Welt schaffen.

## AUSBEUTUNG DER KAPITALISTEN DURCH DIE ARBEITER

Der Charakter der Technologie im größten Teil des zwanzigsten Jahrhunderts machte die gewaltsame Besetzung einer Fabrik, oder einen Sitzstreik, zu einer herausfordernden Taktik, die Eigentümer oder Manager entkräften mussten. Wie Historiker Robert S. McElvaine es ausdrückte, machte es ein Sitzstreik „schwierig für Arbeitgeber, den Streik zu brechen, ohne das Gleiche mit ihrer eigenen Ausrüstung zu tun.“ [^198] In der Tat hielten die Arbeiter das Kapital der Eigentümer physisch als Geisel. Aus den unten erörterten Gründen waren größere Industrieunternehmen leichtere Ziele für Gewerkschaften, als kleinere Firmen. Im Jahr 1937 war General Motors vielleicht das führende Industrieunternehmen der Welt. Seine Fabriken waren unter den größten und kostspieligsten Ansammlungen von Maschinen, die je zusammengestellt wurden, mit vielen Tausenden von Arbeitern. Jede Stunde, jeder Tag, den die GM-Werke gezwungen waren, untätig zu sitzen, kostete das Unternehmen ein kleines Vermögen. Ein Streik, der über Wochen hinweg ungelöst blieb, wie im Winter 1936-37, bedeutete rasch anschwellende Verluste.

### Die Herausforderung von Angebot und Nachfrage

Als GM nach der Beschlagnahmung seiner dritten Fabrik nicht mehr in der Lage war, Autos zu produzieren, kapitulierte das Unternehmen bald vor der Gewerkschaft. Dies war mitnichten eine wirtschaftliche Entscheidung, die auf dem Angebot und der Nachfrage nach Arbeitskräften basierte. Weit gefehlt. Als General Motors den Forderungen der Gewerkschaft nachkam, waren neun Millionen Menschen in den Vereinigten Staaten arbeitslos, 14 Prozent der Arbeitskräfte. Die meisten der Arbeitssuchenden hätten gerne einen Arbeitsplatz bei GM angenommen. Sie hatten sicherlich die Fähigkeiten, um die Arbeitsplätze in der Montagelinie zu besetzen, obwohl man dies aus den meisten zeitgenössischen Berichten nicht herauslesen kann. Ein feines Benehmen überschattete die direkte Analyse der Arbeitsbeziehungen während der industriellen Periode. Eine ihrer Vortäuschungen war die Idee, dass Fabrikarbeitsplätze, insbesondere in der Mitte des zwanzigsten Jahrhunderts, qualifizierte Arbeitsplätze waren. Das war nicht wahr. Die meisten Fabrikarbeitsplätze hätten von fast jedem erledigt werden können, der in der Lage war, pünktlich zu erscheinen. Sie erforderten wenig oder gar keine Ausbildung, nicht einmal die Fähigkeit zu lesen oder zu schreiben. Noch in den 1980er Jahren konnten große Teile der Belegschaft von General Motors entweder nicht lesen, nicht rechnen oder beides. Bis in die 1990er Jahre erhielt der typische Montagelinienarbeiter bei GM nur einen Tag Einarbeitung, bevor er seinen Platz in der Montagelinie einnahm. Ein Job, den man an einem einzigen Tag erlernen kann, ist keine qualifizierte Arbeit.

Und doch konnten die Fabrikarbeiter von GM im Jahr 1937, unqualifizierte und qualifizierte Arbeiter gleichermaßen, ihren Arbeitgebern eine Gehaltserhöhung abringen. Ihr Erfolg hatte viel mehr mit den Dynamiken der Gewalt als mit dem Angebot und der Nachfrage nach Arbeitskräften zu tun. Im März 1937, dem Monat nach der Beilegung der GM-Konfrontation, gab es in den Vereinigten Staaten 17 weitere Sitzstreiks. Die meisten waren erfolgreich. Ähnliche Episoden ereigneten sich in jedem industrialisierten Land. Die Arbeiter besetzten einfach die Fabriken und erpressten die Eigentümer. Es war eine Taktik von großer Einfachheit, und in den meisten Fällen war sie für die Teilnehmer profitabel und unterhaltsam. Ein Sitzstreiker schrieb: „Ich habe eine tolle Zeit, etwas Neues, etwas anderes, jede Menge Essen und Musik.“ [^199]

Der Sitzstreik bei General Motors von 1936-37 und die anderen gewaltsamen Fabrikbesetzungen dieser Zeit waren Beispiele für ein Phänomen, das wir in *Blood in the Streets* als „die Ausbeutung der Kapitalisten durch die Arbeiter“ bezeichneten. Dies war nicht die Sichtweise, die Pete Seeger in seinen traurigen Liedern zum Ausdruck brachte. Aber solange man keine Karriere als Volksliedsänger in einem Arbeiterquartier plant, ist das Wichtige nicht die allseits beliebte Interpretation, sondern die zugrunde liegende Realität. Wo immer man in der Geschichte hinschaut, gibt es im Allgemeinen eine Schicht der Rationalisierung und des Wunschdenkens, die die wahren megapolitischen Grundlagen einer systematischen Erpressung verschleiert. Wenn man die Rationalisierungen für bare Münze nimmt, ist es unwahrscheinlich, dass man verstehen wird, was wirklich vor sich geht.

## DIE ENTSCHLÜSSELUNG DER LOGIK DER ERPRESSUNG

Um die megapolitischen Implikationen der aktuellen Verschiebung hin zum Informationszeitalter zu erkennen, muss man den Schein beiseiteschieben und sich auf die eigentliche Logik der Gewalt in der Gesellschaft konzentrieren. Dies ist vergleichbar mit dem Schälen einer überreifen Zwiebel. Es könnte Ihnen Tränen in die Augen treiben, aber schauen Sie nicht weg! Wir untersuchen zuerst die Logik der Erpressung am Arbeitsplatz und erweitern dann die Analyse auf breitere Themen, die die Erstellung und den Schutz von Vermögenswerten sowie die Natur der modernen Regierung betreffen. In größerem Maße als sich die meisten Menschen vorstellen können, war der Wohlstand der Regierung, wie auch der Gewerkschaften, direkt mit der verfügbaren Hebelwirkung für Erpressung verbunden. Diese Hebelwirkung war im neunzehnten Jahrhundert viel geringer als im zwanzigsten. Im nächsten Jahrtausend wird sie nahezu auf den Nullpunkt fallen.

Die gesamte Logik von Regierungen und die Art der Macht wurden durch die Mikroverarbeitung transformiert. Dies mag auf den ersten Blick übertrieben erscheinen. Aber schauen Sie genau hin. Der Erfolg der Regierungen ging im zwanzigsten Jahrhundert Hand in Hand mit dem Erfolg der Gewerkschaften. Vor diesem Jahrhundert beanspruchten die meisten Regierungen weit weniger Ressourcen als die militanten Wohlfahrtsstaaten, an die wir uns gewöhnt haben. Ebenso waren Gewerkschaften vor diesem Jahrhundert kleine oder unwichtige Faktoren im Wirtschaftsleben. Die Fähigkeit der Arbeiter, ihre Arbeitgeber zur Zahlung von über dem Marktwert liegenden Löhnen zu zwingen, beruhte auf denselben megapolitischen Bedingungen, die es den Regierungen erlaubten, 40 Prozent oder mehr der Wirtschaftsleistung in Form von Steuern zu erheben.

### Arbeitsplatz-Erpressung vor dem zwanzigsten Jahrhundert

Der Aufstieg und Fall der Gewerkschaftserpressung der Kapitalisten lässt sich gut durch die sich verändernde Megapolitik des Produktionsprozesses erklären. Im Jahr 1776, als Adam Smith *Der Wohlstand der Nationen* veröffentlichte, waren die Bedingungen für Erpressung am Arbeitsplatz so ungünstig, dass „Zusammenschlüsse“ von Arbeitern, „um den Preis ihrer Arbeit zu erhöhen“, selten haltbar waren. Die meisten Produktionsfirmen waren winzig und familiengeführt. Industrielle Aktivitäten im größeren Maßstab begannen gerade erst zu entstehen. Dies schloss Möglichkeiten für Gewalt nicht aus, gab ihnen jedoch wenig Hebelwirkung. Tatsächlich wurden Gewerkschaften während der Zeit Smiths und weit ins 19. Jahrhundert hinein in Großbritannien, den USA und anderen Ländern nach dem Common Law allgemein als illegale Zusammenschlüsse angesehen. Adam Smith beschrieb versuchte Streiks mit diesen Worten: „Ihre üblichen Vorwände sind manchmal die hohen Preise für Lebensmittel, manchmal der große Gewinn, den ihre Meister mit ihrer Arbeit machen\.... Sie greifen immer zum lautesten Geschrei und manchmal auch zu schockierender Gewalt und Empörung.“ [^200] Dennoch ziehen die Arbeiter „sehr selten einen Vorteil aus diesen turbulenten Zusammenschlüssen“, abgesehen von „der Bestrafung oder dem Ruin des Anführers.“ [^201]

Im neunzehnten Jahrhundert wuchsen die Größenvorteile in der Industrie und die Unternehmensgröße. Dennoch arbeiteten die meisten Menschen weiterhin als Bauern oder Kleinunternehmer für sich selbst, und Bemühungen von Gewerkschaftsorganisationen, wie sie von Adam Smith beschrieben wurden, endeten „im Allgemeinen ohne Ergebnis“.[^202] Die rechtliche und politische Stellung von Gewerkschaften änderte sich erst, als die Größe der Unternehmen zunahm. Die ersten Gewerkschaften, die sich erfolgreich organisierten, waren Handwerksgewerkschaften von hochqualifizierten Arbeitern, die sich normalerweise ohne umfangreiche Gewalt organisierten. Sie neigten dazu, Lohnerhöhungen zu vereinbaren, die den Grenzkosten ihrer Ersetzung entsprachen. Bei Gewerkschaften für ungelernte Arbeitskräfte sah das anders aus. Sie neigten dazu, den Wechsel zu größeren Unternehmen auszunutzen, indem sie gerade diejenigen Branchen für die Organisationsbemühungen auswählten, die besonders anfällig für Zwang waren, entweder weil sie in größerem Maßstab arbeiteten oder weil die Art der Betriebe ihre Eigentümer der physischen Sabotage aussetzte. Dieses Muster wurde von Newcastle bis Argentinien bestätigt.[^203]

Ein frühes Beispiel für gewalttätige Arbeiterbewegungen in den Vereinigten Staaten war ein Angriff auf den Chesapeake und Ohio Kanal im Jahr 1834. Im Gegensatz zu den meisten Unternehmen im frühen 19. Jahrhundert war der C&O Kanal kein abgegrenzter und leicht zu schützender Betrieb. Ursprünglich sollte er sich über 550 Kilometer erstrecken, mit einem Höhenunterschied von 900 Metern vom unteren Potomac bis zum Norden Ohios.[^204] Ein so großes Bauvorhaben war eine schwierige Aufgabe, die nie ganz abgeschlossen wurde. Dennoch waren viele Arbeiter damit beschäftigt, es zu versuchen. Einige von ihnen erkannten bald, dass der Kanal leicht lahmgelegt werden konnte. Tatsächlich hätte der Kanal ohne regelmäßige Wartung durch Bisamratten, die unter dem Treidelpfad gruben, sabotiert werden können. Während des Betriebs konnten die Schleusen und Rinnen des Kanals leicht durch unsachgemäße Benutzung, Überschwemmungen durch heftige Regenfälle oder durch unbeaufsichtigte Boote beschädigt werden. Es war einfach für Streikende, den Wasserweg mit versunkenen Booten oder anderen Trümmern zu blockieren. Anfang 1834 führte ein Aufstand unter konkurrierenden Banden irischer Arbeiter am C&O zu einem Versuch, diesen potenziellen Sabotageakt durchzuführen und den Kanal zu übernehmen. Der Versuch scheiterte jedoch und hinterließ fünf Tote, nachdem Präsident Andrew Jackson Bundestruppen aus Ft. McHenry entsandt hatte, um die Arbeiter zu vertreiben.

Bergwerke und Eisenbahnen boten ebenfalls frühe Ziele für gewerkschaftliche Aktivitäten in Amerika. Ähnlich wie der Chesapeake-und-Ohio-Kanal waren auch sie äußerst anfällig für Sabotage. Bergwerke konnten zum Beispiel überflutet oder am Eingang blockiert werden. Allein das Töten der Maultiere, die die Erzwägen aus den unterirdischen Minen zogen, schuf eine schwierige und unangenehme Situation für die Besitzer. Ähnlich erstreckten sich Eisenbahngleisbetten über viele Meilen und konnten nur mit Schwierigkeiten bewacht werden. Es war für Gewerkschaftsschläger relativ einfach, Minen und Eisenbahnen anzugreifen und erheblichen wirtschaftlichen Schaden anzurichten. Solche Angriffe waren während der Versuche, effektive Gewerkschaften zu organisieren, an der Tagesordnung. Diese Bemühungen waren allgemein am intensivsten während Perioden, in denen die Reallohnentwicklung aufgrund von Deflation stieg. Wenn Eigentümer versuchten, Nominallöhne anzupassen, löste dies oft Proteste aus, die zu Gewalt führten. Solche Vorfälle waren in der Depression, die auf den Panikzustand von 1873 folgte, weit verbreitet.

Im Dezember 1874 brach offener Krieg in den Anthrazitkohlefeldern von Ost-Pennsylvania aus. Die Gewerkschaften organisierten eine gewalttätige Streitmacht unter dem Deckmantel einer Geheimgesellschaft namens „Ancient Order of Hibernians“. Auch bekannt als die „Molly Maguires“, nach einer irischen Revolutionärin, war diese Gruppe dafür bekannt, die Kohlefelder zu terrorisieren und jene Bergleute zu behindern, die arbeiten wollten. Ihre Mitglieder wurden wegen Sabotage und Zerstörung von Eigentum, unverblümtem Mord und Attentaten verurteilt.[^205]

Es gab auch wiederkehrende Gewalt unter den Eisenbahnangestellten. Zum Beispiel kam es im Juli 1877 zu schwerwiegenden Aufständen mit dem Ziel, das Eigentum sowohl der Pennsylvania als auch der Baltimore & Ohio Eisenbahnen zu zerstören. Die Arbeiter übernahmen die Kontrolle über Weichen, rissen Gleise heraus, versiegelten Güterbahnhöfe, machten Lokomotiven unbrauchbar, sabotierten und plünderten Züge und Schlimmeres. In Pittsburgh wurden Rundhäuser der Pennsylvania Eisenbahn in Brand gesetzt, während sich Hunderte von Menschen darin befanden. Dutzende wurden getötet, zweitausend Eisenbahnwaggons wurden verbrannt und geplündert und die Werkstatt wurde zerstört, zusammen mit einem Getreidesilo und 125 Lokomotiven. Bundestruppen griffen ein, um die Ordnung wiederherzustellen.[^206]

Obwohl diese frühen Streiks von Sozialisten und Gewerkschaftsaktivisten wohlwollend betrachtet wurden, konnten sie wenig öffentliche Unterstützung finden. Trotz der inhärenten Verwundbarkeit von Industrien wie Bergwerken und Eisenbahnen waren die allgemeinen megapolitischen Bedingungen noch nicht günstig genug für die Ausbeutung der Kapitalisten durch die Arbeiter. Der Umfang der Unternehmen war zu gering, um systematische Erpressung zu ermöglichen. Obwohl es gefährdete Branchen gab, stellten sie einen zu geringen Anteil der Bevölkerung ein, als dass die Vorteile der Zwangsmaßnahmen gegen Arbeitgeber breit geteilt werden konnten. Ohne eine solche Unterstützung waren sie untragbar, da die Eigentümer sich auf den Schutz der Regierung verlassen konnten. Während Gewerkschaften manchmal versuchten, lokale Beamte durch Einschüchterung daran zu hindern, Unterlassungsanordnungen durchzusetzen, waren auch diese Bemühungen selten erfolgreich. Selbst die gewalttätigsten Streiks wurden in der Regel innerhalb von Tagen oder Wochen durch militärische Mittel unterdrückt.

### Erpressung leicht gemacht

Eine Lehre für das Informationszeitalter ist die Tatsache, dass die Versuche der Gewerkschaften, Löhne oberhalb des marktüblichen Niveaus zu erreichen, selten erfolgreich waren, wenn die Unternehmen klein waren. Selbst Geschäftsbereiche, die eindeutig anfällig für Sabotage waren, wie Kanäle, Eisenbahnen, Straßenbahnen und Bergwerke, konnten nicht leicht kontrolliert werden. Das liegt nicht daran, dass die Gewerkschaften vor Gewalt zurückgeschreckt hätten. Ganz im Gegenteil. Gewalt wurde reichlich eingesetzt, manchmal gegen prominente Einzelpersonen. Zum Beispiel wurde in einem Fall, der in der amerikanischen Gewerkschaftsbewegung als „Rache der Bergarbeiter“ gefeiert wurde, Gouverneur Frank Steunenberg aus Idaho, der einen von Bergarbeitern initiierten Versuch, die Grundstücke von Coeur d'Alene zu blockieren, abgelehnt hatte, durch einen von der Gewerkschaft angeheuerten Auftragsmörder getötet.[^207] Doch sogar Mord und Morddrohungen reichten meist nicht aus, um eine Anerkennung der Gewerkschaften zu erzielen, bevor im zwanzigsten Jahrhundert großangelegte Fabriken und Massenproduktionsunternehmen auftauchten.

Um zu verstehen, warum sich die Umstände der Gewerkschaften im zwanzigsten Jahrhundert so veränderten, muss man die Eigenschaften der Produktionstechnologie betrachten. Mit dem schnellen Anstieg der Beschäftigung in Fabriken für Arbeiter mit geringer Ausbildung in den frühen Jahrzehnten des zwanzigsten Jahrhunderts, veränderte sich definitiv etwas. Diese Veränderung machte Unternehmen, die an der Spitze der Wirtschaft standen, besonders anfällig für Erpressung. Tatsächlich luden die physischen Eigenschaften der industriellen Technologie Arbeitnehmer fast dazu ein, Zwang einzusetzen, um die Kapitalisten unter Druck zu setzen. Betrachten Sie Folgendes:

1.  *Die meisten Industrieprodukte hatten einen hohen Anteil an natürlichen Ressourcen.* Dies führte

2.  dazu, die Produktion an eine begrenzte Anzahl von Standorten zu binden, fast so, wie Minen dort angesiedelt sein müssen, wo die Erzrohstoffe liegen. Fabriken, die in der Nähe von Verkehrszentren mit bequemem Zugang zu Zulieferern und Rohstoffen platziert wurden, hatten bedeutende Betriebsvorteile. Dies erleichterte es Zwangsorganisationen wie Regierungen und Gewerkschaften, einige dieser Vorteile für sich zu nutzen.

3.  *Steigende Skaleneffekte führten zu sehr großen Unternehmen.* Fabriken zu Beginn des neunzehnten Jahrhunderts waren relativ klein. Aber als die Skaleneffekte mit der Einführung der Fließbandproduktion im zwanzigsten Jahrhundert zunahmen, stiegen Größe und Kosten der Anlagen, die im Vordergrund des Produktionsprozesses standen, rasch an. Dies machte sie in vielerlei Hinsicht zu einfacheren Zielen. Zum Beispiel gehen signifikante Skaleneffekte oft Hand in Hand mit langen Produktzyklen. Lange Produktzyklen sorgen für stabilere Märkte. Dies wiederum lädt dazu ein, Unternehmen räuberisch ins Visier zu nehmen, da es impliziert, dass es langfristige Vorteile zu erlangen gibt.

4.  *Die Anzahl der Wettbewerber in führenden Branchen fiel stark.* Es war nicht ungewöhnlich in der industriellen Ära, dass nur eine Handvoll Firmen um Milliarden-Dollar-Märkte konkurrierten. Dies trug dazu bei, diese Firmen zum Ziel für Gewerkschaftserpressung zu machen. Es ist viel einfacher, fünf Firmen anzugreifen als fünftausend. Die hohe Konzentration der Industrie war selbst ein Faktor, der Erpressung begünstigte. Dieser Vorteil verstärkte sich selbst, weil die Firmen, die zu Monopollohnzahlungen gezwungen wurden, wahrscheinlich nicht mit harter Konkurrenz von anderen Firmen konfrontiert wurden, die nicht ebenfalls mit über dem Marktdurchschnitt liegenden Arbeitskosten belastet waren. Gewerkschaften konnten daher einen erheblichen Teil der Gewinne solcher Unternehmen absorbieren, ohne sie sofort in den Bankrott zu treiben. Offensichtlich hätten Arbeitnehmer, wenn Arbeitgeber routinemäßig pleite gegangen wären, sobald sie gezwungen wurden, über dem Marktdurchschnitt liegende Löhne zu zahlen, wenig davon gehabt, sie dazu zu zwingen.

5.  *Die Kapitalanforderungen für freie Investitionen stiegen in Übereinstimmung mit der Unternehmensgröße.* Dies erhöhte nicht nur die Verletzlichkeit des Kapitals und vergrößerte die Kosten von Werkschließungen; es machte es auch immer unwahrscheinlicher, dass ein modernes Werk von einer einzelnen Person oder Familie besessen werden konnte, außer durch Erbschaft von jemandem, der das Geschäft in kleinerem Maßstab gestartet hatte. Um die enormen Kosten für die Ausrüstung und den Betrieb einer großen Fabrik zu finanzieren, musste das Vermögen von Hunderten oder Tausenden von Menschen auf den Kapitalmärkten gebündelt werden. Dies erschwerte es den zerstreuten und fast anonymen Eigentümern zunehmend, ihr Eigentum zu verteidigen. Sie hatten kaum eine andere Wahl, als sich auf professionelle Manager zu verlassen, die selten mehr als eine kaum messbare Menge der ausstehenden Aktien des Unternehmens hielten. Die Abhängigkeit von untergeordneten Managern schwächte den Widerstand der Firmen gegen Erpressung. Den Managern fehlten starke Anreize, Leib und Leben zu riskieren, um das Eigentum der Firma zu schützen. Ihre Bemühungen entsprachen selten der Art von Militanz, die häufig bei Eigentümern von Spirituosenläden und anderen kleinen Geschäften zu beobachten ist, wenn ihr Eigentum bedroht wird.

6.  *Die Zunahme der Firmengröße bedeutete auch, dass mehr Menschen insgesamt in weniger Unternehmen beschäftigt waren als je zuvor.* In einigen Fällen fanden zehntausende von Arbeitnehmern Arbeit in einem einzigen Unternehmen. In militärischer Hinsicht waren die Firmeninhaber und -leiter stark in der Unterzahl im Vergleich zu den Beschäftigten in untergeordneten Positionen. Verhältnisse von dreißig zu eins oder weniger waren üblich. Dieser Nachteil stieg mit der Unternehmensgröße, da große Mengen von Arbeitnehmern, die zusammenkamen, Gewalt auf anonyme Weise leichter einsetzen konnten. Unter solchen Bedingungen ist es unwahrscheinlich, dass die Arbeiter irgendeinen bedeutsamen Kontakt oder Beziehungen zu den Eigentümern der Fabrik gehabt hätten. Der anonyme Charakter dieser Beziehungen erleichterte es den Arbeitern zweifellos, die Bedeutung der Eigentumsrechte der Eigentümer zu ignorieren.

7.  *Die Beschäftigung einer großen Anzahl von Menschen in einer kleinen Anzahl von Unternehmen war ein weit verbreitetes soziales Phänomen.* Dies verstärkte die Megapolitikvorteile der Gewerkschaften im Vergleich zum 19. Jahrhundert in Amerika, als die meisten Menschen selbstständig oder in kleinen Firmen arbeiteten. 1940 arbeiteten 6 Prozent der amerikanischen Arbeiterschaft als Angestellte.[^208] Als Folge davon breitete sich die Unterstützung für die Erpressung zur Lohnerhöhung unter einer großen Anzahl von Menschen aus, die glaubten, dass sie davon profitieren könnten. Dies wurde durch eine Studie von 1938-39 mit 1.700 Menschen in Akron, Ohio, zum Firmeneigentum illustriert. Die Umfrage ergab, dass 68 Prozent der CIO-Gummiarbeiter sehr wenig oder gar kein Verständnis für das Konzept des Firmeneigentums hatten, während nur ein Prozent in die Kategorie „starke Befürworter von Firmeneigentumsrechten“ eingeordnet wurden.[^209] Andererseits fiel kein einziger Geschäftsmann, nicht einmal ein kleiner Eigentümer, in die gleiche Kategorie der „starken Opposition gegen das Firmeneigentum; 94 Prozent erhielten Bewertungen im Bereich der extrem hohen Unterstützung für die Eigentumsrechte“.[^210]

8.  *Die Fließbandtechnologie war von Natur aus sequenziell.* Die Tatsache, dass der gesamte Produktionsprozess von der Bewegung und Montage von Teilen in einer festen Reihenfolge abhängig war, schuf zusätzliche Anfälligkeiten für Störungen. Tatsächlich war das Fließband wie eine Eisenbahn innerhalb der Fabrikmauern. Wenn die Strecke blockiert werden oder die Verfügbarkeit eines einzelnen Teils unterbrochen werden konnte, wurde der gesamte Produktionsprozess zum Stillstand gebracht.

9.  *Die Fließbandtechnologie standardisierte die Arbeit.* Dies reduzierte die Schwankungen im Output für Personen mit unterschiedlichen Fähigkeiten, die mit denselben Werkzeugen arbeiteten. Ein wesentliches Ziel der Fabrikplanung bestand darin, ein System zu schaffen, in dem ein Genie und ein Idiot in aufeinanderfolgenden Schichten am Fließband dasselbe Produkt herstellen würden. Was man als „dumme“ Maschinen bezeichnen könnte, wurde so konzipiert, dass sie nur eine Art von Output liefern konnte. Dies machte es selbst für den Käufer eines Cadillacs überflüssig, sich nach der Identität der Fließbandarbeiter zu erkundigen, die sein Fahrzeug herstellten. Alle Produkte sollten gleich sein, unabhängig von den Unterschieden in Fähigkeiten und Intelligenz zwischen den Arbeitern, die sie hergestellt hatten.

Die Tatsache, dass ungelernte Arbeiter an der Montagelinie dasselbe Produkt herstellen konnten wie qualifiziertere Personen, trug zur egalitären Agenda bei, indem sie den Eindruck erweckte, dass die wirtschaftlichen Beiträge von allen gleich seien. Unternehmerisches Können und geistige Anstrengung schienen weniger wichtig. Der Zauber der modernen Produktion schien in den Maschinen selbst zu liegen. Auch wenn sie tatsächlich nicht von jedem entworfen werden können, schienen sie dennoch für fast jeden intellektuell zugänglich zu sein. Dies verlieh der Fiktion mehr Plausibilität, dass ungelernte Arbeit von Fabrikbesitzern „ausgebeutet“ werde, die man ohne Verlust für irgendeine andere Partei, abgesehen von ihnen selbst, aus der Gleichung entfernen könnte. „Wir haben gelernt, dass wir die Fabrik übernehmen können“, wie es ein Streikender bei GM formulierte. „Wir wussten schon, wie man sie betreibt. Wenn General Motors nicht aufpasst, werden wir eins und eins zusammenzählen.“ [^211]

Die Merkmale der industriellen Technologie führten einheitlich zur Gründung von Gewerkschaften, um die Anfälligkeit für Erpressungen auszunutzen, sowie zu größeren Regierungen, die sich an den hohen Steuern bereicherten, die große Industrieanlagen zahlen mussten. Dies passierte nicht nur ein oder zwei Mal, sondern überall dort, wo groß-industrielle Produktion Einzug hielt. Immer wieder entstanden Gewerkschaften, die Gewalt anwendeten, um deutlich über das Marktniveau hinausgehende Löhne zu erzielen. Sie waren dazu in der Lage, weil industrielle Fabriken in der Regel teuer, aufwändig, unbeweglich und kostspielig waren. Sie konnten kaum versteckt werden. Sie konnten nicht verlegt werden. Jeder Moment, in dem sie nicht in Betrieb waren, bedeutete, dass ihre enormen Kosten nicht amortisiert wurden.

All dies machte sie zu leichten Zielen für erzwungene Abzockereien, eine Tatsache, die in der Geschichte der Gewerkschaften viel offensichtlicher ist, als die vorherrschende Ideologie des zwanzigsten Jahrhunderts es glauben lässt. Der bekannte Ökonom Henry Simons formulierte das Problem im Jahr 1944:

„Arbeitnehmerorganisationen ohne große Macht zur Zwangsausübung und Einschüchterung sind eine unrealistische Abstraktion. Gewerkschaften haben jetzt solche Macht; sie haben sie immer gehabt und werden sie immer haben, solange sie in ihrer derzeitigen Form bestehen. Wenn die Macht klein oder unsicher ist, muss sie offen und umfassend ausgeübt werden; wenn sie groß und unangefochten ist, wird sie wie die Macht der Regierung, selbstbewusst gehalten, respektvoll angesehen und selten auffällig gezeigt.“ [^212]

So präzise Simons Analyse auch war, er lag dennoch bei einem entscheidenden Punkt falsch.

Er nahm an, dass Gewerkschaften „immer über das verfügen werden“, was er als „große Macht zu Zwang und Einschüchterung“ beschrieb. Tatsächlich schwinden die Gewerkschaften jedoch nicht nur in den USA und Großbritannien, sondern auch in anderen ausgereiften Industriegesellschaften. Der Grund für ihr Verschwinden, den Simons übersehen hat und den selbst viele Gewerkschaftsorganisatoren nicht verstehen, liegt darin, dass der Übergang zu einer Informationsgesellschaft die megapolitischen Bedingungen auf entscheidende Weise verändert hat und die Sicherheit von Eigentum stark erhöht hat. Die Mikrotechnologie hat bereits begonnen, die Erpressung, die den Wohlfahrtsstaat unterstützt, zu untergraben, da sie selbst im kommerziellen Bereich völlig andere Anreize schafft als die industrielle Periode.

1.  *Die Informationstechnologie hat einen vernachlässigbaren Anteil an natürlichen Ressourcen.* Sie vermittelt wenige oder gar keine inhärenten Standortvorteile. Die meisten Informationstechnologien sind hochgradig mobil. Da sie unabhängig vom Ort funktionieren können, erhöht die Informationstechnologie die Mobilität von Ideen, Personen und Kapital. General Motors kann seine drei Montagelinien in Flint, Michigan, nicht einfach einpacken und wegfliegen. Ein Softwareunternehmen kann das. Die Eigentümer können ihre Algorithmen auf tragbare Computer herunterladen und mit dem nächsten Flugzeug abhauen. Solche Unternehmen haben auch einen zusätzlichen Anreiz, hohe Steuern oder Gewerkschaftsforderungen nach Monopollöhnen zu entkommen. Kleinere Firmen neigen dazu, mehr Wettbewerber zu haben. Wenn Sie Dutzende oder sogar Hunderte von Wettbewerbern haben, die Ihre Kunden locken, können Sie es sich nicht leisten, Politikern oder Ihren Mitarbeitern viel mehr zu bezahlen, als sie tatsächlich wert sind. Wenn Sie alleine versuchen würden, dies zu tun, wären Ihre Kosten höher als die Ihrer Wettbewerber und Sie würden pleite gehen. Das Fehlen von signifikanten Betriebsvorteilen an einem bestimmten Ort bedeutet, dass Zwangsorganisationen, wie Regierungen und Gewerkschaften, unweigerlich weniger Hebelwirkung haben werden, um einige dieser Vorteile für sich selbst auszubeuten.

2.  *Die Informationstechnologie senkt die Unternehmensgröße.* Dies führt zu kleineren Firmen und damit zu einer größeren Anzahl von Konkurrenten. Der erhöhte Wettbewerb reduziert das Potenzial für Erpressung, indem die Anzahl der Ziele erhöht wird, die physisch kontrolliert werden müssen, um Löhne oder Steuersätze über Wettbewerbsniveaus anzuheben. Der drastische Rückgang der durchschnittlichen Unternehmensgröße, der durch die Informationstechnologie ermöglicht wurde, hat bereits die Anzahl der Personen reduziert, die in untergeordneten Positionen beschäftigt sind. In den USA beispielsweise lassen weit verbreitete Schätzungen vermuten, dass 1996 bis zu 30 Millionen Personen alleine in ihren eigenen Unternehmen gearbeitet haben. Offensichtlich neigen diese 30 Millionen Menschen kaum dazu gegen sich selbst zu streiken. Es ist nur unwesentlich weniger plausibel, dass die zusätzlichen Millionen, die in kleinen Unternehmen mit einer Handvoll Angestellten arbeiten, versuchen würden, ihre Arbeitgeber zur Zahlung von über dem Marktdurchschnitt liegenden Löhnen zu erpressen. Im Informationszeitalter wird den Arbeitnehmern, die ihre Löhne durch Erpressung erhöhen wollen, der militärische Vorteil der überwältigenden Zahl fehlen, der sie in der Fabrik zu einer furchteinflößenden Macht gemacht hat. Je weniger Personen in einem Unternehmen beschäftigt sind, desto geringer sind die Möglichkeiten für anonyme Gewalt. Aus diesem einen Grund allein würden zehntausend Arbeiter, die auf fünfhundert Unternehmen verteilt sind, eine geringere Gefahr für das Eigentum dieser Unternehmen darstellen als zehntausend Arbeiter in einem einzigen Unternehmen, selbst wenn das Verhältnis von Arbeitnehmern zu Eigentümern/Managern genau gleich wäre.

3.  *Die sinkende Betriebsgröße bedeutet auch, dass Bemühungen um überdurchschnittliche Löhne weniger wahrscheinlich breite gesellschaftliche Unterstützung finden, wie dies in der Industriezeit der Fall war.* Gewerkschaften, die versuchen, Arbeitgeber abzuzocken, sind viel eher in der Situation der Kanalarbeiter, Eisenbahnangestellten und Bergarbeiter des neunzehnten Jahrhunderts. Selbst wenn einige Firmen mit großen Betriebsgrößen als Überbleibsel aus dem Industriezeitalter verbleiben, tun sie dies in einem Kontext von weit verbreiteter Beschäftigung in kleinen Firmen. Die Überzahl von kleinen Firmen und Kleinbetrieben lässt auf eine größere gesellschaftliche Unterstützung für Eigentumsrechte schließen, selbst wenn der Wunsch, Einkommen umzuverteilen, unverändert bleibt.

4.  *Die Informationstechnologie senkt die Kapitalkosten, was auch dazu neigt, den Wettbewerb zu erhöhen, indem sie Unternehmertum fördert und mehr Menschen die Möglichkeit gibt, unabhängig zu arbeiten.* Geringere Kapitalanforderungen reduzieren nicht nur die Barrieren für den Markteinstieg; sie reduzieren auch die „Ausstiegsbarrieren“. Mit anderen Worten, sie implizieren, dass Firmen wahrscheinlich weniger Vermögen im Vergleich zu ihrem Einkommen haben und daher weniger die Fähigkeit haben, Verluste zu verkraften. Sie werden nicht nur weniger Kredite bei den Banken aufnehmen müssen; Unternehmen im Informationszeitalter werden wahrscheinlich auch weniger Sachwerte besitzen, die sie erfassen müssen.

5.  *Die Informationstechnologie verkürzt den Produktlebenszyklus.* Dies führt zu einer schnelleren Produktobsoleszenz. Auch dies tendiert dazu, etwaige Gewinne, die durch das Erpressen von über dem Marktniveau liegenden Löhnen erzielt werden könnten, kurzlebig zu machen. In stark wettbewerbsorientierten Märkten können überhöhte Löhne direkt zu einem raschen Arbeitsplatzverlust und sogar zum Bankrott des Unternehmens führen. Nach vorübergehend höheren Löhnen zu greifen, auf Kosten der Sicherheit des eigenen Arbeitsplatzes, ist vergleichbar mit dem Verbrennen der eigenen Möbel, um das Haus um einige Grad wärmer zu machen.

6.  *Informationstechnologie ist nicht sequenziell, sondern simultan und verstreut.* Anders als die Fließbandarbeit kann Informationstechnologie mehrere Prozesse gleichzeitig verarbeiten. Sie verteilt Arbeitsvorgänge auf Netzwerken, ermöglicht Redundanz und Substitution zwischen Arbeitsstationen, die sich zu Tausenden oder sogar zu Millionen an jedem Ort der Erde befinden können. Bei einer zunehmenden Anzahl von Aktivitäten können Menschen zusammenarbeiten, ohne jemals physischen Kontakt miteinander zu haben. Mit fortschrittlicher virtueller Realität und Videokonferenzen wird die Tendenz zur Verbreitung von Funktionen und Telearbeit beschleunigen. Das entspricht dem Äquivalent des Informationszeitalters von „Outsourcing“, das die Macht der mittelalterlichen Zünfte brach. Die Tatsache, dass immer weniger Menschen zusammen in verrauchten Fabriken arbeiten, nimmt nicht nur einen wichtigen Vorteil weg, den Arbeiter bei der Erpressung der Kapitalisten genossen haben, sondern macht es auch immer schwieriger, die Art von Erpressung, die am Arbeitsplatz akzeptabel war, von Ausbeutung zu unterscheiden. Bisher durften nur Personen, die zusammengearbeitet und von einer Firma an einem gemeinsamen Ort angestellt wurden, Gewalt anwenden, um ihre Einkommen zu erhöhen. Wenn der „Arbeitsplatz“ nicht als zentrale Lage existiert und die meisten Funktionen an Subunternehmer und Telearbeiter ausgelagert sind, wird es kaum etwas geben, um ihre Bemühungen, Geld von ihren Kunden oder „Arbeitgebern“ zu erpressen, von einer systematischen Ausbeutung zu unterscheiden.\
    Ist zum Beispiel ein Telearbeiter, der zusätzliches Geld verlangt unter der Drohung, die Computer des Unternehmens mit einem Virus zu infizieren, ein streikender Arbeitnehmer? Oder ist er ein Internet-Gangster?\
    Ob er das eine oder andere ist, macht keinen Unterschied. Die Reaktion der betroffenen Unternehmen wird wahrscheinlich in jedem Fall ähnlich sein. Technische Lösungen gegen Informationssabotage, wie verbesserte Verschlüsselung und Netzwerksicherheit, die die Gefahr eines externen Hackers beantworten sollten, könnten auch die Möglichkeiten des unzufriedenen Mitarbeiters oder Subunternehmers, Schäden bei Parteien zu verursachen, mit denen er regelmäßig oder sporadisch handelt, unwesentlich machen. Natürlich könnte man vorschlagen, dass der Arbeiter oder Telearbeiter immer ins Büro zurückkehren und dort einen traditionelleren Streik durchführen könnte. Aber selbst das könnte im Informationszeitalter nicht so einfach sein, wie es scheinen mag. Die Möglichkeit der Informationstechnologie, räumliche Begrenzungen zu überwinden und wirtschaftliche Funktionen zu verteilen, bedeutet, dass zum ersten Mal Arbeitgeber und Arbeitnehmer nicht einmal im gleichen Rechtssystem ansässig sein müssen. Hier sprechen wir nicht nur über die Unterschiede zwischen den Stadtteilen Mayfair und Peckham, sondern auch über Arbeitgeber in Bermuda und Telearbeiter in Neu-Delhi.\
    Wenn sich die Inder von den Berichten über die großen GM-Streiks von 1936-37 anstecken ließen und beschließen, auf die Bermudas zu reisen, um Streikposten zu stellen, könnten sie bei ihrer Ankunft überhaupt kein Büro vorfinden. Chiat/Day, eine große Werbefirma, hat bereits begonnen, ihre Hauptverwaltung zu zerlegen. Ihre Mitarbeiter oder Subunternehmer bleiben in Kontakt durch Anrufweiterleitung und das Internet. Wenn es notwendig wird, Talentteams zu treffen, um die Arbeit an Projekten zu koordinieren, mieten sie Hoteltagungsräume. Wenn das Projekt vorbei ist, checken sie aus. Die Tatsache, dass die Mikroverarbeitung dazu beiträgt, den Produktionsprozess von der starren Abfolge des Fließbandes zu befreien und zu zerstreuen, verringert den Einfluss, den Zwangsinstitutionen wie Gewerkschaften und Regierungen früher hatten, erheblich. Wäre das Fließband wie eine Eisenbahn innerhalb der Fabrikmauern, die leicht durch einen Sitzstreik erobert werden könnte, so ist der Cyberspace ein unbegrenzter Bereich ohne physische Existenz. Er kann nicht mit Gewalt besetzt oder erpresst werden. Die Position der Arbeitnehmer, die Gewalt als Hebel nutzen möchten, um ein höheres Einkommen zu erpressen, wird im Informationszeitalter viel schwächer sein, als es bei den Sitzstreikern bei General Motors im Jahre 1936-37 der Fall war.

7.  *Mikroprozessoren individualisieren die Arbeit, Industrietechnik standardisiert die Arbeit.* Wer dieselben Werkzeuge benutzt, produziert dasselbe Ergebnis. Die Mikrotechnologie hat begonnen, „dumme“ Maschinen durch intelligentere Technologie zu ersetzen, die eine stark variable Leistung ermöglicht. Die erhöhte Variabilität der Ergebnisse für Personen, die dieselben Werkzeuge benutzen, hat tiefgreifende Auswirkungen, die wir in den kommenden Kapiteln untersuchen werden. Unter den wichtigeren Aspekten ist die Tatsache, dass bei variablem Output auch die Einkommen variieren. Der größte Teil des Werts in Bereichen, in denen die Fähigkeiten variieren, wird tendenziell von einer kleinen Anzahl von Personen geschaffen. Dies ist ein häufiges Merkmal der wettbewerbsintensivsten Märkte. Das ist beispielsweise im Sport offensichtlich. Millionen von jungen Menschen weltweit spielen auf verschiedenen Ebenen Fußball. Aber 99 Prozent des Geldes, das ausgegeben wird, um Fußballspiele anzusehen, werden gezahlt, um die Leistungen eines winzigen Bruchteils der Gesamtzahl der Spieler zu sehen. Gleiches gilt für die Welt der Schauspielerei, die voller angehender Schauspieler und Schauspielerinnen ist. Dennoch werden nur wenige Stars. Ebenso werden jährlich zehntausende von Büchern veröffentlicht. Aber das meiste Geld aus Tantiemen wird an eine kleine Anzahl von Bestseller-Autoren gezahlt, die ihre Leser wirklich unterhalten können. Unglücklicherweise gehören wir nicht zu ihnen.

Ein weiteres Hindernis für Erpressung ist die Tatsache, dass die Leistung der Personen, die dieselben Geräte benutzen, sehr unterschiedlich ist. Sie verursacht ein großes Verhandlungsproblem darüber, wie der Gewinn geteilt werden sollte. Wo ein relativ kleiner Teil der an einer bestimmten Tätigkeit teilnehmenden Personen den größten Wert schafft, ist es mathematisch nahezu unmöglich, dass sie durch ein erzwungenes Ergebnis, das den Durchschnitt der Einkommen darstellt, bessergestellt sein könnten. Ein Softwareprogrammierer könnte einen Algorithmus zur Steuerung eines Roboters entwickeln, dessen Wert in die Millionen geht. Ein anderer, der mit identischer Ausstattung arbeitet, könnte ein Programm schreiben, das nichts wert ist. Der produktivere Programmierer ist nicht eher bereit, sein Einkommen an das seines Kollegen zu binden, als dass Tom Clancy zustimmt, seine Buchtantiemen mit unseren zu mitteln.

Schon in der Anfangsphase der Informationsrevolution ist es viel offensichtlicher als noch 1975, dass Fähigkeiten und geistige Fertigkeiten entscheidende Variablen für die Wirtschaftsleistung sind. Damit ist die einst stolze Rationalisierung für die Erpressung der Kapitalisten durch die Arbeiter, die während der Industrieperiode vorherrschte, bereits hinfällig geworden. Die Fantasie, dass ungelernte Arbeit tatsächlich den Wert schafft, der scheinbar in einem unverhältnismäßigen Anteil von den Kapitalisten und Unternehmern eingesackt wird, ist bereits ein Anachronismus. Im Falle der Informationstechnologie ist das nicht einmal mehr eine plausible Fiktion. Wenn sich ein Programmierer hinsetzt, um einen Code zu schreiben, besteht eine direkte Verbindung zwischen seinen Fähigkeiten und seinem Produkt, als dass man sich über die Verantwortlichkeiten im Unklaren sein könnte. Es ist unbestreitbar offensichtlich, dass ein Analphabet oder Halbanalphabet keinen Computer programmieren könnte. Es ist daher ebenso offensichtlich, dass jeglicher Wert der von anderen Leuten erstellten Programme nicht von ihm gestohlen worden sein kann. Deshalb hört man jetzige Schreie über „Ausbeutung“ von Arbeitern hauptsächlich unter Hausmeistern.

Die Informationstechnologie macht deutlich, dass das Problem, dem Personen mit geringer Qualifikation gegenüberstehen, nicht darin besteht, dass ihre Produktionskapazitäten unfair ausgenutzt werden; sondern vielmehr die Befürchtung, dass sie möglicherweise nicht in der Lage sind, einen echten wirtschaftlichen Beitrag zu leisten. Wie Kevin Kelly in *Out Of Control* vorschlägt, könnte der „Emporkömmling“ eines Auto-Unternehmens des Informationszeitalters das Produkt von „einem Dutzend Menschen“ sein, die die meisten ihrer Teile auslagern und dennoch Autos produzieren, die sorgfältiger auf die Wünsche des Käufers zugeschnitten sind, als alles, was bisher aus Detroit oder Tokio zu sehen war: „Autos, jedes einzelne auf den Kunden zugeschnitten, werden von einem Netzwerk von Kunden bestellt und verschickt, sobald sie fertig sind. Formen für die Karosserie des Autos werden schnell von computergesteuerten Lasern geformt und mit Designs versehen, die durch Kundenreaktionen und Zielmarketing entstanden sind. Eine flexible Reihe von Robotern montiert die Autos. Die Roboterreparatur und -verbesserung wird an ein Roboterunternehmen ausgelagert.“ [^213]

### „Werkzeuge mit einer Stimme“

Immer mehr kann unqualifizierte Arbeit von automatisierten Maschinen, Robotern und Computersystemen, wie digitalen Assistenten, erledigt werden. Als Aristoteles Sklaven als „Werkzeuge mit einer Stimme“ bezeichnete, sprach er von Menschen. In nicht allzu ferner Zukunft werden „Werkzeuge mit einer Stimme“, wie die Dschinns aus dem Märchen, in der Lage sein zu sprechen und Anweisungen zu befolgen, und sogar komplexe Aufgaben zu bewältigen. Die rasch zunehmende Rechenleistung hat bereits eine Reihe von primitiven Anwendungen der Spracherkennung hervorgebracht, wie Freisprechtelefone und Computer, die mathematische Berechnungen nach verbalen Anweisungen durchführen. Computer, die Sprache in Text umwandeln, wurden bereits Ende 1996 auf den Markt gebracht, während wir dies schreiben. Da die Fähigkeiten zur Mustererkennung verbessert werden, werden Computer, die mit Sprachsynthesizern vernetzt sind, über Netzwerke zahlreiche Funktionen durchführen, die früher von Menschen übernommen wurden, die als Telefonoperator, Sekretäre, Reiseagenten, Verwaltungsassistenten, Schachmeister, Schadensregulierer, Komponisten, Aktienhändler, Cyberkrieg-Spezialisten, Waffenanalysten oder sogar gewiefte Verführerinnen tätig waren, die die Anrufe von 0190-Nummern beantwortet haben.

Michael Mauldin von der Carnegie-Mellon-Universität hat eine künstliche Persönlichkeit namens Julia programmiert, die in der Lage ist, fast jeden, mit dem sie im Internet spricht, zu täuschen. Presseberichten zufolge ist Julia eine „schlagfertige Dame, die ihr Leben in einem Rollenspiel im Internet verbringt. Sie ist schlau, witzig und liebt es zu flirten. Darüber hinaus ist sie eine Eishockey-Expertin und kann im Handumdrehen den perfekten sarkastischen Kommentar abgeben. Julia ist jedoch keine Frau. Sie ist ein Bot, eine künstliche Intelligenz, die nur im Äther des Internets existiert.“ [^214] Der erstaunliche Fortschritt, der bereits in der Programmierung von künstlicher Intelligenz und digitalen Dienern gemacht wurde, lässt kaum Zweifel daran, dass noch viele praktische Anwendungen zu erwarten sind. Dies hat bedeutende megapolitische Konsequenzen.

### Das Individuum als Ensemble

Die Entwicklung von „Werkzeugen mit einer Stimme“ für vielfältige Anwendungen schafft die Möglichkeit, dass sich das Individuum auf mehrere gleichzeitige Aktivitäten verteilt. Das Individuum wird nicht mehr einzigartig sein, sondern potenziell ein Ensemble aus Dutzenden oder vielleicht sogar Tausenden von Aktivitäten, die durch intelligente Agenten durchgeführt werden. Dies wird nicht nur die Produktivität der talentiertesten Individuen erheblich steigern; es macht das souveräne Individuum potenziell auch militärisch weitaus schlagkräftiger, als es das Individuum je zuvor war.

Nicht nur wird ein Individuum offensichtlich seine Aktivitäten durch den Einsatz einer im Grunde unbegrenzten Anzahl von intelligenten Agenten vervielfachen können. Er oder sie wird sogar nach dem Tod handeln können. Zum ersten Mal wird ein Individuum in der Lage sein, komplizierte Aufgaben fortzusetzen, auch wenn es biologisch tot ist. Es wird nicht mehr möglich sein, dass entweder ein Kriegsgegner oder ein Verbrecher die Fähigkeit eines Individuums zur Vergeltung völlig auslöschen kann, indem er es tötet. Dies ist eine der revolutionärsten Innovationen in der Logik der Gewalt in der gesamten Geschichte.

### Einsichten für das Informationszeitalter

Die größten Veränderungen im Leben betreffen Variablen, die niemand beobachtet. Anders ausgedrückt, wir nehmen Variablen für selbstverständlich hin, die über Jahrhunderte oder sogar Hunderte von Generationen nur wenig geschwankt haben. Für den größten Teil der Geschichte, wenn nicht sogar der menschlichen Existenz, hat das Gleichgewicht zwischen Schutz und Erpressung innerhalb einer schmalen Marge geschwankt, wobei die Erpressung stets die Oberhand behielt. Jetzt steht eine Veränderung bevor. Die Informationstechnologie bereitet den Boden für eine grundlegende Verschiebung in den Faktoren, die die Kosten und Belohnungen von Gewaltanwendung bestimmen. Die Tatsache, dass intelligente Agenten verfügbar sein werden, um Gewaltanwendung zu untersuchen und vielleicht in der einen oder anderen Weise gegen diejenigen, die Gewalt initiieren, zu reagieren, ist nur ein Hinweis auf diese neue Aussicht auf Schutz. Vor 25 Jahren wäre die folgende Aussage nicht mehr als das Geschwafel eines Exzentrikers gewesen: „Wenn du mich tötest, werde ich das Geld von deinen Bankkonten fegen und es an Wohltätigkeitsorganisationen in Nepal spenden.“ Nach der Jahrtausendwende mag das nicht mehr der Fall sein. Ob es sich als praktische Bedrohung erweisen würde, würde von Faktoren wie Zeit und Ort bestimmt. Aber selbst wenn die Konten des potenziellen Übeltäters undurchdringbar wären, gäbe es sicherlich andere kostspielige Unannehmlichkeiten, die eine Armee von intelligenten Agenten als Vergeltung für ein Verbrechen verhängen könnte. Denken Sie mal darüber nach.

### Neue Alternativen von Schutz

Das ist lediglich einer von vielen Wegen, den Schutz zu verbessern, die durch die Technologie des Informationszeitalters ermöglicht werden. Die meisten dieser Wege tendieren dazu, jenes nahezu monopolistische Anrecht auf Schutz und Erpressung, das Regierungen in den letzten zwei Jahrhunderten genossen haben, zu untergraben. Auch ohne den neuen technologischen Schnickschnack gab es stets Alternativen für Schutz, die nicht alle dazu tendiert haben von der Regierung monopolisiert zu werden.

Eine Person, die sich bedroht fühlt, könnte einfach davonlaufen. Als die Welt noch jung war und die Horizonte offen, wurde die Option der Flucht häufig genutzt. Wenn Menschen sich um Verluste durch Diebstahl oder Vandalismus sorgen, können sie sich dazu entscheiden, Versicherungspolicen abzuschließen, um solche Risiken abzusichern. Verwünschungen und Zaubersprüche, obwohl schwache Formen des Schutzes, haben auch Leben gerettet und Diebstahlhandlungen abgewehrt. Sie funktionieren manchmal in Gesellschaften, in denen die Räuber abergläubisch sind. Wertgegenstände können auch geschützt werden, indem man sie verbirgt. Dies ist manchmal eine effektive Methode, wenn sie angewendet werden kann. Vermögenswerte können vergraben, mit Schlössern gesichert, hinter hohen Mauern platziert und mit Sirenen und elektronischen Überwachungsgeräten ausgestattet werden. Das Verstecken von Personen und Eigentum war jedoch nicht immer praktikabel.

Trotz aller Vielfalt an Schutzmaßnahmen, die historisch eingesetzt wurden, dominiert eine Methode alle anderen - die Fähigkeit, Gewalt mit Gewalt zu übertreffen, eine größere Kraft aufzubringen, um jeden zu überrumpeln, der Sie angreift oder Ihr Eigentum stiehlt. Die Frage ist, an wen man sich für einen solchen Dienst wenden kann und wie man jemanden motivieren kann, sein Leben und seine Gliedmaßen zu riskieren, um einen bei der Bekämpfung von Schlägern zu helfen, die Gewalt gegen einen initiieren könnten. Manchmal haben nahe Verwandte den Hilferuf beantwortet. Manchmal haben Stammes- und Clan-basierte Gruppen als inoffizielle Polizei gedient, die auf Gewalt gegen ihre Mitglieder mit Blutfehden reagierten. Manchmal wurden Söldner oder private Wachen zur Abwehr von Angriffen eingesetzt, aber nicht immer auf so nützliche Weise, wie man es sich wünschen würde. Die neuen, intelligenten Agenten des Informationszeitalters, auch wenn ihre Aktivitäten größtenteils auf den Cyberspace beschränkt sein werden, bieten eine neue Alternative. Ihre Loyalitäten, anders als die der Söldner, privaten Wächter und sogar entfernten Cousins, sind unbestreitbar.

### Die Paradoxien der Macht

Der Einsatz von Gewalt zur Abwehr von Gewalt ist voller Paradoxien. Unter den bisher existierenden Bedingungen hätte jede Gruppe oder Organisation, die man zur erfolgreichen Verteidigung seines Lebens und Vermögens vor Angriffen anwerben konnte, notwendigerweise auch die Fähigkeit gehabt, einem beides zu entziehen. Das ist ein Nachteil, für den es keine einfache Lösung gibt. Normalerweise könnte man den Wettbewerb dazu nutzen, Anbieter eines wirtschaftlichen Dienstes davon abzuhalten, die Wünsche seiner Kunden zu ignorieren. Aber wo Gewalt eine Rolle spielt, hat direkter Wettbewerb oft perverse Auswirkungen. In der Vergangenheit hat dies in der Regel zu erhöhter Gewalt geführt. Wenn zwei potentielle Schutzorganisationen ihre Streitkräfte aussenden, um einander zu verhaften, gleicht das Ergebnis mehr einem Bürgerkrieg als Schutz. Wenn man Schutz vor Gewalt sucht, möchte man normalerweise nicht die Gewalt steigern, sondern sie unterdrücken. Und zwar unter Bedingungen, die es nicht zulassen, dass die Kunden, die in erster Linie für den Schutzdienst zahlen, ausgeplündert werden.

> „...während der Zeit, in der Menschen ohne eine gemeinsame Macht leben, die sie alle in Ehrfurcht hält, befinden sie sich in dem Zustand, den man Krieg nennt: und ein solcher Krieg bedeutet jeder gegen jeden, wobei die Menschen ohne irgendeine andere Sicherheit leben als die, die ihre eigene Stärke und ihre eigenen Erfindungen ihnen geben können.“ - Thomas Hobbes

### Monopol und Anarchie

Deshalb war Anarchie, oder „der Krieg von jedem gegen jeden“, wie Hobbes es beschrieb, selten ein zufriedenstellender Zustand. Lokaler Wettbewerb in der Anwendung von Gewalt hat normalerweise bedeutet, höhere Kosten für Schutz zu zahlen und weniger davon zu genießen. Gelegentlich haben freidenkende Marktenthusiasten vorgeschlagen, dass allein Marktmechanismen ausreichen würden, um für die Polizeiüberwachung von Eigentumsrechten und den Schutz des Lebens zu sorgen, ohne dass eine Souveränität überhaupt erforderlich wäre.[^215] Einige der Analysen waren elegant, aber die Tatsache bleibt, dass die freie Marktversorgung von Polizei- und Justizdienstleistungen unter den megapolitischen Bedingungen des Industrialismus sich als nicht lebensfähig erwiesen hat. Nur primitive Gesellschaften, in denen das Verhalten stark stereotypisiert ist und die Bevölkerung klein und homogen ist, haben ohne Regierungen überleben können, die den Dienst der lokalen Monopolisierung des Schutzes durch Gewalt boten.

Beispiele für anarchische Gesellschaften über dem Niveau von Jäger-und-Sammler-Stämmen sind rar und antik. Sie finden sich ausschließlich in den einfachsten Volkswirtschaften isolierter Regenwasser-Bauern. Die Kafiren im vorislamischen Afghanistan. Einige irische Stämme im dunklen Zeitalter. Einige Indianerstämme in Brasilien, Venezuela und Paraguay. Andere Ureinwohner in verstreuten Teilen der Welt. Ihre Methoden, Schutz ohne Regierung zu organisieren, sind nur Kennern extremer Fälle bekannt. Wenn Sie mehr über sie erfahren möchten, zitieren wir in unseren Anmerkungen mehrere Bücher, die weitere Details enthalten.[^216] Primitive Gruppen konnten ohne eine spezielle Organisation, die sich auf Gewalt spezialisiert, funktionieren, da sie kleine, geschlossene Gesellschaften waren. Und sie waren isoliert. Sie konnten auf enge Verwandtschaftsbeziehungen zurückgreifen, um sich gegen die meisten gewaltsamen Bedrohungen in geringem Maße zu verteidigen, die die einzigen waren, mit denen sie wahrscheinlich konfrontiert wurden. Als sie auf größere Bedrohungen stießen, die von Staaten organisiert wurden, wurden sie überwältigt und einer von außenstehenden Gruppen monopolisierten Herrschaft unterworfen. Dies geschah immer wieder. Überall dort, wo sich Gesellschaften gebildet haben, die über Banden und Stämme hinausgingen, insbesondere dort, wo Handelswege verschiedene Völker miteinander in Kontakt brachten, sind immer wieder Spezialisten für Gewalt aufgetaucht, um den Überschuss zu plündern, den friedliche Menschen produzieren konnten. Als technologische Bedingungen die Erträge aus Gewalt erhöhten, besiegelten sie das Schicksal von Gesellschaften, die nicht darauf vorbereitet waren, viele Ressourcen in die Kriegsführung zu bewegen.

> „Welche Fürsten leisteten den Polizeidienst? Welche waren Gewaltverbrecher oder sogar Plünderer? Ein Plünderer konnte tatsächlich zum Polizeichef werden, sobald er seine ‚Beute' regulierte, sie an die Zahlungsfähigkeit anpasste, sein Revier gegen andere Plünderer verteidigte und sein territoriales Monopol lange genug aufrechterhielt, damit es durch Gewohnheit legitimiert wurde.“ [^217] - Frederic C. Lane

### Regierungen als Verkäufer von Schutz

Wie wir bereits mehrfach festgestellt haben, besteht die hauptsächliche wirtschaftliche Funktion der Regierung aus der Perspektive derjenigen, die die Steuern zahlen, darin, den Schutz von Leben und Eigentum zu gewährleisten. Dennoch agiert die Regierung oft wie die organisierte Kriminalität, indem sie Ressourcen von Menschen innerhalb ihres Einflussbereichs als Tribut oder Beute extrahiert. Die Regierung ist nicht nur ein Schutzdienst; sie ist auch eine organisierte Schutzgelderpressung. Während die Regierung Schutz vor Gewalt von anderen bietet, berechnet sie den Kunden auch für den Schutz vor Schäden, die sie ansonsten selbst verursachen würde. Die erste Aktion ist eine wirtschaftliche Dienstleistung. Die zweite ist eine Schutzgelderpressung. In der Praxis mag die Unterscheidung zwischen den beiden Formen des „Schutzes“ schwer zu erkennen sein. Regierungen, so hat Charles Tilly betont, könnte man vielleicht am besten als „unsere größten Beispiele für organisierte Kriminalität“ verstehen.[^218]

Die Aktivitäten selbst der besten Regierung beinhalteten meist eine Mischung aus dem wirtschaftlichen Dienstleistungsschutz und Erpressung. Historisch gesehen konnten beide Verfolgungen optimiert werden, wenn die Regierung ein nahezu Monopol auf Zwang innerhalb der Gebiete durchsetzen konnte, in denen sie tätig war. In Fällen, in denen eine einzige bewaffnete Gruppe die Vorherrschaft in der Anwendung von Gewalt erlangen konnte, war die Qualität des Schutzdienstes, den sie bieten konnte, normalerweise weit überlegen gegenüber dem, was von einer der mehreren konkurrierenden Schutzagenturen erzielt werden konnte, die um das gleiche Territorium kämpfte.

### Ein natürliches Monopol auf Land

Das Erreichen eines lokalen Monopols auf Zwang ermöglichte einer Regierung nicht nur, ihre potentiellen Kunden effektiver vor Gewalttaten von anderen zu schützen, sondern senkte auch die Betriebskosten der Regierung erheblich. Wie Lane es ausdrückte: „Die Gewalt anwendende, Gewalt kontrollierende Industrie war ein natürliches Monopol, zumindest auf dem Land. Innerhalb territorialer Grenzen konnte der von ihr erbrachte Dienst viel kostengünstiger von einem Monopol produziert werden.“ [^219] „So ermöglichte ein Monopol auf die Ausübung von Gewalt innerhalb eines zusammenhängenden Territoriums es einem schutzproduzierenden Unternehmen, sein Produkt zu verbessern und seine Kosten zu senken.“ [^220] Eine solche Regierungsorganisation konnte mehr Schutz mit weniger Ausgaben anbieten, wenn sie nicht ständig militärische Maßnahmen ergreifen musste, um konkurrierende Gruppen abzuwehren, die Schutzgelder von ihren Kunden zu erpressen versuchten.

Die Aussicht, dass die Informationstechnologie helfen könnte, die Annahme, dass Souveränität auf einem territorialen Monopol basieren muss, zu „lockern“, hat bereits die Aufmerksamkeit von politischen Theoretikern erregt. Dies ist das Thema von *Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century* von David J. Elkins. Elkins bestätigt unsere These, dass Monopolregierungen dazu bestimmt sind, genauso entbündelt zu werden wie religiöse Monopole in den Jahren nach 1500. Er schreibt: „Wir nahmen früher an, dass Religionen ihr eigenes Territorium oder ‚Revier' haben sollten. Als die Nationen die Weltreligionen als souveräne Schiedsrichter über Leben und Tod ablösten, wich die ‚Kompaktheit' und die ‚Begrenztheit' der Religion der uns heute vertrauten Vermischung von Gläubigen in ein und demselben Gebiet. Stattdessen lehnen wir die Vermischung von Nationen oder Provinzen ab, obwohl ich glaube, dass diese Annahme gerade im Begriff ist zusammenzubrechen.“ [^221] Er argumentiert weiter: Im Einklang mit unserer Ansicht, dass territoriale Souveränitätsmonopole abgebaut werden können, ohne dass Anarchie entsteht, wie das beispielsweise die Teilung der Souveränität zwischen nationalen und provinziellen Regierungen in einem föderalen System wie Kanada und der gemeinschaftlichen Regierung mit gemeinsamer französischer und britischer Souveränität, die einige Pazifikinseln für einen Großteil dieses Jahrhunderts prägte, zeigen. Somit können territoriale Souveränitätsmonopole, während sie selten gewaltsam entbündelt worden sind, durch Vereinbarungen entbündelt werden. Laut Elkins, und wir stimmen zu, ist „die territoriale Nation ein Bündel oder Korb, in den andere Aspekte unseres Lebens passen. Es ähnelt dem wirtschaftlichen Konzept eines ‚Warenkorbs' -- man kann Artikel nicht einfach einzeln nehmen, sondern muss sie kollektiv nehmen. In einem Restaurant kann man ‚à la carte' bestellen; aber was unsere Identitäten anbelangt, müssen wir nehmen, was die Nationen gebündelt haben, was ‚table d'hôte' entspricht. \... Regierung à la carte wird den Bürgern im einundzwanzigsten Jahrhundert natürlich erscheinen.“ [^222] Es gibt keine Entwicklung, die dramatischer zur Zerlegung der Souveränität und zum Aufstieg der Regierung à la carte beitragen wird als das Auftauchen einer Cyberwirtschaft, die physische Grenzen vollständig überwindet.

> „Während die Frequenzen steigen und die Wellenlängen sinken, verbessert sich die digitale Leistung exponentiell. Die Bandbreite erhöht sich, der Energieverbrauch schrumpft, die Antennengröße schrumpft, die Interferenzen brechen zusammen, die Fehlerquoten sinken.“ - George Gilder

## DAS GESETZ DES TELEKOSMOS HEBT DIE GESETZE DER NATIONEN AUF[^507]

Wir sind nicht die Einzigen, die der Meinung sind, dass die Bandbreite (oder die Belastbarkeit der Kommunikationsmedien) dazu bestimmt ist, den Territorialstaat zu übertrumpfen. Jim Taylor und Watts Wacker, die Autoren von *The 500-year Delta: What Happens After What Comes Next*, formulieren ihr Argument nicht so wie wir, aber sie sehen klar, dass „Zugang Globalismus schafft und der Globalismus die politischen Systeme stört, indem er das Konzept der Grenzen obsolet macht. Wenn Grenzen verschwinden, wird das Konzept der Besteuerung, das Regierungen stützt, immer brüchiger\... In dem Maße, wie die Grenzen verschwinden, zerfällt das Konzept des Anspruchs - der Glaube, dass man, weil man an einem bestimmten Ort geboren wurde, Anspruch auf die wirtschaftlichen Vorteile hat, die mit diesem Ort verbunden sind - und in dem Maße, wie er zerfällt, zerfallen auch die Vorzüge der Nationalität. Und während all dies geschieht, werden die Ideale, die der Nationalität zugrunde liegen - Patriotismus, Demokratie, Staat, Assimilation, Vereinheitlichung, verantwortungsvolle Beteiligung, was auch immer das in der jeweiligen Nation bedeuten mag - auf den Müllhaufen der Geschichte verbannt.“ [^223] Ohne es ausdrücklich zu sagen, spüren auch sie offenbar, dass sich die Geschichte auf die Befreiung des souveränen Individuums zubewegt. Wie sie es ausdrücken: „Am Horizont wartet eine viel reinere Form des Individualismus als die Demokratie, wie wir sie jetzt verstehen, es zulässt.“ [^224] Wie wird dies geschehen? Taylor und Wacker sehen eine starke Dynamik am Werk:

Es ist eine einfache Tatsache, dass das größere Gefühl des Patriotismus - die Liebe zur Nation, das Gefühl der kindlichen Pflicht ihr gegenüber - keine noch länger besonders nützliche Veranlagung ist\.... Bürger, die sich in der globalen Gesellschaft wohlfühlen, werden sich global identifizieren. Sie werden politische, gesellschaftliche und wirtschaftliche Entscheidungen treffen, die nicht auf nationaler Identität basieren, sondern darauf, wie sich diese Entscheidungen auf sie selbst und auf Gleichgesinnte in der ganzen Welt beziehen\.... Nationen und Unternehmen, die erfolgreich sind, werden sich entsprechend organisieren. Sie werden die Freiheit zu wissen, zu gehen, zu tun und zu sein maximieren. Nationen und Unternehmen, die das nicht tun, die weiterhin Rückzugsgefechte auf der Grundlage von Nostalgie führen, werden verkümmern.[^225]

Die Entwertung der physischen Grenzen durch die jährliche Verdreifachung der Bandbreite und das geometrische Wachstum des Internets und des World Wide Web wird den Prozess der Abschaffung der Regierungen beschleunigen. Wenn sich die jährliche Verdreifachung der Bandbreite bis zum Jahr 2012 fortsetzt, würde dies ein milliardenfaches Wachstum der Bandbreite seit 1993 bedeuten, seit George Gilder zum ersten Mal andeutete, dass die Bandbreite noch schneller wachsen würde als die Kapazität der Mikroprozessoren. Sollte dies der Fall sein - wovon wir angesichts der jüngsten Durchbrüche in der integrierten Optik ausgehen - würde die dadurch entstehende Fülle an Kommunikationsmöglichkeiten zu einer fantastischen Zunahme des Cyberhandels führen. Mit dem Wellenmultiplexverfahren kann ein einziger Faserstrang, der so dünn wie ein menschliches Haar ist, eine Billion Bits pro Sekunde übertragen.[^226] Mit anderen Worten: Ein einziges Glasfaserkabel könnte fünfundzwanzigmal mehr Bits aufnehmen als die Gesamtlast aller Kommunikationsnetze der Welt zusammen. Die Erweiterungsmöglichkeiten sind verblüffend. Wenn so viel Kommunikationskapazität freigesetzt wird, wird sehr viel mehr Geld für Kommunikation ausgegeben werden, weil sie so billig ist. Und so etablierte Medien wie Telefon und Fernsehen werden zu Anachronismen. Das World Wide Web wird jeden Computer mit einer reichhaltigeren Mischung von Signalen versorgen, als die Verbraucher es heute mit Kabelfernsehen erleben. Die Revolution der Bandbreite wird die Menschen mehr und mehr in die grenzenlose virtuelle Welt der Online-Communities und des Cyberhandels ziehen, eine Welt, die eine so hohe grafische Dichte aufweist, dass sie zum „Metaverse“ wird, der Art von alternativer Cyberspace-Realität, die sich der Science-Fiction-Autor Neal Stephenson vorgestellt hat. Stephensons „Metaverse“ ist eine virtuelle Gemeinschaft mit eigenen Gesetzen, Fürsten und Bösewichten.[^227] Da immer mehr wirtschaftliche Aktivitäten in den Cyberspace verlagert werden, wird der Wert der staatlichen Monopolmacht innerhalb der Grenzen schrumpfen, so dass die Staaten einen wachsenden Anreiz haben, ihre Souveränität aufzuteilen und zu fragmentieren.

So wie Nationalstaaten heute Anreize haben, Freihäfen, Freihandelszonen und Zona Francas einzurichten, so werden sie auch Anreize haben, ihre Souveränität zu verpachten. Wir haben bereits die weit fortgeschrittenen Verhandlungen zwischen dem neunhundert Jahre alten Souveränen Orden der Johanniter von Jerusalem, Rhodos und Malta, besser bekannt als Malteserritter, und der Republik Malta über die Rückgabe der Souveränität über Fort St. Angelo an den Orden diskutiert. Wir erwarten, dass diese Verhandlungen erfolgreich abgeschlossen werden. Andere werden folgen. Einige Nationalstaaten werden die Souveränität über kleine Enklaven und abgelegene Gebiete an völlig neue Gruppierungen und virtuelle Gemeinschaften abtreten. Es ist in der Tat nicht unwahrscheinlich, dass kommerzielle Unternehmen wie Sicherheitsfirmen und Hotelketten um die Souveränität über kleine Gebiete bieten. Wackenhut, Pinkerton und Argenbright könnten in Zukunft hybride Rentnergemeinschaften und steuerfreie Zonen in attraktiven Gegenden der Welt anbieten. Religiöse Organisationen wie die Malteserritter, die jedoch alle denkbaren Konfessionen vertreten, werden auf ihre Weise versuchen, in bestimmten abgelegenen Winkeln der Erde den Himmel zu verwirklichen. Selbst wohlhabende Einzelpersonen und Familien werden ihre eigenen Grundstücke besitzen, auf denen sie eine begrenzte Souveränität ausüben, ihre eigenen Briefmarken und Pässe herausgeben und eine Website unterhalten.

## MONOPOL UND RAUB

Beachten Sie, dass die Anreize, Souveränität gegen eine Gebühr zu teilen oder zu verpachten, ganz andere sind als die, denen Herrscher historisch ausgesetzt waren, die mit ihrem lokalen Monopol auf Zwang militärischer Konkurrenz ausgesetzt waren. Verpachtete Souveränität ist nicht destabilisierender als die Errichtung einer Freihandelszone. Im Gegensatz dazu wirkt sich der militärische Wettbewerb um Macht, wie er von kämpfenden Warlords und Guerillabanden ausgeübt wird, direkt darauf aus, ob die angehende Regierung stärkere Anreize hat, die Menschen in ihrer Reichweite zu beschützen oder auszuplündern. Wo rivalisierende Gruppen miteinander ringen und in einem unausgewogenen Gleichgewicht manövrieren, steigt der Anreiz, räuberische Gewalt anzuwenden. Plünderung wird attraktiver. Weil die Macht weniger stabil ist und das lokale Monopol auf Zwang weniger sicher ist, schrumpfen die Zeithorizonte derjenigen, die in der Lage sind, Gewalt anzuwenden. Der „König des Berges“ steht möglicherweise auf einem derart rutschigen Hang, dass er nicht erwarten kann, lange genug zu überleben, um seinen Anteil an den erheblichen Gewinnen, die letztendlich aus der Eindämmung von Gewalt resultieren, zu realisieren. Wenn dies der Fall ist, gibt es wenig, was diejenigen, die das, was als Regierung gilt, befehligen, davon abzuhalten, ihre Macht zum Terrorisieren und Plündern der Gesellschaft einzusetzen.

Die Logik der Gewalt besagt also, dass je mehr konkurrierende bewaffnete Gruppen in einem Gebiet aktiv sind, desto höher ist die Wahrscheinlichkeit, dass sie zu räuberischer Gewalt greifen. Ohne eine einzige überwältigende Macht, die freie Gewaltanwendung unterdrückt, neigt diese dazu, sich auszubreiten, und viele Errungenschaften der ökonomischen und sozialen Zusammenarbeit gehen dabei verloren.

Der Schaden, der entstehen kann, wenn Gewalt in einem Zustand der Anarchie freien Lauf gelassen wird, wird durch das Schicksal Chinas unter den Kriegsherren in den 1920er Jahren veranschaulicht. Es ist eine Geschichte, die wir in *The Great Reckoning* nacherzählen. Die konkurrierenden Kriegsherren richteten großen Schaden in Gebieten an, in denen es keine einzige, überwältigende Macht gab, um sie in Schach zu halten. Ähnliche Geschichten, die einen ähnlichen Punkt illustrieren, wurden der Welt in lebendiger Farbe durch CNN-Nachrichtenteams, die die Straßen von Mogadischu, Somalia, durchstreiften, übertragen. Die bewaffneten Truppen der somalischen Kriegsherren, die „Technicals“ genannt, brachten Anarchie in dieses traurige Land, bevor die Vereinigten Staaten eine massive militärische Intervention einleiteten, um sie einzudämmen. Als die allmächtige Macht der US-Streitkräfte zurückgezogen wurde, holten die Technicals ihre Waffen wieder hervor, und die Anarchie setzte sich fort. Ein Bericht in der Washington Post bemerkte:

> Pickup-Trucks, die mit Flugabwehrkanonen bestückt sind, pflügen einmal mehr die staubigen, von Trümmern übersäten Straßen. Auch sind die prahlerischen jungen Männer in T-Shirts und mit Kalaschnikow-Gewehren über ihren Schultern zurück, die an provisorischen Straßensperren Geld von vorbeifahrenden Autos und Bussen erpressen. Ein Stadtviertel, das von einer Miliz kontrolliert wird, ist so schwer bewaffnet, dass die Einheimischen es „Bosnien-Herzegowina“ nennen. Das Reisen durch die gefährlichen Straßen dieser Stadt erinnert deutlich an 1992, als der chaotische Krieg unter rivalisierenden Milizen Somalia in Anarchie und eine Hungersnot stürzte, was eine US-geführte militärische Intervention auslöste. Um Mogadischu zu durchqueren, müssen Reisende heutzutage erneut eine Ladung bewaffneter Gangster anheuern, in der Hoffnung, dass diese für rund hundert Dollar am Tag Schutz bieten, plus Freizeit für das Mittagessen.[^228]

Die Beispiele von Somalia, Ruanda und weiteren, die Sie bald im Fernsehen sehen werden, liefern einen farbenfrohen Beweis dafür, dass gewaltsame Konkurrenz um die Gebietskontrolle nicht die gleichen unmittelbaren wirtschaftlichen Gewinne bringen wie andere Wettbewerbsformen. Im Gegenteil, die umherziehenden Banditen und Plünderer, die in der Anarchie konkurrieren, haben nicht einmal die schwachen Anreize zum Schutz produktiver Tätigkeiten, die manchmal selbst die schwere Hand von Diktatoren erleichtern, wenn ihre Herrschaft gesichert ist.

> „Die Gesellschaft dessen, was wir das moderne Zeitalter nennen, ist vor allem im Westen durch ein gewisses Maß an Monopolisierung geprägt. Der freie Gebrauch von Militärwaffen wird dem Einzelnen verweigert und einer zentralen Autorität jeglicher Art vorbehalten, ebenso wie die Besteuerung des Eigentums oder Einkommens der Einzelnen in den Händen einer zentralen sozialen Autorität konzentriert ist. Die finanziellen Mittel, die so in diese zentrale Autorität fließen, erhalten ihr Monopol auf militärische Gewalt aufrecht, während diese wiederum das Monopol auf Besteuerung aufrechterhält. Keines hat in irgendeinem Sinn Vorrang vor dem anderen; sie sind zwei Seiten desselben Monopols. Wenn eines verschwindet, folgt das andere automatisch; die Monopolregel kann manchmal stärker auf der einen Seite als auf der anderen erschüttert werden“ [^229] - Norbert Elias

## DIE ENTWICKLUNG DES SCHUTZES

Lane entwickelte ein Argument, das wir für unsere Zwecke in der Vorstellung, wie das Informationszeitalter sich entfalten könnte, zweckentfremdet haben. Er argumentierte, dass die Geschichte der westlichen Wirtschaften seit dem dunklen Zeitalter in Bezug auf vier Stufen von Wettbewerb und Monopol in der Organisation von Gewalt interpretiert werden kann. Obwohl Lane größtenteils über die megapolitischen Faktoren schweigt, die wir als Einflussfaktoren auf die Größe der Regierungsoperationen identifizieren, stimmt seine Erforschung der Ökonomie der Gewalt eng mit dem Argument überein, das wir in *Blood in the Streets* und *The Great Reckoning* und an anderer Stelle in diesem Band dargelegt haben.

Wir haben bereits einige der megapolitischen Faktoren analysiert, die eine Rolle in der Evolution der westlichen Gesellschaft nach dem Fall Roms gespielt haben. Lane hat sich ebenfalls mit diesem Zeitraum beschäftigt und sich auf die wirtschaftlichen Konsequenzen dieses Wettbewerbs um die Monopolisierung der Gewalt konzentriert. Er erkannte vier wichtige Stadien in der Funktionsweise der Wirtschaften im Laufe der letzten tausend Jahre, wobei jede einen unterschiedlichen Abschnitt in der Organisation der Gewalt beinhaltete.[^244]

### Aus dem dunklen Zeitalter

Die erste Stufe ist die von „Anarchie und Raub“, die die feudale Revolution von vor tausend Jahren geprägt hat. Während Lane die Daten für keine seiner zusammenfassenden Perioden angibt, setzt die Mathematik die Grenze seiner ersten Periode recht klar, und seine Beschreibung der Phase der „Anarchie und Raub“ scheint den Zuständen während des Übergangs von der Dunklen Ära zu entsprechen, wenn der Einsatz von Gewalt „sogar auf dem Land hochgradig wettbewerbsfähig“ war.[^230] Er erklärt nicht warum, aber wenn Gewalt „hochgradig wettbewerbsfähig“ ist, bedeutet dies normalerweise, dass es erhebliche Hindernisse für die Ausübung von Macht auf irgendeine Distanz gibt. In militärischen Begriffen dominiert die Verteidigung über den Angriff.

Aus Gründen, die wir in Kapitel 3 erklärt haben, fiel diese Phase von „Anarchie und Raub“ mit einem Rückgang der Produktivität in der Landwirtschaft aufgrund nachteiliger klimatischer Veränderungen zusammen. Da die Technologie zu der Zeit nur wenige wirksame Skaleneffekte zur Sicherung eines Gewaltmonopols bot, war der Wettbewerb zwischen den angehenden Herrschern weit verbreitet. Die wirtschaftliche Aktivität wurde erstickt.

Die Schwäche der Wirtschaft verschärfte das Problem, eine stabile Ordnung zu etablieren. Die Errichtung eines lokalen Gewaltmonopols verursachte zu hohe Kosten im militärischen Bereich, im Vergleich zum geringen Wert des Wirtschaftsumsatzes. Ohne die Fähigkeit, ein wirksames Monopol über ein wirtschaftlich tragfähiges Gebiet durchzusetzen, terrorisierten und plünderten die bewaffneten Ritter zu Pferd, während sie ihren Kunden kaum „Schutz“ boten.

### Feudalismus

„Die zweite Phase beginnt dort, wo kleine regionale oder provinzielle Monopole etabliert werden. Die landwirtschaftliche Produktion steigt an und der größte Teil des Überschusses wird von den kürzlich etablierten Monopolisten der Gewalt eingezogen.“ [^231] Trotzdem ist der Überschuss während dieser zweiten Phase, die wir mit dem frühen Mittelalter identifizieren, relativ karg. Das Wirtschaftswachstum wird durch das Fehlen von Größenvorteilen bei der Organisation von Gewalt gebremst, was die militärischen Kosten für die Durchsetzung lokaler Monopole hoch hält. Aber während die Kosten hoch bleiben, steigt der Preis, den Minisouveränitäten für Schutz verlangen können, da die wirtschaftliche Aktivität sich ausdehnt, wenn die Anarchie eingedämmt wird.

Während einer späten Phase der zweiten Stufe locken viele Tributnehmer Kunden durch Sonderangebote für landwirtschaftliche und kommerzielle Unternehmen an. Sie bieten Schutz zu niedrigen Preisen für diejenigen an, die neue Länder in Kultur bringen werden, und spezielle Polizeidienste zur Förderung des Handels, wie den von den Grafen von Champagne für Händler, die zu ihren Messen kommen.“ [^232] Mit anderen Worten, als sie in der Lage waren, eine ausreichende Kontrolle über das Territorium zu verhandeln, taten lokale Kriegsherren das, was lokale Händler tun, wenn sie ihren Marktanteil erhöhen müssen: sie rabattierten ihre Dienstleistungen, um Kunden anzuziehen. Die Kriegsherren nutzten später die zusätzlichen Ressourcen aus der zusätzlichen wirtschaftlichen Aktivität, um ihre Kontrolle über größere Gebiete zu festigen. Einmal fest etabliert, begannen sie, mehr von den Vorteilen des Monopols zu genießen. Ihre militärischen Kosten für Polizeiarbeit neigten dazu zu fallen und sie konnten auch den Preis, den sie verlangten, erhöhen, ohne sich Sorgen zu machen, dass dies ihre Dienstleistung für Kunden weniger attraktiv machte.

In dieser komplizierten Phase der westlichen Geschichte nehmen diejenigen, die Gewalt ausüben, die mittelalterlichen Herren und Monarchen, den größten Teil des Überschusses über das Existenzminimum ein. Es gibt nur wenige Händler. Die erfolgreichsten sind diejenigen, die am besten in der Lage sind, die Steuern, Gebühren und anderen Kosten, die von denen verlangt werden, die Geld für „Schutzdienste“ fordern, zu umgehen oder zu minimieren.

### Die frühe Neuzeit

Eine dritte Phase wird erreicht, wenn die Kaufleute und Landbesitzer, die nicht auch auf Gewalt spezialisiert sind, „mehr vom ökonomischen Überschuss bekommen als Lehensträger und Monarchen \... In dieser dritten Phase erhalten die Unternehmen, die sich auf Gewalt spezialisiert haben, weniger vom Überschuss als die Unternehmen, die Schutz vor den Regierungen kaufen.“ [^233] Da erfolgreiche Kaufleute eher dazu neigen, ihre Gewinne neu zu investieren als sie zu verbrauchen, führte der höhere Gewinn der Kaufleute in dieser geschichtlichen Phase zu einem sich selbst verstärkenden Wachstum.

### Das Zeitalter der Fabriken

Lane identifiziert den Übergang von der dritten zur vierten Phase mit dem Aufkommen von technologischen und industriellen Innovationen als wichtigere Faktoren für den Gewinn als die Senkung der Schutzkosten. Dabei scheint Lane sich auf die Zeit seit 1750 zu beziehen. Von diesem Zeitpunkt an begann der Charakter der Technologie, eine eindeutig dominierende Rolle für den Wohlstand der Regionen zu spielen. Um ein extremes Beispiel zu nennen, selbst in Gebieten, in denen es überhaupt keine Regierung gab - wie in einigen Teilen Neuseelands vor 1840 - war es unwahrscheinlich, dass sie einfach deshalb sehr wohlhabend wurden, weil sie keine Steuern zahlten. Zu diesem Zeitpunkt in der Geschichte waren Innovationen in der Industrietechnologie wichtiger für die Erzielung von Gewinnen als jede Einsparung, die durch Senkung der Schutzkosten erzielt werden konnte, sogar bis auf null. Als die Größe der Regierung zunahm, wurden die ursprünglich von Regierungen entwickelten Kredit- und Finanzierungsmechanismen zur Beschaffung von Ressourcen für militärische Operationen auch für die Finanzierung von größeren Unternehmungen verfügbar.

Obwohl Lane es nicht direkt ausspricht, hat die Konzentration von technologischen Vorteilen an einem bestimmten Ort den Wettbewerb zwischen den Rechtsgebieten reduziert und es „Unternehmen, die sich auf den Einsatz von Gewalt spezialisiert haben“, oder Regierungen, ermöglicht, höhere Preise zu verlangen. Wenn es große technologische Lücken zwischen den Wettbewerbern in einer Jurisdiktion und einer anderen gibt, wie es während des Industriezeitalters der Fall war, neigen Unternehmer in den Jurisdiktionen mit der besten Technologie dazu, mehr Geld zu verdienen, auch wenn sie höhere Steuern und andere Kosten an ihre Regierungen zahlen müssen.

### Raub mit einem Lächeln

Regierungen im Industriezeitalter genossen ein erfreuliches Monopol, das sie ausnutzen konnten. Ihre tatsächlichen Kosten für die Gewährleistung des Lebens- und Körperschutzes waren im Vergleich zu den Preisen (Steuern), die sie verlangten, verschwindend gering. Doch sie befanden sich tatsächlich in einem Bereich, in dem der Wettbewerb so verdreht war, dass sie sich wesentlich stärker auf das Geschäft des Raubes statt auf das des Schutzes konzentrieren konnten und diese Tatsache nahezu unbemerkt blieb. Es war ein seltener Moment in der Geschichte.

Die Nachteile der Anarchie unter den megapolitischen Bedingungen des Industrialismus machten einen Wettbewerb in Schutzdiensten innerhalb desselben Territoriums technologisch ungeeignet. Die einzige Möglichkeit, unter diesen Bedingungen effektiven Schutz zu erreichen, bestand darin, die größere Fähigkeit zur Anwendung von Gewalt zu besitzen. Daher gab es wenig zu gewinnen, indem man versuchte, diesen Teil der eigenen Steuern, der, in den Worten von Lane, „als Zahlung für die erbrachte Dienstleistung“ ging, besser von „einem anderen Teil, bei der die Versuchung nahe liegt, sie Raub zu nennen“ zu unterscheiden.[^234] Die Unterscheidung war sicherlich real genug. Aber da man in jedem Fall die Steuern zahlen musste, hatte es wenig Nutzen, diese vollständig zu entwickeln, außer einer morbiden Neugierde nachzugeben. Wie Lane sagte, egal welcher Teil der Steuern als Plünderung bezeichnet wurde, sie waren ein Preis, den man zahlen musste „um größere Verluste zu vermeiden“.[^235]

### Der Aufstieg der Einkommen im Industriezeitalter.

Ein Teil des Grundes, warum dieses Dilemma während der letzten zwei Jahrhunderte der Vorherrschaft des Nationalstaates erträglich war, lag in der Tatsache, dass die Einkommen dramatisch stiegen, insbesondere in den Jurisdiktionen, in denen die industrielle Entwicklung hauptsächlich stattfand. Diejenigen, die die OECD-Regierungen leiteten, nahmen Jahr für Jahr einen höheren Prozentsatz der Einkommen ein. Aber die Zunahme der Plünderung wurde dennoch von weit größerem Wohlstand begleitet und von einer größeren Ungleichheit des Wohlstands im Vergleich zum Rest der Welt. Unter solchen Bedingungen waren Einwände gegen die Steuerwelle unvermeidlich marginal und unzureichend, um die Ereignisse von ihrem logischen Verlauf abzulenken. Tatsächlich hing das militärische Überleben eines Industriestaates, wie in den vorherigen Kapiteln dargelegt, weitgehend davon ab, dass seinen Ansprüchen auf die Ressourcen seiner Bürger keine wirksamen Grenzen gesetzt werden konnten.

In jedem Industriestaat verliefen die Politiken mehr oder weniger in dieselbe Richtung. Auf dem Höhepunkt des Industrialismus nach dem Zweiten Weltkrieg erreichte der Grenzsteuersatz 90 Prozent oder mehr. Dies war eine weitaus aggressivere Behauptung des Rechts des Staates, Ressourcen zu extrahieren, als selbst die orientalischen Despoten der frühen hydraulischen Zivilisationen zu machen neigten. Doch die industrielle Form der Plünderung folgte ihrer eigenen Logik. Ein großer Teil davon wurde von der Charakteristik der industriellen Technologie in der ersten Hälfte des zwanzigsten Jahrhunderts bestimmt, die wir bereits zuvor beschrieben haben.

Diese Technologie machte es praktisch unvermeidbar, dass der Staat einen großen Anteil des Einkommens beschlagnahmte und umverteilte, wobei ein Großteil der Last dieses Raubzugs auf eine kleine Gruppe von Kapitalisten fiel. Die meisten industriellen Prozesse waren stark abhängig von natürlichen Ressourcen und daher an die Orte gebunden, an denen diese Ressourcen vorhanden waren. Ein Stahlwerk, eine Mine oder ein Hafen konnten nur unter enormen Kosten oder gar nicht verlegt werden. Solche Einrichtungen waren daher stationäre Ziele, die leicht besteuert werden konnten. Grundstücks-, Unternehmens- und Entnahmebesteuerung stiegen im Laufe dieses Jahrhunderts stark an. Auch die Einkommensteuern stiegen, zunächst auf die Kapitalisten, aber schließlich auch auf die Arbeiter selbst. Die Einführung großflächiger industrieller Beschäftigung machte eine breit angelegte Einkommensteuer praktisch, da Gehälter direkt an der Quelle gepfändet werden konnten, wobei die Steuerbehörden die Einnahmen in Zusammenarbeit mit den Buchhaltungsabteilungen der Industrieunternehmen koordinierten. Heute nehmen wir dies als gegeben hin, aber die Einziehung einer Einkommensteuer am Fabriktor war eine weitaus einfachere Aufgabe als sich über das ganze Land zu verteilen, um einen Teil der Gewinne von Millionen von unabhängigen Handwerkern und Bauern einzutreiben.

Kurz gesagt, die industrielle Technologie machte die Besteuerung routinierter, berechenbarer und weniger gefährlich als die Besteuerung in vielen früheren Epochen. Dennoch wurde dadurch ein höherer Prozentsatz der gesellschaftlichen Ressourcen entzogen als durch jede andere Form der Souveränität zuvor.

### Was schützen wir?

Die Tatsache, dass Gesellschaften reicher werden konnten, während der Gesamtprozentsatz des Einkommens, der durch Steuern absorbiert wurde, erheblich anstieg, wirft eine Frage über den Charakter des Schutzes auf, den Regierungen den industriellen Ökonomien boten. Was genau haben sie beschützt? Unsere Antwort: Hauptsächlich industrielle Anlagen mit hohen Kapitalkosten und bedeutender Anfälligkeit für Angriffe. Die Präsenz von Großindustrieunternehmen wäre in einer ungeordneten Umgebung mit mehr wettbewerblicher Gewalt nicht möglich gewesen, selbst wenn das Ergebnis des Wettbewerbs eine Verringerung des allgemeinen Anteils am Gesamtertrag gewesen wäre, den die Regierung einnimmt.

Aus diesem Grund sind kapitalintensive Betriebe in den amerikanischen Slums sowie in Dritte-Welt-Ländern, in denen adhoc-Gewalt an der Tagesordnung ist, unwirtschaftlich. Die industrielle Gesellschaft als Ganzes konnte voranschreiten, weil eine bestimmte Art von Ordnung etabliert und aufrechterhalten wurde. Unternehmen waren regelmäßigen, vorhersehbaren „Abschöpfungen“ ausgesetzt, statt unregelmäßiger Gewalt.

Selbst auf dem Höhepunkt der Industrialisierung war es immer eine Übertreibung, davon zu sprechen, dass eine Regierung ein „Gewaltmonopol“ anwendet. Alle Regierungen versuchen ein solches Monopol aufrechtzuerhalten, aber wie wir gesehen haben, stellten die Mitarbeiter von Industrieunternehmen oft fest, dass sie in der Lage waren, Gewalt gegen ihre Arbeitgeber anzuwenden. Solange die breite Öffentlichkeit überhaupt Zugang zu Waffen hat, oder eine chaotische Menge die physische Fähigkeit hat, einen Bus umzukippen oder Steine auf die Polizei zu werfen, monopolisieren diejenigen, die die Regierung kontrollieren, die Gewalt nicht völlig. Sie kontrollieren lediglich die vorherrschende Gewalt, die in einem Maße dominant ist, dass es für die meisten Menschen unter den gegebenen Bedingungen unwirtschaftlich wird, mit ihnen zu konkurrieren.

> „Eine netzbasierte Regierung, kann nur mit Zustimmung der Regierten operieren. Daher muss jede Internetregierung ihren Bürgern echte Vorteile bieten, wenn sie will, dass diese bleiben. Diese Vorteile müssen nicht nur persönliche Güter oder Dienstleistungen sein, sondern es können auch die breiteren Vorteile eines regulativen Regimes sein: Ein sauberer, transparenter Marktplatz mit definierten Regeln und Konsequenzen oder eine betreute Gemeinschaft, in der Kinder den Menschen, denen sie begegnen, vertrauen können und die Privatsphäre des Einzelnen geschützt ist.“ [^236] - Esther Dyson

### Das Informationszeitalter

Das Informationszeitalter bringt eine fünfte Phase in der Entwicklung des Wettbewerbs bei der Verwendung von Gewalt im Westen hervor - eine Phase, die von Lane nicht vorhergesehen wurde. Diese fünfte Phase beinhaltet den Wettbewerb im Cyberspace, einer Arena, die nicht von einem „Gewalt anwendenden Unternehmen“ monopolisiert werden kann. Sie kann nicht monopolisiert werden, weil sie kein Territorium ist.

Obwohl Lanes Argumentation die herkömmlichen Nachkriegsannahmen über die Unvermeidlichkeit des Nationalstaats einbezieht, erkannte er einen Punkt, der möglicherweise zukünftig wichtiger für das Verständnis der Zukunft ist, als es vor vierzig oder fünfzig Jahren den Anschein hatte. Es ist die Tatsache, dass Regierungen nie stabile Monopole der Gewalt auf dem offenen Meer etabliert haben. Denken Sie einmal darüber nach. Kein Regierungsgesetz hat dort jemals ausschließlich Geltung gefunden. Dies ist von äußerster Wichtigkeit, um zu verstehen, wie die Organisation von Gewalt und Schutz sich entwickeln wird, während die Wirtschaft sich in den Cyberspace verlagert, der überhaupt keine physische Existenz hat. Aus den gleichen Gründen, die Lane wegen der Beobachtung angeführt hat, dass keine Regierung jemals in der Lage gewesen ist, Gewalt auf dem Meer zu monopolisieren, ist es noch weniger wahrscheinlich, dass eine Regierung ein unendliches Reich ohne physische Grenzen erfolgreich monopolisieren könnte.

## WETTBEWERB OHNE ANARCHIE

In der Vergangenheit, wenn Bedingungen es schwierig machten, dass eine einzige gewalttätige Einheit ein Monopol errichtete, waren die Ergebnisse Anarchie und Raub. Das Informationszeitalter hat jedoch die technologischen Bedingungen, unter denen Gewalt organisiert wird, auf tiefergreifende Weise verändert. Anders als in der Vergangenheit, als die Unfähigkeit, den Schutz in einer Region zu monopolisieren, höhere Militärkosten und geringere wirtschaftliche Erträge bedeutet, weist die Tatsache, dass Regierungen den Cyberspace nicht monopolisieren können, auf geringere Militärkosten und höhere wirtschaftliche Erträge hin. Denn die Informationstechnologie schafft eine neue Dimension beim Schutz. Zum ersten Mal in der Geschichte ermöglicht die Informationstechnologie die Schaffung und den Schutz von Vermögenswerten, die vollständig außerhalb des Hoheitsbereichs jedes einzelnen staatlichen Gewaltmonopols liegen.

> „Länder, in denen die Einheiten der politischen Macht und Verwaltung vielfältig sind und denen eine zentrale, stabile und unangefochtene überwachende Instanz für Rechtsprechung und Macht fehlt, müssen ihre eigenen funktionierenden Lösungen zur Bewältigung der Probleme finden, die solche Grenzen hervorrufen.“ [^237] - Rees Davies

### Die Analogie zur Grenze

Der Cyberspace ist in gewissem Sinne das Äquivalent zu einer technologisch geschützten Handelszone, wie sie in Grenzgebieten während des Mittelalters existierte. In der Vergangenheit, als die Macht der Herren und Könige schwach war und sich die Ansprüche eines oder mehrerer an einer Grenze überschnitten, existierte so etwas wie eine Wettbewerbsregierung. Ein Blick darauf, wie die Markregionen funktionierten, könnte Einblicke geben, wie Gesetze der Mark oder etwas Ähnliches in den Cyberspace einwandern könnten.

Andorra überlebt als eine Art versteinerte Markregion zwischen Frankreich und Spanien, ein Relikt von geopolitischen Bedingungen, die es für beide Königreiche erschwert haben, das andere in diesem kalten und nahezu unzugänglichen Gebiet von 500 Quadratkilometern in den Pyrenäen zu dominieren. Im Jahr 1278 wurde eine Vereinbarung getroffen, die die Oberhoheit über Andorra zwischen lokalen französischen und spanischen Feudalherren, dem französischen Grafen von Foix und dem spanischen Bischof von Urgel, aufteilte. Jeder von ihnen ernannte einen von zwei „Viquiers“, die die minimale Gewalt der Regierung in Andorra nur spärlich ausübten, hauptsächlich durch das Kommando über die winzige andorranische Miliz, die heute eine Polizeitruppe ist. Die Rolle des Grafen wurde vor langer Zeit durch die Geschichte überholt. Die französische Regierung vertritt ihn heute aus Paris. Zu ihren Aufgaben gehört es, die Hälfte des jährlichen Tributs zu akzeptieren, den Andorra zahlt, ein Betrag, der weniger als eine Monatsmiete in einer heruntergekommenen Wohnung beträgt. Der Bischof von Urgel erhält weiterhin seinen Anteil am Tribut, so wie es seine Vorgänger im Mittelalter taten.

Wie der geteilte Tribut andeutet, hat es in Andorra statt nur einer zwei Quellen der „Aufsichtsgerichtsbarkeit und Macht“ gegeben. Berufungen von andorranischen Zivilklagen wurden traditionell entweder beim Bischofskolleg von Urgel oder beim Kassationshof in Paris eingereicht.

Eine Folge der unsicheren Position von Andorra war, dass fast keine Gesetze erlassen wurden. Andorra hat seit mehr als siebenhundert Jahren eine winzige Regierung und keine Steuern. Heute macht es das zu einem immer attraktiveren Steuerparadies. Doch bis vor einer Generation war Andorra für seine Armut bekannt. Einst dicht bewaldet, wurde es im Laufe der Jahrhunderte von den Bewohnern entwaldet, die in den bitteren Wintern versuchten, sich warm zu halten. Der gesamte Ort ist jedes Jahr von November bis April eingeschneit. Selbst im Sommer ist Andorra so kalt, dass Getreide nur an den südlichen Ausläufern wächst. Wenn unsere Beschreibung es unattraktiv erscheinen lässt, haben Sie gerade das Geheimnis seines Erfolges entdeckt. Andorra überlebte als feudale Enklave im Zeitalter der Nationalstaaten, weil es abgelegen und bettelarm war.

Einst gab es zahlreiche mittelalterliche Grenz- oder „Mark“-Regionen, in denen Souveränitäten verschmolzen. Diese gewalttätigen Grenzgebiete bestanden für Jahrzehnte oder manchmal sogar Jahrhunderte in den Randgebieten Europas. Die meisten waren arm. Wie wir bereits erwähnt haben, gab es Mark-Territorien zwischen den keltischen und englischen Kontrollgebieten in Irland, zwischen Wales und England, Schottland und England, Italien und Frankreich, Frankreich und Spanien, Deutschland und den slawischen Grenzgebieten Mitteleuropas und zwischen den christlichen Königreichen Spaniens und dem islamischen Königreich Granada. Genau wie Andorra entwickelten diese Markgebiete eigene institutionelle und rechtliche Formen, die wir im nächsten Jahrtausend wahrscheinlich wiedersehen werden.

Aufgrund der Wettbewerbsposition beider Autoritäten, von denen beide schwach waren, würden Herrscher manchmal sogar unter ihren Untertanen Freiwillige anwerben, um in Markregionen zu siedeln, um die Reichweite ihrer Autorität zu erhöhen. Fast selbstverständlich wurden die Untertanen mit der Befreiung von Steuern in die Mark gelockt. Angesichts der geringen Margen, auf denen sie konkurrierten, würde es schwieriger für seine Anhänger werden, über die Runden zu kommen, wenn eine der Autoritäten in einer Mark versuchen würde, Steuern zu erheben. Ebenso würde er jedem einen Grund geben, sich seinem Konkurrenten anzuschließen. Daher hatten die Bewohner einer Mark in der Regel die Wahl, zu entscheiden, wessen Gesetze sie befolgen sollten. Diese Wahl basierte auf der Schwäche der konkurrierenden Autoritäten; es handelte sich nicht um eine ideologische Geste.

Dennoch traten praktische Schwierigkeiten auf, die gelöst werden mussten. Im Feudalsystem standen Grundbesitzer, die Eigentum auf beiden Seiten einer nominellen Grenze besaßen, vor einem ernsthaften Konflikt der Pflichten. Beispielsweise könnte ein Herr an der Grenze zwischen Schottland und England, der in beiden Königreichen Besitztümer besaß, theoretisch im Kriegsfall beiden militärischen Dienst schulden. Um diese widersprüchlichen Verpflichtungen zu lösen, konnten fast alle in der feudalen Hierarchie durch einen rechtlichen Prozess namens ‚Bekenntnis' wählen, wessen Gesetze sie befolgen wollten.

Die Informationstechnologie wird äquivalente Möglichkeiten für einen wettbewerbsorientierten Standortwechsel wirtschaftlicher Aktivitäten schaffen, allerdings mit wichtigen Unterschieden. Einer davon ist, dass der Cyberspace, im Gegensatz zu mittelalterlichen Grenzgesellschaften, aller Voraussicht nach das reichste aller Wirtschaftsgebiete sein wird. Es wird daher eher eine wachsende als eine rückläufige Grenze darstellen. Nur wenige Menschen in den Kernregionen der mittelalterlichen Gesellschaft hätten sich ohne starke Anreize, oft auch religiöser Natur, an die Grenzen bewegen wollen, da diese Regionen in der Regel gewalttätig und arm waren. Daher zogen sie keine Ressourcen aus der Kontrolle der Behörden ab. Der Cyberspace wird das aber tun.

Zweitens wird die neue Grenze kein Duopol sein, das zu Kollusionen zwischen den beiden Behörden einlädt, um über ihre Grenzansprüche Kompromisse zu finden. Solche Kompromisse neigten dazu, während der mittelalterlichen Periode aus zwei Gründen nicht effektiv zu sein: Es gab häufig deutliche kulturelle Unterschiede zwischen den rivalisierenden Behörden; und wichtiger noch, ihnen fehlte die physische Kapazität, eine ausgehandelte Lösung durchzusetzen, da sie nicht über ausreichende militärische Präsenz vor Ort verfügten. In der Ära des Nationalstaates, als nationale Behörden tatsächlich ausreichende militärische Macht ausübten, um Lösungen durchzusetzen, verschwanden die meisten Markregionen und unscharfen Grenzen. Die Grenzfestlegung wurde zur Norm. Das ist eine stabile Lösung, wenn Gewalt-Duopolisten vor der Aufgabe stehen, ihre Autorität über angrenzende Regionen zu teilen. Aber der Wettbewerb um die Ansiedlung von Transaktionen in der Cyberwirtschaft wird nicht zwischen zwei Behörden stattfinden, sondern zwischen Hunderten von Behörden auf der ganzen Welt. Für die territorialen Staaten wird es nahezu unmöglich sein, ein effektives Kartell zu schaffen, um die Steuersätze hoch zu halten. Das wird aus demselben Grund wahr sein, weil Kollusionen zur Erzielung von Monopolpreisen auf Märkten mit Hunderten von Wettbewerbern nicht funktionieren.

Als Beweis betrachten Sie den Schritt der Seychellen, einem kleinen Land im Indischen Ozean, ein neues Investitionsgesetz zu erlassen, das US-Regierungsbeamte als „Welcome Criminals“-Gesetz bezeichnen. Nach diesem Gesetz erhält jeder, der 10 Millionen Dollar in den Seychellen investiert, nicht nur einen garantierten Schutz vor der Auslieferung, sondern auch einen diplomatischen Pass. Entgegen den Behauptungen der US-Regierung sind die beabsichtigten Begünstigten jedoch nicht Drogenhändler, die ohnehin im Allgemeinen unter dem Schutz wichtigerer Regierungen stehen, sondern unabhängige Unternehmer, die politisch inkorrekt geworden sind. Der erste potenzielle Begünstigte des Seychellen-Gesetzes ist ein weißer Südafrikaner, der reich wurde, indem er die Wirtschaftssanktionen gegen das ehemalige Apartheid-Regime umging. Jetzt steht er vor der Gefahr wirtschaftlicher Vergeltung durch die neue südafrikanische Regierung und ist bereit, den Seychellen für Schutz zu zahlen.[^238]

Unabhängig vom Verdienst jedes einzelnen Falles zeigt das Beispiel, warum Versuche von Regierungen, ein Schutzkartell auf dem Boden aufrechtzuerhalten, zum Scheitern verurteilt sind.

Im Gegensatz zur mittelalterlichen Grenze, bei der der Wettbewerb nur zwischen zwei Autoritäten stattfand, wird die Grenze im Cyber-Handel zwischen hunderten von Zuständigkeitsbereichen liegen, wobei die Zahl wahrscheinlich rasch in die Tausende steigen wird.

Im Zeitalter der virtuellen Unternehmen werden Einzelpersonen ihre einkommensgenerierenden Aktivitäten in der Rechtsordnung ansiedeln, die die beste Dienstleistung zu den niedrigsten Kosten bietet. Mit anderen Worten, Souveränität wird kommerzialisiert werden. Im Gegensatz zu mittelalterlichen Grenzgesellschaften, die in den meisten Fällen verarmt und gewalttätig waren, wird der Cyberspace weder das eine noch das andere sein. Der Wettbewerb, zu dem die Informationstechnologie die Regierungen antreibt, ist kein militärischer, sondern ein Wettbewerb in Bezug auf Qualität und Preis eines wirtschaftlichen Dienstes - echter Schutz. Kurz gesagt, Regierungen werden verpflichtet sein, den Kunden das zu geben, was sie wollen.

### Die verminderte Nützlichkeit von Gewalt

Das heißt natürlich nicht, dass Regierungen darauf verzichten werden, Gewalt einzusetzen. Ganz im Gegenteil. Vielmehr sagen wir, dass Gewalt einen Großteil ihres Einflusses verliert. Eine mögliche Reaktion der Regierungen wäre die verstärkte Anwendung von Gewalt auf lokaler Ebene, um die abnehmende globale Bedeutung der Gewalt zu kompensieren. Was auch immer Regierungen tun, sie werden nicht in der Lage sein, den Cyberspace auf dieselbe Art und Weise mit Gewalt zu durchdringen, wie sie die Territorien, die sie in der modernen Welt monopolisiert haben, mit Gewalt durchdrungen haben. Egal wie viele Regierungen versuchen, in den Cyberspace einzudringen, sie werden in diesem Bereich nicht mächtiger oder leistungsfähiger sein als jeder andere.

Ironischerweise würden die Versuche der Nationalstaaten, „Informationskriege“ zu führen, um den Cyberspace zu dominieren oder den Zugang dazu zu verhindern, wahrscheinlich nur ihren eigenen Untergang beschleunigen. Die Tendenz zur Auflösung großer Systeme ist bereits stark durch das Wegfallen von Skaleneffekten und die steigenden Kosten der Zusammenhaltung von fragmentierenden sozialen Gruppen. Die Ironie der Informationskriege besteht darin, dass sie den spröden Systemen, die aus dem Industriezeitalter übriggeblieben sind, wahrscheinlich mehr Schock zufügen könnten als der aufkommenden Informationswirtschaft selbst.

Solange die essenzielle Informationstechnologie funktioniert, könnte der Cyber-Handel parallel zu den Kämpfen der Informationskriege ablaufen, auf eine Weise, die in einem territorialen Krieg nie möglich wäre. Man könnte sich nicht vorstellen, dass Millionen von kommerziellen Transaktionen an der Front eines der Kriege des zwanzigsten Jahrhunderts stattfinden. Aber virtuelle Kriege könnten die Kapazität des Cyberspace für die Durchführung vielfältiger Aktivitäten nicht erschöpfen. Und da es keine virtuelle Realität gibt, gäbe es wenig Gefahr der physischen Nähe und praktisch gar keine, von einem explodierenden virtuellen Schrapnell getroffen zu werden.

### Die Verwundbarkeit von großen Systemen

Die Gefahren des Informationskrieges sind hauptsächlich Gefahren für groß angelegte Industriesysteme, die unter zentraler Steuerung und Kontrolle betrieben werden. Die militärischen Autoritäten in den Vereinigten Staaten und anderen führenden Nationalstaaten planen und befürchten Akte der Informationssabotage, die schwerwiegende Folgen für die Abschaltung großer Systeme haben könnten. Ein Akt des Cyberkrieges könnte eine Telefonumschaltstation abschalten, die Flugverkehrskontrolle stören oder ein Pumpsystem sabotieren, das den Wasserfluss zu einer Stadt regelt. Ein programmiertes Virus könnte sogar konventionelle oder nukleare Generatoren abschalten und Teile des Stromnetzes lahmlegen. Sogenannte Logikbomben könnten eine Vielzahl von Informationen durcheinanderbringen, am empfindlichsten in zentralen Kontrollsystemen, die vulnerable, groß angelegte Systeme aus der Industriezeit betreiben. Kurz gesagt, ohne eine massive und umfassende Zerstörung aller Informationstechnologie, die die Weltwirtschaft buchstäblich zum Stillstand bringen würde, würden Cyberhandel und virtuelle Realität jenseits der Kapazität jeder Regierung bleiben, sie zu ersticken oder gar zu monopolisieren.

Sogar einer der deutlichsten Nachteile der Informationstechnologie, die offensichtliche Anfälligkeit von Informationsspeichersystemen für Verfall und Zerstörung, wurde durch neue Archivierungstechnologie weitgehend gelöst. Ein neues System namens „High-Density Read-Only Memory“ oder \“HD-ROM\“ verwendet eine Ion-Mühle, ähnlich wie die in computerunterstützten Fertigungssystemen, um Archive in einem Vakuum zu erstellen. Die Speicherkapazität beträgt nun bis zu 25.000 Megabyte pro Quadratzoll. Im Gegensatz zu früheren Systemen, die anfällig für vorzeitigen Verfall und Störungen durch Schock waren, versprechen die in HD-ROM gespeicherten Daten, für die Dauer vorhanden zu sein. Einer der Entwickler von HD-ROM, Bruce Lamartine, sagt: „Es ist quasi unempfindlich gegen die Verheerungen der Zeit, thermische und mechanische Schocks oder die elektromagnetischen Felder, die für andere Speichermedien so zerstörend sind.“ [^239] Selbst die Detonation einer Bombe durch Kernwaffenterroristen würde nicht unbedingt wichtige Informationen durcheinanderbringen oder zerstören, wie die Codes für digitales Geld, auf die das reibungslose Funktionieren einer Cyberspace-Wirtschaft angewiesen sein wird.

> „Moderne Armeen sind so abhängig von Informationen, dass es möglich ist, sie blind und taub zu machen, um einen Sieg zu erzielen, ohne im herkömmlichen Sinne zu kämpfen.“ [^240] - Oberst Alan Campen, U.S.A.F. (im Ruhestand)

## ÜBERMACHTBEFUGNISSE DER VIRTUELLEN KRIEGSFÜHRUNG

Die Annahmen des Nationalstaats im Krieg werden immer weniger sinnvoll, je mehr die Bedeutung von Informationen in der Kriegsführung zunimmt. Da der Cyberspace keine physische Existenz hat, haben Dimensionen, wie wir sie in der physischen Welt kennen, keine dominierende Bedeutung. Es ist unwichtig, wie viele Programmierer an der Festlegung einer Befehlssequenz beteiligt waren. Alles, was zählt, ist, ob das Programm funktioniert. Der souveräne Einzelne kann in der Cyberwelt ebenso viel zählen wie ein Nationalstaat mit einem Sitz in der UN, einer eigenen Flagge und einer Armee im Einsatz. In rein wirtschaftlicher Hinsicht verfügen bereits einige souveräne Individuen über investierbare Einkommen in Höhe von jährlich mehreren Hundert Millionen, Summen, die die verfügbare Ausgabenmacht einiger bankrotter Nationalstaaten übertreffen. Aber das ist noch nicht alles. Im Hinblick auf virtuelle Kriegsführung durch Informationsmanipulation können einige Individuen genauso groß oder größer als viele der Staaten der Welt erscheinen. Ein bizarres Genie, das mit digitalen Dienern arbeitet, könnte theoretisch die gleiche Wirkung in einem Cyberkrieg erzielen wie ein Nationalstaat. Bill Gates könnte das sicherlich.

In diesem Sinne ist das Zeitalter des souveränen Individuums nicht nur ein Slogan. Ein Hacker oder eine kleine Gruppe von Mathematikern, ganz zu schweigen von einer Firma wie Microsoft oder fast jeder Softwarefirma, könnte theoretisch alle oder einige der Dinge tun, die die Cyberkrieg-Arbeitsgruppe des Pentagon in petto hat. Es gibt Hunderte von Firmen im Silicon Valley und anderswo, die bereits über größere Kapazitäten verfügen, einen Cyberkrieg zu führen, als 90 Prozent der existierenden Nationalstaaten.

Die Annahme, dass die Regierungen weiterhin das Leben am Boden monopolisieren werden, während alternative Schutzmöglichkeiten auf allen Seiten geöffnet werden, ist ein Anachronismus. Ein weitaus wahrscheinlicheres Szenario ist, dass die Nationen umstrukturiert werden müssen, um ihre Anfälligkeit für Computerviren, logische Bomben, infizierte Drähte und Falltürprogramme zu verringern, die von der US-amerikanischen National Security Agency oder auch nur einem jugendlichen Hacker überwacht werden könnten.

Die megapolitische Logik des Cyberspace legt nahe, dass zentrale Befehl- und Kontrollsysteme, die derzeit die großen Infrastrukturen der Welt dominieren, durch multizentrische Sicherheitsmodelle mit verteilten Fähigkeiten ersetzt werden müssen, damit sie nicht leicht von einem Computervirus erfasst oder blockiert werden können. Neue Softwaretypen, bekannt als agorische offene Systeme, werden die Befehls- und Kontrollsoftware, die aus dem industriellen Zeitalter übernommen wurde, ersetzen. Diese ältere Software verteilte Rechenkapazitäten nach starren Prioritäten, ähnlich wie die zentralen Planer bei Gosplan in der ehemaligen Sowjetunion Güter nach starren Regeln auf Güterwagen verteilen. Die neuen Systeme werden durch Algorithmen gesteuert, die Marktmechanismen nachahmen, um Ressourcen effizienter durch einen internen Bieterprozess zu verteilen, der die Wettbewerbsprozesse im Gehirn nachahmt. Anstelle von riesigen Computermonopolen, die wichtige Befehls- und Kontrollfunktionen ausführen, werden diese im neuen Jahrtausend dezentralisiert.

Es gibt kein besseres Beispiel für die Widerstandsfähigkeit verteilter Netzwerke im Vergleich zu Befehls- und Kontrollsystemen als das, was von digitalem Equipment in seinem Forschungslabor in Palo Alto gegeben wurde. Ein Ingenieur öffnete die Tür zu einem Schrank, in dem das firmeneigene Computernetzwerk untergebracht war. Wie Kevin Kelly berichtet, hat der Ingenieur dann dramatisch ein Kabel aus dem Netzwerkgerät gerissen. „Das Netzwerk leitete die Datenströme um die Störstelle herum und blieb dabei völlig unbeeindruckt.“ [^241]

Das Informationszeitalter wird nicht nur den Wettbewerb ohne Anarchie im Cyberspace erleichtern; es wird zwangsläufig zur Neugestaltung wichtiger Systeme führen, die aus dem Industriezeitalter übriggeblieben sind. Eine solche Umgestaltung ist essentiell, um sie weniger anfällig für Unheil zu machen, das von überall und von jedem kommen könnte. Genauso wie das Industriezeitalter unweigerlich zur Umgestaltung von Institutionen führte, die aus dem Mittelalter übrig waren, wie Schulen und Universitäten, so werden auch die verbliebenen Institutionen des Industriezeitalters wahrscheinlich in verkleinerten Formen weiterentwickelt, die der Logik der Mikrotechnologie entsprechen.

Der Schutzbedarf vor Banditen auf der „Autobahn der Informationen“ wird eine weit verbreitete Annahme von Verschlüsselungsalgorithmen mit öffentlichem und privatem Schlüssel erfordern. Diese ermöglichen bereits jedem einzelnen Nutzer eines Computers, jede Nachricht sicherer zu kodieren, als das Pentagon seine Startcodes nur eine Generation zuvor hätte versiegeln können. Diese kraftvollen, unknackbaren Verschlüsselungsformen sind notwendig, um finanzielle Transaktionen vor Hackern und Dieben zu schützen.

Sie werden auch aus einem weiteren Grund notwendig sein. Private Finanzinstitute und Zentralbanken werden unknackbare Verschlüsselungsalgorithmen einführen, wenn sie erkennen, dass die US-Regierung - und sie ist vielleicht nicht die einzige - in der Lage ist, aktuelle Banksysteme und Computersysteme zu durchdringen und buchstäblich ein Land in den Bankrott zu treiben oder das Bankkonto von nahezu jedem Menschen überall zu leeren. Es gibt keinen technologischen Grund, warum irgendein Individuum oder irgendein Land seine finanziellen Einlagen oder Transaktionen dem Erbarmen der US-amerikanischen National Security Agency oder den Nachfolgern des KGB oder irgendeiner ähnlichen Organisation, legal oder illegal, ausliefern sollte.

Verschlüsselungsalgorithmen, die selbst von Regierungen nicht geknackt werden können, sind keine Hirngespinste. Sie sind bereits als Shareware im Internet verfügbar. Sobald Satellitensysteme in niedriger Umlaufbahn voll funktionsfähig sind, wird es Einzelpersonen mittels fortschrittlicher Computer und Antennen, die nicht größer sind als die von Mobiltelefonen, möglich sein, weltweit zu kommunizieren, ohne überhaupt mit dem Telefonsystem verbunden sein zu müssen. Es wird genauso unmöglich sein für eine Regierung, den Cyberspace zu monopolisieren, einem Bereich ohne physische Existenz, wie es für mittelalterliche Ritter unmöglich gewesen wäre, Transaktionen im industriellen Zeitalter auf einem schweren Schlachtross zu kontrollieren.

### Schutz durch Geheimhaltung

Informationsgesellschaften werden riesige Ressourcen außerhalb des Raubzugs stellen. Wenn der Cyberspace zunehmend Finanztransaktionen und andere Formen des Handels beherbergt, werden die dort eingesetzten Ressourcen mehr oder weniger immun gegen gewöhnliche Erpressungen und Diebstähle sein. Daher werden Räuber nicht in der Lage sein, so große Anteile von Ressourcen zu akkumulieren, wie sie es heute tun und wie sie es während des größten Teils des zwanzigsten Jahrhunderts getan haben.

Unweigerlich wird daher der staatliche Schutz eines großen Teils des Weltvermögens überflüssig werden. Die Regierung wird nicht besser in der Lage sein, ein Bankguthaben im Cyberspace zu schützen, als Sie es sind. Da die Regierung weniger notwendig sein wird, wird ihr relativer Preis aus diesem alleinigen Grund wahrscheinlich fallen. Es gibt noch andere Gründe.

Mit einem großen und wachsenden Anteil an Finanztransaktionen, die im Cyberspace im neuen Jahrtausend stattfinden, werden Einzelpersonen die Wahl haben, in welcher Rechtsordnung sie diese durchführen wollen. Dies wird einen intensiven Wettbewerb schaffen, um die Dienstleistungen der Regierung (die von ihr erhobenen Steuern) auf nicht-monopolistischer Basis zu bepreisen. Dies ist revolutionär. Wie George Melloan im Wall Street Journal argumentierte, ist die Institution, die den Kräften des globalen Wettbewerbs am erfolgreichsten widerstanden hat, der Wohlfahrtsstaat. „Eine Studie von Forschern der Wharton School und der Australian National University diskutierte die Kräfte, die auf Einkommensüberweisungen einwirken. Geoffrey Garrett und Deborah Mitchell kamen zu dem Schluss, dass ‚es so gut wie keine Beweise dafür gibt, dass eine erhöhte Marktintegration nach unten Druck auf ihre grundlegendsten Wohlfahrtsprogramme ausgeübt hat.' Im Gegenteil, sie schreiben, ‚Regierungen haben unveränderlich auf eine erhöhte Integration in internationale Märkte reagiert, indem sie Einkommensübertragungen erhöhten.'“ [^242] Das Aufkommen der Cyberwirtschaft wird den Wohlfahrtsstaat endlich einem echten Wettbewerb aussetzen. Es wird die Natur der Souveränitäten verändern und Volkswirtschaften umgestalten, da das Gleichgewicht zwischen Schutz und Erpressung stärker auf die Seite des Schutzes schwingt, als es jemals zuvor der Fall war.

[^187]: Neil Munro, „The Pentagon\'s New Nightmare: An Electronic Pearl Harbor,“ Washington Post, 16. Juli 1995, S. C3.

[^188]: Thomas Hobbes, Leviathan, Kap. 13 „The Natural Condition of Man as Concerning Their Felicity and Misery.“

[^189]: Thomas Schelling, Arms and Influence (New Haven: Yale University Press, 1966).

[^190]: Kevin Kelly, Out of Control: The New Biology of Machines, Social Systems, and the Economic World (Reading, Mass.: Addison\~Wesley, 1995), S. 45-46.

[^191]: Ebenda, S. 2-4.

[^192]: Ebenda, S. 4.

[^193]: Heinz Pagels, The Dreams of Reason (New York: Bantam Books, 1989), zitiert in Roger Lewin, Complexity: Life at the Edge of Chaos (New York: Macmillan, I992), S. 10.

[^194]: Lane, „Economic Consequences of Organized Violence,“ ebenda, S. 402.

[^195]: Frederic C. Lane, „The Economic Meaning of War and Protection“, in Venice and History: The Collected Papers of Frederic C. Lane (Baltimore: The Johns Hopkins Press, 1966), S. 383-384.

[^196]: Shi Mai\'an und Lao Guanzhong, Outlaws of the Marsh, trans. Sidney Shapiro (Bloomington: Indiana University Press, 1981), S. 12.

[^197]: George E Will, „Farewell to Welfare States“, Washington Post, 17. Dezember 1995, S. C7.

[^198]: Robert S. MeElvaine, The Great Depression: America, 1929-1941 (New York: Times Books, 1984), S. 292.

[^199]: Ebenda, S. 293.

[^200]: Smith, ebenda, S. 75.

[^201]: Ebenda, S.76.

[^202]: Ebenda.

[^203]: Eine der ersten argentinischen Gewerkschaften, die sich organisierte, war die Eisenbahngewerkschaft im Jahr 1887. Siehe Carmelo Mesa-Lago, Social Security in Latin America: Pressure Groups, Stratification, and Inequality (Pittsburgh: University of Pittsburgh Press, 1978), S. 161.

[^204]: Zu Einzelheiten über die Planung und den Bau des C&O-Kanals, siehe Robert J. Brugger, Maryland: A Middle Temperament 1634-1980 (Baltimore: The Johns Hopkins Press, 1990), S. 202-203 f.

[^205]: Irving J. Sloan, Our Violent Past: An American Chronicle (New York: Random House, 1970), S. 177.

[^206]: Zu Einzelheiten über die Gewalt bei den Eisenbahnstreiks von 1877, siehe ebenda, und Brugger, ebenda, S. 341-344.

[^207]: Sloan, ebenda, S. 202. Siehe außerdem S. S. Boynton, „Miners\' Vengeance,“ Overland Monthly, vol.22 (1893), S. 303-307.

[^208]: Benjamin Schwartz, „American Inequality: Its History and Scary Future,“ New York Times, 19. Dezember 1995, S. A25.

[^209]: MeElvaine, ebenda, S. 293.

[^210]: Ebenda.

[^211]: Ebenda.

[^212]: Henry C. Simons, „Some Reflections on Syndicalism“, Journal of Political Economy März 1944, S. 22.

[^213]: Kelly, op. cit., S. 191-192.

[^214]: Gayle Ni. Hanson, „A Riveting Account of \'Life\' in Postmodernist Cyberspace“, Washington Times, 24. Dezember 1995, S. B7.

[^215]: Eine knappe Einführung in die wissenschaftliche Erforschung der Anarchie findet sich in Gordon Tullock, Hrsg., Explorations in the Theory of Anarchy (Blacksburg, Va.: Virginia Polytechnic Institute and State University, 1972). Siehe außerdem Murray N. Rothbard, Power and Market, Government and the Economy (Menlo Park, Calif., 1970); und Robert Nozick, Anarchy, State and Utopia (New York: Basic Books, 1974).

[^216]: Siehe Pierre Clastres, Society Against the State: The Leader as Servant and the Humane Uses of Power Among the Indians of the Americas (New York: Urizen Books, 1977); und Jones, ebenda.

[^217]: Lane, „Economic Consequences of Organized Violence“, ebenda, S. 403.

[^218]: Charles Tilly, „War Making and State Making as Organized Crime“, in Peter B. Evans, Dietrich Rue Schemeyer, and Theda Skoepol, Bringing the State Back In (Cambridge: Cambridge University Press, 1985), S. 169.

[^219]: Ebenda.

[^220]: Lane, „Economic Consequences of Organized Violence“, ebenda, S. 402.

[^221]: David J. Elkins, Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century. Toronto: University of Toronto Press, 1995, S. 13-14.

[^222]: Ebenda, S. 29.

[^223]: Jim Taylor und Watts Wacker, The 500-Year Delta: What Happens After What Comes Next. New York: HarperCollins, 1997, S. 40.

[^224]: Ebenda, S. 67.

[^225]: Ebenda, S. 41-42.

[^226]: George Gilder, „Fiber Keeps Its Promise: Get Ready. Bandwidth Will Triple Each Year for the Next 25, Creating Trillions in New Wealth.“ Forbes ASAP, 7. April 1997.

[^227]: Siehe Neal Stephenson, Snow Crash. New York: Bantam Books, 1993.

[^228]: Keith B. Richburg, „Two Years After U.S. Landing in Somalia, It\'s Back to Chaos“, Washington Post, 4. Dezember 1994, S. Al.

[^229]: Zitiert in Tilly, Coercion, Capital and European States, ebenda, S. 85.

[^230]: Lane, „Economic Consequences of Organized Violence“, ebenda, S. 411.

[^231]: Ebenda.

[^232]: Ebenda.

[^233]: Ebenda, S. 412.

[^234]: Ebenda, S. 403.

[^235]: Ebenda, S. 404.

[^236]: Esther Dyson, Release 2.1: A Design for Living in the Digital Age. New York: Broadway Books, 1998, S. 131.

[^237]: Rees Davies, „Frontier Arrangements in Fragmented Societies: Ireland and Wales“, in Robert Bartlett und Angus MacKay, eds., Medieval Frontier Societies (Oxford: Oxford University Press, 1992), S. 80.

[^238]: Siehe Thomas W. Lippman, „Seychelles Offers Investors Safe Haven for \$10 Million“, Washington Post, 31. December 1995, S. A27.

[^239]: Siehe „ROM of Ages,“ Wired, Januar 1996, S. 52.

[^240]: Zitiert in James Adams, „Dawn of the Cyber Soldiers“, The Sunday Times (London), 15. Oktober 1995, S. 3-5.

[^241]: Kelly, ebenda, S. 19.

[^242]: George Melloan, „Welfare State Reform Is Mostly Mythological“, The Wall Street Journal. 14. Oktober 1996, S. A19.

[^243]: Siehe Kapitel 8 von *The Great Reckoning*: „Lineare Erwartungen in einer nichtlinearen Welt: Wie das Teleskop uns zum Rechnen führte; wie der Computer uns helfen kann zu sehen“

[^244]: Beachten Sie, dass Lanes vier Stadien des Wettbewerbs und der Monopolisierung im Gebrauch von Gewalt sich von den vier Stadien in der Organisation des Wirtschaftslebens unterscheiden, die wir identifizieren, nämlich Sammeln und Jagen, Landwirtschaft, Industrialisierung und das Informationszeitalter.

[^507]: Der Begriff Telekosmos bezieht sich in diesem Kontext auf das Buch „Telecosm: The World After Bandwidth Abundance” von George Gilder. Der Begriff hat sich im deutschen Sprachraum jedoch nicht auf die hier intendierte Weise durchgesetzt. Anm. d. Übers.