# DAS ENDE DER EGALITÄREN ÖKONOMIE

*Die Revolution der Einkommensfähigkeit in einer Welt ohne Arbeitsplätze*

> „Gott lässt sich nicht spotten: Denn was der Mensch sät, das wird er ernten." - Galater 6:7

Große Veränderungen in den vorherrschenden Produktions- oder Verteidigungsformen verändern die Struktur der Gesellschaft und das Verhältnis von Reichtum und Macht unterschiedlicher Gruppen. Das Informationszeitalter bedeutet mehr als nur den wachsenden Einsatz leistungsstarker Computer. Es bedeutet eine Revolution in Lebensstilen, Institutionen und der Verteilung von Ressourcen. Da die Rolle von verdeckter Gewalt bei der Kontrolle von Ressourcen stark abnehmen wird, wird sich eine neue Zusammensetzung von Reichtum entwickeln, ohne die zwangsvermittelnde Rolle der Regierung, die das 20. Jahrhundert prägte. Weil der Standort in der Informationsgesellschaft viel weniger bedeuten wird, wird die Bedeutung aller Organisationen, die eher innerhalb als jenseits geografischer Grenzen operieren, in der Zukunft abnehmen. Politiker, Gewerkschaften, regulierte Berufe, Lobbyisten und Regierungen als solche werden, weniger wichtig sein. Da Vetternwirtschaft und Handelshemmnisse, die von Regierungen erzwungen wurden, weniger wertvoll sein werden, werden weniger Ressourcen verschwendet, um Lobbyarbeit zu fördern oder zu bekämpfen.

Diejenigen, die Zwang und lokale Vorteile genutzt haben, um Einkommen umzuverteilen, sind dazu bestimmt, einen Großteil ihrer Macht zu verlieren. Dies wird die Herrschaft über die Ressourcen verändern. Privat generiertes Vermögen, das bisher vom Nationalstaat beansprucht wurde, wird stattdessen von denen einbehalten, die es verdienen. Es werden immer mehr Vermögen in die Hände der fähigsten Unternehmer und Risikokapitalgeber weltweit gelangen. Globalisierung, zusammen mit anderen Merkmalen der Informationswirtschaft, wird dazu tendieren, das Einkommen der talentiertesten Personen in jedem Bereich zu erhöhen. Da der Grenzwert, der durch herausragende Leistungen erzeugt wird, so enorm sein wird, wird die Verteilung der Verdienstmöglichkeiten in der gesamten Weltwirtschaft ähnlich aussehen wie jetzt in Leistungsberufen wie der Leichtathletik und der Oper.

## EINE GRÖẞENORDNUNG JENSEITS DES PARETO-PRINZIPS

Das Pareto-Prinzip besagt, dass 80 Prozent des Nutzens von 20 Prozent der Betroffenen stammt oder auf sie zurückzuführen sind. Dies mag ungefähr zutreffen, obwohl auffällig ist, dass ein Prozent der Bevölkerung der Vereinigten Staaten 28,7 Prozent der Einkommenssteuer zahlt. Dies legt nahe, dass Gesellschaften mit dem Fortschreiten ins Informationszeitalter eine noch schiefere Verteilung von Einkommen und Fähigkeiten erleben werden, als Vilfredo Pareto sie am Ende des letzten Jahrhunderts beobachtet hat. Die Menschen sind es durchaus gewohnt, große Ungleichheiten im Reichtum zu haben. Im Jahr 1828 sollen 4 Prozent der New Yorker 62 Prozent des gesamten Reichtums der Stadt besessen haben. Bis 1845 besaßen die obersten 4 Prozent etwa 81 Prozent des gesamten Unternehmens- und Nicht-Unternehmensvermögens in New York City. Im weiteren Sinne besaßen die obersten 10 Prozent der Bevölkerung etwa 40 Prozent des Reichtums in den gesamten Vereinigten Staaten im Jahr 1860. Den Aufzeichnungen zufolge besaßen die reichsten 12 Prozent dann etwa 86 Prozent des amerikanischen Vermögens im Jahr 1890.[^270]

Die Zahlen von 1890 liegen nahe an dem, was Pareto im Sinn hatte. Sie weichen hauptsächlich von seinem Verhältnis von 80:20 Prozent ab, weil gegen Ende des neunzehnten Jahrhunderts ein massiver Zustrom mittelloser Einwanderer Amerika erreichte. Der Anteil der Einwanderer am Gesamtvermögen war vernachlässigbar; daher machte ihre Ankunft die gesamten Vermögensbestände ungleicher. Tatsächlich handelt es sich hierbei um eine eindrucksvolle Veranschaulichung der Tatsache, dass ein echter Aufstieg der Chancen fast zwangsläufig mindestens zu einem kurzzeitigen Anstieg der Ungleichheit führen muss. Bis 1890 machten Einwanderer etwa 15 Prozent der gesamten Bevölkerung der USA aus, in einigen der nordöstlichen Staaten, in denen ein Großteil des Einkommens und des Vermögens generiert wurde, betrug ihr Anteil aber mehr als 40 Prozent.[^271] Unter Berücksichtigung des Anstiegs der Einwanderung passte das Amerika des späten neunzehnten Jahrhunderts fast genauso gut in Paretos Formel wie die Schweiz des späten neunzehnten Jahrhunderts, in der er lebte.

Das Informationszeitalter hat bereits die Verteilung des Reichtums verändert, insbesondere in den Vereinigten Staaten, und gehört zu den Gründen für die Bitterkeit der modernen amerikanischen Politik, die wir im nächsten Kapitel näher untersuchen werden. Das Informationszeitalter erfordert für den wirtschaftlichen Erfolg einen recht hohen Standard an Alphabetisierung und Rechenfähigkeiten. Eine umfangreiche Untersuchung des US-Bildungsministeriums, „Erwachsenenbildungsstand in Amerika", hat gezeigt, dass bis zu 90 Millionen Amerikaner von über fünfzehn Jahren unzureichende Kompetenzen besitzen. Oder, in der bildhafteren Charakterisierung des amerikanischen Auswanderers Bill Bryson ausgedrückt: „Sie sind so dumm wie Schweinesabber." [^272] Insbesondere wurden 90 Millionen erwachsene Amerikaner als unfähig eingestuft, einen Brief zu schreiben, einen Busfahrplan zu verstehen oder zu addieren und zu subtrahieren, selbst mit Hilfe eines Taschenrechners. Diejenigen, die keinen gewöhnlichen Busfahrplan verstehen können, werden wahrscheinlich nicht viel von der Informationsautobahn mitbekommen. Dieses Drittel der Amerikaner, die sich nicht auf die elektronische Informationswelt vorbereitet haben, bilden eine wütende Unterschicht. An der Spitze der Gesellschaft steht eine kleine Gruppe, vielleicht 5 Prozent, von hochgebildeten Informationsarbeitern oder Kapitalbesitzern, die im Informationszeitalter das Äquivalent der Landaristokratie des Mittelalters bilden - mit dem entscheidenden Unterschied, dass die Elite des Informationszeitalters Spezialisten in Produktion, nicht in Gewalt sind.

### Die Megapolitik der Innovation

Aus nicht eindeutig nachvollziehbaren Gründen haben die meisten Soziologen des zwanzigsten Jahrhunderts angenommen, dass technologischer Fortschritt tendenziell zu immer egalitäreren Gesellschaften führen würde. Dies war jedoch vor etwa 1750 nicht der Fall. Zu dieser Zeit begann die innovative neue Industrietechnologie Arbeitsmöglichkeiten für Ungelernte zu eröffnen und die Unternehmensgröße zu erhöhen. Die neue Technologie der Fabrik erhöhte nicht nur das tatsächliche Einkommen der Armen ohne ihr Zutun; sie steigerte auch die Macht politischer Systeme, die dadurch nicht nur besser Einkommen umverteilen konnten, sondern auch widerstandsfähiger gegen Unruhen wurden. Aus einer langfristigen Perspektive heraus gibt es keinen inhärenten Grund anzunehmen, dass Technologie immer tendenziell dazu neigt, Unterschiede in menschlichem Talent und Motivation zu verschleiern, anstatt sie zu betonen. Einige Technologien waren verhältnismäßig egalitär und erforderten Beiträge vieler unabhängiger Arbeiter mit annähernd gleicher Nützlichkeit; andere legten Macht oder Reichtum in die Hände weniger Meister, während die meisten Menschen kaum mehr als Leibeigene waren. Geschichte und Technologie haben unterschiedliche Nationen in unterschiedlicher Weise geprägt. Das Fabrikzeitalter produzierte die eine Form, und das Informationszeitalter produziert eine andere, weniger gewalttätige, und daher elitärere und weniger egalitäre als die, die es ersetzt.

## AMMONS RÜBE

Im späten neunzehnten Jahrhundert begann eine Reihe von Ökonomen, unter denen William Stanley Jevons in England der renommierteste war, mit der Entwicklung der mathematischen Wirtschaftswissenschaften. Einer der Ersten, der die Wahrscheinlichkeitstheorie auf eine wichtige soziale Frage anwandte, war der deutsche Wirtschaftswissenschaftler Otto Ammon, dessen Arbeit erstmals 1899 von Carlos C. Closson ins Englische übersetzt wurde. Dies geschah in einem Artikel im *Journal of Political Economy* mit dem Titel „Some Social Applications of the Doctrine of Probability." [^273] Man könnte annehmen, dass ein solcher Artikel heute nur noch von antiquarischem Interesse ist. Tatsächlich behandelt er jedoch ein ökonomisches Problem, das wieder in den Vordergrund tritt, und zwar auf eine immer noch inspirierende Art und Weise.

Otto Ammon interessierte sich für die Verteilung von Fähigkeiten in der Gesellschaft und deren Beziehung zur Verteilung von Einkommen und Status. Als Ausgangspunkt nahm er das wahrscheinliche Auftreten von Gesamtpunkten aus vier Würfeln, jeder mit sechs Seiten. Von 1.296 möglichen Würfen treten einige Summen häufiger auf als andere.

Die Summe von 24 Punkten wird einmal auftreten.\
Die Summe von 23 Punkten wird 4 mal auftreten.\
Die Summe von 22 Punkten wird 10 mal auftreten.\
Die Summe von 21 Punkten wird 20 mal auftreten.\
Die Summe von 20 Punkten wird 35 mal auftreten.\
Die Summe von 19 Punkten wird 56 mal auftreten.\
Die Summe von 18 Punkten wird 80 mal auftreten.\
Die Summe von 17 Punkten wird 104 mal auftreten.\
Die Summe von 16 Punkten wird 125 mal auftreten.\
Die Summe von 15 Punkten wird 140 mal auftreten.\
Die Summe von 14 Punkten wird 146 mal auftreten.\
Die Summe von 13 Punkten wird 140 mal auftreten.\
Die Summe von 12 Punkten wird 125 mal auftreten.\
Die Summe von 11 Punkten wird 104 mal auftreten.\
Die Summe von 10 Punkten wird 80 mal auftreten.\
Die Summe von 9 Punkten wird 56 mal auftreten.\
Die Summe von 8 Punkten wird 35 mal auftreten.\
Die Summe von 7 Punkten wird 20 mal auftreten.\
Die Summe von 6 Punkten wird 10 mal auftreten.\
Die Summe von 5 Punkten wird 4 mal auftreten.\
Die Summe von 4 Punkten wird einmal auftreten.

Es wird sofort deutlich, dass hohe und niedrige Werte beide vergleichsweise selten sind. Es gibt zwei mögliche Summen, aber die oberen vier davon treten nur fünfunddreißig Mal auf. Die mittlere Gruppe von sieben Werten kann voraussichtlich 884 Mal auftreten; das mittlere Drittel der möglichen Werte ist das Ergebnis in mehr als zwei Dritteln aller Würfe. Dies führt zur charakteristischen Häufung in der Mitte in der Wahrscheinlichkeitstheorie.

Otto Ammon argumentierte, dass diese zufällige Verteilung von Würfelwürfen der Verteilung menschlicher Fähigkeiten entsprach. Er schrieb dies, bevor die Entwicklung von Intelligenztests und IQs stattfand, und stützte sich auf die früheren Arbeiten über Intelligenz von Francis Galton. Ammon war nicht der Meinung, dass sozialer Nutzen oder Erfolg im Leben einfach von der Intelligenz abhing. Er listete „drei Gruppen von geistigen Eigenschaften auf, die weitgehend darüber entscheiden, welchen Platz ein Mann im Leben einnehmen wird". Diese lauteten:

1.  Geistige Eigenschaften; hierzu zählte ich alles, was zur rationalen Seite der menschlichen Fähigkeiten gehört, wie schnelle Auffassungsgabe, Gedächtnis, Urteilsvermögen, Erfindungsgeist und alles andere, was zu diesem Gebiet gehört.

2.  Moralische Eigenschaften; nämlich Selbstkontrolle, Willenskraft, Fleiß, Ausdauer, Mäßigung, Beachtung der familiären Verpflichtungen, Ehrlichkeit und dergleichen.

3.  Wirtschaftliche Merkmale; wie unternehmerische Fähigkeiten, organisatorisches Talent, technisches Können, Vorsicht, kluge Kalkulation, Weitblick, Sparsamkeit und so weiter.

Zu diesen geistigen Merkmalen fügte er hinzu:

4.  Körperliche Eigenschaften; Arbeitskraft, Ausdauer, die Fähigkeit, Anstrengungen zu ertragen und Erregungen jeder Art zu widerstehen, Vitalität, Gesundheit, usw.

In Otto Ammons Sichtweise entsprach die wahrscheinliche Verteilung dieser Qualitäten von Intelligenz, Charakter, Talent und Körper den Punktzahlen im Würfelspiel. Er ging sogar noch weiter und argumentierte, dass es tatsächlich viel mehr als vier Variablen gab und dass diese in mehr als sechs Stufen variierten. Würde man anstelle von vier Würfeln acht werfen, dann gäbe es nicht weniger als 1.679.616 mögliche Würfe, aber man könnte erwarten, dass die höchste Punktzahl, achtundvierzig, nur einmal auftritt. Der Mann oder die Frau, die in all den Faktoren, die den Platz im Leben bestimmen, sehr hoch abschneiden, sind viel seltener als die Wahrscheinlichkeit, vier Sechser zu werfen, nahelegen würde; vielleicht so selten wie das Werfen von acht Sechsern. Dennoch merkt Ammon an, dass eine Mischung aus hohen und niedrigen Punktzahlen in diesen menschlichen Qualitäten „Personen mit unausgeglichenen, unharmonischen Gaben" hervorbringen kann, die „trotz einiger brillanter Eigenschaften die Prüfungen des Lebens nicht erfolgreich bestehen können."

> „Wie ein einsamer Berggipfel, oder eher wie die Turmspitze einer Kathedrale, erheben sich die Männer von hohem Talent und Genius über die breite Masse der Mittelmäßigkeit \... Die Anzahl der hochbegabten ist in jedem Fall so klein, dass es unmöglich ist, dass ‚viele' solcher in den niederen Klassen durch die Unvollständigkeit der sozialen Institutionen zurückgehalten wurden." - Otto Ammon

### Eigenschaften und Einkommen

Dann wendete sich Ammon der Einkommensverteilung zu. Natürlich waren die Statistiken der 1890er Jahre weit weniger hinreichend als sie es heute wären, aber die deutsche Bürokratie war bereits gut entwickelt, und Otto Ammon fand in Sachsen, Preußen, Baden und anderen deutschen Staaten Einkommenskurven, die er sowohl mit seiner wahrgenommenen Verteilung menschlicher Fähigkeiten als auch mit den Wahrscheinlichkeiten beim Würfeln gleichsetzte. Er fand ähnliche Zahlen in Charles Booths *Life and Labour of the People of London* (1892). Tatsächlich sieht Booths soziale Verteilung ziemlich so aus, wie man es von Ammons Wahrscheinlichkeitstheorie erwarten würde. Booth stellte in London fest, dass 25 Prozent arm oder sehr arm waren, 51,5 Prozent ein komfortables Leben führten und 15 Prozent wohlhabend oder reich waren; wenn man die zwei niedrigsten Kategorien von Booth nimmt, ergeben sie 9,5 Prozent. Vor den Wohlfahrtsstaaten des 20. Jahrhunderts war es üblich, von den am schlechtesten Gestellten als das „versunkene Zehntel" zu sprechen.[^274] Die zwei höchsten Kategorien von Booth summierten sich auf 7 Prozent.

Aus all dem zog Otto Ammon eine Reihe von interessanten Schlussfolgerungen. Er war der Ansicht, dass die Fähigkeiten der Menschen, im weitesten Sinne definiert, ihren Platz in der Gesellschaft und ihr Einkommen bestimmten. Er glaubte, dass hohe Fähigkeiten auf natürliche Weise dazu führen, dass Menschen im Einkommen und in der sozialen Position aufsteigen. „Wie ein einsamer Berggipfel, oder eher wie die Turmspitze einer Kathedrale, erheben sich die Männer von hohem Talent und Genius über die breite Masse der Mittelmäßigkeit\..." Er glaubte auch, dass die „wahre Form der sogenannten sozialen Pyramide, die einer eher flachen Zwiebel oder einer Rübe hat." Die Rübe hat einen schmalen Stiel oben und eine schmale Wurzel unten. Eine solche soziale Rübe ist als Metapher einer sozialen Pyramide vorzuziehen, denn wie die moderne Industriegesellschaft hat, sie ihre Masse in der Mitte, während die Pyramide ihre Masse unten hat.

### Die Form der Rübe

Moderne Industriegesellschaften sind tatsächlich alle wie Rüben, mit einer kleinen wohlhabenden und oberen Berufsklasse an der Spitze, einer größeren Mittelschicht und einer Minderheit als arme Klasse am unteren Ende. Im Verhältnis zur Mittelschicht sind beide Extreme klein. Im modernen London, wenn nicht gar in Washington, gibt es sicherlich mehr Millionäre als Obdachlose.

All das ist faszinierend, doch das unmittelbare Interesse an Ammons Arbeit liegt in der bedeutenden langfristigen Veränderung, die wir in den finanziellen und politischen Beziehungen zwischen der Spitze und der Mitte erleben. Die Fähigkeiten, die im Fabrikzeitalter, das nun zu Ende geht, benötigt wurden, unterscheiden sich zweifellos von denen, die das Informationszeitalter erfordert. Die meisten Menschen konnten die Fähigkeiten erlernen, die erforderlich waren, um die Maschinen der Mitte des 20. Jahrhunderts zu bedienen, aber diese Arbeitsplätze wurden nun durch intelligente Maschinen ersetzt, die sich im Grunde genommen selbst steuern. Ein ganzes Arbeitsfeld mit geringen und mittleren Fertigkeiten ist bereits verschwunden. Wenn wir richtig liegen, ist dies ein Vorläufer für das Verschwinden des größten Teils der Beschäftigung und die Neugestaltung der Arbeit am Effektivmarkt.

> „Es ist eine Tatsache, die offiziell, aber leise anerkannt wurde, dass die meisten der arbeitslosen Jugendlichen überhaupt keine Qualifikationen haben\..."[^275] - Clive Jenkins und Barrie Sherman

## WENIGER MENSCHEN WERDEN MEHR ARBEIT LEISTEN

Wir können die einfache Vier-Würfel-Verteilung der menschlichen Fähigkeiten nehmen und annehmen, dass die Menschen im Fabrikzeitalter mit einem Satz von 4 x 2 oder mehr punkten könnten. Das würde bedeuten, dass über 95 Prozent der Bevölkerung über dem liegen, was Charles Booth als „die niedrigste Grenze der positiven sozialen Nützlichkeit" bezeichnete. Tatsächlich wurden in den 1940er und 1950er Jahren 3 Prozent als Vollbeschäftigungsstandard festgesetzt. Nehmen wir an, dass im Informationszeitalter die erforderliche Punktzahl auf 4 x 3 gestiegen ist und das erforderliche Minimum von 8 auf 12 gestiegen ist. Das würde bedeuten, dass fast 24 Prozent unter dieser Grenze der „sozialen Nützlichkeit" liegen würden.

Etwas Ähnliches würde am oberen Ende der Skala geschehen. Im Fabrikzeitalter war das erforderliche Niveau hoher Fähigkeiten vielleicht bei 4 x 4; nehmen wir an, dass es im Informationszeitalter auf 4 x 5 gestiegen ist. In diesem Fall würde der Anteil der Menschen, die für die Spitzenarbeitsplätze qualifiziert sind, die auch am besten bezahlt werden, von 34 Prozent auf 5 Prozent fallen.

Diese Zahlen sind rein hypothetisch. Natürlich wissen wir nicht, wie die Verschiebung in den Anforderungen an die Fähigkeiten sein wird - oder bereits war - aber es hat sicherlich einen Anstieg gegeben. Aufgrund der Form der Rübe würde ein relativ bescheidener Anstieg der Mindestanforderungen an die Fähigkeiten eine große Anzahl von Menschen außerhalb einer bedeutenden wirtschaftlichen Rolle stellen. Ebenso würde ein recht kleiner Anstieg in den höheren Fähigkeitsanforderungen die Anzahl der für die höheren Arbeitsplätze qualifizierten Personen sehr dramatisch reduzieren. Eine Verschiebung findet statt: Wir wissen nur noch nicht, wie groß sie sein wird.

Es gibt tatsächlich keinen Mangel an sozialen und politischen Beweisen dafür, dass dieser Wandel in allen fortgeschrittenen Industriegesellschaften stattfindet, dass das Tempo dafür zunimmt, und dass die Bewegung bereits weit fortgeschritten ist. Die Belohnungen für seltene Fähigkeiten haben zugenommen und nehmen weiter zu. Dies wurde von konventionellen Denkern mit Unbehagen festgestellt. Betrachten Sie zum Beispiel *The Winner-Take-All Society* von Robert H. Frank und Philip J. Cook.[^276] Es dokumentiert die wachsende Tendenz, dass die talentiertesten Konkurrenten in vielen Bereichen in den Vereinigten Staaten sehr hohe Einkommen erzielen. Gleichzeitig sinken die Möglichkeiten für mittlere Fähigkeiten; eine beträchtliche Anzahl von gering qualifizierten Personen fällt jetzt aus dem Bereich heraus, der mit einem komfortablen Leben belohnt wird, obwohl sie vielleicht noch einen Platz in kleineren Dienstleistungen finden.

Wenn das Informationszeitalter sowohl an der Spitze als auch am unteren Ende höhere Fähigkeiten verlangt, werden alle außer den obersten 5 Prozent relativ benachteiligt sein, aber die obersten 5 Prozent werden enorm profitieren. Sie werden sowohl einen höheren Anteil des Einkommens verdienen als auch einen größeren Anteil von dem, was sie verdienen, behalten. Gleichzeitig werden sie einen größeren Teil der weltweiten Arbeit leisten als je zuvor. Viele werden sich als souveräne Individuen herausbilden. Im Informationszeitalter wird die Einkommensverteilung eher aussehen wie 1750 als wie 1950.

Gesellschaften, die auf Einkommensgleichheit und hohen Konsum für Menschen mit geringen oder bescheidenen Fähigkeiten konditioniert wurden, werden Demotivation und Unsicherheit gegenüberstehen. Da die Volkswirtschaften von immer mehr Ländern die Informationstechnologie tiefer integrieren, werden sie das Aufkommen einer mehr oder weniger unbeschäftigbaren Unterschicht erleben - ein Phänomen, das in Nordamerika bereits deutlich sichtbar ist. Genau das passiert gerade. Dies wird zu einer Reaktion von nationalistischer, technikfeindlicher Voreingenommenheit führen, wie wir im nächsten Kapitel detailliert ausarbeiten werden.

Es könnte sich herausstellen, dass das Zeitalter der Fabriken eine einzigartige Phase war, in der halb-dumme Maschinen eine äußerst profitable Nische für ungelernte Menschen hinterließen. Nun, da die Maschinen in der Lage sind, für sich selbst zu sorgen, verschüttet das Informationszeitalter seine Gaben auf die oberen 5 Prozent von Otto Ammons Rübe. Schon für die oberen 10 Prozent, die sogenannte kognitive Elite, sah das Informationszeitalter vielversprechender aus. Doch am bestmöglichen wird es für die oberen 10 Prozent der oberen 10 Prozent sein, die kognitive Doppelspitze. Im feudalen Zeitalter waren hundert halb-qualifizierte Bauern nötig, um einen hoch-qualifizierten Kriegsherren (oder Ritter) zu Pferde zu unterstützen. Die souveränen Individuen der Informationswirtschaft werden keine Kriegsherren sein, sondern Meister spezialisierter Fähigkeiten, einschließlich Unternehmertum und Investitionen. Dennoch scheint das feudale Verhältnis von hundert zu eins zurückzukehren. Zum Besseren oder Schlechteren scheinen die Gesellschaften des 21. Jahrhunderts ungleicher zu werden als die, in denen wir im 20. Jahrhundert gelebt haben.

## DIE MEISTEN MENSCHEN WERDEN VOM ENDE DER POLITIK PROFITIEREN

Es ist unwahrscheinlich, dass die egalitäre Wirtschaft und die Nationen, die sie unterstützt, ohne eine Krise verschwinden können. Obwohl eine Krise per Definition nur eine kurze Zeit andauern kann, stellen wir uns dennoch vor, dass das Trauma des Endes der Nationen über Jahre hinweg nachhallen könnte. Ohne dieses Trauma zu ignorieren, dessen Ausmaße wir später genauer erforschen, dürfen wir nicht vergessen, dass in vielen Teilen der Welt der Übergang zur Informationswirtschaft zu einem Anstieg der Produktion führen wird, mit höheren Einkommen allgemein. Tatsächlich steigen in jenen Bereichen, die nie vollständig von den Vorteilen der Industrialisierung profitiert haben, aber nun dem freien Markt offenstehen, die Einkommen aller Bevölkerungsschichten oder werden steigen.

Die Abschaffung des Zwanges als Merkmal des Wirtschaftslebens wird es den Produzenten ermöglichen, Vermögenswerte zu behalten, die bisher beschlagnahmt und umverteilt wurden. Umverteilung bedeutete in der Regel, dass Vermögenswerte zu weniger wertvollen Zwecken eingesetzt wurden und so die Produktivität des Kapitals reduziert wurde. Vermögen, welches überproportional von Personen genommen wurde, die besonders investitionsfähig waren, wurden von Politikern an weniger Geschickte umverteilt. In den meisten Fällen wurde das umverteilte Einkommen in untergeordnete wirtschaftliche Aktivitäten investiert. Die Auswirkungen der Befreiung von systematischem Zwang werden zwischen den Rechtssystemen stark variieren. Diese Einfrierung von Ressourcen wird Wohlfahrtsstaaten in den Bankrott treiben und die Nachteile großer Skaleneffekte verstärken, die große Regierungen und alle durch sie subventionierten Einrichtungen untergraben. Andererseits wird der Übergang zur Cyberwirtschaft die wirtschaftlichen Nachteile verringern, die Menschen in Regionen erfahren, die traditionell unter der Unfähigkeit gelitten haben, in großem Maßstab zu organisieren.

> „Wenn die Welt wie ein großer Markt agiert, wird jeder Arbeitnehmer mit jeder Person überall auf der Welt konkurrieren, der in der Lage ist, die gleiche Arbeit zu verrichten. Es gibt viele von ihnen und viele von ihnen sind hungrig." [^277] - Andrew S. Grove, Präsident, Intel Corp.

## DIE VERSCHIEBUNG GEOGRAPHISCHER VORTEILE

Da es keine steigenden Renditen durch Gewalt mehr geben wird, wird es keinen Vorteil mehr darstellen, unter einer Regierung zu leben, die sie einfordern kann. Einst kompetente Regierungen werden nicht länger Freunde der Vermögensanhäufung sein, sondern deren Feinde. Hohe Steuern, lästige regulatorische Kosten und ehrgeizige Pläne zur Einkommensumverteilung werden die Gebiete unter ihrer Kontrolle zu unattraktiven Orten für Geschäftstätigkeiten machen.

Diejenigen, die in Regionen leben, die während der industriellen Periode arm oder unterentwickelt geblieben sind, haben am meisten von der Befreiung der Volkswirtschaften von den Fesseln der Geographie zu gewinnen. Dies steht im Gegensatz zu dem, was man oft hört. Die Hauptkontroverse rund um den Aufstieg der Informationswirtschaft und den Vormarsch des souveränen Individuums konzentriert sich auf die angeblich negativen Auswirkungen auf die „Fairness", die sich aus dem Ende der Politik ergibt. Es ist sicherlich wahr, dass die Einführung der globalen Informationswirtschaft den Plänen zur Einkommensumverteilung in großem Maßstab den Todesstoß versetzen wird. Die Hauptnutznießer der Einkommensumverteilung im Industriezeitalter waren die Bewohner von wohlhabenden Gebieten, deren Konsumniveau zwanzigmal höher war als der weltweite Durchschnitt. Einkommensumverteilung hat nur in den OECD-Ländern bemerkbare Auswirkungen auf die Einkommen unqualifizierter Personen gehabt.

Die größten Einkommensungleichheiten wurden *innerhalb* von Rechtssystemen beobachtet. Einkommensumverteilung hat wenig dazu beigetragen, diese Ungleichheiten zu beseitigen. In der Tat sind wir der Meinung, dass ausländische Hilfe und internationale Entwicklungsprogramme den paradoxen Effekt hatten, die realen Einkommen armer Menschen in armen Ländern zu senken, indem sie inkompetente Regierungen subventionierten. Dieses Problem analysieren wir genauer, wenn wir die Auswirkungen der Informationsrevolution auf die Moral betrachten.

### Ein Jahrhundert steigender Einkommensungleichheit

Während des industriellen Zeitalters war der Faktor, der am meisten dazu beitrug, das lebenslange Einkommen einer normalen Person zu bestimmen, die politische Zuständigkeit, in der sie sich zufällig befand. Im Gegensatz zum gängigen Eindruck in reichen Volkswirtschaften heute, stieg die Einkommensungleichheit während der industriellen Periode rapide an. Eine von der Weltbank zitierte Schätzung legt nahe, dass das durchschnittliche Pro-Kopf-Einkommen in den reichsten Ländern von elfmal so hoch wie in den ärmsten Ländern im Jahr 1870 auf fünfzigmal so hoch im Jahr 1985 anstieg.[^278] Während die Ungleichheit auf weltweiter Ebene dramatisch zunahm, schien dies für den Bruchteil der Weltbevölkerung, der in den wohlhabenden Industrieländern lebte, oft andersherum. Die Einkommensungleichheit stieg eher innerhalb der Rechtssysteme als zwischen ihnen.

Aus von uns bereits untersuchten Gründen hat der Charakter der industriellen Technologie selbst dazu beigetragen, dass die Einkommenslücken in den Zuständigkeitsbereichen, in denen halbwegs kompetente Regierungen die Ausübung von Macht in großem Maßstab beherrschten, geringer wurden. Als die Gewinne aus der Gewalt stiegen, was sie während des Industriezeitalters taten, wurden Regierungen, die in großem Maßstab operierten, in der Regel von ihren Angestellten kontrolliert. Dies machte es effektiv unmöglich, Kontrollen über die Ansprüche aufzuerlegen, die diese Regierungen auf Ressourcen erhoben. Ihre uneingeschränkte Kontrolle über Ressourcen verschaffte ihnen einen bedeutenden militärischen Vorteil, solange das Ausmaß der Macht gegenüber der Effizienz, mit der sie eingesetzt wurde, überwog. Ein keineswegs unbedeutender Nebeneffekt von Regierungen, die von ihren Mitarbeitern kontrolliert wurden, war eine starke Beschleunigung der Einkommensumverteilung. Fast jede Gesellschaft hat eine bestimmte Regelung zur Einkommensumverteilung, zumindest vorübergehend in außergewöhnlichen Umständen. Eine genaue Untersuchung der Geschichte der Bedürftigenhilfe zeigt jedoch, dass „Sozialleistungen" tendenziell großzügiger sind, wenn die Armut minimal ist. Es ist wahrscheinlicher, dass die Einkommensumverteilung eingeschränkt wird, wenn die Einkommen einer großen Zahl von Menschen sinken. Die Bedingungen in den wohlhabenden Industriegesellschaften in der zweiten Hälfte des 20. Jahrhunderts waren nahezu perfekt für die Umverteilung des Einkommens. Dies führte zu deutlich höheren Belohnungen für ungelernte Arbeit innerhalb dieser begünstigten Zuständigkeitsgebiete. Schließlich bot es sogar hohe Konsumniveaus für diejenigen, die überhaupt nicht arbeiteten.

### Das Paradoxon des industriellen Reichtums

Die Ironie besteht darin, dass auch in diesen Rechtssystemen mehr Menschen zu Wohlstand kamen. Dieses scheinbare Paradoxon ergibt Sinn, wenn man die Dynamik der Megapolitik versteht, die wir in den vorangegangenen Kapiteln untersucht haben. Führende Sektoren der Industriewirtschaft erforderten die Aufrechterhaltung von Ordnung in großem Maßstab, um optimal zu funktionieren. Dies machte sie besonders anfällig für Erpressung durch Gewerkschaften und Regierungen, die darauf bedacht waren, die Anzahl der Personen unter ihrer Kontrolle zu maximieren. Dennoch erstickte die weit verbreitete Umverteilung von Einkommen die Fähigkeit der Industriewirtschaft zu funktionieren nicht völlig. Wer das Glück hatte, während der Hochphase der Industrialisierung in Westeuropa, den ehemaligen britischen Siedlungskolonien oder Japan geboren zu werden, war daher wahrscheinlich viel reicher als eine Person mit vergleichbaren Fähigkeiten in Südamerika, Osteuropa, der späten Sowjetunion, Afrika und den asiatischen Gebieten. Der positive Einfluss der Informationstechnologie wird dazu beitragen, viele der Hindernisse für die Entwicklung zu überwinden, die während eines Großteils der modernen Zeit der Mehrheit der Weltbevölkerung den Genuss eines Großteils der Vorteile freier Märkte verwehrten.

> „Die einheimischen Eigenschaften von armen Ländern sind auffallend ungeeignet für effektive Großorganisationen, besonders für solche, die (wie Regierungen) über ein großes geografisches Gebiet operieren müssen." [^279] - Mancur Olson

## SKALENNACHTEILE UND VERZÖGERTES WACHSTUM

Wie Mancur Olson bewiesen hat, war die Rückständigkeit im zwanzigsten Jahrhundert nicht auf einen Mangel an Kapital oder spezialisierten Fähigkeiten an sich zurückzuführen. In seinem 1987 veröffentlichten Aufsatz „Diseconomies of Scale and Development", welches zwei Jahre vor dem Fall der Berliner Mauer erschien, schrieb Olson: „Wenn Kapital tatsächlich in den armen Ländern knapp gewesen wäre, hätte die ‚Grenzproduktivität' und somit die Rentabilität der Nutzung größer sein müssen als in den wohlhabenden Ländern. Die niedrigen Wachstumsraten vieler Länder, die nicht unerhebliche Beträge an ausländischer Hilfe erhalten haben, und die geringe Produktivität einiger moderner Fabriken, die in armen Ländern gebaut wurden, haben die Glaubwürdigkeit der Erklärung der Unterentwicklung durch „Kapitalknappheit" weiter verringert".[^280] Dies muss zutreffen. Hätte ein Mangel an Kapital oder Fähigkeiten die Hauptbeeinträchtigung dargestellt, wären die in armen Regionen erzielten Erträge höher gewesen als in entwickelten Ländern. Sowohl qualifiziertes Personal als auch Kapital wären in diese Regionen geströmt, bis die Erträge sich ausgeglichen hätten. Tatsächlich war meist das Gegenteil der Fall. Es gab eine erhebliche Auswanderung von gebildeten Menschen aus rückständigen Gebieten. Und die wenigen Glücklichen, die es schafften, an solchen Orten Kapital anzuhäufen, exportierten es so schnell wie möglich in die Schweiz und andere fortgeschrittene Länder.

### Bessere Regierungen können nicht importiert werden

Olson argumentiert, und wir stimmen zu, dass das wahre Hindernis für die Entwicklung in rückständigen Ländern der eine Produktionsfaktor war, der nicht einfach aus dem Ausland geliehen oder importiert werden konnte, nämlich die Regierung. Dieses Problem verschärfte sich im Laufe des zwanzigsten Jahrhunderts. 1900 waren Großbritannien und Frankreich zusammen mit einigen anderen europäischen Ländern in das Geschäft involviert, kompetente Regierungen in Regionen zu exportieren, in denen die einheimischen Mächte nicht in der Lage waren, effektiv im großen Maßstab zu funktionieren. Aber die sich verändernden megapolitischen Bedingungen im zwanzigsten Jahrhundert erhöhten die Kosten und verringerten den Ertrag dieser Aktivität. Kolonialismus, oder Imperialismus, wie er weniger liebevoll genannt wurde, hörte auf, ein lohnendes Geschäft zu sein. Technologische Verschiebungen erhöhten die Kosten für die Ausdehnung der Macht vom Zentrum zur Peripherie und senkten die militärischen Kosten für einen effektiven Widerstand. Daraufhin zogen sich die imperialistischen Mächte zurück oder hielten sich nur noch in winzigen Enklaven wie Bermuda oder den Cayman-Inseln auf.

> „Wenn der postkoloniale Nationalstaat zu einer Fessel des Fortschritts geworden war, wie bis zum Ende der 1980er Jahre immer mehr Kritiker in Afrika zuzustimmen schienen, dann dürfte der Hauptgrund dafür kaum zu bezweifeln sein. Der Staat war nicht befreiend und schützend für seine Bürger, ungeachtet dessen, was seine Propaganda behauptete; im Gegenteil, seine brutale Wirkung war eher einschränkend und ausbeuterisch, oder er versäumte es schlichtweg, in irgendeinem sozialen Sinne überhaupt zu funktionieren." [^281] - Basil Davidson

Die einheimischen Regierungen, die in den nicht von Europäern besiedelten Ländern an die Stelle der Kolonialherrschaft traten, rekrutierten ihre Führer und Verwalter aus Bevölkerungsgruppen, die wenig Erfahrung oder Fähigkeiten in der Führung von Großunternehmen hatten. In vielen Fällen, insbesondere in Afrika, wurde die von den abziehenden Kolonialmächten überlassene Infrastruktur schnell geplündert, zerstört oder dem Verfall überlassen. Telefonleitungen wurden von Plünderern abgerissen und zu Armbändern verarbeitet. Straßen wurden nicht mehr instandgehalten. Die Eisenbahnlinien wurden unbrauchbar, da die Gleisbetten zerfielen und die Lokomotiven ausfielen. In Zaire war die von den Belgiern aufwendig errichtete Verkehrsinfrastruktur bis 1990 nahezu völlig verschwunden. Nur ein paar altersschwache Flussboote waren noch in Betrieb, von denen eines vom Diktator als eine Art schwimmender Palast übernommen wurde.

Unzuverlässige Kommunikation und Transport spiegeln die Inkompetenz von rückständigen Nationalstaaten bei der Aufrechterhaltung der Ordnung wider. Sie hielten die Preise hoch und die Chancen für den Großteil der Weltbevölkerung minimal. Wie Olson hervorhebt:

> Erstens zwingen schlechte Transport- und Kommunikationsmöglichkeiten ein Unternehmen dazu, sich hauptsächlich auf lokale Produktionsfaktoren zu stützen. Wenn sich der Umfang eines Unternehmens erhöht, muss es weiter ausholen, um Produktionsfaktoren zu erhalten, und je schlechter die Transport- und Kommunikationssysteme sind, desto schneller steigen diese Kosten mit der steigenden Produktion. Der zweite und wichtigere Grund, warum schlechte Transport- und Kommunikationssysteme effektive Großunternehmen behindern, ist, dass sie die Koordinierung solcher Unternehmen erheblich erschweren.[^282]

### Die Erleichterung der Last schlechter Regierungen

Die ehrgeizigen Armen der Welt, mehr als alle anderen, könnten davon profitieren, wenn die Informationstechnologie die Fähigkeit, Einkommen zu erzielen, von dem Ort, an dem man lebt, entkoppelt. Neue Technologien, wie das digitale Mobiltelefon, ermöglichen Kommunikation, die unabhängig von der Fähigkeit der lokalen Polizei ist, jeden Telefonmast eines Rechtssystems vor Kupferdieben zu schützen. Wenn drahtlose Fax- und Internetverbindungen verfügbar werden, spielt es keine so große Rolle mehr, ob extrem arme Postangestellte Briefe stehlen, nur um die Briefmarke zu klauen.

In vielen Fällen ersetzen effektive Kommunikationssysteme sogar die Notwendigkeit des physischen Transports von Gütern und Dienstleistungen. Bessere Kommunikation und eine stark gestiegene Rechenleistung machen nicht nur die Koordination komplexer Aktivitäten billiger und effektiver; sie verringern auch die Skaleneffekte und zersetzen große Organisationen. Diese Entwicklungen verringern allgemein die Nachteile, unter denen Personen in rückständigen Ländern durch das Leben unter inkompetenten Regierungen gelitten haben. Die Informationsrevolution wird es viel weniger wichtigmachen, ob Regierungen fähig sind, kompetent zu funktionieren. Daher wird es für Personen, die in traditionell armen Ländern leben, einfacher sein, die Hürden zu überwinden, die ihre Regierungen bisher dem Wirtschaftswachstum in den Weg gestellt haben.

### Gleiche Chancen im Informationszeitalter

Im Informationszeitalter werden bekannte Standortvorteile schnell durch Technologie verändert. Die Ertragskapazität für Menschen mit ähnlichen Fähigkeiten wird weitaus gleichmäßiger, unabhängig davon, in welcher Rechtsordnung sie leben. Dies hat bereits angefangen. Da Institutionen, die Macht und lokale Vorteile zur Umverteilung von Einkommen verwendet haben, an Einfluss verlieren, wird die Einkommensungleichheit innerhalb von Rechtsordnungen steigen. Der globale Wettbewerb wird auch dazu neigen, das Einkommen der hochtalentierten Personen in jeder Branche zu erhöhen, egal wo sie leben, ähnlich wie es jetzt im professionellen Sport der Fall ist. Der Grenzwert, der durch überlegene Leistung auf einem globalen Markt erzeugt wird, wird enorm sein.

Während die öffentliche Debatte sich auf die wachsende „Ungleichheit" in den OECD-Ländern konzentrieren wird, werden Individuen überall eine weitaus gleichberechtigtere Chance genießen. Sie werden nicht länger in einem Rechtssystem leben müssen, das in großem Maßstab gut funktioniert, um erfolgreich zu sein. Angeborene Fähigkeiten und die Bereitschaft, sie zu entwickeln, werden auf einem gleichberechtigteren Spielfeld gemessen werden als je zuvor. Rechtliche Vorteile, die während der industriellen Periode zu einer wachsenden Ungleichheit zwischen reichen und armen Volkswirtschaften geführt haben, werden sich dramatisch ändern.

### Höhere Renditen in ärmeren Gebieten

Die Hindernisse, die Regierungen in ärmeren Regionen dem reibungslosen Funktionieren freier Märkte in den Weg legen, werden erheblich verringert, wenn die Cyberwirtschaft in Kraft tritt. Infolgedessen werden Kapital und Fähigkeiten, die knapp sind, tatsächlich höhere Renditen in vielen derzeit ärmeren Gebieten erzielen, genau wie die Entwicklungstheoretiker der 1950er Jahre postulierten. Und sowohl das Kapital als auch die Fähigkeiten werden viel leichter importierbar sein. Die aufstrebenden Volkswirtschaften werden in ihrem Produktionsprozess nicht mehr so stark auf lokale Faktoren angewiesen sein wie im industriellen Zeitalter. Ihre verbesserte Fähigkeit, Kapital und Expertise aus der Ferne zu beziehen, wird zu höheren Wachstumsraten führen. Dies wird passieren, unabhängig davon, ob inkompetente Regierungen ehrlicher werden oder besser in der Lage sind, Eigentumsrechte zu schützen. Da sie keine Macht über den Cyberspace haben, werden schlechte Regierungen einfach nicht mehr in der Lage sein, die Menschen in ihrem Rechtsraum daran zu hindern, von der wirtschaftlichen Freiheit zu profitieren.

### Positive Verstärkung

In der neuen Cyberwirtschaft wird die fast vollständige Übertragbarkeit der Informationstechnologie das Ansammeln vieler in der Industriezeit entstandener Standortvorteile untersagen. Erhöhter Wettbewerb zwischen immer mehr Rechtsgebieten wird auf neuen Arten von lokalem Vorteil beruhen. Souveränität wird kommerziell statt ausbeuterisch sein. Regierungen werden durch die Kraft des Wettbewerbs verpflichtet sein, Richtlinien zu erlassen, die denjenigen ihrer Kunden entgegenkommen, die den größten Beitrag zum wirtschaftlichen Wohlergehen leisten, anstatt denen, die wenig oder negative wirtschaftliche Beiträge leisten.

Dies wird eine enorme Veränderung gegenüber dem üblichen Vorgehen des zwanzigsten Jahrhunderts darstellen. Die Ideologie des Nationalstaates war, dass das Leben auf positive Weise reguliert werden kann und sollte, indem unerwünschte Ergebnisse subventioniert und erwünschte bestraft werden. Arm zu sein ist unerwünscht; daher wurden die Armen subventioniert. Reich zu werden ist wünschenswert; deshalb wurden Strafsteuern auf die Reichen verhängt, um das Leben „fairer" zu gestalten.

Da diese gesamte politische Herangehensweise in einer megapolitischen Grundlage verwurzelt war, die jeglichem Einspruch trotzte, spielte es kaum eine Rolle, was die perversen Folgen der Subventionierung von Fehlfunktionen waren. Auch die Fähigkeiten, die harte Arbeit und der Einfallsreichtum, mit denen der umverteilte Reichtum erwirtschaftet wurde, wurden kaum berücksichtigt. Die Ergebnisse wurden im Sinne von Ansprüchen gemessen. Die politische Auffassung des zwanzigsten Jahrhunderts ging davon aus, dass die Ergebnisse nur dann „fair" wären, wenn sie gleich sind.

### Das Neue Paradigma

Die neuen megapolitischen Bedingungen des 21. Jahrhunderts ermöglichen es, dass Marktergebnisse in Bereichen reguliert werden, die zuvor von der Politik dominiert wurden. Das Marktmodell geht davon aus, dass Ergebnisse besser reguliert werden können, wenn erwünschte Ergebnisse belohnt und unerwünschte bestraft werden. Arm zu sein, ist unerwünscht, und reich zu werden, ist wünschenswert. Daher sollten Anreize die Schaffung von Reichtum belohnen und Menschen dazu ermutigen, für die Ressourcen, die sie verbrauchen, zu bezahlen. Das Leben ist „fairer", wenn Menschen mehr von dem behalten dürfen, was sie verdienen.

Dies ist eine Ansicht, die im neuen Jahrtausend häufiger zu hören sein wird als im nun endenden Jahrhundert. Darüber hinaus wird sie noch eindringlicher sein, weil sie megapolitisch begründet ist. Kapital im Informationszeitalter wird mit jedem Augenblick mobiler. Die Möglichkeit, ein hohes Einkommen zu erzielen, ist nicht mehr an den Wohnsitz von bestimmten Orten gebunden, wie es einst der Fall war, als der größte Teil des Reichtums durch die Nutzung natürlicher Ressourcen entstand. Mit jedem Tag, der vergeht, wird es für Menschen, die hochmobile Informationstechnologie nutzen, einfacher, Vermögenswerte zu schaffen, die weit weniger der Hebelwirkung von Gewalt ausgesetzt sind als jede frühere Form von Reichtum.

Willkürliche politische Regulierungen, die Kosten verursachen, ohne gleichzeitig marktfördernde Vorteile zu generieren, werden bald nicht mehr realisierbar sein. Starke Wettbewerbskräfte neigen dazu, die Preise für Güter, Dienstleistungen, Arbeitskräfte und Kapital auf der ganzen Welt anzugleichen. Regierungen werden weniger Spielraum haben, willkürliche Politiken durchzusetzen, als sie es gewohnt sind. Jede Regierung, die versucht, strengere Regulierungen für eine Tätigkeit aufzuerlegen als andere Souveränitäten, wird diese Tätigkeit einfach fernhalten. In einigen Fällen wird das Vertreiben unerwünschter Aktivitäten den Markt natürlich erfreuen und diese Rechtsräume umso beliebter und wohlhabender machen. In diesem Sinne können bestimmte Regulierungen mit den Hausregeln verglichen werden, die von den Besitzern einer Hotelkette durchgesetzt werden. Wenn sie es Menschen verbieten, barfuß zu gehen oder in der Lobby zu rauchen, werden sie zweifellos einige Kunden verlieren. Aber das Vertreiben dieser Kunden wird der Zuständigkeit insgesamt vielleicht nicht einmal Kunden oder Einnahmen kosten. Gut beschuhte Nichtraucher könnten genau deshalb mehr bezahlen, weil barfuß rauchende Menschen ausgeschlossen werden. Genauso können Regulierungen, die es teuer oder unmöglich machen, eine Verarbeitungsanlage in einer bestimmten Zuständigkeit zu betreiben, die Verarbeitung anderswo ohne Einnahmeverlust für die Gesamtzuständigkeit verlagern.

Diese Beispiele zeigen, wie Regulierungen in seltenen Fällen eher einen positiven als negativen Marktwert haben können, insbesondere in einer Welt mit rasant wachsender Anzahl an Gerichtsbarkeiten. Regeln, die hohe Standards in Bezug auf öffentliche Gesundheit, saubere Luft und sauberes Wasser bewahren, werden an vielen Orten sehr geschätzt. Das Gleiche gilt für andere, manchmal exotischere Regulierungen und Vereinbarungen, wie sie vielleicht von Immobilienentwicklern oder Hotels auferlegt werden, die bestimmte Marktsegmente bedienen.

### Keine Zölle im Cyberspace

Wir gehen davon aus, dass die Kommerzialisierung der Souveränität rasch zur Dezentralisierung vieler großer territorialer Souveränitäten führen wird. Die Tatsache, dass die Informationstechnologie nicht den Grenzkontrollen unterworfen werden kann, die immer noch den Handel mit Industrie- und Agrarprodukten behindern können, hat wichtige Auswirkungen. Sie bedeutet, dass Protektionismus mit der Zeit immer weniger wirksam sein wird, da der Handel mit Informationen physische Produkte bei der Generierung von Wohlstand verdrängen wird. Es bedeutet auch, dass kleinere Regionen immer weniger von der Aufrechterhaltung umfangreicher politischer Zuständigkeiten abhängig sein werden, um den Zugang zu Märkten zu gewährleisten, auf denen sie Einkommen erzielen können.

Die Informationstechnologie setzt Menschen, die in früher geschützten Dienstleistungssektoren arbeiten, dem ausländischen Wettbewerb aus. Wenn eine Firma in Toronto vor zwanzig Jahren einen Buchhalter einstellen wollte, musste diese Person physisch in Toronto oder in einer nahegelegenen Gemeinde wohnen, die für den Pendelverkehr erreichbar war. Im Zeitalter der Information könnte ein Buchhalter in Budapest oder Bangalore, Indien, die Arbeit erledigen und alles benötigte Material in verschlüsselter Form über das Internet herunterladen. Sofortige Kommunikation durch Satellitenverbindungen erreicht jeden Teil der Welt per Modem und Fax in nur einem Moment. Jemand, der Aktienanalysten braucht, könnte statt eines Wall Street Analysten, siebenundzwanzig davon zum gleichen Preis in Indien einstellen. Da sich die Informationstechnologie alle achtzehn Monate um ein Vielfaches verbessert (Moores Gesetz), werden immer mehr Dienstleistungssektor-Angestellte einem Preiswettbewerb ausgesetzt, der jenseits der Fähigkeit von Politikern liegt, ihn zu verhindern. Dieser Wettbewerb wird schließlich für die akademischen Berufe ebenso gelten wie für die Buchhalter. Digitale Anwälte und Cyber-Ärzte werden in der Informationswirtschaft vermehrt auftreten.

### Sterbehilfe für Nationalstaaten

Mit den wirtschaftlichen Vorteilen, die ehemals innerhalb der Grenzen von Nationalstaaten festgehalten wurden, die nun zerfallen, werden die Nationalstaaten letztendlich unter ihren schweren Verpflichtungen zusammenbrechen. Aber die Tatsache, dass alle Nationalstaaten auf der Todesliste stehen, bedeutet nicht, dass sie alle zum gleichen Zeitpunkt sterben werden. Weit davon entfernt. Der Dezentralisierungsdruck wird in der Regel in großen politischen Einheiten am stärksten sein, in denen die Einkommen des größten Teils der Bevölkerung stagnieren oder sinken. Jurisdiktionen in Lateinamerika und Asien, in denen das Pro-Kopf-Einkommen schnell steigt, können Generationen lang bestehen bleiben, oder bis die lebenslangen Einkommensperspektiven dort denen in den ehemals reichen Industrieländern entsprechen. An diesem Punkt wird es keine einfachen Kostensubstitutionen mehr zu gewinnen geben, und die Politik des Wachstums wird herausfordernder werden.

Wir vermuten ebenfalls, dass Nationalstaaten mit einer einzigen großen Metropole länger bestehen bleiben werden als solche mit mehreren großen Städten, was mehrere Interessenszentren mit ihren verschiedenen Umgebungen impliziert.

Ein weiterer Anreiz zur Dezentralisierung wird die hohe Verschuldung der Zentralregierung sein. Drei der wohlhabendsten Industrieländer mit der höchsten relativen Verschuldung - Kanada, Belgien und Italien - sind nicht zufällig Nationen mit fortgeschrittenen Separatistenbewegungen. Alle drei Länder haben unter chronischen Haushaltsdefiziten gelitten und haben jetzt nationale Schulden, die über 100 Prozent des Bruttoinlandsprodukts hinausgehen. Da die Staatsverschuldungen in jedem Land gestiegen sind, hat die Anziehungskraft der Separatistenbewegungen ebenfalls zugenommen. In Italien hat sich die Lega Nord als eine dynamische und beliebte regionale politische Bewegung entwickelt. Ihre Plattform basiert auf einer einfachen mathematischen Beobachtung: Norditalien, oder „Padanien", wäre reicher als die Schweiz, wenn nicht große Teile seines Einkommens abgezogen würden, um Rom und den ärmeren Süden zu subventionieren. Die Lega Nord schlägt eine offensichtliche Lösung vor: Sie will sich von Italien abspalten und so einigen der schlimmsten Konsequenzen des Zinseszinses entkommen. Ebenso in Belgien, wo die Staatsverschuldung über 130 Prozent des BIP liegt, zanken die Flamen und Wallonen wie ein zerstrittenes Paar vor einer Scheidung. Eine wachsende Minderheit unter den Flamen argumentiert, dass sie die Wallonen unfair subventionieren, und dass eine Aufteilung Belgiens in zwei Teile ihre wirtschaftliche Situation verbessern könnte.

Kanadas Fall unterscheidet sich in dem Detail, dass Französisch-Kanada, die Hauptregion, die jetzt für Separatismus eintritt, historisch gesehen von Englisch-Kanada subventioniert wurde. Aber mit der steigenden Bundesschuld und dem wachsenden Defizit wird in Quebec allmählich die Erkenntnis geweckt, dass diese Form der Einkommensumverteilung abnehmen wird. Der Bloc Quebecois kokettiert deshalb mit einem Reiz, den er vor einem Jahrzehnt nicht hatte - dem Versprechen, das nach Steuerabzug verbleibende Einkommen durch Abschaffung der kanadischen Bundesteuerzahlung zu erhöhen. Separatistenführer schlagen ebenfalls vor, dass Quebec Kanada verlassen sollte, ohne einen anteiligen Teil der Bundesschuld zu übernehmen.

Englischsprachige Kanadier sträuben sich gegen dieses Argument und neigen dazu, es abzulehnen, weil sie sich der umfangreichen Transfers, die im Laufe der Jahre nach Quebec geflossen sind, durchaus bewusst sind. Nichtsdestotrotz ist die Anziehungskraft des Parti Quebecois stark, und es scheint nur eine Frage der Zeit zu sein, bis ein Referendum zur Sezession Kanada auflöst. Ein ähnliches Schicksal erwartet andere Nationalstaaten, wenn ihre finanziellen Verhältnisse sich verschlechtern.

Ein weiterer Faktor, der Kanadas langfristiges Überleben bedroht, ist die Tatsache, dass es ein dünn besiedeltes Land mit weitläufiger Infrastruktur aus der Industrieära ist, die gewartet werden muss. Der Übergang ins Informationszeitalter entwertet unweigerlich die physische Infrastruktur. Da Heimarbeiter die Fabrikarbeiter und Büroangestellten ersetzen, wird es weniger wichtig, ob Autobahnen und andere Verkehrswege wieder aufgebaut und gut gewartet werden. Angesichts der knapper werdenden finanziellen Ressourcen werden sich immer mehr Gruppierungen im kanadischen Leben, auf die im 18. Jahrhundert von Adam Smith befürwortete exklusive Finanzierung von öffentlichen Gütern zurückziehen. Er schrieb in *Der Wohlstand der Nationen*:

> Würden die Straßen von London auf Kosten der[^nationalen] Staatskassen beleuchtet und gepflastert, ist es dann wahrscheinlich, dass sie so gut beleuchtet und gepflastert wären, wie sie es derzeit sind, oder sogar zu so geringen Kosten? Die Ausgaben würden, anstatt durch eine lokale Steuer auf die Bewohner jeder einzelnen Straße, Gemeinde oder Bezirks in London erhoben, in diesem Fall aus den allgemeinen Staatskassen finanziert und folglich von allen Einwohnern des Königreichs besteuert werden, von denen der größte Teil keinen Nutzen aus der Beleuchtung und Pflasterung der Londoner Straßen zieht.[^283]

Man ersetze London mit Toronto und man befindet sich in einer Gleichung, die vielen Menschen in Alberta und British Columbia durch den Kopf gehen wird. Die Logik der Dezentralisierung wird sich als ansteckend erweisen.

Wenn Kanada zerfällt, wird dies zu einer deutlichen Zunahme der sezessionistischen Aktivität im Pazifischen Nordwesten der USA führen. Die Bewohner von Alaska, Washington, Oregon, Idaho und Montana würden sich im Wettbewerb mit Alberta und British Columbia als unabhängige Souveränitäten eindeutig benachteiligt sehen.

## NACH DEM NATIONALSTAAT

Anstatt von Nationalstaaten wird man zunächst kleinere Verwaltungsbezirke auf Provinzebene sehen und letztendlich kleinere Souveränitäten, Enklaven verschiedener Art, ähnlich mittelalterlicher Stadtstaaten, umgeben von ihren Einzugsgebieten. So ungewöhnlich es Menschen erscheinen mag, denen die Bedeutung der Politik eingebläut wurde, wird die Politik dieser neuen Mini-Staaten in vielen Fällen mehr durch unternehmerische Positionierung als durch politisches Machtgeringe bestimmt. Diese neuen, fragmentierten Souveränitäten werden unterschiedliche Geschmäcker bedienen, genau wie Hotels und Restaurants, indem sie spezifische Vorschriften in ihren öffentlichen Bereichen durchsetzen, die den Marktsegmenten entsprechen, aus denen sie ihre Kunden ziehen. Das bedeutet natürlich nicht, dass es keine spezifischen Probleme gibt, die aus der Organisation des Schutzes auf einer nomadischen Grundlage entstehen. Diese werden wir im nächsten Kapitel behandeln.

> „Stadtluft macht frei" - Mittelalterliches Sprichwort

### Keine Bürger des Schutzherren

Trotz dieser Schwierigkeiten findet der menschliche Erfindungsreichtum in der Regel einen Weg, um Institutionen zu schaffen, die gewinnbringende Möglichkeiten nutzen, selbst wenn die Nachfrage von Personen ausgeht, die nur wenig zahlen können. Wenn die potenziellen Kunden zu den reichsten Menschen auf der Welt gehören, sollte dieser Trend umso hervorstechender sein. Die Möglichkeit, abzuwandern oder „mit den Füßen abzustimmen" besteht, wenn veraltete Produkte, Organisationen oder sogar Regierungen ihren Reiz verlieren und kaum Aussichten auf sofortige Verbesserung bieten. Nehmen Sie zum Beispiel das Wachstum mittelalterlicher Städte, die als sichere Zufluchtsorte für Leibeigene dienten, die vor der feudalen Unterdrückung flüchteten. Ihre Rolle könnte vergleichbar sein mit der Rolle neuer Rechtssysteme, die die bevorstehende Abkehr von Nationalstaaten auffangen. Die Aufnahme von Ausländern, die vor einem Herrn flüchteten, als „Bürger des Schutzherren", widersetzte sich den damals geltenden Konventionen des Feudalrechts und der bischöflichen Autorität. Aber es war dennoch eine generell erfolgreiche Alternative für diejenigen, die sie nutzten und trug maßgeblich dazu bei, den Griff des Feudalismus zu lösen. Wie der mittelalterliche Historiker Fritz Rorig es ausdrückte, wäre der Leibeigene eines weltlichen Herrn „nach einem Jahr und einem Tag ein freier Bürger der Stadt".[^284] Es ist vernünftig zu erwarten, dass neue institutionelle Zufluchtsorte durch „neue rechtliche Prinzipien" entstehen, um staatlichen Bürgern einen fiskalischen Zufluchtsort zu bieten, genau wie die mittelalterliche Stadt den feudalen Untertanen, die in ihrem Schatten lebten, Zuflucht bot.

Der Ökonom Albert O. Hirschman, der sich in *Exit, Voice, and Loyalty*, erstmals 1969 veröffentlicht, mit den theoretischen Feinheiten des „Abstimmens mit den Füßen" befasste, prophezeite, dass technologische Fortschritte die Wahrscheinlichkeit eines Ausstiegs als Strategie zur Bewältigung von Staaten im Niedergang erhöhen würden. Er schrieb: „Nur wenn Länder aufgrund des Fortschritts in der Kommunikation und der allgemeinen Modernisierung einander zu ähneln beginnen, wird die Gefahr eines vorzeitigen und übermäßigen Ausstiegs drohen \...".[^285] Genau das passiert gerade. Die Informationstechnologie verringert rasch viele der Unterschiede zwischen den Jurisdiktionen und macht den Ausstieg zu einer deutlich attraktiveren Option. Selbstverständlich versteht man unter „vorzeitigen und übermäßigen Ausstiegen" in Hirschmans Sprachgebrauch die Sicht dessen, was für den verlassenen Staat optimal ist. Zweifellos glaubten die Herren im mittelalterlichen Europa, dass sie unter „vorzeitigen und übermäßigen Ausstiegen" ihrer Leibeigenen in Städte litten, wo diese ihre Freiheit erlangten.

Um zu unserem früheren Beispiel zurückzukehren: Es ist nicht so weit hergeholt, wie es scheinen mag, dass es eine Reihe von Mini-Staaten geben wird, die Exilanten, die vor den sterbenden Nationalstaaten fliehen, Zuflucht bieten. Diese Souveränitäten konkurrieren um die Bedingungen des Exils. Einige, vielleicht an der Westküste von Nordamerika, könnten Menschen ansprechen, die nicht rauchen und intolerant gegenüber Passivrauch von denen sind, die rauchen. Offensichtlich würden solche Regime bei Rauchern nicht beliebt sein. Regeln, die ihre Gewohnheit verbieten, werden für viele Raucher als willkürliche Bestrafung erscheinen.

Im industriellen Zeitalter der Massenpolitik wurden solche Meinungsverschiedenheiten in politischen Kampagnen ausgetragen, die letztlich die eine oder andere Gruppe zwangen, sich den Wünschen der Mächtigeren zu beugen. Es ist jedoch keineswegs zwingend, dass Auseinandersetzungen über sich gegenseitig ausschließende Entscheidungen so gelöst werden, dass die Präferenzen großer Teile der Bevölkerung unterdrückt werden müssen.

Einige Menschen mögen gern Gänseleberpastete, andere Hot Dogs und wieder andere Sojaquark. Normalerweise müssen sie nicht über ihre Ernährungsvorlieben diskutieren, da ihre kulinarischen Entscheidungen nicht miteinander verknüpft sind. Niemand zwingt alle, das gleiche Essen zu konsumieren. Unter den megapolitischen Bedingungen jedoch, zwangen die Regierungen in der industriellen Ära viele Arten von kollektiven und sogar privaten Gütern zur gemeinsamen Nutzung. Warum? Weil es große wirtschaftliche Vorteile zu erlangen gab, indem man in großem Maßstab agierte. Es war daher unpraktisch, weite Gerichtsbarkeiten in Enklaven aufzuteilen, in denen jeder, auch bei wichtigen Entscheidungen, seinen eigenen Weg gehen konnte. Der von Adam Smith vertretene ausschließende Ansatz bei der Bereitstellung öffentlicher Güter lässt sich viel leichter verwirklichen, wenn sich die Zahl der Gerichtsbarkeiten verzehnfacht oder gar verhundertfacht. Im Informationszeitalter werden die wachsenden Souveränitäten vielmehr kleine Enklaven sein, als kontinentale Imperien. Einige könnten nordamerikanische Indianerstämme sein, die eine Steuerhoheit über ihre Reservate beanspruchen, so wie sie heute das Recht beanspruchen, Spielkasinos zu betreiben oder unter Missachtung von Grenzwerten zu fischen.

Da die Informationstechnologie viele der Nachteile der Dezentralisierung von Handelsräumen beseitigt, wird es für die neuen Souveränitäten praktisch sein, mehr nach den Prinzipien von Clubs oder Interessengruppen zu arbeiten als nach denen, die die territorialen Nationalstaaten regierten. So wie es nicht unerlässlich ist, dass jeder potenzielle Kunde den gleichen Geschmack für Kleidung hat oder die gleichen Fernsehprogramme ansieht, wird es weniger wichtig sein, als es scheinen mag, dass jeder mit den Gemeinsamkeitspunkten übereinstimmt, die den Führungsstil der fragmentierten Souveränitäten definieren.

Weit verstreute Geschmacksrichtungen werden in weit divergierenden Stilen fragmentierter Souveränität resultieren, ganz so wie es zunehmend breitere Auswahlmöglichkeiten im Kleidungsstil oder bei Fernsehsendungen gibt. Einige Kleinststaaten können sogar wie Hotelgruppen in Franchisesystemen zusammengeschlossen sein oder gemeinsam operieren, um Vorteile bei Polizeifunktionen und anderen Restdienstleistungen der Regierung zu erzielen. Diejenigen, die saubere Straßen mögen und es verabscheuen, Kaugummi unter Tischplatten zu finden, werden Singapur ansprechend finden. Fans von Beavis und Butthead wahrscheinlich nicht. Diejenigen, die ein wildes Nachtleben mögen, werden Macao oder Panama, oder einen ähnlichen Ort bevorzugen. Kunden, die sich mit den Sitten eines Rechtssystems unwohl fühlen, werden sich in anderen willkommen fühlen. Während Salt Lake City möglicherweise rauchfrei sein mag, wird der neue Stadtstaat in Havanna, vielleicht umbenannt in Monte Cristo, wahrscheinlich in eine Wolke aus Zigarrenrauch gehüllt sein.

> „Das bedeutet, dass alle Monopole, Hierarchien, Pyramiden und Machtstrukturen der Industriegesellschaft diesem ständigen Druck, Intelligenz an die Ränder aller Netzwerke zu verteilen, weichen werden. Vor allem aber wird das Mooresche Gesetz die wichtigste Konzentration, die wichtigste physische Ansammlung von Macht im heutigen Amerika zu Fall bringen: die Großstadt - die große Ansammlung von Industriestädten, die jetzt von Lebenserhaltungssystemen über Wasser gehalten wird - mit 360 Milliarden direkten Subventionen von uns allen jedes Jahr. Großstädte sind übriggebliebenes Gepäck aus dem Industriezeitalter." [^286] - George Gilder

Eine eigenartige Ironie der Wiederkehr von Mikro-Souveränitäten oder „Stadtstaaten" ist es, dass es mit der Entleerung vieler Städte zusammenfallen könnte. Die Großstadt war weitgehend ein Artefakt des Industriezeitalters im Westen. Sie entstand zusammen mit dem Fabriksystem, um Skaleneffekte bei der Produktion von Produkten mit hohem natürlichen Ressourceninhalt zu nutzen.

Als das 19. Jahrhundert begann, galten Städte mit mehr als 100.000 Einwohnern als riesig und außerhalb von Asien, wo die Bevölkerungsstatistiken zweifelhaft waren, gab es keine Städte mit mehr als einer Million Menschen. Die größte Stadt in den Vereinigten Staaten im Jahr 1800 war Philadelphia, mit einer Bevölkerung von 69.403. New York zählte gerade einmal 60.489. Baltimore war mit 26.114 Einwohnern die drittgrößte Stadt in Amerika.[^287] Die meisten der künftigen großen Metropolen Europas hatten Bevölkerungszahlen, die nach heutigen Standards gering sind. London, mit einer Bevölkerung von 864.845, war wahrscheinlich die größte Stadt der Welt. Paris, mit 547.756, war die einzige andere Stadt in Europa mit mehr als einer halben Million Einwohner im Jahr 1801.[^288] Lissabons Bevölkerung betrug 350.000.[^289] Wien hatte eine Bevölkerung von 252.000.[^290] Berlin hatte 1819 knapp 200.000 erreicht.[^291] Madrid zählte 156.670 Einwohner.[^292] Brüssel hatte 1802 eine Bevölkerung von 66.297. Budapest zählte gerade einmal 61.000.[^293]

Die Versuchung ist groß, das Wachstum von Großstädten als direkte Folge des Bevölkerungswachstums zu betrachten. Aber dies ist nicht unbedingt der Fall. Jeder Mensch auf der Erde könnte nach Texas gepackt werden, wobei jede Familie in ihrem eigenen freistehenden Haus mit Garten lebt, und es wäre immer noch etwas von Texas übrig. Wie Adna Weber in der klassischen Studie „Das Wachstum von Städten im 19. Jahrhundert" argumentierte, erklärt das Bevölkerungswachstum allein nicht, warum Menschen in städtischen Umgebungen leben, anstatt auf dem Land verteilt zu sein. 1890 hatte Bengalen in etwa die gleiche Bevölkerungsdichte wie England. Doch die städtische Bevölkerung von Bengalen betrug nur 4,8 Prozent, während es in England 61,7 Prozent waren.[^294]

Historisch gesehen waren Städte durch Mauern vom Umland abgeschottet, um Plünderer und die unteren Klassen fernzuhalten. Das Wachstum der industriellen Beschäftigung im neunzehnten und zwanzigsten Jahrhundert führte zur Entstehung von Großstädten. Heute ist die Großstadt höchst anfällig für Zusammenbrüche, da der Industrialismus zu verblassen beginnt. Das perfekte Beispiel dafür ist Detroit, die führende Industriestadt der Mitte des zwanzigsten Jahrhunderts. Einst floss ein großer Anteil der industriellen Weltproduktion durch Detroit. Jetzt ist es eine leere Hülle, geplagt von Kriminalität und Chaos. In vielen Blocks der Innenstadt von Detroit wurden ein oder mehrere verfallene Gebäude niedergebrannt oder abgerissen, so dass der Eindruck entsteht, dass die Stadt eine Reihe von Bombenangriffen aus dem Zweiten Weltkrieg überlebt hat.

Detroit steht als Mahnmal dafür, dass viele Industriestädte nicht mehr lebensfähig sind. Sie werden zerfallen, da Informationen und Ideen an Wert gewinnen, im Vergleich zur traditionellen Produktion aus natürlichen Ressourcen. Vielerorts ist die Großstadt bereits zu groß geworden, um ihr eigenes Gewicht zu tragen. Um eine Metropole funktionstüchtig zu halten, müssen eine erhebliche Anzahl von Unterstützungssystemen effektiv im großen Maßstab funktionieren. Das enge Zusammenleben von Millionen von Menschen impliziert eine enorme Zunahme der Verwundbarkeit für Kriminalität, Sabotage und willkürliche Gewalt. Während der industriellen Ära wurde der Preis für den Schutz vor diesen Risiken durch die Wirtschaftlichkeit der Hochskalenproduktion ausgeglichen.

Im Informationszeitalter werden nur Städte, die ihre Unterhaltskosten durch ein hohes Lebensqualitätsniveau ausgleichen können, überlebensfähig bleiben. Personen in der Ferne werden nicht mehr gezwungen sein, sie zu subventionieren. Ein guter Indikator für die Lebensfähigkeit von Städten ist, ob die Menschen im Zentrum der Stadt reicher sind als die an ihren Außenrändern. Buenos Aires, London und Paris werden noch lange einladende Orte zum Leben und Arbeiten sein, lange nachdem das letzte gute Restaurant in South Bend, Louisville und Philadelphia geschlossen hat.

### Länderstaaten

Einige Stadtstaaten könnten sich lediglich als Enklaven erweisen, ohne angeschlossene Städte. Vielleicht wäre es besser, sie als Dorfstaaten oder Länderstaaten zu betrachten.

Natürliche Ressourcen werden auch unterschiedlich bewertet. Wenn man überall Geschäfte machen kann, entscheidet man sich vielleicht dafür, Geschäfte an einem schönen Ort zu machen, an dem man durchatmen kann, ohne zu viel krebserzeugende Verschmutzung einzuatmen. Kommunikationstechnologien, die Sprachhindernisse minimieren, machen es immer einfacher, fast überall zu leben, wo die Umwelt attraktiv ist. Dünn besiedelte Regionen mit gemäßigtem Klima und einem großen Vorrat an fruchtbarem Land pro Kopf, wie Neuseeland und Argentinien, werden ebenfalls einen vergleichbaren Vorteil genießen, weil sie hohe Standards in der öffentlichen Gesundheit aufweisen und kostengünstige Produzenten von Lebensmitteln und erneuerbaren Produkten sind. Solche Produkte werden von der steigenden Nachfrage profitieren, wenn der Lebensstandard von Milliarden Menschen in Ostasien und Lateinamerika steigt.

### Das Inäquivalenz-Theorem

Viele Annahmen von Ökonomen über menschliches Verhalten sind in der Tyrannei des Ortes verwurzelt. Ein deutliches Beispiel ist Ricardos „Äquivalenztheorem", das besagt, dass die Bürger eines Landes, das große Defizite aufweist, ihre persönlichen Erwartungen in Erwartung höherer Steuersätze anpassen werden, die in der Zukunft zur Tilgung der Schulden erforderlich sind. In diesem Sinne gibt es eine „Äquivalenz" zwischen der Finanzierung von Ausgaben durch Besteuerung und durch Verschuldung. Zumindest gab es eine solche Äquivalenz zu Beginn des 19. Jahrhunderts, als Ricardo seine Schriften verfasste. Im Informationszeitalter wird der rationale Mensch jedoch nicht auf die Aussicht höherer Steuern zur Finanzierung von Defiziten reagieren, indem er seine Sparquote erhöht; er wird seinen Wohnsitz verlagern oder seine Transaktionen anderswo tätigen. Aus demselben Grund, aus dem Produzenten unter Lieferanten nach den geringsten Kosten suchen, wird jeder noch stärker motiviert sein, alternative Schutzanbieter zu suchen. Die Vorteile, dies zu tun, werden die zu erwartenden Margen durch den Wechsel zu einem neuen Lieferanten von Kunststoffrohren bei Weitem übertreffen. Das zu erwartende Ergebnis ist, dass souveräne Individuen und andere rationale Menschen Gerichtsbarkeiten mit großen unbeglichenen Verbindlichkeiten verlassen werden.

Günstige Regierungen, die wenige Schulden haben und ihren Kunden geringe Kosten auferlegen, werden im Informationszeitalter die bevorzugten Wohnorte für die Schaffung von Wohlstand sein. Dies bedeutet, dass die Aussichten für Geschäfte in Gebieten, in denen die Verschuldung niedrig ist und die Regierungen bereits umstrukturiert wurden, wie in Neuseeland, Argentinien, Chile, Peru, Singapur und anderen Teilen Asiens und Lateinamerikas, viel attraktiver sind. Diese Gebiete werden auch bessere Plattformen für Geschäfte sein als die unreformierten, kostenintensiven Volkswirtschaften in Nordamerika und Westeuropa.

### Die Erosion lokaler Preisabweichungen

Die erheblich reduzierten Informationskosten werden die meisten lokalen Preisvorteile überflüssig machen. Käufer werden nicht nur in der Lage sein, eine immense Anzahl von Verkaufsstellen zu durchsuchen, um die niedrigsten Preise für handelbare Waren zu finden; sie werden auch Dienstleistungen aus der Ferne nutzen können, um über juristische Grenzen hinweg einzukaufen. Dies wird es den Menschen erheblich erleichtern, Eigenschaften von schwer zu analysierenden Produkten wie Versicherungen zu vergleichen. Und sie werden Handelsbeschränkungen umgehen, die durch lokale Lizenzierungsverfahren auferlegt werden. Daher werden Gewinnmargen wahrscheinlich in jedem Bereich sinken, in dem lokale Preisunterschiede durch zusätzliche Informationen und Wettbewerb reduziert werden können.

## NEUE ORGANISATORISCHE ANFORDERUNGEN

Die Cyberwirtschaft wird sich in der Art und Weise, wie ihre Teilnehmer interagieren, erheblich von der Industriewirtschaft unterscheiden. Informationstechnologie wird viele der langfristigen organisatorischen Vorteile von Unternehmen, die aus hohen Transaktions- und Informationskosten entstehen, beseitigen. Das Informationszeitalter wird das Zeitalter der „virtuellen Unternehmen" sein.

Viele Analysten, die über weitaus mehr Kenntnisse in der Informationstechnologie verfügen als wir, haben völlig verfehlt zu erkennen, dass sie dazu bestimmt ist, die Logik der Wirtschaftsorganisation zu transformieren. Die neue Technologie überwindet nicht nur Grenzen und Barrieren; sie revolutioniert auch die „internen" Kosten der Berechnung. Sogar die wenigen Unternehmen, die nicht der erhöhten grenzüberschreitenden Konkurrenz aufgrund der verbesserten Informations- und Kommunikationstechnologie ausgesetzt sein werden, werden neuen organisatorischen Anforderungen ausgesetzt sein. Rasch fallende Informations- und Transaktionskosten werden die Größenvorteile entscheidend senken, wodurch viele der Anreize, die während der industriellen Periode zu langfristigen Unternehmen und Karriere-Einstellungen geführt haben, hinfällig werden.

### Warum Unternehmen?

Die klassischen Ökonomen wie Adam Smith waren fast stumm zur Frage der Unternehmensgröße. Sie sprachen nicht darüber, was die optimale Größe von Unternehmen beeinflusst, warum Unternehmen bestimmte Formen annehmen, oder sogar, warum Unternehmen überhaupt existieren. Warum stellen Unternehmer Mitarbeiter ein, anstatt jede zu erledigende Aufgabe unter unabhängigen Auftragnehmern auf dem Auktionsmarkt auszuschreiben? Der Nobelpreisträger Ronald Coase leitete eine neue Denkrichtung in den Wirtschaftswissenschaften ein, indem er einige dieser wichtigen Fragen stellte. Die Antworten, die er half zu formulieren, deuten auf die revolutionären Folgen der Informationstechnologie für die Struktur des Geschäfts hin. Coase argumentierte, dass Unternehmen ein effizienter Weg sind, um Informationsdefizite und hohe Transaktionskosten zu überwinden.[^295]

### Informations- und Transaktionskosten

Um zu verstehen, warum, betrachten Sie die Hindernisse, denen Sie gegenübergestanden hätten, wenn Sie versucht hätten, eine industrielle Montagelinie ohne, ein einziges Unternehmen zu betreiben, das die Aktivitäten koordiniert. Im Prinzip hätte ein Automobil produziert werden können, ohne dass die Produktion unter der Aufsicht eines einzigen Unternehmens zentralisiert würde. Der Ökonom Oliver Williamson, mit Coase zusammen, ist ein weiterer Pionier in der Entwicklung der Theorie des Unternehmens. Williamson definierte sechs verschiedene Betriebs- und Kontrollmethoden. Darunter die „Entrepreneurmethode", „in der jede Arbeitsstation von einem Spezialisten besessen und betrieben wird." [^296] Eine weitere ist die, die Williamson die „verbundenen Arbeitsstationen" nennt, bei denen „ein Zwischenprodukt von jedem Arbeiter über die Stufen hinweg transferiert wird." [^297] Es gibt keinen physischen Grund, warum tausende von Mitarbeitern nicht durch eine Schar unabhängiger Auftragnehmer ersetzt hätte werden können, die jeweils Raum auf dem Fabrikboden mieten, Teile ersteigern und anbieten, die Achse zu montieren oder die Kotflügel an das Chassis zu schweißen. Dennoch würde man vergeblich nach einem Beispiel für eine industrielle Automobilfabrik suchen, die von unabhängigen Auftragnehmern organisiert und betrieben wird.

### Koordinationsprobleme

Der Betrieb einer Industrieanlage ohne den Vorteil der Koordinierung durch ein einziges Unternehmen hätte die meisten der durch den Betrieb in großem Maßstab zu erzielenden Einsparungen zunichte gemacht. Die massiven Transaktionsprobleme bei der Koordinierung eines Flickenteppichs von Kleinunternehmen hätten das Fließband praktisch zum Erliegen gebracht. Ein solches System hätte unaufhörliche Verhandlungen zwischen den einzelnen Auftragnehmern erforderlich gemacht. Anstatt sich auf die Produktion zu konzentrieren, hätte die Vielzahl von Auftragnehmern oder Unternehmern ihre Zeit und Aufmerksamkeit darauf verwenden müssen, die Preise für die Komponenten festzulegen und die Bedingungen ihrer eigenen, sich ständig ändernden Interaktionen auszuarbeiten. Allein die Überwachung der Produktion wäre ein schwieriges Problem gewesen.

### Die Befugnis zu handeln

Bei einer derartigen Anzahl unabhängiger Organisationen, die sich um den Zusammenbau eines Autos bemühen, wäre die Entwicklung und Überarbeitung der Modelle ein Alptraum gewesen. Man braucht sich nur vorzustellen, wie schwierig es für den Konstrukteur gewesen wäre, hunderte von unabhängigen Auftragnehmern von den Änderungen zu überzeugen, die für die Einführung eines neuen Modells erforderlich sind. In der Praxis wäre beinahe einstimmiges Einverständnis erforderlich gewesen. Jeder, der Widerstand leistet oder irgendeine Änderung in der Spezifikation des Produkts ablehnt, hätte entweder die Verbesserung des Modells effektiv verhindert oder die Kosten für dessen Einführung erhöht, was die Gewinne durch den Betrieb in großem Maßstab weiter gefährdet hätte.

### Unnötige Verhandlungen

Eine Montagelinie, die von unabhängigen Vertragspartnern gemietet (oder getrennt erworben) worden wäre, hätte zahlreichen Risiken ausgesetzt sein können, die durch den Betrieb innerhalb eines einzigen Unternehmens vermieden wurden. Tod, Krankheit oder finanzieller Misserfolg einzelner Vertragspartner hätte bei Betrieben, die die Zusammenarbeit von tausenden von Menschen erfordert, um ein einzelnes Produkt unter einem Dach herzustellen, niemals zum Erfolg geführt. Der Auktionsmarkt wäre sicherlich in der Lage gewesen, diese Auftragnehmer zu ersetzen. Aber bei jeder Nachfolge wäre eine Verhandlungslösung erforderlich gewesen, wie die Übernahme des bisherigen Betreibers durch seinen Nachfolger. Außerdem wäre eine Vereinbarung über die Übernahme der Miete für die Werkshalle und vielleicht ein neuer Mietvertrag für die Schweißmaschine oder die Presse zum Ausstanzen der Rücklichtfassungen erforderlich gewesen. All dies wäre sehr kompliziert gewesen.

### Anreizfallen

Ein weiteres kritisches Problem einer Produktionslinie unabhängiger Vertragspartner unter den Bedingungen des industriellen Zeitalters war, dass die Kapitalanforderungen für die einzelnen Vertragspartner stark variieren würden. Eine Kunststoffform, die benötigt wird, um zum Beispiel einen Schalter im Armaturenbrett herzustellen, könnte relativ kostengünstig sein, während die Ausrüstung zum Gießen eines Motorblocks oder zum Ausstanzen des Blechs an einem Kotflügel Millionen kostet. Der hohe Ressourcengehalt und die sequenzielle Natur der Fließbandproduktion machten Probleme aufgrund hoher Kapitalkosten unvermeidlich, aus Gründen, die im letzten Kapitel analysiert wurden. Vertragspartner mit kapitalintensiven Aufgaben wären im Wesentlichen abhängig von der Zusammenarbeit anderer, um ihre Investitionen amortisieren zu können. Die Fähigkeit der Auftragnehmer mit höherem Kapitalbedarf, Geld zu beschaffen und gewinnbringend zu arbeiten, hätte davon abgehangen, dass sie sich die Mitarbeit vieler anderer Teilnehmer am Prozess sichern, deren Kapitalkosten weitaus geringer waren. In vielen Fällen hätten sie diese nicht bekommen.

Es hätte einen erheblichen Anreiz für die Kleinen gegeben, die Großen auszunutzen. Jene, die weniger Geld benötigten, um ihren speziellen Funktionsteil an der Fertigungsstraße zu betreiben, hätten davon profitieren können, in entscheidenden Momenten nicht zu kooperieren. Wie streikende Arbeiter hätten sie unter diesem oder jenem Vorwand die Fertigungsstraße stilllegen können, wodurch sie selbst nur geringe Kosten tragen, aber denen mit größeren Kapitalinvestitionen viel Leid zufügen würden. Der Produktionsprozess hätte ständigen Manipulationen unterlegen, wobei kleinere Vertragspartner diejenigen mit höheren Kapitalkosten durch ihre Fähigkeit, die Produktion zu behindern, erpressen könnten. Das Manövrieren kleinerer Auftragnehmer, um Nebenleistungen von den großen Unternehmen zu erpressen, hätte die Effizienz des Systems reduziert.

### Die Unternehmenslösung

Kurz gesagt, viele der wirtschaftlichen Vorteile, die während des Industriezeitalters durch den Betrieb einer Großproduktion erzielt werden konnten, wären verloren gegangen, wenn die Produktion auf eine Vielzahl von Einzelunternehmern aufgeteilt worden wäre. Das einzelne große Unternehmen war trotz seiner sonstigen Einschränkungen ein effizienter Weg, diese Nachteile zu überwinden. Große Unternehmen waren bürokratisch. Aber in gewissem Maße waren Bürokratie und Hierarchie genau das, was während des Industriezeitalters benötigt wurde. Verwaltungs- und Managementteams überwachten und koordinierten die Produktion. Eine Unmenge mittlerer Manager leitete Befehle weiter die Hierarchie hinab und andere Informationen zurück die Befehlskette hinauf. Zudem bot die Unternehmensbürokratie buchhalterische Kontrollmechanismen und minimierte Agentur-Probleme, bei denen Mitarbeiter nicht im besten Interesse des Unternehmens handeln, das sie beschäftigt. Um anspruchsvolle Buchführung unter den Bedingungen des Industriezeitalters zu erreichen, war die Arbeit vieler Menschen erforderlich. Die Aufrechterhaltung einer solchen Verwaltungsbürokratie war teuer. Sie musste bezahlt werden, unabhängig davon, ob die Produktion aktiv war oder nicht. Da diese Verwalter über entscheidendes Wissen zur Betriebsführung verfügten, wurden sie in der Regel über dem üblichen Marktpreis für ihre Fähigkeiten vergütet.

### „Organisatorischer Müßiggang"

Die große Anzahl professioneller Manager und Verwalter hatten auch den Nachteil, dazu zu neigen, die Firma „zu kapern" und sie in ihren eigenen Interessen, statt denen der Aktionäre zu betreiben. In der industriellen Ära war es beispielsweise nicht ungewöhnlich, Firmen zu finden, die verschwenderisch viel für Büromöbel, Clubmitgliedschaften und andere Vergünstigungen zahlten, die zwar von der Geschäftsführung genossen wurden, die aber möglicherweise keine direkte Rendite für die Investoren erbrachten. In einem komplizierten Geschäft war es unmöglich, von außen zu überwachen, welche Gemeinkosten wesentlich und welche Ausgaben Luxus für die Mitarbeiter waren. Es war auch schwierig zu verhindern, dass manchmal ein beträchtlicher Teil der Firmenmitarbeiter ihre Aufgaben vernachlässigte. Die Tatsache, dass es technologisch schwierig war, die Leistung zu überwachen, machte ein großes mittleres Management erforderlich und gleichzeitig war es schwierig, die Überwacher zu überwachen. All diese Bedingungen trugen zu dem bei, was als „organizational slack" bekannt wurde, ein Begriff, der 1963 von Richard Cyert und James March in *A Behavioral Theory of the Firm* geprägt wurde.[^298] Eine sorgfältige Prüfung ergab, dass zahlreiche reale Unternehmen ihr Potenzial bei weitem nicht ausgeschöpft haben.

> „Ob du Ergebnisse erzielst oder nicht, die Bezahlung ist die gleiche.\
> Ob du hart arbeitest oder nicht, die Bezahlung ist die gleiche.\
> Ob du dich kümmerst oder nicht, die Bezahlung bleibt die gleiche." [^299] - Chris Dray

### „Nicht mein Problem"

Als Unternehmen, das auf Dauer angelegt ist, hat das große Industrieunternehmen den bereits erwähnten Nachteil, dass es von den Gewerkschaften ausgeplündert werden kann. Es teilte auch einige Merkmale der Bürokratie, die in noch übertriebenerer Form in Regierungsbüros vorhanden sind. Anweisungen wurden von oben herab erteilt. Aufgaben waren stereotyp und abgegrenzt. Diese Aufgaben wurden oft starr definiert. Grenzen entstanden zwischen den Jobkategorien, ähnlich denen, die von den Kartellen zur Regulierung der akademischen Berufe durchgesetzt wurden. Es wäre vielen während des Industriezeitalters genauso seltsam erschienen, von einem Buchhalter zu erwarten, dass er eine durchgebrannte Glühbirne in einer Lampe auf seinem Schreibtisch wechselt, wie einen Anwalt zur Behandlung einer Grippe zu rufen. Von den Mitarbeitern wurde weder erwartet, die abgesteckten Grenzen zwischen starr definierten Funktionen zu überschreiten, noch war es ihnen in den meisten Fällen überhaupt gestattet.

„Nicht mein Problem" war ein weit verbreitetes Motto, das den „organisatorischen Müßiggang" des Industriezeitalters unterstrich. Jeder hatte eine genau definierte Rolle mit stereotypen Aufgaben, die niemand überschreiten durfte, auch wenn dies die Produktivität gesteigert hätte. Jeder Angestellte in der Unternehmensbürokratie wurde nach „Qualifikation" eingestellt, von der angenommen wurde, dass sie die Leistung in seiner spezifischen Funktion voraussagen könnte. Mit wenigen Ausnahmen wurde jeder nach einer Arbeitsplatz-Klassifikation bezahlt, mit mehr oder weniger gleichem Gehalt im gesamten Unternehmen. Da die spezifische Leistung in den administrativen Hierarchien der Großkonzerne oft nicht gemessen wurde, ähnlich wie in staatlichen Bürokratien, wurde die Arbeit in einem gemütlichen Tempo erledigt. Während das Unternehmen also die Skaleneffekte der Massenproduktion nutzte, tat es dies auf Kosten anderer Ineffizienzen.

> „Auf einem Markt macht man etwas nicht, weil es einem gesagt wird oder weil es auf Seite 30 des strategischen Plans steht. Ein Markt kennt keine Arbeitsgrenzen\... Es gibt keine Befehle, keine Übersetzung von Signalen von oben, niemand teilt die Arbeit in Pakete auf. Auf einem Markt hat man Kunden und die Beziehung zwischen einem Anbieter und einem Kunden ist grundsätzlich nicht organisatorisch, denn sie besteht zwischen zwei unabhängigen Einheiten." [^300] William Bridges

### Neue Gebote

Die neuen megapolitischen Bedingungen des Informationszeitalters werden die Logik der Unternehmensorganisation erheblich verändern. Ein Teil davon ist offensichtlich. Wenn die Informationstechnologie irgendetwas tut, dann senkt sie die Kosten für die Verarbeitung, Berechnung und Analyse von Informationen dramatisch. Eine Auswirkung solcher Technologie besteht darin, die Notwendigkeit der Einstellung großer Mengen von mittleren Führungskräften zur Überwachung von Produktionsprozessen zu reduzieren. Tatsächlich ersetzen in vielen Fällen automatisierte Werkzeugmaschinen die Arbeiter, die stündlich entlohnt werden. Und dort, wo der Produktionsprozess weiterhin von Menschenhand geführt wird, wurde der Kontroll- und Koordinierungsprozess größtenteils automatisiert. Anlagen, die mit Mikroprozessoren ausgestattet sind, können den Fortschritt der Montagelinie viel effektiver überwachen als Manager es jemals konnten. Die neue Ausrüstung kann nicht nur die Geschwindigkeit und Genauigkeit messen, mit der Menschen arbeiten, sie kann auch automatisch Konten führen und Komponenten nachbestellen, sobald diese aus dem Inventar entnommen werden. Selbst die kleinsten Betriebe können sich nun Finanzkontrollprogramme leisten, die ihre Finanzen mit größerer Geschwindigkeit und Raffinesse buchen, als selbst die größten Unternehmen dies vor einigen Jahrzehnten durch ihre Produktionshierarchien hätten erreichen können.

Die Tatsache, dass Informationstechnologie eine dezentrale, nicht sequentielle Ausgabe von Produkten mit reduziertem Naturressourceninhalt ermöglicht, verringert drastisch die Anfälligkeit für Spielchen und Erpressung, wie wir bereits untersucht haben. Dies sind jedoch nicht die einzigen Eigenschaften von Informationstechnologie, die sie immer attraktiver für die Auslagerung von Funktionen machen, die früher von Mitarbeitern erledigt wurden. Die Kapitalkosten sind geringer. Die Produktionszyklen sind kürzer. Die unabhängigen Auftragnehmer selbst, einschließlich der Ein-Personen-Firmen, verfügen über deutlich ausgefeiltere Informationsnetzwerke. Bald werden sie in der Lage sein, sich auf eine Vielzahl von digitalen Dienern zu verlassen, um eine breite Palette von Bürofunktionen zu erfüllen, vom Beantworten des Telefons bis hin zu Sekretariatsdiensten. Digitale Diener werden Sekretäre, Werbeagenten, Reisebüros, Bankangestellte und Bürokraten sein.

### Das Verschwinden guter Arbeitsplätze

In zunehmendem Maße werden Individuen, die in der Lage sind, einen bedeutenden wirtschaftlichen Wert zu schaffen, den größten Teil des von ihnen geschaffenen Werts für sich selbst behalten können. Unterstützungspersonal, das bisher einen großen Teil, der von den Haupterzeugern in einem Unternehmen erzeugten Einnahmen absorbiert hat, wird durch kostengünstige automatisierte Agenten und Informationssysteme ersetzt. Dies deutet darauf hin, dass eine Organisation in der Lage sein wird, sich einer höheren Qualität des Dienstes zu versichern, indem sie diesen vertraglich auslagert, anstatt die Funktion innerhalb des Unternehmens zu halten, wo es deutlich schwieriger sein wird, Individuen für eine gut ausgeführte Aufgabe zu belohnen. Ein virtuelles Unternehmen wird den größten Teil des „organisatorischen Müßiggangs" beseitigen, indem sie die Organisation eliminiert.

„Gute Arbeitsplätze" werden der Vergangenheit angehören. Ein „guter Arbeitsplatz", wie es der Wirtschaftswissenschaftler von Princeton, Orly Ashenfelter, ausdrückte, „ist ein Arbeitsplatz, der mehr zahlt als man wert ist." [^301] Im Industriezeitalter existierten viele „gute Arbeitsplätze" aufgrund hoher Informations- und Transaktionskosten. Unternehmen wuchsen und internalisierten eine größere Bandbreite an Funktionen, weil sie so Skaleneffekte realisieren konnten. Die Aufblähung der Unternehmen wurde auch durch Steuergesetze gefördert. Die hohen Steuern, die in den späteren Stadien des Industriezeitalters vorherrschten, überhöhten künstlich die Vorteile der Gründung eines langlebigen Unternehmens und der Beschäftigung von Festangestellten. In den meisten Ländern haben Steuergesetze und Vorschriften die Kosten für Gründung und Auflösung von Firmen auf Projektbasis erheblich erhöht. Außerdem zwingen sie die Unternehmer dazu, selbständige Auftragnehmer als Arbeitnehmer zu betrachten. Gesetzliche Eingriffe haben das Angebot an „guten Arbeitsplätzen" vorübergehend weiter erhöht, indem sie es kostspielig und schwierig machten, einen Arbeitnehmer zu entlassen, auch wenn er nur wenig zur Produktivität des Unternehmens beiträgt.

Unvermeidlich und logisch sicherte der Charakter von Unternehmensorganisationen im industriellen Zeitalter, dass die hochqualifizierten und talentierten Menschen, die einen überproportionalen Anteil der Wertschöpfung in einer Organisation lieferten, proportional weniger bezahlt wurden als ihr Beitrag wert war. Dies wird sich im Informationszeitalter ändern.

Die Mikroprozessor-Revolution erhöht drastisch die Verfügbarkeit von Informationen und senkt die Transaktionskosten. Dies führt zu einer Veränderung der Struktur von Unternehmen. Anstelle einer permanenten Bürokratie werden Aktivitäten um Projekte organisiert, ähnlich wie dies bereits bei Filmunternehmen der Fall ist. Die meisten der früheren „internen" Funktionen des Unternehmens werden an unabhängige Auftragnehmer ausgelagert. Die industriellen Arbeitnehmer, die „gute Arbeitsplätze" hatten, aber wenig beitrugen und sich auf ihre Kollegen verließen, um für sie „einzuspringen", werden sich bald auf dem Effektivmarkt um Verträge bemühen müssen. Gleiches gilt für viele loyale, fleißige Mitarbeiter. „Gute Arbeitsplätze" werden zum Anachronismus, weil Arbeitsplätze im Allgemeinen anachronistisch werden.

Im Extremfall der großen japanischen Unternehmen erwarteten die Mitarbeiter, einen Arbeitsplatz auf Lebenszeit zu haben. Selbst wenn sie keine produktive Aufgabe zu erfüllen hatten, wurden sie behalten, manchmal nur, um „an einem leeren Schreibtisch in einer Fabrikecke" zu sitzen. Nun wird aber auch in Japan die aufgeblähte Büroarbeiterschaft reduziert. Die Schlagzeile einer Geschichte in der International Herald Tribune erzählte die Geschichte: „Abschied ist ein bitterer Schmerz: Japans Kultur der Anstellung auf Lebenszeit geht schmerzhaft zu Ende." [^302]

Im postindustriellen Zeitalter wird Arbeit aus Aufgaben bestehen, die man erledigt, nicht als etwas, das man „hat". Vor der industriellen Ära war eine dauerhafte Anstellung praktisch unbekannt. Wie William Bridges es ausdrückte: „Vor 1800 - und in vielen Fällen noch lange danach - bezog sich *Job* immer auf eine bestimmte Aufgabe oder Unternehmung, nie auf eine Rolle oder Position in einer Organisation. \... Zwischen 1700 und 1890 findet das Oxford English Dictionary viele Verwendungen von Begriffen wie *Job-Kutscher, Job-Arzt und Job-Gärtner* - alle beziehen sich auf Menschen, die einmalig angestellt wurden. Jobarbeit (ein weiterer häufiger Begriff) war gelegentliche Arbeit, keine regelmäßige Beschäftigung." [^303] Im Informationszeitalter werden die meisten Aufgaben, die früher zur Senkung der Informations- und Transaktionskosten in den Unternehmen angesiedelt waren, wieder auf den Effektivmarkt verlagert. Die \"Just-in-time\"-Bestandsführung und das Outsourcing sind beide dank der Informationstechnologie praktisch. Es sind Schritte in Richtung Ende des Arbeitsplatzes. Schon jetzt haben große Unternehmen wie AT&T alle dauerhaften Arbeitsplätze abgeschafft. Positionen in diesem großen Unternehmen bestehen jetzt aus Zeitarbeit. In Bridges Worten: „Die Beschäftigung wird wieder vorübergehend und situativ, und Kategorien verlieren ihre Grenzen." [^304] In der neuen Cyberwirtschaft werden „unabhängige Auftragnehmer" über Kontinente hinweg telearbeiten, um sich auf dem Äquivalent der Informationsära zur Montagelinie zusammenzuschließen.

### Hollywood übernimmt

Das Geschäftsmodell der neuen Informationswirtschaft könnte eine Filmproduktionsfirma sein. Solche Unternehmen können sehr ausgefeilt sein, mit Budgets in Höhe von Hunderten Millionen Dollar. Obwohl sie oft große Operationen sind, sind sie auch temporärer Natur. Eine Filmfirma, die einen Film für 100 Millionen Dollar produziert, kann sich für ein Jahr zusammenschließen und sich dann auflösen. Während die Leute, die an der Produktion arbeiten, talentiert sind, besteht keinerlei Erwartungshaltung, dass die Arbeit an diesem Projekt gleichbedeutend mit einem „Arbeitsplatz" ist. Wenn das Projekt vorbei ist, werden die Beleuchtungstechniker, Kameramänner, Toningenieure und Garderobenspezialisten ihrer eigenen Wege gehen. Sie könnten bei einem anderen Projekt wiedervereint sein, oder auch nicht.

Mit fallenden Skaleneffekten und gleichzeitig sinkenden Kapitalanforderungen für viele informationsintensive Aktivitäten wird es einen starken Anreiz für Unternehmen geben, sich aufzulösen. Geschäftstätigkeiten werden eher ad hoc und temporärer Natur sein. Unternehmen werden tendenziell kurzlebiger sein. Virtuelle Unternehmen, die Talente für spezifische Zwecke zusammenbringen, werden effizienter sein als langjährige Firmen. Da die Verschlüsselung immer verbreiteter wird und die Besteuerung von Kapital durch Wettbewerb gedrängt wird, werden künstliche Skaleneffekte, die die Existenz von „dauerhaften" Firmen aufrechterhalten, weichen. Dies wird passieren, ob die Steuern nun schnell oder langsam gesenkt werden. Wenn sie schnell gesenkt werden, werden die künstlichen Kosten für Projektarbeit schneller verschwinden. Wenn sie langsamer gesenkt werden, wird die Hauptlast der anachronistisch hohen Steuern auf bestehende Unternehmen fallen, während neue Unternehmen als virtuelle Konzerne agieren, was ihnen besser ermöglicht, kostspielige Lasten zu vermeiden, die vom sterbenden Nationalstaat auferlegt wurden.

Während besondere Fähigkeiten und Talente in der Informationswirtschaft wichtiger denn je sein werden, werden die meisten künstlichen Grenzen zwischen den Berufen verschwinden. Fortgeschrittene Informations- und Speichertechnologien werden die Geschäftsgeheimnisse, und Fachinformationen von Berufen im Bereich Jura, Medizin und Buchhaltung für jedermann zugänglich sein. Der wirtschaftliche Wert des Auswendiglernens als Fähigkeit wird sinken, während die Bedeutung der Synthese und der kreativen Anwendung von Informationen steigen wird.

Die vollen Auswirkungen dieser Veränderungen werden durch veraltete Regulierung verlangsamt. Aber auf längere Sicht wird die Macht der Regierungen, die Cyberwirtschaft zu regulieren, bis hin zum Nullpunkt schwinden. Jede künstliche Regulierung von Berufsmonopolen, die die Kosten in die Höhe treibt, ohne dass der Nutzen auf dem Markt bewertet wird, wird letztlich ignoriert werden.

Es gibt weitere Implikationen der Verschiebung hin zu einer Informationswirtschaft:

-   Lokale Vorschriften, die höhere Kosten verursachen, werden auf eine Marktbasis umgestellt.
-   Der Wettbewerb zwischen den einzelnen Ländern um die Ansiedlung von Tätigkeiten mit hoher Wertschöpfung, die im Prinzip überall angesiedelt werden könnten, wird sich verschärfen. Kein Knotenpunkt ist zwangsläufig attraktiver als ein anderer.
-   Die Geschäftsbeziehungen werden sich zunehmend auf „Vertrauenskreise" stützen. Aufgrund der Verschlüsselung, die es Individuen ermöglicht, unbemerkt zu stehlen, wird Ehrlichkeit eine hoch geschätzte Eigenschaft von Geschäftspartnern sein.
-   Patent- und Urheberrechtsregelungen werden sich aufgrund des leichten Zugangs zu bestimmten Informationen ändern.
-   Schutz wird zunehmend technologisch und nicht mehr juristisch sein. Die unteren Klassen werden abgeschottet. Der Übergang zu „Gated Communities" ist nahezu unvermeidlich. Die Ausgrenzung von Unruhestiftern ist ein wirksames und traditionelles Mittel zur Minimierung krimineller Gewalt in Zeiten schwacher zentraler Autorität.
-   Massengüter werden wie im Mittelalter stark besteuert und lokal verschickt, während Luxusgüter gering besteuert und über große Entfernungen verschickt werden.[^305]
-   Die polizeilichen Aufgaben werden zunehmend von privaten Wächtern übernommen, die mit Handelsvereinigungen verbunden sind.
-   In der Übergangsphase könnten private Unternehmen gegenüber börsennotierten Firmen im Vorteil sein, da private Unternehmen einen größeren Spielraum haben, um den von den Regierungen auferlegten Kosten zu entgehen.
-   Die Beschäftigung auf Lebenszeit wird verschwinden, da „Arbeitsplätze" zunehmend zu Aufgaben oder „Zeitarbeit" werden und nicht mehr zu Positionen innerhalb einer Organisation.
-   Die Kontrolle über die wirtschaftlichen Ressourcen wird sich vom Staat auf Personen mit überdurchschnittlichen Fähigkeiten und Intelligenz verlagern, da es immer einfacher wird, Wohlstand zu schaffen, indem man den Produkten Wissen hinzufügt.
-   Viele Angehörige erlernter Berufe werden durch interaktive Informationsbeschaffungssysteme verdrängt werden.
-   Personen mit geringerer Intelligenz werden neue Überlebensstrategien entwickeln, die eine stärkere Konzentration auf die Entwicklung von Freizeitbeschäftigungen, sportlichen Fähigkeiten und Kriminalität sowie den Dienst an der wachsenden Zahl souveräner Individuen beinhalten, da die Einkommensungleichheit innerhalb der Gerichtsbarkeiten zunimmt.

Politische Systeme, die sich in einer Zeit entwickelt haben, in der die Gewaltzunahme im Vordergrund stand, müssen schmerzhafte Anpassungen durchlaufen. Da Effizienz gegenüber der Macht eines Systems immer wichtiger wird, werden kleine, effiziente Souveränitäten, die ihren Bürgern mehr Schutz zu geringeren Kosten bieten, immer nachhaltiger.

Wie im Mittelalter gibt es auch heute wieder zunehmende Skalenvorteile bei der Organisation von Gewalt. Dies spiegelt sich bereits in der steigenden Anzahl souveräner Einheiten seit dem Fall des Kommunismus wider. Wir erwarten, dass die Anzahl der Souveränitäten in der Welt sich schnell vervielfacht, wenn sich die Logik des Informationszeitalters durch die Erfahrung bestätigt.

Die Macht wird erneut auf kleinster Ebene ausgeübt. Enklaven und Provinzen könnten sogar feststellen, dass sie im Vergleich zu länderübergreifenden Nationen erhebliche Vorteile haben, indem sie ihren „Kunden" wettbewerbsfähige Konditionen für Souveränitätsleistungen anbieten. Dies wird sich stark von der schnell sterbenden modernen Ära unterscheiden, in der keine Einheit überleben konnte, es sei denn, sie könnte eine militärische Macht kontrollieren, die ausreicht, um ein Königreich zu beherrschen. In der Vergangenheit, als es noch Größenvorteile bei der Machtausübung gab, kontrollierten diejenigen, die am meisten vom Schutz profitierten, wie die wohlhabenden Kaufleute in den spätmittelalterlichen Stadtstaaten, die Regierung. Aus unserer Sicht können Sie schon mal anfangen, wieder nach dergleichen zu suchen. Die Reduzierung von Raublasten und eine effizientere Ressourcenverteilung sollten in Gebieten, in denen die Kunden Kontrolle über die lokalen Souveränitäten ausüben, zu einem schnellen Wachstum führen.

Wie wir im Folgenden untersuchen werden, wird die Frage, ob diese Entwicklungen gegen den Widerstand von Legionen von Verlierern fortgesetzt werden können oder sollten, zu den wichtigsten Kontroversen des Informationszeitalters gehören.

[^270]: Benjamin Schwarz, „\~American Inequality: Its History and Scary Future", New York Times, 19. Dezember 1995, S. A25.

[^271]: Adna Ferrin Weber, The Growth of Cities in the Nineteenth Century (New York: Macmillan, 1899; Neuauflage von Cornell University Press, 1963), S. 249.

[^272]: Bill Bryson, The Lost Continent (New York: Harper Perennial, 1989), S. 72.

[^273]: Dieser Artikel erschien in der 4. Auflage von Adrian Darnell\'s collection, Early Mathematical Economists, 6 vols. (London: Pickering & Chatto, 1991).

[^274]: Siehe z.B. Weber, ebenda, S. 2.

[^275]: Clive Jenkins und Barrie Sherman, The Collapse of Work (London: Methuen, 1979), S. 103.

[^276]: Robert H. Frank and Philip J. Cook, The Winner-Take-All Societv (New York: The Free Press, 1995).

[^277]: Clay Chandler, „Buchanan\'s Success Frightens Business," Washington Post, 22. Februar 1996, S. D12.

[^278]: Stephanie Flanders und Martin Wolfe, „Haunted by the Trade Spectre", Financial Times, 24. Juli 1995, S. 11. Sie zitieren den jüngsten Bericht der Weltentwicklung der Weltbank über Arbeiter in einer integrierten Weltwirtschaft.

[^279]: Siehe Mancur Olson, „Diseconomies of Scale and Development", Cato Journal, vol.7, no.1 (Spring/Summer 1987).

[^280]: Ebenda

[^281]: Basil Davidson, The Black Mans\' Burden: Africa and the Curse of the Nation State (New York: Times Books, 1992), S. 290.

[^282]: Olson, ebenda.

[^283]: Adam Smith, The Wealth of Nations, S. 724. Dieser Punkt wurde durch ein Argument von Edwin G. West vorgeschlagen in Adam Smith and Modern Economics (Aldershot, England: Edward Elgar Publishing, 1990), S. 88-89.

[^284]: Fritz Rorig, The Medieval Town (Berkeley: University of California Press, 1967), S. 28.

[^285]: Albert O. Hirschman, Exit, Voice, and Loyalty (Cambridge: Harvard University Press, 1969), S. 81.

[^286]: Tom Peters und George Gilder, „City vs. Country: Tom Peters & George Gilder Debate the Impact of Technology on Location", Forbes, Februar 1995.

[^287]: Weber, ebenda, S. 21.

[^288]: Ebenda, S. 46 for London, S. 73 for Paris.

[^289]: Ebenda, S. 120.

[^290]: Ebenda, S. 95.

[^291]: Ebenda, S. 84.

[^292]: Ebenda, S. 119.

[^293]: Ebenda, S. 101.

[^294]: Ebenda, S. 5.

[^295]: Siehe Ronald Coase, „The Nature of the Firm", Neuauflage in Louis Putterman und Randall S. Kroszner, eds., The Economic Nature of the Firm: A Reader 2nd ed. (Cambridge: Cambridge University Press, 1996), S. 89-104.

[^296]: Zitiert von West, ebenda, S. 58; siehe außerdem Oliver E. Williamson, „The Organization of Work: A Comparative Insititutional Assessment," Journal of Economic Behaviour and Organisation, vol.1, no.1.

[^297]: Zitiert von West, ebenda, S. 59; siehe außerdem Williamson, ebenda.

[^298]: Richard Cyert und James March, A Behavioral Theory of the Firm (Englewood Cliffs, N.J.: Prentice-Hall, 1983).

[^299]: Chris Dray\~ „Civil Servants Lead Lives of Quiet Collusion", Globe and Mail, 2. Februar 1996, S. A14.

[^300]: William Bridges, Jobsh ft: How to Prosper in a Workplace Without Jobs (Reading, Mass.: Addison-Wesley, 1994), S. 62, 64.

[^301]: Siehe Al Ehrbar, „'Re-Engineering' Gives Firms New Efficiency, Workers the Pink Slip", Wall Street Journal, 22. Juli 1992, S. A14, zitiert durch Bridges, ebenda, S. 39.

[^302]: Sheryl WuDunn, „Parting Is Such Sour Sorrow: Japan\'s Job-for-Life Culture Painfully Expires", International Herald Tribune, 13. Juni 1996, S. 13.

[^303]: Bridges, ebenda, S. 31-32.

[^304]: Ebenda, S. 58.

[^305]: Abu-Lughod, ebenda, S. 186.
