# DAS LEBEN UND DIE GESUNDHEIT DES NATIONENSTAATES

*Demokratie und Nationalismus als Ressourcenstrategien im Zeitalter der Gewalt*

> „Der Erfolg im Krieg hängt vor allem davon ab, dass man genug Geld hat, um alles zu beschaffen, was das Unternehmen braucht."[^163] - Robert de Balsac, 1502

## DIE TRÜMMER DER GESCHICHTE

Am 9. und 10. November 1989 übertrug das Fernsehen in die ganze Welt Szenen, in denen euphorische Ostberliner die Berliner Mauer mit Vorschlaghämmern einschlugen. Die jungen Unternehmer in der Menge sammelten Mauerstücke ein, die später als Souvenir-Briefbeschwerer an Kapitalisten in aller Welt vermarktet wurden. Mit diesen Relikten wurde noch jahrelang ein reger Handel betrieben. Noch heute findet man gelegentlich Anzeigen in kleinen Magazinen, in denen alte DDR-Betonstücke zu Preisen angeboten werden, die sonst nur für hochwertiges Silbererz gezahlt werden. Wir sind der Meinung, dass diejenigen, die die Briefbeschwerer der Berliner Mauer gekauft haben, es nicht eilig haben sollten, sie zu verkaufen. Sie sind ein Andenken an etwas Größeres als den Zusammenbruch des Kommunismus. Wir glauben, dass die Berliner Mauer zum wichtigsten historischen Trümmerhaufen wurde, seit die Mauern von San Giovanni im Februar 1495 fast fünf Jahrhunderte zuvor in die Luft gesprengt wurden.[^164]

Die Zerstörung von San Giovanni durch den französischen König Karl VIII. war die erste Explosion der Schießpulverrevolution. Sie markierte das Ende der feudalen Phase der Geschichte und den Beginn der Industrialisierung, wie wir bereits dargelegt haben. Der Fall der Berliner Mauer markiert einen weiteren historischen Wendepunkt, den Übergang vom Industriezeitalter zum neuen Informationszeitalter. Nie zuvor hat es einen so großen symbolischen Triumph der Effizienz über die Macht gegeben. Als die Mauern von San Giovanni fielen, war dies ein deutlicher Beweis dafür, dass die wirtschaftliche Rentabilität von Gewalt in der Welt drastisch gestiegen war. Der Fall der Berliner Mauer besagt etwas anderes, nämlich dass die Rendite für Gewalt jetzt sinkt. Dies ist etwas, das nur wenige erkannt haben, das aber dramatische Folgen haben wird.

Aus Gründen, die wir in diesem Kapitel untersuchen, könnte sich die Berliner Mauer als weitaus symbolträchtiger für die gesamte Ära des industriellen Nationalstaates erweisen, als die Menschen in der Menge in jener Nacht in Berlin oder die Millionen, die aus der Ferne zusahen, verstanden haben. Die Berliner Mauer wurde zu einem ganz anderen Zweck gebaut als die Mauern von San Giovanni - um die Menschen im Inneren an der Flucht zu hindern - nicht um Räuber von außen am Eindringen zu hindern. Allein diese Tatsache ist ein aufschlussreicher Indikator für die Zunahme der Macht des Staates vom 15. bis zum 20. Jahrhundert. Und das in mehr als einer Hinsicht.

Über Jahrhunderte hinweg machte der Nationalstaat alle nach außen gerichteten Mauern überflüssig und unnötig. Das Zwangsmonopol des Staates in den Gebieten, in denen er zuerst Fuß fasste, machte diese sowohl im Inneren friedlicher als auch militärisch eindrucksvoller als alle Souveränitäten, die die Welt zuvor gesehen hatte. Der Staat nutzte die Ressourcen, die er aus einer weitgehend entwaffneten Bevölkerung herausholte, um Kleinkriminelle auszumerzen. Der Nationalstaat wurde zum erfolgreichsten Instrument der Geschichte für die Aneignung von Ressourcen. Sein Erfolg beruhte auf seiner überlegenen Fähigkeit, den Reichtum seiner Bürger auszuschöpfen.

> „MTV ist mehr als nur ein Anbieter von Musikvideos und ein Werbeträger für die Plattenindustrie. Es ist das erste wirklich globale Netzwerk, das erste Netzwerk, das ein einziges Programm in praktisch jedem Land der Welt ausstrahlt. Dabei schafft MTV für seine Zuschauer, Kinder und junge Erwachsene, ein einheitliches Gefühl einer gemeinsamen globalen Realität. Jüngste Untersuchungen haben ergeben, dass junge Menschen auf der ganzen Welt mehr und mehr nicht nur gemeinsame Pop-Ikonen und einen gemeinsamen Geschmack teilen, sondern auch gemeinsame Erwartungen an ihre Karriere, gemeinsame Wertvorstellungen darüber, was im Leben sinnvoll ist und wovor man sich fürchten muss, ein gemeinsames Gefühl dafür, dass die Politik bei der Gestaltung ihrer Zukunft weniger wichtig ist als ihre eigenen Fähigkeiten."[^165] - Jim Taylor and Watts Wacker, The 500-Year Delta: What Happens After What Comes Next

### „Love It or Leave It" (Es sei denn, du bist reich)

Noch bevor der Übergang vom Nationalstaat zu den neuen Souveränitäten des Informationszeitalters vollzogen ist, werden viele Bewohner der größten und mächtigsten westlichen Nationalstaaten, wie ihre Pendants in Ost-Berlin im Jahr 1989, versuchen, ihren Weg nach draußen zu finden. Für die Generationen, die vor dem Zweiten Weltkrieg oder zu Beginn des Kalten Krieges aufgewachsen sind, ist das Überschreiten von Grenzen traumatisch. Aber für die neuen Generationen, die sich aus einer globaleren Perspektive heraus orientieren, ist das Verlassen des Landes, in dem sie geboren wurden, nicht mehr so undenkbar wie für die Älteren, denen die Ideologie des Nationalstaates tief in Fleisch und Blut übergegangen ist. Jim Taylor und Watts Wacker berichten über die verblüffenden Ergebnisse einer Massenbefragung von 20.000 Mittelschülern auf fünf Kontinenten. In einer Stichprobe, die während des Schuljahres 1995/96 von der Brainwaves Group, einem New Yorker Verbraucherforschungsunternehmen, durchgeführt wurde, stimmten neun von zehn Schülern der Aussage zu, dass „es an mir liegt, das zu bekommen, was ich vom Leben will". Noch bemerkenswerter ist, dass „fast die Hälfte der Teenager sagte, sie würden das Land ihrer Geburt verlassen, um ihre Ziele zu erreichen"[^166]. Vielleicht hat Bill Clinton, weil er auf die Einstellungen der MTV-Generation eingestellt war, als erster Präsidentschaftskandidat, der auf MTV Wahlkampf machte, versucht, es den Amerikanern zu erschweren, „das Land ihrer Geburt zu verlassen, um ihre Ziele zu erreichen". 1995, etwa zur gleichen Zeit, als die Schüler ihre Absicht erklärten, die Unabhängigkeit anzustreben, schlug der Präsident der Vereinigten Staaten die Einführung einer Ausreisesteuer vor, einer „Berliner Mauer für Kapital", die von wohlhabenden Amerikanern die Zahlung eines beträchtlichen Lösegelds verlangen würde, um auch nur mit einem Teil ihres Geldes zu entkommen.

Clintons Lösegeld erinnert nicht nur an die Politik der späten DDR, ihre Bürger wie Vermögenswerte zu behandeln, sondern auch an die zunehmend drakonischen Maßnahmen, die ergriffen wurden, um die Finanzlage des im Niedergang befindlichen Römischen Reiches zu stützen. Diese Passage aus The Cambridge Ancient History erzählt die Geschichte:

> So begann das erbitterte Bestreben des Staates, die Bevölkerung bis auf den letzten Tropfen auszupressen. Da die wirtschaftlichen Ressourcen nicht ausreichten, kämpften die Starken mit einer Gewalt und Skrupellosigkeit, die der Herkunft der Machthaber entsprach, und mit einem an Plünderungen gewöhnten Soldaten, um sich den größten Anteil zu sichern. Die ganze Härte des Gesetzes wurde auf die Bevölkerung losgelassen. Soldaten fungierten als Gerichtsvollzieher oder zogen als Geheimpolizei durch das Land. Die Leidtragenden waren natürlich die Besitzenden. An ihr Eigentum war relativ leicht heranzukommen, und im Notfall waren sie die Klasse, von der am häufigsten und schnellsten etwas erpresst werden konnte.[^167]

Wenn gescheiterte Systeme die Macht dazu haben, bürden sie denjenigen, die zu entkommen versuchen, oft strafrechtliche Belastungen auf. Auch hier zitieren wir The Cambridge Ancient History: „Während die besitzende Klasse ihr Geld vergrub oder zwei Drittel ihres Besitzes opferte, um der Obrigkeit zu entkommen, oder sogar so weit ging, ihren gesamten Besitz aufzugeben, um sich von der Grundsteuer zu befreien, und die nicht besitzende Klasse davonlief, antwortete der Staat mit zusätzlichem Druck."

Daran sollte man denken, wenn man vorausplant. Die Dämmerung von Staatssystemen war in der Vergangenheit selten ein höflicher, geordneter Prozess. In Kapitel 2 haben wir die üblen Angewohnheiten der römischen Steuereintreiber erwähnt. Die große Zahl der deserti agri, der verlassenen Bauernhöfe, in Westeuropa nach dem Zusammenbruch des Römischen Reiches war nur ein kleiner Teil eines größeren Problems. Tatsächlich waren die Abgaben in Gallien und in den Grenzgebieten, zu denen das heutige Luxemburg und Deutschland gehörten, in der Regel relativ gering. In der fruchtbarsten Region Roms, in Ägypten, wo die Landwirtschaft aufgrund der Bewässerung produktiver war, stellte die Flucht durch die Eigentümer ein noch größeres Problem dar. Die Frage, ob ein Fluchtversuch unternommen werden sollte, das „ultimum refugium", wie es im Lateinischen hieß, wurde zur vorrangigen Frage für fast jeden, der Eigentum besaß. Aufzeichnungen zeigen, dass „zu den üblichen Fragen, die in Ägypten an ein Orakel gestellt wurden, drei Standardfragen gehörten: ‚Werde ich zum Bettler?', ‚Soll ich fliehen?' und ‚Wird meine Flucht gestoppt werden?'"[^168]

Clintons Vorschlag sagt: Ja. Es handelt sich um eine frühe Version eines Fluchthindernisses, das in dem Maße, in dem die fiskalischen Ressourcen des Nationalstaates schwinden, wahrscheinlich noch schwerwiegender werden wird. Natürlich ist die erste US-Version einer Ausreisesperre harmloser als Erich Honeckers Beton und Stacheldraht. Sie ist auch preissensibler und belastet nur „Milliardäre" mit einem zu versteuernden Vermögen von über 600.000 Dollar. Dennoch wurde es mit ähnlichen Argumenten gerechtfertigt, wie sie einst von Honecker zur Verteidigung des berühmtesten öffentlichen Bauprojekts der späten Deutschen Demokratischen Republik vorgebracht wurden. Honecker behauptete, dass der ostdeutsche Staat eine erhebliche Investition in potenzielle Flüchtlinge getätigt habe. Er wies darauf hin, dass die freie Ausreise der Flüchtlinge zu einem wirtschaftlichen Nachteil für den Staat führen würde, der ihre Anstrengungen in Ostdeutschland benötige.

Wenn man die Prämisse akzeptiert, dass die Menschen Eigentum des Staates sind oder sein sollten, war Honeckers Mauer sinnvoll. Berlin ohne Mauer war für die Kommunisten ein Schlupfloch, so wie die Flucht vor der amerikanischen Steuerhoheit für Clintons Finanzamt ein Schlupfloch war. Clintons Argumente über die Flucht von Milliardären waren, abgesehen von der üblichen Missachtung der Integrität von Zahlen durch einen Politiker, ähnlich wie die von Honecker, aber etwas weniger logisch, weil die US-Regierung in der Tat keine großen wirtschaftlichen Investitionen in wohlhabende Bürger tätigt, die möglicherweise fliehen wollen. Es geht nicht darum, dass sie auf Staatskosten ausgebildet wurden und sich davonstehlen wollen, um woanders als Anwalt zu arbeiten. Die überwältigende Mehrheit derjenigen, für die die Wegzugssteuer gelten würde, hat ihren Reichtum durch eigene Anstrengungen trotz und nicht wegen der US-Regierung geschaffen.

Da die obersten 1 Prozent der Steuerzahler heute 28,7 Prozent der gesamten Einkommenssteuer in den Vereinigten Staaten zahlen, geht es nicht darum, dass die Reichen eine echte Investition, die der Staat in ihre Bildung oder ihren wirtschaftlichen Wohlstand getätigt hat, nicht zurückzahlen können. Das Gegenteil ist der Fall. Diejenigen, die den größten Teil der Rechnungen bezahlen, zahlen weit mehr als den Wert der Leistungen, die sie erhalten. Mit einer durchschnittlichen jährlichen Steuerzahlung von mehr als 125.000 Dollar kosten die Steuern das oberste 1 Prozent der amerikanischen Steuerzahler weit mehr, als sie heute wissen. Angenommen, sie könnten über einen Zeitraum von 40 Jahren auch nur eine 10-prozentige Rendite auf die zu viel gezahlten Steuern erwirtschaften, so würde jede jährliche Steuerüberzahlung von 5.000 Dollar ihr Nettovermögen um 2,2 Millionen Dollar verringern. Bei einer Rendite von 20 Prozent verringert sich das Nettovermögen um 44 Millionen Dollar pro 5.000 Dollar Steuerüberschuss.

Mit dem Herannahen des neuen Jahrtausends werden die neuen megapolitischen Bedingungen des Informationszeitalters immer deutlicher machen, dass der aus dem Industriezeitalter übernommene Nationalstaat eine räuberische Institution ist. Mit jedem Jahr, das vergeht, wird er weniger ein Segen für den Wohlstand als vielmehr ein Hindernis sein, dem der Einzelne entkommen will. Eine Flucht, die verzweifelte Regierungen nur ungern zulassen werden. Die Stabilität und sogar das Überleben der westlichen Wohlfahrtsstaaten hängt davon ab, ob sie in der Lage sind, weiterhin einen riesigen Teil der weltweiten Gesamtproduktion für die Umverteilung an eine Untergruppe von Wählern in den OECD-Ländern abzuziehen. Dies setzt voraus, dass die Steuern, die den produktivsten Bürgern der derzeit reichen Länder auferlegt werden, zu supermonopolistischen Sätzen erhoben werden, die Hunderte oder sogar Tausende Male höher sind als die tatsächlichen Kosten der Dienstleistungen, die die Regierungen im Gegenzug erbringen.

## DAS LEBEN UND STERBEN DES NATIONALSTAATES

Der Fall der Berliner Mauer war nicht nur ein sichtbares Symbol für den Tod des Kommunismus. Er war eine Niederlage für das gesamte Weltsystem der Nationalstaaten und ein Triumph der Effizienz und der Märkte. Der Dreh- und Angelpunkt der Macht in der Geschichte hat sich verschoben. Wir glauben, dass mit dem Fall der Berliner Mauer 1989 die Ära des Nationalstaates zu Ende geht, eine eigentümliche zweihundertjährige Phase der Geschichte, die mit der Französischen Revolution begann. Staaten gibt es seit sechstausend Jahren. Doch vor dem neunzehnten Jahrhundert machten sie nur einen kleinen Teil der weltweiten Souveränitäten aus. Ihre Vorherrschaft begann und endete in der Revolution. Die großen Ereignisse von 1789 brachten Europa auf den Weg zu wirklich nationalen Regierungen. Die großen Ereignisse von 1989 markierten den Tod des Kommunismus und die Behauptung der Kontrolle der Marktkräfte über die Macht der Massen. Diese beiden Revolutionen, die genau zweihundert Jahre auseinander liegen, definieren die Ära, in der der Nationalstaat im System der Großmächte vorherrschte. Die Großmächte wiederum beherrschten die Welt, indem sie selbst in der entlegensten Stammesenklave staatliche Systeme verbreiteten oder aufzwangen.

Der Siegeszug des Staates als wichtigstes Mittel zur Organisation von Gewalt in der Welt war keine Frage der Ideologie. Er wurde durch die kalte Logik der Gewalt notwendig. Es war, wie wir zu sagen pflegen, ein megapolitisches Ereignis, das nicht so sehr durch die Wünsche von Theoretikern und Staatsmännern oder gar durch die Manöver von Generälen bestimmt wurde, sondern durch die verborgene Hebelwirkung der Gewalt, die die Geschichte so bewegte, wie Archimedes davon träumte, die Welt zu bewegen.

Staaten waren in den letzten zweihundert Jahren der Neuzeit die Norm. Aber im weiteren Verlauf der Geschichte waren Staaten selten. Ihre Lebensfähigkeit hing immer von außergewöhnlichen megapolitischen Bedingungen ab. Vor der Neuzeit waren die meisten Staaten „orientalische Despotien", Agrargesellschaften in Wüsten, die für ihr Überleben auf die Kontrolle von Bewässerungssystemen angewiesen waren. Selbst das Römische Reich war durch seine Kontrolle über Ägypten und Nordafrika indirekt eine hydraulische Gesellschaft. Aber nicht genug, um zu überleben. Rom fehlte, wie den meisten vormodernen Staaten, letztlich die Fähigkeit, die Einhaltung des Gewaltmonopols zu erzwingen, das die Fähigkeit bietet, Menschen auszuhungern. Außerhalb Afrikas konnte der römische Staat das Wasser für den Ackerbau nicht abstellen, indem er ungehorsamen Menschen den Zugang zum Bewässerungssystem verwehrte. Solche hydraulischen Systeme lieferten mehr Druckmittel für Gewalt als jede andere megapolitische Konfiguration in der antiken Wirtschaft. Wer auch immer das Wasser in diesen Gesellschaften kontrollierte, konnte Beute in einer Größenordnung machen, die fast mit dem prozentualen Anteil an der Gesamtproduktion vergleichbar ist, den moderne Nationalstaaten absorbieren.[^169]

**Größe vor Effizienz**

Das Schießpulver ermöglichte es den Staaten, sich leichter über die Grenzen der Reisfelder und trockenen Flusstäler hinaus auszudehnen. Die Beschaffenheit der Schießpulverwaffen und der Charakter der industriellen Wirtschaft führten zu erheblichen Größenvorteilen in der Kriegsführung. Dies führte zu hohen und steigenden Renditen für Gewalt. Der Historiker Charles Tilly drückte es so aus: „Staaten, die über die größten Zwangsmittel verfügten, neigten dazu, Kriege zu gewinnen; die Effizienz (das Verhältnis von Output zu Input) kam an zweiter Stelle nach der Effektivität (Gesamtoutput)".[^170] Da die Regierungen meist in großem Maßstab organisiert waren, brauchten selbst die wenigen kleinen Souveränitäten, die überlebten, wie Monaco oder Andorra, die Anerkennung der größeren Staaten, um ihre Unabhängigkeit zu sichern. Nur große Regierungen, die über immer mehr Ressourcen verfügten, konnten auf dem Schlachtfeld konkurrieren.

### Die große unbeantwortete Frage

Dies bringt uns zu einem der großen ungelösten Rätsel der modernen Geschichte: Warum der Kalte Krieg, der am Ende des Systems der Großmächte stand, kommunistische Diktaturen gegen wohlfahrtsstaatliche Demokratien als seine letzten Kontrahenten antreten ließ. Diese Frage ist so wenig untersucht worden, dass es vielen tatsächlich plausibel erschien, als ein Analyst des Außenministeriums, Francis Fukuyama, nach dem Fall der Berliner Mauer „das Ende der Geschichte" ausrief. Das begeisterte Publikum, das seine Arbeit hervorrief, nahm zu viel als selbstverständlich hin. Offenbar hatten sich weder der Autor noch viele andere die Mühe gemacht, eine grundlegende Frage zu stellen: Welche gemeinsamen Merkmale des Staatssozialismus und der wohlfahrtsstaatlichen Demokratien führten dazu, dass sie die letzten Anwärter auf die Weltherrschaft waren?

Dies ist ein wichtiges Thema. Schließlich sind in den letzten fünf Jahrhunderten Dutzende von konkurrierenden Systemen der Souveränität entstanden und wieder verschwunden, darunter absolute Monarchien, Stammesenklaven, Fürstbistümer, direkte Herrschaft des Papstes, Sultanate, Stadtstaaten und Täuferkolonien. Heute wären die meisten Menschen überrascht, wenn sie wüssten, dass eine Krankenhausverwaltungsgesellschaft mit ihren eigenen Streitkräften ein Land jahrhundertelang regieren könnte. Und doch ist etwas Ähnliches passiert. Nach 1228 herrschten die Deutschordensritter des St. Marienhospitals zu Jerusalem, die später mit den Rittern des Schwertes von Livland vereinigt wurden, dreihundert Jahre lang über Ostpreußen und verschiedene Gebiete in Osteuropa, darunter Teile von Litauen und Polen. Dann kam die Schießpulverrevolution. Innerhalb weniger Jahrzehnte wurden die Deutschordensritter als Herrscher all ihrer Territorien vertrieben, und ihr Großmeister war militärisch nicht mehr von Bedeutung als ein Schachmeister. Und warum? Warum sind so viele andere Souveränitätssysteme zur Bedeutungslosigkeit geschrumpft, während im großen Kampf um die Weltmacht am Ende des Industriezeitalters Massendemokratien gegen staatssozialistische Systeme antraten?

### Uneingeschränkte Kontrolle

Wenn unsere Theorie der Megapolitik richtig ist, ist die Antwort einfach. Es ist in etwa so, als würde man fragen, warum Sumoringer dazu neigen, dick zu sein. Die Antwort ist, dass ein schlanker Sumoringer, wie beeindruckend sein Verhältnis von Kraft zu Gewicht auch sein mag, nicht mit einem anderen Ringer konkurrieren kann, der gigantisch ist. Wie Tilly andeutet, geht es um die „Effektivität (Gesamtleistung)", nicht um die „Effizienz (Verhältnis von Leistung und Aufwand)". In einer zunehmend von Gewalt geprägten Welt waren die Systeme, die sich in fünf Jahrhunderten des Wettbewerbs durchsetzten, notwendigerweise diejenigen, die den größten Zugang zu den Ressourcen ermöglichten, die für die Führung von Kriegen in großem Maßstab benötigt wurden.

Wie hat das funktioniert?

Im Fall des Kommunismus liegt die Antwort auf der Hand. Im Kommunismus kontrollierten diejenigen, die den Staat kontrollierten, fast alles. Wenn Sie während des Kalten Krieges Bürger der Sowjetunion gewesen wären, hätte der KGB Ihnen Ihre Zahnbürste wegnehmen können, wenn er es für seine Zwecke für nützlich gehalten hätte. Er hätte Ihnen auch Ihre Zähne wegnehmen können. Glaubwürdigen Schätzungen zufolge, die seit der Öffnung ehemaliger sowjetischer Archive im Jahr 1992 noch glaubwürdiger geworden sind, haben die Geheimpolizei und andere Agenten des späten Sowjetstaates in den 74 Jahren ihrer Herrschaft 50 Millionen Menschen das Leben genommen. Das staatssozialistische System war in der Lage, alles, was innerhalb seiner Grenzen existierte, für sein Militär zu mobilisieren, ohne dass irgendjemand, der dort lebte, etwas dagegen einzuwenden gehabt hatte.

Im Falle der westlichen Demokratien ist die Geschichte weniger offensichtlich, was zum Teil daran liegt, dass wir daran gewöhnt sind, die Demokratie im krassen Gegensatz zum Kommunismus zu sehen. Im Hinblick auf das Industriezeitalter waren die beiden Systeme tatsächlich große Gegensätze. Aber aus der Perspektive des Informationszeitalters betrachtet, hatten die beiden Systeme mehr gemeinsam, als man vermuten würde. Beide ermöglichten eine ungehinderte Kontrolle der Ressourcen durch den Staat. Der Unterschied bestand darin, dass der demokratische Wohlfahrtsstaat noch mehr Ressourcen in die Hände des Staates legte als die staatssozialistischen Systeme.

Dies ist ein eindeutiges Beispiel für ein seltenes Phänomen: Weniger ist mehr. Das staatssozialistische System beruhte auf der Doktrin, dass dem Staat alles gehört. Der demokratische Wohlfahrtsstaat hingegen erhebt bescheidenere Ansprüche und setzt damit bessere Anreize, um mehr Leistung zu mobilisieren. Anstatt von Anfang an Anspruch auf alles zu erheben, erlaubten die Regierungen im Westen dem Einzelnen, Eigentum zu besitzen und Wohlstand anzuhäufen. Nachdem der Reichtum angehäuft worden war, besteuerten die westlichen Nationalstaaten einen großen Teil des Vermögens. Durch hohe Vermögens-, Einkommens- und Erbschaftssteuern wurden dem demokratischen Wohlfahrtsstaat im Vergleich zu den staatssozialistischen Systemen ungeheure Mengen an Ressourcen zur Verfügung gestellt.

### Ineffizienz, wo es darauf ankam

Im Vergleich zum Kommunismus war der Wohlfahrtsstaat tatsächlich ein weitaus effizienteres System. Aber im Vergleich zu anderen Systemen zur Anhäufung von Reichtum, wie etwa einer echten Laissez-faire-Enklave wie Hongkong, war der Wohlfahrtsstaat ineffizient. Auch hier gilt: Weniger war mehr. Es war genau diese Ineffizienz, die den Wohlfahrtsstaat unter den megapolitischen Bedingungen des Industriezeitalters übermächtig machte.

Wenn man begreift, warum das so ist, kommt man der Erkenntnis viel näher, was der Fall der Berliner Mauer und der Untergang des Kommunismus wirklich bedeuten. Der Fall der Berliner Mauer und der Untergang des Kommunismus sind keine Garantie für den Siegeszug des demokratischen Wohlfahrtsstaates, wie weithin angenommen wurde, sondern es ist eher so, als ob ein zweieiiger Zwilling an Altersschwäche gestorben wäre. Die gleiche megapolitische Revolution, die dem Kommunismus den Garaus gemacht hat, wird wahrscheinlich auch die demokratischen Wohlfahrtsstaaten, wie wir sie im zwanzigsten Jahrhundert kannten, untergraben und zerstören.

## WER KONTROLLIERT DIE REGIERUNG?

Der Schlüssel zu dieser unorthodoxen Schlussfolgerung liegt in der Erkenntnis, wo die Kontrolle der demokratischen Regierung angesiedelt ist. Das ist eine Frage, die nicht so einfach ist, wie es vielleicht scheint. In der modernen Ära wurde die Frage, wer die Regierung kontrolliert, fast immer als politische Frage gestellt. Es gab viele Antworten darauf, aber fast immer ging es darum, die politische Partei, Gruppe oder Fraktion zu identifizieren, die zu einem bestimmten Zeitpunkt die Kontrolle über einen bestimmten Staat ausübte. Sie haben von Regierungen gehört, die von Kapitalisten kontrolliert wurden. Von Regierungen, die von der Arbeiterschaft kontrolliert wurden. Von Regierungen, die von Katholiken und islamischen Fundamentalisten kontrolliert wurden. Regierungen, die von Stammes- und Rassengruppen kontrolliert wurden; Regierungen, die von Hutus und Regierungen, die von Weißen kontrolliert wurden. Sie haben auch schon von Regierungen gehört, die von Berufsgruppen wie Anwälten oder Bankern kontrolliert wurden. Sie haben von Regierungen gehört, die von ländlichen Interessen, von Großstadtmaschinerien und von Menschen, die in den Vorstädten leben, kontrolliert werden. Und Sie haben sicherlich schon von Regierungen gehört, die von politischen Parteien kontrolliert werden, von Demokraten, Konservativen, Christdemokraten, Liberalen, Radikalen, Republikanern und Sozialisten.

Aber Sie haben wahrscheinlich noch nicht viel von einer Regierung gehört, die von ihren Kunden kontrolliert wird. Der Wirtschaftshistoriker Frederic Lane hat in einigen seiner einleuchtenden Aufsätze über die wirtschaftlichen Folgen von Gewalt die Grundlage für ein neues Verständnis der Kontrolle der Regierung gelegt. Die Betrachtung des Staates als wirtschaftliche Einheit, die Schutz verkauft, veranlasste Lane, die Kontrolle des Staates in wirtschaftlicher und nicht in politischer Hinsicht zu analysieren. Aus dieser Sicht gibt es drei grundlegende Alternativen für die Kontrolle der Regierung, von denen jede eine grundlegend andere Reihe von Anreizen mit sich bringt: Eigentümer, Angestellte und Kunden.

### Eigentümer

In seltenen Fällen werden Regierungen auch heute noch von einem Eigentümer kontrolliert, in der Regel einem erblichen Oberhaupt, dem das Land praktisch gehört. Der Sultan von Brunei beispielsweise behandelt die Regierung von Brunei in gewisser Weise wie sein Eigentum. Dies war eher bei den Herren des Mittelalters üblich, die ihre Lehen wie Eigentum behandelten, um ihre Einkünfte zu optimieren.

Lane beschrieb die Anreize der „Eigentümer des produzierenden Unternehmens" wie folgt:

> Das Interesse an einer Gewinnmaximierung würde ihn dazu veranlassen, unter Beibehaltung der Preise zu versuchen, seine Kosten zu senken. Wie Heinrich VII. von England oder Ludwig XI. von Frankreich würde er billige Tricks anwenden, zumindest so billige wie möglich, um seine Legitimität zu bekräftigen, die innere Ordnung aufrechtzuerhalten und die benachbarten Fürsten abzulenken, damit seine eigenen Militärausgaben niedrig sind. Aus den gesenkten Kosten oder aus den erhöhten Abgaben, die durch die Stabilität seines Monopols möglich wurden, oder aus einer Kombination, häufte er einen Überschuss an\...[^171]

Von Eigentümern kontrollierte Regierungen haben starke Anreize, die Kosten für die Bereitstellung von Schutz oder die Monopolisierung von Gewalt in einem bestimmten Gebiet zu senken. Solange ihre Herrschaft jedoch sicher ist, haben sie wenig Anreiz, den Preis (die Steuer), den sie von ihren Kunden verlangen, unter den Satz zu senken, der die Einnahmen optimiert. Je höher der Preis ist, den ein Monopolist verlangen kann, und je niedriger seine tatsächlichen Kosten sind, desto größer ist der Gewinn, den er erzielt. Die ideale Steuerpolitik für eine Regierung, die von ihren Eigentümern kontrolliert wird, wäre ein großer Überschuss. Wenn Regierungen ihre Einnahmen hoch halten, aber ihre Kosten senken können, hat dies große Auswirkungen auf die Nutzung der Ressourcen. Arbeitskräfte und andere wertvolle Inputs, die andernfalls für unnötig teuren Schutz verschwendet würden, stehen stattdessen für Investitionen und andere Zwecke zur Verfügung. Je höher der Monarch seinen Gewinn durch die Senkung der Kosten steigern kann, desto mehr Ressourcen werden freigesetzt. Wenn diese Ressourcen für Investitionen verwendet werden, sorgen sie für einen Wachstumsimpuls. Aber auch wenn sie für den Prestigekonsum verwendet werden, tragen sie dazu bei, neue Märkte zu schaffen und zu versorgen, die sonst nicht existieren würden, wenn die Ressourcen für die Produktion von ineffizientem „Schutz" verschwendet worden wären.

### Angestellte

Die Anreize für Regierungen, die von ihren Angestellten kontrolliert werden, sind leicht zu charakterisieren. Es sind ähnliche Anreize wie in anderen von Arbeitnehmern kontrollierten Organisationen. In erster Linie neigen von Arbeitnehmern geführte Organisationen dazu, jede Politik zu bevorzugen, die die Beschäftigung erhöht, und Maßnahmen abzulehnen, die Arbeitsplätze abbauen. Wie Lane es ausdrückt: „Als die Arbeitnehmer als Ganzes die Kontrolle ausübten, hatten sie wenig Interesse daran, die für den Schutz geforderten Beträge zu minimieren, und kein Interesse daran, den großen Teil der Kosten zu minimieren, der auf die Arbeitskosten, auf ihre eigenen Gehälter, entfällt. Eine Maximierung der Größe war auch eher nach ihrem Geschmack."[^172] Eine Regierung, die von ihren Mitarbeitern kontrolliert wird, hätte selten Anreize, entweder die Kosten der Regierung oder den Preis für ihre Kunden zu senken. Wenn jedoch die Bedingungen einen starken Preiswiderstand in Form von Widerstand gegen höhere Steuern erzwingen, würden von Arbeitnehmern kontrollierte Regierungen eher dazu neigen, ihre Einnahmen unter ihre Ausgaben fallen zu lassen, als ihre Ausgaben zu kürzen. Mit anderen Worten, ihre Anreize lassen vermuten, dass sie zu chronischen Defiziten neigen könnten, was bei Regierungen, die von Eigentümern kontrolliert werden, nicht der Fall wäre.

### Kunden

Gibt es Beispiele für Regierungen, die von ihren Kunden kontrolliert werden? Ja. Das Beispiel der mittelalterlichen Handelsrepubliken wie Venedig inspirierte Lane dazu, die Kontrolle der Regierung in wirtschaftlicher Hinsicht zu analysieren. Dort kontrollierte eine Gruppe von Großhändlern, die Schutz brauchten, jahrhundertelang effektiv die Regierung. Sie waren wirklich Kunden für den Schutz, den die Regierung bot, und nicht Eigentümer. Sie zahlten für die Dienstleistung. Sie versuchten nicht, von ihrer Kontrolle des staatlichen Gewaltmonopols zu profitieren. Falls doch, wurden sie von den anderen Kunden über lange Zeiträume daran gehindert. Andere Beispiele für Regierungen, die von ihren Kunden kontrolliert wurden, sind Demokratien und Republiken mit begrenztem Wahlrecht, wie die antiken Demokratien oder die amerikanische Republik in ihrer Gründungszeit. Damals durften nur diejenigen wählen, die für die Regierung zahlten, etwa 10 Prozent der Bevölkerung.

Regierungen, die von ihren Kunden kontrolliert werden, haben ebenso wie die Eigentümer Anreize, ihre Betriebskosten so weit wie möglich zu senken.

Aber im Gegensatz zu Regierungen, die von Eigentümern oder Angestellten kontrolliert werden, haben Regierungen, die tatsächlich von ihren Kunden kontrolliert werden, Anreize, die Preise, die sie verlangen, niedrig zu halten. Wo Kunden regieren, sind Regierungen schlank und im Allgemeinen unauffällig, mit geringen Betriebskosten, minimaler Beschäftigung und niedrigen Steuern. Ein Staat, der von seinen Kunden kontrolliert wird, legt die Steuersätze nicht fest, um den Betrag zu optimieren, den der Staat einnehmen kann, sondern um den Betrag zu optimieren, den die Kunden einbehalten können.

Wie typische Unternehmen auf Wettbewerbsmärkten wäre auch ein Monopol, das von seinen Kunden kontrolliert wird, gezwungen, sich um Effizienz zu bemühen. Es wäre nicht in der Lage, einen Preis in Form von Steuern zu verlangen, der die Kosten um mehr als eine knappe Marge übersteigt.

## DIE ROLLE DER DEMOKRATIE: WÄHLER ALS ARBEITNEHMER UND KUNDEN

Lane behandelt die Demokratie auf herkömmliche Weise, indem er davon ausgeht, dass sie gewaltausübende und gewaltproduzierende Unternehmen „zunehmend unter die Kontrolle ihrer Kunden bringt".[^173] Dies ist sicherlich die politisch korrekte Schlussfolgerung. Aber ist sie wahr? Wir glauben nicht. Schauen Sie sich genau an, wie moderne Demokratien funktionieren.

Zunächst mal weisen sie nur wenige Merkmale jener wettbewerbsfähigen Branchen auf, in denen die Handelsbedingungen eindeutig von den Kunden kontrolliert werden. Zum einen geben demokratische Regierungen in der Regel nur einen Bruchteil ihrer Gesamtausgaben für den Schutzdienst aus, der ihre Haupttätigkeit ist. In den Vereinigten Staaten beispielsweise geben die Regierungen der Bundesstaaten und Kommunen nur 3,5 Prozent ihrer Gesamtausgaben für die Bereitstellung von Polizei, Gerichten und Gefängnissen aus. Rechnet man die Militärausgaben hinzu, so beträgt der Anteil der Einnahmen, der für den Schutz aufgewendet wird, immer noch nur etwa 10 Prozent. Ein weiterer aufschlussreicher Hinweis darauf, dass die Massendemokratie nicht von ihren Kunden kontrolliert wird, ist die Tatsache, dass die heutige politische Kultur, ein Erbe des Industriezeitalters, es als empörend empfinden würde, wenn die Politik in entscheidenden Fragen tatsächlich von den Interessen der Menschen bestimmt würde, die die Rechnungen bezahlen. Stellen Sie sich den Aufschrei vor, wenn ein amerikanischer Präsident oder ein britischer Premierminister vorschlagen würde, die Gruppe der Bürger, die den Großteil der Steuern zahlt, darüber entscheiden zu lassen, welche Regierungsprogramme fortgeführt und welche Gruppen von Mitarbeitern entlassen werden sollen. Dies würde die Erwartungen an die Arbeitsweise der Regierung zutiefst verletzen, und zwar in einer Weise, wie es nicht der Fall wäre, wenn man den Regierungsangestellten erlauben würde, zu bestimmen, wessen Steuern erhöht werden sollen.

Wenn man jedoch darüber nachdenkt, dass der Kunde wirklich das Sagen hat, wäre es empörend, wenn er nicht bekäme, was er will. Wenn Sie in ein Geschäft gehen, um Möbel zu kaufen, und das Verkaufspersonal nimmt Ihr Geld entgegen, ignoriert dann aber Ihre Wünsche und berät sich mit anderen darüber, wie Sie Ihr Geld ausgeben sollen, wären Sie zu Recht verärgert. Sie würden es weder für normal noch für vertretbar halten, wenn die Angestellten des Geschäfts argumentieren würden, dass Sie die Möbel gar nicht verdient hätten und sie stattdessen an jemanden geliefert werden sollten, den sie für würdiger hielten. Die Tatsache, dass so etwas im Umgang mit der Regierung vorkommt, zeigt, wie wenig Kontrolle die „Kunden" tatsächlich haben.

Die Kosten einer demokratischen Regierung sind in jeder Hinsicht außer Kontrolle geraten, im Gegensatz zu der typischen Situation, in der die Kundenpräferenzen die Anbieter zu Effizienz zwingen. Die meisten Demokratien weisen chronische Defizite auf. Dies ist ein finanzpolitisches Merkmal der Kontrolle durch die Beschäftigten. Regierungen scheinen besonders resistent zu sein, wenn es darum geht, die Kosten ihrer Tätigkeit zu senken. Eine fast allgemeingültige Klage über die heutigen Regierungen weltweit ist, dass politische Programme, wenn sie einmal eingeführt sind, nur sehr schwer wieder zurückgenommen werden können. Einen Regierungsangestellten zu entlassen ist so gut wie unmöglich. Tatsächlich besteht einer der Hauptvorteile der Privatisierung ehemals staatlicher Funktionen darin, dass es unter privater Kontrolle in der Regel viel einfacher ist, unnötige Arbeitsplätze zu streichen. Von Großbritannien bis Argentinien war es nicht ungewöhnlich, dass die neuen privaten Manager 50-95 Prozent der ehemaligen Staatsbediensteten entlassen haben.

Denken Sie auch an die Grundlage, auf der die fiskalischen Bedingungen für die staatliche Schutzleistung bepreist werden. Hinweise auf wettbewerbliche Einflüsse auf die Steuersätze, nach denen staatliche Leistungen bepreist werden, sucht man zumeist vergebens. Selbst die gelegentlichen Debatten über Steuersenkungen, die in den letzten Jahren den normalen politischen Diskurs unterbrochen haben, verraten, wie weit der demokratische Staat normalerweise von einer Kontrolle durch seine Kunden entfernt ist. Befürworter von Steuersenkungen haben manchmal argumentiert, dass die Staatseinnahmen tatsächlich steigen würden, weil die Steuersätze zuvor so hoch angesetzt waren, dass sie die Wirtschaftstätigkeit behinderten.

Der Kompromiss, den sie normalerweise hervorheben wollten, war nicht der Wettbewerb zwischen den Rechtsordnungen, sondern etwas viel Erstaunlicheres. Sie argumentierten nicht, dass, weil die Steuersätze in Hongkong nur 15 Prozent betragen, die Sätze in den Vereinigten Staaten oder Deutschland nicht höher als 15 Prozent sein dürfen. Das Gegenteil ist der Fall. In den Steuerdebatten wurde normalerweise davon ausgegangen, dass der Steuerzahler nicht vor der Wahl steht, ob er seine Geschäfte in einem Land oder in einem anderen Land tätigt, sondern ob er seine Geschäfte zu Strafsteuersätzen tätigt oder Urlaub macht. Man hat Ihnen gesagt, dass produktive Personen, die einer räuberischen Besteuerung unterworfen sind, sich von ihren Briefkästen entfernen und Golf spielen gehen würden, wenn ihre Steuerlast nicht gemildert würde.

Die Tatsache, dass ein solches Argument überhaupt vorgebracht werden kann, zeigt, wie weit entfernt die von den demokratischen Wohlfahrtsstaaten auferlegten Schutzkosten von einer wettbewerbsorientierten Grundlage sind. Die Bedingungen der progressiven Einkommensbesteuerung, die im Laufe des zwanzigsten Jahrhunderts in jedem demokratischen Wohlfahrtsstaat aufkam, unterscheiden sich dramatisch von den Preisbestimmungen, die von den Kunden bevorzugt werden würden. Dies lässt sich leicht erkennen, wenn man die Besteuerung zur Unterstützung eines monopolistischen Schutzes mit den Tarifen für den Telefondienst vergleicht, der bis vor kurzem an den meisten Orten ein Monopol war. Die Kunden würden aufschreien, wenn eine Telefongesellschaft versuchen würde, Anrufe auf der gleichen Grundlage wie die Einkommenssteuer zu berechnen. Stellen Sie sich vor, die Telefongesellschaft schickt Ihnen eine Rechnung über 50.000 Dollar für einen Anruf nach London, nur weil Sie während eines Gesprächs ein Geschäft im Wert von 125.000 Dollar abgeschlossen haben. Weder Sie noch irgendein anderer Kunde, der bei Verstand ist, würde diese Rechnung bezahlen. Aber genau auf dieser Grundlage werden in jedem demokratischen Wohlfahrtsstaat die Einkommenssteuern erhoben.

Wenn man genau darüber nachdenkt, unter welchen Bedingungen die industriellen Demokratien funktioniert haben, ist es logischer, sie als eine Form der Regierung zu betrachten, die von ihren Mitarbeitern kontrolliert wird. Wenn man sich die Massendemokratie als eine von den Arbeitnehmern kontrollierte Regierung vorstellt, erklärt sich auch die Schwierigkeit, die Regierungspolitik zu ändern. Die Regierung scheint in vielerlei Hinsicht zum Nutzen der Beschäftigten geführt zu werden. Zum Beispiel scheinen die staatlichen Schulen in den meisten demokratischen Ländern chronisch dysfunktional zu sein, ohne Chance auf die Behebung ihrer Missstände. Wenn die Kunden wirklich das Sagen hätten, wäre es für sie einfacher, neue politische Richtungen vorzugeben. Diejenigen, die für eine demokratische Regierung zahlen, bestimmen nur selten die Bedingungen für die Staatsausgaben. Stattdessen funktioniert der Staat wie eine Genossenschaft, die sich der Kontrolle durch die Eigentümer entzieht und wie ein natürliches Monopol funktioniert. Die Preise stehen in keinem Verhältnis zu den Kosten. Die Qualität der Dienstleistungen ist im Allgemeinen niedriger als in der Privatwirtschaft. Kundenbeschwerden sind schwer zu beheben. Kurz gesagt, die Massendemokratie führt zu einer Kontrolle der Regierung durch ihre „Angestellten".

Aber halt. Sie werden vielleicht sagen, dass es in den meisten Ländern viel mehr Wähler gibt, als Personen, die auf der Gehaltsliste der Regierung stehen. Wie ist es möglich, dass die Beschäftigten unter solchen Bedingungen dominieren können? Der Wohlfahrtsstaat ist als Antwort auf genau dieses Dilemma entstanden. Da es nicht genügend Arbeitnehmer gab, um eine arbeitende Mehrheit zu bilden, wurde eine wachsende Zahl von Wählern auf die Lohnliste gesetzt, um Transferleistungen aller Art zu erhalten. So wurden die Empfänger von Transferleistungen und Subventionen zu Pseudo-Staatsbediensteten, die sich nicht mehr jeden Tag zur Arbeit melden mussten. Das war ein Ergebnis, das von der megapolitischen Logik des Industriezeitalters diktiert wurde.

Wenn das Ausmaß der Zwangsgewalt wichtiger ist als der effiziente Einsatz von Ressourcen, wie es vor 1989 der Fall war, ist es für die meisten Regierungen so gut wie unmöglich, von ihren Kunden kontrolliert zu werden. Wie das Beispiel der späten Sowjetunion zeigt, war es bis vor wenigen Jahren für Staaten möglich, große Macht in der Welt auszuüben und gleichzeitig Ressourcen in großem Umfang zu verschwenden. Wenn die Renditen für Gewalt hoch sind und steigen, bedeutet Größe mehr als Effizienz. Größere Einheiten neigen dazu, sich gegenüber kleineren durchzusetzen. Diejenigen Regierungen, die militärische Ressourcen effektiver mobilisieren, auch wenn sie dafür viele von ihnen verschwenden, setzen sich tendenziell gegenüber denjenigen durch, die die Ressourcen effizienter nutzen.

Überlegen Sie, was das bedeutet. Es bedeutet unweigerlich, dass Regierungen, die von ihren Kunden kontrolliert werden, sich nicht durchsetzen und oft nicht überleben können, wenn Größe mehr bedeutet als Effizienz. Unter solchen Bedingungen werden diejenigen Einheiten militärisch am effektivsten sein, die die meisten Ressourcen für den Krieg requirieren. Aber Regierungen, die wirklich von ihren Kunden, die ihre Rechnungen bezahlen, kontrolliert werden, haben wahrscheinlich keinen Freibrief, jedem in die Tasche zu greifen, um Ressourcen zu beschaffen.

Die Kunden möchten normalerweise, dass die Preise, die sie für ein Produkt oder eine Dienstleistung, einschließlich Schutz, zahlen, gesenkt und unter Kontrolle gehalten werden. Hätten die westlichen Demokratien während des Kalten Krieges unter der Kontrolle der Kunden gestanden, hätte allein diese Tatsache sie militärisch zu schwächeren Konkurrenten gemacht, da dies mit ziemlicher Sicherheit den Fluss von Ressourcen in die Regierung eingeschränkt hätte. Denken Sie daran, dass dort, wo die Kunden regieren, sowohl die Preise als auch die Kosten unter strenger Kontrolle stehen sollten. Doch genau das ist nicht geschehen. Die Wohlfahrtsstaaten waren während des Kalten Krieges die offensichtlichen Gewinner des Ausgabenwettbewerbs. Kommentatoren aller Couleur nannten als Grund für ihren Triumph die Fähigkeit, die Sowjetunion in den Bankrott zu treiben.

Genau diese Tatsache verdeutlicht, wie die Ineffizienzen der Demokratie sie in einer Zeit steigender Gewaltrenditen zur vorherrschenden Megapolitik machten. Massive Militärausgaben mit all ihrer Verschwendung stellen einen eindeutig suboptimalen Einsatz von Kapital zum privaten Nutzen dar. Wir haben bereits angedeutet, dass Wohlfahrtsstaaten im Vergleich zu staatssozialistischen Systemen zwar wirtschaftlich effizient sind, dass sie aber bei der Schaffung von Wohlstand weit weniger effizient sind als Laissez-faire-Enklaven wie Hongkong. Ironischerweise war es gerade diese Ineffizienz des demokratischen Wohlfahrtsstaates im Vergleich zu einem unbelasteten System der freien Marktwirtschaft, die ihn unter den megapolitischen Bedingungen des Industrialismus erfolgreich machte.

Wie konnte die von der Demokratie geförderte Ineffizienz zu einem Faktor ihres Erfolgs im Zeitalter der Gewalt werden? Der Schlüssel zum Entwirren dieses scheinbaren Paradoxons liegt in der Erkenntnis zweier Punkte:

1.  Der Erfolg einer Souveränität in der Neuzeit lag nicht in der Schaffung von Reichtum, sondern in der Schaffung einer militärischen Macht, die in der Lage war, übermächtige Gewalt gegen jeden anderen Staat einzusetzen. Dazu brauchte man Geld, aber mit Geld allein konnte man keine Schlacht gewinnen. Die Herausforderung bestand nicht darin, ein System mit der effizientesten Wirtschaft oder der schnellsten Wachstumsrate zu schaffen, sondern ein System, das mehr Ressourcen abziehen und diese in das Militär lenken konnte. Militärausgaben sind naturgemäß ein Bereich, in dem der finanzielle Ertrag an sich gering oder gar nicht vorhanden ist.

2.  Der einfachste Weg, um die Erlaubnis zu erhalten, Gelder in Aktivitäten zu investieren, die wenig oder keinen direkten finanziellen Ertrag bringen, wie z. B. Steuerzahlungen, ist, jemanden um Erlaubnis zu bitten, der nicht die Person ist, deren Geld man begehrt. Einer der Gründe, warum die Niederländer Manhattan für Perlen im Wert von dreiundzwanzig Dollar kaufen konnten, war, dass die Indianer, denen sie das Angebot unterbreiteten, nicht diejenigen waren, denen es eigentlich gehörte. Unter diesen Bedingungen ist es viel einfacher, ein „Ja" zu bekommen, wie die Marketingleute sagen. Nehmen wir zum Beispiel an, wir als Autoren dieses Buches wollten, dass Sie nicht den Einbandpreis, sondern 40 Prozent Ihres Jahreseinkommens für ein Exemplar zahlen. Es wäre viel wahrscheinlicher, dass wir die Erlaubnis dazu bekämen, wenn wir jemand anderen als Sie fragen würden. Tatsächlich wären wir weitaus überzeugender, wenn wir uns stattdessen auf die Zustimmung mehrerer Personen verlassen könnten, die Sie nicht einmal kennen. Wir könnten eine Ad-hoc-Wahl durchführen, was H. L. Mencken mit weniger Übertreibung als er dachte als „eine fortgeschrittene Versteigerung gestohlener Waren" bezeichnete. Und um das Beispiel realistischer zu machen, würden wir uns bereit erklären, einen Teil des Geldes, das wir von Ihnen gesammelt haben, mit diesen anonymen Umstehenden im Austausch für ihre Unterstützung zu teilen.

Das ist die Rolle, die der moderne demokratische Wohlfahrtsstaat zu erfüllen hat. Er war im Industriezeitalter ein unübertroffenes System, weil er dort, wo es darauf ankam, sowohl effizient als auch ineffizient war. Er kombinierte die Effizienz des Privateigentums und Anreize für die Schaffung von Wohlstand mit einem Mechanismus, der einen im Wesentlichen unkontrollierten Zugang zu diesem Wohlstand ermöglichte. Die Demokratie hielt die Taschen der Wohlstandsproduzenten offen. Militärisch war sie während der Hochphase steigender Gewaltrenditen in der Welt gerade deshalb erfolgreich, weil sie es den Kunden erschwerte, die von der Regierung erhobenen Steuern oder andere Möglichkeiten der Finanzierung der Ausgaben für das Militär, wie etwa die Inflation, wirksam zu beschränken.

### Warum die Kunden nicht dominieren konnten

Diejenigen, die in der Neuzeit für den „Schutz" zahlten, waren nicht in der Lage, dem Souverän erfolgreich Ressourcen zu verweigern, selbst wenn sie kollektiv handelten, da sie dies nur der Gefahr ausgesetzt hätte, von anderen, möglicherweise feindlicheren Staaten überwältigt zu werden. Dies war eine offensichtliche Überlegung während des Kalten Krieges. Die Kunden bzw. Steuerzahler, die in den führenden westlichen Industriestaaten einen unverhältnismäßig hohen Anteil an den Kosten des Staates trugen, konnten sich nicht weigern, hohe Steuern zu zahlen. Das Ergebnis wäre gewesen, dass sie sich der totalen Beschlagnahmung durch die Sowjetunion oder eine andere aggressive Gruppe, die in der Lage war, Gewalt zu organisieren, ausgesetzt hätten.

### Industrialisierung und Demokratie

Längerfristig betrachtet könnte sich die Massendemokratie als Anachronismus erweisen, der das Ende des Industriezeitalters nicht lange überleben wird. Sicher ist, dass die Massendemokratie und der Nationalstaat zusammen mit der Französischen Revolution am Ende des 18. Jahrhunderts entstanden sind, wahrscheinlich als Reaktion auf einen Anstieg des Realeinkommens. Um 1750 begannen die Einkommen in Westeuropa erheblich zu steigen, was zum Teil auf das wärmere Wetter zurückzuführen war. Dies fiel mit einer Periode technologischer Innovationen zusammen, in der qualifizierte Arbeitsplätze von Handwerkern durch Maschinen ersetzt wurden, die von ungelernten Arbeitern, sogar Frauen und Kindern, bedient werden konnten. Diese neuen Industrieanlagen führten zu höheren Einkommen für ungelernte Arbeitskräfte, wodurch die Einkommensverteilung gleichmäßiger wurde.

Der entscheidende Auslöser der Revolution war vielleicht nicht, wie oft angenommen wird, die perverse Idee, dass die Menschen dazu neigen, sich aufzulehnen, wenn sich die Bedingungen verbessern. Wichtiger könnte die Tatsache gewesen sein, dass es für den frühmodernen Staat endlich praktisch wurde, die privaten Vermittler und mächtigen Magnaten, mit denen er zuvor um Ressourcen gefeilscht hatte, zu umgehen und zu einem System der „direkten Herrschaft" überzugehen, in dem eine nationale Regierung direkt mit den einzelnen Bürgern verhandelte, sie mit immer höheren Steuersätzen belastete und einen schlecht bezahlten Militärdienst als Gegenleistung für die Bereitstellung verschiedener Leistungen forderte.[^174]

Da die aufstrebende Mittelschicht bald über genügend Geld verfügte, das besteuert werden konnte, war es für die Herrscher nicht mehr so wichtig wie zuvor, mit mächtigen Grundbesitzern oder Großkaufleuten zu verhandeln, die, wie der Historiker Charles Tilly schrieb, „in der Lage waren, die Schaffung eines mächtigen Staates zu verhindern", der „ihr Vermögen beschlagnahmen und ihre Transaktionen einschränken würde."[^175] Es ist leicht einzusehen, warum Regierungen bei der Gewinnung von Ressourcen erfolgreicher waren, wenn sie mit Millionen von Bürgern einzeln verhandelten als mit einer relativen Handvoll von Herren, Herzögen, Grafen, Bischöfen, Vertragssöldnern, freien Städten und anderen halbstaatlichen Einheiten, mit denen die Herrscher europäischer Staaten vor der Mitte des 18. Jahrhunderts verhandeln mussten.

Steigende Realeinkommen ermöglichten es den Regierungen, eine Strategie zu verfolgen, mit der sie mehr Ressourcen unter ihre Kontrolle brachten. Kleine Beträge, die von Millionen von Steuerzahlern eingenommen wurden, konnten mehr Einnahmen bringen als größere Beträge, die von einigen wenigen Mächtigen gezahlt wurden. Außerdem war es viel einfacher, mit den Vielen umzugehen als mit den Wenigen, die im Allgemeinen nicht bereit waren, ihr Geld zu verschenken, und die sich viel besser wehren konnten.

Schließlich verfügte der typische Bauer, Kleinhändler oder Arbeiter im Vergleich zum Staat selbst über verschwindend geringe Ressourcen. Es war nicht einmal im Entferntesten möglich, dass der typische Privatmann in Westeuropa am Vorabend der Französischen Revolution wirksam mit dem Staat verhandeln konnte, um seinen Steuersatz zu senken, oder einen wirksamen Widerstand gegen Regierungspläne und -maßnahmen leisten konnte, die seine Interessen bedrohten. Doch genau das hatten mächtige Privatmagnaten jahrhundertelang getan und würden es auch weiterhin tun. Sie leisteten wirksamen Widerstand und verhandelten mit den Machthabern, um deren Möglichkeiten zur Aneignung von Ressourcen zu beschränken.

> „Der Kriegseintritt beschleunigte den Übergang von der indirekten zur direkten Herrschaft. Fast jeder Staat, der in den Krieg zieht, stellt fest, dass er den Aufwand nicht aus seinen angesammelten Reserven und laufenden Einnahmen bezahlen kann. Fast alle kriegführenden Staaten nehmen in großem Umfang Kredite auf, erhöhen die Steuern und beschlagnahmen die Kampfmittel - einschließlich der Männer - von widerstrebenden Bürgern, die eine andere Nutzung ihrer Ressourcen vorgesehen hatten."[^176] Charles Tilly

Das Beispiel Polens in der Mitte des achtzehnten Jahrhunderts veranschaulicht dies perfekt. Im Jahr 1760 umfasste die polnische Nationalarmee 18.000 Soldaten. Im Vergleich zu den Armeen der benachbarten Länder Österreich, Preußen und Russland, von denen das kleinste über ein stehendes Heer von 100.000 Soldaten verfügte, war dies eine magere Truppe. Tatsächlich war die polnische Nationalarmee im Jahr 1760 selbst im Vergleich zu anderen bewaffneten Einheiten innerhalb Polens klein. Die kombinierten Streitkräfte des polnischen Adels umfassten dreißigtausend Mann.[^177]

Wäre der polnische König in der Lage gewesen, direkt mit Millionen einzelner Polen in Kontakt zu treten und sie direkt zu besteuern, anstatt sich darauf zu beschränken, die Mittel indirekt über die Beiträge der mächtigen polnischen Magnaten zu erhalten, wäre die polnische Zentralregierung zweifellos in der Lage gewesen, weitaus mehr Einnahmen zu erzielen und somit eine größere Armee zu finanzieren.

Gegenüber einfachen Bürgern, die nicht in der Lage waren, gemeinsam mit Millionen anderer einfacher Bürger zu handeln, sollten sich die Zentralbehörden überall als unwiderstehlich mächtig erweisen. Aber der polnische König hatte 1760 nicht die Möglichkeit, seine Bürger direkt zu besteuern. Er musste über die Fürsten, wohlhabenden Kaufleute und anderen Honoratioren verhandeln, die eine kleine, zusammenhängende Gruppe bildeten. Sie konnten gemeinsam handeln und taten dies auch, um den König daran zu hindern, sich ihre Ressourcen ohne ihre Zustimmung anzueignen. Da der polnische Adel über weit mehr Truppen verfügte als er selbst, konnte der König nicht darauf bestehen.

Wie sich herausstellte, war der militärische Nachteil, die Reichen und Mächtigen bei der Beschaffung von Ressourcen nicht umgehen zu können, im Zeitalter der Gewalt entscheidend. Innerhalb weniger Jahre hörte Polen auf, als unabhängiges Land zu existieren. Es wurde von Österreich, Preußen und Russland erobert, drei Ländern mit Armeen, die jeweils um ein Vielfaches größer waren als die kleine polnische Streitmacht. In jedem dieser Länder hatten die Herrscher Wege gefunden, die Fähigkeit der wohlhabenden Kaufleute und des Adels zur Begrenzung der Beschlagnahmung ihrer Ressourcen zu umgehen.

### Nach der französischen Revolution

Die Französische Revolution führte zu einer noch stärkeren Vergrößerung der Armeen, eine Tatsache, die die Stärke der demokratischen Strategie unter Beweis stellte, als die Rendite der Gewalt stieg. Der Handel, den die Regierungen seit der Französischen Revolution eingingen, bestand darin, ein noch nie dagewesenes Maß an Einmischung in das Leben des Durchschnittsbürgers zu gewähren, und zwar im Gegenzug dafür, dass dieser anstelle von Söldnern an Kriegen teilnahm und eine wachsende Steuerlast aus seinem steigenden Einkommen zahlte.

Wie Tilly sagte:

> Die Sphäre des Staates dehnte sich weit über seinen militärischen Kern hinaus aus, und seine Bürger begannen, ihn für ein sehr breites Spektrum von Schutz, Rechtsprechung, Produktion und Verteilung in Anspruch zu nehmen. In dem Maße, wie die nationalen Gesetzgebungen ihre eigenen Bereiche weit über die Genehmigung von Steuern hinaus ausdehnten, wurden sie zur Zielscheibe von Forderungen aller gut organisierten Gruppen, deren Interessen der Staat berührte oder berühren konnte. Direkte Herrschaft und nationale Massenpolitik wuchsen zusammen und verstärkten sich gegenseitig.[^178]

Die gleiche Logik, die im achtzehnten Jahrhundert galt, blieb bis zum Fall der Berliner Mauer 1989 gültig. Mit dem Fortschreiten des Industriezeitalters stiegen die Einkommen für ungelernte Arbeit weiter an, was die Massendemokratie zu einer noch effektiveren Methode zur Optimierung der Ressourcengewinnung machte. Infolgedessen wuchs und wuchs der Staat und erhöhte im Laufe des zwanzigsten Jahrhunderts in einem durchschnittlichen Industrieland seinen Gesamtanspruch auf das Jahreseinkommen um etwa 0,5 Prozent.

Im Industriezeitalter vor 1989 erwies sich die Demokratie gerade deshalb als die militärisch effektivste Regierungsform, weil die Demokratie es schwierig oder unmöglich machte, der Beschlagnahmung von Ressourcen durch den Staat wirksame Grenzen zu setzen. Die großzügige Gewährung von Wohlfahrtsleistungen für alle und jeden lud eine Mehrheit der Wähler dazu ein, faktisch Angestellte der Regierung zu werden. Dies wurde zum vorherrschenden politischen Merkmal aller führenden Industrieländer, da sich die Wähler in ihrer Rolle als Kunden für den Schutzdienst in einer schwachen Position befanden, um die Regierung wirksam zu kontrollieren. Sie sahen sich nicht nur mit der aggressiven Bedrohung durch kommunistische Systeme konfrontiert, die große Ressourcen für militärische Zwecke produzieren konnten, da der Staat die gesamte Wirtschaft kontrollierte. Eine echte Kontrolle des Staates durch die Steuerzahler war auch aus einem anderen Grund nicht möglich.

Millionen von Durchschnittsbürgern können nicht wirksam zusammenarbeiten, um ihre Interessen zu schützen. Da die Hindernisse für ihre Zusammenarbeit hoch sind und der Gewinn für jeden Einzelnen bei erfolgreicher Verteidigung der gemeinsamen Interessen der Gruppe minimal ist, werden Millionen von Durchschnittsbürgern nicht so erfolgreich sein, ihr Vermögen der Regierung vorzuenthalten, wie kleinere Gruppen mit günstigeren Anreizen.

Unter sonst gleichen Bedingungen würde man daher erwarten, dass in einer Massendemokratie ein höherer Anteil der Gesamtressourcen von der Regierung requiriert wird als in einer Oligarchie oder in einem System fragmentierter Souveränität, in dem Magnaten militärische Macht ausübten und ihre eigenen Armeen aufstellten, wie es überall im frühmodernen Europa vor dem 18. Jahrhundert der Fall war.

Ein entscheidender, wenn auch selten untersuchter Grund für das Wachstum der Demokratie in der westlichen Welt ist also die relative Bedeutung der Verhandlungskosten in einer Zeit, in der die Rendite der Gewalt stieg. Es war immer kostspieliger, Ressourcen von den Wenigen zu beziehen als von den Vielen.

Eine relativ kleine, elitäre Gruppe von Reichen stellt eine kohärentere und effektivere Einheit dar als eine große Masse von Bürgern. Die kleine Gruppe hat stärkere Anreize, zusammenzuarbeiten. Sie wird ihre Interessen fast zwangsläufig wirksamer schützen als eine Massengruppierung.[^179] Und selbst wenn die meisten Mitglieder der Gruppe sich entscheiden, bei einer gemeinsamen Aktion nicht zu kooperieren, können einige wenige Reiche in der Lage sein, genügend Ressourcen einzusetzen, um die Aufgabe zu bewältigen.

Mit der demokratischen Entscheidungsfindung konnte der Nationalstaat seine Macht über Millionen von Menschen, die nicht ohne weiteres zusammenarbeiten konnten, um kollektiv in ihrem eigenen Interesse zu handeln, viel umfassender ausüben als gegenüber einer viel kleineren Zahl, die die organisatorischen Schwierigkeiten bei der Verteidigung ihrer konzentrierten Interessen leichter überwinden konnte. Die Demokratie hatte den noch viel verlockenderen Vorteil, dass sie eine legitimierende Entscheidungsregel schuf, die es dem Staat ermöglichte, die Ressourcen der Wohlhabenden anzuzapfen, ohne direkt um ihre Zustimmung verhandeln zu müssen. Kurzum, die Demokratie war als Entscheidungsmechanismus gut an die megapolitischen Bedingungen des Industriezeitalters angepasst. Sie ergänzte den Nationalstaat, weil sie die Konzentration militärischer Macht in den Händen derjenigen erleichterte, die ihn führten, und zwar zu einer Zeit, als das Ausmaß der eingesetzten Kräfte wichtiger war als die Effizienz, mit der sie mobilisiert wurden.

Ein entscheidender Beweis dafür war die Französische Revolution, die das Ausmaß der militärischen Gewalt auf dem Schlachtfeld erhöhte. Danach hatten andere konkurrierende Nationalstaaten kaum eine andere Wahl, als sich einer ähnlichen Organisation anzunähern, wobei die Legitimität letztlich an die demokratische Entscheidungsfindung gebunden war. Zusammenfassend lässt sich sagen, dass der demokratische Nationalstaat in den letzten zwei Jahrhunderten aus den folgenden, versteckten Gründen erfolgreich war:

1.  Es gab steigende Renditen für Gewalt, so dass das Ausmaß der Gewalt wichtiger wurde als die Effizienz als Leitprinzip.

2.  Die Einkommen stiegen so weit über das Existenzminimum, dass es dem Staat möglich wurde, große Mengen an Gesamtressourcen einzutreiben, ohne mit mächtigen Magnaten verhandeln zu müssen, die in der Lage waren, Widerstand zu leisten.

3.  Die Demokratie erwies sich als hinreichend kompatibel mit dem Funktionieren freier Märkte, um die Schaffung von immer mehr Wohlstand zu ermöglichen.

4.  Die Demokratie erleichterte die Beherrschung der Regierung durch ihre „Angestellten" und stellte damit sicher, dass es schwierig sein würde, die Ausgaben, einschließlich der Militärausgaben, zu kürzen.

5.  Die Demokratie als Entscheidungsregel erwies sich als wirksames Gegenmittel gegen die Fähigkeit der Wohlhabenden, gemeinsam zu handeln, um die Fähigkeit des Nationalstaates zu beschränken, Steuern zu erheben oder ihr Vermögen auf andere Weise vor Übergriffen zu schützen.

Die Demokratie wurde zur militärisch siegreichen Strategie, weil sie es dem Staat erleichterte, mehr Ressourcen in seine Hände zu bekommen. Im Vergleich zu anderen Formen der Souveränität, deren Legitimität von anderen Prinzipien abhing, wie z. B. der Feudalabgabe, dem göttlichen Recht der Könige, der korporativen religiösen Pflicht oder den freiwilligen Beiträgen der Reichen, wurde die Massendemokratie militärisch am stärksten, weil sie der sicherste Weg war, um in einer industriellen Wirtschaft Ressourcen zu sammeln.

> „Die Nation als kulturell definierte Gemeinschaft ist der höchste symbolische Wert der Moderne; sie wurde mit einem quasi sakralen Charakter ausgestattet, der nur von der Religion übertroffen wird. Tatsächlich leitet sich dieser quasi-sakrale Charakter von der Religion ab. In der Praxis ist die Nation entweder zum modernen, säkularen Ersatz für die Religion oder zu ihrem mächtigsten Verbündeten geworden. In der modernen Zeit werden die von der Nation erzeugten Gemeinschaftsgefühle hoch angesehen und als Grundlage für die Loyalität zur Gruppe gesucht\... Dass der moderne Staat oft der Nutznießer ist, sollte angesichts seiner überragenden Macht kaum überraschen."[^180] - Joseph R. Llobera

### Nationalismus

Ähnliches lässt sich über den Nationalismus sagen, der eine Begleiterscheinung der Massendemokratie wurde. Staaten, die sich des Nationalismus bedienen konnten, stellten fest, dass sie größere Armeen zu geringeren Kosten mobilisieren konnten. Der Nationalismus war eine Erfindung, die es einem Staat ermöglichte, seine militärische Schlagkraft zu erhöhen. Wie die Politik selbst ist auch der Nationalismus zumeist eine moderne Erfindung. Wie der Soziologe Joseph Llobera in seinem reichhaltig dokumentierten Buch über den Aufstieg des Nationalismus gezeigt hat, ist die Nation eine imaginäre Gemeinschaft, die zu einem großen Teil als Mittel zur Mobilisierung staatlicher Macht während der Französischen Revolution entstanden ist. Er drückt es so aus: „Im modernen Sinne des Wortes gibt es das Nationalbewusstsein erst seit der Französischen Revolution, seit der Zeit, als die verfassungsgebende Versammlung 1789 das französische Volk mit der französischen Nation gleichsetzte."[^181]

Der Nationalismus erleichterte die Mobilisierung von Macht und die Kontrolle über eine große Zahl von Menschen. Nationalstaaten bildeten sich, indem sie gemeinsame Merkmale, insbesondere die gesprochene Sprache, hervorhoben und betonten. Dies erleichterte die Herrschaft ohne die Einschaltung von Mittelsmännern. Es vereinfachte die Aufgaben der Bürokratie. Erlasse, die nur in einer Sprache verkündet werden müssen, können schneller und mit weniger Verwirrung versandt werden als solche, die in ein Durcheinander von Sprachen übersetzt werden müssen. Der Nationalismus senkte daher tendenziell die Kosten für die Kontrolle größerer Gebiete. Vor dem Nationalismus benötigte der frühneuzeitliche Staat die Hilfe von Herren, Herzögen, Grafen, Bischöfen, freien Städten und anderen korporativen und ethnischen Vermittlern, von Steuer-„Bauern" bis hin zu militärischen Vertragshändlern und Söldnern, um Einnahmen einzutreiben, Truppen aufzustellen und andere Regierungsaufgaben zu erfüllen.

Der Nationalismus senkte auch entscheidend die Kosten für die Mobilisierung von Militärpersonal, indem er die Identifikation der Gruppe mit den Interessen des Staates förderte. Die Nutzung von Gruppengefühlen für die Interessen des Staates war so vorteilhaft, dass sich die meisten Staaten, selbst die angeblich internationalistische Sowjetunion, dem Nationalismus als einer ergänzenden Ideologie anschlossen.

Längerfristig gesehen ist der Nationalismus ebenso eine Anomalie wie der Staat selbst. Wie der Historiker William McNeill dokumentiert hat, waren polyethnische Souveränitäten in der Vergangenheit die Norm.[^182]

In McNeills Worten: „Die Idee, dass eine Regierung rechtmäßig nur über Bürger eines einzigen Ethnos herrschen sollte, begann sich in Westeuropa gegen Ende des Mittelalters zu entwickeln."[^183] Eine frühe nationalistische Einheit war der Preußische Bund, der sich 1440 in Opposition zur Herrschaft des Deutschen Ordens bildete. Einige der Merkmale des Ordens wurden bereits als polares Beispiel für eine Souveränität im Gegensatz zum Nationalstaat hervorgehoben. Der Deutsche Orden war eine Art Chartergesellschaft, deren Mitglieder fast alle nicht aus Preußen stammten. Sein Hauptsitz wechselte zu verschiedenen Zeiten von Bremen und Lübeck nach Jerusalem, Akkon, Venedig und schließlich Marienberg an der Weichsel. Eine Zeit lang regierte sie den Bezirk Burzenland in Siebenbürgen. Es ist nicht verwunderlich, dass eine Souveränität, die einem Staat so unähnlich ist, zum Gegenstand eines der ersten Versuche wurde, das Nationalgefühl als Faktor zur Organisation von Macht zu mobilisieren. Ein Hinweis darauf, wie sehr sich der frühe Nationalismus von späteren Spielarten unterschied, ist, dass die deutschsprachigen Adligen des Preußischen Bundes den König von Polen baten, Preußen unter polnische Herrschaft zu stellen, vor allem weil der polnische König schon damals ein relativ schwacher Monarch war, von dem man nicht erwartete, dass er mit der gleichen Strenge regierte wie der Deutsche Orden.

Der Nationalismus kam in seinen frühen Formen kurz vor der Schießpulverrevolution ins Spiel. Er entwickelte sich weiter, als sich der frühneuzeitliche Staat entwickelte, und machte zur Zeit der Französischen Revolution einen Quantensprung in seiner Bedeutung. Wir sind der Meinung, dass der Nationalismus als Idee der Gewalt bereits auf dem Rückzug ist. Seinen Höhepunkt erreichte er wahrscheinlich mit Woodrow Wilsons Versuch, jede ethnische Gruppe in Europa am Ende des Ersten Weltkriegs mit einem eigenen Staat auszustatten. Heute ist er eine reaktionäre Kraft, die sich an Orten mit sinkenden Einkommen und sinkenden Aussichten wie Serbien entzündet.

Wie wir später noch ausführen werden, erwarten wir, dass Nationalismus ein Hauptthema von Personen mit geringer Qualifikation sein wird, die sich nach Zwang sehnen, wenn der Wohlfahrtsstaat in den westlichen Demokratien zusammenbricht. Noch haben Sie nichts gesehen. Für die meisten Menschen im Westen waren die Folgen des Untergangs des Kommunismus relativ harmlos. Sie haben einen Rückgang der Militärausgaben, einen Einbruch der Aluminiumpreise und eine neue Quelle von Eishockeyspielern für die NHL gesehen. Das sind die guten Nachrichten. Das sind Nachrichten, die die meisten Menschen, die im zwanzigsten Jahrhundert aufgewachsen sind, begrüßen könnten, vor allem, wenn sie Eishockey-Fans sind. Die meisten Nachrichten, die sich als weniger populär erweisen werden, stehen noch aus.

Mit dem Ende des Industriezeitalters fallen die megapolitischen Bedingungen, die die Demokratie erfüllte, rasch weg. Daher ist es zweifelhaft, dass die Massendemokratie und der Wohlfahrtsstaat unter den neuen megapolitischen Bedingungen des Informationszeitalters lange überleben werden.

> „Der Kongress war kein Tempel der Demokratie, sondern ein Markt für den Tausch von Gesetzen." - Alberto Fujimori, Präsident von Peru

Zukünftige Historiker werden vielleicht berichten, dass wir bereits den ersten postmodernen Staatsstreich erlebt haben - die bemerkenswerte Abriegelung des Kongresses in Peru im Jahr 1993. Dies war nicht wirklich ein Ereignis, das in den führenden Industriedemokratien viel Aufmerksamkeit erregte. Aber es könnte sich im Laufe der Zeit als bedeutsamer erweisen, als herkömmliche Analysten vermuten würden. Die wenigen, die darüber nachgedacht haben, neigen dazu, es nur als eine weitere Machtergreifung der Art zu sehen, die in der Geschichte Lateinamerikas deprimierend vertraut geworden ist. Wir aber sehen darin vielleicht den ersten Schritt zur Delegitimierung einer Regierungsform, deren unmittelbare megapolitische Daseinsberechtigung mit dem Übergang zum Informationszeitalter zu verschwinden beginnt. Fujimoris Schließung des Kongresses ist ein Symptom für die endgültige Entwertung politischer Versprechen. Ein ähnliches Schicksal könnte andere Parlamente erwarten, wenn ihr Kredit aufgebraucht ist.

Der technologische Wandel, der den Industrialismus aushöhlt, hat in vielen Ländern zu Regierungen geführt, die nicht mehr funktionieren. Oder schlecht funktionieren. Insbesondere die Legislative scheint in zunehmendem Maße dysfunktional zu sein. Sie erlassen Gesetze, die vor fünfzig Jahren vielleicht nur dumm waren, heute aber gefährlich sind. Dies zeigte sich auf spektakuläre Weise in Peru, wo die innere Souveränität des Staates 1993 fast zusammengebrochen war.

> „Überfälle, Entführungen, Vergewaltigungen und Morde gehen einher mit einem zunehmend aggressiven Fahrverhalten und unsicheren Straßen. Die Polizei hat allmählich die Kontrolle über die Situation verloren, und einige ihrer Mitglieder sind in Skandale verwickelt und zu routinierten Kriminellen geworden\... Die Menschen haben sich allmählich daran gewöhnt, außerhalb des Gesetzes zu leben. Diebstahl, illegale Beschlagnahmungen und Fabrikübernahmen sind alltäglich geworden."[^184] Hernando de Soto

### Peru in Trümmern

In gewisser Weise war Peru 1993 kein moderner Nationalstaat mehr. Es hatte zwar noch eine Flagge und eine Armee, aber die meisten seiner Institutionen lagen in Trümmern. Sogar die Gefängnisse waren von den Insassen übernommen worden. Für diesen Zerfall gibt es eine Reihe von Ursachen, aber die meisten Erklärungsversuche der Experten gehen am Kern der Sache vorbei. Peru war ein frühes Opfer des technologischen Wandels, der geschlossene Volkswirtschaften dysfunktional macht und die zentrale Autorität überall untergräbt. Diese megapolitischen Spannungen werden noch dadurch verstärkt, dass Entscheidungsinstitutionen wie der peruanische Kongress durch perverse Anreize dazu verleitet werden, genau die Probleme zu bündeln, die sie am dringendsten lösen müssen.

Die repräsentative Demokratie in Peru war wie ein Paar gezinkte Würfel. Als Entscheidungsmechanismus zur Vergrößerung des Staates war sie unübertroffen. Doch als die neuen Umstände die Übertragung von Macht verlangten, machten die inhärenten Verzerrungen, die die Demokratie unter den alten megapolitischen Bedingungen so nützlich gemacht hatten, sie zunehmend dysfunktional. Die Gesetze, die der Kongress verabschiedete, zerstörten rasch jede Grundlage von Wert und Respekt vor dem Gesetz. Wie de Soto es in The Other Path ausdrückt: „Kleine Interessengruppen bekämpfen sich untereinander, verursachen Konkurse und ziehen Beamte hinein. Die Regierungen verteilen Privilegien. Das Gesetz wird benutzt, um weit mehr zu geben und zu nehmen, als die Moral erlaubt."[^185] Ein Kongress wie der peruanische, der ganz und gar den Interessengruppen hörig ist, hat die moralische Statur einer Hehlerbande, die gestohlene Waren versteigert. Er hat den freien Markt illegal und damit das Gesetz lächerlich gemacht. Wie de Soto über die Zeit vor Fujimori schreibt:

> Eine völlige Umkehrung von Zweck und Mitteln hat das Leben der peruanischen Gesellschaft auf den Kopf gestellt, so dass es Handlungen gibt, die zwar offiziell kriminell sind, aber vom kollektiven Bewusstsein nicht mehr verurteilt werden. Der Schmuggel ist ein Beispiel dafür. Jeder, von der aristokratischen Dame bis zum einfachen Mann, erwirbt Schmuggelware. Niemand hat dabei Skrupel, im Gegenteil, es wird als eine Art Herausforderung an den individuellen Einfallsreichtum oder als Rache gegen den Staat angesehen. Das Eindringen von Gewalt und Kriminalität in den Alltag geht einher mit zunehmender Armut und Entbehrung. Generell ist das reale Durchschnittseinkommen der Peruaner in den letzten zehn Jahren stetig gesunken und liegt heute auf dem Niveau von vor zwanzig Jahren. Auf allen Seiten türmen sich Berge von Müll auf. Tag und Nacht belagern Legionen von Bettlern, Autowäschern und Plünderern die Passanten und bitten um Geld. Geisteskranke tummeln sich nackt auf den Straßen und stinken nach Urin. Kinder, alleinstehende Mütter und Krüppel betteln an jeder Ecke um Almosen. Der traditionelle Zentralismus unserer Gesellschaft hat sich eindeutig als unfähig erwiesen, die vielfältigen Bedürfnisse eines Landes im Wandel zu befriedigen.[^186]

De Soto bezeichnete die Abkehr von der grotesken gesetzmäßigen Wirtschaft zugunsten des Schwarzmarktes, die im Gange war, bevor Fujimori den Kongress mit Vorhängeschlössern versperrte, als „eine unsichtbare Revolution".

Wir stehen den Vorteilen des freien Marktes positiv gegenüber, aber weit weniger positiv dem Versprechen einer Gesellschaft, in der das Recht genauso verkommen ist wie das Geld. Die Welt, die de Soto vor 1993 in Peru beschrieb, war eine „Clockwork Orange"-Welt, in der übermäßig zentralisierte und dysfunktionale staatliche Institutionen die Zivilgesellschaft buchstäblich zerstörten.

Genau das wollte Fujimori ändern. Er hatte die Inflation gesenkt, indem er die Druckerpressen abstellte. Es war ihm auch gelungen, fünfzigtausend Staatsbedienstete zu entlassen und einige Subventionen zu kürzen. Er hatte einen Anfang gemacht, um den Haushalt auszugleichen. Sein Reformprogramm enthielt umfassende Pläne zur Schaffung freier Märkte und zur Privatisierung der Industrie. Aber wie in der ehemaligen Sowjetunion waren die meisten wichtigen Elemente von Fujimoris Reform 1993 noch nicht verabschiedet, einschließlich der ersten Runde der groß angelegten Privatisierung von staatlichen Banken, Bergbauunternehmen und Versorgungsbetrieben. Anstatt diese notwendigen Vorschläge umzusetzen, versuchte der peruanische Kongress, ähnlich wie der russische Kongress, der Jelzins Reformen in Moskau in Frage stellte, einen Rückzieher zu machen. Ihr Plan: Wiederherstellung von Subventionen aus einer leeren Staatskasse, Aufstockung der Gehaltslisten und Schutz aller Besitzstände, insbesondere der Bürokratie - genau das, was man von einer Regierung erwarten würde, die von ihren Angestellten kontrolliert wird.

Fujimori behauptete, der peruanische Kongress sei unentschlossen und korrupt, eine Tatsache, der fast jeder zustimmte. Er behauptete weiter, dass das Zaudern und die Korruption des Kongresses es unmöglich machten, die kollabierende peruanische Wirtschaft zu reformieren oder einen gewaltsamen Angriff der Narco-Terroristen und der nihilistischen Sendero Luminoso (Leuchtender Pfad) Guerilla zu bekämpfen.

### Die 70-Prozent-Lösung

Fujimori schloss also den Kongress, ein Akt, der darauf hätte hindeuten können, dass er genauso autoritär war wie viele frühere lateinamerikanische Führer. Wir waren jedoch der Meinung, und haben dies damals auch gesagt, dass Fujimori ein grundlegendes Reformhindernis richtig erkannt hatte. Die überschwänglichen Klagelieder amerikanischer Redakteure und Beamten des Außenministeriums bezüglich des peruanischen Kongresses wurden von der peruanischen Bevölkerung nicht geteilt. Während die Nordamerikaner so taten, als sei der peruanische Kongress die Inkarnation von Freiheit und Zivilisation, jubelte das peruanische Volk. Die Popularität von Präsident Fujimori stieg auf über 70 Prozent, als er den Kongress nach Hause schickte. Und er wurde später mit einem Erdrutschsieg für eine zweite Amtszeit wiedergewählt. Die meisten Bürger sahen ihre Legislative offenbar eher als Hindernis für ihr Wohlergehen denn als Ausdruck ihrer Rechte. 1994 erreichte das reale Wirtschaftswachstum in Peru 12,9 %, das höchste der Welt.

### Die Deflation politischer Versprechen

Wir sahen in den Unruhen in Peru weniger einen Rückfall in die Diktaturen der Vergangenheit als vielmehr eine erste Etappe einer umfassenderen Übergangskrise. Es ist zu erwarten, dass es in vielen Ländern zu Fehlregierungen kommen wird, wenn politische Versprechen enttäuscht werden und den Regierungen das Geld ausgeht. Letztendlich werden sich neue institutionelle Formen herausbilden müssen, die in der Lage sind, die Freiheit unter den neuen technologischen Bedingungen zu bewahren und gleichzeitig den gemeinsamen Interessen aller Bürger Ausdruck und Leben zu verleihen.

Nur wenige haben begonnen, über die Unvereinbarkeit zwischen einigen der Institutionen der industriellen Regierung und der Megapolitik der postindustriellen Gesellschaft nachzudenken. Unabhängig davon, ob diese Widersprüche ausdrücklich anerkannt werden oder nicht, werden ihre Folgen nichtsdestotrotz immer deutlicher, wenn sich die Beispiele für politisches Versagen in der ganzen Welt häufen. Die Regierungsinstitutionen, die in der Neuzeit entstanden sind, spiegeln die megapolitischen Bedingungen von vor einem oder mehreren Jahrhunderten wider. Das Informationszeitalter wird neue Mechanismen der Repräsentation erfordern, um chronische Funktionsstörungen und sogar den sozialen Zusammenbruch zu vermeiden.

Als 1989 die Berliner Mauer fiel, bedeutete dies nicht nur das Ende des Kalten Krieges, sondern war auch das äußere Zeichen für ein stilles Erdbeben in den Grundfesten der Macht in der Welt. Es war das Ende einer langen Periode der zunehmenden Rendite der Gewalt. Der Untergang des Kommunismus, den wir 1987 in Blood in the Streets und noch früher in unserem monatlichen Newsletter Strategic Investment prognostizierten, war nicht nur die Ablehnung einer Ideologie. Er war das äußere Zeichen für die wichtigste Entwicklung in der Geschichte der Gewalt in den letzten fünf Jahrhunderten. Wenn unsere Analyse richtig ist, wird sich die Organisation der Gesellschaft zwangsläufig ändern, um die zunehmenden Ungleichgewichte bei der Anwendung von Gewalt widerzuspiegeln. Die Grenzen, innerhalb derer die Zukunft liegen muss, sind neu gezogen worden.

[^163]: Zitiert in Tilly, ebenda, S. 84.

[^164]: Siehe John Keegan, A History of Warfare (London: Hutchinson, 1993), S. 321.

[^165]: Jim Taylor und Watts Wacker, The 500-Year Delta: What Happens After What Comes Next, New York: HarperCollins, 1997, S. 38-39.

[^166]: Ebenda, S. 39.

[^167]: The Cambridge Ancient History, ebenda, S. 263-64.

[^168]: Cook et al., ebenda, S. 268.

[^169]: Für Weiteres zur Logik von hydraulischen Gesellschaften, siehe Karl A. Wittfogel, Oriental Despotism: A Comparative Study of Total Power (New Haven: Yale University Press, 1957).

[^170]: Tilly, Ebenda, S.28.

[^171]: Lane, „Consequences of Organized Violence", ebenda, S. 406.

[^172]: Ebenda.

[^173]: Ebenda., S. 412.

[^174]: Tilly, ebenda, S. 96-126.

[^175]: Ebenda., S. 130.

[^176]: Ebenda., S. 110.

[^177]: Dieses Beispiel ebenda, S. 139.

[^178]: Ebenda., S. 115.

[^179]: Siehe Mancur Olson, The Logic of Collective Action (Cambridge: Harvard University Press, 1965).

[^180]: Josep R. Llobera,\_The God of Modernity: The Development of Nationalism in Western Europe (Oxford: Berg Publishers, 1994), S. ix-x.

[^181]: Ebenda., S. xiii.

[^182]: Siehe William McNeill, Polyethnicity and National Unity in World History (Toronto: University of Toronto Press, 1986).

[^183]: Ebenda., S. 7.

[^184]: Hernando de Soto, The Other Path (New York: Harper & Row, 1989).

[^185]: Ebenda.

[^186]: Ebenda., S .6.
