# MORAL UND VERBRECHEN IN DER „NATÜRLICHEN WIRTSCHAFT" DES INFORMATIONSZEITALTERS

> „Korruption\...ist weitaus verbreiteter und universeller als bisher angenommen. Beweise dafür sind überall zu finden, sowohl in Entwicklungsländern als auch, mit wachsender Häufigkeit, in Industrieländern. \...Hochrangige politische Persönlichkeiten, darunter Staatsoberhäupter und Minister, wurden der Korruption beschuldigt. \...In gewisser Weise repräsentiert dies eine Privatisierung des Staates, bei der die Macht nicht, wie Privatisierung normalerweise impliziert, dem Markt überlassen wird, sondern an Regierungsbeamte und Bürokraten geht." [^467] - Viro Tanzi

Wir gehen davon aus, dass sich der moderne Nationalstaat immer mehr auflöst und „Barbaren der Neuzeit“ zunehmend die tatsächliche Macht hinter den Kulissen ausüben. Gruppierungen wie die russischen Mafiaclans, die die Überreste der ehemaligen Sowjetunion ausschlachten, ethnische Verbrecherbanden, Nomenklaturen, Drogenbarone und abtrünnige Geheimdienstagenturen werden immer mehr zu Rechtsstaaten in sich selbst. Sie sind es bereits. Viel mehr als allgemein bekannt ist, haben die modernen Barbaren bereits die Formen des Nationalstaates infiltriert, ohne sein Erscheinungsbild allzu sehr zu verändern. Sie sind Mikroparasiten, die sich von einem sterbenden System ernähren. Ebenso gewalttätig und skrupellos wie ein Staat im Krieg, wenden diese Gruppen die Techniken des Staates auf kleinerer Ebene an. Ihr wachsender Einfluss und ihre Macht sind Teil der Verkleinerung der Politik. Durch die Mikroverarbeitung wird die Größe, die Gruppen erreichen müssen, um eine effektive Nutzung und Kontrolle der Gewalt zu gewährleisten, reduziert. Mit dem Fortschreiten dieser technologischen Revolution wird räuberische Gewalt zunehmend außerhalb zentraler Kontrollen organisiert. Auch Bemühungen, Gewalt einzudämmen, werden sich mehr auf Effizienz als auf die Größe der Macht stützen.

Die verstärkte heimliche kriminelle Aktivität und Korruption innerhalb von Nationalstaaten wird eine wichtige Nebenhandlung in der Veränderung der Welt bilden. Was Sie sehen könnten, wäre eine heimtückische und düstere Variante eines schlechten Films, die *Invasion der Körperfresser*. Bevor die meisten Nationalstaaten sichtbar zusammenbrechen, werden sie von neuzeitlichen Barbaren dominiert. Nicht selten, wie in dem berühmten B-Film aus den 1950er-Jahren, werden sie getarnte Barbaren sein. Die Körperfresser der Zukunft werden jedoch keine Außerirdischen aus dem Weltraum sein, sondern Kriminelle unterschiedlicher Zugehörigkeit, die offizielle Positionen bekleiden und sich zumindest teilweise außerhalb der verfassungsmäßigen Ordnung bewegen.

Das Ende einer Ära ist normalerweise eine Zeit intensiver Korruption. Wenn sich die Bindungen an das alte System auflösen, löst sich auch das soziale Ethos auf. Dies schafft eine Atmosphäre, in der Personen in hohen Positionen öffentliche Anliegen mit privaten kriminellen Aktivitäten vermischen können.

Leider können Sie sich nicht auf normale Informationskanäle verlassen, um ein genaues und rechtzeitiges Verständnis vom Zerfall des Nationalstaates zu erhalten. Die „hartnäckige Täuschung", die den Untergang des Römischen Reiches verschleiert hat, ist wahrscheinlich ein typisches Merkmal für den Zerfall großer politischer Einheiten. Sie verschleiert und maskiert nun den Zusammenbruch des Nationalstaates. Aus verschiedenen Gründen kann man sich nicht immer darauf verlassen, dass die Nachrichten die Wahrheit sagen. Viele sind konservativ in dem Sinne, dass sie die Parteien der Vergangenheit repräsentieren. Einige sind durch anachronistische ideologische Verpflichtungen zum Sozialismus und zum Nationalstaat geblendet. Einige werden aus konkreteren Gründen Angst haben, die Korruption zu offenbaren, die in einem zerfallenden System wahrscheinlich immer mehr zum Vorschein kommen wird. Einigen fehlt der physische Mut, der für eine solche Aufgabe erforderlich sein könnte. Andere fürchten um ihren Arbeitsplatz oder haben Angst vor anderen Vergeltungsmaßnahmen, wenn sie ihre Meinung sagen. Und natürlich gibt es keinen Grund zu der Annahme, dass Reporter und Redakteure weniger anfällig für korrupte Überlegungen sind als Bauinspektoren oder italienische Straßenbauunternehmer. Wichtige Informationsorgane, die scheinbar alles melden wollen, können sich in größerem Umfang als erwartet als weniger verlässliche Informationsquellen erweisen, als gemeinhin angenommen wird. Viele werden andere Beweggründe haben, einschließlich der Unterstützung für ein schwankendes System, die sie einer ehrlichen Information vorziehen. Sie werden wenig sehen und noch weniger erklären.

## JENSEITS DER REALITÄT

Mit der stetigen Verbesserung der Technologien für künstliche Realität und Computerspiele werden Sie sogar in der Lage sein, einen Abendnachrichtenbericht zu bestellen, der genau die Nachrichten simuliert, die Sie sehen möchten. Möchten Sie einen Bericht sehen, in dem Sie selbst als Sieger des Zehnkampfs bei den Olympischen Spielen dargestellt werden? Kein Problem. Es könnte die Schlagzeile von morgen sein. Sie werden jede Geschichte, die Sie sich wünschen, ob wahr oder falsch, auf Ihrem Fernseher/Computer sehen, und zwar mit größerer Wahrhaftigkeit als alles, was NBC oder die BBC derzeit vorweisen können.

Wir bewegen uns rasant auf eine Welt zu, in der Informationen so weit von den Grenzen der Realität befreit sein werden, wie die menschliche Erfindungsgabe es ermöglicht. Sicherlich wird dies enorme Auswirkungen auf die Qualität und den Charakter der Informationen haben, die Sie erhalten. In einer Welt der künstlichen Realität und der sofortigen Übertragung von allem und jedem wird die Integrität des Urteils und die Fähigkeit, das Wahre vom Falschen zu unterscheiden, noch wichtiger.

Diese Veränderung wird jedoch weniger von unseren gegenwärtigen Umständen abweichend sein, als es viele Menschen vermuten würden. Die Unterscheidungen zwischen wahr und unwahr werden häufig aus Gründen verwischt, die durch Technologie verstärkt wurden. Wir sagen dies in dem Bewusstsein, dass viele der Folgen der Informationsrevolution befreiend waren.

Die Technologie hat bereits begonnen, geographische Nähe und politische Dominanz zu überwinden. Regierungen können Hindernisse errichten, um den Handel mit Waren zu behindern, aber sie können viel weniger tun, um die Übertragung von Informationen zu stoppen. Fast jeder Gast in einem beliebigen Restaurant in Hongkong ist über das Mobiltelefon mit dem Rest der Welt verbunden. Die Hardliner-Putschisten in Moskau konnten im August 1991 Jelzins Kommunikation nicht unterbrechen, weil er Mobiltelefone hatte.

### Mehr Information, weniger Verständnis

Da die Barrieren zur Informationsübertragung gefallen sind, gibt es nun mehr davon, was gut ist. Aber es gibt auch mehr Verwirrung darüber, was etwas bedeutet. Die moderne Technologie, die hilft, Informationen von politischen Kontrollen und zeitlich-räumlichen Hindernissen zu befreien, neigt auch dazu, den Wert des altmodischen Urteilsvermögens zu erhöhen. Die Art von Einsicht, die hilft, das Wichtige und Wahre aus dem Berg von Fakten und Fantasien herauszufiltern, gewinnt fast täglich an Wert. Dies ist aus mindestens drei Gründen der Fall:

1.  Angesichts der Flut von Informationen, die heute zur Verfügung stehen, ist es wichtig, sich kurz zu fassen.

Kürze führt zu Verkürzung. Verkürzung lässt das Unvertraute weg. Wenn man viele Fakten zu verdauen und zahlreiche Telefonanrufe zu erledigen hat, ist das natürliche Bedürfnis, jeden Informationsverarbeitungsvorgang so knapp wie möglich zu gestalten. Leider bietet verkürzte Information oft eine schlechte Grundlage für das Verständnis. Die tieferen und reicheren Texturen der Geschichte sind genau die Teile, die in den 25-Sekunden-Soundbites tendenziell weggeschnitten und auf CNN missverstanden werden. Es ist viel einfacher, eine Nachricht zu vermitteln, die eine Variation eines bereits verstandenen Themas ist, als ein neues Verständnisparadigma zu erforschen. Man kann viel einfacher über ein Baseball- oder Cricketspiel berichten, als zu erklären, wie Baseball oder Cricket gespielt wird und was das bedeutet.

2\. Der rasante technologische Wandel untergräbt die megapolitische Grundlage der sozialen und wirtschaftlichen Organisation. Dies hat zur Folge, dass ein umfassendes paradigmatisches Verständnis oder unausgesprochene Theorien darüber, wie die Welt funktioniert, schneller als in der Vergangenheit veraltet sind. Damit steigt die Bedeutung des Gesamtüberblicks und sinkt der Wert einzelner „Fakten", die für fast jeden, der über ein Informationssuchsystem verfügt, leicht zugänglich sind.

3\. Die zunehmende Tribalisierung und Marginalisierung des Lebens haben den Diskurs und sogar das Denken beeinträchtigt. Viele Menschen haben sich infolgedessen angewöhnt, vor Schlussfolgerungen zurückzuscheuen, die offensichtlich von den ihnen zur Verfügung stehenden Fakten nahegelegt werden. Eine kürzlich durchgeführte psychologische Studie, die als Meinungsumfrage getarnt war, zeigte, dass Mitglieder einzelner Berufsgruppen fast einhellig jede Schlussfolgerung ablehnten, die einen Einkommensverlust für sie implizierte, unabhängig davon, wie stichhaltig die sie unterstützende Logik war. Angesichts der zunehmenden Spezialisierung ist die Mehrzahl der interpretativen Informationen über die meisten spezialisierten Berufsgruppen darauf ausgelegt, den Interessen der Gruppen selbst zu dienen. Sie haben wenig Interesse an Ansichten, die unhöflich, unprofitabel oder politisch inkorrekt sein könnten. Es gibt kein besseres Beispiel für diese allgemeine Tendenz als den breiten Trommelwirbel von Ansichten, der eine rosige Zukunft für Investitionen an der Börse nahelegt. Die meisten dieser Informationen werden von Brokerhäusern generiert, von denen nur wenige Ihnen sagen werden, dass Aktien überbewertet sind. Ihr Einkommen stammt aus dem Transaktionsgeschäft, das davon abhängt, dass die Mehrheit der Kunden bereit ist zu kaufen. Unabhängige, gegensätzliche Stimmen sind selten zu hören.

Aus diesen und anderen Gründen ist das Zeitalter der Information noch nicht das Zeitalter des Verstehens geworden. Im Gegenteil, es hat einen starken Rückgang der Rigorosität in der öffentlichen Diskussion gegeben. Die Welt könnte jetzt mehr wissen als zu irgendeinem früheren Zeitpunkt. Aber es gibt kaum noch eine öffentliche Stimme, die die Bedeutung von Ereignissen bewerten und sagen kann, was wahr ist. Das ist der Grund, warum wir fasziniert davon sind, das laue Interesse, insbesondere in den US-Medien, an der Berichterstattung über Hinweise auf sensationelle Korruption auf hohen Ebenen der US-Regierung zu sehen.

Ein zentrales Thema, mit dem wir uns in diesem Buch auseinandergesetzt haben, ist wie sich verändernde Technologien und andere „megapolitische" Faktoren die „natürliche Wirtschaft" verändern. Die „natürliche Wirtschaft" ist der darwinsche „Naturzustand", in dem Ergebnisse, manchmal ungerecht, durch körperliche Kraft bestimmt werden. In der „natürlichen Wirtschaft" ist ein wichtiger Verhaltensstrang das, was Biologen als „Interferenz-Konkurrenz" bezeichnen.

### Interferenz-Konkurrenz

„Interferenz-Konkurrenten", wie Jack Hirshleifer es ausdrückte, „gewinnen und behalten die Kontrolle über Ressourcen, indem sie ihre Rivalen direkt bekämpfen oder behindern." [^468] So sehr wir uns auch wünschen mögen, dass menschliches Verhalten stets dem Gesetz und „anderen sozial durchgesetzten Spielregeln" („politische Ökonomie") unterliegt, gibt es ausreichend Beweise dafür, dass viele Menschen nur „nach den Regeln spielen", wenn es ihnen passt. Hirshleifer, eine Autorität in Sachen Konflikt, formulierte es so: „Die Beharrlichkeit von Verbrechen, Krieg und Politik lehrt uns, dass tatsächliche menschliche Angelegenheiten weiterhin stark den zugrunde liegenden Druckmitteln der natürlichen Wirtschaft unterliegen." [^469]

Mit anderen Worten werden wirtschaftliche Ergebnisse nicht nur durch das friedliche und gesetzestreue Verhalten des in Lehrbüchern beschriebenen Homo oeconomicus bestimmt, der Eigentumsrechte respektiert „und einfach nicht nehmen wird, was ihm nicht gehört".[^470] Tatsächliche Ergebnisse werden auch durch Konflikte geformt, einschließlich offen ausgeübter Gewalt. Wie der Ökonom Hirshleifer hervorhebt, wird „selbst unter Gesetz und Regierung der rationale, selbstinteressierte Mensch zwischen legalen und illegalen Mitteln zur Beschaffung von Ressourcen - zwischen Produktion und Austausch einerseits und Diebstahl, Betrug und Erpressung andererseits - ein Gleichgewicht finden." [^471]

## RAUBÜBERFALL IM INFORMATIONSZEITALTER

Michelle R. Garfinkel und Stergios Skaperdas untersuchen dies in ihrem aufschlussreichen Buch über Gewalt, Kriminalität und Politik, *The Political Economy of Conflict and Appropriation*: „Individuen und Gruppen können entweder produzieren und somit Reichtum schaffen oder den von anderen erschaffenen Reichtum an sich reißen." [^472] Sie zitieren eine Geschichte moderner Interferenz-Konkurrenz, die ursprünglich vom *Economist* berichtet wurde: „Ein amerikanischer Geschäftsmann, der gerade in Moskau angekommen war, um ein Büro zu eröffnen, wurde in seinem Hotel von fünf Männern mit goldenen Uhren, Pistolen und einem Ausdruck des Nettovermögens seiner Firma empfangen. Sie verlangten 7% der künftigen Einnahmen. Er nahm den ersten Flug nach New York, wo Straßenräuber weniger raffiniert sind." [^473] Diese Geschichte des Raubüberfalls im Informationszeitalter verdankt der neuen Technologie mehr, als der einfachen Tatsache, dass russische Schläger nun über das Internet Zugang zu Finanzprofilen und Kreditauskünften ihrer Opfer haben.

### Sinkende Entscheidungskraft der militärischen Macht

Zum Guten wie zum Schlechten hat die Informationstechnologie durch die Verringerung der Bedeutung von Großmächten das Entscheidungspotenzial des Nationalstaates in einer unruhigen Welt drastisch reduziert. Wo einst, wie Voltaire sagte, „Gott auf der Seite der größeren Bataillone war", scheint es mit jedem vergehenden Tag weniger göttliche Unterstützung für die Erzeugung großer Gewaltrenditen zu geben. Stattdessen sehen wir das Gegenteil - mehr Hinweise auf sinkende Gewaltrenditen - was stark darauf hindeutet, dass große Konglomerate wie der Nationalstaat ihre enormen Gemeinkosten nicht mehr rechtfertigen können.

Das offensichtlichste Anzeichen für die sinkende Entscheidungsmacht zentralisierter Gewalt ist der Anstieg des Terrorismus. Hochkarätige Bombenanschläge in den USA in den mittleren neunziger Jahren zeigen, dass selbst die größte militärische Supermacht der Welt nicht vor Angriffen gefeit ist.

Eine weitere wichtige Erscheinung des Rückgangs der Gewaltbereitschaft ist die weltweite Zunahme des Gangstertums und der organisierten Kriminalität sowie der damit einhergehenden politischen Vetternwirtschaft und Korruption. Sie spiegeln eine allgemein unmoralische Atmosphäre wider, in der der Staat zwingen, aber nicht schützen kann. In dem Maße, in dem das Gewaltmonopol zerfällt, drängen neue Konkurrenten auf den Plan, wie die Schläger, die dem amerikanischen Geschäftsmann in Moskau ihre eigenen privaten Steuern aufzwingen wollten.

Kleine Gruppen, Stämme, Triaden, Banden, Gangster, Mafias, Milizen und sogar einzelne Individuen haben zunehmend militärische Wirksamkeit erlangt. Sie werden in der „natürlichen Wirtschaft" des nächsten Jahrtausends viel mehr reale Macht ausüben, als sie es im zwanzigsten Jahrhundert getan haben. Waffen, die Mikrochips verwenden, neigen dazu, das Machtgleichgewicht in Richtung Verteidigung zu verschieben, wodurch entscheidende Aggressionen weniger lukrativ und daher weniger wahrscheinlich werden. Intelligente Waffen, wie Stinger-Raketen beispielsweise, neutralisieren effektiv einen Großteil des Vorteils, den große, wohlhabende Staaten bisher beim Einsatz teurer Luftwaffen gegen ärmere, kleinere Gruppen genossen haben.

### Informationskrieg voraus

Unmittelbar bevor steht die heiß diskutierte, aber wenig verstandene Möglichkeit des „Informationskrieges". Dies weist auch auf abnehmende Gewaltrenditen hin. „Logikbomben" könnten Flugverkehrskontrollsysteme, Eisenbahnweichensysteme, Stromerzeuger und -verteilungsnetze, Wasser- und Abwassersysteme, Telefonrelais, sogar die eigenen Kommunikationssysteme des Militärs lahmlegen oder sabotieren. Da Gesellschaften immer mehr von computerisierten Kontrollsystemen abhängig werden, könnten „Logikbomben" fast genauso viel Schaden verursachen wie physische Explosionen.

Im Gegensatz zu herkömmlichen Bomben könnten „Logikbomben" nicht nur von feindlichen Regierungen, sondern auch von Gruppen freiberuflicher Computerprogrammierer und sogar talentierten einzelnen Hackern aus der Ferne gezündet werden. Beachten Sie, dass 1996 ein argentinischer Teenager verhaftet wurde, weil er wiederholt in die Computer des Pentagons eingedrungen ist. Zwar haben Hacker bisher nicht dazu geneigt, computergesteuerte Systeme auf zerstörerische Weise zu manipulieren, aber das liegt nicht daran, dass es wirklich wirksame Mittel gibt, sie zu stoppen.

Wenn das Zeitalter des Informationskrieges endlich anbricht, ist es unwahrscheinlich, dass seine Antagonisten nur Regierungen sein werden. Ein Unternehmen wie Microsoft hat sicherlich eine größere Fähigkeit, einen Informationskrieg zu führen, als 90 Prozent der Nationalstaaten der Welt.

### Das Zeitalter des souveränen Individuums

Dies ist Teil des Grundes, warum wir dieses Buch „Das souveräne Individuum" genannt haben. Da der Umfang der Kriegsführung abnimmt, werden Verteidigung und Schutz auf kleinerer Ebene organisiert. Daher werden es zunehmend private statt öffentliche Güter sein, die von privaten Auftragnehmern auf Basis von Gewinnstreben bereitgestellt werden. Dies zeigt sich bereits in der Privatisierung der Polizeiarbeit in Nordamerika. Eine der am schnellsten wachsenden Berufsgruppen in den USA ist der „Sicherheitswachmann". Prognosen deuten darauf hin, dass die Anzahl der privaten Sicherheitskräfte bis zum Jahr 2005 um 24 bis 40 Prozent über den Werten von 1990 zunehmen wird.[^474]

Die Privatisierung der Polizei ist bereits ein deutlich erkennbarer Trend. Wie jedoch der anglo-irische Experte Hamish McRae hervorhebt, ist dies kaum das Ergebnis einer bewussten Entscheidung der Regierung. Er schreibt dazu in „Die Welt im Jahr 2020":

> Weder hat irgendeine Regierung die spezielle Entscheidung getroffen, sich aus bestimmten Polizeiaufgaben zurückzuziehen, noch haben sie sich tatsächlich zurückgezogen; der Privatsektor ist vielmehr hineingegrätscht. Dies ist teilweise eine Folge der wahrgenommenen Versäumnisse der Polizei, aber auch eine Folge anderer gesellschaftlicher Veränderungen. Private Sicherheitsfirmen übernehmen allmählich einen Großteil der Aufgabe, normale Bürger in ihren Büros oder Einkaufszentren zu schützen. Wie die geschlossenen Wohnanlagen von Los Angeles zeigen, bewegen sich die Menschen sogar wieder ein Stück weit in Richtung des mittelalterlichen Stadt-Konzepts, wo die Bewohner hinter Stadtmauern leben, die von Wachen patrouilliert werden, und der Zugang nur an kontrollierten Toren möglich ist.[^475]

Wir glauben, dass dies nur ein Vorgeschmack auf eine umfassendere Privatisierung fast aller Funktionen ist, die von den Regierungen im zwanzigsten Jahrhundert bislang ausgeübt wurden. Da die Informationstechnologie die Fähigkeit zentralisierter Autoritäten untergraben hat, Macht auszuüben und physische Sicherheit für Systeme zu gewährleisten, die in großem Maßstab operieren, sinkt die optimale Größe fast jedes Unternehmens in der „natürlichen Wirtschaft".

Um auf diese technologische Veränderung zu reagieren, wird ein massiver Investitionsbedarf (besser: Chance) erforderlich sein, um anfällige Systeme neu zu gestalten, mit dezentralisierten anstatt konzentrierten Fähigkeiten. Wenn Schwachstellen im großen Maßstab nicht beseitigt werden, werden die Systeme, die sie beibehalten, einem katastrophalen Ausfall unterliegen.

Früher oder später werden sich Dienstleistungen und Produkte, die von großen bürokratischen Behörden und Unternehmen angeboten werden, in stark wettbewerbsorientierte Märkte verwandeln, die nicht von einem „Hauptquartier" aus, sondern über ein verteiltes, dezentralisiertes Netz verwaltet werden. Das Unternehmen mit einem Hauptsitz, der von Streikposten umgeben oder von Terroristen sabotiert werden kann, wird anfällig sein, bis er letztendlich zu einer „virtuellen Firma" ohne fixem Standort wird, „die gleichzeitig an vielen Orten wohnt", wie Kevin Kelly, leitender Redakteur des Wired Magazins, in *Out of Control* schreibt.[^476] Kelly weiß, dass die Technologie die Notwendigkeit, Produktionsprozesse unter zentrale Kontrolle zu bringen, verändert hat. „Während des größten Teils der industriellen Revolution wurde ernsthafter Wohlstand durch die Zusammenführung von Prozessen unter einem Dach geschaffen. Größer war effizienter." Heute ist das nicht mehr der Fall.

Kelly sieht die Möglichkeit voraus, dass das Auto der Zukunft, das Upstart Car, möglicherweise von nur einem Dutzend Menschen entworfen und in Produktion gebracht werden könnte, die in einer virtuellen Firma zusammenarbeiten.

In der Zukunft könnte übermäßige Größe nicht nur kontraproduktiv, sondern auch gefährlich sein. Größere Unternehmen stellen verlockendere Ziele dar. Wie Praktiker der Untergrundwirtschaft zeigen, ist einer der Geheimnisse zur Vermeidung von Steuern, die Vermeidung von Entdeckung. Dies wird für kleinere, „virtuelle Unternehmen" viel einfacher sein als für altmodische Konzerne, die von einer Hochhauszentrale aus operieren, deren Name in Leuchtschrift über der Tür steht. Sie sind zwangsläufig anfälliger für die Aufmerksamkeit von „Männern mit goldenen Uhren, Pistolen und einem Ausdruck des Nettovermögens der Firma", den Gangstern, die in anderen Teilen der Welt ihre eigene Art der Besteuerung durchsetzen werden, wie sie es in Russland tun. Unternehmen aller Größenordnungen werden anfällig für kriminelle Ausplünderungen und Auflagen durch organisierte kriminelle Banden.

> „Betrachten Sie die Definition eines Erpressers als jemanden, der eine Bedrohung schafft und dann Gebühren für deren Reduzierung verlangt. Im Vergleich dazu kann oft die Bereitstellung von Schutz durch Regierungen als Erpressung eingestuft werden." [^477] - Charles Tilly

### Die Natur hasst Monopole

Sobald das auf Gewalt basierende Monopol der „größeren Bataillone" zerfällt, ist einer der ersten zu erwartenden Auswirkungen ein zunehmender Wohlstand für das organisierte Verbrechen. Immerhin stellt das organisierte Verbrechen die größte Konkurrenz für Nationalstaaten dar, wenn es darum geht, Gewalt für räuberische Zwecke einzusetzen. Obwohl es unhöflich ist, dies zu sagen, sollte nicht vergessen werden, wie uns der Politikwissenschaftler Charles Tilly erinnert, dass Regierungen selbst -- „die Schutzgelderpresser schlechthin mit dem Vorteil der Legitimität - als unsere größten Beispiele für organisierte Kriminalität gelten." [^478]

Wenn Sie nichts anderes über die Welt wüssten, als dass ein wichtiges Monopol gerade zusammenbricht, wäre eine der einfachsten und sichersten Vorhersagen, die Sie treffen könnten, dass seine nächsten Wettbewerber am meisten profitieren würden. Es ist daher kein Zufall, dass Drogenkartelle, Banden, Mafias und Triaden verschiedenster Art auf der ganzen Welt zunehmen.

### Sistema del Potere

Von Russland über Japan bis hin zu den Vereinigten Staaten ist die organisierte Kriminalität ein weit wichtigerer Faktor im Betrieb von Volkswirtschaften, als Wirtschaftsbücher Sie glauben lassen würden. Was die Sizilianer das „*sistema del potere*", das „System der Macht", der organisierten Kriminalität nennen, spielt eine zunehmend wichtige Rolle dabei, zu bestimmen, wie Volkswirtschaften funktionieren.

Europäische Polizeibeamte berichten, dass internationale Verbrechensyndikate, darunter die russische und italienische Mafia, „eine dominante Rolle" bei der Finanzierung der genozidalen Kriege spielten, die in den letzten Jahren auf dem Balkan wüteten.

Drogenschmuggler haben ebenfalls eine Schlüsselrolle bei der Finanzierung jüngster Bürgerkriege und Aufstände in anderen Teilen der Welt gespielt. Julio Fernandez, Chef der spanischen Drogenpolizei in Katalonien, sagt: „Von 1986 bis 1988 wurden 80 Prozent des Heroins in Spanien von Tamil Tiger Guerillas transportiert, die mit pakistanischen Bewohnern in Barcelona oder Madrid zusammenarbeiteten. Als wir dieses Netzwerk durch Festnahmen zerschlagen haben, wurde es durch Kurden aus der Türkei ersetzt, die es in den nächsten zwei Jahren völlig dominierten." [^479] Es ist sehr wahrscheinlich, dass immer dann, wenn ein neuer Bürgerkrieg oder Aufstand beginnt, die verzweifelten armen Kämpfer ihre militärischen Bemühungen durch den Transport von Drogen und die Geldwäsche von Drogengeld finanzieren.

### Drogenfinanzierte Rabatte

Die Aktivitäten organisierter krimineller Syndikate üben einen Abwärtsdruck auf die Preise von Waren aus, mit Ausnahme von Drogen. Auf mikroökonomischer Ebene subventionieren Verbrechersyndikate offenbar legitime Geschäfte mit der Beute aus kriminellen Unternehmungen. Sie können Drogengewinne und andere illegale Gelder waschen, indem sie gewöhnliche Waren unterhalb der Kosten verkaufen, wodurch sie die Preise ihrer sauberen Wettbewerber unterbieten und viele davon aus dem Geschäft drängen.

### Yakuza-Deflation

In Japan spielten die mächtigen Yakuza-Gangs eine Schlüsselrolle in der hyperaktiven Immobilienblase der späten 1980er Jahre. Trotz der Tatsache, dass die neunzigtausend Yakuza jährlich zwischen 10,19 Milliarden Dollar (offizielle Schätzung) und 71,35 Milliarden Dollar (Schätzung von Professor Takatsugu Nato) verdienen, wurde ein hoher Anteil der uneinbringlichen Kredite, die die Zahlungsfähigkeit der japanischen Banken gefährdet haben, durch Yakuza-unterstützte Geschäfte gemacht.[^480] Der Deflationsdruck - die „Preiszerstörung", wie die Japaner es nennen - die Japans Wirtschaft prägten, sind eine Folge davon.

### Ein Auge zudrücken

Die Mafias Russlands, wie Jelzin selbst zugegeben hat, sind mit „kommerziellen Strukturen, Verwaltungsbehörden, Innenministerien und städtischen Autoritäten \..." [^481] verschmolzen. Aufgrund der Immunität, die die Mafias durch die Verschmelzung mit der Polizei erreicht haben, sind sie in der Lage, die Einziehung ihrer Privatsteuern durch offenkundige Gewalt zu erzwingen. Autoritative Quellen weisen darauf hin, dass vier von fünf russischen Unternehmen nun „Schutzgeld" zahlen. „Laut einigen Berichten müssen lokale Kleinunternehmen in Russland 30 bis 50 Prozent ihrer Gewinne an Räuber abgeben, nicht nur die mageren 7 Prozent, die vom amerikanischen Geschäftsmann verlangt werden." [^482]

Im Jahr 1993 gab es in Russland offiziell 355.500 als „gangsterhaft" eingestufte Verbrechen, darunter fast „30.000 vorsätzliche Morde", hauptsächlich Gang-Attentate an Geschäftsleuten. Laut einem ehemaligen Innenminister, General Viktor Yerin, „waren die meisten davon Auftragsmorde aufgrund von Konflikten im Bereich der kommerziellen und finanziellen Aktivitäten". In den meisten Fällen drückten die Behörden „ein Auge zu". Kriminelle Organisationen spielen, „durch ihre Kontrolle über Zwang und Korruption", wie die Ökonomen Gianluca Fiorentini und Sam Peltzman in *The Economics of Organized Crime* schreiben, eine Schlüsselrolle in der Wirtschaft.[^483] Theoretisch kann dieser Einfluss manchmal vorteilhaft sein, da er die Regulierung einschränkt und Regierungen möglicherweise dazu ermutigt, ihre Bereitstellung öffentlicher Güter zu verbessern. Die Präsenz einer mächtigen Mafia „schränkt die monopolistische Rolle der Regierungsbehörden ein".[^484] Regierungen in Gebieten mit mächtigen organisierten Kriminalitätsgruppen können nur mit großer Schwierigkeit Maßnahmen verfolgen, denen die Mafias widersprechen.

### Geheime Absprachen

Tatsächlich ist es bemerkenswert, wie selten die meisten Regierungen bereit sind, die Mafias, ihre Hauptkonkurrenten in der Anwendung organisierter Zwangsmaßnahmen, direkt zu konfrontieren. Aus rein wirtschaftlicher Hinsicht ist dies nicht überraschend. Die profitabelste Vereinbarung, die „die gewählten Mitglieder der öffentlichen Verwaltung" treffen können, ist eine „geheime Absprache" mit dem organisierten Verbrechen. Fiorentini und Peltzman stellen fest, dass „es Beweise für groß angelegte Vereinbarungen gibt, bei denen das organisierte Verbrechen politische Unterstützung für Kandidatengruppen sicherstellt, während diese den Gefallen durch eine günstige Verwaltung öffentlicher Beschaffungen und die Bereitstellung öffentlicher Dienstleistungen oder Subventionen erwidern." [^485]

Im Gegensatz zu dem von Hollywood vermittelten Eindruck scheint es nun, dass das Durchdringen und Betrügen von Regierungen zu einem der Hauptziele krimineller Organisationen wie der sizilianischen Mafia geworden ist. „Die meisten Forscher sind mittlerweile der Auffassung, dass das größte Geschäft der sizilianischen Mafia gerade darin besteht, sich verschiedene Quellen öffentlicher Ausgaben anzueignen und Betrug gegen lokale, nationale und europäische Gemeinschaftsförderprogramme zu organisieren." [^486]

### „Narco-Staaten"

Wie wir in *The Great Reckoning* gewarnt haben, sind viele Regierungen auf der Welt durch Drogenbarone gründlich korrumpiert. Mexiko ist ein unbestreitbares Beispiel. Der ehemalige mexikanische Bundesvize-Generalstaatsanwalt Eduardo Valle Espinosa brachte das mexikanische System in seiner Rücktrittserklärung auf den Punkt: „Niemand kann ein politisches Projekt entwerfen, in dem die Köpfe des Drogenhandels und ihre Finanziers nicht berücksichtigt werden. Denn wenn Sie es tun, sterben Sie." Valle deutete an, dass Bestechungsgelder das Amt des mexikanischen Polizeichefs so lukrativ machen, dass Kandidaten bis zu 2 Millionen Dollar zahlen, nur um eingestellt zu werden. In einer strikten Gewinn- und Verlustrechnung kann der Erwerb einer regionalen Polizeibehörde eine lukrative Investition sein. Drogenkartelle sind bereit, auch niederrangigen mexikanischen Beamten hohe Summen zu zahlen, weil das Geld ihnen Immunität vor Strafverfolgung für ihre Verbrechen bietet.

Kolumbien ist ein weiteres Land, in dem die obersten Ränge der Regierung von Drogenbaronen dominiert werden. Die US-Behörden haben kürzlich das US-Visum des kolumbianischen Präsidenten Ernesto Samper abgelehnt, mit der Begründung, dass er wissentlich politische Spenden von Drogenhändlern im Austausch für Gefälligkeiten erhalten habe.

### Ein Esel schimpft den anderen Langohr

Jeder, der die Berichte in unserem Newsletter, *Strategic Investment*, während der 1990er Jahre verfolgt hat, wird sofort die Ironie in der Haltung der Clinton-Administration gegenüber Samper erkennen. Es gibt glaubwürdige Beweise dafür, dass der US-Präsident Bill Clinton selbst all das getan hat, was Samper vorgeworfen wird und noch Schlimmeres. Selbst wenn Sie uns nicht glauben, wird Clintons Hintergrund in schillernden Details in zwei gründlich recherchierten Büchern von Autoren auf gegenüberliegenden Seiten des politischen Spektrums hervorgehoben.

Roger Morris, der meist eine linke Perspektive einnimmt, war Beamter für nationale Sicherheit in der Nixon-Regierung sowie ein leitender Berater für Dean Acheson, Präsident Lyndon B. Johnson und Walter Mondale. Morris hat einen Doktortitel von der Harvard University. Sein Buch, *Partners in Power*, enthüllt eine schmuddelige Vergangenheit für Clinton, die Ernesto Samper wie einen Pfadfinder erscheinen lässt.

Morris erzählt von Clintons vaterloser Kindheit in Hot Springs, Arkansas, einem Zentrum für Glücksspiel, Prostitution und organisiertem Verbrechen, zu dem der Großteil seiner Familie eine gewisse Verbindung hatte. Clintons Stiefonkel, Raymond Clinton, der für Bill Clinton eine „Vaterfigur" war, galt angeblich als eine führende Figur des „Paten" in der Dixie-Mafia. Morris behauptet, dass Bill Clinton ein CIA-Rekrut wurde und seine Studententage in Oxford damit verbrachte, Anti-Vietnamkriegsaktivisten zu überwachen. So wie Morris die Dinge sieht, blieb Clinton ein CIA-Agent während seiner Amtszeit als Gouverneur, und erleichterte eine auf Mena, Arkansas, zentrierte CIA-Drogen- und Waffenhandelsoperation. Morris scheint die gesamte CIA des Drogenhandels zu beschuldigen, anstatt die Möglichkeit in Betracht zu ziehen, dass Clinton sich mit einer korrupten Fraktion der Agentur verbündet hat, was uns wahrscheinlicher erscheint. Jede Interpretation deutet jedoch darauf hin, dass die Hauptgeheimdienstagentur der US-Regierung entweder direkt oder indirekt an organisiertem Drogenhandel im großen Maßstab beteiligt ist. Wenn die CIA nicht ein Anhängsel des organisierten Verbrechens ist, ist sie gefährlich dicht daran, es zu werden.[^487]

### Chance 1:250.000.000

Trotzdem enthält *Partners in Power* Details, die jeden Studenten über Korruption der modernen amerikanischen Politik interessieren würden. Morris richtet seine Kritik jedoch keineswegs nur an Bill Clinton. Auch seine Frau erhält einige kritische Aufmerksamkeit. Betrachten Sie zum Beispiel diesen Auszug aus Morris' Bericht über Hillary Clintons wundersamen Handel mit Rohstoffen: „Im Jahr 1995 führten Ökonomen der Universitäten Auburn und North Florida ein ausgeklügeltes Computerstatistikmodell der Geschäfte der First Lady zur Veröffentlichung in der Zeitschrift *Journal of Economics and Statistics* durch, wobei sie alle verfügbaren Unterlagen sowie Marktinformationen aus dem *Wall Street Journal* nutzten. Die Wahrscheinlichkeit, dass Hillary Rodham ihre Geschäfte auf legitime Weise gemacht hat, berechneten sie, war weniger als eins zu 250.000.000." [^488]

Morris führt viele belastende Details über den Drogenhandel und die Geldwäsche auf, die unter Clinton in Arkansas florierten. „Durch das schiere Ausmaß der Drogen und des Geldes, das durch die Flüge generiert wurde, wurde das winzige Mena, Arkansas, in den 1980er Jahren zu einem der weltweiten Zentren des Drogenhandels." [^489] Morris zitiert einen Vertrauten, der über Clinton aussagte: „Er wusste Bescheid."

Clinton wusste nicht nur vom Kokainschmuggel, sondern sagte laut dem State Trooper L.D. Brown, einem ehemaligen Leibwächter, dem Clinton zu einer Position bei der CIA verholfen hatte, dass der Drogenhandel keine CIA-Operation sei. „‚Oh, nein', sagte Clinton, ‚Das ist ein Geschäft von Lasater.'" [^490]

Dan Lasater, ein verurteilter Kokainhändler, war einer von Clintons wichtigsten finanziellen Unterstützern. Ein Mann, der Millionen mit Geschäften in Arkansas verdiente und angeblich dem damaligen Gouverneur von Kentucky, John Y. Brown, 300.000 Dollar in bar in einer braunen Papiertüte gab. Laut Morris war Lasater „nie nur ein weiterer großer Spender, dem besondere Beachtung geschenkt wurde, sondern ein außergewöhnlich enger Vertrauter, den Clinton regelmäßig in seinem Maklerbüro besuchte und der nach Belieben zu seiner Villa kam." [^491] Morris berichtet, dass Lasaters Chauffeur, der ihn oft zur Villa brachte, „ein verurteilter Mörder war, der eine Waffe trug und von dem allgemein bekannt war, dass er nebenbei mit Drogen handelte." [^492] Laut Morris scheint der Präsident der Vereinigten Staaten ein engeres Verhältnis zu einem Drogenhändler gehabt zu haben als die behauptete Beziehung zwischen dem kolumbianischen Präsidenten Ernesto Samper und dem Cali-Kartell.

> „Puh! Bob sagt Dinge über Bill Clinton, die selbst Hillary nicht sagen würde" - P.J. O'Rourke

R. Emmett Tyrell Jr., der Chefredakteur von *The American Spectator*, ist kein Linker wie Morris. Doch sein Bericht *Boy Clinton* enthält viele der gleichen Details, die auch Morris nutzt, um ein Bild von Clinton als einem korrupten Politiker zu zeichnen, der eng mit Drogenhandel und anderen Verbrechen verbunden ist. Im Prolog von *Boy Clinton* wird L. D. Brown, Clintons ehemaliger Leibwächter, zitiert, der die sensationelle Behauptung aufstellt, Clinton sei in die Aktivitäten der Todesschwadrone verwickelt gewesen, um Zeugen zu beseitigen, die über den Drogenhandel in Mena Bescheid wussten.

Insbesondere bezeugt Brown, dass er persönlich am 18. Juni 1986 nach Puerto Vallarta, Mexiko, entsandt wurde, mit einem belgischen leichten automatischen F.A.L. Gewehr. Unter dem Pseudonym Michael Johnson sollte Brown Terry Reed erschossen und getötet haben.

Reed, wie Sie sich vielleicht erinnern, geriet 1994 als Mitautor von *Compromised: Clinton, Bush and the CIA* in das öffentliche Interesse. Die These von *Compromised* ist, dass die CIA „die Präsidentschaft vereinnahmt" hat und dass ihre „verdeckten Operationen wie ein Krebsgeschwür die Organe der Regierung metastasiert haben". Genauer gesagt, behaupten Reed und sein Mitautor, dass sowohl Clinton als auch Bush tief in illegale Aktivitäten in Arkansas verwickelt waren, einschließlich des Drogenhandels.

Brown hat Reed nicht, wie befohlen, getötet. Er und Reed schafften es, zu überleben und zumindest einen Teil ihrer Geschichten zu erzählen, womit sie mehr Glück hatten als andere, die damals und später mit Clinton in Verbindung standen. Betrachten Sie den späten Jerry Parks, der 1992 für die Sicherheit des Clinton-Gore Hauptquartiers zuständig war und im September 1993 in einer gangsterhaften Ermordung erschossen wurde. In einer weiteren bizarren Wendung dieser verdrehten Geschichte hat der Londoner *Sunday Telegraph* auf der Grundlage von exklusiven Informationen, die von Parks' Witwe zur Verfügung gestellt wurden, enthüllt, dass Parks von dem verstorbenen Vincent Foster beauftragt wurde, Bill Clinton zu bespitzeln.

Warum Foster ein belastendes Dossier über Clinton anlegen wollte, kann nur vermutet werden. (Er behauptete, er tue es für Hillary.) Aber in jedem Fall widerlegt es die offizielle Darstellung von Foster als naiven Landjungen, der durch die rücksichtslosen Methoden Washingtons so schockiert war, dass er aus Verzweiflung Selbstmord beging. Diese ohnehin schon unwahrscheinliche Geschichte wird mit jeder neuen Enthüllung noch unwahrscheinlicher.[^493]

### Der Mafia-Präsident

Während die Welt im Großen und Ganzen vor der verstörenden Schlussfolgerung zurückschreckt, dass der Präsident der Vereinigten Staaten durch eine enge Verbindung mit organisierter Kriminalität und Kriminellen belastet ist, deutet das Beweismaterial genau darauf hin. Morris zitiert einen ehemaligen US-Staatsanwalt, der organisierte Verbrecher und deren Interessen verfolgte. Er behauptet, dass Clintons Wahl zum Gouverneur im Jahr 1984 „die Wahl war, bei der die Mafia wirklich in die Politik von Arkansas eintrat, die Jungs von den Hunde- und Pferderennen, die Schmiergeldzahler, die eine Gelegenheit erkannten \... es ging weit über unsere alte Dixie-Mafia hinaus, die im Vergleich dazu wie Kleinkinder wirkten. Es handelte sich um kriminelles Geld von der Ost- und Westküste, das die Möglichkeiten genauso erkannte wie die legalen Konzerne." [^494]

Anscheinend haben auch andere mit ähnlichen Einstellungen weiterhin die Möglichkeiten mit Clinton wahrgenommen. Das *New Yorker* Magazin berichtet in Anlehnung an einen früheren Artikel in *Readers' Digest*, dass „die entscheidenden Verbündeten des Präsidenten in der Gewerkschaftsbewegung ebenfalls Männer sind, die mit dem, was allem Anschein nach einige der schmutzigsten, von der Mafia durchdrungensten Gewerkschaften in Amerika sind, in Verbindung stehen." [^495] Von besonderem Interesse ist Clintons enge Beziehung zu Arthur Coia. Coia, der einer von Clintons „wichtigsten Geldbeschaffern" ist, ist Präsident der Laborers International Union of North America, „einer der korruptesten Gewerkschaften in der Geschichte der Arbeiterbewegung".[^496]

Offensichtlich hat das Justizministerium unter Clinton einen Deal mit Coia geschlossen, den *New Yorker* als „seltsam großzügig" beschreibt, „damit er seinen Job behält, obwohl dasselbe Justizministerium ihn seit langem der organisierten Kriminalität zuordnet".[^497]

Ob Terry Reeds These richtig ist, dass „die CIA die Präsidentschaft übernommen hat", ist ungewiss, aber es gibt offensichtlich eine starke Versuchung für Individuen innerhalb einer verdeckten Organisation, die autorisiert ist, „Verdeckte Operationen" durchzuführen, sich der rationalen Wahl von Professor Hirshleifer zu bedienen und „unrechtmäßige Mittel zur Beschaffung von Ressourcen" zu nutzen.

Angesichts des technologischen Wandels, der die Entscheidungsgewalt von konzentrierter militärischer Macht in der Welt verringert, sollte man vielleicht eine zunehmende Korruption erwarten, wenn nicht sogar eine direkte Übernahme von Regierungen durch organisierte kriminelle Unternehmungen.

Hirshleifer argumentiert, und wir stimmen zu, dass „die Institutionen der politischen Ökonomie niemals so perfekt sein können, dass sie\... die zugrunde liegenden Realitäten der natürlichen Wirtschaft" vollständig verdrängen.[^498] Die Macht verlagert sich in der „natürlichen Wirtschaft". Dies impliziert weitreichende Verschiebungen in den internen Machtverhältnissen der Gesellschaft.

Politische Korruption, so bemerkt Vito Tanzi scharfsinnig, „repräsentiert eine Privatisierung des Staates, bei der seine Macht nicht wie bei der Privatisierung üblich zum Markt verlagert wird, sondern zu Regierungsbeamten und Bürokraten".[^499] In der Tat ist dies unter Clinton beim FBI und anderen Polizeibehörden geschehen. Die „Rechtsstaatlichkeit" wird immer mehr zu dem, was Clinton und seine Kumpane wollen. Bis jetzt scheint es wenig Beweise dafür zu geben, dass Einzelheiten zu diesen korrupten Verbindungen für die Wähler von Bedeutung sein werden, selbst wenn sie von den Massenmedien aufgegriffen und diskutiert würden. Im Gegenteil. Es scheint wenig Sorge über Hinweise zu geben, dass der Präsident der Vereinigten Staaten in Drogenschmuggel, Geldwäsche und Schlimmeres verwickelt sein könnte.

Das erinnert an die späte Befürchtung von Walter Lippmann, dass Wählern die Wahrnehmung fehlte, um das zu durchschauen, was er fiktive Persönlichkeiten nannte. Er war der Ansicht, dass Wähler „mit Schmeicheleien und Lobhudeleien schlecht bedient sind. Und sie werden durch die unterwürfige Heuchelei verraten, die ihnen sagt, dass das, was wahr und was falsch, was recht und was unrecht ist, durch ihre Stimme bestimmt werden kann." [^500]

Lippmann nahm einen „Zusammenbruch der verfassungsmäßigen Ordnung" wahr, der „die Ursache für den abrupten und katastrophalen Niedergang der westlichen Gesellschaft sein könnte. Wir sind in kurzer Zeit weit gefallen. \... Was wir gesehen haben, ist nicht nur Verfall - obwohl ein großer Teil der alten Struktur sich auflöst - sondern etwas, das als historische Katastrophe bezeichnet werden kann." [^501]

Das Problem besteht darin, dass politische Urteile weniger eine Reaktion auf die reale Welt zu sein scheinen als auf eine von der breiten Öffentlichkeit konstruierte Scheinrealität über Phänomene, die außerhalb ihres direkten Wissens liegen.[^502] Aber es ist ein Fehler, sich von den Grenzen dessen leiten zu lassen, was andere sehen. Selbst wenn es Sie kein bisschen interessiert, ob Vincent Foster ermordet wurde und sein Mord von den höchsten Polizeibehörden und verantwortlichen Beamten der US-Regierung, einschließlich sogar des aktuellen Sonderermittlers Kenneth Starr, vertuscht wurde, könnten Sie dennoch Beweise für das breitere Muster von Verbindungen zwischen organisierter Kriminalität und dem Weißen Haus in Betracht ziehen wollen.

Auf lange Sicht macht politische Korruption auf höchsten Ebenen den konventionellen Lobgesang auf die Möglichkeiten der Demokratie zur bewussten Lösung öffentlicher Probleme zunichte. Im Informationszeitalter wird es viel weniger wichtig sein, dass eine Regierung groß und mächtig ist, als dass sie ehrlich ist. Die meisten der Dienstleistungen, die Regierungen historisch gesehen erbracht haben, werden im nächsten Jahrtausend voraussichtlich auf den privaten Markt verlagert. Doch angesichts der weltweiten Beweise ist es fraglich, ob man sich langfristig auf ein korruptes System mit korrupten Anführern für die Sicherheit seiner Familie und Investitionen verlassen kann.

Wie Morris sagt: „Die Clintons sind nicht nur symptomatisch, sondern sie sind bezeichnend für das größere parteiübergreifende System in seiner Sackgasse am Ende des Jahrhunderts".[^503] Vito Tanzi zeigt in seinem Aufsatz über Korruption, dass „die einzige Möglichkeit, Korruption abzuwehren, darin besteht, den Umfang öffentlicher Interventionen erheblich zu reduzieren".[^504] Die Informationsrevolution wird „den Umfang öffentlicher Interventionen" erheblich verringern und auf dieser Grundlage besteht die Hoffnung auf eine Wiederbelebung von Moral und Ehrlichkeit. Eine weitere offensichtliche Folge der Informationsrevolution für Moral ist eine erhöhte Verwundbarkeit, die mit der Möglichkeit des Cyberhandels und virtueller Unternehmen einhergeht, die mit unknackbarer Verschlüsselung kommunizieren können. Interne Diebe innerhalb einer Organisation, selbst einer virtuellen Organisation, werden schwieriger aufzuspüren sein, und es wird so gut wie unmöglich sein, gestohlenes oder heimlich erhaltenes Geld für den Verkauf von Geschäftsgeheimnissen, Patenten oder anderen wertvollen Wirtschaftsgütern wiederzuerlangen.

Kriminalität lohnt sich, und viele finden es attraktiv, rechtschaffene, produktive Tätigkeiten durch gesetzlose, räuberische zu ergänzen. Im Gegensatz zu der üblichen Situation, die in westlichen Gesellschaften während der meisten der letzten zwei Jahrhunderte vorherrschte, sind Kriminelle nicht bloß Außenseiter ohne sozialen Status. Wenn Kriminalität sich auszahlt, neigt man dazu, eine bessere Klasse von Kriminellen zu bekommen, da wenig gesellschaftlicher Makel mit Verbrechen verbunden ist. Die sizilianische Mafia zum Beispiel und viele Drogenhändler, die einheimische Arbeitskräfte zu überhöhten Preisen beschäftigen, genießen in ihrem Heimatland Respekt und Unterstützung.

## DIE MORALISCHE ORDNUNG UND IHRE FEINDE

Alle starken Gesellschaften haben eine starke moralische Grundlage. Jede Studie zur Geschichte der Wirtschaftsentwicklung zeigt die enge Beziehung zwischen moralischen und wirtschaftlichen Faktoren. Länder und Gruppierungen, die eine erfolgreiche Entwicklung erzielen, tun dies teilweise, weil sie eine Ethik besitzen, die die wirtschaftlichen Tugenden von Eigenverantwortung, harter Arbeit, familiärer und sozialer Verantwortung, hohen Sparquoten und Ehrlichkeit fördert. Das gilt auch für soziale Untergruppen. Der Geschäftserfolg von Juden, insbesondere von religiösen Juden, von den Puritanern in Neuengland, von den Quäkern im britischen Geschäft des 18. und 19. Jahrhunderts oder von den Mormonen im modernen Amerika, zeigt die wirtschaftlichen Vorteile, die aus Kulturen mit einem starken moralischen Rahmenwerk resultieren.

Man kann die Quäker als Beispiel nehmen. Die Quäker wurden aus mehreren Gründen geschäftlich erfolgreich, insbesondere als Bankiers. Sie setzten für sich selbst den höchstmöglichen Standard an Vertrauenswürdigkeit. Sie leisteten keine Eide, sahen aber jede geschäftliche Verpflichtung als ebenso bindend an wie einen Eid. „Mein Wort gilt" war für sie ein absolutes Prinzip. Sie glaubten an einen ruhigen Lebensstil, anständig, aber sparsam. Aus religiöser Pflicht vermieden sie es, Geld für die Eitelkeiten dieser Welt auszugeben. Sie mieden Streitigkeiten und hielten Krieg immer für sündig. Sie glaubten, dass der Geschäftsmann die moralische Verpflichtung hat, einen fairen Wert zu geben, und als Händler erwarben sie den Ruf, hohe Qualität zu moderaten Preisen zu bieten. „Caveat emptor" - der Käufer muss aufpassen - war für sie nicht gut genug. In einer Zeit, in der die meisten Händler die Hohe-Preise-Hohe-Gewinne-Theorie des Handels verfolgten, führte die Quäker-Moral sie auf natürliche Weise zu einer Niedriger-Gewinn-Hoher-Umsatz-Politik. Wie Henry Ford später zeigte, kann das potenziell wesentlich profitabler sein. Sie folgten dieser Geschäftspolitik, weil sie glaubten, es sei ihre Pflicht, ihre Kunden nicht zu betrügen, aber es stellte sich heraus, dass es der beste Weg war, ihr Geschäft zu erweitern. Die Quäker erwiesen sich als gute Geschäftspartner, also kamen ihre Kunden wieder; es gab Gewinne auf beiden Seiten. Als eine Gemeinschaft, die viel sparte und ihre Verpflichtungen ehrte, hatten die Quäker Vorteile als Bankiers, und die Mitgliedschaft bei den Quäkern war an sich ein Geschäftsvermögen, das Vertrauen weckte.

Leider können solche Geschäftsvorteile durch den Erfolg, den sie hervorbringen, wieder zunichte gemacht werden. Länder durchlaufen einen Zyklus, der die Grundlage von Adam Fergusons soziologischer Theorie im 18. Jahrhundert bildet - von Armut und harter Arbeit, zu Reichtum, zu Luxus, zu Dekadenz und weiter zum Niedergang. Die alten Römer selbst blickten zurück auf die Tugenden der republikanischen Ära, als das Reich aufgebaut wurde, und beklagten den Luxus und die Faulheit, die sie als Ursache ihres Niedergangs ansahen. Diese Erosion der fleißigen Tugenden durch Wohlstand kann überraschend schnell passieren. Die Deutschen sind immer noch ein fähiges und effizientes Volk, aber sie arbeiten bei weitem nicht mehr so schwer wie in den Zeiten, als sie ihr Land nach der verheerenden Niederlage im Jahr 1945 wieder aufbauten. Innerhalb von zwei Generationen sind sie von langen Arbeitszeiten, fast mit bloßen Händen, unter Bedingungen akuter Armut zu kurzen Arbeitszeiten für die höchsten Löhne und den teuersten Wohlstand der Welt übergegangen. Im Oktober 1995 wurde die Petersburger Erklärung von sechzehn deutschen Arbeitgeberverbänden unterzeichnet. Sie ist ein Katalog gut begründeter Beschwerden, die den Niedergang der Arbeitsmoral in Deutschland widerspiegeln.

> Die Steuerbelastung in Deutschland erreichte 1995 Rekordhöhen, insbesondere aufgrund des Solidaritätszuschlags und der Beiträge zur Pflegeversicherung. Mit einer Gesamtunternehmensbesteuerung von über 60 Prozent liegt Deutschland weit über der vergleichbaren internationalen Ebene von 35 bis 40 Prozent. Gewohnheiten des öffentlichen Sektors wie geregelte Beförderungen, Arbeitsplätze auf Lebenszeit und höhere Rentenzahlungen müssen durch die Regeln des freien Marktes mit leistungsgerechter Beförderung und Entlohnung ersetzt werden. Da Deutschland die höchsten Arbeitskosten der Welt hat, muss die Lohnpolitik zum Abbau der Arbeitslosigkeit beitragen, indem sie die Kosten für die Unternehmen senkt\...Lohnerhöhungen sollten an der Wettbewerbsfähigkeit und Produktivität gemessen werden\.... Das Verhalten der Gewerkschaften muss sich ändern. Das alljährliche Ritual von Kampagnen, Forderungen, Arbeitnehmermobilisierung, Drohungen und Warnstreiks ist schädlich.

Diese Besorgnis, dass die Deutschen, insbesondere die jungen Leute und die Erben des Wohlstands, die Gewohnheit zu arbeiten verloren haben, wird auch von Bundeskanzler Kohl geteilt.

Der bestehende Arbeitsvertrag von Volkswagen sieht den höchsten Lohn für Automobilarbeiter weltweit vor, zu dem noch Sozialabgaben hinzukommen, im Austausch für eine 28-Stunden-Woche - vier Tage mit jeweils sieben Stunden. Das Nachkriegsdeutschland ist nun ein großer Exporteur von Arbeitsplätzen. Im 19. Jahrhundert galten die Briten als die effizienteste Industrienation - einen Ruf, den sie einhundert Jahre später sicherlich verloren hatten. Der Zyklus des Wohlstands untergräbt zweifellos die Tugenden von harter Arbeit und bescheidenen Erwartungen, die in den frühen Phasen der erfolgreichen industriellen Entwicklung existieren. Nationen können ihre ursprünglichen Tugenden nicht bewahren, so wie Individuen durch zu leichten Erfolg gierig und faul werden können.

Globale Investitionen belohnen zweifelsohne diese fleißigen Tugenden und bestrafen diejenigen, die gierig und faul werden, so wie es sich gehört. Tatsächlich könnte man sagen, dass eine solide Investition sowohl auf einer moralischen als auch auf einer rein finanziellen Beurteilung basieren muss. Der Engländer im achtzehnten Jahrhundert, der das Kapital einer Quäker-Bank zeichnete, hatte gute Aussichten auf Erfolg. Im neunzehnten Jahrhundert investierten die Quäker in Schokoladengeschäfte, da sie annahmen, dass Kakao gesünder ist als Alkohol. Das ist er wahrscheinlich auch. Dennoch wäre eine Investition in Fry's oder Cadbury's sicherlich eine gute Investition gewesen. Investoren sollten darauf bedacht sein, Zeiten der Dekadenz zu vermeiden. Selbst wenn Deutschland eine starke Position auf dem europäischen Markt und hohe industrielle Fähigkeiten beibehält, haben hohe Arbeitskosten und kurze Arbeitszeiten das zukünftige Potenzial Deutschlands bereits verringert.

Soziale Moral und wirtschaftlicher Erfolg sind untrennbar miteinander verbunden. Aber welche Faktoren tragen dazu bei, die soziale Moral aufrechtzuerhalten, und welche neigen dazu, sie zu untergraben? Arnold Toynbee, der bedeutende Philosophiehistoriker der ersten Hälfte des zwanzigsten Jahrhunderts, formulierte die Theorie der Herausforderung und der Antwort. Gesellschaften werden durch Herausforderungen belebt und entwickeln Tugenden, von denen sie nicht einmal wussten, dass sie sie besitzen.

Es gibt immer eine menschliche Anerkennung, dass sich schwere Zeiten entwickeln können, und diese normalerweise gesündere Reaktionen hervorrufen als Perioden des Wohlstands. In unserem individuellen Leben versuchen wir alle, es uns bequem zu machen, wir hoffen, in einem Haus zu leben, das uns gefällt, einen Arbeitsplatz zu haben, der uns gefällt, genug Geld auf der Bank zu haben und so weiter. Der Kampf, diese Ziele zu erreichen, lohnt sich. Wir lernen in der Schule, wir bilden uns weiter, wir arbeiten hart in unserem Unternehmen oder Beruf, um diese Ziele zu erreichen.

Für allzu viele Menschen erweist sich die Erreichung dieser Ziele als eine Art Falle. Der Kampf ist besser als die Errungenschaft. Der große Schweizer Psychologe Carl Jung hatte Anfang dieses Jahrhunderts einen amerikanischen Geschäftsmann als Patienten. Der Geschäftsmann hatte genau diese Ambitionen als junger Mann. Er hatte daran gearbeitet, sein eigenes Geschäft aufzubauen und genug Geld zu verdienen, um sich mit vierzig zur Ruhe zu setzen. Er heiratete eine junge und attraktive Frau, kaufte ein schönes Haus, hatte eine junge Familie, sein Geschäft war sehr erfolgreich und mit vierzig Jahren konnte er tatsächlich verkaufen und sich zur Ruhe setzen. Ein reicher und unabhängiger Mann mit scheinbar keinen Sorgen. Anfangs genoss er seine Freiheit, konnte Dinge tun, die er sich schon lange versprochen hatte. Er nahm seine Familie mit nach Europa. Sie besuchten Kunstgalerien und so weiter. Allmählich begannen diese Interessen und sein Freiheitsgefühl selbst zu verblassen. Er begann die Zeit, in der er nicht frei hatte, in der er rund um die Uhr für sein Geschäft arbeitete und all die üblichen Geschäftssorgen hatte, als die glücklichste Zeit seines Lebens zu betrachten. Er verfiel in eine Depression, aufgrund derer seine Frau ihn zu Jung als Patienten brachte. Jung diagnostizierte ihn im Grunde genommen damit, dass er keinen Ausweg für seine kreative Energie hatte, was auf ihn zurückfiel und ihn zerstörte. Die Diagnose mag korrekt gewesen sein, führte aber nicht zur Heilung. Der Geschäftsmann erholte sich nie von seinem Nervenzusammenbruch.

Für den Menschen ist es der Kampf an sich, der zählt, und nicht so sehr die Errungenschaft; wir sind für das Handeln geschaffen und der Erfolg kann sich als große Enttäuschung erweisen. Die Ambitionen, was auch immer sie sein mögen, setzen den Kampf in Gang, aber der Kampf ist angenehmer als das eigentliche Ergebnis, selbst wenn das Ziel in vollem Umfang erreicht ist. Und natürlich können die Ziele, für die meisten Menschen, nur teilweise erreicht werden. Die meisten von uns haben nicht so viel Geld, wie wir es gern hätten, und wir leben nicht in unserem Traumhaus. Wir müssen uns mit weniger zufriedengeben.

Dieses Gefühl, dass Tugend dynamisch ist, dass sie sich eher in der Anstrengung als im Ergebnis zeigt, entwickelte sich im 19. Jahrhundert stark und auf verschiedene Weisen. Es gibt ein bekanntes Gedicht von Arthur Hugh Clough, das vielen Menschen in dem Kampf um Leben und Tod des Zweiten Weltkriegs Trost brachte. Es ist bemerkenswert, dass die Suizidraten in den kriegführenden Ländern im Zweiten Weltkrieg gefallen sind; selbst der Kampf des Krieges kann besser sein als die Depression der Inaktivität.

> *Sage nicht, der Kampf sei vergebens,\
> die Arbeit und die Wunden seien umsonst,\
> der Feind ermattet und versagt nicht,\
> und wie die Dinge waren, so bleiben sie.*
>
> *Wenn Hoffnungen getäuscht wurden, könnten Ängste Lügner sein;\
> Es könnte sein, dass in jenem verborgenen Rauch,\
> deine Kameraden sogar jetzt die Fliehenden jagen,\
> und, wäre es nicht für dich, das Feld besitzen.*
>
> *Denn während die müden Wellen, vergeblich brechend,\
> scheinbar hier keinen schmerzhaften Zentimeter gewinnen,\
> kommt weit zurück, durch Bäche und Einlassstellen,\
> schweigend, das Hauptwasser hereinflutend.*
>
> *Und nicht nur durch die Fenster im Osten,\
> wenn der Tag anbricht, kommt das Licht,\
> vorne steigt die Sonne langsam, oh so langsam,\
> aber schau nach Westen, dort strahlt das Land hell.*

Dieser aktive Wettbewerb spricht immer noch das moderne Empfinden an. Tatsächlich ist es die Art und Weise, wie viele moderne Männer und Frauen ihr Leben führen, in einem ständigen Kampf, um die Möglichkeiten einer potenziell feindlichen Umgebung zu ergreifen. Wir alle leben in einer Wettbewerbswelt und die meisten von uns möchten sich nicht davon distanzieren. Natürlich gibt es auch das kontemplative spirituelle Temperament, aber es ist ziemlich selten.

Eine ähnliche Wahrnehmung dieser dynamischen Moral des neunzehnten Jahrhunderts wurde von William James, dem größten amerikanischen Philosophen, in einer Rede vor dem Philosophischen Club von Yale im Jahr 1891 entwickelt:

> Der tiefste Unterschied, praktisch gesehen, im moralischen Leben des Menschen ist der Unterschied zwischen der sorglosen und der anstrengenden Stimmung. Wenn wir uns in einer sorglosen Stimmung befinden, ist das Vermeiden gegenwärtiger Übel unser vorherrschendes Anliegen. Die anstrengende Stimmung hingegen macht uns gegenüber gegenwärtigen Übeln völlig gleichgültig, solange nur das größere Ideal erreicht wird. Die Fähigkeit zur anstrengenden Stimmung liegt wahrscheinlich in jedem Menschen schlummernd, doch bei manchem fällt es schwerer als bei anderen, sie zu wecken. Sie benötigt die wilderen Leidenschaften, die großen Ängste, Liebe und Empörungen; oder den tiefgreifenden Appell einer der höheren Treueschwüre, wie Gerechtigkeit, Wahrheit und Freiheit. Ein starker Kontrast ist ein Erfordernis ihres Sichtfelds; eine Welt, in der alle Berge eingeebnet und alle Täler erhöht werden, ist kein für sie angemessener Wohnort. Deswegen könnte diese Stimmung bei einem einsamen Denker für immer schlummern, ohne jemals zu erwachen. Seine verschiedenen Ideale, von denen er weiß, dass sie nur seine eigenen Vorlieben sind, liegen fast vom selben Wert: Er kann mit ihnen nach Belieben umgehen. Aus diesem Grund ist in einer rein menschlichen Welt ohne Gott der Appell an unsere moralische Energie nicht vollkommen stimulierend. Das Leben ist sicherlich auch in einer solchen Welt eine echte ethische Symphonie; aber sie wird nur innerhalb von ein paar schwachen Oktaven gespielt, und die unendliche Skala der Werte bleibt verschlossen.

William James vertrat die Ansicht, dass die dynamische Moral, die darin besteht, eher zu tun als zu sein, eher zu handeln als zu unterlassen, auch auf den religiösen Bereich ausgedehnt werden kann. Eine starke Entwicklung der Wettbewerbs- und Überlebensmoral findet sich auch in den Werken von Adam Smith (1776), Thomas Malthus (1798) und Charles Darwin (1859). Da dies die dominierende Morallehre der heutigen Weltwirtschaftsordnung ist, bedarf deren zentrales Thema einer sorgfältigen Betrachtung.

Die dominierende Idee des Darwinismus ist, dass Spezies durch Anpassung an ihre Umgebung überleben und dieser Prozess der natürlichen Selektion die Merkmale der Arten formt. Bei Tieren ist dieser Prozess das Ergebnis von zufälligen Mutationen, die, wie wir heute wissen, zu einem genetischen Prozess gehören, über den Darwin selbst nur spekulieren konnte. Das Überleben menschlicher Gesellschaften hängt jedoch von kulturellen Entscheidungen ab, die auf menschlicher Intelligenz basieren. Kultur verändert die menschliche Gesellschaft, so wie Gene andere Arten verändern. Veränderungen können daher viel schneller in unseren Gesellschaften stattfinden. Es muss nicht über viele Generationen hinweg arbeiten, wie es bei zufälligen genetischen Mutationen der Fall ist. Anstelle der natürlichen Selektion bei Tieren haben Menschen die kulturelle Selektion entwickelt, wobei einige Kulturen zu bestimmten Zeiten der Menschheitsgeschichte neue Technologien entwickelten, die ihnen einen entscheidenden Vorteil in der Schaffung von Reichtum oder Macht verliehen. Der kulturelle Vorsprung der neuen Technologien, wie ihn der eisenzeitliche Mensch gegenüber dem bronzezeitlichen oder der elektronische Mensch gegenüber dem mechanischen Menschen hatte, ist entscheidend. Adam Smith mag nicht der erste wirtschaftswissenschaftliche Schriftsteller gewesen sein, der das Wohlergehen von Nationen auf das Handeln von Einzelpersonen reduziert hat, aber er hat es am prägnantesten und mit der größten Autorität ausgedrückt:

> Jeder Einzelne ist ständig bemüht, die vorteilhafteste Verwendung für das Kapital zu finden, über das er verfügen kann. Es ist tatsächlich sein eigener Vorteil, nicht der der Gesellschaft, den er im Blick hat. Aber die Untersuchung seines eigenen Vorteils führt ihn natürlich, oder eher zwangsläufig, dazu, jene Tätigkeit vorzuziehen, die für die Gesellschaft am vorteilhaftesten ist.

Thomas Malthus, der Begründer der Bevölkerungsstudien, erkannte, dass das Argument von Adam Smith nicht nur auf die Entwicklung der Wirtschaft von Nationen angewendet werden konnte, sondern auch auf das Überleben der menschlichen Bevölkerungen. Er ist bekannt für seine These, dass „die Bevölkerung, wenn sie unkontrolliert bleibt, in einem geometrischen Verhältnis zunimmt. Die Lebensgrundlagen nehmen jedoch nur in einem linearen Verhältnis zu. Wer sich ein wenig mit Zahlen auskennt, wird die Unermesslichkeit der ersten Macht im Vergleich zur zweiten erkennen.\"

Malthus hatte sogar lange vor Darwin erkannt, dass das gleiche Prinzip in der gesamten Natur Anwendung findet:

> Durch die Tier- und Pflanzenreiche hat die Natur das Leben mit großzügiger Hand weit und breit verstreut. Sie war dagegen vergleichsweise sparsam mit dem Raum und der Nahrung, die notwendig sind, um sie zu pflegen. Die Lebenskeime, die in diesem Fleckchen Erde enthalten sind, könnten mit ausreichend Nahrung und genügend Platz zum Ausbreiten in ein paar tausend Jahren Millionen von Welten füllen. Die Notwendigkeit, dieses zwingende und allgegenwärtige Gesetz der Natur, hält sie innerhalb der vorgeschriebenen Grenzen.

Die Art und Weise, wie sich die Welt entwickelt, wurde schon gegen Ende des achtzehnten Jahrhunderts, zur Zeit von Adam Smith und Malthus, als dynamisch verstanden - was sie tatsächlich immer schon war. Die Menschheit, als eine Spezies unter vielen, ist gezwungen, um Ressourcen zu konkurrieren. Diese Konkurrenz wird durch das Missverhältnis zwischen ihrer unbegrenzten Fortpflanzungsfähigkeit und ihrer begrenzten Kapazität, Nahrung zu produzieren, verursacht. Das Überleben menschlicher Gesellschaften, wie auch das von Tierarten, hängt von einer erfolgreichen Anpassung an die Umwelt ab. Eine dynamische Moral beschäftigt sich daher mit der Überwindung der Anpassungsprobleme. Dies gelingt am besten Individuen, die ihre Handlungen den Möglichkeiten der Umwelt anpassen und daher die in der Gesellschaft verfügbaren Ressourcen bestmöglich nutzen.

Malthus erkannte bereits, dass die Ideen von Adam Smith die Welt verändert hatten, und er schrieb, dass sein neuer Ansatz zum Thema Bevölkerung nicht neu war: „Die Prinzipien, auf denen sie basieren, wurden zum Teil von Hume und zum Teil von Dr. Adam Smith erklärt." Er sah auch, dass dieser ständige Wettkampf ums Überleben eine moralische, nicht nur eine praktische Angelegenheit war. Die letzte Passage des „Essays" von 1798 lautet:

> Das Böse existiert in der Welt, nicht um Verzweiflung zu erzeugen, sondern um Tätigkeit zu fördern. Wir sollen es nicht geduldig hinnehmen, sondern uns bemühen, es zu vermeiden. Es ist nicht nur das Interesse, sondern die Pflicht eines jeden Einzelnen, sich nach Kräften zu bemühen, das Böse von sich selbst und von einem möglichst großen Kreis zu entfernen. Je mehr er sich in dieser Pflicht übt, je weiser er seine Bemühungen lenkt und je erfolgreicher diese Bemühungen sind, desto mehr wird er wahrscheinlich seinen eigenen Geist verbessern und erhöhen, und desto vollständiger scheint er den Willen seines Schöpfers zu erfüllen.

Vielleicht kann man Darwins Sinn für die Wichtigkeit dieser Argumente mit seiner Zusammenfassung der Inhalte von Kapitel 3 aus seinem bahnbrechenden Buch „Über die Entstehung der Arten", das erstmals 1859 veröffentlicht wurde, veranschaulichen. Er nannte dieses entscheidende Kapitel *Der Kampf ums Dasein*. Die Überschriften lauten: „Betrifft die natürliche Auswahl - Der Begriff im weitesten Sinne verwendet - Geometrische Vermehrungsrate - Schnelle Vermehrung von eingebürgerten Tieren und Pflanzen - Art der Vermehrungskontrolle - Wettbewerb ist universell - Auswirkungen des Klimas - Schutz vor der Anzahl der Individuen - Komplexe Beziehungen zwischen allen Tieren und Pflanzen in der gesamten Natur - Der Überlebenskampf ist am härtesten zwischen Individuen und Varianten der gleichen Art; oft auch zwischen Arten der gleichen Gattung - Die Beziehung von Organismus zu Organismus ist die wichtigste aller Beziehungen."

Seit 1776 ist es offensichtlich, dass der beste Weg zur Optimierung des Wohlstands der Nationen darin besteht, Einzelpersonen zu erlauben, ihre eigene Kapitalrendite unter Bedingungen des freien Wettbewerbs zu optimieren. Seit 1798 ist es offensichtlich, dass das relative Überleben von Populationen von ausreichendem wirtschaftlichen und politischen Erfolg der Gesellschaften abhängt, um sich selbst ernähren, sich vor ansteckenden Krankheiten schützen und die Bevölkerungen in Kriegen schützen zu können. Seit 1859 ist es offensichtlich, dass das gesamte Drama des Lebens, sei es im menschlichen, tierischen oder pflanzlichen Reich, aus einem fortwährenden Kampf ums Überleben besteht, bei dem die Arten oder Kulturen, die einander am nächsten sind, die größten Rivalen sein können. Dieser Kampf erfordert eine dynamische Moral, die aktiv das Böse abwehrt und nicht nur darauf reagiert, wenn es geschieht.

Diese Ideen waren so machtvoll, dass es unmöglich war, über die Natur der Menschheit oder die Probleme der Moral seit der Zeit, in der sie entwickelt wurden, nachzudenken, ohne auf sie zu reagieren. Karl Marx glaubte genauso an den Kampf ums Überleben wie Charles Darwin, aber er sah es als einen Krieg zwischen den Sozialklassen an, die selbst durch ökonomische Kräfte geformt wurden. Adolf Hitler glaubte an den Kampf ums Überleben und sah seine eigene politische Karriere fast ausschließlich in diesen Begriffen. Aber er glaubte, dass der Kampf einer zwischen verschiedenen Rassen war. Marx, Lenin, Stalin, Mao und Hitler können alle als Sozialdarwinisten bezeichnet werden, insofern sie den Überlebenskampf, „Mein Kampf" wie Hitler es nannte, als die zentrale politische Frage sahen. Die Marxisten sahen soziale Klassen, als wären sie separate Spezies; die Nazis sahen Rassen im gleichen Licht.

Dies stellt jedoch keine dynamische Moral dar, wie Malthus sie sich vorstellte, sondern eine dynamische Unmoral. Sowohl der Marxismus als auch der Nationalsozialismus wollten das gleiche Problem lösen, das Problem des Kampfes ums Überleben, jedoch durch die Zerstörung des Wettbewerbs. Sie griffen fremde Gebiete an und stachelten Konflikte zwischen verschiedenen Klassen, die um soziale Macht konkurrierten, oder verschiedenen Rassen an, die entweder als wirtschaftliche Ausbeuter (der normalerweise gegen Juden erhobene Vorwurf von Antisemiten) oder als gefährliche Unterschicht (die Angst der Weißen vor den Schwarzen) angesehen wurden. Der Zweite Weltkrieg war ein gescheiterter Versuch Adolf Hitlers, dem deutschen Volk einen Überlebensvorteil zu verschaffen, indem er potenzielle Konkurrenten, insbesondere Slawen und Juden, vernichtete. Interessanterweise erwies sich die Kriegsniederlage für Deutschland als vorteilhafter, als es der Sieg der Nazis jemals hätte sein können.

Die Alternative zu destruktiver „Interferenz-Konkurrenz" ist kollaborative Konkurrenz, und kollaborative Konkurrenz ist die zentrale Idee von Adam Smith, aber auch von Malthus und William James. Das Urmodell des destruktiven Wettbewerbs ist der Eroberer. Er zerstört seine Konkurrenten, um ihre Vermögenswerte zu ergreifen, was auch die Übernahme ihrer Länder einschließen und die Versklavung ihrer Völker beinhalten kann. Das Modell des kollaborativen Wettbewerbs ist der Kaufmann. Es liegt im Interesse des Kaufmanns, dass der Kunde mit der Transaktion zufrieden sein sollte, denn nur ein zufriedener Kunde kommt für mehr Handel zurück. Es liegt auch im Interesse des Kaufmanns, dass der Kunde wohlhabend ist, denn ein wohlhabender Kunde hat das Geld, um weiter einzukaufen. Eroberung impliziert die Zerstörung der anderen Partei; Handel impliziert die Zufriedenheit der anderen Partei. Da die moderne Technologie die Eroberung zu einer außerordentlich gefährlichen Politik gemacht hat, ist der Handel zum einzigen rationalen Ansatz für die Lösung der Überlebensprobleme geworden.

Diese Interdependenz wird durch eine weitere zentrale Idee von Adam Smith verstärkt, die nicht neu für ihn war, nämlich die Spezialisierung der Funktionen. *Der Wohlstand der Nationen* beginnt mit einem berühmten Abschnitt, in dem Adam Smith bemerkt, dass „die größte Verbesserung der Produktivkräfte der Arbeit und der größte Teil der Gewandtheit, der Geschicklichkeit und des Urteilsvermögens, mit denen sie überall gerichtet oder angewandt wird, die Auswirkungen der Arbeitsteilung gewesen zu sein scheinen." Er weist darauf hin, dass „das wichtige Geschäft der Herstellung eines Stecknadelkopfes auf diese Weise in etwa achtzehn verschiedene Vorgänge unterteilt ist, die in einigen Fabriken alle von verschiedenen Personen ausgeführt werden." Je vollständiger die Spezialisierung der Funktionen, desto wahrscheinlicher ist die Effizienz der Herstellung, aber offensichtlich ist eine solche Wirtschaft stark voneinander abhängig. Wenn sie erfolgreich sein soll, muss sie kollaborativ sein.

Eine erfolgreiche soziale Moral muss daher bestimmte Merkmale aufweisen. Sie muss stark sein - eine schwache Moral ist verletzlich und ineffektiv. Sie muss zum Überlebenskampf beitragen, aber auf eine kollaborative Art und Weise, nicht mörderisch. Hitler hatte eine starke Morallehre des Überlebens, doch ihre destruktive Qualität hätte seine eigene Gesellschaft beinahe zerstört. Sie muss dynamisch sein, um den dynamischen Veränderungen der modernen Technologie und tatsächlich aller modernen sozialen Systeme gerecht zu werden. Sie muss wirtschaftlich effizient sein. Die Mischung aus egalitären und autoritären Ideen im leninistischen System hat einfach nicht funktioniert. Doch dies sind nicht alle Merkmale, die man von einer solchen sozialen Moralität erwarten könnte. Sie hat den breiteren Zweck, die Gesellschaft zu einem guten Ort zum Leben zu machen und die Menschen zusammenzubinden. Auch Moralvorstellungen müssen sich anpassen und überleben; eine brüchige Moral wird vielleicht von unserer Generation akzeptiert, nur um in der nächsten abgelehnt zu werden. Eine traditionelle soziale Moral mag zu starr sein, um sich auf die aufeinanderfolgenden Veränderungen in der Sozialstruktur einzustellen. Andererseits ist ein rein relativistisches System überhaupt keine Moral; es gibt keine klaren Anweisungen, wie man sich verhalten soll.

Wir können zunächst einmal die gesamte soziale Moral in einen Kontext stellen. Eine starke Gemeinschaft, selbst eine virtuelle Gemeinschaft, hängt davon ab, dass die Moral weitgehend akzeptiert wird. Die erfolgreichsten Epochen in der Geschichte der Gesellschaften sind in der Regel solche, in denen die kollektive Moral vollständig geteilt wird. Eine solche Moral erfüllt nicht nur spezifische Funktionen wie die Reduzierung von Verbrechen und die Unterstützung von Familien- und Sozialstrukturen, sondern gibt den Bürgern auch ein Gefühl von Ziel und Richtung. Historisch gesehen scheint ein Konsens über Moral davon abhängig zu sein, dass es eine dominierende Religion gibt, ob es nun die Staatsreligion der frühen Überlebensgemeinschaften für ein zerstreutes Volk; die islamische Religion mit ihren sozialen Regeln; der Katholizismus des Mittelalters; oder der Protestantismus des frühen Neuenglands ist. Die drei Ideen eines Volkes, einer Moral und einer Religion hängen voneinander ab, und jede tendiert dazu, die anderen zu verstärken.

In einer solchen moralischen Gesellschaft ist es dem einzelnen Bürger möglich, persönliche Ziele innerhalb eines Rahmens sozialer Unterstützung zu verwirklichen. Zugegeben, die moralischen Gesetze können etwas willkürlich sein, oder zumindest für Außenstehende so erscheinen. Der orthodoxe Jude verliert die Freiheit, Schweinefleisch oder Schalentiere zu essen oder am Sabbat zu arbeiten. Der treue Katholik könnte die Freiheit verlieren, künstliche Verhütungsmittel zu verwenden, geschweige denn, eine Abtreibung vorzunehmen. Der Moslem könnte die Freiheit verlieren, Alkohol zu trinken. Der fromme Konfuzianer könnte eine unangenehm lange Trauerzeit für seinen verehrten Vater haben - selbst Konfuzius warnte, dass Trauerrituale übertrieben werden könnten. Doch die Anhänger jedes dieser Glaubenssysteme betrachten diese Beobachtungen als geringen Preis für ein gemeinsames und kohärentes Verständnis der Weltordnung, in der der Einzelne einen festen Platz hat. Ein orthodoxer Jude könnte gut argumentieren, dass die Einhaltung des Sabbats ein kleiner Preis für die Vorteile des Gesetzes oder die Stärke der jüdischen Familie ist. Eine gemeinsame Moral in einer toleranten Gesellschaft war das Ideal von John Locke und den frühen Philosophen der Freiheit. Sie glaubten keineswegs, dass eine Gesellschaft jeglicher Art ohne Regeln existieren kann, aber sie meinten, dass die Regeln der besten Vernunft unterliegen sollten und dass Menschen nur zur Annahme der wichtigsten Regeln gezwungen werden sollten. Sie erkannten, dass Zwang in der sozialen Moral unvermeidlich ist, insbesondere beim Schutz von Leben oder von Eigentum, weil sie der Ansicht waren, dass keine Gesellschaft überleben kann, wenn es keine Sicherheit gibt. Sie zeigten eine fast absolute Toleranz gegenüber Variationen bei persönlichen Entscheidungen, die das Wohl anderer nicht beeinträchtigen. Der Konfuzianer, der seinen Vater vierzig Tage lang betrauert, könnte neben dem Juden wohnen, der den Sabbat ehrt, ohne den anderen zu stören oder ihn zwingen zu wollen, seine eigenen religiösen Praktiken zu befolgen.

Aus dieser kombinierten Doktrin der sozialen Moral in wesentlichen Angelegenheiten und der Toleranz in persönlichen Entscheidungen entsteht tatsächlich ein moralischer Grundsatz, der allen Bürgern auferlegt werden muss, und eine freiwillige Ethik, die die Bürger als Einzelpersonen oder als Mitglieder von Untergruppen in der Gesellschaft akzeptieren. Wenn ein Benediktinermönch Gelübde der Armut, der Keuschheit und des Gehorsams ablegt, tut er dies als Mitglied einer solchen Untergruppe. Er fordert nicht alle Katholiken, geschweige denn alle seine Mitbürger, auf, die gleichen Gelübde abzulegen oder dieselben Regeln zu befolgen. Er wird den Befehlen seines Abtes gehorchen, aber er erwartet nicht, dass jemand außerhalb seines Klosters ihnen Beachtung schenkt. Die Einhaltung dieser optionalen Teile der sozialen Moral muss nicht universell sein, aber die Kernmoral muss geteilt werden, und Menschen, die die Kernmoral nicht akzeptieren, schaden sowohl der Gesellschaft als auch sich selbst. Im extremen Beispiel bietet eine Gesellschaft, die von Räubern überrannt wird, die nicht zögern zu morden, so wie es in großen Teilen Europas nach dem Fall des Römischen Reiches der Fall war, niemandem ein zufriedenstellendes Leben, nicht einmal den Räubern selbst; sie sind immer besonders bedroht durch andere Mörder. Dies gilt gleichermaßen für einige innenstädtische Gebiete der Vereinigten Staaten heute. Anarchie ist nicht die ideale Gesellschaft, denn ohne die Durchsetzung des Rechts gibt es keine menschliche Sicherheit.

Wenn man die Kräfte betrachtet, die der Moralethik der Gesellschaft feindselig gegenüberstehen, muss man diese Kernmoral in Erwägung ziehen, die in den meisten modernen religiösen Glaubenssystemen recht ähnlich ist. Zumindest zwei der Zehn Gebote des Alten Testaments für Christen, oder der Thora für Juden, können als universell für alles angesehen werden, was man als eine Religion anerkennen könnte: „Du sollst nicht morden" und „Du sollst nicht stehlen". Man kann sogar noch weiter gehen. Fast alle ernsthaften Agnostiker würden sowohl Mord als auch Diebstahl -- die ultimative Bedrohung des Lebens und die ultimative Bedrohung des Eigentums - als verboten ansehen und würden akzeptieren, dass die Gesellschaft das Recht hat, Menschen zu bestrafen, die morden oder rauben. Sie könnten sich über die angemessene Bestrafung für ein bestimmtes Verbrechen uneinig sein, aber nicht über das Recht der Gesellschaft, als solche zu bestrafen.

Der ursprüngliche Ausdruck von John Locke trifft es genau. Jeder hat das Recht auf „Leben, Freiheit und Eigentum". 1776 fügte Thomas Jefferson einen weiteren Ausdruck von John Locke hinzu: „das Streben nach Glück". Das ergibt einen sehr schönen Ausdruck, und ein sehr nobles Bestreben, aber „Leben, Freiheit und Eigentum" sind konkreter als „Leben, Freiheit und das Streben nach Glück". Die Gesellschaft hängt absolut vom Recht auf Leben und dem Recht auf Eigentum ab. Die Praxis der Geschichte zeigt, dass diese Rechte nur dann geschützt werden können, wenn Freiheit herrscht. Ist der Staat allmächtig, wird er zum großen Feind des Lebens, wie in Angriffskriegen, und des individuellen Eigentums, indem er einen übermäßigen Anteil des nationalen Vermögens für seine eigenen, oft unerwünschten und stets verschwenderischen Zwecke nimmt.

Die Kernmoral ist jedoch in den am weitesten fortgeschrittenen Nationen unter Beschuss, teils durch die Kräfte der Modernität, die diesen Nationen ihren technischen Vorsprung geben. Die Vereinigten Staaten sind die führende technologische Macht der Welt. Viele Menschen, einschließlich der meisten Amerikaner, hätten die Vereinigten Staaten zu jeder Zeit bis in die frühen 1960er Jahre als moralisches Vorbild für den Rest der Welt betrachtet. Heute wird diese Ansicht selten geäußert, selbst von Amerikanern, die stolz auf ihr Land sind. Man konnte nicht, wie es die Welt tat, dem Prozess gegen O. J. Simpson zuhören und die Vereinigten Staaten als die einfache tugendhafte Republik betrachten, die sie anfangs waren.

Wenn man auf die Kennzeichen des alten Amerika zurückblickt, spiegeln sie die Bedürfnisse einer Frontier-Gesellschaft wider, die die Einstellungen ihrer Bürger sogar in den Großstädten prägte. Grenzgebiete sind demokratische Orte. Die Menschen fühlen sich als gleichberechtigt, und die frühen Amerikaner warfen die Klassenhierarchien Europas ab. Selbst Leibeigene, die als Gefangene aus England geschickt wurden, etablierten sich als unabhängige Handwerker, Bauern oder freie Arbeiter, sobald ihre Leibeigenschaft vorbei war. Die Löhne waren höher als in Europa, und die Kosten für lebensnotwendige Güter waren gering, obwohl importierte Waren teuer waren. Im Frontier selbst waren die Menschen sehr voneinander abhängig, aber das Leben, wenn auch hart, war gemessen an europäischen Standards gut. Einwanderer mussten vielleicht als Niedriglohnempfänger in den Slums von Boston und New York beginnen, entkamen diesen jedoch meist ziemlich schnell, und Generation für Generation fand Wohlstand. Nach dem Bürgerkrieg sahen sich die Schwarzen als eine weitere Einwanderergruppe und viele von ihnen teilten die amerikanischen Werte und Ziele. Aus diesen entwickelte sich die schwarze Mittelschicht.

Dieser Anspruch, gestärkt durch die tatsächliche Erfahrung der Grenzgebiete und durch den Einfluss der Kirchen, sowohl protestantischer als auch katholischer, prägte den Patriotismus der Amerikaner. Sie glaubten, in Gottes eigenem Land zu leben, einer Vorstellung, die einzigartig von demokratischen Idealen und christlichem Glauben geleitet war und die erste und erfolgreichste der weltweiten Demokratien darstellte. Das Bild ist uns sehr vertraut; es ist in dem Bild verkörpert, das wir alle, oder fast alle, von Abraham Lincoln haben, obwohl man noch immer einige Amerikaner im Süden finden kann, die Lincoln als den Mann sehen, der die Schrecken des ersten modernen Krieges entfesselte, um freie Staaten daran zu hindern, eine Union zu verlassen, der sie nicht länger vertrauten.

Nichtsdestotrotz bleibt das Bild von Lincoln, zerklüftet, einfach, ehrlich und eloquent, immer noch das oberste amerikanische Bild, und es ist im Wesentlichen ein moralisches. Viele Amerikaner spüren immer noch den ursprünglichen, lebhaften Kontrast zwischen der demokratischen Energie des neuen Landes und den müden Hierarchien Europas. Dieses Ideal einer im Wesentlichen dynamischen Leistungsgesellschaft ist für den Ausländer schwer zu erkennen, wenn er das heutige Los Angeles, New York, Houston oder Washington betrachtet, obwohl seine Spuren, und mehr als nur Spuren, immer noch in den großen Vorstadtgebieten oder in ländlichen Gegenden zu finden sind. Die amerikanische puritanische Ethik, mit all ihrer historischen Bedeutung, überlebt am besten nördlich der Schneegrenze, aber die unternehmerische Dynamik ist weiter verbreitet.

Amerikaner würden auf den Verfall der Großstädte hinweisen, die zu Brutstätten für Kriminalität, insbesondere das Drogengeschäft, geworden sind, als das schlimmste Symptom für den Rückgang eines gemeinschaftlichen Moralgefühls. Die meisten Amerikaner erkennen auch, dass es einen Zusammenstoß mehrerer unterschiedlicher moralischer Kulturen gibt, die alle in ihren Ansprüchen und ihrer Autorität konkurrieren. Die „politisch korrekte" Kultur lehnt viele, aber nicht alle moralischen Grundsätze ab, auf denen die alte Kultur beruhte. Sie betont aggressiv die Rolle und die Rechte von Gruppen, die als historisch von einer dominanten weißen männlichen Kultur ausgebeutet angesehen werden und lehnt diese Kultur ab, obwohl sie die Gründungskultur der Vereinigten Staaten ist.

Die dominante männliche Kultur der ersten Hälfte des 20. Jahrhunderts konzentrierte sich auf das Überleben der Kernfamilie. Historisch gesehen verschaffte dies dem Ehemann und Vater zumindest nominell Vorherrschaft im Haus, obwohl das Haus in der Praxis oft von der Ehefrau und Mutter geführt wurde, mit der oft sanften Akzeptanz des nominellen Herrn. Es gab dem männlichen Chef eine echte Dominanz am Arbeitsplatz, eine Dominanz, die die feministische Bewegung bislang herausgefordert, aber noch nicht umgekehrt hat. Das Interesse der Familie und die historische christliche Lehre verboten Abtreibung. Die alte Moral hielt Abtreibung für unrechtmäßiges Töten, sie war nie erlaubt, und die Anhänger der traditionellen Moral denken immer noch so. Anhänger der neuen Moral denken das Gegenteil. Im Falle Roe v. Wade stützte der Oberste Gerichtshof das verfassungsmäßige Recht auf Abtreibung, das bis dahin als Frage der Einzelstaaten betrachtet wurde, auf die Doktrin eines Rechts auf Privatsphäre, das weit entfernt von jeglicher Sprache ist, die tatsächlich in der Verfassung oder ihren Änderungen zu finden ist.

Das Recht auf Privatsphäre einer Frau umfasste auch das Recht, Kinder zu haben oder nicht zu haben, unabhängig von den Konsequenzen für den Embryo. Der Oberste Gerichtshof betrachtete den Embryo nicht als Träger verfassungsmäßiger Rechte - Embryos waren in der zweiten Hälfte des 20. Jahrhunderts dieselben außerhalb der Verfassung stehenden Entitäten, wie Sklaven es in der ersten Hälfte des 19. Jahrhunderts gewesen waren. „Leben, Freiheit und das Streben nach Glück" galt nicht für Sklaven, und die Formulierungen der Unabhängigkeitserklärung wurden von den Richtern in Roe v. Wade nicht auf Embryonen angewendet.

Die Abtreibungsdebatte ist das extremste Beispiel für den Konflikt zwischen der alten und der neuen Moral, obwohl es ebenso bemerkenswerte Konflikte in anderen Bereichen gibt, in denen die alte gesellschaftliche Struktur mit ihrer Moral von der neuen herausgefordert worden ist. Die traditionelle christliche Moral, gleichermaßen in der protestantischen und katholischen Kirche, legte großen Wert auf sexuelle Rollen: Kein heterosexueller Geschlechtsverkehr außerhalb oder vor der Ehe. Keine homosexuellen Beziehungen. Lesbianismus wurde weniger betont, da die Gesellschaft dessen Existenz kaum anerkannte. Als Königin Victoria erstmals davon erzählt wurde, weigerte sie sich vehement zu glauben, dass solche Dinge zwischen Frauen geschehen könnten. Politische Korrektheit ist die Moral von vermeintlich unterdrückten Gruppen. Die Homosexuellen reklamierten eine gleichwertige Gültigkeit für ihren Lebensstil und stellten die traditionelle Opposition zu ihrem sexuellen Verhalten in Frage. „Homophobie" wurde als eine empörende Form von Vorurteilen angesehen, ähnlich wie rassistische Diskriminierung. Es wird von der neuen Moral als ebenso inakzeptabel angesehen, Homosexuelle zu kritisieren, wie Schwarze, Juden oder Frauen.

Gleichzeitig wurden andere sexuelle Tabus aufgehoben oder abgeschafft. In den 1960er Jahren gab es eine neue Welle der freien Liebe, teilweise basierend auf der scheinbaren Sicherheit der Anti-Baby-Pille, aber auch gefördert durch stimmungsverändernde Drogen und Popmusik. Dies führte zu einer zunehmenden Anzahl nichtehelichen Zusammenlebens. In den 1990er Jahren galt es in Großbritannien, einer eher altmodischen Gesellschaft im Vergleich zu den meisten Teilen der Vereinigten Staaten, als absolut normal, dass Prinz Edward mit seiner Freundin im Buckingham Palast schlief - in der gleichen stabilen, aber unverheirateten Intimität, in der Studenten seit den 60er Jahren miteinander in ihren Unterkünften schliefen. Nur wenige fanden es bemerkenswert, dass Königin Elizabeth II., das Oberhaupt der Church of England, das Verhalten ihres jüngsten Sohnes billigte, nachdem die Ehen ihrer drei älteren Kinder bereits gescheitert waren. Diejenigen, die sich beschwerten, wurden als hoffnungslos veraltet und prüde angesehen. Und doch gab es immer noch viele Menschen, die die alte Moral vorzogen, selbst wenn sie sie nicht selbst praktizierten oder ernsthaft erwarteten, dass ihre Kinder dies über ein bestimmtes Alter hinaus tun würden.

Die Bewegung der politischen Korrektheit hatte ebenfalls eine eigene puritanische Seite. Da sie aus den wahrgenommenen Interessen der Frauen hervorging, die als die am stärksten unterdrückte Gruppe angesehen wurden, gab es eine gewisse Feindseligkeit gegenüber männlicher Sexualität, sowohl in aggressiven als auch in zuvor als harmlos angesehenen Formen. Einige Frauen waren der Ansicht, dass alle Männer von Natur aus Vergewaltiger seien, und der natürliche Schrecken vor der Vergewaltigung wurde in eine allgemeine Verleumdung des männlichen Geschlechts übertrieben. Andere konzentrierten sich auf sexuelle Belästigung, ein tatsächliches Übel - viele Männer haben sehr grobe sexuelle Umgangsformen - welches in einigen trivialen Fällen lächerlich wurde. Sexuelle Belästigung wurde sogar bei bloßen Blicken ohne jedes gesprochene Wort oder physischen Kontakt angeklagt. Daher konnte die neue Moral sehr zensurbehaftet sein. Weiße Menschen konnten aufgrund ihrer Hautfarbe des Rassismus beschuldigt werden, nicht weil sie rassistisch waren, sondern weil sie weiß waren. Männer konnten der sexuellen Belästigung beschuldigt werden, weil ihre Mimik zeigte, dass sie eine Frau attraktiv fanden, was in einer früheren Generation eher als Kompliment denn als Beleidigung angesehen wurde.

Die politisch korrekten und die christlich-fundamentalistischen Gruppen kritisieren sich gegenseitig heftig, doch in der modernen Welt sehen sie sich ziemlich ähnlich. Beide setzen die Autorität einer bestimmten moralischen Doktrin voraus, als ob sie universell wäre, obwohl ihre moralischen Doktrinen unterschiedlich sind. Beide können tatsächlich wegen des gleichen Mangels kritisiert werden: wegen eines übertriebenen und übermäßig selbstsicheren Moralismus, dem es an Tiefe, historischem Verständnis und Toleranz mangelt. Beide werden wegen ihrer angeblichen Ähnlichkeit mit dem Puritanismus des siebzehnten Jahrhunderts angegriffen, mit selbstbewussten Moralisten wie Oliver Cromwell in England - er wäre beinahe nach Neuengland ausgewandert - oder den Hexenjägern von Salem. Weder die Frauenbewegung in ihrer dogmatischeren Form, noch die konservativen Prediger des Bible Belt können eines Mangels an Moral beschuldigt werden, sondern ihrer Überentwicklung und Starrheit. Das Herz dieser Moral scheint manchmal zu Stein geworden zu sein. Diese Art der Verhärtung der moralischen Arterien ist ebenso schädlich für die Konsensmoral der Gesellschaft wie die „Alles-ist-erlaubt"-Anarchie, gegen die sie protestiert.

Es handelt sich um eine Verzerrung der moralischen Kräfte, eine Verrohung in Selbstgerechtigkeit. Pharisäertum, die Überzeugung, einzigartig tugendhaft zu sein, existiert so lange wie die Menschheit selbst und war besonders für Jesus Christus anstößig. Die Aushöhlung der Moral, der Glaube, dass ethische Entscheidungen eine reine Privatsache sind, so wie die Wahl der Kleidung, ist ein jüngeres Phänomen. Dieser Glaube spiegelt das Fehlen jeglicher gemeinsamen Moral wider. Er führt das klassische Konzept der Freiheit auf eine ganz neue Ebene und verwandelt „das Streben nach Glück", wie es John Locke ursprünglich gemeint und Jefferson es 1776 verstanden hatte, in einen Hedonismus, der die Folgen nicht beachtet.

Der Ausdruck „das Streben nach Glück" stammt aus John Lockes *Essay über menschliches Verständnis* (1691). „Die höchste Vollkommenheit der intellektuellen Natur liegt in einer sorgfältigen Verfolgung von wahrem und solidem Glück, so dass die Sorge um uns selbst, dass wir imaginäres Glück nicht mit echtem Glück verwechseln, die notwendige Grundlage unserer Freiheit ist." Er führt jedoch aus, dass „nicht jeder sein Glück in derselben Sache sieht\... der Geist hat ebenso wie der Gaumen einen anderen Geschmack\... Die Menschen können unterschiedliche Dinge wählen, doch alle wählen richtig, vorausgesetzt, sie sind nur wie eine Gruppe armer Insekten, von denen einige Bienen sind, die sich an Blumen und ihrer Süße erfreuen, andere Käfer, die sich an anderen Arten von Speisen erfreuen." Dennoch argumentiert er weiter, dass die Vorliebe für Laster gegenüber Tugend „offensichtlich ein falsches Urteil" ist. Er legt besonderes Gewicht auf das religiöse Argument, meint aber auch, dass „böse Menschen hier den schlechteren Teil haben". Er glaubt, dass „Moral, auf ihren wahren Grundlagen errichtet, die Wahl in jedem, der nachdenken will, bestimmen kann".

Die Lockesche Lehre der Freiheit gibt den menschlichen Vorlieben zweifellos einen größeren Spielraum als autoritärere moralische Systeme, die darauf abzielen, alle Menschen gleich zu behandeln und Verhaltenseinheitlichkeit zu erzwingen. Doch schon bald erkennt die klassische Freiheitslehre die Notwendigkeit kollektiver moralischer Gebote an, einschließlich der Achtung anderer Menschen in der Gesellschaft, insbesondere ihres Lebens und des friedlichen Besitzes ihres Eigentums vor dem Gesetz. Ein allgemeiner Abbau der kollektiven Moral bedroht die Freiheit, sowohl direkt, indem ein Element der Anarchie eingeführt wird, als auch indirekt, indem die autoritärsten Kräfte der Gesellschaft ermutigt werden. Wir können die Geschichte der öffentlichen Moral als einen Zyklus zwischen Chaos und Autoritarismus sehen; die moderne autoritäre Moral, sowohl der Feminismus als auch der Fundamentalismus, sind als zyklische Reaktion auf den Hedonismus der 1960er Jahre entstanden.

Wir haben bereits einige Attribute der neuen Welt des nächsten Jahrhunderts beschrieben. Sie wird durch zwei Hauptkräfte geprägt sein: die Verschiebung der Technologie, die die Volkswirtschaften Asiens öffnet, und die neuen globalen elektronischen Kommunikationsmittel, die den Bürger immer unabhängiger von ihrer lokalen Regierung machen. Die neue Technologie wird viele der mittleren menschlichen Qualifikationen ersetzen oder hat sie bereits ersetzt - den Arbeiter am Fließband, den Büroangestellten und jetzt zunehmend auch den mittleren Manager. Aber sie hat die selteneren Fähigkeiten belohnt und eine internationale kognitive Elite von hochqualifizierten Menschen geschaffen, für die die neuen Kommunikationswege den größtmöglichen Markt für ihre Fähigkeiten eröffnen. Wie die meisten Eliten neigen auch die Mitglieder der kognitiven Elite dazu, sich selbst für etwas Besseres zu halten, sind eher arrogant und glauben, sie könnten ihre eigenen Standards setzen. Sie sind als Ergebnis davon von der Gesellschaft entfremdet.

Während der ersten Hälfte des nächsten Jahrhunderts wird ein massiver Vermögenstransfer von dem alten Westen zum neuen Osten stattfinden. Politische Fehler - und China ist immer noch ein politisch rückständiges Land - könnten diesen Transfer von Reichtum und strategischer Macht verzögern, aber es ist höchst unwahrscheinlich, dass sie ihn verhindern können. Sie können ihn nicht umkehren.

Dieser Prozess der Wohlstandsverschiebung wird in jedem Fall den größtmöglichen Druck auf die von Weißen dominierten Länder der Nordhalbkugel, auf Europa und Nordamerika, ausüben. Derzeit gehören etwa 750 Millionen Menschen zu den fortschrittlichen Ländern dieser Region; bis vor kurzem war Japan das einzige asiatische, nicht-weiße Land, das den euro-amerikanischen Lebensstandard erreicht hat, obwohl es ethnisch europäische Bevölkerungsgruppen in Neuseeland, Australien und in der weißen Bevölkerung Südafrikas gab. Sogar 1990 bestand die Gesamtbevölkerung der fortschrittlichen Industrieländer nur aus etwa 15 Prozent der Weltbevölkerung von 5 Milliarden. Die Form der Verteilung des weltweiten Reichtums war 15 Prozent reich, 85 Prozent arm, sehr ähnlich der Einkommensverteilung in fortschrittlichen Industriegesellschaften vor hundert Jahren. Bis 2050, in einem beschleunigenden Prozess, wird erwartet, dass die fortschrittlichen Volkswirtschaften etwa 3 Milliarden Menschen aus einer Weltbevölkerung umfassen werden, die vielleicht auf 7 Milliarden angestiegen ist, oder eine Vermögensverteilung von 40 Prozent reich, 60 Prozent arm. Bis zum Ende des Jahrhunderts könnten diese Zahlen gut umgekehrt sein, und die Verteilung könnte 60 Prozent reich und 40 Prozent arm sein, wobei die Armut besonders in Afrika konzentriert ist. Die Verschiebung zwischen den Nationen wird hin zu einer größeren Gleichheit des Reichtums sein, aber innerhalb der Nationen wird sie wahrscheinlich zu größerer Ungleichheit tendieren. Die effizienten Nutzer von Talent und Kapital werden einen entscheidenden Vorteil gegenüber denen mit mäßigen Fähigkeiten oder wenig Kapital haben. Dieser Reichtum wird hochmobil sein. Die Armen in der fortschrittlichen Welt werden die Reichen nicht in dem Maß des zwanzigsten Jahrhunderts besteuern können; die Länder, die dies versuchen, werden in einem intensiv wettbewerbsorientierten Rennen zurückfallen.

Natürlich wird die Gesamtproduktivität der Weltwirtschaft weiter steigen, möglicherweise um durchschnittlich 3 Prozent in der ganzen Welt, wenn es keinen Weltkrieg gibt. Wenn das zutrifft, wird sich das gesamte Weltprodukt alle fünfundzwanzig Jahre verdoppeln, was bedeutet, dass es bis 2050 mehr als viermal so groß wie jetzt und bis 2100 sechzehn bis zwanzigmal so groß sein wird. Selbst wenn die Weltbevölkerung bis 2100 auf 8 Milliarden angestiegen ist, wird das weltweite BIP pro Kopf am Ende des Jahrhunderts zehnmal so hoch sein wie jetzt. Ein solcher Anstieg des Wohlstands kann den Aufstieg der neuen Industriegesellschaften und die Millioneneinkommen der kognitiven Elite versorgen und trotzdem einen anständigen und steigenden Lebensstandard für den Rest der fortgeschrittenen Belegschaft sichern. Aber die Differenzen werden deutlich anders sein als im zwanzigsten Jahrhundert. In globaler Hinsicht werden die armen Nationen ihre Einkommen viel schneller wachsen sehen als die der reichen Nationen; national gesehen, werden die Einkommen der Reichen, wie in Amerika in den 1990er Jahren, viel schneller wachsen als mittlere oder niedrige Einkommen. Im nächsten Jahrhundert werden wir die Schaffung einer weltweiten Superklasse erleben, vielleicht von 500 Millionen sehr reichen Menschen, von denen 100 Millionen reich genug sein werden, um als souveräne Individuen hervorzugehen.

Dieser Prozess wird eine unvermeidliche Konsequenz haben. Gesellschaften werden viel weniger homogen werden; der Nationalstaat wird schwächer werden oder ganz zerfallen; die kognitive Elite wird sich als kosmopolitisch betrachten. Bereits jetzt entwickeln Menschen, die in den gleichen globalen Funktionen arbeiten, eine Kultur, die ihrer Arbeit in anderen Teilen der Welt näher steht, als ihren Mitbürgern in den alten Nationalstaaten. Ein Londoner Investmentbanker wird sich wahrscheinlich mehr in Seoul zu Hause fühlen als in Glasgow; ein Beamter aus Washington könnte sich in Bonn mehr zu Hause fühlen als in schwarzen Vierteln von Washington selbst. Wir können bereits den fragmentierenden Effekt beobachten, den dieser Prozess auf moralische Werte hat. Die Moral des Einzelnen wird zum Teil durch Bildung geprägt, durch das, was dem Einzelnen als Kind beigebracht wurde; sie wird auch teilweise durch Lebenserfahrungen geprägt. Sowohl die Bildung als auch die Erfahrungen der kognitiven Elite werden kosmopolitisch sein und dazu neigen, Menschen von ihren lokalen Gemeinschaften zu entfremden.

In dem Maße, wie wir uns auf das nächste Jahrhundert zubewegen, haben viele Menschen in der wachsenden kognitiven Elite kaum religiöse oder moralische Erziehung in der Familie bekommen. Die verbreitetste Religion der Elite ist ein agnostischer Humanismus. Viele solcher Familien sind selbst durch Scheidung, Wiederverheiratung und nachfolgende dritte Ehen gespalten. Das Ehemuster von Hollywood ist nicht überall in den USA anzutreffen, aber die kognitive Elite in Euro-Amerika hat eine hohe Scheidungsquote, die wahrscheinlich ein Drittel oder mehr beträgt. Die Kinder dieser geschiedenen Eltern haben selten eine grundlegende religiöse Erziehung und sind sich der Variabilität der moralischen Einstellung zwischen den Eltern, Stiefeltern und Stiefgeschwistern bewusst. Vergleicht man die ursprüngliche moralische Erziehung dieser Gruppe mit der einer irischen oder polnischen Dorfgemeinschaft, so bietet die Dorferziehung offensichtlich die stärkere religiöse Ausbildung. Eine gottlose, wurzellose und reiche Elite wird wahrscheinlich weder glücklich sein noch geliebt werden.

Diese Unzulänglichkeit in der anfänglichen moralischen Bildung, die in der dominanten Wirtschaftsgruppe des nächsten Jahrhunderts vorherrschen wird, wird wahrscheinlich durch ihre Lebenserfahrungen verstärkt. Diese Menschen werden die Disziplin einer fortgeschrittenen technischen Ausbildung, in welcher Art auch immer, besitzen, um sich auf ihre neue Rolle als Leiter des neuen elektronischen Universums vorzubereiten. Doch sie werden daraus nur einige der moralischen Lektionen lernen, die historisch das Gerüst für menschliches soziales Verhalten gebildet haben. Nach den Maßstäben von Konfuzius, Buddha oder Plato (500 v.Chr.), St. Paulus (50 n.Chr.) oder Mohammed (600 n.Chr.) könnten sie als moralisch ungebildet gelten. Sie werden die Lektionen wirtschaftlicher Effizienz, den Einsatz von Ressourcen und die Verfolgung von Geld vermittelt bekommen haben, aber nicht die Tugenden der Bescheidenheit oder Selbstlosigkeit, geschweige denn der Keuschheit. Im Wesentlichen werden die meisten von ihnen wie Heiden mit einem Wertesystem erzogen worden sein, das näher an das der späten Römischen Republik als an das Christentum heranreicht. Selbst diese Werte werden höchst individuell sein, statt geteilt. Gesellschaften, wie wir argumentiert haben, können nur stark sein, wenn echte moralische Werte weit verbreitet sind. Die fortschrittlichen Nationen bewegen sich bereits auf eine Situation zu, in der viele Menschen schwache oder begrenzte moralische Werte haben werden, andere werden dies durch ein vehementes Festhalten an irrationalen Werten kompensieren, und nur wenige Werte werden in der gesamten Gesellschaft geteilt werden. Zweifellos werden einige der „konkurrierenden territorialen Clubs", die wir zuvor beschrieben haben, anspruchsvolle moralische Standards für den Aufenthalt auferlegen.

Unterschiede im Wohlstand haben an sich in der Geschichte nicht zu fundamentalen Unterschieden in religiösen Werten geführt. In dichten und stabilen Gesellschaften mit starken Traditionen kann eine steile hierarchische Struktur -- „der reiche Mann in seiner Burg, der arme Mann vor seinem Tor" - Werte verbergen, die sich durch die Hierarchie ziehen. Dies hängt aber von der Stärke des gemeinschaftlichen Gefühls der Reichen und Armen und der Stärke der sozialen Traditionen ab. Keine dieser Bedingungen besteht heute, und sowohl das Gemeinschaftsgefühl als auch die Traditionen werden durch die wirtschaftliche und technologische Revolution, die gerade stattfindet, geschwächt. Die Leben der vielen und der wenigen entfernen sich immer mehr voneinander. Die technologische Revolution wurde durch den Bruch mit den alten Methoden erreicht. In jedem Bereich waren es die Radikalen, die gesiegt haben und die konventionellen Denker, die ins Hintertreffen geraten und buchstäblich aus dem Rennen gefallen sind. Unsere Politik mag von konventionellen Denkern - Bill Clinton, Helmut Kohl, John Major - geführt werden, aber unsere erfolgreichsten Unternehmen werden von Radikalen mit einem tiefen Verständnis für die neue technologische Welt angeführt; das Paradebeispiel ist Bill Gates. Das konventionelle Denken wurde durch seine Unfähigkeit, mit der Geschwindigkeit und der schieren Kraft des Wandels umzugehen, diskreditiert.

Und doch ist Moral nicht so. Wenn wir die Wissenschaft des Moses nehmen, die etwa 1000 v. Chr. entstanden ist, hat sie uns sehr wenig zu sagen. Der Bericht über die Schöpfung im Buch Genesis mag eine theologische Wahrheit enthalten - Gott schuf das Universum und die Menschheit, gibt aber keinen wissenschaftlichen Bericht über die tatsächliche Entwicklung physischer Strukturen. Wenn wir jedoch die Moral des Moses - die Zehn Gebote - betrachten, hat sie uns eine Menge zu sagen.

Respekt für die Eltern und Treue in der Ehe sind die besten Wege, das Familienleben zu bewahren; das Familienleben ist der beste Weg, moralisch gesunde Kinder großzuziehen. Diebstahl schadet dem Dieb und den Menschen, von denen Sachen gestohlen werden, und hemmt die Anreize zu arbeiten und zu sparen. Die soziale Ordnung hängt von der Wahrheit der Zeugen ab. Es ist falsch zu morden, und so weiter.

In der Wissenschaft haben drei Jahrtausende völlig verändert, was menschliches Wissen ist; in der Moral könnten wir tatsächlich zurückgefallen sein. Der durchschnittliche Psychotherapeut gibt dem Patienten wahrscheinlich weniger gute moralische Ratschläge, wie er sein Leben führen soll, als der durchschnittliche Jude von seinem Lehrer in der Zeit von Moses erhalten hätte. Natürlich ist das Christentum selbst noch immer vorhanden, aber es ist für den größten Teil der Welt nur ein blasser Schatten seines früheren Selbst. Wenige Menschen haben den Glauben der früheren Zeitalter, oder sogar der weniger ausgeklügelten Gemeinschaften; man sucht nicht nach Heiligen auf der Park Avenue.

Die Zerstörung der Tradition war eine notwendige Bedingung für den wissenschaftlichen Fortschritt. Wenn wir alle noch glauben würden, dass die Sonne sich um die Erde dreht, hätten wir keine Satellitenkommunikation entwickelt. Was wir tatsächlich für Wissenschaft halten, ist nichts weiter als eine Reihe von Hypothesen, unvollkommene Erklärungen, die durch andere, stärkere, aber immer noch unvollkommene Erklärungen ersetzt werden. Und doch hat die Zerstörung der Tradition ein Desaster für die moralische Ordnung der Welt bedeutet.

Konfuzius lehrte, dass wir immer Maß halten sollten (er nannte das goldene Mittel *Chum Yum*, zumindest wurde es so von Gelehrten des siebzehnten Jahrhunderts übersetzt). Er lehrte auch, dass wir die Autorität respektieren und andere so behandeln sollten, wie wir selbst behandelt werden möchten. Diese Lehre ist zweihundertfünfzig Jahre alt. Als Tradition beeinflusste sie China über die gesamte aufgezeichnete Geschichte hinweg, doch dem Konfuzianismus messen viele moderne Chinesen keine Bedeutung mehr bei, die keine Mäßigung schätzen, die Kraft statt Autorität respektieren und sicherlich andere nicht so behandeln, wie sie selbst behandelt werden möchten. Mit dem Verlust der Tradition können Gesellschaften das ganze Vokabular ihres moralischen Konsenses verlieren. China, mit all seiner aufstrebenden Macht, ist heute im Vergleich zu Tibet ein moralisch rückständiges Land, so arm und unterdrückt die Tibeter auch sein mögen.

Eine gute soziale Moral hat bestimmte Eigenschaften. Sie sollte zur Überlebensfähigkeit der Gesellschaft und von Individuen beitragen, und zwar auf dynamische und nicht auf statische Weise. Sie sollte Toleranz beinhalten und Selbstgerechtigkeit vermeiden. Sie sollte religiös sein, nicht bloß agnostisch. Sie sollte nicht vorgeben, Fragen wissenschaftlicher Fakten entscheiden zu können. Sie sollte weder anarchistisch noch autoritär sein. Sie sollte weit verbreitet und tief verankert sein. Eine solche soziale Moral ist besonders wichtig für die Familie und für die Erziehung von Kindern zu unabhängigen und verantwortungsbewussten Erwachsenen. Sie bildet den Mittelpunkt einer guten Gesellschaft.

Wir stellen fest, dass eine solche Moral von der Logik der gegenseitigen Abhängigkeit getragen wird, die sich aus dem Handel und dem Miteinander ergibt, aber durch die Angriffe eines oberflächlichen Szientismus, durch die Entfremdung einer Ober- und einer Unterklasse, durch den Verlust der Verwurzelung der alten geografischen Ökonomien bedroht ist. Vielleicht wird es eine Reaktion gegen diese Tendenzen geben. Sie müssen als äußerst gefährlich für die Gesellschaften des nächsten Jahrhunderts erkannt werden.

Mit dem Ende des „schrecklichsten Jahrhunderts der abendländischen Geschichte", wie es Isaiah Berlin nannte, geht auch das Zeitalter des Gigantismus in der Sozialstruktur zu Ende. Die letzten Tage des zwanzigsten Jahrhunderts sind dazu bestimmt, eine Zeit der Verkleinerung, der Dezentralisierung und der Neuorganisation zu sein. Es wird die Zeit der sozialen Dinosaurier sein, die in der Teergrube gefangen sind. Und eine Zeit der Aasfresser. Vögel werden die Knochen der Dinosaurier picken. Regierungen, Unternehmen und Gewerkschaften werden gezwungen sein, sich gegen ihre Neigungen hin zu neuen Meta-Konstitutionsbedingungen, bedingt durch den Einzug der Mikrotechnologie, anzupassen. Dies hat die Grenzen, innerhalb derer Gewalt ausgeübt wird, tiefgreifend verschoben. Die heutige Welt hat sich bereits mehr verändert, als wir allgemein verstehen, mehr als CNN und die Zeitungen uns erzählen. Und sie hat sich genau in den Richtungen verändert, wie sie eine Studie über megapolitische Zustände zeigt. Wie wir zuerst in *Blood in the Streets* und dann in *The Great Reckoning* argumentierten, wenn sich Technologie oder andere Faktoren, die die Grenzen setzen, innerhalb derer Gewalt ausgeübt wird, verändern, verändert sich unweigerlich auch der Charakter der Gesellschaft. Alles, was mit der Art und Weise verbunden ist, wie Menschen interagieren, einschließlich der Moral und des gesunden Menschenverstandes, wie wir die Welt sehen, wird sich ebenfalls ändern. Nach einer Phase schwacher Moral, die das Ende einer Ära anzeigt, werden wir ein Erwachen einer strengeren Moral erleben, mit anspruchsvolleren Forderungen, um den anspruchsvolleren Anforderungen einer Welt der Wettbewerbssouveränität zu begegnen.

Mehrere Merkmale der neuen Moral sind absehbar. Zum einen wird sie die Bedeutung der Produktivität und die Korrektheit der Einbehaltung von Gewinnen durch diejenigen, die sie erwirtschaften, betonen. Ein weiterer Schlüsselpunkt wird die Effizienz von Investitionen sein. Die Moral des Informationszeitalters lobt Effizienz und erkennt den Vorteil an, Ressourcen ihrer hochwertigsten Nutzung zuzuführen. Mit anderen Worten, die Moral des Informationszeitalters wird die Moral des Marktes sein. Wie James Bennett argumentiert hat, wird die Moral des Informationszeitalters auch eine Moral des Vertrauens sein. Die Cyberwirtschaft wird eine hochgradig vertrauenswürdige Gemeinschaft sein. In einem Umfeld, in dem eine unknackbare Verschlüsselung es einem Veruntreuer oder Dieb ermöglicht, die Erlöse aus seinen Verbrechen sicher außerhalb des Bereichs der Wiedererlangung zu platzieren, wird es einen sehr starken Anreiz geben, Verluste zu vermeiden, indem man mit Dieben und Veruntreuern gar nicht erst Geschäfte macht. Ebenso, wie im früher zitierten Beispiel der Quäker, wird ein Ruf der Ehrlichkeit ein wichtiges Gut in der Cyberwirtschaft sein. In der Anonymität des Cyberspace wird dieser Ruf vielleicht nicht immer einer bekannten Person gelten, aber er wird zuverlässig verifizierbar sein durch die Identifizierung von kryptographischen Schlüsseln. Die Möglichkeit, dass es zu Ausweitungen von Schwierigkeiten kommt, wenn Verschlüsselung oder Zertifizierung kryptografischer Identitäten durch Gangster oder andere korrupte Personen missbraucht werden, ist entmutigend genug, dass es stark gegen die Anstellung von Personen spricht, deren Verhalten auf mangelnde Vertrauenswürdigkeit hinweist. Bennett stellt sich einen „Gentlemen's Club des Cyberspace" vor, geschützte Bereiche, die für die Teilnahme erhöhte Sicherheitsmaßnahmen verlangen würden, „möglicherweise mit biometrischer Überprüfung wie Stimmerkennung. Die Betreiber würden die Verantwortung für die Identifizierung der Teilnehmer und bis zu einem gewissen Grad für ihre Vertrauenswürdigkeit übernehmen und so einen ‚Gentlemen's Club im Cyberspace' schaffen (obwohl Damen heutzutage natürlich willkommen wären). In diesen Bereichen könnten Menschen Geschäfte mit größerer Sicherheit und Vertrauen als im allgemeinen Bereich des Cyberspace abwickeln. So könnte das 21. Jahrhundert eine Rückkehr zu einem viktorianischen Schwerpunkt auf Vertrauenswürdigkeit und Charakter in einer Umgebung sehen, die sich kein Viktorianer hätte vorstellen können."

Die geschützten Bereiche des Cyberspace könnten ebenfalls Garantien anbieten, um Risiken zu mindern, ähnlich wie die extraterritorialen Schutzgarantien, die die Grafen von Champagne anboten, um Händler auf den Messen von Champagne zu schützen. Andere Gerichtsbarkeiten haben tatsächlich „Händler auf Reisen vor jeglichen Verlusten geschützt, die sie möglicherweise erleiden könnten, während sie durch das Territorium unter der Gerichtsbarkeit des jeweiligen Adeligen ziehen."

„Die Wächter der Messe", ursprünglich von den Grafen ernannte Beamte, boten Sicherheit und ein „Tribunal der Gerechtigkeit" für die Händler auf der Messe. Sie entwickelten sich schließlich zu eigenständigeren Instanzen, mit einem separaten Siegel, das Verträge beglaubigte und deren Erfüllung erzwang mit der Macht, „jeden Händler, der einer Nichtzahlung seiner Schulden oder der Nichterfüllung seiner vertraglichen Versprechen für schuldig befunden wurde, von zukünftigen Messen auszuschließen. Dies war offensichtlich eine so schwere Strafe, dass nur wenige bereit waren, diesen Entzug von zukünftigen Gewinnmöglichkeiten freiwillig zu riskieren. Andernfalls könnten die Wachen die Güter eines säumigen Schuldners beschlagnahmen und zugunsten seiner Gläubiger verkaufen." [^505]

Die Ächtung als Mittel zur Durchsetzung von Verträgen verlor an Bedeutung, als die Anzahl alternativer Märkte stieg. Mit der nun verfügbaren neuen Informationstechnologie könnte die Ächtung von Betrügern und Vertragsbrechern jedoch wieder zu einem starken Durchsetzungsmechanismus in den fragmentierten Souveränitäten der nächsten Gesellschaftsstufe werden. Computer-Verknüpfungen können den Cyberspace mit unauslöschlichen Informationen über Kredit und Betrug überwachen. Da die Welt in diesem Sinne eine besonders kleine Gemeinschaft sein wird, werden Betrüger und Schwindler entmutigt werden.

Zusätzlich zur Betonung der Moral von Einnahmen und Effizienz und der erneuten Betonung von Charakter und Vertrauenswürdigkeit, wird die neue Moral vermutlich auch die Boshaftigkeit von Gewalt hervorheben, insbesondere Entführung und Erpressung, die als Mittel zum „Ausnehmen" von Individuen zunehmen werden, deren Ressourcen ohne diese Methoden nicht leicht zur Beute von Kriminalität werden würden.

Ein weiterer wahrscheinlicher Antrieb zu strengerer Moral wird das Ende von Ansprüchen und Einkommensumverteilung sein. Wenn die Hoffnung auf Hilfe für diejenigen, die zurückfallen, hauptsächlich auf Aufrufen an Privatpersonen und wohltätige Körperschaften beruht, wird es wichtiger als im zwanzigsten Jahrhundert sein, dass die Empfänger von Wohltätigkeit gegenüber denen, die freiwillig Wohltätigkeit leisten, als moralisch würdig erscheinen.

> „Subventionen, Geldgeschenke und die Aussicht auf wirtschaftliche Möglichkeiten lassen die Notwendigkeit des Umweltschutzes in den Hintergrund treten. Die Mantras von Demokratie, Umverteilung und wirtschaftlicher Entwicklung steigern die Erwartungen und die Fruchtbarkeitsraten, fördern das Bevölkerungswachstum und verstärken damit eine ökologische und wirtschaftliche Abwärtsspirale." [^506] - Virginia Abernathy

In gewisser Weise wird die neue Informationswelt besser in der Lage sein, Ernsthaftigkeit in moralischen Fragen zu fördern. Die Versprechen einer Einkommensumverteilung, die in den USA, Kanada und Westeuropa Erwartungen unter den Unglücklichen und Erfolglosen geschürt haben, haben auch international eine perverse Wirkung gehabt. Es gibt starke Hinweise darauf, dass ausländische Hilfe und Versprechen von Interventionen zur Abwendung von Hungersnöten und zur Steigerung der Lebensstandards wichtige Faktoren für das Bevölkerungswachstum waren, das die Tragfähigkeit von rückständigen Wirtschaften übersteigt. Das erschreckende Wachstum der Weltbevölkerung seit dem Zweiten Weltkrieg, mit seinen oft zerstörerischen Auswirkungen auf Wälder, Böden und Wasserressourcen, kann auf eine globale Intervention zurückgeführt werden. Diese Intervention hat die negativen Rückkopplungsfolgen umgangen, die lange Zeit dafür gesorgt haben, dass lokale Bevölkerungen im Einklang mit den Ressourcen standen, die zur Unterstützung von ihnen notwendig waren.

Natürlich waren viele, die in lokalen Umgebungen mit wenigen Ressourcen und wenig oder keinem Wachstum lebten, nur allzu erfreut zu hören, dass die einschränkenden Begrenzungen ihres Dorflebens beiseite gelegt werden könnten. Sie nahmen die optimistische Botschaft von internationalen Hilfsarbeitern, Freiwilligen des Friedenskorps, lokalen Revolutionären und den konkurrierenden Ideologen des Kalten Krieges, die jedem versprachen, dass bessere Zeiten bevorstünden, begierig an. Dies war genau die falsche Botschaft.

Eine wichtige Auswirkung der Umverteilung zwischen Kulturen besteht darin, dass Menschen, die in nichtindustriellen Zivilisationen lebten und nichtindustrielle Werte beibehielten, künstlich wettbewerbsfähig gemacht wurden. Internationale Hilfe, Rettungseinsätze zur Bekämpfung von Hungersnöten und Krankheiten sowie technische Interventionen gaukelten vielen vor, dass ihre Lebensaussichten sich stark verbessert hätten, ohne dass sie ihre Werte aktualisieren oder ihr Verhalten signifikant ändern mussten.

Die internationale Einkommensumverteilung hat nicht nur zu einem nicht nachhaltigen Bevölkerungswachstum in der Welt beigetragen, sondern auch in wichtigen Aspekten zur kulturellen Relativität und zur weit verbreiteten Verwirrung über die entscheidende Rolle der Kultur für die Menschen, um in ihrer lokalen Umgebung zu gedeihen. Heutzutage glauben die meisten Menschen, dass Kulturen eher Geschmacksache sind als Ressourcen, die das Verhalten lenken und sowohl irreführen als auch informieren können. Wir sind zu sehr darauf versessen zu glauben, dass alle Kulturen gleich sind, und zu langsam, um die Nachteile kontraproduktiver Kulturen zu erkennen. Das gilt insbesondere für die hybriden Kulturen, die in diesem Jahrhundert in vielen Teilen der Welt im Treibhaus von Subventionen und Interventionen zu entstehen begonnen haben. Wie die kriminelle Subkultur in den inneren Städten Amerikas behalten sie inkohärente Teile von Kulturen aus früheren Phasen der wirtschaftlichen Entwicklung bei und kombinieren sie mit Wertvorstellungen für das Verhalten im Informationszeitalter.

Die Informationsrevolution wird daher nicht nur das Genie in uns entfesseln, sie wird auch den Geist der Nemesis entfachen. Beide werden im kommenden Jahrtausend wie nie zuvor um Dominanz ringen.

Der Übergang von einer Industrie- zu einer Informationsgesellschaft wird atemberaubend sein. Der Übergang von einer Wirtschaftsphase zur nächsten hat immer eine Revolution mit sich gebracht. Wir glauben, dass die Informationsrevolution wahrscheinlich die weitreichendste von allen sein wird. Sie wird das Leben grundlegender neu organisieren als die Agrarrevolution oder die industrielle Revolution. Und ihre Auswirkungen werden in einem Bruchteil der Zeit zu spüren sein. Schnallen Sie sich an.

[^467]: Vito Tanzi, „Corruption: Arm's-length Relationships and Markets," in Gianluca Fiorentini und Sam Peltzman, eds., The Economics of Organized Crime (Cambridge: Cambridge University Press, 1995), S. 167, 170.

[^468]: Hirshleifer, ebenda, S. 176.

[^469]: Ebenda, S. 169.

[^470]: Michelle R. Garfinkel und Stergios Skaperdas, Hrsg., The Political Economy of Conflict and Appropriation (Cambridge: Cambridge University Press, 1996), S. 1.

[^471]: Hirshleifer, ebenda, S. 173.

[^472]: Garfinkel und Skaperdas, ebenda, S. 1.

[^473]: Ebenda

[^474]: Hamish McRae, The World in 2020 (London: Harper Collins, 1995), S. 188.

[^475]: Ebenda, S. 188-89.

[^476]: Kevin Kelly, Out of Control (Reading, Mass.: Addison-Wesley, 1994), S. 189

[^477]: Tilly, „War Making and State Making as Organized Crime," in Evans, Rueschemeyer, und Skoepol, ebenda, S. 171.

[^478]: Ebenda, S. 169.

[^479]: Frank Viamo, „The New Mafia Order," Mother Jones, Mai/Juni 1995, S. 55.

[^480]: Siehe Velisarios Kattoulas, „Japan\'s Yakuza Claim Place Among Criminal Elite," Washington Times, 25. November 1994, S. A22.

[^481]: Viamo, ebenda, S. 49.

[^482]: Garfinkel und Skaperdas, ebenda, S. 2.

[^483]: Fiorentini und Peltzman, ebenda, S. 15.

[^484]: Ebenda.

[^485]: Ebenda, S. 16.

[^486]: Ebenda.

[^487]: Für weitere eindeutige Beweise für die Beteiligung der CIA am Drogenhandel, siehe Michael Levine, The Big White Lie: The Deep Cover Operation That Exposed the CIA Sabotage of the Drug War (New York: Thunder\'s Mouth Press, 1994).

[^488]: Roger Morris, Partners in Power (New York: Henry Holt, 1996), S. 233.

[^489]: Ebenda, S. 393.

[^490]: Ebenda, S. 411.

[^491]: Ebenda, S. 418.

[^492]: Ebenda.

[^493]: Gründlicher Überblick über die Foster-Geschichte, siehe Christopher Ruddy, Vincent Foster: The Ruddy Investigation, verfügbar für \$19.95 von 1-800-711-1968.

[^494]: Morris, ebenda, S. 331.

[^495]: Siehe Jeffrey Goldberg, „Some of the President's New Union Pals Seem to Have Some Suspicious Pals of Their Own", New York, 9. Juli, 1996, S. 17.

[^496]: Ebenda, S. 19.

[^497]: Ebenda.

[^498]: Hirshleifer, ebenda, S. 173.

[^499]: Tanzi, ebenda, S. 167, 170.

[^500]: Walter Lippmann, The Public Philosophy (New Brunswick, N.J.: Transaction Publishers, 1989), S. 14.

[^501]: Ebenda, S. 15.

[^502]: Paul Roazen, „Introduction", in Lippmann, ebenda, S. xv.

[^503]: Morris, ebenda, S. 469.

[^504]: Fiorentini und Peltzman, ebenda, S. 16.

[^505]: James Bennett, „Cyberspace and the Return of Trust", Strategic Investment, Oktober 1996.

[^506]: Virginia Abernethy, „Optimism and Overpopulation", Atlantic Monthly December 1994, S. 88.
