# Kapitel 10: DIE DÄMMERUNG DER DEMOKRATIE

> „Demokratische politische Systeme sind in historischer Hinsicht eine neuere Angelegenheit. Sie hatten eine kurze Existenz in Griechenland und Rom, bevor sie im 18. Jahrhundert, vor weniger als 200 Jahren, erneut aufgetaucht sind. \... Ein Zyklus der Ablehnung könnte nun wieder begonnen haben." [^430] - William Pfaff

Es ist kein Geheimnis, dass Demokratie in der Geschichte der Regierungen relativ selten und vergänglich war. In den antiken und modernen Zeiten, in denen sich die Demokratie durchgesetzt hat, hing ihr Erfolg von megapolitischen Bedingungen ab, die die militärische Macht und Bedeutung der Massen stärkten. Der Historiker Carroll Quigley hat diese Charakteristika in seinem Werk „Waffensysteme und politische Stabilität" analysiert. [^431]

Miteinbezogen wurde unter anderem Folgendes:

1.  **Günstige und weit verbreitete Waffen.** Demokratie neigt dazu, zu gedeihen, wenn die Kosten für den Kauf nützlicher Waffen niedrig sind.

2.  **Waffen, die effektiv von Laien genutzt werden können.** Die Wahrscheinlichkeit von Demokratie steigt, wenn jeder in der Lage ist, effektive Waffen ohne langwierige Ausbildung zu benutzen.

3.  **Ein militärischer Vorteil für eine große Anzahl von Fußsoldaten im Kampf.** Wie Quigley herausstellt: „Phasen der Dominanz der Infanterie waren Zeiten, in denen die politische Macht innerhalb der Gesellschaft stärker verteilt war und die Demokratie eine bessere Chance hatte, sich durchzusetzen." [^432]

Dies ist kaum ein vollständiger Katalog der Bedingungen, unter denen Demokratie existieren kann. Wenn dies der Fall wäre, wäre die Demokratie nicht zum triumphierenden System am Ende des zwanzigsten Jahrhunderts geworden. Waffen waren zum Ende der Industrieära vermutlich teurer als je zuvor. Und viele der wirksamsten Waffen erforderten definitiv Spezialisten, um effektiv eingesetzt zu werden. Darüber hinaus bewies der Golfkrieg zwischen den Vereinigten Staaten, ihren Verbündeten und dem Irak, wie verwundbar große Infanterieeinheiten sind, selbst wenn sie in Schützengräben und Befestigungen verschanzt sind. Warum also schien die Demokratie unter diesen Bedingungen zu florieren, als das zwanzigste Jahrhundert zu Ende ging?

## DEMOKRATIE, DER ZWILLINGBRUDER DES KOMMUNISMUS?

Wir haben in Kapitel 5 eine paradoxe Erklärung angeboten, nämlich dass die Demokratie als Zwillingsbruder des Kommunismus gerade deshalb aufblühte, weil sie eine ungehinderte Kontrolle der Ressourcen durch den Staat ermöglichte. Dieser Schluss mag dem ‚gesunden Menschenverstand' des industriellen Zeitalters albern erscheinen. Wir leugnen nicht, dass demokratische Systeme und Kommunismus innerhalb der Grenzen der industriellen Gesellschaft drastische Gegensätze darstellten. Doch aus einer megapolitischen Perspektive betrachtet, wie sie wahrscheinlich eher aus der Sicht des Informationszeitalters wahrgenommen wird, hatten die beiden Systeme mehr gemeinsam, als man vermuten würde.

In einem Kontext, in dem Waffen grotesk teuer waren, wurde die Demokratie zum Entscheidungsmechanismus, der die Kontrolle über Ressourcen durch den Staat maximiert. Ähnlich wie der staatliche Sozialismus, machten demokratische Systeme riesige Summen zur Finanzierung einer massiven militärischen Infrastruktur verfügbar. Der Unterschied bestand jedoch darin, dass der demokratische Wohlfahrtsstaat sogar noch mehr Ressourcen in die Hände des Staates legte als es die staatlich-sozialistischen Systeme tun konnten. Das ist durchaus bemerkenswert, wenn man bedenkt, dass die staatlich-sozialistischen oder kommunistischen Systeme praktisch jeden wertvollen Besitz beanspruchten.

Betrachtet man das Ganze nüchtern lediglich als Mechanismus zur Ressourcensammlung, war der demokratische Staat dem staatlichen Sozialismus als Rezept zur Bereicherung des Staates überlegen. Wie wir bereits früher erklärten, stellte die Demokratie dem Militär erheblich mehr Geld zur Verfügung, weil die Demokratie mit privatem Eigentum und kapitalistischer Produktivität kompatibel war.

Das System des staatlichen Sozialismus basierte auf der Lehre, dass der Staat alles besaß. Der demokratische Wohlfahrtsstaat hingegen stellte zunächst begrenztere Ansprüche. Er gab vor, privates Eigentum zuzulassen, wenn auch von einer bedingten Art, und nutzte so überlegene Anreize zur Mobilisierung von Leistungen. Anstatt von Beginn an eine umfassende Misswirtschaft zu betreiben, ließen demokratische Regierungen im Westen den Individuen Eigentum besitzen und Reichtum ansammeln. Erst nachdem der Reichtum geschaffen wurde, griffen die demokratischen Nationalstaaten ein, um einen großen Teil davon wegzubesteuern.

Das Wort „groß" sollte an dieser Stelle großgeschrieben werden. Zum Beispiel stand im Jahr 1996 der lebenslange Bundessteuersatz in den Vereinigten Staaten bei 73 Cent pro Dollar. Für Eigentümer von Unternehmen, die ihr Einkommen durch Dividenden erhielten, lag der Satz bei 83 Cent pro Dollar. Und für jede Person, die Geld an Enkelkinder weitergeben oder verlassen wollte, betrug die Bundessteuerrate 99 Cent pro Dollar. Wenn man die Bundes- und Landessteuern ebenfalls in Betracht zieht, konfisziert eine demokratische Regierung auf allen Ebenen den Löwenanteil jedes in den Vereinigten Staaten verdienten Dollars. Die räuberischen Steuersätze machten den demokratischen Staat zu einem de facto Partner mit einem Anteil von mindestens drei Vierteln bis neun Zehnteln an allen Einnahmen. Das war sicherlich nicht dasselbe wie Staatsozialismus. Aber es war eine enge Verwandtschaft.

Der demokratische Staat überlebte länger, weil er flexibler war und im Vergleich zu Moskau oder Ost-Berlin über größere Mengen an Ressourcen verfügte.

### „Ineffizienz, wo es darauf ankam"

Wir haben die megapolitischen Vorteile der Demokratie als Entscheidungsgrundlage für eine mächtige Regierung als „Ineffizienz, wo es darauf ankam" beschrieben. Verglichen mit dem Kommunismus war der Wohlfahrtsstaat in der Tat ein viel effizienteres System. Aber im Vergleich zu einer echten Laissez-Faire-Enklave wie Hongkong war der Wohlfahrtsstaat ineffizient. Die Wachstumsraten in Hongkong waren fabelhaft, aber ihre Überlegenheit lag genau in der Tatsache, dass der Bewohner von Hongkong, und nicht die Regierung, in der Lage war, 85 Prozent der Vorteile des schnelleren Wachstums einzustecken.

Hongkong ist natürlich keine Demokratie. Tatsächlich ist es ein geistiges Modell für die Art von Zuständigkeit, die wir im Informationszeitalter zu sehen erwarten. Im Industriezeitalter musste Hongkong keine Demokratie sein, da es die unangenehme Notwendigkeit vermieden hat, Ressourcen zur Unterstützung einer mächtigen militärischen Einrichtung zu sammeln. Hongkong wurde von außen verteidigt, sodass es sich leisten konnte, eine wirklich freie Wirtschaft zu erhalten.

Es war genau diese Fähigkeit, Ressourcen anzuhäufen, die der Demokratie während der megapolitischen Bedingungen des Industriezeitalters die Oberhand verlieh. Massendemokratie ging Hand in Hand mit dem Industriekapitalismus. Wie Alvin Toffler sagte, ist die Massendemokratie „der politische Ausdruck von Massenproduktion, Massenverteilung, Massenkonsum, Massenbildung, Massenmedien, Massenunterhaltung, und allem Anderen." [^433]

Nun, da die Informationstechnologie die Massenproduktion verdrängt, ist es logisch, den Niedergang der Massendemokratie zu erwarten. Das entscheidende megapolitische Gebot, das die Massendemokratie im Industriezeitalter zum Triumph führte, ist verschwunden. Es ist daher nur eine Frage der Zeit, bis die Massendemokratie den Weg ihres Bruders, des Kommunismus, geht.

### Massendemokratie unvereinbar mit dem Informationszeitalter

Eine kurze Reflektion zeigt, dass die Technologie des Informationszeitalters nicht zwangsläufig eine Massentechnologie ist. In militärischer Hinsicht, wie wir angedeutet haben, eröffnet sie das Potenzial für „intelligente Waffen" und „Informationskrieg", in dem „Logikbomben" zentralisierte Kommando- und Kontrollsysteme sabotieren könnten. Die Informationstechnologie weist nicht nur eindeutig auf die Perfektionierung von Waffen hin, die von Spezialisten bedient werden; sie verringert auch die Entscheidungsfähigkeit der Kriegsführung und verbessert die relative Position der Verteidigung. Die Mikrotechnologie ermöglicht einen dramatischen Anstieg der militärischen Macht des Einzelnen, während die Bedeutung von Masseninfanterieformationen abnimmt. In einem Bericht der Rand Corporation an den Verteidigungsminister heißt es: „Verbundene Netzwerke können nicht nur von Staaten, sondern auch von nichtstaatlichen Akteuren, einschließlich verstreuter Gruppen und sogar Einzelpersonen, angegriffen und gestört werden." [^434] Darüber hinaus lässt dies darauf schließen, dass Cyberkrieg das Potenzial der inhärenten Skalennachteile in großen zentralisierten Systemen realisieren wird.

In den Worten der Rand-Experten: „Informationsbasierte Techniken machen die geografische Entfernung irrelevant; Ziele auf dem amerikanischen Festland sind genauso verwundbar wie Agenten im Kriegsgebiet." [^435] Früher war mit dem Wohnsitz innerhalb der Grenzen großer, supermächtiger Nationalstaaten wie den Vereinigten Staaten eine gewisse Sicherheit verbunden, im Informationszeitalter könnte jedoch die Logik der Machtkonzentration umgekehrt werden. Peoria mag weit von jeder potenziellen militärischen Front entfernt sein, aber es wird nicht länger sicher vor Cyberattacken von nahezu jedem potenziellen Gegner sein. Innerhalb der Grenzen einer Supermacht zu leben, bedeutet, sich selbst ins Zentrum des Zieles zu setzen. Statt sich zu vereinigen, könnten Orte ihre Sicherheit erhöhen, indem sie sich aufspalten. Das Aufkommen des Cyberkrieges wird die Verwundbarkeit zentralisierter Befehls- und Kontrollsysteme erhöhen, während die Wettbewerbsfähigkeit verteilter Systeme gesteigert wird.

Die dadurch ausgelösten Rückkopplungsmechanismen könnten den Dezentralisierungsprozess beschleunigen. Wie die Rand-Experten vorschlagen, werden die Regierungen gezwungen sein, „die Nutzung neuer Software-Verschlüsselungstechniken" zu verstärken, um die Anfälligkeit der Kommando- und Kontrollsysteme, die sich in der Spätphase des Nationalstaates entwickelt haben, für Cyberangriffe zu verringern. Dadurch werden diese hauptsächlich privatwirtschaftlichen Systeme weitaus weniger sabotageanfällig und gleichzeitig wird die kommerzielle Verbreitung der starken Verschlüsselung beschleunigt, was dazu beitragen wird, sie von der staatlichen Vorherrschaft zu befreien. Auch dies wird der Dezentralisierung Auftrieb geben. Wie wir bereits dargelegt haben, wird dies die Verlagerung von Ressourcen in den Cyberspace weiter vorantreiben, wo sie außerhalb der Reichweite der Politik liegen.

Letztendlich bedeutet dies das Ende der Massendemokratie, insbesondere in ihrer vorherrschenden Form, der repräsentativen Fehlregierung, sei es vom Bundes- oder vom Landtag.

## DIE MEGAPOLITIK DER FEHLDARSTELLUNG

Wenn sich megapolitische Bedingungen so stark verändern, wie sie es jetzt tun, verändert sich die Organisation der Regierung ebenfalls unweigerlich. Tatsächlich war die Form der repräsentativen Regierung traditionell ein Artefakt der Verteilung von roher Macht. Dies wird durch die Tatsache gezeigt, dass Vertreter auf geographischer Basis ausgewählt werden, und nicht auf irgendeine andere Weise.

Denken Sie mal darüber nach. Grundsätzlich wäre ein Parlament genauso demokratisch, wenn seine Mitglieder entsprechend einer beliebigen Aufteilung der Bevölkerung ausgewählt würden. Parlamentarische Wahlbezirke oder kommunale Ebenen könnten auf Grundlage von Geburtstagen oder sogar alphabetischen Wahlkreisen gebildet werden. Jeder, der am 1. Januar geboren wurde, könnte aus einer Liste von Kandidaten wählen. Diejenigen, die am 2. Januar geboren wurden, aus einer anderen. Oder jede Person, deren Name mit \"Aa\" bis \"Af\" beginnt, könnte aus einer Liste von Kandidaten wählen. Diejenigen, deren Namen mit \"Ag\" beginnen, würden aus einer anderen wählen. Und so weiter.

Ein solches System existiert aus mehreren Gründen derzeit nicht. Ein erster und ausreichender Grund ist, dass es im 18. Jahrhundert technologisch nicht umsetzbar war. Aber noch wichtiger ist die Tatsache, dass Wahlkreise auf Grundlage von Geburtstagen oder dem Alphabet nicht die Verteilung von roher Macht wiedergegeben oder sich ihr auch nur angenähert hätten, die die Stimme zu dieser Zeit ausdrücken musste. Personen, die nicht mehr als Geburtstage oder die ersten paar Buchstaben ihrer Namen gemeinsam haben, waren und wären immer noch äußerst schwer in irgendeiner kohärenten Machtbasis zu organisieren.

### Warum zählen geografische Querschnitte mehr?

Die Abstimmung begann tatsächlich als ein Stellvertreter für einen militärischen Konflikt. Und auch heute bleibt sie dies, wenn auch in einer verdeckten Art und Weise. Solche Konflikte können entlang geographischer Linien organisiert werden und seltener entlang von Verwandtschafts- oder Religionslinien. Sie können jedoch nicht auf der Grundlage von Geburtstagen oder Anfangsbuchstaben organisiert werden. Auch können sie nicht effektiv nach Berufen organisiert werden, es sei denn, diese Berufe sind in Erbgilden begrenzt, wie die Kasten in Indien, oder regional gruppiert, wie die Landwirte in Iowa.

Der ganze Sinn der aktuellen Formeln der Vertretung besteht darin, dass sie geographisch verankerte Interessen repräsentieren, anstatt entlang einer anderen Dimension. Historisch gesehen war der Schlüssel zum militärischen Erfolg die Kontrolle über Territorium. Alle militärischen Bedrohungen haben sich lokal gebildet. Repräsentative Systeme sind darauf ausgelegt, einen anderen Schauplatz für den Ausdruck dieser Macht zu bieten. Die Tatsache, dass sie unweigerlich dazu neigen, lokale Interessen zu fördern, ist ein Artefakt der Vertretungsformel. Geographische Wahlkreise veranlassen Vertreter dazu, spezielle Gruppen auf Kosten der allgemeinen Interessen zu bevorzugen, die alle Bewohner eines Landes teilen.

### Neue Möglichkeiten voraus

Wie Analysen von Public-Choice-Ökonomen gezeigt haben, haben scheinbar geringfügige Veränderungen in der Form, in der eine Wahl strukturiert ist, oder in der Art und Weise, wie die Stimmen berechnet werden, große und vorhersehbare Auswirkungen auf das Ergebnis. [^436] Aus diesem Grund müssen ernsthafte Studenten von Politikwissenschaften heute auch ernsthafte Studenten von Verfassungen sein. Und es ist eine der Überlegungen, die uns dazu veranlasst haben, über Verfassungen hinaus auf die ultimative Metaverfassung zu schauen, die durch die vorherrschenden megapolitischen Faktoren eines bestimmten Umfelds bestimmt wird.

Technologischer Wandel hat bereits einige der Grundlagen dafür beseitigt, dass die Wahl auf geographische Wahlkreise begrenzt ist. Als die modernen repräsentativen Systeme im achtzehnten und neunzehnten Jahrhundert entstanden, waren fast alle Kommunikationen lokal. Die meisten Menschen lebten und starben innerhalb weniger Kilometer von ihrem Geburtsort, und ihr gesamter Handel und ihre Kommunikation wurden lokal abgewickelt. Heute gibt es weltweite Sofortkommunikation. Man kann mit jemandem fünftausend Kilometer entfernt nahezu genauso leicht Geschäfte machen wie mit einem Nachbarn. In zunehmendem Maße überwindet die Wirtschaft geographische Einschränkungen. Die Gesellschaft ist viel mobiler geworden.

Und so ist es auch mit dem Reichtum im Informationszeitalter. Im Unterschied zu einem Stahlwerk kann ein Computerprogramm kaum dem hiesigen politischen Prozess zum Opfer fallen. Ein Stahlwerk kann nicht einfach umziehen, wenn Gesetzgeber sich entscheiden, es zu besteuern oder seine Besitzer zu regulieren. Ein Computerprogramm hingegen kann per Modem mit Lichtgeschwindigkeit rund um die Welt übertragen werden. Der Besitzer kann seinen Laptop packen und losfliegen. Auch das untergräbt die megapolitischen Grundlagen von geografischen Wahlkreisen.

Ein wesentliches Problem, das alle repräsentativen Demokratiesysteme in Anbetracht unserer Analyse teilen, ist, dass ihre geografischen Wahlkreise zwangsläufig die etablierten Interessen von Unternehmen des Industriezeitalters überrepräsentieren. Die „Verlierer" oder „Zurückgebliebenen" sind perfekte Wähler, geografisch konzentriert und politisch bedürftig. Die Geschichte der Industriedemokratie bestätigt dies. Die „Gewinner" der neuen Industrien waren in den gesetzgeberischen Beratungen selbst in der Hochphase des Industriezeitalters in den 1930er Jahren chronisch unterrepräsentiert. [^437] Die Tendenz der Politiker, die bestehenden, etablierten Mitbewerber zu vertreten und nicht die neu entstehenden Unternehmen oder die potenziellen Kunden dieser Unternehmen, ist wahrscheinlich ein inhärentes Merkmal der repräsentativen Regierung. Wie Mancur Olson in *The Rise and Decline of Nations* argumentierte, neigen langjährige Branchen dazu, effektivere „Verteilungskoalitionen" zu entwickeln, um Lobbyarbeit zu betreiben und um politische Beute zu kämpfen. [^438]

In der Wirtschaft des Informationszeitalters verschärft sich dieses Prinzip ins Unermessliche. Die kreativeren Teilnehmer an der neuen Wirtschaft sind geografisch verteilt. Daher ist es unwahrscheinlich, dass sie eine ausreichende Konzentration bilden, um die Aufmerksamkeit von Gesetzgebern zu erregen, so wie es die Lachsfischer in Schottland oder die Weizenbauern in Saskatchewan tun. Tatsächlich ist es unwahrscheinlich, dass viele der dynamischen Persönlichkeiten der neuen Wirtschaft Bürger selbst der umfassendsten Gerichtsbarkeit sind. Daher werden sie kaum eine „Stimme" in den legislativen Beratungen von repräsentativen Demokratien haben. Als anschauliches Beispiel betrachten Sie die fragwürdigen Bemühungen amerikanischer Mathematik-Promovierender, ausländische Mathematiker daran zu hindern, Arbeitsplätze in den Vereinigten Staaten anzunehmen. [^439] Ihre fremdenfeindlichen Forderungen an den Kongress, die Arbeitgeber daran hindern sollen, Mitarbeiter auf der Grundlage ihrer Verdienste einzustellen, werden mit großer Wahrscheinlichkeit Gehör finden. Die antiquierte geografische Vertretung, die aus dem Industriezeitalter übriggeblieben ist, nimmt keine Rücksicht auf ausländische Mathematiker oder andere wichtige Wohlstandsbringer, die keine Wähler sind.

„Warum glauben Menschen an die Legitimität demokratischer Institutionen? Die Beantwortung dieser Frage ist fast ebenso schwierig wie die Erklärung dafür, warum Menschen an bestimmte religiöse Dogmen glauben. Denn wie bei religiösen Glaubensvorstellungen variiert das Verständnis, der Skeptizismus und der Glaube stark innerhalb der Gesellschaft und über die Zeit hinweg." [^440] - Juan J. Linz

Wenige haben begonnen, auf konzertierte Weise über die Folgen des technologischen Wandels nachzudenken, der den Industrialismus untergräbt und die Einkommensverteilungen verändert. Offensichtlich wird die Demokratie wahrscheinlich nicht viel mehr als ein Rezept für legalisierten Parasitismus sein, wenn Einkommen so stark divergieren, wie sie es in der Informationswirtschaft könnten. Noch weniger Menschen haben die angedeutete Unverträglichkeit zwischen einigen Institutionen der Industrieregierung und der Megapolitik der postindustriellen Gesellschaft bemerkt. Ob diese Widersprüche nun explizit anerkannt werden oder nicht, ihre Auswirkungen werden immer offensichtlicher, wenn Beispiele für politisches Scheitern sich weltweit häufen. Regierungsinstitutionen, die in der Moderne entstanden sind, spiegeln die megapolitischen Bedingungen von vor einem oder mehreren Jahrhunderten wider. Sie überlebten den Übergang von der Agrargesellschaft zum urbanen Industrialismus. Aber das Informationszeitalter könnte neue Mechanismen der Repräsentation erfordern, um chronische Dysfunktion und sogar einen Zusammenbruch im Stil der Sowjetunion zu vermeiden.

Man kann erwarten, dass Krisen der Fehlregierung in vielen Ländern auftreten, da politische Versprechen entwertet werden und den Regierungen der Kredit und die institutionelle Unterstützung ausgehen. Letztlich werden neue institutionelle Formen entstehen müssen, die in der Lage sind, die Freiheit unter den neuen technologischen Bedingungen zu bewahren und gleichzeitig die gemeinsamen Interessen der Individuen zum Ausdruck und zum Leben zu bringen.

All dies deutet auf das Ende der Massendemokratie hin, wie wir sie im zwanzigsten Jahrhundert kannten. Die Frage ist: Was wird an ihre Stelle treten? Wenn die einzige Alternative zur Massendemokratie eine Diktatur wäre, in der der Einzelne kein Mitspracherecht über sein Schicksal hat, könnte man versucht sein, sich der „Revolte gegen die Zukunft" der Neo-Ludditen anzuschließen.

### Neue Institutionen

Glücklicherweise ist die Diktatur jedoch nicht die einzige Alternative zur Massendemokratie. Informationstechnologie ermöglicht Wahlmöglichkeiten. Statt kollektiver Entscheidungen im eingeschränkten Kontext der „Massenproduktion, Massenkonsum, Massenbildung, Massenmedien, Massenunterhaltung und all dem Anderen", wird die Informationstechnologie echte, kundenspezifische Souveränitätsdienstleistungen ermöglichen. Dies wird möglich sein, weil es nicht mehr zwingend notwendig sein wird, in großem Maßstab zu arbeiten. Wir glauben, dass die Technologie des Informationszeitalters neue Formen des Regierens hervorbringen wird - so wie die landwirtschaftliche Revolution und später das Industriezeitalter ihre eigenen, unverwechselbaren Formen der sozialen Organisation hervorgebracht haben.

Wie könnten solche neuen Institutionen aussehen? Um das zu verstehen, müssen Sie alles vergessen, was Sie in falsch benannten „politikwissenschaftlichen" Texten lesen. Die neuen Institutionen des Regierens für das Informationszeitalter werden die Grenzen des herkömmlichen Denkens überschreiten. Die Entwicklung hin zu solchen Institutionen des neuen Zeitalters hat bereits begonnen. Es handelt sich um wenig beachtete Improvisationen zur Umstrukturierung unzureichend genutzter Güter, nämlich der Vorteile der Souveränität. Die Nationalstaaten der Welt, die ängstlich auf die Sezessionsbewegungen und die mächtigen Kräfte der Dezentralisierung blicken, haben sich zusammengetan, um das stärkste Kartell zu bilden, das sie durchsetzen können. Während die Zahl der neuen Staaten in der Welt in den 1990er Jahren zugenommen hat, geschah dies hauptsächlich in zwei Gruppen, dank des Zusammenbruchs der multiethnischen kommunistischen Diktaturen in der ehemaligen Sowjetunion und Jugoslawien. Es ist bemerkenswert, dass andere führende Nationalstaaten, einschließlich der Vereinigten Staaten, sich bemühten, die Sowjetunion so lange wie möglich zu erhalten. Und nur wenige Regierungen begrüßten den Zerfall Jugoslawiens. Die Unabhängigkeit der ehemaligen jugoslawischen Republiken wurde erst anerkannt, nachdem die Sezessionisten die Kontrolle errungen hatten, die sie durch eigene militärische Anstrengungen durchsetzen konnten. Die führenden Mächte gaben sich damit zufrieden, dass unbewaffnete oder schlecht bewaffnete Separatisten von ihren serbischen Peinigern abgeschlachtet wurden. Selbst das ferne China, ein mächtiger Nationalstaat, der kein unmittelbares Interesse an der Erhaltung des jugoslawischen Rumpfes hatte, widersetzte sich energisch den Bemühungen um die Selbstbestimmung der unterdrückten ethnischen Albaner im Kosovo. Ironischerweise ist es wahrscheinlicher, dass dieser Fetisch der Grenzbefestigung den Weg zu einer zersplitterten Souveränität diktiert, als dass er eine Dezentralisierung tatsächlich verhindert. Der erbitterte Widerstand schwacher Nationalstaaten auf der ganzen Welt gegen offene Sezession und politische Aufspaltung macht anerkannte Souveränität zu einer wertvollen Form transzendentalen Kapitals, das von den Staaten, die es besitzen, freiwillig fragmentiert und untervermietet werden kann.

Ein Beispiel dafür, wie Souveränität freiwillig fragmentiert werden kann, um eine im Wesentlichen private, steuerfreie Gerichtsbarkeit zu schaffen, ist die Agulhas Bay Concession Free Zone, die fünfzig Quadratkilometer der Insel Príncipe vor der Küste Westafrikas umfasst. Obwohl das Gebiet innerhalb der Grenzen der Demokratischen Republik Sao Tomé und Príncipe bleibt, ist die Verwaltung der Zone privatisiert. Die Verwaltung wird durch einen Vertrag geregelt, der von der WADCO, der West African Development Corporation Ltd. verwaltet wird, einem privaten Unternehmen mit Sitz in Südafrika. Die Amtssprache in der Zone ist nicht die offizielle toméanische Sprache Portugiesisch, sondern Englisch. Die offizielle Währung ist nicht das toméanische Monopol-Geld, die Dobra, sondern das Geld der Welt, der US-Dollar. Für die Sicherheit sorgen nicht die Polizeikräfte der Demokratischen Republik São Tomé und Príncipe, sondern private Polizisten, die von der WADCO beschäftigt werden. Das são-toméische Handelsrecht ist auf Handelsgeschäfte innerhalb der Zone nicht anwendbar und die são-toméischen Gerichte sind nicht zuständig. Alle Streitigkeiten müssen durch ein transnationales Schiedsverfahren nach den Pariser ICC-Regeln beigelegt werden. Abgesehen von einigen streng geregelten und unbedeutenden Ausnahmen gelten in der Zone weder são-toméische Steuern noch offizielle Monopole. Die Telekommunikation zum Beispiel ist innerhalb der Zone automatisch dereguliert. Vorbehaltlich der Zahlung des Pachtzinses und der Einhaltung anderer Konzessionsbedingungen ist WADCO berechtigt, den Pachtvertrag über die private, fragmentierte Souveränität automatisch und wiederholt um fünfzig Jahre zu verlängern, beginnend mit dem ersten Verlängerungsdatum im Jahr 2047.

Was WADCO in Sao Tomé und Principe erreicht hat, können und werden andere in vielen verschiedenen Ländern nachahmen. Einer der wahren Pioniere des 21. Jahrhunderts, Joaquin Aguirre, hat eine ähnliche Zone privater Souveränität in der Central Aguirre Portuaria im Osten Boliviens geschaffen. Aguirre, ein Multimillionär, Schriftsteller und Erfinder, Mitbegründer der Vereinten Nationen und ehemaliger Senator der bolivianischen Republik, ist in mehrfacher Hinsicht ein Pionier. Ein halbes Jahrhundert, nachdem er die Vereinten Nationen mitbegründet hat, ist Aguirre nun der Prototyp des souveränen Individuums des 21. Jahrhunderts. Seine Zona Franca, die frei von den meisten bolivianischen Steuern, Zöllen und behördlichen Auflagen ist, weist den Weg zu der neuen Form des privatisierten Stadtstaates, den erfolgreiche Einzelpersonen im Informationszeitalter zunehmend erreichen werden. Es zeigt auch eindeutig, dass das Leben der Massen, das von den Apologeten von großen Regierungen so oft gepriesen wird, durch die wirtschaftliche Entwicklung, die durch Freihandelszonen wie die von Señor Aguirre ins Leben gerufen und katalysiert wird, dramatisch verbessert werden kann. Im Laufe der Zeit wird sich die Zahl der De-facto-Stadtstaaten auf der Welt erheblich vervielfachen. Wenn Sie als Einzelperson eine ausreichende finanzielle Unabhängigkeit erreichen, werden Sie in der Lage sein, die endgültige Unabhängigkeit zu erlangen, wie Joaquin Aguirre. Für den Fall, dass Ihnen kein anderes Stück zersplitterter, kommerzialisierter Souveränität eine bequeme Heimat bietet, können Sie Ihren eigenen proprietären Ministaat gründen, der so unabhängig ist wie jedes Herzogtum des Mittelalters. Anstatt mit Demagogen und politischen Schreiberlingen Tauziehen zu spielen, um zu verhindern, dass Ihr Vermögen den vielen zeternden Händen der Massendemokratie entrissen und unter ihnen aufgeteilt wird, können Sie Ihr eigenes privates Reich der Herrschaft errichten.

Der dramatische Phasenwechsel von der Massendemokratie zur ultimativen Form der Selbstverwaltung, der individuellen Souveränität, muss weder einen radikalen Wandel der öffentlichen Meinung noch ein wundersames Votum enttäuschter Wähler voraussetzen, die sich für die Abschaffung der Massendemokratie entscheiden. Eine solche Revolution kann beginnen, ja sie hat bereits begonnen, unsichtbar, mit der Verpachtung von Hoheitsgebieten zur Nutzung als steuerfreie Zonen, „Zona Francas" und Freihäfen. Zu gegebener Zeit wird die Souveränität immer wieder zersplittert, bis sie so zerklüftet ist, dass eine weitere Aufteilung keinen ausreichenden Wert mehr hätte, um die Transaktionskosten der Dezentralisierung auszugleichen. Angesichts des Moore'schen Gesetzes und des Gilder'schen Korollariums, wonach sich die Bandbreite jedes Jahr verdreifacht, gibt es derzeit keinen Grund, ein baldiges Ende des Dezentralisierungstrends vorauszusehen. Im Gegenteil, wir gehen davon aus, dass die scheinbar solide Macht der Nationalstaaten, die sich derzeit der Massendemokratie verschrieben hat, in Zehntausende von Fragmenten in ein System zersplittern wird, das mehr an das Mittelalter als an das moderne Industriezeitalter erinnert.

Zu gegebener Zeit werden selbst Nationalstaaten, die noch über Rumpfinstitutionen der Massendemokratie verfügen, einen bedeutenden Politikwandel erleben, um sich den neuen metakonstitutionellen Realitäten anzupassen. Wie William Keech, ein treuer Verfechter der Demokratie, in *Economic Politics: The Costs of Democracy* argumentiert: „Die Menschen lernen zu wollen, das bekommen zu können, was sie sehen, aber sie können auch ihre Meinung ändern, wenn sie sehen, dass ihnen nicht gefällt, was sie wollten und was sie bekommen haben." [^441] Mit anderen Worten: Die Tatsache, dass die Massendemokratie mit konventionellen Institutionen der repräsentativen Regierung am Ende des zwanzigsten Jahrhunderts überall bejubelt wird, könnte ein „Verkaufssignal" sein. Sie ist keineswegs eine Garantie dafür, dass solche Entscheidungsregeln den Test der Zeit bestehen werden, nicht einmal unter ihren eigenen Bedingungen. Denken Sie daran, dass es außerhalb der Politik kaum Anzeichen dafür gibt, dass Führungskräfte, Verwaltungsangestellte, Trainer oder andere professionelle Führungskräfte auf demokratische Weise ausgewählt werden. Im Gegenteil, die erfolgreichsten Führungspersönlichkeiten werden regelmäßig von den Eigentümern im Rahmen von Auswahlverfahren eingestellt, bei denen diejenigen, deren Interessen am stärksten im Vordergrund stehen, ein ungleiches und unverhältnismäßig großes Mitspracherecht bei der Bestimmung des Ergebnisses haben. Wenn die demokratische Auswahl wirklich eine überlegene Methode wäre, um kompetente Führungskräfte zu finden, würde man erwarten, dass sie als universelle Entscheidungsregel gilt. Stattdessen ist sie fast ausschließlich auf den politischen Bereich beschränkt. Kurz gesagt, die Annahme, dass die Erbringung hoheitlicher Dienstleistungen durch die Dominanz demokratischer Entscheidungsfindung behindert wird, ist nach den derzeitigen Erkenntnissen vernünftiger als die gegenteilige Annahme, dass Unternehmen und Wirtschaftsorganisationen darunter leiden, dass sie von Führungskräften geleitet werden, die von den Eigentümern eingesetzt werden, anstatt per Handzeichen.

Bis Mitte des 21. Jahrhunderts wird die Ausbreitung proprietärer Gerichtsbarkeiten mit zersplitterter Souveränität wahrscheinlich die Vorteile der proprietären Verwaltung endgültig demonstriert haben. Die Wähler werden sehen, dass sie darunter leiden, dass ihnen die Massendemokratie aufgebürdet wird. Daher werden sie, wie Professor Keech vorschlägt, zu der Einsicht gelangen, dass die Vorteile, die sich aus der Kontrolle der Regierung durch die Arbeitnehmer ergeben, durch deren Kosten aufgewogen werden. Sie werden zu Reformen übergehen. Sogar die Wähler in Europa und Nordamerika, die jetzt so stark gegen Reformen eingestellt zu sein scheinen, könnten schließlich dafür stimmen, dass ihre Regionen der Eigenverwaltung mehr entgegenkommen. Mehrheiten könnten bereitwillig, ja sogar mit Freude die Farce der Politik zugunsten einer eigenverantwortlichen Regierungsführung aufgeben, die tatsächlich darauf abzielt, optimale Bedingungen für den Abschluss und die Durchsetzung von Verträgen zu schaffen.

Sofern die Regierung mit ihren fadenscheinigen Ausstattungen überhaupt überlebt, kann sie auf völlig neue Weise informiert werden. Irgendwo, in irgendeinem Rechtssystem, irgendwann vor dem Jüngsten Tag, wird jemand das Potential erkennen, das die Computertechnologie bietet, um eine wirklich repräsentative Regierung zu ermöglichen. Das vermeintliche Problem hoher Ausgaben für Wahlkampagnen und die zweifellos störenden Dauerkampagnen könnten im Handstreich gelöst werden. Anstatt gewählt zu werden, könnten Vertreter vollkommen zufällig durch Losverfahren ausgewählt werden, mit einer hohen statistischen Wahrscheinlichkeit, dass ihre Talente und Ansichten denen der breiten Bevölkerung entsprechen.

Dies wäre lediglich eine moderne Version des antiken griechischen Systems der Auswahl durch Los. Wie E. S. Staveley in seiner autoritativen Geschichte griechischer und römischer Wahlen und Abstimmungen ausführlich beschreibt, wurden in Athen zahlreiche Ämter, von den Magistraten bis zu den Archonten, durch Losentscheid als Ersatz für Wahlen besetzt. Dies wurde geschickt erreicht, trotz mechanischer Einschränkungen bei der Zufälligkeit der Chancen, durch die Verwendung einer Losmaschine „oder, wie die Athener sie nannten, das Kleroterion." [^442]

Eine Reihe von schwarzen und weißen Bohnen wurden als zufällige Zählmarken verwendet, um zu bestimmen, wer ausgewählt würde, um verschiedene Ämter zu besetzen, sowie um „die Reihenfolge zu bestimmen, in der die Stammesabschnitte im Rat ihre Runden als Prytanen machen würden." [^443] Die klassische Herkunft dieser Idee könnte ihr zusätzliche Glaubwürdigkeit verleihen. Aber ihre Hauptattraktivität besteht genau darin, dass sie die Nachteile der Selbstauswahl in der Politik vermeiden würde. Sie würde statistisch sicherstellen, dass weniger Anwälte und Egomanen das öffentliche Geschäft monopolisieren.

Die Parlamente könnten aus echten Vertretern zusammengesetzt sein. Da sie nicht durch eine Machtsuche zusammengeführt würden und sie ohnehin nur eine sehr geringe Chance hätten, erneut per Losverfahren ausgewählt zu werden, wären sie frei, die Regierungsgeschäfte zu führen und Politiken auf der Grundlage einer rationalen Analyse der Angelegenheiten zu formulieren.

### Direkte Provision

Heutzutage haben Politiker, die darauf bedacht sind, Stimmen zu optimieren, wenig Anreiz, Probleme kohärent zu analysieren. Es ist deshalb kaum verwunderlich, dass ihre Erfolgsbilanz bei der eigentlichen Problemlösung im Vergleich zu Unternehmern, Geschäftsführern und Trainern von Sportteams, die nach ihrer Leistung belohnt werden, so armselig ist. Eine leistungsbezogene Vergütung für Gesetzgeber würde nicht jeden zufällig Ausgewählten so effizient machen wie Lee Kuan Yew. Es gibt jedoch allen Grund zu der Annahme, dass die Leistung deutlich verbessert würde, wenn das Gehalt der Gesetzgeber an eine objektive Leistungsmaßnahme, wie beispielsweise das Wachstum des Pro-Kopf-Einkommens nach Steuern, gekoppelt wäre. Wenn man sie nach Leistung bezahlt, steigt die Wahrscheinlichkeit, dass sie Leistung erbringen, um ein Tausendfaches.

Der Gewinn für die Gesellschaft durch Politiken, die das reale Einkommen abzüglich Steuern verbessern, könnte enorm sein. Warum also nicht Premierminister und Präsidenten sogar einen winzigen Anteil des Gewinns zahlen, den ihre Politiken fördern? Die Mittel für solche Zahlungen könnten durch eine kleine, unauffällige Steuer erhoben werden. Eine solche Regelung würde die Gesellschaft von der Bedrohung befreien, der sie heute durch ehrgeizige Männer mit besonderen politischen Fähigkeiten wie Richard Nixon und Bill Clinton ausgesetzt ist.

> „Sie brachten ihm Gold, Silber und Kleidung; aber der ‚Christ' verteilte all diese Dinge an die Armen. Wenn Geschenke angeboten wurden, verneigten sich er und seine Gefährtin und sprachen Gebete aus; aber dann erhob er sich und befahl der Versammlung, ihn anzubeten. Später organisierte er eine bewaffnete Bande, die er durch die Landschaft führte, raubte Reisende, die sie auf dem Weg trafen, aus. Aber auch hier war sein Ehrgeiz nicht, reich zu werden, sondern angebetet zu werden. Er verteilte alle Beute an diejenigen, die nichts hatten, einschließlich, so darf man annehmen, seiner eigenen Anhänger." [^444] Norman Cohn

### Messianische Persönlichkeiten

Es wurde zu wenig beachtet, dass die Wahlpolitik gestörte, messianische Persönlichkeiten in Machtpositionen lockt. Solche Personen existierten und stellten oft ernsthafte Bedrohungen für die soziale Ordnung dar, sogar in Agrargemeinschaften vor dem Aufkommen demokratischer politischer Systeme. Wenn man die Karrieren von Eudo de Stell, dem Bretonischen Christus, Adelbert im 8. Jahrhundert, Eon im 11. Jahrhundert, Tanchelm von Antwerpen, Melchior Hoffman und Bernt Rothmann und ihren Gleichgesinnten betrachtet, sticht einiges hervor. Je offensichtlicher ihre politischen Talente zu sein scheinen, desto größer scheint der Schaden zu sein, den sie verursacht haben. Da der Staat noch nicht damit beschäftigt war, weit verbreitete systematische Zwangsmaßnahmen zu organisieren, nahmen diese frühen Protopolitiker es oft auf sich, zu rauben und zu plündern, um Geld zu beschaffen, das sie an ihre Anhänger unter den Armen verteilen konnten.

### Protopolitiker in Aktion

Die Geschichten ihrer Eskapaden vermitteln einen Eindruck von Talenten, die ihrer Zeit voraus waren, als würde man von zwei Meter großen Männern lesen, die einen Platz hoch und runter laufen, bevor Basketball erfunden wurde. Heute, dank der NBA, verdienen außergewöhnlich groß gewachsene Männer Millionen, indem sie dribbeln und dunken. Würde es Basketball nicht mehr geben, würden sie wieder in die Nischen der Gesellschaft zurückfallen und wahrscheinlich hauptsächlich als Attraktionen im Zirkus und in Schaubuden auftreten.

Bevor die Politik erfunden wurde, wurden Demagogen zur nächsten Annäherung von Politik gezogen, die die agrarische Welt zu bieten hatte: Wanderpredigt. Sie hielten Reden vor Menschenmengen und versprachen wie Politiker denen, die ihnen folgen würden, ein besseres Leben. Damals wie heute waren die Armen die Hauptziele der Demagogen. Norman Cohns große Geschichte der Jahrtausendbewegungen, die Suche nach dem Millennium, erzählt die Karrieren zahlreicher messianischer Führer bevor es Wahlumfragen gab. In seinen Beschreibungen ist es leicht, die starken Ähnlichkeiten im Persönlichkeitstyp mit dem charismatischen Politiker der Moderne zu erkennen.

> Der Anführer hat - wie der Pharao und viele andere „göttliche Könige" - alle Attribute eines idealen Vaters: Er ist vollkommen weise, er ist vollkommen gerecht, er schützt die Schwachen. Aber andererseits ist er auch der Sohn, dessen Aufgabe es ist, die Welt zu verändern, der Messias, der einen neuen Himmel und eine neue Erde schaffen soll und von sich selbst sagen kann: „Sieh her, ich mache alles neu!" Und sowohl als Vater als auch als Sohn ist diese Figur kolossal, übermenschlich, allmächtig. Ihm werden so viele übernatürliche Kräfte zugeschrieben, dass man sich vorstellt, sie strömten wie Licht hervor. ... Darüber hinaus besitzt der eschatologische Anführer durch die Fülle dieses göttlichen Geistes einzigartige wundertätige Kräfte. Seine Armeen werden stets triumphierend und siegreich sein. Seine Anwesenheit wird die Erde Ernten hervorbringen lassen, seine Herrschaft wird ein Zeitalter vollkommener Harmonie sein, wie die alte, korrupte Welt es nie gekannt hat.
>
> Dieses Bild war natürlich ein rein fantastisches, im Sinne, dass es keinen Bezug zur wirklichen Natur und Fähigkeit eines Menschen hatte, der jemals existierte oder existieren könnte. Nichtsdestotrotz war es ein Bild, das auf einen lebenden Menschen projiziert werden konnte; und es gab immer Männer, die mehr als bereit waren, eine solche Projektion anzunehmen, die tatsächlich leidenschaftlich darauf brannten, als unfehlbare, wundertätige Erlöser gesehen zu werden. ... Und das Geheimnis der Vorherrschaft, die sie ausübten, lag weder in ihrer Herkunft noch zu einem großen Teil in ihrer Bildung, sondern immer in ihren Persönlichkeiten. Zeitgenössische Berichte über diese Messiasse der Armen betonen häufig ihre Beredsamkeit, ihre beherrschende Haltung und ihr persönliches Charisma. Vor allem hat man den Eindruck, dass sogar wenn einige dieser Männer möglicherweise bewusste Betrüger gewesen sein könnten, die meisten von ihnen sich wirklich als inkarnierte Götter sahen. . . . Und diese totale Überzeugung würde sich leicht genug den Massen mitteilen, deren tiefstes Verlangen sich genau nach so einem eschatologischen Erlöser sehnte. [^445]

Obwohl dieser Abschnitt wunderbar prägnant die selbsternannten Weltuntergangsretter beschreibt, die häufig die mittelalterliche Gesellschaft aufwühlten, kann er nicht das volle Ausmaß von Cohns meisterhafter Untersuchung wiedergeben. Man kann das gesamte Werk nicht lesen, ohne in den Possen dieser Propheten die bekannten Eigenschaften des modernen Demagogen zu erkennen: die Beredsamkeit, die „persönliche Ausstrahlung", die „messianischen Ansprüche" und das wiederkehrende Verlangen, als Volkstribun der Armen verehrt zu werden.

Der Hauptunterschied zwischen der Rezeption dieser Hochstapler durch die mittelalterliche Gesellschaft und der durch die Demokratie am Ende des 20. Jahrhunderts besteht darin, dass solche Personen im Mittelalter in der Regel hingerichtet wurden, während die moderne demokratische Politik ihnen am Ende des 20. Jahrhunderts einen offenen Kanal bereitstellt, um auf legitime Weise die Macht des Nationalstaats zu ergreifen.

Ein System, das routinemäßig die Kontrolle über die größten, tödlichsten Unternehmen auf der Erde dem Gewinner von Beliebtheitswettbewerben zwischen charismatischen Demagogen übergibt, wird auf lange Sicht darunter leiden.

### Bezahlt die Führungskräfte dafür, gute Arbeit zu leisten

Wie oben angedeutet, wäre es ein Leichtes, eine überlegene Methode zur Gewinnung talentierter Führungskräfte für eine Organisation festzulegen: die Einstellung von Führungskräften. Dies ist die Methode, die in wettbewerbsfähigen Volkswirtschaften am häufigsten und erfolgreichsten eingesetzt wird. Ein rationaler Auswahlprozess in Verbindung mit einer konstruktiven Anreizstruktur zur Belohnung positiver Führung würde fähige Leute an die Spitze der Regierung bringen. Es würde auch neue Arten von Talenten mobilisieren, die sich sonst nicht für die Probleme des Regierens interessieren würden.

Die talentiertesten Führungskräfte der Welt könnten dazu verleitet werden, strauchelnde Regierungen zu übernehmen, wenn sie auf der Grundlage der Ergebnisse vergütet würden, die sie tatsächlich für die Gesellschaft erzielen. Ein Anführer, der in der Lage wäre, das reale Einkommen in irgendeiner führenden westlichen Nation signifikant zu steigern, könnte mit Recht weitaus mehr verdienen als Michael Eisner. In einer besseren Welt wäre jeder erfolgreiche Regierungschef ein Multimillionär.

### Elektronische Volksentscheide

Eine offensichtliche Alternative zur repräsentativen Fehlregierung wäre die Durchführung von elektronischen Volksabstimmungen, bei denen Bürger, möglicherweise eine repräsentative Auswahl, die durch manipulationssichere Auslosungen ausgewählt wurde, ihre Stimmen direkt zu gesetzgeberischen Vorschlägen abgeben könnten. Computertechnologie ermöglicht es, Entscheidungen demokratisch zu treffen, mit elektronischen Volksabstimmungen. Volksabstimmungen könnten leicht mit Zuweisungen verknüpft werden, um die Anzahl der Stimmen zu bestimmten Fragen zu verringern. Grundsätzlich ist es für die Wählerschaft weniger herausfordernd, politische Fragen zu verstehen, als zu versuchen, Politiker zu durchschauen und die Beurteilungen dieser Politiker zu den gleichen Fragen zu bewerten, ganz zu schweigen davon, zu wissen, was diese Politiker tatsächlich tun würden, wenn sie ihr Amt antreten. Dies ist besonders schwierig, da Politiker und ihre Teams zunehmend geschickter darin werden, die Bilder, die sie der Öffentlichkeit präsentieren, zu verpacken und zu manipulieren.

## KOMMERZIALISIERTE SOUVERÄNITÄT

Wir erwarten, dass etwas Neues entsteht, um die Politik zu ersetzen. Obwohl alle Möglichkeiten, die wir oben diskutiert haben, mit einigem Vorteil erprobt werden könnten, erwarten wir nicht, dass die Politik reformiert oder verbessert wird, sondern dass sie überholt und in den meisten Aspekten aufgegeben wird. Damit meinen wir nicht, dass wir eine Diktatur erwarten, sondern eine unternehmerische Regierung - die Kommerzialisierung der Souveränität.

Im Gegensatz zur Diktatur oder sogar zur Demokratie wird die kommerzialisierte Souveränität nicht die Wahlfreiheit einschränken. Sie wird jedem Einzelnen mehr Spielraum bieten, seine Meinungen auszudrücken. Und für diejenigen, die das Talent haben, es für sich zu nutzen, wird die kommerzialisierte Souveränität mehr praktischen Spielraum für Entscheidungsfindung und Selbstbestimmung erlauben als jede Form von sozialer Organisation, die bisher existiert hat.

### Kundengerechte Regierung

Damit dies nicht so nach 2000 klingt, sollte man bedenken, dass die Mikrotechnik miniaturisiert und disaggregiert. Sie erleichtert die Anpassung an Kundenwünsche statt an die Massenproduktion. Man kann nun in ein Geschäft gehen und Jeans kaufen, die nach einem Muster geschnitten sind, das an die eigenen Maße angepasst und dann auf der anderen Seite der Welt genäht wird. Wenn neue Institutionen endlich entstehen, um sich den neuen megapolitischen Realitäten des Informationszeitalters anzupassen, werden Sie in der Lage sein, eine Regierungsführung zu erhalten, die mindestens so gut auf Ihre persönlichen Bedürfnisse und Geschmäcker zugeschnitten ist wie Jeans.

Ausgerechnet Alvin Toffler hat die Idee kritisiert, dass die Informationstechnologie die Bürger zu Kunden machen könnte. Toffler sagt, unserer Meinung nach falsch: „Das ist ein viel zu enges Modell. Ob es uns gefällt oder nicht, es gibt eine Welt voller Religion und Gefühl, die nicht einfach auf Vertragsbeziehungen reduziert werden kann." [^446] Aus Gründen, die wir zuvor erörtert haben, stimmen wir zu, dass es schwierig sein wird, „die Welt nationalistischer Empfindungen" auf „Vertragsbeziehungen" zu reduzieren. Aber das heißt nicht, dass es unmöglich ist, und schon gar nicht, dass es eine schlechte Lösung wäre. Etwas weniger irrationale Begeisterung für den Nationalismus könnte Millionen von Menschenleben retten.

### „Eintritt, Austritt" und „Stimme"

Natürlich ist die Kommerzialisierung der Souveränität ein unvertrautes Konzept, anscheinend sogar für Alvin Toffler. Aber seine zentrale Idee - der wirtschaftliche Ausdruck - ist für die Menschen, die am Ende des 20. Jahrhunderts leben, alltäglich. In jeder auch nur teilweise freien Wirtschaft können Verbraucher ihre Wünsche direkt durch den Kauf von Dienstleistungen und Produkten zum Ausdruck bringen. Oder durch das Entziehen ihrer Kundschaft. Wenn Sie mit einer Version eines Produkts oder einem Anbieter eines Dienstes unzufrieden sind, können Sie Ihre Unzufriedenheit durch den „Austritt" direkt zum Ausdruck bringen. Mit anderen Worten, Sie können Ihr Geschäft woandershin verlegen.

In den vorherigen Kapiteln haben wir analysiert, wie der Fortschritt der Informationstechnologie es bald ermöglichen wird, dass Sie Vermögenswerte im Cyberspace erstellen können, die nahezu sicher vor räuberischen Überfällen von Nationalstaaten sind. Dadurch wird eine *de facto* metakonstitutionelle Anforderung geschaffen, dass die Regierungen Ihnen tatsächlich einen zufriedenstellenden Service bieten, bevor Sie ihre Rechnungen bezahlen. Warum? Weil die Einkommensbesteuerung in der Praxis fast genauso freiwillig sein wird, wie sie es in der Theorie sein sollte.

### Vermeidung von „schwerfälligen politischen Kanälen"

Im Endeffekt, wenn sich die Informationstechnologie so entwickelt, wie sie könnte, wird sie gewährleisten, dass Regierungen tatsächlich von ihren Bürgern kontrolliert werden. Als Bürgerin oder Bürger haben Sie zuerst hunderte, dann tausende von Möglichkeiten, Ihre Schutzkosten direkt zu senken, indem Sie einen privaten Steuervertrag mit einem Nationalstaat abschließen oder sich vollständig von Nationalstaaten zu entstehenden Mini-Souveränitäten abwenden. Diese „Eintritts-" und „Austritts"-Optionen sind der wirtschaftliche Ausdruck Ihrer Wünsche als Kunde. Mit den Füßen und dem Geld abzustimmen hat den großen Vorteil, dass es zu Ergebnissen führt, die man sich wünscht.

Wie verhalten sich Ihre Einstiegs- und Ausstiegsmöglichkeiten als Kunde zu den politischen Ausdrucksformen in der Demokratie? Personen, die mit einem Produkt oder einer Dienstleistung unzufrieden werden, insbesondere wenn diese von der Regierung angeboten oder stark reguliert wird, können ihrer Meinung eine „Stimme" verleihen, indem sie beispielweise Briefe an den Präsidenten der Vereinigten Staaten schreiben oder versuchen, ein Treffen mit ihrem Abgeordneten oder einem anderen geeigneten gewählten Amtsträger zu erwirken. Manchmal haben solche Liebesbriefe Erfolg. Aber nicht immer. Normalerweise nicht. Wenn sie zunächst keinen Erfolg haben, können Personen, die ihre „Stimme" für Veränderungen einsetzen möchten, dann Demonstrationen organisieren, eine ganzseitige Anzeige in einer Zeitung schalten oder sogar selbst ein öffentliches Amt anstreben.

Die politische Ausdrucksweise bietet zwar die Möglichkeit, sich zu artikulieren und zu reden. Sie bringt jedoch den Nachteil mit sich, dass man nur selten Zufriedenheit erlangen oder seine Position durch eigenes Handeln verbessern kann. Wenn man mit einem minderwertigen Produkt oder einer minderwertigen Dienstleistung der Regierung konfrontiert wird, ist man gezwungen, so lange dafür zu bezahlen, bis man den gesamten politischen Prozess davon überzeugen kann, seiner Forderung nach einer Änderung nachzukommen.

In westlichen Ländern, und mittlerweile praktisch auf der ganzen Welt, hat dies dazu geführt, dass die Notwendigkeit besteht, die Mehrheitsunterstützung eines demokratischen politischen Systems zu sichern. Die Anforderung, eine Mehrheit einzubeziehen, verursacht enorme Transaktionskosten zwischen Ihnen und dem Erreichen dessen, was aller Wahrscheinlichkeit nach ein relativ unkompliziertes und rationales Ziel ist.

Milton Friedman diskutierte die Vorteile der wirtschaftlichen, im Gegensatz zur politischen Ausdrucksweise, um seinen Vorschlag für Bildungsgutscheine in *Capitalism and Freedom* voranzubringen:

> Eltern könnten ihre Ansichten über Schulen direkt ausdrücken, indem sie ihre Kinder von einer Schule abmelden und sie zu einer anderen schicken, in einem viel größeren Ausmaß als es jetzt möglich ist. Im Allgemeinen können sie diesen Schritt zurzeit nur unternehmen, indem sie ihren Wohnort wechseln. Ansonsten können sie ihre Meinungen nur durch umständliche politische Kanäle äußern. [^447]

Albert O. Hirschman, der sich als Parteigänger der Politik äußerte, nahm Anstoß an Friedmans Vorliebe für den „Ausstieg als ‚direkte' Möglichkeit, seine ablehnende Haltung gegenüber einer Organisation zum Ausdruck zu bringen. Eine in Wirtschaftsfragen weniger geschulte Person könnte naiverweise annehmen, dass der direkte Weg, seine Meinung zu äußern, darin besteht, sie zu äußern!" [^448]

Ob es direkter oder effektiver ist, Ihre Meinungen durch Marktmittel auszudrücken, beispielsweise indem Sie Ihre Unterstützung als Kunde äußern oder zurückziehen, oder über „schwerfällige politische Kanäle", ist eine komplexe und umstrittene Frage. Verschiedene Personen werden sie auf unterschiedliche Weise beantworten. Für diejenigen, deren Hauptengagement bei der politischen Meinungsäußerung darin besteht, Leistungen auf Kosten anderer zu fordern, mag der Wechsel zur wirtschaftlichen Ausdrucksform tatsächlich eine trostlose Alternative zum Schreiben an einen Politiker sein, um mehr zu verlangen.

### Wirtschaftlicher Ausdruck und „reziproke Sozialität"

Für diejenigen, die beabsichtigen, ihre Mitmenschen in einer „gegenseitigen" anstatt einer „zwanghaften" oder parasitären Gesellschaft einzubeziehen, eröffnet die wirtschaftliche Ausdrucksform die Aussicht, mit geringerem Aufwand an Zeit und Mühe eine weit größere Zufriedenheit zu erreichen. Trotz Professor Hirschfields Einwänden, lässt sich dies einfach demonstrieren.

Jede wirtschaftliche Ausdrucksform, bestehend aus Eintritt, laufenden Verträgen und Austritt, könnte in eine politische „Stimme" umgewandelt werden, indem eine Vielzahl von Menschen in die Entscheidungsfindung einbezogen wird. Versuchen Sie es doch einfach mal. Alles, was Sie für das Experiment benötigen, sind ein paar hundert Menschen, die das Gefühl haben, dass es in ihrem Leben nicht genug Politik gibt. Anstatt ihr verfügbares Einkommen in Tausenden von Einzelkäufen über ein Jahr hinweg auszugeben, würden sie diese Vielzahl von wirtschaftlichen Entscheidungen in eine Handvoll politischer Entscheidungen umwandeln.

Zu Beginn würden alle zustimmen, ihr verfügbares Einkommen zusammenzulegen und fortan individuelle Käufe zu unterlassen. Anstelle von tausenden von Dollar, die individuell auf tausende Arten ausgegeben werden könnten, erhält jeder eine Stimme oder vielleicht mehrere Stimmen, abhängig von der Anzahl der zu besetzenden Posten. Anstatt jederzeit Geld direkt auszugeben, um das zu bekommen, was man sich wünscht, würde man seine Stimme oder Stimmen bei den wenigen Gelegenheiten abgeben, wenn Wahlen abgehalten werden, um die Repräsentanten zu wählen, die dann entscheiden würden, wie die nun riesige gemeinsame Geldbörse ausgegeben werden sollte.

Sie würden zusammen mit den anderen an dem Konsum dieser Dinge teilhaben, und nur an denen, die das herrschende Gremium im Namen der Mehrheit genehmigt hat.

Erscheint das schon als „schwerfälliger politischer Kanal" zur Meinungsäußerung? Abwarten! Dieses Modell birgt das ganze Potential für Redekunst und Überzeugungsarbeit, wie man es auf nationaler politischer Ebene findet. Und die meiste Aussicht auf Frustration.

Wenn Sie zum Beispiel frischen Brokkoli mögen und die Gruppe eine gewöhnliche Verteilung von Geschmacksvorlieben bei Lebensmitteln hat, sind Sie in Schwierigkeiten. Es ist wahrscheinlich, dass einige oder die meisten der anderen in Ihrer Gruppe es vorziehen würden, mehr von der gemeinsamen Lebensmittelzuteilung für rotes Fleisch als für frisches Gemüse auszugeben. Um zu verhindern, dass das Kantinenkomitee in ein Lagerhaus geht und das gesamte jährliche Gemüsebudget für Dosen-Erbsen und -Mais verpulvert, müssten Sie vielleicht vorstellig werden und Ihre „Stimme" erheben. Sie könnten die Aufmerksamkeit der Gruppe auf die relativen Vorteile lenken, mehr Vitamine und Nährstoffe wie Sulforaphan in Brokkoli zu sich zu nehmen, im Vergleich zu mehr gesättigten Fettsäuren und Cholesterin aus rotem Fleisch.

Wie genau man diesen oder jeden anderen Punkt verständlich macht, ist in diesem konstruierten politischen Modell natürlich ebenso rätselhaft wie für die Befürworter jeder politischen Sache oder Kandidatur. Sie könnten eine Rede halten, aber das setzt natürlich voraus, dass ein guter Teil der Gruppe, die Sie überzeugen müssen, bereits irgendwo versammelt und bereit ist, zuzuhören. Sie könnten Flugblätter drucken, vorausgesetzt, dass die Hausregeln Ihres politischen Spiels eine solche „Wahlkampfausgabe" zulassen. Sie könnten Briefe schreiben. Aber beide Möglichkeiten hängen davon ab, dass die anderen Teilnehmer lesen können.

> „Es zeichnet das Bild einer Gesellschaft, in der die überwiegende Mehrheit der Amerikaner nicht weiß, dass sie nicht die Fähigkeiten besitzen, die sie benötigen, um in unserer zunehmend technologischen Gesellschaft und im internationalen Markt ihren Lebensunterhalt zu verdienen." Richard Riley; U.S. Bildungsminister, In „Adult Literacy in America"

### Neunzig Millionen Alzheimer-Patienten?

Wenn Ihre Gruppe in dieser politischen Modellübung zufällig aus Amerikanern bestehen würde, hätten Sie erhebliche Schwierigkeiten, eine überzeugende Botschaft zu verbreiten, insbesondere wenn die Mitglieder der Gruppe dem gesamten US-Wählerpublikum ähneln. Die Wahrnehmung, dass unverhältnismäßig viele Bürger der mächtigsten Nation der Welt unterdurchschnittliche Leistungen erbringen, wurde durch die gründlichste jemals durchgeführte Untersuchung der Kompetenz amerikanischer Erwachsener traurig bestätigt. Die Studie, „Adult Literacy in America", zeigt, dass es keineswegs einfach ist, ein gebildetes Publikum für irgendein politisches Argument zu finden. Ein großer Teil, vielleicht sogar die Mehrheit der Amerikaner über fünfzehn, fehlen grundlegende Fertigkeiten, die zur Bewertung von Ideen und zur Urteilsbildung notwendig sind. Laut dem US-Bildungsministerium können 90 Millionen Amerikaner keinen Brief schreiben, keinen Busfahrplan verstehen oder auch nur auf einem Taschenrechner addieren und subtrahieren. Dies entspricht ungefähr dem, was man erwarten würde, wenn 90 Millionen Amerikaner sich in verschiedenen Stadien der Alzheimer-Krankheit befänden. Dreißig Millionen wurden als so inkompetent eingestuft, dass sie nicht einmal auf Fragen antworten konnten.

Wenn also Ihre Gesundheitsbotschaft die Wende nicht geschafft hat, die sich ansonsten ihren eigenen Weg sucht, könnten Sie bei Tierrechtsaktivisten um Hilfe rufen. Vielleicht könnten Sie sie dazu bringen, Ihre Gegner im Kantinenausschuss zu belagern oder bei den Häusern einflussreicher Mitglieder einen Aufstand über das Unrecht des Tötens von Kühen zu machen.

Dieses Beispiel könnte unendlich weitergeführt werden, was wohl weit über das Maß der Geduld rationaler Menschen hinausgeht. Es zeigt deutlich, dass 1. jeglicher wirtschaftlicher Ausdruck von Eintritt oder Austritt in eine politische Äußerung der Stimme umgewandelt werden kann, indem er zu einer kollektiven Entscheidung gemacht wird; und 2. dass kollektive Entscheidungen, trotz der Einladung, die sie zur Eloquenz bieten, tatsächlich oft schwerfällig und unhandlich sind.

Genau das hat die Erfahrung gezeigt. Es ist alles andere als einfach, den Aufwand zu mobilisieren, der erforderlich ist, um den Kurs einer Demokratie zu ändern. Um es noch einmal zu betonen, das könnte durchaus der Grund sein, dass demokratische Wohlfahrtsstaaten Jahrhunderte des Wettbewerbs mit alternativen Regierungsformen überlebt haben um am Ende der industriellen Ära zu dominieren. Demokratie hat sich als politisches System gerade deshalb durchgesetzt, weil ihre Funktionsweise es den Bürgern erschwerte, die Kontrolle über die Regierung zu übernehmen oder die Ansprüche des Staates auf Ressourcen zu begrenzen.

Da jedoch eine unbeschränkte Partnerschaft mit dem Staat in Ihren Angelegenheiten im Informationszeitalter keinen militärischen Vorteil mehr bietet, werden einfallsreiche Menschen überlegene Wege finden, um die wenigen wertvollen Dienstleistungen zu erhalten, die Regierungen tatsächlich anbieten. Es ist wahrscheinlich, dass die tatsächliche Leistung aus kollektiven Mechanismen, die sich nicht mehr rechnen, ausgegliedert wird. Wir erwarten, dass Effizienz über gebündelte Macht dominieren wird. Wie Neil Munro knapp ausdrückte, „ist es die computerisierte Information - nicht Manpower oder Massenproduktion - die zunehmend die US-Wirtschaft antreibt und die Kriege in einer Welt gewinnen wird, die für 500 Fernsehkanäle verkabelt ist. Die computergestützte Information existiert im Cyberspace - der neuen Dimension, die durch die endlose Vermehrung von Computernetzwerken, Satelliten, Modems, Datenbanken und dem öffentlichen Internet geschaffen wird." [^449]

In einer solchen Welt werden Massenarmeen wenig Bedeutung haben. Effizienz wird noch wichtiger sein als zuvor. Wie wir bereits in Kapitel 6 und anderswo erläutert haben, schafft die Mikrotechnologie eine neue Dimension des Schutzes. Erstmals in der menschlichen Existenz werden Menschen in der Lage sein, Vermögenswerte zu schaffen und zu schützen, die vollständig außerhalb des Hoheitsbereichs einzelner Regierungen liegen. Diese Vermögenswerte werden daher hochempfindlich gegenüber individueller Kontrolle sein. Es wird völlig legitim sein, wenn Sie und eine bedeutende Anzahl anderer zukünftiger souveräner Individuen „mit den Füßen abstimmen" und sich dafür entscheiden, aus führenden Nationen auszutreten, um mit einer abgelegenen Nation oder einer neuen Minisouveränität einen Vertrag über persönlichen Schutz abzuschließen, die nur einen kommerziell tolerierbaren Betrag verlangt und nicht den Großteil Ihres Vermögens. Kurz gesagt, Sie würden wahrscheinlich 50 Millionen Dollar akzeptieren, um nach Bermuda zu ziehen.

### Zuerst aussteigen, später Verträge abschließen

Der erste Impuls zur Kommerzialisierung der Souveränität muss von Personen kommen, die sich durch ihre wirtschaftliche Abwanderung ausdrücken. Diese Option wird besonders schwer in den Vereinigten Staaten umsetzbar sein, wo sie aber auch am wertvollsten ist. Die „Berliner Mauer" für Kapitalisten, die von Präsident Bill Clinton und dem republikanischen Kongress auferlegt wurde, widerspricht dem von amerikanischen Nationalisten in den 1960er Jahren selbstbewusst geäußerten Slogan „Love it or leave it". Durch die Verhängung hoher Steuern auf diejenigen, die auswandern, soll die Auswanderungssteuer Loyalität erzwingen. Doch diese rachsüchtige Gesetzgebung, die an die Strafen für fliehende Immobilienbesitzer in den letzten Tagen des Römischen Reiches erinnert, könnte unabsichtlich den Rahmen für eine rationalere Politik im späteren Informationszeitalter festlegen.

Es wird einen Zeitpunkt geben, an dem genügend fähige Personen das Land verlassen und im Ausland bedeutende Vermögen angehäuft haben. Dann wird es für die US-Behörden attraktiv erscheinen, ihren Bürgern oder Inhabern einer Aufenthaltsgenehmigung zu gestatten, ihre zukünftigen Steuerpflichten abzukaufen, indem sie eine Auswanderungssteuer zahlen, ohne dabei jedoch tatsächlich auszuwandern. Mit anderen Worten, die Auswanderungssteuer könnte zum Modell für eine einmalige Abfindungszahlung werden. Eine Regierung, die eine solche Auswanderungssteuer auferlegt, könnte erhebliche Vorteile daraus ziehen, wenn sie diejenigen, die auswandern, unter den Bedingungen eines privaten Abkommens, wie es derzeit in der Schweiz und anderen Ländern existiert, wieder ansiedeln lässt.

Solche Schritte seitens der Vereinigten Staaten oder anderer Regierungen wären rationale Gesten zur Optimierung der Einnahmen. Letztendlich wird der Wettbewerb bei den Schutzdienstleistungen die Steuersätze senken und die Steuerbedingungen an zivilisiertere Standards anpassen. Anstatt sich auf den Gesetzgeber zu verlassen, um akzeptable Steuersysteme zu erlassen, werden souveräne Einzelpersonen in Zukunft in der Lage sein, akzeptable, maßgeschneiderte Maßnahmenpakete durch private Verträge auszuhandeln.

## BELEIDIGUNG DER WAHREN GLÄUBIGEN

Natürlich vertreten wir nicht für einen Moment die Vorstellung, dass vieles davon populär sein wird. Die Entnationalisierung des Individuums und die darin implizierte Kommerzialisierung der Souveränität wird die verbleibenden wahren Gläubigen der Klischees der Politik des 20. Jahrhunderts beleidigen. Wie der verstorbene Christopher Lasch sehen sie in der Verkümmerung der Politik eine Bedrohung für das Wohlergehen eines Großteils der Bevölkerung. Ihrer Ansicht nach könnte eine Wiederbelebung der Politik des Industriezeitalters mit ihrem Engagement für die Umverteilung von Einkommen eine Lösung für die Nöte sein, die so viele Menschen angesichts des Wettbewerbsdrucks durch die Informationstechnologie empfinden.

E. J. Dionne, Jr., ist ein politischer Reporter für die *Washington Post*. Ähnlich wie Lasch, blickt er nostalgisch auf die Politik zurück. Er spricht sich auch für einen sozialdemokratischen Ausgleichsimpuls aus, der in den kommenden Jahrzehnten zwangsläufig lauter werden wird, wenn die neuen megapolitischen Realitäten des Informationszeitalters die aus der modernen Welt übrig gebliebenen Institutionen immer stärker untergraben. Dionne ist der Ansicht, dass die materiellen Verbesserungen des Lebensstandards, die im 20. Jahrhundert in den reichen Ländern weit verbreitet waren, in erster Linie der demokratischen Politik zu verdanken sind und nicht der technologischen oder wirtschaftlichen Entwicklung. Seine Botschaft lautet, dass die Hoffnung für die Zukunft eine Ausweitung der Herrschaft der Politik über die Technologien des Informationszeitalters erfordert:

> „Das dringende Bedürfnis in den Vereinigten Staaten und in der gesamten demokratischen Welt besteht in einem neuen Engagement für demokratische Reformen, dem politischen Motor, der das Industriezeitalter so erfolgreich gemacht hat. Die Technologien des Informationszeitalters werden nicht von alleine eine erfolgreiche Gesellschaft aufbauen, genauso wenig wie der Industrialismus für sich alleine die Welt verbessert hätte. \...Selbst die außergewöhnlichsten Durchbrüche in der Technologie und die cleversten Anwendungen des Internets werden uns nicht vor sozialem Zusammenbruch, Verbrechen oder Ungerechtigkeit retten. Nur die Politik, die Kunst wie wir uns organisieren, kann überhaupt erst damit anfangen, solche Aufgaben zu übernehmen." [^450]

Dionne und Leute wie er scheitern daran zu verstehen, dass die Bedingungen, die das Leben im 20. Jahrhundert besonders förderlich für systematischen Zwang gemacht haben, nicht von einer menschlichen Instanz gewählt wurden. Die „Kunst, wie wir uns organisieren", ist eine Aussage, die vor der modernen Ära unverständlich gewesen wäre. Gesellschaften sind zu komplex, um richtig als Ergebnis eines willentlichen Selbstorganisationsversuchs betrachtet zu werden. Die Nationalstaaten der modernen Ära entstanden spontan als zufälliges Nebenprodukt der Industrietechnologie, die die Gewinnmöglichkeiten durch Gewalt erhöhte. Nun reduziert die Informationstechnologie die Gewinnmöglichkeiten durch Gewalt. Dies macht die Politik zu einem Anachronismus und einer unwiederbringlichen Sache, unabhängig davon, wie sehr die Menschen sie ins nächste Jahrtausend hinüberretten möchten.

> „Nicht heut und gestern nur, die leben immer, Und niemand weiß, woher sie sind gekommen." - Sophokles, Antigone

## „SIE MACHEN ES NICHT MEHR SO WIE FRÜHER"

Der brennende Wunsch, „Gesetze zu machen", der so sehr Teil des „gesunden Menschenverstands" der Politik des 20. Jahrhunderts zu sein scheint, ist keineswegs allen Kulturen eigen. Sein Verschwinden in der Zukunft könnte als Teil eines Zyklus gesehen werden, der im Laufe der Jahrhunderte gewachsen und geschrumpft ist. Zum Beispiel glaubten die alten Griechen, unter anderem, dass Gesetze nicht gemacht werden könnten. In den Worten des Philosophen Ernst Cassirer glaubten die Griechen, „die ‚ungeschriebenen Gesetze', die Gesetze der Gerechtigkeit, haben keinen Anfang in der Zeit". [^451] Wie andere präpolitische Völker fühlten sie, dass niemand die natürlichen, „geometrischen" Gesetze der Gerechtigkeit verbessern konnte, die von keiner menschlichen Macht geschaffen wurden.

Sie glaubten nicht an einen „Gesetzgeber". Wie Cassirer es ausdrückte: „Es liegt am rationalen Denken, dass wir die Standards moralischen Verhaltens finden, und es ist die Vernunft, und nur die Vernunft, die ihnen ihre Autorität verleihen kann." In diesem Sinne wäre jeder Versuch, Gesellschaften durch Gesetzgebung Gesetze aufzuerlegen, so, als würde man versuchen, die Geometrie durch Gesetzgebung zu verändern.

### Gesetzgebung als Sakrileg

Aus völlig anderen Gründen herrschte während eines großen Teils des Mittelalters ein ähnlicher Widerstand gegen die „Gesetzgebung". Wie John B. Morrall schreibt, „Für die Deutschen war das Gesetz etwas, das seit Urzeiten existierte". Es war „eine Garantie für die Rechte" einzelner Mitglieder des Stammes. [^452] Könige und Räte

> hatten bisher keine Absicht, neues Recht zu schaffen. Eine solche Absicht wäre aus der Sicht des frühen Mittelalters nicht nur überflüssig, sondern geradezu gotteslästerlich gewesen, denn das Recht besaß ebenso wie das Königtum eine eigene sakrosankte Aura. Stattdessen sahen sich König und Räte nur als Erklärer oder Klärer der wahren Bedeutung des bereits existierenden und vollständigen Körpers des Rechts. Der germanische Brauch überlieferte dem mittelalterlichen Geist eine Idee, die er nie vergessen konnte, selbst wenn er in der Praxis anders handelte. Diese Idee bestand darin, dass gute Gesetze wiederentdeckt oder neu formuliert, aber niemals neu gemacht wurden. [^453]

Nach den Exzessen der Gesetzgebung des zwanzigsten Jahrhunderts hat diese alte Einstellung etwas Seltsames an sich. Der Wunsch, die Zwangsgewalt des Staates für private Zwecke einzusetzen, insbesondere für die Umverteilung von Einkommen, wurde fast zur zweiten Natur.

### Bedauern

Es ist daher kaum verwunderlich, dass es traurige Lieder über die Politik in ihren letzten Tagen gibt. Sie sind völlig vorhersehbar. Und nicht nur, weil sie die Blindheit der meisten Denker gegenüber den Imperativen der Megapolitik widerspiegeln. Wenige politische Reporter, wie Dionne, sind bereit, die offensichtliche Rückbildung und den Niedergang der Politik zu akzeptieren, wenn dies dazu führen könnte, dass sie wieder auf der Verbrechensspur landen. Am Ende des Mittelalters wurden Stimmen laut, die eine Wiederbelebung der Ritterlichkeit unterstützten. Betrachten Sie *Il Libro del Cortegiano* oder *Das Buch des Hofmanns*, das 1514 von Graf Baldassare Castiglione geschrieben und 1528 von Aldus in Venedig veröffentlicht wurde.

Castigliones tiefgreifendes Verlangen nach einer Rückkehr zu den Tugenden des Rittertums war stark spürbar, doch die Sehnsucht nach einer erloschenen Lebensweise konnte sie im sechzehnten Jahrhundert nicht zurückbringen. Und das wird sie auch im einundzwanzigsten Jahrhundert nicht tun.

Wie wir bei der Erläuterung unserer Theorie der Megapolitik zu vermitteln versucht haben, sind technologische Imperative und nicht die öffentliche Meinung die wichtigsten Quellen für Veränderungen. Wenn unsere Theorie der Megapolitik zutrifft, dann war der Grund dafür, dass die Moderne mit ihrem Konzept der Staatsbürgerschaft und der auf den Staat ausgerichteten Politik das Feudalsystem und das auf persönliche Eide und Beziehungen ausgerichtete Rittertum verdrängt hat, nicht eine Frage der Ideen, sondern der Verschiebung von Kosten und Nutzen aufgrund neuer Technologien. Das Rittertum starb nicht aus, weil Castiglione oder andere daran scheiterten, eine gleichgültige Bevölkerung davon zu überzeugen, dass es in Staatsangelegenheiten keinen Bedarf an Ehre oder Moral gab. Im Gegenteil, Castigliones ‚Der Hofmann' ist kritisch gegenüber Fürsten und der von seinem Zeitgenossen Niccolò Machiavelli in *Il Principe* oder *Der Fürst* gelobten Verhaltensweise. Und was dann? Letztlich erreichte Machiavelli mit seinem Buch ein größeres Publikum, nicht weil sein Argument in *Der Fürst* überzeugender war, sondern weil seine Ratschläge besser zu den megapolitischen Bedingungen des modernen Zeitalters passten.

Wie der angesehene Philosoph des 20. Jahrhunderts, Ernst Cassirer, in seiner Diskussion über „Das moralische Problem bei Machiavelli" sagte,

> Das Buch beschreibt, mit völliger Gleichgültigkeit, die Methoden und Mittel, mit denen politische Macht erworben und aufrechterhalten werden kann. Über den korrekten Gebrauch dieser Macht sagt es kein Wort. \... Niemand hatte jemals bezweifelt, dass das politische Leben, wie es momentan aussieht, voller Verbrechen, Verrätereien und schweren Vergehen ist. Aber kein Denker vor Machiavelli hatte sich daran gemacht, die Kunst dieser Verbrechen zu lehren. Diese Dinge wurden getan, aber sie wurden nicht gelehrt. Dass Machiavelli versprach, ein Lehrer in der Kunst der Intrigen, Untreue und Grausamkeit zu werden, war bisher unerhört. [^454]

Kurz gesagt, *Der Fürst* war ein radikales Werk, das ein modernes Rezept entwarf, wie ein aufstrebender Herrscher seine Karriere um jeden Preis für andere vorantreiben konnte. Machiavelli befürwortete Verhaltensweisen, die sich als gut geeignet für die Politik in einem Zeitalter der Macht erwiesen. Aber die Kunst des Doppelspiels, die eine kluge Politik für Politiker im modernen Zeitalter war, war empörend und subversiv im Vergleich zur Kultur des Rittertums, die in den vorherigen Jahrhunderten gewachsen war.

Wie wir bereits früher herausgefunden haben, zählten zu den Tugenden des Rittertums ein besonderes Augenmerk auf extreme Treue zu Eiden. Dies war eine Notwendigkeit in einer Gesellschaft, in der Schutz im Tausch gegen persönliche Dienste organisiert wurde. Die Abmachungen, auf denen die feudale Gesellschaft beruhte, waren nicht so beschaffen, dass sie unter Menschen, die unter Zwang frei über ihre Interessen entscheiden konnten, spontan wieder zustande gekommen wären. Daher mussten die feudalen Verpflichtungen, die die Grundlage des Rittertums bildeten, durch ein starkes Ehrgefühl ergänzt werden. In diesem Zusammenhang hätte kaum etwas subversiver sein können als Machiavellis Vorschlag, der Fürst solle nicht zögern zu lügen, zu betrügen und zu stehlen, wenn dies seinen Interessen diene.

Als das 20. Jahrhundert sich dem Ende zuneigte, wurden Machiavellis Argumente immer noch auf ihre Bedeutung für das Verständnis der modernen Politik und verschiedener Verbrechen und Tyranneien des 20. Jahrhunderts hin untersucht. Castigliones Werk hingegen ist nahezu vergessen. Im Laufe eines Jahres wird *Il Libro del Cortegiano* vielleicht von einer Handvoll Literaturstudenten auf dem Postgraduiertenniveau und einigen Kennern der Geschichte der Manieren von Anfang bis Ende gelesen.

Irgendwann in den nächsten Jahrzehnten wird die neue Megapolitik des Informationszeitalters *Der Fürst* veralten lassen. Das souveräne Individuum wird ein neues Erfolgsrezept benötigen, das Ehre und Geradlinigkeit bei der Bereitstellung von Ressourcen außerhalb des Staates stark betont. Wir können voraussagen, dass solche Ratschläge von E. J. Dionne Jr. und den anderen lebenden Sozialdemokraten nicht mit Vergnügen gelesen werden.

### Von Kunden festgelegte Politik

Dies wird besonders zu Beginn des Übergangs der Fall sein, wenn die meisten Zuständigkeitsbereiche noch mit der Notwendigkeit belastet sein werden, Politiken zu formulieren, deren Befürworter die Unterstützung der Mehrheit der Bevölkerung gewinnen können. Später, wenn die Demokratie nachlässt und der Markt für Souveränitätsdienste intensiver wird, sollen die Marktbeschränkungen, die die „Politik" beeinflussen, breiter verstanden werden.

Was wir derzeit als „politische" Führung verstehen, die immer im Kontext eines Nationalstaates gedacht wird, wird zunehmend eher unternehmerischer als politischer Natur. Unter diesen Bedingungen wird der praktikable Spielraum für die Zusammenstellung eines „politischen" Regelwerks für einen Gerichtsstand effektiv eingeschränkt, genauso wie der Spielraum für Unternehmer bei der Planung eines erstklassigen Resort Hotels oder eines ähnlichen Produkts oder einer Dienstleistung durch das definiert ist, was Menschen dafür bezahlen würden. Ein Resort Hotel zum Beispiel würde selten versuchen, unter Bedingungen zu agieren, die von den Gästen verlangen, hart zu arbeiten, um seine Einrichtungen zu reparieren und zu erweitern. Selbst ein Resort Hotel, das von seinen Mitarbeitern besessen oder kontrolliert wird, ähnlich wie die typische moderne Demokratie, würde vergeblich versuchen, seine Kunden dazu zu zwingen, solchen Forderungen nachzukommen, insbesondere wenn bessere Unterkünfte verfügbar werden. Wenn die Kunden lieber Golf spielen würden, als schwere Arbeiten in der heißen Sonne zu verrichten, dann bietet der Markt in dieser Frage zumindest wenig Spielraum für das Aufzwingen willkürlicher Alternativen. Unter solchen Bedingungen werden aktuell „politische" Fragen zunehmend in unternehmerische Entscheidungen übergehen, während die Gerichtsbarkeiten versuchen zu entdecken, welche politischen Pakete Kunden anziehen werden.

### Die Verkümmerung der Politik

In dem Maße, in dem dies verstanden wird, werden sich auch die Einstellungen ändern. Die Bevölkerung in den dezentralisierten Ländern wird nicht mehr erwarten, dass sie aus der gleichen Palette von wunscherfüllenden politischen Optionen wählen kann, die im zwanzigsten Jahrhundert die politische Debatte beherrschten. Da die Einkommensmöglichkeiten stärker verteilt sind als im Industriezeitalter, werden die Staaten dazu neigen, die Bedürfnisse derjenigen Kunden zu befriedigen, deren Geschäft am wertvollsten ist und die die größte Auswahl haben, wo sie es ausgeben können.

Unter solchen Bedingungen könnte es viel weniger bedeutsam sein, als wir gewohnt sind anzunehmen, ob Politiken, die kommerziell optimal für einen Zuständigkeitsbereich sind, dem „Durchschnittswähler" in einer Fokusgruppe gefallen würden. Kurz gesagt, die Kommerzialisierung der Souveränität wird die Kontrolle der Regierungen durch ihre Kunden erleichtern. Dies wird dazu tendieren, die Meinungen der Nicht-Kunden irrelevant oder zumindest weniger relevant zu machen, so wie die Meinungen der Big Mac-Esser über Stopfleber für den Erfolg von französischen Drei-Sterne-Restaurants wie L\'Arpège in Paris irrelevant sind.

## „DER VERRAT AN DER DEMOKRATIE"

Wie der verstorbene Christopher Lasch werden Gegner nicht nur beklagen, dass die Informationstechnologie Arbeitsplätze vernichtet; sie werden auch beklagen, dass sie die Demokratie negiert, weil sie es dem Einzelnen ermöglicht, seine Ressourcen außerhalb der Reichweite politischer Zwänge einzusetzen. Aus diesem Grund wird die durch Informationstechnologie erleichterte finanzielle Privatsphäre den Reaktionären des neuen Jahrtausends besonders bedrohlich erscheinen. Sie werden vor der Aussicht zurückschrecken, dass die Einkommens- und Kapitalbesteuerung wirklich von „freiwilliger Übereinkunft" abhängen könnten. Sie werden neuartige und sogar drastische Mittel unterstützen, um jedem, der wohlhabend zu sein scheint, die Mittel abzupressen, wie z. B. „mutmaßliche Besteuerung" und regelrechtes Erpressen von wohlhabenden Personen.

### Gemeinschaftseigentum

Hinweise auf das, was noch kommen soll, liegen zum Zeitpunkt unserer Schreibarbeit nahe an der Oberfläche. Frühe Anzeichen dafür, dass die Fähigkeit der Regierungen, internationale Märkte zu kontrollieren, zu schwinden beginnt, provozieren jene, die glauben, dass Individuen rechtmäßig Vermögenswerte von Nationalstaaten sind. Sie möchten ihre Fähigkeit durchsetzen, die Bürger eines Landes als Vermögenswerte und nicht als Kunden zu behandeln. Die Reaktionäre sind der Überzeugung, dass sämtliches Einkommen als Gemeinschaftseinnahmen angesehen werden sollten, was bedeutet, dass es dem Staat zur Verfügung stehen sollte. [^455]

Wir haben bereits die Argumente diskutiert, die Lasch in *Revolt of the Elites and the Betrayal of Democracy* vorgebracht hat. Aber das ist nicht die einzige Streitschrift zugunsten des Nationalstaates. Der Politikwissenschaftler der Harvard Universität, Michael Sandel, argumentiert in *Democracy in Discontent*, dass „eine heutige Demokratie ohne eine Politik, die die globalen wirtschaftlichen Kräfte kontrollieren kann, nicht möglich ist, denn ohne eine solche Kontrolle ist es egal, wen die Menschen wählen, da die Konzerne regieren werden." [^456] Mit anderen Worten: Der Staat muss seine parasitäre Macht über die Individuen beibehalten, um sicherzustellen, dass politische Ergebnisse sich von Marktergebnissen unterscheiden können. Andernfalls wären kollektive Entscheidungen zur Herbeiführung unwirtschaftlicher Ergebnisse bedeutungslos.

In unserer Sichtweise ist Sandels Kritik, wie die von Lasch, nur zur Hälfte richtig. Wir räumen ein, dass die Demokratie einen Großteil ihrer Bedeutung verlieren wird, wenn Regierungen nicht die Macht haben, Einzelpersonen zu zwingen, sich so zu verhalten, wie Politiker es vorschreiben. Das ist offensichtlich. Tatsächlich ist die Demokratie, wie wir sie aus dem 19. und 20. Jahrhundert kennen, dazu bestimmt, zu verschwinden. Aber Sandel übersieht die wirkliche Bedeutung des Triumphs der Märkte über den Zwang. Sein Aufruf zu einer „Herrschaft der Konzerne" als eine Gefahr, die mit dem Zusammenbruch des Nationalstaats einhergeht, ist auffallend anachronistisch.

Konzerne werden kaum in der Lage sein, die Märkte der neuen globalen Wirtschaft zu beherrschen. Tatsächlich ist, wie wir bereits angedeutet haben, keineswegs offensichtlich, dass Konzerne auch in ihrer vertrauten modernen Form weiter bestehen werden. Weit gefehlt. Konzerne sind quasi dazu verpflichtet, sich in der megapolitischen Revolution zu verändern, die mit der Einführung des Informationszeitalters einhergeht. Wie wir zuvor diskutiert haben, wird die Mikroverarbeitung die „Informationskosten" verändern, die dazu beitragen, den „Nexus von Verträgen" zu bestimmen, der Unternehmen definiert. Wie die Ökonomen Michael C. Jensen und William H. Meckling vorschlagen, sind Unternehmen lediglich eine rechtliche Form, die „einen Nexus für eine Reihe von Vertragsbeziehungen zwischen Individuen" darstellt. [^457]

Ob Konzerne überhaupt noch überleben können, geschweige denn „herrschen" als „ein Bereich bürokratischer Leitung, der vor Marktkräften abgeschirmt ist", wird nach den Worten der Wirtschaftswissenschaftler Louis Putterman und Randall S. Kroszner wahrscheinlich selbst durch „die Vollständigkeit der Marktkräfte und die Fähigkeit der Marktkräfte, die innerbetrieblichen Beziehungen zu durchdringen" bestimmt. [^458]

Wie wir bereits zuvor argumentiert haben, ist es zweifelhaft, dass Firmen das zunehmende Eindringen von Marktkräften in das, was bisher „innerbetriebliche Beziehungen" waren, überleben können. Infolgedessen werden Unternehmen dazu tendieren, sich aufzulösen, da die Informationstechnologie es attraktiver macht, sich auf den Preismechanismus und den Auktionsmarkt zu verlassen, um anstehende Aufgaben zu erledigen, anstatt sie innerhalb einer formellen Organisation zu internalisieren. Da die Informationstechnologie den Produktionsprozess zunehmend automatisiert, wird sie einen Teil der Daseinsberechtigung der Firma, die Notwendigkeit, Manager zu beschäftigen und zu motivieren, um einzelne Arbeiter zu überwachen, wegnehmen.

### „Warum gibt es Firmen?"

Denken Sie daran, dass die Frage „Warum gibt es Firmen?" nicht so trivial ist, wie sie auf den ersten Blick erscheinen mag. Die Mikroökonomie geht allgemein davon aus, dass der Preismechanismus das effektivste Mittel zur Koordination von Ressourcen für deren am höchsten bewerteten Einsatz ist. Wie Putterman und Kroszner feststellen, deutet dies tendenziell darauf hin, dass Organisationen wie Firmen keine inhärente „ökonomische Daseinsberechtigung" [^459] haben. In diesem Sinne sind Firmen hauptsächlich Artefakte von Informations- und Transaktionskosten, die Informationstechnologien tendenziell drastisch reduzieren.

Daher wird das Informationszeitalter eher das Zeitalter von unabhängigen Auftragnehmern ohne „Arbeitsplätze" in langjährigen „Firmen" sein. Da Technologie die Transaktionskosten senkt, wird der gleiche Prozess der Befreiung von politischer Beherrschung auch die „Herrschaft durch Konzerne" verhindern. Konzerne werden in einem Ausmaß mit „virtuellen Konzernen" überall auf der Welt konkurrieren, das alle außer Wenigen beunruhigen und bedrohen wird. Die meisten Konzerne als Institutionen werden mit dem verschärften Wettbewerb in immer vollständigeren Märkten zu kämpfen haben, um zu überleben.

Die zu erwartende Konsequenz ist nicht, dass Individuen den Konzernen ausgeliefert sein werden. Im Gegenteil. Konzerne als solche werden nicht mehr Macht haben, die Märkte zu manipulieren als Politiker. Es ist vielmehr so, dass Individuen endlich frei sein werden, ihr eigenes Schicksal in einem wirklich freien Markt zu bestimmen, der weder von mächtigen Regierungen noch von Konzernhierarchien geregelt wird.

Diese Erosion der Transaktionskosten wird auch die kürzlich in Mode gekommene Vorstellung vom „Stakeholder-Kapitalismus" in Frage stellen. Solche Konzepte, die Tony Blair von der britischen Labour Party ebenso am Herzen liegen wie einigen in Bill Clintons Umfeld, beruhen auf der Fähigkeit des Staates, die Konzerne zu manipulieren. Nach dem Zusammenbruch des Sozialismus träumen die Interventionisten nun davon, die Ziele des Sozialismus durch markteffizientere Mittel zu erreichen, indem sie die Unternehmen stark regulieren. Diese neue umverteilende These besagt, dass Geschäftsführung, Aktionäre, Mitarbeiter und „die Gemeinschaft" alle „Stakeholder" der Firmen sind. Das Argument lautet, dass sie alle Vorteile von langlebigen Firmen ableiten und sogar auf diese Vorteile angewiesen sind. Daher sollte die Regulierung den Anteil schützen, den Manager, Mitarbeiter und lokale Steuerbehörden an der Fortsetzung ihrer historischen Beziehungen mit den Firmen haben.

„Stakeholder-Kapitalismus" ist eine Doktrin, die letztendlich nicht nur die Fähigkeit des Staates voraussetzt, die Entscheidungsfindung von Konzernen zu manipulieren, sondern noch grundlegender die Existenz von Konzernen als langjährige Organisationen voraussetzt, die unabhängig von Preissignalen im Auktionsmarkt funktionieren können.

Wir vermuten, dass die Vertiefung der Märkte nicht nur die Steuerkapazität des Nationalstaates verringern wird, sondern auch die Fähigkeit der Politiker, den Eigentümern von Ressourcen durch Regulierung willkürlich ihren Willen aufzuzwingen. In einer Welt, in der juristische Vorteile Markttests unterzogen werden und viele lokale Märkte für Wettbewerb aus aller Welt geöffnet werden, ist kaum zu erwarten, dass lokale „Gemeinschaften" viele wirksame Möglichkeiten haben werden, bevorzugte Firmen vor globalem Wettbewerbsdruck zu isolieren. Daher werden sie kaum Möglichkeiten haben, sicherzustellen, dass Konzerne, die mit höheren Kosten belastet sind (zum Beispiel zum Halten von unnötigen Angestellten und Managementpersonal und zur Aufrechterhaltung von ungenutzten Einrichtungen, um lokalem politischem Druck gerecht zu werden), in der Lage sind, diese Kosten auszugleichen und im Geschäft zu bleiben. Im Industriezeitalter konnten Politiker Märkte schließen und den Zugang für einige bevorzugte Firmen einschränken, um Beschäftigung und andere Ziele zu erreichen. In der Zukunft, wenn Informationen überall auf der Welt frei gehandelt werden können, wird die Macht der Regierungen, lokale Unternehmen vor globalem Wettbewerbsdruck zu schützen, minimal sein.

Auch ist es unwahrscheinlich, dass sich Forderungen nach einem „neuen Gesellschaftsvertrag\", der sich auf einen so genannten unabhängigen oder ehrenamtlichen Sektor konzentriert, der die Zeit von ansonsten arbeitslosen oder marginalisierten Arbeitnehmern „in der Gemeinschaft" auffangen soll, als realisierbar erweisen werden. [^460] Jeremy Rifkin stellt sich „eine neue Partnerschaft zwischen der Regierung und dem dritten Sektor vor, um die Sozialwirtschaft wieder aufzubauen. \... Die Armen zu ernähren, eine medizinische Grundversorgung bereitzustellen, die Jugend der Nation auszubilden, erschwingliche Wohnungen zu bauen und die Umwelt zu erhalten. \..." [^461]

### Das Verschwinden der öffentlichen Güter

Natürlich werden Apologeten der Zwangsanwendung argumentieren, dass das Abnehmen der Staatsmacht zu einem Unvermögen führen wird, öffentliche Güter zu beschaffen oder zu genießen. Dies ist aus Wettbewerbsgründen und anderen Gründen unwahrscheinlich. Zum einen werden, da technologische Entwicklungen Standortvorteile zumeist aufheben, Zuständigkeitsbereiche, die wesentliche öffentliche Güter wie die Aufrechterhaltung von Recht und Ordnung nicht bereitstellen, schnell Kunden verlieren. Im extremsten Falle, wie bereits in Somalia, Liberia, Ruanda und dem ehemaligen Jugoslawien zu sehen, können Horden mittelloser Flüchtlinge über Grenzen strömen, um eine zufriedenstellendere Bereitstellung von Recht und Ordnung zu suchen. Aber diese extremen Beispiele für Desertationen oder Abstimmungen mit den Füßen unterscheiden sich nur in ihrer Dringlichkeit vom einfachen Einkauf von Rechtssystemen. In jedem Fall werden Unternehmen lokale Rechtssysteme dazu zwingen, die Bedürfnisse ihrer Kunden zu erfüllen.

### „Wettbewerbsfähige Territorialklubs"

Dies ist mehr als nur eine Theorie, wie sie erstmals vom Wirtschaftswissenschaftler Charles Tiebout im Jahr 1956 vorgestellt wurde. [^462] Wirtschaftswissenschaftler Fred Foldvary hat in *Public Goods and Private Communities: The Market Provision of Social Services* dokumentiert, dass es keinen wesentlichen Grund dafür gibt, dass soziale Dienstleistungen und viele öffentliche Güter mit politischen Mitteln bereitgestellt werden müssen. Foldvarys Beispiele bestätigen unter anderem das umstrittene Theorem des Nobelpreisträgers Ronald Coase, dass „staatliche Interventionen nicht notwendig sind, um Probleme im Zusammenhang mit externen Einflüssen", z. B. Umweltverschmutzung, zu lösen. [^463] Unternehmer können kollektive Güter durch Marktmittel bereitstellen. Viele tun dies bereits in der realen Welt. Foldvarys Fallstudien zeigen, wie die Privatisierung von Gemeinschaften zu neuen Mechanismen für die Bereitstellung und Finanzierung von öffentlichen Gütern und Dienstleistungen führen kann. [^464]

### Der Weg zum Wohlstand

Die Mikrotechnologie selbst wird neue Möglichkeiten zur Finanzierung und Regulierung von Waren bereitstellen, die bisher als öffentliche Güter behandelt wurden. Rückblickend werden einige dieser Güter sich als getarnte private Güter herausstellen. Autobahnen sind ein Paradebeispiel. Solange Staus ein geringes Problem waren, konnten Straßen und Autobahnen als öffentliche Güter behandelt werden, auch wenn sie den von Adam Smith geäußerten Kritikpunkten unterlagen, dass sie die in der Nähe lebenden Menschen überproportional begünstigen, auf Kosten derjenigen in entfernten Regionen, die gezwungen sind, dafür zu bezahlen, während sie nur wenige der Vorteile genießen.

Im Informationszeitalter wird es technologisch möglich sein, Maut- sowie Staugebühren, zu erheben, die den Zugang zu Autobahnen, Start- und Landebahnen und anderen Infrastrukturen genau bepreisen, ohne den Verkehrsfluss zu unterbrechen. Damit könnte die Bereitstellung der Verkehrsinfrastruktur diskret privatisiert und direkt von den Nutzern des Dienstes finanziert werden. Der Ökonom Paul Krugman schätzt, dass die marktgerechte Preisgestaltung der US-Verkehrsinfrastruktur jährlich zwischen 60 und 100 Milliarden US-Dollar zum CIDP (Corridor Identification and Development Program) in den USA hinzufügen würde, während gleichzeitig die Effizienz der Ressourcennutzung verbessert und die Umweltverschmutzung reduziert würde. [^465]

Darüber hinaus darf nicht vergessen werden, dass der kostspieligste Teil dessen, was moderne Nationalstaaten tun - die Umverteilung von Einkommen - nicht die Bereitstellung eines öffentlichen Gutes ist, sondern die Bereitstellung privater Güter auf Kosten der Allgemeinheit. „Auf Kosten der Allgemeinheit\" ist hier ein Euphemismus für „auf Kosten derjenigen, die Steuern zahlen".

Wie sieht es mit einem echten öffentlichen Gut aus, wie der Bereitstellung einer Militärmacht, die in der Lage ist, einen Angriff einer Großmacht abzuwehren? Solche Streitkräfte waren traditionell teuer. Wie wir bereits untersucht haben, wäre eine Regierung, die nicht die uneingeschränkte Fähigkeit hat, die Einkommen und das Eigentum ihrer Bürger zu konfiszieren, nicht in der Lage, eine Beteiligung an einem anderen Großmacht-Konflikt wie dem Zweiten Weltkrieg zu finanzieren.

Und doch stellt dieses fiskalische Limit weniger eine Bedrohung dar, als reaktionäre Kräfte vorgeben, aus dem einfachen Grund, dass es keine Konflikte mehr wie den Zweiten Weltkrieg geben wird. Die Technologie, die Individuen befreit, wird dafür sorgen.

### Über die Politik hinweg

Anstatt die Qualität und den Charakter solcher Dienstleistungen dem Belieben der Politik zu überlassen, können „Regierungen" unternehmerisch geführt und in das umgewandelt werden, was Foldvary als „wettbewerbsfähige Territorialklubs" bezeichnet. [^466] Wir vermuten, dass letztendlich der Entscheidungsprozess, durch den solche „wettbewerbsfähige Territorialklubs" organisiert werden, viel weniger bedeutet als ihr Erfolg bei der Bewältigung marktbasierter Leistungstests. Heutzutage interessiert es nur wenige Verbraucher, wenn sie ein Produkt oder eine Dienstleistung kaufen, ob das Unternehmen, das es verkauft, ein Einzelunternehmen, eine Gesellschaft mit beschränkter Haftung oder eine Aktiengesellschaft ist, die von externen, durch Pensionspläne ernannten Direktoren kontrolliert wird. Ebenso bezweifeln wir, dass es den rationalen Verbraucher von Staatsdienstleistungen im Informationszeitalter interessiert, ob Singapur eine Massendemokratie oder das Eigentum von Lee Kwan Yew ist.

[^430]: John Dunn, *Western Political Theory in the Face of the Future*, Cambridge, Eng.: Cambridge University Press. 1979, S. 2.

[^431]: Carroll Quigley, *Weapons Systems and Political Stability* (Washington, D.C.: University Press of America, 1983).

[^432]: Ebenda, S. 56.

[^433]: Zitiert in Kelly, ebenda, S. 46.

[^434]: Molander, et al. Strategic Information Warfare, ebenda, S. xv.

[^435]: Ebenda, S. xiv.

[^436]: Dennis C. Mueller, *Public Choice*, Vol. 2 (Cambridge: Cambridge University Press, 1989), S. 43-226.

[^437]: Michael A. Bernstein, *The Great Depression: Delayed Recovery and Economic Change in America*, 1929-1939" (Cambridge: Cambridge University Press, 1987).

[^438]: Mancur Olson, *The Rise and Decline of Nations: Economic Growth, Stagflation, and Social Rigidities* (New Haven: Yale University Press, 1982).

[^439]: Michael M. Phillips, „Math Ph.D.s Add to Anti-Foreigner Wave: Scholars Facing High Jobless Rate Seek Immigration Curbs," Wall Street Journal, 4. September 1996, S. A2.

[^440]: Juan J. Linz and Alfred Stepan, eds., *The Breakdown of Democratic Regimes* (Baltimore, Md.: The Johns Hopkins University Press, 1978), S. 18.

[^441]: William Keech, Economic Politics: The Costs of Democracy. Cambridge: Cambridge University Press, 1995, S. 221.

[^442]: E.S. Staveley, Greek and Roman Voting and Elections (Ithaca, N.Y.: Cornell University Press, 1972), S. 62.

[^443]: Ebenda, S. 65.

[^444]: Norman Cohn, The Pursuit of the Millennium (Oxford: Oxford University Press, 1970), S. 41.

[^445]: Ebenda, S. 84-85.

[^446]: Zitiert in Kelly, ebenda, S. 46.

[^447]: Milton Friedman, „Capitalism and Freedom" (Chicago: University of Chicago Press, 1962), p.91. Discussed by Hirschman, ebenda, S. 16-17.

[^448]: Hirschman, ebenda, S. 17.

[^449]: Neil Munro, „The Pentagon\'s New Nightmare: An Electronic Pearl Harbor," Washington Post, 16. Juli 1995, S. C3.

[^450]: E. J. Dionne, „Why the Right Is Wrong", Utne Reader, Juni 1996, S. 32.

[^451]: Ernst Cassirer, The Myth of the State (New Haven: Yale University Press, 1946), S. 81.

[^452]: John B. Morrall, Political Thought in Medieval Times (New York: Harper Torchbooks, 1962), S. 15.

[^453]: Ebenda, S. 16.

[^454]: Cassirer, ebenda, S. 142, 150.

[^455]: Robert I Shapiro, „Flat Wrong: New Tax Schemes Can\'t Top Old Progressive Truths," Washington Post, 24. März 1996, S.C3, und Thomas L. Friedman, „Politics in the Age of NAFTA," New York Times, 7. April S. E11.

[^456]: Zitiert von Friedman, ebenda.

[^457]: Siehe Louis Putterman und Randall S. Kroszner, „The Economic Nature of the Firm: A New Introduction," in Louis Putterman und Randall S. Kroszner, eds., „The Economic Nature of the Firm: A Reader" (Cambridge: Cambridge University Press, 1996), S. 17.

[^458]: Ebenda.

[^459]: Ebenda, S. 9.

[^460]: Siehe Jeremy Rifkin, „The End of Work: The Decline of the Global Labor Force and the Dawn of the Post-Market Era" (New York: G.P. Putnam\'s Sons, 1995).

[^461]: Ebenda, S. 250.

[^462]: Siehe Charles M. Tiebout, „A Pure Theory of Local Expenditure", Journal of Political Economy 64 (1956), S. 416-24

[^463]: Mueller, ebenda, S .28-29.

[^464]: Fred Foldvary, „Public Goods and Private Communities: The Market Provision of Social Services" (Aldershot, Hants, England: Edward Elgar Publishing, Ltd., 1994).

[^465]: Paul R. Krugman, „The Tax-Reform Obsession", New York Times Magazine, 7. April 1996, S. 37.

[^466]: Foldvary, ebenda, S. 66f.
