# DIE ÜBERWINDUNG DES RÄUMLICHEN

*Das Aufkommen der Cyberökonomie*

> „Das eigentliche Problem ist die Kontrolle. Das Internet ist zu weit verbreitet, um einfach so von einer einzelnen Regierung dominiert zu werden. Durch die Schaffung einer reibungslosen globalen Wirtschaftszone, die sowohl anti-souverän als auch unregulierbar ist, stellt das Internet die bloße Idee eines Nationalstaates in Frage." [^245]: - John Perry Barlow

Die Informationsautobahn ist zu einer der bekanntesten Metaphern aus den Anfangstagen des digitalen Zeitalters geworden. Sie ist nicht nur aufgrund ihrer Allgegenwärtigkeit bemerkenswert, sondern auch für das weit verbreitete Missverständnis, das sie sich über die Cyberwirtschaft offenbart. Eine Autobahn ist schließlich eine industrielle Version eines Fußweges, ein Netzwerk für den physischen Transit von Menschen und Gütern. Die Informationswirtschaft ist nicht wie eine Autobahn, eine Eisenbahn oder eine Pipeline. Sie transportiert oder befördert keine Informationen von einem Punkt zum anderen, so wie die Trans-Canada Autobahn schwere Lastwagen von Alberta nach New Brunswick transportiert. Was die Welt als „Informationsautobahn" bezeichnet, ist nicht nur ein Transitweg. Es ist das Ziel.

Der Cyberspace überwindet Räumlichkeit. Er beinhaltet nichts Geringeres als das sofortige Teilen von Daten überall und nirgendwo gleichzeitig. Die entstehende Informationswirtschaft basiert auf den Verbindungen, die Millionen von Nutzern mit Millionen von Computern verknüpfen und immer wieder neu verknüpfen. Ihr Wesen liegt in den neuen Möglichkeiten, die aus diesen Verbindungen entstehen. Wie John Perry Barlow es ausdrückte: „Was das Netz bietet, ist das Versprechen eines neuen sozialen Raums, der global und anti-souverän ist und in dem jeder, egal wo, dem Rest der Menschheit ohne Angst sagen kann, was er oder sie glaubt. Diese neuen Medien sind eine Vorahnung der intellektuellen und wirtschaftlichen Freiheit, die alle autoritären Mächte der Welt auslöschen könnte." [^246]:

Der Cyberspace, ähnlich dem imaginären Reich der Götter Homers, ist ein Bereich abseits der vertrauten irdischen Welt von Landwirtschaft und Fabriken. Doch seine Auswirkungen werden nicht imaginär, sondern real sein. In weit größerem Ausmaß, als viele derzeit verstehen, wird das sofortige Teilen von Informationen wie ein Lösungsmittel wirken, das große Institutionen auflöst. Es wird nicht nur die Logik der Gewalt verändern, wie wir bereits untersucht haben; es wird auch die Informations- und Transaktionskosten, die bestimmen, wie sich Unternehmen organisieren und wie die Wirtschaft funktioniert, radikal verändern. Wir erwarten, dass die Mikroverarbeitung die wirtschaftliche Organisation der Welt verändern wird.

> „Es ist heute mehr denn je in der Geschichte der Welt möglich, dass ein Unternehmen von überall aus agieren und Ressourcen aus der ganzen Welt nutzen kann, um ein Produkt herzustellen, das überall verkauft werden kann." - Milton Friedman

## DIE TYRANNEI DES ORTES

Die Tatsache, dass der erste Versuch des verblassenden industriellen Zeitalters, die Informationsökonomie zu konzipieren, darin besteht, sie sich in Form eines riesigen öffentlichen Bauprojekts vorzustellen, zeigt, wie sehr unser Denken in den Paradigmen der Vergangenheit verhaftet ist. Es ist eher so, als würden wir Bauern am Ende des achtzehnten Jahrhunderts eine Fabrik als „einen Bauernhof mit einem Dach" beschreiben hören. Doch die Metapher der „Super-Autobahn" ist noch aufschlussreicher. Sie verrät auch, inwieweit wir der Tyrannei des Ortes ausgeliefert sind. Selbst wenn die Technologie uns ermöglicht, die Räumlichkeit zu überwinden, bekommt das Instrument unserer Befreiung einen Spitznamen, der es als Weg von Ort zu Ort beschreibt. Wie Lachse, die durch ihren Heiminstinkt geprägt sind, ist unser Bewusstsein immer noch tief von Vorstellungen der Räumlichkeit gezeichnet.

Die gesamte Geschichte hindurch waren Volkswirtschaften an ein lokales geografisches Gebiet gebunden. Die meisten Menschen, die vor dem zwanzigsten Jahrhundert lebten, verbrachten ihre Tage de facto wie Gefangene unter Hausarrest, selten mehr als ein paar Tage Fußmarsch von dem Ort entfernt, an dem sie geboren wurden. Eine Reise über eine beliebige Distanz war das Werk von Generationen. Nur gelegentlich löste irgendeine Krise - Krieg, Pest, eine unerwünschte klimatische Veränderung - eine breite Migration aus. Um Menschen dazu zu bringen, ein elendes Dorf zu verlassen, bedurfte es etwas Spektakulärem und Dringendem. Nichts Geringeres konnte die Menschen dazu bewegen, ihre Habseligkeiten zusammenzupacken und auf der Suche nach einem besseren Leben abzuwandern.

Bis vor kurzem wurden diejenigen, die außerhalb ihres eigenen Gebiets nach Möglichkeiten suchten, oft berühmt. Nehmen wir zum Beispiel Marco Polo, der immer noch dafür bekannt ist, dass er den eurasischen Kontinent bereist hat, um den Hof des großen Khan zu besuchen. Er war zu seiner Zeit die Ausnahme. Wenige andere Reisetagebücher der Vormoderne sind erhalten geblieben. Unter den meistgelesenen sticht *Mandevilles Reisen*, geschrieben auf Französisch im Jahr 1357, hervor. Interessant ist, dass es wahrscheinlich von jemandem verfasst wurde, der Europa nie verlassen hat. Mandeville vermittelt bezaubernde und oft fantastische Details über das Leben in aller Welt, einschließlich der Behauptung, dass viele Äthiopier nur einen Fuß haben: „\...der Fuß ist so groß, dass er den ganzen Körper vor der Sonne abschirmt, wenn sie sich ausruhen wollen." [^247]: Offensichtlich wussten nur wenige von Mandevilles Zeitgenossen, die seine beliebte Geschichte lasen, dass sein äthiopischer „Bigfoot" nicht existierte.

Erst mit Beginn des modernen Zeitalters, durch die Entdeckungsreisen am Ende des 15. Jahrhunderts, gab es dauerhafte Kontakte zwischen den Kontinenten. Wagemutige Kapitäne wie Christoph Kolumbus und Vasco da Gama, die sich daran machten, den Gewürzhandel zu erobern, waren außergewöhnlich genug, um für den größten Teil von fünf Jahrhunderten in jedem gebildeten Haushalt in Erinnerung zu bleiben.

Von der Entstehung der Landwirtschaft bis in die jüngsten Generationen war das Leben durch seine Unbeweglichkeit geprägt. Dies ist heute fast vergessen, insbesondere in den europäischen Siedlungskolonien der „Neuen Welt", wo Bewegungen flüssiger sind und jeder dazu neigt, seine Perspektive aus dem Blickwinkel eines Einwanderers zu betrachten. Ein wesentliches Thema im Grundschulunterricht in Nordamerika ist, dass die Kolonisten aus Europa kamen, um Freiheit und Chancen zu suchen, was der Wahrheit entspricht. Was jedoch selten erzählt wird, ist, wie widerwillig die meisten Menschen die Reise angetreten haben, selbst wenn sie zu Hause Armut gegenüberstanden. Die wenigen, die auswanderten, erlitten nach heutigen Begriffen unvorstellbare Strapazen, um sich zu etablieren. Nur die unternehmungslustigsten oder verzweifeltsten Armen wagten es. Mitte des 17. Jahrhunderts revoltierten Insassen in Bridewell, dem berüchtigten Zuchthaus in London, um „ihren Unwillen zum Ausdruck zu bringen, nach Virginia zu gehen".[^248]: Im Jahr 1720 kam es zu Tumulten auf den Straßen von Paris, um Obdachlose, Diebe und Mörder zu befreien, die zur Deportation nach Louisiana vorgesehen waren.

### Enge Horizonte

Die physischen Schwierigkeiten der Kommunikation und des Transports, ergänzt in den meisten Zeiten und Orten durch begrenzte Sprachkenntnisse, machten den Fokus menschlichen Handelns eng und lokal. Noch im frühen zwanzigsten Jahrhundert war es üblich, chinesische Dörfer zu finden, die nur fünf Meilen voneinander entfernt lagen und trotz Küstennähe gegenseitig unverständliche Dialekte sprachen. Die lokale Organisation fast aller Wirtschaften legte eine Strafe für schmale Märkte und verpasste Chancen auf. Die Faktorkosten wurden aufgrund begrenzten Wettbewerbs hoch gehalten. Der Zugang zu spezialisierten Fähigkeiten war minimal. Mit Einkommen, so niedrig, dass sie am Rand des Verderbens kratzten, und ohne Zugang zu externem Kapital oder effizienten Versicherungsmärkten, waren Kleinbauern in großen Teilen der Welt in Armut gefangen. Wir haben einige der Schwierigkeiten diskutiert, mit denen Bauern aufgrund des eingeschränkten Dorflebens konfrontiert waren. Selbst jetzt, während wir schreiben, kämpfen mindestens eine Milliarde Menschen, meist in Asien und Afrika, um mit weniger als einem Dollar pro Tag zu überleben.

## „JEDE POLITIK IST LOKAL"

In einem größeren Ausmaß als allgemein realisiert wird, hat die Unbeweglichkeit von Menschen und ihren Vermögenswerten die Art und Weise geprägt, wie wir die Welt sehen. Selbst diejenigen, die am meisten bereit zu sein scheinen, zuzustimmen, dass die Erde am Ende des zwanzigsten Jahrhunderts ein kleiner Ort ist, denken weiterhin in Begriffen, die von antiquierten Konzepten der Industriepolitik eingeschränkt sind. Dies wird durch einen Slogan unterstrichen, der in den 1980er Jahren unter Umweltschützern populär wurde: „Denke global, handle lokal". Es ist eine Aufforderung, die die Logik der Politik widerspiegelt, eine Logik, die schon immer auf lokalen Machtvorteilen basierte.

Die lokale Denkweise wurde durch die Megapolitik aller vergangenen Gesellschaften bestimmt. Alle topographischen Merkmale, die als Barriere oder Förderer der Ausübung von Macht dienen, sind lokal. Jeder Fluss, jeder Berg, jede Insel ist lokal. Das Klima ist lokal. Temperatur, Regenfall und Anbaubedingungen variieren, wenn man auf und über einen Berg geht. Jeder Mikroorganismus, der sich ausbreitet, tut dies an einem bestimmten und nicht an einem beliebigen anderen Ort.

Kein Wunder also, dass die Tyrannei des Ortes unsere Vorstellungen davon durchdringt, wie eine Gesellschaft zu organisieren ist und wie sie funktionieren muss. Die Machtvorteile, die der einen oder anderen Gruppe ein lokales Monopol auf Gewalt eingeräumt haben, sind immer irgendwo entstanden und verblassten entlang der megapolitischen Ränder, an denen die Grenzen gezogen werden. Das ist der Grund, warum es noch nie eine Weltregierung gegeben hat.

Die Bedeutung des Ortes für die Ausübung von Macht wurde selten explizit thematisiert, aber einige Befürworter der erzwungenen Umverteilung der Früchte menschlichen Handelns begannen schon in den 1930er Jahren, den sinkenden Einfluss des Ortes zu spüren. Sie erkannten in der modernen Verkehrstechnologie eine Teilung des sozialen Raums zwischen den Gutverdienern und den Armen. Diese Furcht wurde von John Dos Passos in „The Big Money" erfasst: „Der ‚Vagabund' sitzt am Straßenrand, pleite und hungrig. Über ihm fliegt ein Transkontinentalflugzeug voller gutbezahlter Führungskräfte. Die Oberschicht hat die Luft, die Unterschicht die Straße erobert: Zwischen ihnen gibt es keine Verbindung mehr, es sind zwei Nationen." [^249]: Das ist eine andere Art zu sagen, dass verbesserte Verkehrsmittel die Möglichkeit zur Erpressung einfach dadurch verringern, dass sie die Auswahl an Orten erhöhten, an denen erfolgreiche Personen sein können. Sicherlich war der Vagabund auf der Straße unten in keiner Position, um von denen über ihm fliegenden Personen eine milde Gabe zu verlangen. Die Tendenzen, die Dos Passos vor sechzig Jahren beobachtet hat, haben sich nur noch stärker ausgeprägt.

### Massenverkehrsmittel

Im Jahr 1995 überquerten täglich eine Million Menschen irgendwo auf der Welt Grenzen. Dies stellt eine erstaunliche Veränderung gegenüber der Vergangenheit dar. Vor dem zwanzigsten Jahrhundert war das Reisen so selten, dass die meisten Grenzen einfach als Grenzen und nicht als Hindernisse für den Transit angesehen wurden. Pässe waren unbekannt. Die Entwicklung von Ozeandampfern, Zügen und anderen verbesserten Transportmitteln hat die Bewegung dramatisch erhöht. Doch diese Bewegung wurde stärker von Staaten reguliert, deren Macht durch die gleichen Verbesserungen beim Transport und der Kommunikation erhöht wurde, die das zivile Reisen billiger und einfacher machten. Die Einführung von Filmen und vor allem des Fernsehens hat ebenfalls viel dazu beigetragen, den Horizont zu erweitern und Reisen und Einwanderung anzuregen. Aber bis jetzt sind die grundlegenden Annahmen der sozialen und wirtschaftlichen Organisation in der Räumlichkeit verankert geblieben.

> „\... um dieses Versagen der Nerven zu vermeiden, für den die Geschichte so gnadenlos bestraft. Wir müssen den Mut haben, alle technischen Extrapolationen bis zu ihrem logischen Schluss zu verfolgen." [^250]: - Arthur C. Clarke

## DER FEHLER VON MINIMALEN ERWARTUNGEN

Die geographische Fessel der Vorstellungskraft ist immer noch so eng, dass einige Experten, die das Internet im Jahr 1995 untersuchten, zu dem Schluss gekommen sind, dass es kaum kommerzielles Potenzial hat und kaum Bedeutung, außer als elektronisches Medium für Chats und eine Vertriebsstelle für Pornographie. Die vielen Zweifler an der wirtschaftlichen Bedeutung des Cyberspace sind die Ewiggestrigen des Informationszeitalters. Ihre Selbstzufriedenheit steht der des britischen Establishments gegenüber, das sich in den 1930er Jahren mit dem Niedergang des Reiches konfrontiert sah. Immer wenn sich Eliten bedroht sehen, ist ihre erste Reaktion Verleugnung. Dies zeigt sich in der frommen Hoffnung, dass das Internet nie viel bedeuten wird, manchmal sogar von Autoritäten unterstützt, die es eigentlich besser wissen sollten. Wir haben zuvor auf die Arbeit von David Kline und Daniel Burstein, *Road Warriors: Dreams and Nightmares Along the Information Highway*, verwiesen. Ihre Abwertung des ökonomischen Potenzials des Netzes ist ein weiterer Beweis dafür, dass technisches Wissen nicht gleichbedeutend mit dem Verständnis über die Konsequenzen der Technologie ist.[^251]:

Selbst die technisch versiertesten Beobachter der Vergangenheit haben oft die Auswirkungen neuer Technologien nicht erkannt. Ein im Jahr 1878 einberufener britischer Parlamentsausschuss, der die Perspektiven für Thomas Edisons Glühbirne betrachten sollte, bezeichnete Edisons Ideen als „gut genug für unsere transatlantischen Freunde, \... aber unwürdig der Aufmerksamkeit von praktischen oder wissenschaftlichen Männern".[^252]: Thomas Edison selbst war ein Mann großer Visionen, aber er dachte, dass der von ihm erfundene Phonograph hauptsächlich von Geschäftsleuten zum Diktieren genutzt würde. Kurz bevor die Gebrüder Wright bewiesen, dass Flugzeuge fliegen können, demonstrierte der renommierte amerikanische Astronom Simon Newcomb, warum es unmöglich ist, dass Flugzeuge, die schwerer sind als Luft, fliegen können. Er folgerte: „Die Demonstration, dass keine mögliche Kombination bekannter Substanzen, bekannter Formen von Maschinen und bekannter Formen von Kraft in einer praktischen Maschine vereint werden kann, mit der Menschen lange Strecken durch die Luft fliegen können, scheint dem Autor so vollständig zu sein, wie es für die Demonstration einer physikalischen Tatsache möglich ist".[^253]: Kurz nachdem Flugzeuge zu fliegen begannen, erklärte ein weiterer renommierter Astronom, William H. Pickering der Öffentlichkeit, warum kommerzielle Reisen niemals möglich sein würden: „Die breite Öffentlichkeit stellt sich oft gigantische Flugmaschinen vor, die über den Atlantik rasen und unzählige Passagiere transportieren, analog zu unseren modernen Dampfschiffen. \... Es ist klar, dass wir mit unseren derzeitigen Geräten weder mit unseren Lokomotiven noch mit unseren Autos in Bezug auf Geschwindigkeit konkurrieren können".[^254]: Wir haben zuvor bereits an eine andere extrem ungenaue Prophezeiung über das Potenzial einer neuen Technologie erinnert - die Prognose des Autoherstellers Mercedes zu Beginn des 20. Jahrhunderts, dass es weltweit nie mehr als eine Million Autos geben würde. Sie wussten mehr über Autos als fast jeder andere, aber sie hätten sich in Bezug auf die Auswirkung von Autos auf die Gesellschaft nicht stärker irren können.

Angesichts dieser Tradition ahnungsloser Missverständnisse ist es kaum überraschend, dass viele Beobachter nur langsam die wichtigsten Implikationen der neuen Informationstechnologie erfassen - die Tatsache, dass sie die Tyrannei der Räumlichkeit überwindet. Die neue Technologie schafft zum ersten Mal eine unendliche, nicht irdische Sphäre für wirtschaftliche Aktivitäten. Sie eröffnet die Möglichkeit, die neuen Grenzen der Cyber-Ökonomie zu erkunden, „global zu denken und global zu handeln". Dieses Kapitel erklärt, warum.

## JENSEITS DER RÄUMLICHKEIT

Das wiederkehrende Thema der Unterschätzung technologischer Entwicklungen ist weiterhin präsent, diesmal mit Schwerpunkt auf Informationstechnologie. Die rapide Verarbeitung und Nutzung von Informationen ersetzt physische Produkte zunehmend als wichtigste Einnahmequelle. Die Informationstechnologie entkoppelt das Potenzial, Einkommen zu erzielen, von einer Residenz an einem bestimmten geographischen Ort. Da ein immer größerer Teil des Produkt- und Dienstleistungswertes durch hinzugefügte Ideen und Wissen geschaffen wird, wird ein immer kleinerer Anteil des Mehrwerts in lokalen Jurisdiktionen erfasst werden können. Da Ideen überall formuliert und weltweit mit Lichtgeschwindigkeit übertragen werden können, wird die Informationswirtschaft sich zwangsläufig drastisch von der Wirtschaft des Fabrikzeitalters unterscheiden.

Wir würden den Kritikern zugestehen, dass eine Aufzählung der Aufgaben, die man 1996 durch das Internet hätte erledigen können, banal erscheinen mag. Schließlich ist es nicht besonders revolutionär, einen Artikel über Gartenarbeit im Netz zu lesen oder aus der Ferne eine Kiste Wein zu kaufen. Allerdings sollte das Potenzial der Cyberökonomie nicht ausschließlich nach ihren frühen Anfängen beurteilt werden, genau so wenig wie das Potenzial des Automobils, die Gesellschaft zu verändern, nach dem beurteilt werden kann, was man 1900 sehen konnte. Wir gehen davon aus, dass die Cyberökonomie sich durch mehrere Stufen entwickeln wird.

1.  Die primitivsten Manifestationen des Informationszeitalters nutzen das Netz einfach als Informationsmedium, um ansonsten gewöhnliche industrielle Transaktionen zu erleichtern. In diesem Stadium ist das Netz nicht mehr als ein exotisches Liefersystem für Kataloge. Virtual Vineyards, zum Beispiel, einer der ersten Cyberhändler, verkauft einfach Wein von einer Seite im World Wide Web. Solche Transaktionen sind noch nicht direkt subversiv gegenüber den alten Institutionen. Sie nutzen Industriewährungen und finden innerhalb erkennbarer Zuständigkeiten statt. Eine solche Nutzung des Internets hat wenig megapolitischen Einfluss.

2.  Ein mittleres Stadium des Internet-Handels wird die Informationstechnologie auf eine Weise einsetzen, die im Industriezeitalter unmöglich gewesen wären, wie etwa in der Fernbuchhaltung oder bei medizinischen Fern-Diagnosen. Weitere Beispiele für diese neuen Anwendungen der erweiterten Rechenleistung werden unten ausgeführt. Die zweite Stufe des Netz-Handels wird noch innerhalb des alten institutionellen Rahmens funktionieren, nationale Währungen verwenden und sich der Zuständigkeit der Nationalstaaten unterwerfen. Die Händler, die das Netz für den Verkauf nutzen, werden es noch nicht zur Verbuchung ihrer Gewinne nutzen, sondern nur um Umsätze zu erzielen. Diese auf Internettransaktionen basierenden Gewinne werden weiterhin besteuert werden.

3.  Ein fortgeschritteneres Stadium wird den Übergang zu echter Cyberökonomie kennzeichnen. Transaktionen werden nicht nur über das Netz stattfinden, sondern auch die Zuständigkeit von Nationalstaaten überwinden. Die Bezahlung wird in Cyberwährung erfolgen. Gewinne werden in Cyber-Banken verbucht. Investitionen werden bei Cyber-Brokern gemacht. Viele Transaktionen werden nicht besteuert werden. In diesem Stadium wird die Cyberökonomie beginnen, erhebliche megapolitische Konsequenzen zu haben, die wir bereits skizziert haben. Die Macht von Regierungen über traditionelle wirtschaftliche Bereiche wird durch die neue Logik des Netzes transformiert werden. Exterritoriale Regulierungsgewalt wird zusammenbrechen. Die Zuständigkeiten werden sich auflösen. Die Struktur von Unternehmen wird sich verändern und ebenso die Art und Weise der Arbeit und der Beschäftigung. Dieser Überblick über die Phasen der Informationsrevolution ist nur der kargste Entwurf dessen, was das weitreichendste wirtschaftliche Transformationsereignis sein könnte.

## DIE GLOBALISIERUNG DES HANDELS

Im Informationszeitalter werden die meisten aktuellen rechtlichen Vorteile durch Technologie rasch erodieren. Neue Arten von Vorteilen werden entstehen. Die sinkenden Kommunikationskosten haben bereits den Bedarf an Nähe als notwendige Bedingung für Geschäftstätigkeiten reduziert. 1946 war es technisch möglich, dass ein Investor in London einen Auftrag an einen Makler in New York stellte. Aber nur die größte und überzeugendste Transaktion hätte dies gerechtfertigt: Ein dreiminütiges Telefongespräch zwischen New York und London kostete 650 Dollar. Heute kostet es 0,91 Dollar. Der Preis für ein interkontinentales Telefonat ist in einem halben Jahrhundert um mehr als 99 Prozent gesunken.

### Konvergente Kommunikation

Bald könnte der Unterschied zwischen einem interkontinentalen Chat und einem lokalen Anruf minimal sein. Ebenso könnten die Unterschiede zwischen Ihrem Telefon, Ihrem Computer und Ihrem Fernseher gering sein. Alle werden interaktive Kommunikationsgeräte sein, die eher anhand ergonomischer statt funktioneller Merkmale unterschieden werden können. Sie werden in der Lage sein, ein Gespräch über das Internet mit Mikrofonen und Lautsprechern auf Ihrem PC zu führen. Oder einen Film anzusehen. Sie werden in der Lage sein, Ihrem Fernseher zu antworten und über das Netzwerk, das von den Unterhaltungsmedien des Fernsehens bereitgestellt wird, riesige Datenmengen zu übertragen. Da die industrielle Unterscheidung zwischen verschiedenen Kommunikationsformen abbricht und die Kosten sinken, werden immer mehr Dienste Ihnen nach Nutzungszeit berechnen und nicht nach dem Ziel Ihrer Nachrichten. Gespräche oder Datenübertragungen an jedem Ort der Welt werden kaum mehr kosten als ein lokaler Anruf in den meisten Ländern im Jahr 1985.

### Internet ohne Kabel

Satelliten in einer niedrigen Umlaufbahn und andere drahtlose Technologien werden Daten direkt an einen Piepser in Ihrer Tasche, einen tragbaren Computer oder eine Arbeitsstation übertragen, ohne dass ein lokales Telefon- oder Fernsehkabelsystem erforderlich ist. Kurz gesagt, das Internet wird kabellos sein. Die ersten Schritte in diese Richtung dürften wegen der relativ langsamen Datenübertragungsgeschwindigkeit in den frühen drahtlosen Medien und den Schwierigkeiten, schwache Signale von Teilnehmergeräten zu „hören", von denen einige mobil und batteriebetrieben sein werden, zögerlich sein. Nichtsdestotrotz werden diese technischen Probleme angegangen und gelöst werden.

### Geschäft ohne Grenzen

Die fortgesetzte Steigerung der Rechenleistung wird zu einer verbesserten Kompressionstechnologie führen, die den Datenfluss beschleunigt. Die weit verbreitete Nutzung bestehender Verschlüsselungsalgorithmen zwischen öffentlichen und privaten Schlüsseln wird es Anbietern, wie zum Beispiel Satellitensystemen, ermöglichen, die Abrechnungsfunktion direkt in den Service zu integrieren, was die Kosten senkt. Gleichzeitig mit diesem Dienst werden die Anbieter in der Lage sein, die auf den PCs gespeicherten Konten zu belasten, ähnlich wie France Telecom die in den Pariser Telefonzellen verwendeten „Smart Cards" belastet.

### Das Telefon wird zur Bank

Der Unterschied ist, dass Sie in naher Zukunft in der Lage sein werden, mit allen Arten von Transaktionen Guthaben auf Ihrem Konto anzusammeln und Ihre Telefonbox mit sich zu führen. Ihr PC wird die Filiale Ihrer Bank und der globalen Geldvermittlungsstelle sein, ebenso wie das Pendant zum Pariser Kiosk, an dem Sie Ihre anonyme Telefonkarte kaufen. Und wie die 150 „Smart Card"-Bezahltelefone, die bei gewaltsamer Öffnung mit einem Brecheisen für Diebe nutzlos sind, könnte Ihr Computer nur von jemandem ausgeraubt werden, der in der Lage ist, einen hochentwickelten Computercode zu knacken oder zu manipulieren. Das würde viele Grobmotoriker, die bloß mit einer Brechstange umgehen können, ausschließen. Bei richtiger Verschlüsselung könnte nichts in Ihrem Computer entschlüsselt oder missbraucht werden.

Bis zur Jahrtausendwende werden Sie in der Lage sein, Geschäfte fast überall nördlich der Antarktis abzuwickeln. Überall dort, wo ein verkabeltes oder digitales Mobiltelefon verfügbar ist. Überall dort, wo interaktive Kabel-Fernsehsysteme genutzt werden. Überall dort, wo ein Satellit über unseren Köpfen schwebt oder andere drahtlose Übertragungssysteme installiert sind. Sie werden in der Lage sein, Daten zu übermitteln, zu sprechen und sich mittels virtueller Realität über Grenzen und Gegebenheiten hinweg zu bewegen. Telefonnummern, die den Ort des Anrufers durch Vorwahlen kennzeichnen, werden wahrscheinlich von universellen Zugangsnummern abgelöst, die die Person, mit der Sie kommunizieren möchten, überall auf dem Planeten erreichen können.

### Chinesisch verstehen

Sie werden nicht nur in der Lage sein zu sprechen und ein Fax zu senden. Mit der Zeit könnten Sie einen mehrjährigen Lernprozess verkürzen und mit einem Vorarbeiter in Shanghai auf Chinesisch sprechen. Es wird dann nicht mehr so wichtig sein, dass Sie seine Sprache oder seinen Dialekt nicht sprechen. Seine Worte mögen Chinesisch sein, aber Sie werden hören, wie sie etwa ins Deutsche übersetzt werden. Er wird Ihre Unterhaltung auf Chinesisch hören. Mit der Zeit wird die Fähigkeit, sofortige Übersetzungen zu nutzen, den Wettbewerb in Regionen, in denen Sprachen und Redewendungen bisher bedeutende Hindernisse waren, deutlich erhöhen. Wenn das passiert, wird es wenig oder gar keine Rolle mehr spielen, ob die chinesische Regierung sich wünscht, dass der Anruf getätigt wird oder nicht.

### Individuell angepasste Medien

Während die Welt immer näher zusammenrückt, haben Sie mehr Möglichkeiten als jemals zuvor, Ihren speziellen Platz darin zu gestalten. Selbst die Informationen, die Sie regelmäßig aus den Medien erhalten, werden Informationen Ihrer Wahl sein. Die Massenmedien werden sich zu individualisierten Medien wandeln. Wenn Sie vor allem an Schach interessiert sind oder ein begeisterter Katzenliebhaber sind, können Sie Ihre Abendnachrichtensendung so programmieren, dass sie für Sie wichtige Informationen über Katzen oder Schach enthält. Sie werden nicht länger auf die Gnade von Kai Gniffke oder der Tagesschau angewiesen sein, um die Nachrichten zu sehen, die Sie sehen möchten. Sie werden in der Lage sein, Nachrichten auszuwählen, die nach Ihren Anweisungen zusammengestellt und bearbeitet werden.

### Von Massen- zu Individualfertigung

Wenn die Nachrichtenlage ruhig ist, können Sie auf einen virtuellen Katalog im World Wide Web zugreifen. Wenn Sie eine Hose sehen, die Ihnen einigermaßen gefällt, können Sie beim Bestellen die Weite des Hosenbeinabschlusses anpassen. Sie wird von Robotern in Malaysia individuell zugeschnitten, die auf Ihrem Computer eingescannte und über das Netz übertragene Fotos verwenden und sie an Ihren Körper anpassen.

### Cyber-Makler

Sie werden in der Lage sein, Cyber-Geld für Investitionen sowie zur Bezahlung von Dienstleistungen und Produkten zu nutzen. Wenn Sie in einer Rechtsordnung wie den Vereinigten Staaten leben, die Ihre Investmentoptionen stark reguliert, können Sie Ihre Aktivitäten in einer Rechtsordnung ansiedeln, die Ihnen die Freiheit gibt, eine vollständige Palette von Investmentoptionen zu verfolgen. Es spielt keine Rolle, ob Sie in Cleveland oder Belo Horizonte leben, Sie können Ihr Investmentgeschäft in Bermuda, auf den Cayman-Inseln, in Rio de Janeiro oder Buenos Aires abwickeln. Wo auch immer Sie sich befinden, der Gebrauch digitaler Ressourcen wird sich mit der Entwicklung der Cyber-Wirtschaft ausweiten. Sie werden in der Lage sein, Expertensysteme zu nutzen, um Ihre Investitionen auszuwählen, und Cyber-Buchhalter und -Buchprüfer, um den Fortschritt Ihres Portfolios in Echtzeit zu überwachen.

### Virtuelle Kultur

Wenn Sie nicht gerade Ihre Gewinn- und Verlustdaten prüfen, können Sie einen virtuellen Besuch im Louvre machen. Für Ihre Reise müssen Sie möglicherweise eine Lizenzgebühr, die dem Drittel eines Cents entspricht, an Bill Gates oder eine andere Person mit gleicher Voraussicht zahlen, die die Rechte zur virtuellen Besichtigung des Museums erworben hat. Während Sie sich fragen, ob die Mona Lisa Probleme mit ihren Zähnen hatte, könnte Ihr Computer die Übersetzung von S. I. Hsiungs „The Romance of the Western Chamber" herunterladen. Zu einer von Ihnen ausgewählten Zeit wird Ihr persönliches Kommunikationssystem den Text vorlesen wie ein mittelalterlicher Barde. Multitasking-Programme ermöglichen es Ihnen, viele Funktionen gleichzeitig auszuführen.

### Rechtssysteme im Netz einkaufen

Wenn Sie sich von Ihrer Dosis an Klassikern inspirieren lassen, können Sie ein virtuelles Unternehmen gründen, um dramatische Inszenierungen berühmter Literatur zu vermarkten, die auf dreidimensionalen Netzhautbildschirmen zu sehen sind. Anstatt in die Luft projiziert zu werden, werden die Bilder direkt auf die Netzhäute der Zuschauer mit niedrigenergetischen Lasern projiziert, die fünfzigtausend Mal pro Sekunde fluktuieren. Diese Technologie, die bereits von MicroVision in Seattle, Washington, entwickelt wird, wird vielen Personen, die rechtlich blind sind, das Sehen ermöglichen. Bevor Sie das Projekt in Angriff nehmen, könnten Sie Ihren digitalen Assistenten beauftragen, die aktuellen Vertragsangebote zum Schutz von Produktionsstätten in Malaysia, China, Peru, Brasilien und der Tschechischen Republik zu prüfen. Wenn Sie einen Standort ausgewählt haben, können Sie dank der St. Georges Trust Company Ihre Firma innerhalb von einer Stunde auf den Bahamas gründen lassen. Ihre Anweisungen werden alle flüssigen Vermögenswerte der Firma auf ein Cyberkonto in einer Cyberbank übertragen, die gleichzeitig in Neufundland, den Cayman-Inseln, Uruguay, Argentinien und Liechtenstein ansässig ist. Wenn eines dieser Rechtssysteme versucht, Ihnen die Betriebserlaubnis zu entziehen oder die Vermögenswerte der Einleger zu beschlagnahmen, werden die Vermögenswerte automatisch mit Lichtgeschwindigkeit in ein anderes Rechtssystem übertragen.

## QUALITATIVE FORTSCHRITTE

Viele der Transaktionen, die Sie bald im Cyberspace durchführen können, wären im Industriezeitalter unmöglich gewesen, und das nicht nur, weil sie eine Sprachbarriere überwinden. Den digitalen Assistenten zu beauftragen, nicht übersetzte Artikel in ungarischen wissenschaftlichen Journals zu finden, ist qualitativ anders als mit einem Bibliothekar zu sprechen. Einem Oxford-Tutorium aus einer Entfernung von fünftausend Meilen beizuwohnen ist nicht dasselbe wie das Tutorium zu besuchen, wenn man nur sechs Meilen von Carfax entfernt schläft. Und das Spielen am Roulette-Rad im Hotel de Paris, Monte Carlo, ist eine neue Erfahrung, wenn man es auf einer Party in Punta del Este, Uruguay, durch Virtual Reality tun kann.

### Ein Cyberbesuch beim Cyberarzt

Innerhalb kürzester Zeit, schneller als viele Experten es derzeit für möglich halten, werden Tätigkeiten in die Cyberwirtschaft übergehen, die Technologien auf neuartige Weise kombinieren, um die Tyrannei des Ortes und die veralteten Institutionen der Industriewirtschaft zu überwinden. Wenn Sie Magenschmerzen haben, können Sie schon bald eine digitale Ärztin konsultieren, ein Expertensystem mit enzyklopädischem Wissen über Symptome, Krankheiten und Gegenmittel. Es wird auf Ihre Krankengeschichte in verschlüsselter Form zugreifen, fragen, ob Ihre Schmerzen nach dem Essen oder vor den Mahlzeiten auftreten. Ob sie stechend oder dumpf, anhaltend oder episodisch sind. Welche Fragen auch immer Ärzte stellen, der digitale Arzt wird sie stellen. Er kann feststellen, dass Sie zu viel Wein trinken, oder nicht genug. Sie könnten an einen Cyberspezialisten überwiesen werden. Wenn Sie eine Operation benötigen, könnte ein Cyberchirurg in Bermuda die Operation mit der Hilfe von spezialisierten Geräten, die Mikroeinschnitte durchführen, aus der Ferne durchführen.

### Lebenswichtige Informationsverarbeitung

Das mag alles wie Science-Fiction klingen. Aber viele der Komponenten der Cyberchirurgie sind bereits vorhanden. Andere werden bereits funktionsfähig sein, während Sie dieses Buch lesen. General Electric hat eine neue Magnetresonanztherapiemaschine (MRT) in fünfzehn Krankenhäusern auf der ganzen Welt eingeführt. Es wird erwartet, dass die Maschine eine dreijährige Forschungs- und Entwicklungsphase durchläuft, aber danach wird sie sich wahrscheinlich rapide ausbreiten und zur Norm für viele Arten von Operationen werden. Es ist ein Beispiel, aber ein gutes, dafür, wie die Technologie die Gesellschaft verändert.

Die meisten von uns sind mit Magnetresonanztomographie (MRT) -Maschinen vertraut, bei denen Magnetresonanzverfahren verwendet werden, um Ärzten weiche Gewebebilder zu diagnostischen Zwecken zur Verfügung zu stellen. Sie liefern bessere Bilder von weichem Gewebe als Röntgen oder Ultraschall und sind zu einem wesentlichen Teil moderner Diagnosetechniken geworden, insbesondere bei Krebserkrankungen. Sie haben jedoch derzeit zwei wesentliche Einschränkungen. Das Röhrensystem ermöglicht keinen freien Zugang zum Patienten; die Maschinen sind von begrenzter Leistung.

### Cyberchirurgie

General Electric hat Magnetresonanzmaschinen so überarbeitet, dass sie sowohl für die Behandlung als auch für die Diagnose eingesetzt werden können. Die Leistung wurde um das Fünffache erhöht. Die Röhre wurde im Grunde genommen in zwei Teile geschnitten, sodass der Patient nun zwischen zwei donutförmigen Einheiten liegt und nicht vollständig eingeschlossen wird. Anstatt ein Bild aufzunehmen und dann in Anbetracht dieses Bildes eine Operation durchzuführen, wird der Chirurg das, was er tut, sehen können, während er es tut. Die MRT wird mit nicht-invasiver oder weniger invasiver Chirurgie unter Einsatz von Mikrotechniken kombiniert werden. Anstatt große Einschnitte mit dem Skalpell zu machen, wird der Chirurg Mikroeinschnitte mit Sonden vornehmen und sehen können, was die Sonden während der Operation offenbaren. Er führt die Operation aus dem Bild heraus durch, anstatt direkt in den Körper zu schauen. Im Prinzip werden die Sonden aus der Ferne bedienbar sein. Sie werden in der Lage sein, Tumore mit Laser- oder Kryo-Heiz- oder Gefriergeräten von großer Präzision zu zerstören.

Dies wird Operationen ermöglichen, die heute noch unmöglich sind, insbesondere in der Neurochirurgie, wo Tumore oft sehr nahe an lebenswichtigen Gehirnregionen liegen. Es wird auch wiederholte Operationen erlauben, bei denen das Trauma der traditionellen chirurgischen Operation nicht ohne inakzeptable Schäden wiederholt werden kann. Einige Forscher sind der Meinung, dass das Skalpell für Weichteilchirurgie bis zum Jahr 2010 als ein veraltetes Relikt angesehen werden könnte. Eine Menge Angst und viele der Nachbeben werden aus der Chirurgie genommen, wenn das zutrifft. Offensichtlich ist dies eine sehr gute Nachricht für den Patienten. Operationen, die jetzt Stunden dauern und denen Tage oder Wochen im Krankenhaus folgen, werden nur eine halbe Stunde dauern und vielleicht überhaupt keine Krankenhausaufnahme erfordern. Es wäre möglich, dass sich der Chirurg und der Patient nie im selben Raum befinden. Aber was wird das für Krankenhäuser und Chirurgen bedeuten?

### Weniger Mikrochirurgen machen mehr.

Es wird eine Revolution in der Chirurgie geben. In der Ausbildung hat ein Drittel der jungen Chirurgen nicht die notwendigen Fertigkeiten für die Mikrochirurgie erworben. Ein Drittel schafft es gerade so, und ein Drittel ist hervorragend. Ähnliche Verhältnisse finden sich in Umschulungskursen für ältere Chirurgen. Weniger Chirurgen werden in der Lage sein, mehr Operationen in kürzerer Zeit durchzuführen. Es ist wahrscheinlich, dass Krankenkassen und Personen, die eine Operation suchen, auf Erfolgsstatistiken für jeden Chirurg bestehen werden, die recht unterschiedlich sein können. Patienten werden Chirurgen bevorzugen, die die besten Ergebnisse liefern, insbesondere wenn ihre Zustände lebensbedrohlich sind. In einigen Fällen können die besten Chirurgen sogar aus der Ferne operieren. Sie könnten die gesamte Operation aus einem anderen Rechtssystem heraus durchführen, in der die Steuern niedriger sind und Gerichte überhöhte Schadensersatzansprüche für Fehlverhalten nicht anerkennen.

### Digitale Anwälte

Bevor er der Durchführung einer Operation zustimmt, wird der erfahrene Chirurg wahrscheinlich auf einen digitalen Rechtsanwalt zurückgreifen, um einen sofortigen Vertrag zu entwerfen, der die Haftung auf der Grundlage der Größe und Eigenschaften des in den Bildern der Magnetresonanzmaschine dargestellten Tumors spezifiziert und begrenzt. Digitale Anwälte werden Informationserfassungssysteme sein, die die Auswahl der Vertragsbestimmungen automatisieren und künstliche Intelligenzverfahren wie neuronale Netzwerke nutzen, um private Verträge an transnationale rechtliche Bedingungen anzupassen. Teilnehmer an den meisten hochwertigen oder wichtigen Transaktionen werden nicht nur nach geeigneten Partnern suchen, mit denen sie Geschäfte abwickeln können; sie werden auch nach einem geeigneten Domizil für ihre Transaktionen suchen.

### Notfallberatung

Fahren wir mit dem Beispiel der Cyberchirurgie fort. Die Technologie des Informationszeitalters wird einen besonderen Wert auf die höchsten Fähigkeiten in der Chirurgie legen, wie es fast in jedem Bestreben der Fall sein wird. Patienten sind bereit gewesen, einen solchen Mehrwert so lange zu bezahlen, wie es Messer gegeben hat. Doch die Grenzen der Informationen und die Schwierigkeit, im Notfall an einem konkreten Ort nach Chirurgen zu suchen, haben den Markt für Chirurgie sehr unvollkommen gemacht. Er wird im Informationszeitalter weniger unvollkommen sein. Ein Patient, der innerhalb von 24 Stunden, oder vielleicht sogar 45 Minuten, eine Operation braucht, könnte digitale Assistenten beauftragen, die besten zehn Chirurgen weltweit zu finden, die bereit sind, solch eine Aufgabe aus der Ferne durchzuführen, ihre Erfolgsraten in ähnlichen Fällen zu überprüfen, und Angebote für ihren speziellen Fall von entsprechenden digitalen Dienern einzuholen. All dies könnte in wenigen Augenblicken abgewickelt werden. Als Folge dessen werden die bevorzugten 10 Prozent der Chirurgen einen sehr viel größeren Anteil am globalen Markt für Chirurgie haben. Die MRT-Maschine sowie Mikrochirurgietechniken werden den Mehrwert ihrer Arbeit erhöhen. Chirurgen mit geringeren Fähigkeiten werden sich auf lokale Restmärkte konzentrieren.

Dieses Beispiel von Leben und Tod hilft, einige der revolutionären Folgen der Befreiung von Volkswirtschaften von der Tyrannei der Räumlichkeit zu verdeutlichen. Jemand könnte einwenden, dass die MRT-Maschine von General Electric nicht dafür gedacht war, aus der Ferne eingesetzt zu werden. Vielleicht, aber das verfehlt den Punkt. Diese oder ähnliche Geräte werden es bald sein. Wenn Operationen besser von Chirurgen durchgeführt werden, die auf einen Bildschirm schauen, anstatt den Patienten direkt zu betrachten, wird es weniger wichtig sein, wo sich der Chirurg und sein Bildschirm befinden. Eine immer größere Anzahl von Dienstleistungen ist dazu bestimmt, neu konfiguriert zu werden, um die Tatsache zu berücksichtigen, dass Informationstechnologie es Personen auf der ganzen Welt ermöglicht, sogar in einer so heiklen Angelegenheit wie einer Operation, miteinander zu interagieren. In Aktivitäten, die weniger präzise Ausrüstungen erfordern und bei denen das Risiko eines Misserfolgs geringer ist, wird die Cyberökonomie noch schneller florieren.

> „Die Finanzpolitik des Wohlfahrtsstaates erfordert, dass es für die Eigentümer von Vermögen keine Möglichkeit gibt, sich selbst zu schützen." - Alan Greenspan

## Die Abschwächung des Zwangs

In nahezu jedem Wettbewerbsbereich, einschließlich des Großteils der weltweiten, billionenschweren Anlageaktivitäten, wird die Verlagerung von Transaktionen in den Cyberspace durch einen nahezu hydraulischen Druck angetrieben -- dem Bestreben, räuberischen Besteuerungen zu entgehen, einschließlich der Steuer, die die Inflation auf jeden ausübt, der sein Vermögen in einer nationalen Währung hält.

### Dem Schutzgeldsystem entfliehen

Sie müssen nicht lange über die Megapolitik des Informationszeitalters nachdenken, um zu erkennen, dass räuberische Steuern und Inflation, wie sie die reichsten Industrieländer ihren Bürgern mit einer Selbstverständlichkeit auferlegen, in den neuen Grenzen des Cyberspace lächerlich wettbewerbsunfähig sein werden. Kurz nach der Jahrtausendwende wird jeder, der Einkommenssteuern zu den derzeit aufgelegten Raten zahlt, dies aus freien Stücken tun. Wie Frederic C. Lane anmerkte, zeigt die Geschichte, dass „an den Grenzen und auf hoher See, wo niemand ein dauerhaftes Monopol auf die Anwendung von Gewalt hat, Händler die Zahlung von Abgaben vermieden, die so hoch waren, dass Schutz durch andere Mittel billiger zu bekommen war." [^255]:

Die Cyberwirtschaft bietet genau eine solche Alternative. Keine Regierung wird in der Lage sein, sie zu monopolisieren. Und die darin enthaltenen Informationstechnologien werden einen günstigeren und effektiveren Schutz für Finanzvermögen bieten, als es die meisten Regierungen jemals anbieten konnten.

### Die schwarze Magie des Zinseszinses

Bedenken Sie, dass jede jährliche Steuerzahlung von 5.000 Dollar, die über vierzig Jahre geleistet wird, Ihr Nettovermögen um 2,2 Millionen Dollar reduziert, vorausgesetzt, Sie könnten bloß eine 10-prozentige Rendite auf Ihr Kapital erzielen. Bei einer 20-prozentigen Rendite steigt der kumulierte Verlust auf etwa 44 Millionen Dollar. Für besserverdienende Personen in einem Hochsteuerland sind die kumulierten Verluste durch übermäßige Besteuerung im Laufe eines Lebens gewaltig. Die meisten verlieren mehr, als sie je besessen haben.

Das scheint unmöglich zu sein, aber die Mathematik ist eindeutig. Sie können dies selbst mit einem Taschenrechner überprüfen. Die obersten 1 Prozent der Steuerzahler in den Vereinigten Staaten zahlen im Durchschnitt jährlich mehr als 125.000 Dollar an Bundes-Einkommensteuern. Für einen Bruchteil dieses Betrags, nämlich 45.000 Dollar pro Jahr, könnte man in der Schweiz im Rahmen eines privaten Steuerabkommens leben und Recht und Ordnung genießen, die von dem wohl ehrlichsten Polizei- und Justizsystem der Welt gewährleistet werden. Aus dieser Perspektive könnten die zusätzlich über dieses großzügige Niveau hinaus gezahlten 80.000 Dollar an Einkommensteuer durchaus als Tribut oder Raub betrachtet werden. 45.000 Dollar sind sicherlich eine erhebliche Zahlung zur Aufrechterhaltung von Recht und Ordnung, wenn man bedenkt, dass polizeilicher Schutz als öffentliches Gut gedacht ist. Theoretisch können öffentliche Güter zu Grenzkosten von Null auf zusätzliche Nutzer ausgeweitet werden. Die Schweizer freuen sich, wenn Sie eine ausgehandelte feste Steuer von 45.000 Dollar (50.000 Schweizer Franken) pro Jahr zahlen, denn sie machen einen jährlichen Gewinn von 45.000 Dollar mit jedem Millionär, der sich anmeldet.

Im Vergleich zur Schweizer Alternative würden die lebenslang erlittenen Verluste für das Zahlen von Bundessteuern in den USA für einen Investor, der im Durchschnitt eine Rendite von 20 Prozent erzielen könnte, 705 Millionen Dollar betragen. Aber denken Sie daran, dass wir dabei von einer jährlichen Steuerzahlung von 45.000 Dollar ausgehen. Im Vergleich zu einem Steuerparadies wie Bermuda, wo die Einkommenssteuer null ist, würden die lebenslang erlittenen Verluste für das Zahlen von Steuern nach amerikanischen Sätzen etwa 1,1 Milliarden Dollar betragen.

Möglicherweise wenden Sie ein, dass eine jährliche Rendite von 20 Prozent eine hohe Rendite ist. Zweifellos hätten Sie recht. Aber angesichts des überragenden Wachstums in Asien in den letzten Jahrzehnten haben viele Anleger weltweit das und mehr bereits erreicht. Die durchschnittliche jährliche Rendite bei Immobilien in Hongkong beträgt seit 1950 über 20 Prozent. Sogar einige Volkswirtschaften, die weniger für ihr Wachstum bekannt sind, haben einfache Möglichkeiten für hohe Gewinne geboten. Sie hätten in den letzten drei Jahrzehnten mit Einlagen in US-Dollar in paraguayischen Banken eine durchschnittliche reale Rendite von mehr als 30 Prozent pro Jahr einstreichen können. Hohe Anlagerenditen sind an einigen Orten einfacher zu realisieren als an anderen, aber geschickte Anleger können sicherlich Gewinne von 20 Prozent oder mehr in guten Jahren erzielen, auch wenn sie nicht konstant die Leistungen von George Soros oder Warren Buffet erreichen.

Natürlich sind die Opportunitätskosten, die durch räuberische Einkommens- und Kapitalertragssteuern auferlegt werden, umso größer, je höher die Rendite ist, die Sie auf Ihr Kapital erzielen könnten. Aber die Schlussfolgerung, dass der Verlust enorm ist, in der Tat sogar größer als die gesamte Vermögenssumme, die Sie jemals ansammeln könnten, hängt nicht davon ab, dass Sie astronomische Renditen erreichen können. Einige Investmentfonds, die in den USA tätig sind, haben über einen Zeitraum von mehr als einem halben Jahrhundert durchschnittlich jährliche Gewinne von über 10 Prozent verzeichnet. Wenn Sie nicht besser abschneiden und zu den obersten 1 % der amerikanischen Einkommensbezieher gehören, dann verringert sich Ihr Nettowert um mehr als 33 Millionen Dollar allein durch die Einkommenssteuer, bei der Sie jährlich über 45.000 Dollar zahlen. Im Vergleich zu einem Land ohne Einkommensteuer beträgt der Verlust 55 Millionen Dollar.

### 55 Dollar statt 55 Millionen Dollar

Wenn die Gewinnmaximierungsannahmen der Ökonomen korrekt sind, wie wir allgemein annehmen, dann ist eine der sichersten Vorhersagen, die man machen kann, dass die meisten Menschen handeln würden, um 55 Millionen Dollar zu retten, wenn sie könnten. Das ist unsere Vorhersage. Wenn die schwarze Magie des Zinseszinses in den Köpfen der erfolgreichen Leute in Hochsteuerländern klarer wird, werden sie ausgiebig in verschiedenen Gerichtsbarkeiten einkaufen, so wie sie jetzt nach Autos suchen oder Versicherungstarife vergleichen. Wenn Sie daran zweifeln, halten Sie doch einfach mal ein paar Leute an, die zufällig auf den Straßen von New York oder Toronto herumlaufen und fragen sie, ob sie für 55 Millionen Dollar nach Bermuda ziehen würden. Die Frage beantwortet sich von selbst. Das Dilemma, das sie aufwirft, erinnert an das, was Mark Twain sich vorstellte, als er entschied, ob er lieber nackt mit Lillian Russell oder voll bekleidet mit General Grant übernachten würde. Er zögerte nicht lange. Die Einwohner ausgewachsener Wohlfahrtsstaaten, insbesondere der Vereinigten Staaten, sind vielleicht langsamer, aber nur, weil sie sich der Wahl, die sie haben, noch nicht bewusst sind. Zu gegebener Zeit werden sie sich dessen bewusst werden. Sie und jeder, der von dem Wunsch motiviert ist, ein besseres Leben zu führen, wird die Anziehungskraft verspüren, die Verluste zu reduzieren, die Sie durch räuberische Besteuerung erleiden. Sie müssen lediglich Ihre Transaktionen im Cyberspace durchführen. Dies wird natürlich in vielen Rechtssystemen illegal sein. Aber alte Gesetze haben neuen Technologien selten etwas entgegenzusetzen. In den 1980er Jahren war es in den Vereinigten Staaten illegal, eine Faxnachricht zu senden. Die U.S. Post betrachtete Faxe als Post der ersten Klasse, auf die die U.S. Post ein altes Monopol beanspruchte. Eine entsprechende Verordnung wurde erlassen, die die Anforderung wiederholte, dass alle Faxsendungen zur nächsten Poststelle geleitet werden, um mit der regulären Post geliefert zu werden. Milliarden von Faxnachrichten später ist immer noch unklar, ob diesem Gesetz jemals jemand nachgekommen ist. Wenn ja, dann war die Einhaltung nur von kurzer Dauer. Die Vorteile, in der aufkommenden Cyberwirtschaft zu arbeiten, sind noch überzeugender als das Umgehen der Post beim Senden eines Faxes.

Die weit verbreitete Einführung von Technologien zur Verschlüsselung mit öffentlichem und privatem Schlüssel wird es bald ermöglichen, viele wirtschaftliche Aktivitäten überall nach Belieben durchzuführen. Wie James Bennet, Technologie-Redakteur von Strategic Investment, geschrieben hat:

> Die Durchsetzung von Gesetzen, insbesondere Steuergesetzen, ist stark von der Überwachung von Kommunikation und Transaktionen abhängig. Wenn die nächsten logischen Schritte unternommen worden sind und Offshore-Bankstandorte die Dienste von Kommunikationen in starker RSA-Verschlüsselung mittels elektronischer Post anbieten, die Kontonummern aus öffentlichen Schlüsselsystemen verwendet, werden Finanztransaktionen fast unmöglich zu überwachen sein, egal ob bei der Bank oder in den Kommunikationen. Selbst wenn die Steuerbehörden einen Maulwurf in der Offshore-Bank platzieren würden oder die Bankdaten ausrauben würden, könnten sie die Einleger nicht identifizieren.[^256]:

In einem Umfang, der noch nie zuvor möglich war, werden Einzelpersonen bestimmen können, wo sie ihre wirtschaftlichen Aktivitäten ansiedeln und wie viel Einkommenssteuer sie vorziehen zu zahlen. Viele Transaktionen im Informationszeitalter werden überhaupt nicht in irgendeiner territorialen Souveränität angesiedelt sein müssen. Diejenigen, die es tun, werden zunehmend ihren Weg zu Orten wie Bermuda, den Cayman-Inseln, Uruguay oder ähnlichen Rechtssystemen finden, die keine Einkommensteuern oder andere kostspielige Belastungen auf den Handel erheben.

### Vom Monopol zur Konkurrenz

Regierungen haben sich daran gewöhnt, „Schutzdienste" aufzuerlegen, die, in den Worten von Frederic C. Lane, „von schlechter Qualität und skandalös überteuert" [^257]: sind. Dieser Brauch, weit mehr zu berechnen, als die Dienstleistungen der Regierung tatsächlich wert sind, entwickelte sich über Jahrhunderte des Monopols. Steuern wurden rücksichtslos für jeden erhöht, der fähig schien zu zahlen - gerade weil Regierungen ein Monopol oder Quasi-Monopol auf Zwang hatten. Diese Tradition des Monopols wird auf eine tiefgehende Weise mit den neuen megapolitischen Möglichkeiten des Cyberhandels kollidieren.

Die Verschlüsselung wird es einfach machen, Transaktionen im Cyberspace zu schützen. Die Kosten für ein effektives Verschlüsselungssoftwareprogramm wie PGP sind geringer als die Provision, die ein Full-Service-Broker für den Handel von hundert Aktien erhebt. Dennoch wird es fast jede Transaktion unsichtbar und unangreifbar für Regierungen und Diebe für viele Jahre in der Zukunft machen. Die neue Technologie des Informationszeitalters wird Cybervermögen zu verschwindend geringen Kosten effektiv schützen. Für 55 Dollar statt 55 Millionen Dollar werden Teilnehmer in der Cyberökonomie einen besseren und echteren Schutz ihrer Vermögenswerte genießen, als sie es in der Industrieära oder zu irgendeiner früheren Zeit in der Geschichte genossen haben. Leicht verwendbare Verschlüsselungsalgorithmen und die Fähigkeit, zwischen terrestrischen Domizilen für Transaktionen zu wählen, werden einen effektiven Schutz gegen die größte Quelle von Plünderungen bieten: die Nationalstaaten selbst.

Das bedeutet jedoch nicht, dass territoriale Regierungen vollständig ausmanövriert werden. Sie werden immer noch in der Lage sein, Schwachstellen zum persönlichen Schaden auszunutzen, um Kopfsteuern zu erheben oder vielleicht sogar wohlhabende Einzelpersonen zu erpressen. Sie könnten auch die Erhebung von Verbrauchssteuern durchsetzen. Der Schutz, die wichtigste staatliche Dienstleistung, wird jedoch auf eine nahezu wettbewerbsfähige Grundlage gestellt. Weniger von den Kosten, die produktive Menschen für ihren Schutz zahlen, können von den politischen Behörden beschlagnahmt und umverteilt werden. Technologische Innovationen werden einen großen und wachsenden Teil des weltweiten Reichtums außerhalb der Reichweite von Regierungen platzieren. Dies verringert die Risiken des Handels und senkt, in den Worten der Historikerin Janet Abu-Lughod, „den Anteil aller Kosten", der andernfalls „für Transitzölle, Tribut oder einfache Erpressung" aufgewendet werden müsste.[^258]:

Es kam in der Geschichte selten vor, dass Regierungen wirklich durch Wettbewerb eingeschränkt waren. In den wenigen Zeiten, in denen so etwas passiert ist, waren die Regierungen schwach und die Technologie zwischen Rechtssystemen ähnlich. Wie Lane vorschlug, neigt der Hauptfaktor, der die Rentabilität unter solchen Bedingungen beeinflusst, dazu, der Unterschied in den Schutzkosten zu sein, die verschiedene Unternehmer zahlen müssen. Der mittelalterliche Kaufmann, der zwanzig verschiedene Zollgebühren zahlen musste, um seine Waren zum Markt zu bringen, konnte nicht mit einem Kaufmann konkurrieren, der nur vier Zollgebühren zahlen musste, um die gleichen Waren zum Kunden zu liefern. Ähnliche Bedingungen werden mit dem Informationszeitalter zurückkehren. Die Rentabilität wird erneut nicht so sehr vom technologischen Vorsprung abhängen, sondern davon, ob es Ihnen gelingt, die Kosten, die Sie für Ihren Schutz zahlen müssen, zu minimieren.

Diese neue ökonomische Dynamik steht in direktem Gegensatz zu den Wunschvorstellungen von Regierungen aus der industriellen Ära, Monopolpreise für ihre Schutzdienstleistungen durchzusetzen. Aber ob es uns gefällt oder nicht, das alte System wird in der neuen Wettbewerbsumgebung des Informationszeitalters nicht mehr lebensfähig sein. Jede Regierung, die darauf besteht, ihre Bürger mit hohen Steuern zu belasten, die Wettbewerber nicht zahlen, wird lediglich sicherstellen, dass Gewinne und Reichtum anderswo hingelangen. Daher wird das Versagen der reifen Wohlfahrtsstaaten, die Steuern langfristig zu senken, sich selbst korrigieren. Regierungen, die zu stark besteuern, machen das Wohnen innerhalb ihres Einflussbereichs zu einem Insolvenzantrag.

> „...wie der König nach seinem Ermessen Geld aus beliebigem Material und in beliebiger Form herstellen und den Standard dafür festlegen kann, so kann er sein Geld in Substanz und Prägung ändern, den Wert davon erhöhen oder mindern, oder es vollständig entwerten und annullieren" [^259]: - Aus einer englischen Gerichtsentscheidung, 1604

## DAS ENDE DER SEIGNIORAGE

Regierungen werden nicht nur ihre Macht verlieren, viele Arten von Einkommen und Vermögen zu besteuern; sie sind auch dazu bestimmt, ihr Machtmonopol über Geld zu verlieren. In der Vergangenheit waren megapolitische Übergänge mit Veränderungen in der Eigenschaft von Geld verbunden.

-   Die Einführung des Münzwesens trug dazu bei, den fünfhundertjährigen Expansionszyklus der antiken Wirtschaft einzuleiten, der mit der Geburt Christi und den niedrigsten Zinssätzen vor der Neuzeit seinen Höhepunkt erreichte.
-   Der Beginn des Dunklen Zeitalters fiel mit der faktischen Schließung der Münzstätten zusammen. Römische Münzen zirkulierten zwar weiterhin, aber die Geldmenge ging zusammen mit dem Handel in einer sich selbst verstärkenden Abwärtsspirale zurück.
-   Die feudale Revolution fiel mit der Wiedereinführung von Geld, Münzen, Wechseln und anderen Instrumenten zur Abwicklung von Handelsgeschäften zusammen. Insbesondere der Anstieg der europäischen Silberproduktion durch die neuen Minen am Rammelsberg in Deutschland ermöglichte eine Zunahme des Münzumlaufs, der den Handel ankurbelte.
-   Die größte Revolution des Geldes vor dem Informationszeitalter kam mit dem Aufkommen der Industrialisierung. In der Schießpulverrevolution festigte der frühneuzeitliche Staat seine Macht. In dem Maße, wie seine Kontrolle zunahm, machte der Staat seine Macht über das Geld geltend und stützte sich dabei in hohem Maße auf die charakteristische Technologie der Industrialisierung, die Druckerpresse. Das erste Instrument der Massenproduktion, die Druckerpresse, wurde von den Regierungen in der Neuzeit häufig zur Massenproduktion von Papiergeld eingesetzt.

Papiergeld ist ein eindeutig industrielles Produkt. Vor der Erfindung der Druckpresse wäre es unpraktisch gewesen, Quittungen oder Zertifikate zu duplizieren, die zu Papiergeld wurden. Mönche in Skriptorien hätten ihre Zeit verschwendet, Fünfzig-Pfund-Noten zu zeichnen. Papiergeld hat auch erheblich zur Macht des Staates beigetragen, nicht nur durch Gewinne aus der Abwertung der Währung, sondern auch dadurch, dass der Staat Einfluss darauf hatte, wer Reichtum ansammeln konnte. Wie Abu-Lughod es formulierte: „Wenn Papiergeld, das vom Staat gedeckt wird, zur anerkannten Währung wird, wird es schwierig, Kapital entgegen oder unabhängig von den staatlichen Maschinerien anzuhäufen." [^260]:

## CYBERGELD

Nun bedeutet das Aufkommen des Informationszeitalters eine weitere Revolution in der Eigenschaft des Geldes. Mit dem Beginn des Cyberhandels führt der Weg unweigerlich zum Cybergeld. Diese neue Art des Geldes wird das bisherige Kräfteverhältnis neu ausrichten, indem es die Fähigkeit der Nationen der Welt reduziert, darüber zu bestimmen, wer zum souveränen Individuum wird. Ein entscheidender Teil dieser Veränderung wird sich durch den Einfluss der Informationstechnologie vollziehen, indem sie Vermögensinhaber vor einer Enteignung durch Inflation schützt. Bald werden Sie fast jede Transaktion über das Internet oder das World Wide Web zur gleichen Zeit, in der sie die Transaktion tätigen, mit Cybergeld bezahlen.

Diese neue digitale Form von Geld ist dazu bestimmt, eine entscheidende Rolle im Cyberhandel zu spielen. Es wird aus verschlüsselten Sequenzen von mehreren hundertstelligen Primzahlen bestehen. Einzigartig, anonym und überprüfbar, wird dieses Geld die umfangreichsten Transaktionen ermöglichen. Es wird außerdem in den kleinsten Bruchteil des Wertes teilbar sein. Durch das Drücken einer Taste kann es in einem billionenschweren Großhandelsmarkt ohne Grenzen gehandelt werden.

### Die Wahl des Geldes

Unweigerlich wird dieses neue Cybergeld entnationalisiert werden. Wenn souveräne Individuen in einem Bereich ohne physische Realität über Grenzen hinweg handeln können, werden sie es nicht mehr erdulden müssen, dass Regierungen den Wert ihres Geldes durch Inflation mindern. Warum sollten sie auch? Die Kontrolle über das Geld wird von den Machtzentralen auf den globalen Marktplatz verlagert. Jede Einzelperson oder Firma mit Zugang zum Cyberspace wird in der Lage sein, problemlos aus einer Währung auszusteigen, die Gefahr läuft, an Wert zu verlieren. Anders als heute wird es keine Notwendigkeit geben, in gesetzlichen Zahlungsmitteln zu handeln. Tatsächlich ist es wahrscheinlich, dass bei Transaktionen, die den Globus umspannen, mindestens eine Partei in einer Währung handeln wird, die für sie kein gesetzliches Zahlungsmittel ist.

### Die Reduzierung der Nachteile des Tauschhandels

Sie werden in der Lage sein, in der Cyberökonomie in jedem Medium Ihrer Wahl zu handeln. Wie der verstorbene, mit dem Nobelpreis ausgezeichnete Wirtschaftswissenschaftler F. A. von Hayek argumentierte, gibt es „keinen eindeutigen Unterschied zwischen Geld und Nicht-Geld". Er schrieb: „Obwohl wir für gewöhnlich annehmen, dass es eine klare Unterscheidung zwischen dem gibt, was Geld ist und was nicht - und das Gesetz im Allgemeinen versucht, eine solche Unterscheidung zu machen - gibt es keinen so klaren Unterschied, was die kausalen Auswirkungen von monetären Ereignissen betrifft. Was wir stattdessen vielmehr vorfinden, ist ein Kontinuum, in dem Objekte unterschiedlicher Liquidität oder mit Werten, die unabhängig voneinander schwanken können, in dem Maße ineinander übergehen, wie sie als Geld funktionieren." [^261]: Digitales Geld in globalen Computernetzwerken wird jedes Objekt auf Hayeks Kontinuum der Liquidität flüssiger machen - mit Ausnahme von staatlichen Papieren. Eine Folge davon wird sein, dass der Tauschhandel viel praktischer wird. Eine wachsende Anzahl von Objekten und Dienstleistungen wird in spezifischen Angeboten für andere Objekte und Dienstleistungen angeboten. Diese potenziellen Transaktionen werden weltweit im Netz beworben, was ihre Liquidität um ein Vielfaches erhöht.

Eines der Hauptprobleme des Tauschhandels war immer die Schwierigkeit, eine Person mit einem bestimmten Bedarf mit einer anderen zu verbinden, die genau dieses Angebot hatte und genau das erwerben wollte, was die erste Partei zum Tausch anbot. Der primitive Tauschhandel stolperte über die entmutigende Unwahrscheinlichkeit, genau zwei Parteien in einem lokalen Markt zu finden, die einen Austausch wünschten. Bargeld überwand die Beschränkungen des Tauschhandels, und seine Vorteile bleiben in den meisten Transaktionen überzeugend. Aber enorme Zunahmen der Rechenleistung und die Globalisierung des Handels im Cyberspace verringern auch die Nachteile des Tauschhandels. Die Chancen, jemanden mit genau entsprechenden Wünschen zu finden, steigen dramatisch, wenn Sie sofort weltweit suchen können, anstatt sich nur auf diejenigen zu beschränken, die Sie lokal treffen könnten.

### Unfälschbar

Obwohl Papiergeld zweifellos weiterhin als verbliebenes Tauschmedium für die Armen und diejenigen, die mit Computern nicht umgehen können, im Umlauf bleiben wird, wird das Geld für Transaktionen von hohem Wert privatisiert. Cyber-Geld wird nicht mehr nur in nationalen Einheiten, wie das Papiergeld der Industriezeit, bemessen sein. Wahrscheinlich wird es nach Gramm oder Unzen Gold definiert, so fein teilbar wie das Gold selbst. Oder es könnte auf Basis anderer realer Wertspeicher definiert werden. Selbst dort, wo unterschiedliche Preismaßstäbe verwendet werden oder bestimmte Transaktionen weiterhin in nationalen Währungen bemessen werden, wird das Cyber-Geld den Verbrauchern weitaus besser dienen als staatliches Geld es jemals konnte. Die rasch voranschreitende Rechenkapazität wird die Schwierigkeiten, Preise an verschiedene Tauschmittel anzupassen, auf ein Minimum reduzieren. Jede Transaktion beinhaltet die Übertragung verschlüsselter mehrerer hundertstelliger Primzahlenfolgen. Im Gegensatz zu den von Regierungen im Zeitalter des Goldstandards ausgegebenen Papiergeldscheinen, die nach Belieben dupliziert werden konnten, wird der neue digitale Goldstandard oder seine Tauschwertäquivalente fast unmöglich zu fälschen sein. Der zugrundeliegende mathematische Beweis dafür lautet, dass es nahezu unmöglich ist, das Produkt aus mehreren hundertstelligen Primzahlen zu entwirren. Alle Quittungen werden nachweislich einzigartig sein.

Die Namen traditioneller Währungen wie „Pfund" und „Peso" spiegeln die Tatsache wider, dass sie ursprünglich als Maßeinheiten für das Gewicht bestimmter Mengen von Edelmetallen entstanden sind. Das Pfund Sterling war einmal ein Pfund Sterlingsilber. Papiergeld im Westen begann als Lager- oder Safedepot-Scheine für Mengen von Edelmetallen. Regierungen, die diese Scheine ausgaben, stellten bald fest, dass sie deutlich mehr davon drucken konnten, als sie tatsächlich aus ihrem Gold- und Silberbestand einlösen konnten. Das war einfach. Keine Person, die ein Gold- oder Silberzertifikat besaß, konnte irgendeine Information über den tatsächlichen Vorrat an Edelmetallen aus ihrer Quittung entnehmen. Abgesehen von den Seriennummern sahen alle Scheine gleich aus, eine Tatsache, die sowohl Fälschern als auch Politikern und Bankern gefiel, die von der Inflation der Geldmenge profitieren wollten.

Cyberwährungen werden auf diese Weise praktisch unmöglich zu fälschen sein, ob offiziell oder inoffiziell. Die Überprüfbarkeit der digitalen Belege schließt dieses klassische Mittel zur Enteignung von Vermögen durch Inflation aus. Das neue digitale Geld des Informationszeitalters wird die Kontrolle über das Tauschmedium wieder den Eigentümern von Vermögen zurückgeben, die es bewahren möchten, anstatt es den Nationalstaaten zu überlassen, die es verschwinden lassen möchten.

### Die Transaktionskosten von \"freier\" Währung

Die Nutzung dieser neuen Cyber-Währung wird Sie weitgehend von der Macht des Staates befreien. Früher haben wir die trostlose Bilanz der nationalstaatlichen Welt in Bezug auf die Werterhaltung ihrer Währungen über das letzte halbe Jahrhundert erwähnt. Seit dem Zweiten Weltkrieg hat keine Währung weniger Wert durch Inflation verloren als die Deutsche Mark. Und dennoch verschwand zwischen dem 1. Januar 1949 und Ende Juni 1995 sogar 71 Prozent ihres Wertes. Die Weltreservewährung in dieser Zeit, der US-Dollar, verlor 84 Prozent seines Wertes.[^262]: Dies ist ein Maß für den Reichtum, den Regierungen durch Ausnutzung ihrer territorialen Monopole auf gesetzliche Zahlungsmittel enteigneten.

Beachten Sie, dass es keine intrinsische Notwendigkeit gibt, dass eine Währung abwertet oder die nominellen Lebenshaltungskosten jedes Jahr steigen. Im Gegenteil. Die technische Herausforderung, die Kaufkraft von Ersparnissen aufrechtzuerhalten, ist trivial. Dies wird deutlich, wenn Sie sich einfach die langfristige Kaufkraft von Gold ansehen.

Zwischen dem 1. Januar 1949 und Ende Juni 1995 verlor die beste der nationalisierten Währungen fast drei Viertel ihres Wertes, während die Kaufkraft von Gold tatsächlich stieg. Wie Professor Roy W. Jastrom in seinem Buch *The Golden Constant* dokumentiert hat, hat Gold seine Kaufkraft mit geringfügigen Schwankungen so lange aufrechterhalten, wie zuverlässige Preisaufzeichnungen verfügbar sind, im Falle Englands bis 1560.

Nationalwährungen, die an Gold gebunden sind, haben ihre Kaufkraft auch dann bewahrt, wenn militärische Notwendigkeiten nicht erdrückend waren. Der Wert des britischen Pfunds Sterling stieg im relativ friedlichen 19. Jahrhundert eher an, obwohl es nur lose mit Gold verbunden war. Die neuen megapolitischen Bedingungen des Informationszeitalters machen jedoch nicht eine schwache Verbindung, wie den Goldstandard, sondern eine starke Verbindung möglich, die zum ersten Mal durch erheblich verbesserte Informations- und Rechenressourcen in den Händen der Verbraucher gestärkt wird.

> „Die Bedrohung durch den schnellen Verlust ihres gesamten Geschäfts, wenn sie die Erwartungen nicht erfüllen (und wie jede Regierungsorganisation sicherlich die Gelegenheit missbrauchen wird, mit Rohstoffpreisen zu spielen!), würde einen viel stärkeren Schutz bieten als jeder, der gegen ein Regierungsmonopol entwickelt werden wird" [^263]: - Friedrich A. Von Hayek

### Die Privatisierung von Geld

Friedrich von Hayek argumentierte 1976, dass der Einsatz von wettbewerbsfähigen, privaten Währungen die Inflation beseitigen würde.[^264]: Ohne Anforderungen an gesetzliche Zahlungsmittel, die die Annahme einer im Wert steigenden Währung innerhalb eines Rechtssystems erzwingen, argumentierte Hayek, würde der Markt den privaten Emittenten von Währungen auferlegen, den Wert ihres Tauschmediums zu erhalten. Jeder Emittent einer privaten Währung, der es nicht schafft, seinen Wert zu erhalten, würde bald seine Kunden verlieren. Die Entwicklung von verschlüsseltem Cybercash wird Hayeks Logik anschaulich zum Leben erwecken.

Die Theorie des „freien Bankwesens", wie es genannt wird, ist nicht bloß ein hypothetisches akademisches Gedankenspiel. Private, konkurrierende Währungen zirkulierten in Schottland von Anfang des achtzehnten Jahrhunderts bis 1844. Während dieser Zeit gab es in Schottland keine Zentralbank. Es gab wenige Vorschriften oder Beschränkungen für den Eintritt in das Bankgeschäft. Private Banken nahmen Einlagen entgegen und gaben ihre eigenen privaten Währungen aus, die durch Goldbarren gedeckt waren. Wie Professor Lawrence White dokumentiert hat, hat dieses System gut funktioniert. Es war stabiler, mit weniger Inflation als das stärker regulierte und politisierte System des Bankwesens und des Geldes, das in England während der gleichen Zeit angewendet wurde.[^265]: Michael Prowse von der Financial Times fasste die Erfahrungen Schottlands mit dem freien Bankwesen zusammen: „Es gab wenig Betrug. Es gab keine Anzeichen für eine Überausgabe von Banknoten. Die Banken hielten in der Regel weder übermäßige noch unzureichende Reserven. Bank Runs waren selten und uferten nicht aus. Die freien Banken genossen das Ansehen der Bürger und bildeten eine solide Grundlage für ein Wirtschaftswachstum, das das in England für die meiste Zeit dieser Periode übertraf." [^266]:

Was unter den technologischen Bedingungen des achtzehnten und neunzehnten Jahrhunderts gut funktioniert hat, wird mit der Technologie des einundzwanzigsten Jahrhunderts sogar noch besser funktionieren. Sie werden bald in der Lage sein, mit digitalem Geld von einer privaten Firma zu handeln, das ähnlich ausgegeben wird, wie American Express Reiseschecks als Belege für Bargeld ausstellt. Eine Institution von höherem Ansehen als jede Regierung, wie zum Beispiel ein führendes Bergbauunternehmen oder die Swiss Bank Corporation, könnte verschlüsselte Quittungen für Goldmengen oder sogar für einzigartige Goldbarren erstellen, die durch molekulare Signaturen identifiziert und möglicherweise sogar mit Hologrammen beschriftet werden. Diese Quittungen werden dann als Geld gehandelt, mit fast keiner Möglichkeit, dass sie gefälscht oder inflationiert werden können.

Das neue digitale Gold wird viele der praktischen Probleme, die die direkte Nutzung von Gold als Geld in der Vergangenheit gehemmt haben, überwinden. Es wird nicht länger unpraktisch, umständlich oder gefährlich sein, mit großen Summen von Gold zu handeln. Digitale Quittungen werden nicht zu schwer zum Tragen sein. Tatsächlich wird ihre einzige physische Existenz in aufwendigen Mustern von Computercode bestehen. Ebenso wird es nicht schwierig sein, digitale Quittungen in so kleine Einheiten zu unterteilen, dass sie selbst für Mikro-Käufe genutzt werden können. Ein winziges Stück physisches Gold, klein genug, um damit einen Kaugummi zu bezahlen, würde bald verloren gehen oder mit einem Stück verwechselt werden, das klein genug ist, um zwei Kaugummis zu bezahlen. Aber für den Computer wird es einfach sein, diese Stückelungen von digitalem Geld zu unterscheiden, egal ob es die Größe eines Streifenhörnchens oder die eines Nashorns hat.

Die Fähigkeit von digitalem Geld, Mikrozahlungen zu ermöglichen, wird die Entstehung von neuen Geschäftsarten begünstigen, die bisher nicht existieren konnten, die sich auf die Organisation der Verteilung von Informationen mit geringem Wert spezialisieren. Die Anbieter dieser Informationen werden nun durch Direkt-Abbuchungsgebührensysteme entschädigt, die die bisher abschreckenden Transaktionskosten überwinden. Wenn die Kosten für die Rechnungsstellung den Wert einer Transaktion überschreiten, wird sie wahrscheinlich nicht stattfinden. Die Nutzung von Cyber-Geld erleichtert sehr kostengünstige gleichzeitige Abrechnungen, bei denen Konten mit deren Nutzung belastet werden. Wir zitierten ein solches Beispiel oben, indem wir uns vorstellten, dass Sie möglicherweise eine Lizenzgebühr in Höhe von einem Drittel eines Pennys an Bill Gates, oder wer auch immer die virtuellen Realitätsrechte für eine Tour durch den Louvre besitzt, zahlen könnten. Dies kann auf tausend Arten geschehen. Die virtuelle Realität wird nahezu unbegrenzte Lizenzierungsmöglichkeiten schaffen, die dennoch nur Mikro-Lizenzgebühren einfordern. Eines Tages werden Sie in der Lage sein, das dritte Spiel der World Series von 1969 erneut anzusehen und Mikrolizenzen an die Spieler zu zahlen, deren Bilder verwendet werden, um Ihre virtuelle Realität real erscheinen zu lassen.

## INFLATION BESEITIGEN

Ungeachtet solcher Möglichkeiten dürfte die bedeutendste Auswirkung des neuen digitalen Geldes das Ende der Inflation und die Entschuldung des Finanzsystems sein. Die wirtschaftlichen Implikationen sind tiefgreifend. Der Anstieg der Inflation im zwanzigsten Jahrhundert, wie wir es in *Blood in the Streets* und *The Great Reckoning* dargelegt haben, war eng mit der weltweiten Machtverteilung verbunden. Steigende Erträge durch Gewaltanwendung erforderten drastisch höhere Militärausgaben, die wiederum immer aggressivere Bemühungen zur Enteignung von Reichtum notwendig machten. Regierungen entdeckten, dass sie effektiv eine jährliche Vermögenssteuer auf alle erheben konnten, die Guthaben in ihrer nationalen Währung hielten. Diese jährliche Vermögenssteuer auf Währungsinhaber konnte auch als Transaktionsgebühr gesehen werden, die den Nutzern der Währung erlaubte, ihren Reichtum in einer von den Emittenten bereitgestellten bequemen Form zu halten.[^269]:

Es mag ungewöhnlich sein, die Inflation als eine Transaktionsgebühr für die Bequemlichkeit des Geldbesitzes zu betrachten, aber denken Sie genau darüber nach. Während des Industriezeitalters haben wir uns so sehr daran gewöhnt, die Bereitstellung von Währung als Dienstleistung zu sehen, für die man nicht direkt bezahlt, dass es leicht war zu vergessen, dass die Ausgeber der Dollars, Pesos, Pfund und Franken, nämlich die Regierungen, von uns verlangt haben, dass wir dafür bezahlen, und zwar teuer -- durch Inflation. Die Rate dieser inflatorischen Transaktionsgebühr auf Währung variierte im letzten halben Jahrhundert von einem Tiefststand von 2,7 Prozent jährlich für die Deutsche Mark bis hin zu Raten, die gefährlich nahe an 100 Prozent lagen. So wurden beispielsweise zwischen 1960 und 1991, als Präsident Menem die argentinische Währungsreform einleitete, durch die Inflation siebzehn Nullen aus den verschiedenen Versionen der argentinischen Währung gestrichen. Wenn 1960 der gesamte Reichtum der Welt in argentinische Pesos umgewandelt und vergraben worden wäre, wäre es 1991 nicht mehr die Mühe wert gewesen, diesen wieder auszugraben.

Argentiniens Beispiel ist ein führender Indikator für das nächste Jahrtausend. Währung wird nicht mehr inflationierbar sein, weil andere Staaten nicht mehr damit davonkommen, ebenso wie Argentinien es nicht mehr kann. Inflation hatte in der Industriezeit, als die Preise und Löhne nach unten hin unflexibel waren, eine weitere Verlockung. Eine mäßige Inflation erhöht die Produktion durch Senkung der Reallöhne, und die Preise könnten durch eine aus anderen Ländern importierte Kreditverknappung beeinträchtigt werden. Privates Geld wird aufgrund des Wettbewerbsdrucks nicht inflationierbar sein.

Die Beseitigung der Inflation wird die getarnten Profite wegnehmen, die die Inflation bisher denjenigen zukommen ließ, die die monopolistischen Ausgeber der Währung waren. Falls alle getarnten Gewinne aus der Ausgabe von Geld verschwinden würden, wäre eine neue Zahlungsmethode notwendig, um die Währungsausgeber direkt zu entschädigen. Die Nutzung des neuen Geldsystems wird daher wahrscheinlich explizitere Transaktionskosten beinhalten, vielleicht eine Gebühr in der Größenordnung von 1 Prozent pro Jahr. Das ist ein kleiner Preis im Vergleich zu der jährlichen Inflationsstrafe von 2,7 bis 99 Prozent, die von Nationalstaaten verhängt wird. Dies gilt umso mehr, da die Wahrscheinlichkeit besteht, dass die Gesamtpreise in Zukunft sinken werden, wenn Monopole abgebaut werden und der Wettbewerb weltweit zunimmt.

### Vertragliche Hebelwirkung

Das Aufkommen digitaler Geldarten wird nicht nur ein für alle Mal die Inflation besiegen; es wird auch den Hebel in den Bankensystemen der Welt reduzieren. Die Fähigkeit von Menschen auf der ganzen Welt, regulatorische Behörden zu umgehen und ihre Gelder direkt über das Internet zu verschieben, ist eine völlig beispiellose Folge der Globalisierung der Märkte. Es wird jenseits der Macht jeder Regierung liegen, dies zu regulieren. Wenn Regierungen nicht mehr in der Lage sind, Währungen durch Gelddrucken zu entwerten oder die Sparer zu betrügen, indem sie die Kreditvergabe über die konzerneigenen Bankensysteme nach Belieben ausweiten, verlieren sie einen großen Teil ihrer indirekten Fähigkeit, Ressourcen zu beschlagnahmen.

### Höhere Zinssätze

Dies wird ein offensichtliches Dilemma für die meisten westlichen Regierungen schaffen. Sie werden mit starken Einbußen bei den Steuereinnahmen und der faktischen Abschaffung der Hebelwirkung im Geldsystem konfrontiert sein. Gleichzeitig werden sie die ungedeckten Verpflichtungen und die aufgeblähten Erwartungen für Sozialausgaben, die aus der Industrieära geerbt wurden, beibehalten. Das erwartete Resultat ist eine intensive fiskale Krise mit vielen unangenehmen sozialen Nebenwirkungen, die wir in den späteren Kapiteln berücksichtigen werden. Die wirtschaftliche Konsequenz dieser Übergangskrise wird wahrscheinlich einen einmaligen Anstieg der realen Zinssätze beinhalten. Die Schuldner werden in Bedrängnis geraten, da langfristige Verbindlichkeiten, die unter dem alten System eingegangen wurden, abgewickelt werden und Vorzugskredite versiegen.

### Durch den Wettbewerb verändert

Regierungen, die mit ernsthafter Konkurrenz zu ihren Währungsmonopolen konfrontiert sind, werden wahrscheinlich versuchen, die kostenpflichtigen Cyberwährungen zu unterbieten, indem sie Kredite straffen und Sparern höhere tatsächliche Renditen auf Kontoguthaben in nationalen Währungen bieten. Einige Regierungen könnten sogar danach streben, Gold als weiteres Mittel zur Bewältigung des Wettbewerbs von privaten Währungen wieder zu monetarisieren. Sie könnten zu dem Schluss kommen, dass sie höhere Seigniorage-Gewinne von einem locker kontrollierten Goldstandard des 19. Jahrhunderts erzielen könnten, als wenn sie es zulassen würden, dass ihre nationale Währung vollständig durch kommerzielles Cyber-Geld ersetzt wird. Aber nicht alle Regierungen werden auf die gleiche Weise reagieren. Diejenigen, die in Regionen leben, in denen die Computernutzung und die Beteiligung am Netz gering sind, können sich in der Anfangsphase der Cyberwirtschaft für eine altmodische Hyperinflation entscheiden. Das wird es diesen Regierungen nicht ermöglichen, sich die Geldbestände der Reichen zu sichern, aber es wird Ressourcen von denen abzwacken, die wenig Vermögen oder Zugang zur Cyberwirtschaft haben. Regierungen, die solche Taktiken anwenden, könnten sich nichtsdestotrotz international Geld in der Cyberwährung leihen.

Andere Regierungen könnten sich den Chancen anpassen, die durch die Informationswirtschaft entstehen, und lokale Transaktionen in Cyberwährung erleichtern. Diejenigen Rechtsgebiete, die die Gültigkeit digitaler Signaturen als erste anerkennen und die Zwangsvollstreckung bei Nichtbezahlung von Cyberschulden vor Ort ermöglichen, werden von einem unverhältnismäßig starken Anstieg der langfristigen Kapitalvergabe profitieren. Natürlich wäre in Gebieten, in denen lokale Gerichte Strafen verhängen oder Schuldnern einen Zahlungsausfall ohne rechtliche Konsequenzen gestatten, kein Cyber-Geld für langfristige Kredite verfügbar.

### Ertragslücke

Die Kombination aus Kreditkrisen, wettbewerbsbedingten Anpassungen durch nationale Währungsbehörden und anfänglichen Übergangshürden bei der Vergabe von Cyberwährungskrediten wird in den Anfangsstadien der Informationswirtschaft zu einer Renditelücke führen. Cyber-Geld wird niedrigere Zinssätze als nationale Währungen zahlen und wahrscheinlich auch explizite Transaktionskosten tragen. Diese offensichtlichen Nachteile des Haltens von Guthaben in digitaler Währung werden jedoch durch einen verbesserten Schutz vor Verlusten aus Raubsteuern und Inflation ausgeglichen. Da es wahrscheinlich an Gold gebunden ist, wird Cyber-Geld auch von der Aufwertung des Goldes profitieren. Der Goldpreis wird wahrscheinlich deutlich steigen, unabhängig davon, welche der alternativen Regierungspolitiken dominiert. Warum? Der reale Goldpreis steigt praktisch immer in einer Deflation. Eine Deflation spiegelt schließlich einen Liquiditätsmangel wider. Und Gold ist die ultimative Form der Liquidität.

### Die Deflation des Industriezeitalters

Höhere Realzinsen überall werden die Liquidierung von kostenintensiven, unproduktiven Aktivitäten anspornen und vorübergehend den Konsum reduzieren. Wir haben die Logik des Konjunkturzyklus und seine Auflösung in *Blood in the Streets* und *The Great Reckoning* untersucht, daher werden wir diese Argumente hier nicht erneut durchgehen. Es genügt an dieser Stelle zu erwähnen, dass sich das deflationäre Umfeld noch einige Zeit hinziehen könnte, mit größeren Konsequenzen für die industriellen Hochlohnländer Nordamerikas und Westeuropas als für die Niedriglohnländer Asiens und Lateinamerikas.

## Langfristig niedrigere Zinssätze

Während die frühen Auswirkungen des Aufkommens der Cyberwirtschaft wahrscheinlich höhere Zinsen beinhalten werden, wird die langfristige Konsequenz genau das Gegenteil sein. Die nach Steuern abgezogenen Erträge für die Sparer werden deutlich steigen, sobald die Ressourcen dem Zugriff der Regierungen entkommen. Dramatische Verbesserungen bei der Effizienz der Ressourcennutzung und die Befreiung von Kapital, um weltweit die höchsten Renditen zu finden, sollten schnell für den Verlust an Produktion entschädigen, der zu Anfang in der Übergangskrise eintritt.

### Anlegerkontrolle über das Kapital

Konventionelle Denker, die unser Argument bis hierhin betrachten, würden zu dem Schluss kommen, dass der Zusammenbruch der Einkommensumverteilung in den führenden Nationenstaaten die Welt in einen wirtschaftlichen Kollaps stürzen würde. Glauben Sie das nicht! Wir bestreiten nicht die Tatsache, dass eine Übergangskrise wahrscheinlich ist. Aber die Ansicht, dass der Staat die Funktionsweise der Wirtschaft durch massive Umverteilung von Ressourcen verbessert, ist ein Anachronismus, ein Glaubensgrundsatz, der etwa dem weit verbreiteten Aberglauben am Ende des Mittelalters entspricht, dass Fasten und Selbstkasteiung einer Gemeinschaft zugutekamen. Es sollte nicht vergessen werden, dass Regierungen Ressourcen in großem Stil verschwenden. Verschwenderischer Umgang mit Ressourcen macht arm. Eine dramatische Verbesserung der Effizienz der Ressourcennutzung wird eintreten, wenn die Einnahmen, die historisch von Regierungen vereinnahmt wurden, stattdessen von Personen mit echtem Talent kontrolliert werden.

Zehn und schließlich Hunderte von Milliarden Dollar werden von Hunderttausenden und letztendlich Millionen von souveränen Einzelpersonen kontrolliert werden. Es ist wahrscheinlich, dass diese neuen Verwalter des Weltvermögens weitaus besser als Politiker in der Lage sein werden, Ressourcen zu nutzen und Investitionen einzusetzen. Zum ersten Mal in der Geschichte werden es aufgrund der megapolitischen Bedingungen die fähigsten Investoren und Unternehmer sein, die am Ende die Kontrolle über das Kapital haben, und nicht mehr die Spezialisten für Gewalt. Es ist nicht unplausibel zu erwarten, dass die Renditen dieser dezentralisierten, marktgesteuerten Investitionen doppelt oder sogar dreimal so hoch sein könnten wie die geringen Erträge aus den politisch gesteuerten Haushaltszuweisungen der Ära des Nationalstaates. Es war in den letzten Jahrzehnten des zwanzigsten Jahrhunderts nicht unüblich, in jedem Land Beispiele für staatliche Investitionen zu finden, die deutlich negativ waren. In der überarbeiteten Version von *The Great Reckoning* vom November 1992 zitierten wir offizielle russische Statistiken, die darauf hindeuteten, dass die gesamte russische Wirtschaft „nur 30 Milliarden Dollar wert war, weniger als ein Drittel des Wertes des Rohstoffeinsatzes. Daher würde sich der Output der russischen Wirtschaft mehr als verdreifachen, wenn die inländische Fertigungs- und Dienstleistungswirtschaft vollständig stillgelegt wäre. Statt Wert hinzuzufügen, wird er abgezogen." [^267]:

Zugegebenermaßen ist das Beispiel Russlands nach dem Zusammenbruch des Kommunismus ein extremes, aber es gibt genügend Beweise dafür, dass eine Verringerung der staatlichen Kontrolle über Ressourcen dazu neigt, die wirtschaftliche Effizienz zu verbessern. Wachstumsraten, die vom Economist zitiert werden, legen nahe, dass wirtschaftliche Freiheit stark mit wirtschaftlichem Wachstum korreliert, wobei die schnellsten Wachstumsraten in den freiesten Ländern zu verzeichnen sind. Die Cyberökonomie des Informationszeitalters wird freier sein als jeder andere kommerzielle Bereich in der Geschichte. Es ist daher vernünftig zu erwarten, dass die Cyberökonomie schnell zur wichtigsten neuen Wirtschaft des neuen Jahrtausends werden wird. Ihr Erfolg wird neue Teilnehmer aus aller Welt anziehen, so wie die breite Verwendung von Faxgeräten das Fernkopieren auch für Nichtnutzer immer attraktiver machte. Aber noch wichtiger ist, dass die Freiheit von räuberischer Gewalt es der Cyberökonomie ermöglichen wird, mit weit höheren zusammengesetzten Wachstumsraten zu wachsen als herkömmliche Volkswirtschaften, die von Nationalstaaten dominiert werden.

Dies ist vielleicht der wichtigste Punkt bei der Vorwegnahme der wirtschaftlichen Auswirkungen des wahrscheinlichen Zusammenbruchs der monopolistischen Steuer- und Inflationsfähigkeit des Staates. Von Übergangsschwierigkeiten, die Jahrzehnte dauern könnten, mal abgesehen, dürften die langfristigen Perspektiven für die Weltwirtschaft sehr positiv sein. Wenn die Umstände es den Menschen erlauben, die Schutzkosten zu senken und die Tributzahlungen an diejenigen, die die organisierte Gewalt kontrollieren, zu minimieren, wächst die Wirtschaft in der Regel dramatisch. Wie Lane sagte: „Ich möchte behaupten, dass der wichtigste Einzelfaktor in den meisten Wachstumsperioden, wenn überhaupt ein Faktor am wichtigsten war, die Verringerung des Anteils der für Krieg und Polizei aufgewendeten Mittel war." [^268]:

Es könnten erhebliche Effizienzsteigerungen erzielt werden, wenn weniger Ressourcen für Raub und das Leben von der Beute des Raubes aufgewendet würden. Würde der Preis der Sicherheit auf eine Wettbewerbsbasis gestellt, bei der lokale Monopole auf der Grundlage von Preis und Qualität um Kunden konkurrieren, könnten potenziell riesige Effizienzgewinne möglich sein. Das zu erwartende Ergebnis wären weit geringere Steuersätze und weniger Verlust von Ressourcen und Aufwand in der politischen Aktivität, die nicht mehr die gewaltigen zuvor erzielten Gewinne einbringen würde.

Würden Wähler bereitwillig auf politische Vorteile verzichten, an die sie sich gewöhnt haben? Das ist eine Frage, die wir an anderer Stelle ausführlich diskutieren. Aber eine einfache Antwort wäre, dass sie vielleicht keine Wahl haben. Niemand demonstriert jetzt gegen Regenwetter oder Dürre, egal wie wirtschaftlich schädlich oder unangenehm es sein mag. Niemand, egal wieviel kriminelle Energie er besitzt, hält einen Bettler als Geisel und fordert unter Todesdrohung ein hohes Lösegeld. Wenn es für Politiker unmöglich wird, Ressourcen zur Umverteilung zu erlangen, könnte die Öffentlichkeit rational reagieren und die Politik vergessen, genauso wie gut meinende Menschen aufgehört haben, Bußprozessionen zu organisieren, als das Mittelalter zu Ende ging.

[^245]: Perry Barlow, „Thinking Locally, Acting Globally," Time, 15. Januar 1996, S. 57.

[^246]: Ebenda.

[^247]: M. C. Seymour, ed., Mandeville: Travels (Oxford: Oxford University Press, 1968), S. 122.

[^248]: R. C. Johnson, „The Transportation of Vagrant Children from London to Virginia, 1618-1622", in H. S. Reinmuth, ed., Early Stuart Studies (Minneapolis: University of Minnesota Press, 1970), S. \~43-44, zitiert aus Jutte, ebenda, S. 168.

[^249]: John Dos Passos, The Big Money (New York: Harcourt, Brace & Co., 1936).

[^250]: Clarke, ebenda, S. 29.

[^251]: Zitiert aus Kline und Burstein, ebenda, S. \~05.

[^252]: Clarke, ebenda, S. 20.

[^253]: Ebenda.

[^254]: Ebenda, S.21.

[^255]: Lane, „Economic Consequences of Organized Violence", ebenda, S. 404.

[^256]: James Bennet, „The Information Revolution and the Demise of the Income Tax," Strategic Investment, November 1994, S. 11-12.

[^257]: Lane, „Economic Consequences of Organized Violence," ebenda, S. 404.

[^258]: Abu-Lughod, ebenda, S. 177.

[^259]: Zitiert aus Henry Mark Holzer, Governments\' Money Monopoly (New York: Books in Focus, 1981), S. 4.

[^260]: Abu-Lughod, ebenda., S. 332.

[^261]: Friedrich A. von Hayek, The Denationalization of Money (London: Institute of Economic Affairs, 1976), S. 47.

[^262]: Siehe Kapitel 1, Anmerkung 6.

[^263]: Hayek, ebenda, S. 40.

[^264]: Ebenda.

[^265]: Siehe Lawrence White, Free Banking in Britain (London: Institute of Economic Affairs, 1995).

[^266]: Michael Prowse, „Bring Back Gold", Financial Times, 5. Februar 1996, S. 12.

[^267]: Davidson und Rees-Mogg, ebenda, S. 203.

[^268]: Lane, „Economic Consequences of Organized Violence," ebenda, S. 413.

[^269]: Die Inflation hatte in der Industriezeit, als die Preise und Löhne nach unten hin unflexibel waren, eine weitere Verlockung. Eine mäßige Inflation erhöhte die Produktion, indem sie die Reallöhne und Preise senkte.
