# MEGAPOLITISCHE VERÄNDERUNGEN IM HISTORISCHEN KONTEXT

> „In der Geschichte wie in der Natur sind Geburt und Tod gleichermaßen ausgeglichen.“ - Johan Huizinga[^29]

## DER VERFALL DER MODERNEN WELT

Aus unserer Sicht erleben Sie nichts Geringeres als den Verfall des modernen Zeitalters. Es ist eine Entwicklung, die von einer gnadenlosen, aber verborgenen Logik angetrieben wird. Es ist mehr als wir im Allgemeinen verstehen und mehr als CNN und die Zeitungen uns erzählen. Das nächste Jahrtausend wird nicht mehr „modern“ sein. Wir sagen dies nicht, um anzudeuten, dass Sie einer wilden oder rückständigen Zukunft gegenüberstehen, obwohl das möglich ist, sondern um zu betonen, dass die jetzt beginnende Phase der Geschichte qualitativ anders sein wird als die, in die Sie hineingeboren wurden.

Etwas Neues kommt. So wie sich landwirtschaftliche Gesellschaften grundlegend von Jäger-und-Sammler-Gruppen unterschieden haben, wie sich industrielle Gesellschaften radikal von feudalen oder kleinbäuerlichen Agrarsystemen unterschieden haben, wird auch die zukünftige Welt, die uns erwartet, eine radikale Abkehr von allem darstellen, was wir bisher gesehen haben.

Im neuen Jahrtausend wird das wirtschaftliche und politische Leben nicht mehr in gigantischem Maßstab unter der Herrschaft des Nationalstaates organisiert sein, wie es während der modernen Jahrhunderte der Fall war. Die Zivilisation, die Ihnen den Weltkrieg, das Fließband, die soziale Sicherheit, die Einkommensteuer, das Deodorant und den Minibackofen brachte, stirbt aus. Das Deodorant und der Minibackofen könnten überleben. Die anderen nicht. Wie ein alter und einst mächtiger Mann, hat der Nationalstaat eine Zukunft, die in Jahren und Tagen, und nicht mehr in Jahrhunderten und Jahrzehnten, bemessen ist.

Regierungen haben bereits viel von ihrer Macht, zu regulieren und zu erzwingen, verloren. Der Zusammenbruch des Kommunismus markierte das Ende eines langen Zyklus von fünf Jahrhunderten, währenddessen die Größenordnung der Macht die Effizienz in der Organisation der Regierung überwältigte. Es war eine Zeit, in der die Renditen für Gewalt hoch waren und weiter stiegen. Sie sind es nicht mehr. Ein Phasenübergang von weltgeschichtlichen Ausmaßen hat bereits begonnen. Tatsächlich könnte der zukünftige Geschichtsschreiber, der den Niedergang und den Fall des einstigen modernen Zeitalters im nächsten Jahrtausend niederschreibt, erklären, dass es bereits zu Ende gegangen ist, während Sie gerade dieses Buch lesen. Rückblickend könnte er, so wie wir, auch sagen, dass es mit dem Fall der Berliner Mauer im Jahr 1989 endete. Oder mit dem Zusammenbruch der Sowjetunion im Jahr 1991. Beide Daten könnten als maßgebliches Ereignis in der Entwicklung der Zivilisation stehen, das Ende dessen, was wir heute als modernes Zeitalter kennen.

Die vierte Stufe der menschlichen Entwicklung kommt, und vielleicht ist das am wenigsten voraussagbare Merkmal der neue Name, unter dem sie bekannt sein wird. Nennen Sie es „Post-Modern.“ Nennen Sie es die „Cyber-Gesellschaft“ oder das „Informationszeitalter“. Oder erfinden Sie Ihren eigenen Namen. Niemand weiß, welches Etikett auf die nächste Phase der Geschichte geklebt werden wird.

Wir wissen nicht einmal, ob der gerade endende fünfhundertjährige Abschnitt der Geschichte weiterhin als „modern“ betrachtet werden wird. Wenn zukünftige Historiker irgendetwas über Wortableitungen wissen, wird dem wahrscheinlich nicht so sein. Ein passenderer Titel könnte „Staatszeitalter“ oder „Das Zeitalter der Gewalt“ sein. Aber ein solcher Name würde außerhalb des zeitlichen Spektrums fallen, das derzeit die Epochen der Geschichte definiert. „Modern“ bezieht sich laut Wörterbuch auf die Gegenwart und die jüngste Vergangenheit, im Gegensatz zur fernen Vergangenheit\... Im historischen Gebrauch wird es üblicherweise (im Gegensatz zu antik und mittelalterlich) auf die Zeit im Anschluss an das Mittelalter angewendet.“ [^30]

Menschen im Westen begannen sich erst bewusst als „modern“ zu bezeichnen, als sie begriffen, dass das mittelalterliche Zeitalter vorbei war. Vor 1500 hatte niemand die feudalen Jahrhunderte als eine „mittlere“ Periode in der westlichen Zivilisation angesehen. Der Grund dafür liegt auf der Hand: bevor ein Zeitalter vernünftigerweise als in der „Mitte“ zwischen zwei anderen historischen Epochen gesehen werden kann, muss es bereits zu Ende gegangen sein. Diejenigen, die während der feudalen Jahrhunderte lebten, hätten sich nicht vorstellen können Bewohner eines Durchgangshauses zwischen Antike und moderner Zivilisation zu sein, bis ihnen bewusst wurde, dass nicht nur das Mittelalter vorbei war, sondern dass sich die mittelalterliche Zivilisation stark von der Zivilisation des dunklen Zeitalters oder der Antike unterschied.[^31]

Menschliche Kulturen haben blinde Flecken. Uns fehlt der Wortschatz, um Paradigmenwechsel, speziell diejenigen, die gerade um uns herum stattfinden, zu beschreiben. Ungeachtet der vielen dramatischen Veränderungen, die sich seit der Zeit von Moses ereignet haben, haben sich nur ein paar Ketzer die Mühe gemacht, darüber nachzudenken, wie die Übergänge von einer Phase der Zivilisation zur anderen tatsächlich ablaufen.

Wie werden sie ausgelöst? Was haben sie gemeinsam? Welche Muster können Ihnen helfen zu erkennen, wann sie beginnen und wann sie enden? Wann werden Großbritannien oder die Vereinigten Staaten untergehen? Das sind Fragen, für die man nur schwer konventionelle Antworten finden würde.

### Das Tabu der Zukunftsprognosen

„Von außen“ auf ein bestehendes System zu schauen, gleicht einem Bühnenarbeiter, der versucht, einen Dialog mit einer Figur in einem Theaterstück zu führen. Es bricht eine Konvention, die dem System hilft, zu funktionieren. Jede gesellschaftliche Ordnung enthält unter ihren großen Tabus die Vorstellung, dass Menschen, die darin leben, nicht darüber nachdenken sollten, wie sie enden wird und welche neuen Regeln das neue System, das ihren Platz einnimmt, beherrschen könnten. Implizit ist jedes bestehende System das letzte oder das einzige System, das jemals existieren wird. Nicht dass dies so offen ausgesprochen würde. Nur wenige, die jemals ein Geschichtsbuch gelesen haben, würden eine solche Annahme für realistisch halten, wenn sie ausformuliert wäre. Dennoch, genau das ist die Konvention, die die Welt beherrscht. Jedes soziale System, egal wie fest es sich an die Macht klammert, tut so, als ob seine Regeln niemals überholt werden könnten. Sie haben das letzte Wort. Oder vielleicht das einzige Wort. Primitive Geister gehen stets davon aus, dass ihre Art, das Leben zu organisieren, die einzige Möglichkeit ist. Wirtschaftlich komplexere Systeme, die ein Verständnis für Geschichte miteinbeziehen, stellen sich in der Regel an deren Spitze. Ob sie chinesische Beamte am Hof des Kaisers, die marxistische Nomenklatura in Stalins Kreml oder Mitglieder des Repräsentantenhauses in Washington sind, die Machthaber stellen sich entweder gar keine Geschichte vor oder setzen sich an die Spitze der Geschichte, in einer überlegenen Position verglichen mit allen, die vor ihnen kamen, und an vorderster Front für alles, was noch kommen mag.

Das gilt aus nahezu unvermeidlichen Gründen. Je offensichtlicher es ist, dass ein System seinem Ende nahe ist, desto mehr zögern die Menschen, sich an seine Gesetze zu halten. Jede soziale Organisation wird daher dazu neigen, Analysen, die ihr Ende vorhersehen, zu entmutigen oder herunterzuspielen. Dies allein hilft sicherzustellen, dass die großen Übergänge in der Geschichte selten erkannt werden, während sie stattfinden. Wenn Sie nichts über die Zukunft wissen, können Sie sicher sein, dass dramatische Veränderungen weder von konventionellen Denkern begrüßt noch beworben werden.

Sie können sich nicht auf herkömmliche Informationsquellen verlassen, um Ihnen eine objektive und zeitnahe Warnung darüber zu geben, wie sich die Welt verändert und warum. Wenn Sie den großen Übergang, der gerade im Gange ist, verstehen wollen, haben Sie kaum eine andere Wahl, als sich selbst ein Bild davon zu machen.

### Jenseits des Offensichtlichen

Das bedeutet, über das Offensichtliche hinauszuschauen. Die Aufzeichnungen zeigen, dass selbst Übergänge, die im Nachhinein unbestreitbar real sind, möglicherweise erst Jahrzehnte oder sogar Jahrhunderte nach ihrem Auftreten anerkannt werden. Denken Sie an den Fall Roms. Es war wahrscheinlich die wichtigste historische Entwicklung im ersten Jahrtausend der christlichen Ära. Doch noch lange nach Roms Untergang wurde die Fiktion, dass es überlebt hätte, der Öffentlichkeit ebenso präsentiert, wie Lenins einbalsamierter Leichnam. Niemand, der für sein Verständnis der „Nachrichten“ auf die Behauptungen von Beamten angewiesen war, hätte je erfahren, dass Rom gefallen war, bis lange nachdem diese Information irrelevant geworden war.

Der Grund für diese Situation war nicht allein die Unzulänglichkeit der Kommunikation in der alten Welt. Das Ergebnis wäre wahrscheinlich das gleiche gewesen, hätte CNN auf wundersame Weise bereits existiert und im September 476 seine Videobänder laufen lassen. Das ist der Zeitpunkt, als der letzte römische Kaiser im Westen, Romulus Augustulus, in Ravenna gefangen genommen und zur Zwangspension in eine Villa in Kampania gebracht wurde. Selbst wenn Wolf Blitzer damals im Jahr 476 mit Minikameras die Nachrichten aufgezeichnet hätte, ist es unwahrscheinlich, dass er oder jemand anderes es gewagt hätte, diese Ereignisse als das Ende des römischen Reiches zu bezeichnen. Das ist aber natürlich genau das, was spätere Historiker gesagt haben, was passiert sei.

Vermutlich hätten die CNN-Redakteure eine Schlagzeilengeschichte mit dem Titel „Rom ist heute Abend gefallen“ nicht genehmigt. Die Machthaber leugneten, dass Rom gefallen war. Leute, die ihre „Nachrichten“ verhökern, sind selten Partisanen von Kontroversen auf eine Weise, die ihren eigenen Gewinn untergraben würde. Sie könnten es sein. Vielleicht sogar mit feurigem Eifer. Aber sie berichten selten über Schlussfolgerungen, die ihre Abonnenten dazu bringen könnten, ihre Abonnements zu kündigen und sich zurückzuziehen. Aus diesem Grund hätten wahrscheinlich nur wenige den Fall Roms gemeldet, selbst wenn es technologisch möglich gewesen wäre. Experten wären hervorgetreten und hätten gesagt, dass es lächerlich wäre, von einem Fall Roms zu sprechen. Etwas anderes zu sagen, wäre schlecht für das Geschäft gewesen und vielleicht auch schlecht für die Gesundheit derjenigen, die Bericht erstatteten. Die Machthaber im Rom des späten fünften Jahrhunderts waren Barbaren, und sie leugneten, dass Rom gefallen war.

Aber es handelte sich nicht bloß um einen Fall, bei dem die Autoritäten sagten: „Melden Sie das nicht, sonst töten wir Sie.“ Ein Teil des Problems bestand darin, dass Rom bis in die späten Jahrzehnte des fünften Jahrhunderts so degeneriert war, dass sein „Fall“ den meisten Menschen, die es miterlebten, tatsächlich entging. In der Tat war es eine Generation später, als Graf Marcellinus erstmals andeutete, dass „das weströmische Reich mit Augustulus unterging.“ [^32] Viele weitere Jahrzehnte vergingen, vielleicht Jahrhunderte, bevor es eine allgemeine Anerkennung gab, dass das römische Reich im Westen nicht mehr existierte. Mit Sicherheit glaubte Karl der Große, dass er im Jahr 800 der rechtmäßige römische Kaiser war.

Der Punkt ist nicht, dass Karl der Große und alle, die nach 476 in konventionellen Begriffen über das Römische Reich dachten, Narren waren. Ganz im Gegenteil. Die Charakterisierung sozialer Entwicklungen ist oft mehrdeutig. Wenn die Macht dominanter Institutionen ins Spiel gebracht wird, um eine günstige Schlussfolgerung zu verstärken, selbst wenn diese hauptsächlich auf Vortäuschung basiert, würde nur jemand mit starkem Charakter und starker Meinung es wagen, ihr zu widersprechen. Wenn man versucht, sich in die Lage eines Römers des späten fünften Jahrhunderts zu versetzen, ist es leicht vorstellbar, wie verlockend es gewesen wäre, zu schlussfolgern, dass sich nichts verändert hat. Diese Gewissheit war der optimistische Schluss. Anders zu denken hätte beängstigend sein können. Und warum sollte man zu einer beängstigenden Schlussfolgerung kommen, wenn eine beruhigende zur Verfügung steht?

Immerhin könnte behauptet werden, dass die Geschäfte wie gewohnt weitergeführt würden. In der Vergangenheit war das der Fall. Die römische Armee, insbesondere die Grenzgarnisonen, waren seit Jahrhunderten barbarisiert.[^33] Im dritten Jahrhundert wurde es zur regulären Praxis, dass die Armee einen neuen Kaiser ausrief. Im vierten Jahrhundert waren sogar die Offiziere Germanen und oft Analphabeten.[^34] Es hatte viele gewaltsame Umstürze von Kaisern gegeben, bevor Romulus Augustulus vom Thron entfernt wurde. Sein Abgang könnte seinen Zeitgenossen nicht anders erschienen sein als viele andere Umwälzungen in einer chaotischen Zeit. Und er wurde mit einer Pension abgefertigt. Die Tatsache, dass er eine Pension erhielt, wenn auch nur für eine kurze Zeit, bevor er ermordet wurde, war die Beruhigung, dass das System überlebt hatte. Optimistisch betrachtet hat Odoaker, der Romulus Augustulus absetzte, das Reich eher vereint als zerstört. Odoaker, der Sohn von Attilas Gehilfen Edekon, war ein kluger Mann. Er rief sich nicht selbst zum Kaiser aus. Stattdessen versammelte er den Senat und überredete seine allzu beeinflussbaren Mitglieder dazu, die Kaiserwürde und somit die Souveränität über das gesamte Reich Zeno, dem oströmischen Kaiser im weit entfernten Byzanz anzubieten. Odoaker sollte lediglich Zenos Patricius sein, um Italien zu regieren.

Wie Will Durant in *The Story of Civilization* schrieb, erschienen diese Veränderungen nicht als der „Fall Roms“, sondern lediglich als „vernachlässigbare Verschiebungen an der Oberfläche des nationalen Panoramas.“ [^35] Als Rom fiel, behauptete Odoaker, dass Rom weiter bestand. Er, wie fast jeder andere auch, war begierig darauf so zu tun, als ob sich nichts verändert hätte. Sie wussten, dass „die Herrlichkeit Roms“, weitaus besser war als die Barbarei, die ihren Platz einnahm. Selbst die Barbaren dachten so. Wie C. W. Previte-Orton in *The Shorter Cambridge Medieval History* schrieb, war das Ende des fünften Jahrhunderts, als „die Kaiser durch barbarische deutsche Könige ersetzt worden waren“, eine Zeit der „hartnäckigen Fantasterei.“ [^36]

### „Hartnäckige Fantasterei“

Diese „Fantasterei“ beinhaltete die Bewahrung der Fassade des alten Systems, selbst als seine Essenz „durch Barbarei verunstaltet“ worden war.[^37] Die alten Regierungsformen blieben die gleichen, als der letzte Kaiser durch einen barbarischen „Stellvertreter“ ersetzt wurde. Der Senat tagte immer noch. „Die prätorianische Präfektur und andere hohe Ämter blieben bestehen und wurden von prominenten Römern besetzt.“ [^38] Konsuln wurden wie üblich für ein Jahr nominiert. „Die römische Zivilverwaltung überlebte unversehrt.“ [^39] Tatsächlich blieb sie in einigen Aspekten bis zur Geburt des Feudalismus am Ende des zehnten Jahrhunderts intakt. Bei öffentlichen Anlässen wurden weiterhin alte kaiserliche Insignien verwendet. Das Christentum war nach wie vor die Staatsreligion. Die Barbaren gaben vor, immer noch dem östlichen Kaiser in Konstantinopel und den Traditionen des römischen Rechts die Treue zu schulden. Wie Durant es ausdrückte „war das große Imperium im Westen nicht mehr existent“.[^40]

### Was nun?

Das weit entfernte Beispiel des Falls von Rom ist aus verschiedenen Gründen relevant, wenn man die Bedingungen der heutigen Welt betrachtet. Die meisten Bücher über die Zukunft sind eigentlich Bücher über die Gegenwart. Wir haben versucht, diesen Mangel zu beheben, indem wir dieses Buch in erster Linie als ein Buch über die Vergangenheit gestalten. Wir glauben, dass Sie wahrscheinlich eine bessere Perspektive darauf erhalten, was die Zukunft bereithält, wenn wir wichtige megapolitische Argumente zur Logik der Gewalt mit realen Beispielen aus der Vergangenheit illustrieren. Geschichte ist eine erstaunliche Lehrerin. Die Erzählungen sind interessanter als wir sie erfinden könnten. Und viele der interessantesten beziehen sich auf den Fall von Rom. Sie dokumentieren wichtige Lektionen, die für Ihre Zukunft im Informationszeitalter relevant sein könnten.

Zunächst einmal ist der Fall Roms eines der lebendigsten Beispiele in der Geschichte dafür, was in einem größeren Übergang passierte, als der Umfang der Regierung zusammenbrach. Die Übergänge des Jahres 1000 beinhalteten ebenfalls den Zusammenbruch der zentralen Autorität und taten dies in einer Weise, die die Komplexität und den Umfang der wirtschaftlichen Aktivität erhöhte. Die Schießpulverrevolution am Ende des fünfzehnten Jahrhunderts führte zu großen Veränderungen in den Institutionen, die dazu neigten, den Umfang der Regierung eher zu erhöhen als zu verringern. Heute, zum ersten Mal seit tausend Jahren, untergraben und zerstören megapolitische Bedingungen im Westen Regierungen und viele andere Institutionen, die in großem Umfang agieren.

Natürlich hatte der Zusammenbruch der Regierungsgröße am Ende des römischen Reiches ganz andere Ursachen als jene, die zum Beginn des Informationszeitalters existierten. Ein Teil der Ursache, warum Rom fiel, liegt einfach darin, dass es über das Maß hinausgewachsen war, in dem die Ökonomien der Gewalt aufrechterhalten werden konnten. Die Kosten für die Besatzung der weit entfernten Grenzen des Reiches überstiegen die wirtschaftlichen Vorteile, die eine antike Agrarwirtschaft unterstützen konnte. Die Last von Steuern und Regulierung, die zur Finanzierung des militärischen Aufwands benötigt wurde, stieg über die Tragfähigkeit der Wirtschaft hinaus. Korruption wurde zur Normalität. Wie der Historiker Ramsay MacMullen dokumentiert hat, widmeten sich die Militärkommandanten stark der Verfolgung „illegaler Gewinne aus ihrem Kommando“.[^41] Dies erreichten sie, indem sie die Bevölkerung ausbeuteten, was der Beobachter des vierten Jahrhunderts, Synesius, als „den Krieg in Friedenszeiten, einen fast schlimmeren als den Barbarenkrieg und resultierend aus der Disziplinlosigkeit des Militärs und der Gier der Offiziere“ beschrieb.[^42]

Ein weiterer wichtiger Faktor, der zum Zusammenbruch Roms beitrug, war das demographische Defizit, das durch die Antoninische Pest verursacht wurde. Der Rückgang der römischen Bevölkerung in vielen Gebieten trug offensichtlich zur wirtschaftlichen und militärischen Schwäche bei. Nichts dergleichen ist heute passiert, zumindest noch nicht. Aus einer längerfristigen Perspektive heraus betrachtet, könnte die Geißel neuer „Pandemien“ die Herausforderungen der technologischen Entwicklung im neuen Jahrtausend verschärfen. Die beispiellose Zunahme der menschlichen Bevölkerung im zwanzigsten Jahrhundert schafft ein verlockendes Ziel für schnell mutierende Mikroparasiten. Ängste vor dem Ebola-Virus oder ähnlichen Krankheiten, die städtische Bevölkerungsgruppen befallen könnten, sind möglicherweise begründet. Doch dies ist nicht der Ort, um die Koevolution von Menschen und Krankheiten zu diskutieren. So interessant dieses Thema auch ist, geht es uns an dieser Stelle nicht darum, warum Rom fiel, oder ob die Welt heute einigen der gleichen Einflüsse ausgesetzt ist, die zum Niedergang Roms beigetragen haben. Es geht um etwas anderes -- nämlich die Art und Weise, wie die großen Veränderungen in der Geschichte wahrgenommen, oder vielmehr, während sie geschehen, missverstanden werden.

Die Menschen sind stets und überall zu einem gewissen Grad konservativ. Dies impliziert eine Zurückhaltung, in Bezug auf die Auflösung von geschätzten gesellschaftlichen Konventionen, den Umsturz der anerkannten Institutionen und dem Trotzen gegenüber Gesetzen und Werten, die ihnen als Orientierung dienen. Nur wenige sind bereit zu erwägen, dass scheinbar geringfügige Veränderungen im Klima oder der Technologie oder in einer anderen Variablen irgendwie verantwortlich sein könnten, die Verbindungen zur Welt ihrer Väter zu kappen. Die Römer zögerten, die sich um sie herum entfaltenden Veränderungen anzuerkennen. Und so geht es uns auch.

Ob wir es anerkennen oder nicht, wir durchleben einen Wechsel der historischen Jahreszeit, eine Transformation in der Art und Weise, wie die Menschen ihren Lebensunterhalt organisieren und sich verteidigen, die so tiefgreifend ist, dass sie unweigerlich die gesamte Gesellschaft verändern wird. Der Wandel wird so tiefgreifend sein, dass man, um ihn zu verstehen, fast nichts als selbstverständlich ansehen muss. Ihnen wird nahezu bei jeder Gelegenheit suggeriert, dass die kommenden Informationsgesellschaften der Industriegesellschaft, in der Sie aufgewachsen sind, sehr ähnlich sein werden. Wir bezweifeln das. Die Mikroverarbeitung wird den Mörtel in den Steinen auflösen. Sie wird die Logik der Gewalt so tiefgreifend verändern, dass sie dramatisch die Art und Weise verändert, wie Menschen ihren Lebensunterhalt organisieren und sich verteidigen. Dennoch wird die Tendenz bestehen, die Unvermeidlichkeit dieser Veränderungen herunterzuspielen, oder ihre Erwünschtheit zu diskutieren, als ob es in der Hand der industriellen Institutionen läge, die Entwicklung der Geschichte zu bestimmen.

### Die große Illusion

Autoren, die in vielerlei Hinsicht besser informiert sind als wir, können uns dennoch in Bezug auf die Zukunft in die Irre führen, weil sie die Funktionsweise von Gesellschaften viel zu oberflächlich untersuchen. Zum Beispiel haben David Kline und Daniel Burstein ein gut recherchiertes Werk mit dem Titel „Road Warriors: Dreams and Nightmares Along the Information Highway“ verfasst. Es steckt voller bewundernswerter Details, doch viele dieser Details werden dazu verwendet, eine Illusion zu unterstützen, nämlich die Idee, „dass Bürger gemeinsam und bewusst die spontanen wirtschaftlichen und natürlichen Prozesse, die um sie herum stattfinden, gestalten können.“ [^43] Obwohl es möglicherweise nicht offensichtlich ist, entspricht dies der Aussage, dass der Feudalismus hätte überleben können, wenn sich jeder erneut der Ritterlichkeit verschrieben hätte. Niemand in einem Gericht des späten fünfzehnten Jahrhunderts hätte eine solche Ansicht abgelehnt. Tatsächlich wäre es Ketzerei gewesen, dies zu tun. Aber es wäre auch völlig irreführend gewesen. Wie eine Schlange, die versucht, ihre Zukunft in ihrer alten Haut zu finden.

Die grundlegenden Ursachen für Veränderungen sind genau diejenigen, die nicht bewusst kontrolliert werden können. Sie sind die Faktoren, die die Bedingungen verändern, unter denen Gewalt Vorteile bringt. Tatsächlich sind sie so fern von jeglichen offensichtlichen Mitteln zur Manipulation, dass sie nicht einmal Gegenstand politischer Manöver sind, in einer Welt, die von Politik durchdrungen ist. Niemand hat jemals auf einer Demonstration gerufen: „Erhöhen Sie die Skaleneffekte im Produktionsprozess“. Kein Banner hat jemals die Forderung erhoben: „Erfinden Sie ein Waffensystem, das die Bedeutung der Infanterie erhöht“. Kein politischer Kandidat hat je versprochen „das Gleichgewicht zwischen der Effizienz und dem Ausmaß von Schutz der Gewalt zu verändern“. Solche Parolen wären lächerlich, gerade weil diese Ziele jenseits der Fähigkeit des Einzelnen liegen, sie bewusst zu beeinflussen. Dennoch bestimmen diese Variablen, wie wir erkennen werden, in weit größerem Maße wie die Welt funktioniert, als jede politische Plattform.

Wenn man ernsthaft darüber nachdenkt, sollte es offensichtlich sein, dass wichtige Übergänge in der Geschichte selten hauptsächlich von menschlichen Wünschen angetrieben werden. Sie geschehen nicht, weil die Menschen von einer Lebensweise genug haben und plötzlich eine andere bevorzugen. Eine kurze Überlegung zeigt warum. Wenn das, was Menschen denken und wünschen, die einzigen Determinanten dessen wären, was passiert, dann müssten alle abrupten Veränderungen in der Geschichte durch wilde Stimmungsschwankungen erklärt werden, die in keiner Verbindung zu irgendwelchen Veränderungen in den tatsächlichen Lebensbedingungen stehen. Tatsächlich geschieht dies jedoch nie. Nur in Fällen von medizinischen Problemen, die nur wenige Menschen betreffen, sehen wir willkürliche Stimmungsschwankungen, die scheinbar vollständig von jeder objektiven Ursache getrennt sind.

Normalerweise entscheiden große Menschengruppen sich nicht plötzlich dafür, ihren Lebensstil aufzugeben, nur weil sie es amüsant finden. Kein Jäger und Sammler hat jemals gesagt: „Ich bin es leid, in prähistorischen Zeiten zu leben, ich würde das Leben eines Bauern in einem Bauerndorf vorziehen.“ Jeder entscheidende Umschwung in Verhaltensmustern und Werten ist unweigerlich eine Reaktion auf eine tatsächliche Veränderung der Lebensbedingungen. In diesem Sinne sind die Menschen zumindest immer realistisch. Wenn sich ihre Ansichten plötzlich ändern, deutet das wahrscheinlich darauf hin, dass sie mit einer Abweichung von den bekannten Bedingungen konfrontiert wurden: Einer Invasion, einer Pandemie, einer plötzlichen klimatischen Veränderung oder einer technologischen Revolution, die ihre Lebensgrundlage oder ihre Fähigkeit zur Selbstverteidigung verändert hat.

Entgegen menschlicher Wunschvorstellungen widersprechen entscheidende historische Veränderungen häufig der Sehnsucht der meisten Menschen nach Stabilität. Wenn Veränderungen eintreten, verursachen sie typischerweise eine weit verbreitete Desorientierung, insbesondere bei denjenigen, die Einkommen oder sozialen Status verlieren. Sie werden vergeblich in Meinungsumfragen oder anderen Stimmungsmessungen nach einem Verständnis dafür suchen, wie der bevorstehende megapolitische Übergang sich wahrscheinlich entwickeln wird.

## LEBEN OHNE WEITSICHT

Wenn wir die große Übergangsphase, die um uns herum stattfindet, nicht wahrnehmen, liegt das teilweise daran, dass wir sie nicht sehen wollen. Unsere nomadischen Vorfahren hätten vielleicht genauso starrsinnig sein können, aber sie hatten eine bessere Ausrede. Vor zehntausend Jahren hätte niemand die Folgen der Agrarrevolution voraussehen können. Tatsächlich hätte niemand etwas über das Finden der nächsten Mahlzeit hinaus erahnen können. Als die Landwirtschaft begann, gab es keine Aufzeichnungen vergangener Ereignisse, aus denen man Perspektiven für die Zukunft hätte gewinnen können. Es gab nicht einmal ein westliches Verständnis von Zeit, das in geordnete Einheiten wie Sekunden, Minuten, Stunden, Tage usw. unterteilt gewesen wäre, um die Jahre zu messen. Die Nomaden lebten in der „ewigen Gegenwart“, ohne Kalender und ohne jegliche schriftliche Aufzeichnungen. Sie hatten keine Wissenschaft und kein anderes intellektuelles Werkzeug, um Ursache und Wirkung über ihre eigenen Intuitionen hinaus zu verstehen. Was die Zukunftsplanung betrifft, waren unsere urzeitlichen Vorfahren blind. Um es mit einer biblischen Metapher auszudrücken: Sie hatten noch nicht von der Frucht der Erkenntnis gegessen.

### Aus der Vergangenheit lernen

Glücklicherweise haben wir einen besseren Aussichtspunkt. Die vergangenen fünfhundert Generationen haben uns analytische Fähigkeiten verliehen, die unseren Vorfahren fehlten. Wissenschaft und Mathematik haben uns dabei geholfen, viele Geheimnisse der Natur zu entschlüsseln und uns ein Verständnis von Ursache und Wirkung gegeben, das im Vergleich zu dem der frühen Sammler und Jäger geradezu magisch anmutet. Berechnungsalgorithmen, die durch Hochgeschwindigkeitscomputer entwickelt wurden, haben neue Einblicke in die Funktionsweise komplexer, dynamischer Systeme wie der menschlichen Wirtschaft ermöglicht. Die mühsame Entwicklung der politischen Ökonomie selbst -- obwohl sie weit davon entfernt ist, perfekt zu sein -- hat das Verständnis der Faktoren, die menschliches Handeln beeinflussen, geschärft. Insbesondere ist die Erkenntnis wichtig, dass Menschen zu allen Zeiten und an allen Orten dazu neigen, auf Anreize zu reagieren. Nicht immer so mechanisch, wie Ökonomen es sich vorstellen, aber sie reagieren. Kosten und Belohnungen sind relevant. Veränderungen der äußeren Bedingungen, die die Belohnungen erhöhen oder die Kosten für bestimmtes Verhalten senken, führen vermehrt zu diesem Verhalten, sofern alle anderen Bedingungen gleichbleiben.

### Anreize sind wichtig

Die Tatsache, dass Menschen dazu neigen, auf Kosten und Belohnungen zu reagieren, ist ein wesentliches Element der Vorhersage. Man kann mit hoher Sicherheit sagen, dass wenn man einen Hundert-Dollar-Schein auf der Straße fallen lässt, ihn jemand bald aufheben wird, egal ob man in New York, Mexico City, oder Moskau ist. Das ist nicht so trivial, wie es scheint. Es zeigt, warum die klugen Leute, die sagen, dass Vorhersagen unmöglich sind, unrecht haben. Jede Prognose, die die Auswirkungen von Anreizen auf das Verhalten genau antizipiert, wird wahrscheinlich generell korrekt sein. Und je größer die erwartete Veränderung in Bezug auf Kosten und Belohnungen ist, desto weniger trivial ist wahrscheinlich die implizierte Prognose.

Die weitreichendsten Prognosen aller Zeiten werden wahrscheinlich aus der Erkenntnis der Implikationen sich verändernder megapolitischer Variablen hervorgehen. Gewalt ist die ultimative Grenze für das Verhalten; wenn Sie also verstehen können, wie sich die Logik der Gewalt verändern wird, können Sie auf nützliche Weise vorhersagen, wo Menschen in der Zukunft das Äquivalent von Hundert-Dollar-Scheinen fallen lassen oder aufheben werden.

Wir meinen damit nicht, dass Sie sich über die Unsicherheit sicher sein können. Wir können Ihnen nicht sagen, wie Sie die Gewinnzahlen der Lotterie oder irgendein wirklich zufälliges Ereignis vorhersagen können. Wir haben keine Möglichkeit zu wissen, wann oder ob ein Terrorist eine Atombombe in Manhattan zünden wird. Oder ob ein Asteroid Saudi-Arabien treffen wird. Wir können das Kommen einer neuen Eiszeit, einen plötzlichen Vulkanausbruch oder das Auftreten einer neuen Krankheit nicht vorhersagen. Die Anzahl unbekannter Ereignisse, die den Lauf der Geschichte verändern könnten, ist groß. Aber Sicherheit über die Unsicherheit ist etwas ganz anderes als die Auswirkungen dessen herauszuarbeiten, was bereits bekannt ist. Wenn Sie in weiter Entfernung einen Blitz sehen, können Sie mit hoher Gewissheit vorhersagen, dass der Donner kommen wird. Die Vorhersage der Folgen von megapolitischen Übergängen beinhaltet viel längere Zeitrahmen und weniger sichere Zusammenhänge, aber es handelt sich um eine ähnliche Art der Übung.

Megapolitische Katalysatoren für Veränderungen erscheinen in der Regel lange bevor sich ihre Konsequenzen manifestieren. Es dauerte fünftausend Jahre, bis die vollen Auswirkungen der Agrarrevolution zum Vorschein kamen. Der Übergang von einer Agrargesellschaft zu einer Industriegesellschaft basierend auf Produktion und chemischer Energie entfaltete sich schneller. Es dauerte Jahrhunderte. Der Übergang zur Informationsgesellschaft wird noch schneller stattfinden, wahrscheinlich innerhalb einer Lebensspanne. Dennoch, selbst wenn man die Verkürzung der Geschichte berücksichtigt, kann man erwarten, dass Jahrzehnte vergehen, bevor die volle megapolitische Auswirkung der bestehenden Informationstechnologie realisiert wird.

### Große und kleine megapolitische Übergänge

Dieses Kapitel analysiert einige der gemeinsamen Merkmale von megapolitischen Übergängen. In den folgenden Kapiteln betrachten wir die Agrarrevolution und den Übergang von der Landwirtschaft zur Fabrikarbeit, die zweite der vorherigen großen Phasenwechsel, genauer. Innerhalb der landwirtschaftlichen Phase der Zivilisation gab es viele kleinere megapolitische Übergänge, wie zum Beispiel den Fall Roms und die feudale Revolution des Jahres 1000. Diese markierten das Aufkommen und den Niedergang der Machtverhältnisse, während Regierungen aufstiegen und fielen und die Erlöse aus der Landwirtschaft von einer Gruppe zur anderen übergingen. Die Besitzer von großflächigen Anwesen im römischen Reich, Kleinbauern im europäischen Mittelalter und die Herren und Leibeigenen der Feudalzeit ernährten sich alle von den gleichen Feldern. Sie lebten unter sehr unterschiedlichen Regierungen aufgrund der kumulativen Auswirkungen verschiedener Technologien, Klimaschwankungen und der disruptiven Einflüsse von Krankheiten.

Unser Ziel ist es nicht, all diese Veränderungen gründlich zu erklären. Wir geben nicht vor, dies zu tun, obwohl wir einige Beispiele skizziert haben, wie sich verändernde megapolitische Variablen die Art und Weise verändert haben, wie Macht in der Vergangenheit ausgeübt wurde. Regierungen sind gewachsen und geschrumpft, da megapolitische Schwankungen die Kosten für die Ausübung von Macht gesenkt oder erhöht haben.

Hier sind einige zusammenfassende Punkte, die Sie im Hinterkopf behalten sollten, wenn Sie versuchen, die Informationsrevolution zu verstehen:

1.  Eine Verschiebung der megapolitischen Grundlagen der Macht vollzieht sich in der Regel weit vor den eigentlichen Revolutionen in der Anwendung der Macht.

2.  Die Einkommen sinken in der Regel, wenn ein größerer Übergang beginnt, oft weil eine Gesellschaft sich selbst krisenanfällig gemacht hat, indem sie die Ressourcen aufgrund des Bevölkerungsdrucks marginalisiert hat.

3.  Der Blick „außerhalb“ eines Systems ist in der Regel tabu. Die Menschen sind häufig blind für die Logik der Gewalt in der bestehenden Gesellschaft; daher sind sie auch fast immer blind für Veränderungen innerhalb dieser Logik, ob versteckt oder offensichtlich. Megapolitische Übergänge werden selten erkannt, bevor sie stattfinden.

4.  Große Übergänge sind immer mit einer kulturellen Revolution verbunden und führen in der Regel zu Konflikten zwischen den Anhängern der alten und der neuen Werte.

5.  Megapolitische Übergänge sind nie populär, weil sie mühsam erworbenes intellektuelles Kapital antiquieren und etablierte moralische Imperative in Frage stellen. Sie werden nicht auf allgemeine Nachfrage hin vollzogen, sondern als Reaktion auf veränderte externe Bedingungen, die die Logik der Gewalt im lokalen Umfeld verändern.

6.  Übergänge zu neuen Formen der Organisation des Lebensunterhalts oder zu neuen Regierungsformen sind zunächst auf die Gebiete beschränkt, in denen die megapolitischen Katalysatoren am Werk sind.

7.  Mit der möglichen Ausnahme der Anfangsphase der Landwirtschaft waren Übergänge in der Vergangenheit immer mit Perioden des sozialen Chaos und erhöhter Gewalt aufgrund von Desorientierung und Zusammenbruch des alten Systems verbunden.

8.  Korruption, moralischer Verfall und Ineffizienz scheinen Merkmale des Endstadiums eines Systems zu sein.

9.  Die wachsende Bedeutung der Technologie bei der Gestaltung der Logik der Gewalt hat zu einer Beschleunigung der Geschichte geführt, so dass bei jedem aufeinanderfolgenden Übergang weniger Zeit zur Anpassung bleibt als je zuvor.

### Die Geschichte beschleunigt sich

Da sich die Ereignisse heute oftmals schneller entwickeln als während früherer Transformationen, könnte ein frühzeitiges Verständnis davon, wie sich die Welt verändern wird, weitaus nützlicher für Sie sein als es für Ihre Vorfahren zu einem vergleichbaren Zeitpunkt in der Vergangenheit gewesen wäre. Selbst wenn die ersten Bauern auf wundersame Weise die vollen megapolitischen Implikationen des Ackerbaus verstanden hätten, wären diese Informationen praktisch nutzlos gewesen, da tausende von Jahren vergehen sollten, bis der Übergang in die nächste Phase der Gesellschaft komplett vollzogen war.

Das ist heutzutage nicht mehr so. Die Geschichte hat sich beschleunigt. Prognosen, die die megapolitischen Auswirkungen neuer Technologien korrekt vorhersagen, dürften heute weitaus nützlicher sein. Wenn wir die Implikationen des aktuellen Übergangs zur Informationsgesellschaft genauso detailliert erfassen können, wie jemand mit aktuellem Wissen die Implikationen vergangener Übergänge zur Landwirtschaft und zur Fabrikarbeit hätte verstehen können, sollte diese Information heute ein Vielfaches wert sein. Einfach ausgedrückt: der Handlungshorizont für megapolitische Prognosen hat sich auf seinen nützlichsten Bereich innerhalb einer einzelnen Lebensspanne reduziert.

> „Blickt man über die Jahrhunderte zurück oder betrachtet man sogar nur die Gegenwart, so lässt sich deutlich beobachten, dass viele Männer ihren Lebensunterhalt, oft einen sehr guten Lebensunterhalt, aus ihrer besonderen Fähigkeit gezogen haben, die Waffen der Gewalt anzuwenden, und dass ihre Aktivitäten einen sehr großen Teil dazu beigetragen haben, welche Verwendung knappen Ressourcen zugefügt wurde.“ - Frederic C. Lane[^44]

Unsere Studie über Megapolitik versucht genau dies zu tun -- die Konsequenzen der sich ändernden Faktoren, welche die Grenzen, innerhalb derer Gewalt ausgeübt wird, verändern, herauszuarbeiten.

Diese megapolitischen Faktoren bestimmen im Wesentlichen, wann und wo Gewalt sich auszahlt. Außerdem helfen sie bei der Informationsbeschaffung einer marktgerechten Einkommensverteilung. Wie der Wirtschaftshistoriker Frederic Lane so gekonnt formulierte, spielt die Art und Weise, wie Gewalt organisiert und kontrolliert wird, eine große Rolle bei der Bestimmung „welche Verwendungen knappen Ressourcen zugefügt wurde.“ [^45]

## EIN CRASHKURS IN MEGAPOLITIK

Das Konzept der Megapolitik ist mächtig. Es hilft dabei, einige der größten Geheimnisse der Geschichte zu beleuchten: wie Regierungen aufsteigen und fallen und welche Art von Institutionen sie werden; das Timing und Ergebnis von Kriegen; Muster wirtschaftlichen Wohlstands und Verfalls. Durch die Erhöhung oder Senkung von Kosten und Belohnungen für die Projektion von Macht, beherrscht die Megapolitik die Fähigkeit der Menschen, ihren Willen anderen aufzuzwingen. Dies war seit den frühesten menschlichen Gesellschaften der Fall. Und das ist auch immer noch so. Wir haben viele der wichtigen, versteckten megapolitischen Faktoren erforscht, die die Entwicklung der Geschichte in *Blood in the Streets* und *The Great Reckoning* bestimmen. Der Schlüssel zur Enthüllung der Auswirkungen megapolitischer Veränderungen liegt im Verständnis der Faktoren, die Revolutionen in der Anwendung von Gewalt auslösen. Diese Variablen können in vier Kategorien eingeteilt werden: Topographie, Klima, Mikroben und Technologie.

1\. Topographie ist ein entscheidender Faktor, wie die Tatsache beweist, dass die Kontrolle von Gewalt auf offener See nie so monopolisiert war wie an Land. Die Gesetze einer Regierung haben dort nie exklusiv gegolten. Dies ist von größter Bedeutung, um zu verstehen, wie sich die Organisation von Gewalt und Schutz entwickeln wird, wenn die Wirtschaft in den Cyberspace abwandert.

Topographie spielte zusammen mit dem Klima eine bedeutende Rolle in der frühen Geschichte. Die ersten Staaten entstanden auf Überschwemmungsgebieten die von Wüste umgeben waren, wie beispielsweise in Mesopotamien und Ägypten, wo Wasser zur Bewässerung reichlich vorhanden war, während die umliegenden Regionen zu trocken waren, um kleinbäuerliche Landwirtschaft zu unterstützen. Unter solchen Bedingungen standen einzelne Landwirte vor extrem hohen Kosten, wenn sie nicht an der Erhaltung der politischen Struktur mitwirkten. Ohne Bewässerung, die nur im großen Maßstab gewährleistet werden konnte, würden die Pflanzen nicht wachsen. Keine Ernte bedeutete Hunger. Die Bedingungen, die diejenigen, die das Wasser in einer Wüste kontrollierten, in eine Position der Stärke brachten, führten zu einer despotischen und reichen Regierung.

Wie wir in *The Great Reckoning* analysiert haben, spielten auch topographische Bedingungen eine entscheidende Rolle für den Wohlstand der Landwirte im alten Griechenland und ermöglichten dieser Region, die Wiege der westlichen Demokratie zu werden. Angesichts der primitiven Transportbedingungen, die vor dreitausend Jahren im Mittelmeerraum herrschten, war es nahezu unmöglich, für Personen, die mehr als ein paar Kilometer vom Meer entfernten lebten, mit der Produktion der reichhaltigen Ernte von Oliven und Trauben in der antiken Welt zu konkurrieren. Wenn Öl und Wein über gewisse Entfernung an Land transportiert werden mussten, waren die Transportkosten so hoch, dass sie nicht mit Gewinn verkauft werden konnten. Die ausgedehnten Linien der griechischen Küste bedeuteten, dass die meisten Gebiete Griechenlands nicht mehr als dreißig Kilometer vom Meer entfernt waren. Dies verschaffte den griechischen Bauern einen entscheidenden Vorteil gegenüber ihren potenziellen Wettbewerbern in Binnenländern.

Aufgrund dieses Handelsvorteils mit hochwertigen Produkten erzielten die griechischen Bauern hohe Einkommen, obwohl sie nur kleine Landparzellen besaßen. Diese hohen Einkommen ermöglichten es ihnen, kostspielige Rüstungen zu erwerben. Die berühmten Hopliten des antiken Griechenlands waren Bauern oder Landbesitzer, die sich auf eigene Kosten bewaffneten. Die gut bewaffneten und hochmotivierten griechischen Hopliten stellten eine ernstzunehmende militärische Macht dar und konnten nicht ignoriert werden. Die topografischen Bedingungen bildeten das Fundament der griechischen Demokratie, genauso wie andere Gegebenheiten zur Entstehung der orientalischen Despotien in Ägypten und anderen Orten führten.

2\. Klima trägt ebenfalls dazu bei, die Grenzen zu setzen, innerhalb derer rohe Gewalt ausgeübt werden kann. Ein Klimawandel war der Auslöser für den ersten großen Übergang von der Nahrungssuche zum Ackerbau.

Das Ende der letzten Eiszeit, vor ungefähr dreizehntausend Jahren, führte zu einer radikalen Veränderung der Vegetation. Beginnend im nahen Osten, wo die Eiszeit zuerst zurückging, führte ein allmählicher Anstieg von Temperatur und Niederschlägen zur Ausbreitung von Wäldern in Gebieten, die zuvor Graslandschaften waren. Insbesondere die rasche Ausbreitung von Buchenwäldern begrenzte die menschliche Ernährung erheblich. Wie Susan Alling Gregg es in *Foragers and Farmers* ausdrückte:

„Die Ansammlung von Buchenwäldern muss schwerwiegende Folgen für die lokalen menschlichen, pflanzlichen und tierischen Populationen gehabt haben. Das Blätterdach eines Eichenwaldes ist relativ offen und lässt viel Sonnenlicht auf den Waldboden fallen. Ein üppiger Unterwuchs aus gemischten Sträuchern, Kräutern und Gräsern entwickelt sich und die Vielfalt der Pflanzen unterstützt eine Vielzahl von Wildtieren. Im Gegensatz dazu ist das Blätterdach eines Buchenwaldes geschlossen und der Waldboden ist stark beschattet. Abgesehen von einem Schub von Frühjahrsblühern vor dem Austreten der Blätter, findet man nur schattentolerante Seggen, Farne und einige Gräser.“ [^46]

Mit der Zeit breiteten sich dichte Wälder auf den offenen Ebenen aus und zogen sich durch ganz Europa bis in die östlichen Steppen.[^47] Die Wälder verringerten die Weidefläche, die zur Unterstützung großer Tiere zur Verfügung stand, was es für die Bevölkerung der menschlichen Sammler zunehmend schwierig machte, sich zu ernähren.

Die Population der Jäger und Sammler war während der Wohlstandszeit der Eiszeit so stark angewachsen, dass sie sich nicht mehr durch die schrumpfenden Herden großer Säugetiere, von denen viele Arten bis zur Ausrottung gejagt wurden, ernähren konnte. Der Übergang zur Landwirtschaft war kein Wunsch, sondern eine unter Notwendigkeit angenommene Improvisation, um Engpässe in der Ernährung auszugleichen. Die Nahrungssuche blieb weiterhin in den weiter nördlich gelegenen Gebieten vorherrschend, wo der Erwärmungstrend den Lebensraum großer Säugetiere nicht beeinträchtigte, sowie in tropischen Regenwäldern, in denen der globale Erwärmungstrend nicht die perverse Auswirkung hatte, dass die Nahrungsversorgung verringert wurde. Seit dem Aufkommen der Landwirtschaft ist es weit häufiger, dass Veränderungen durch die Abkühlung anstatt durch die Erwärmung des Klimas verursacht werden.

Ein bescheidenes Verständnis der Dynamik des Klimawandels in vergangenen Gesellschaften könnte sich als nützlich erweisen, falls das Klima weiterhin Schwankungen unterliegt. Wenn man weiß, dass ein Rückgang um ein Grad Celsius im Durchschnitt die Wachstumsperiode um drei bis vier Wochen verkürzt und die maximale Anbauhöhe um 150 Meter reduziert, dann hat man eine Vorstellung von den Randbedingungen, die das Handeln der Menschen in der Zukunft einschränken werden.[^48] Mit diesem Wissen können Sie Veränderungen von Getreidepreisen bis hin zum Wert von Landflächen prognostizieren. Sie könnten sogar in der Lage sein, informierte Schlussfolgerungen über den wahrscheinlichen Einfluss fallender Temperaturen auf die realen Einkommen und die politische Stabilität zu ziehen. In der Vergangenheit wurden Regierungen gestürzt, wenn mehrjährige Ernteausfälle die Lebensmittelpreise in die Höhe trieben und das verfügbare Einkommen schrumpfen ließen.

Es ist beispielsweise kein Zufall, dass das siebzehnte Jahrhundert, das kälteste in der modernen Epoche, auch eine Zeit weltweiter Revolutionen war. Eine verborgene megapolitische Ursache dieser Unzufriedenheit war das drastisch kältere Wetter. Tatsächlich war es so kalt, dass der Wein auf dem Tisch des „Sonnenkönigs“ in Versailles gefror. Verkürzte Wachstumsperioden führten zu Ernteausfällen und untergruben das reale Einkommen. Aufgrund des kühleren Wetters begann der Wohlstand in eine lange globale Depression abzurutschen, die um 1620 einsetzte. Sie erwies sich als drastisch destabilisierend. Die Wirtschaftskrise des siebzehnten Jahrhunderts führte dazu, dass die Welt von Aufständen überflutet wurde, viele davon sammelten sich im Jahr 1648, genau zweihundert Jahre vor einem anderen und berühmteren Zyklus von Rebellionen. Zwischen 1640 und 1650 gab es Aufstände in Irland, Schottland, England, Portugal, Katalonien, Frankreich, Moskau, Neapel, Sizilien, Brasilien, Böhmen, der Ukraine, Österreich, Polen, Schweden, den Niederlanden und der Türkei. Sogar China und Japan wurden von Unruhen erfasst.

Es könnte auch sein, dass es kein Zufall war, dass der Merkantilismus im siebzehnten Jahrhundert während einer Periode des schrumpfenden Handels dominierte. Die wirtschaftliche Abschottung war vielleicht am Ende des Jahrhunderts am stärksten ausgeprägt, „als eine schreckliche Hungersnot eintrat.“ [^49] Bis zum achtzehnten Jahrhundert, insbesondere nach 1750, begannen wärmere Temperaturen und höhere Ernteerträge, die realen Einkommen in Westeuropa ausreichend zu steigern, um die Nachfrage nach Industriegütern zu erweitern. Freiere Marktregelungen wurden angenommen. Dies führte zu einem selbstverstärkenden Wirtschaftswachstum, da die Industrie in größerem Maßstab ausgedehnt wurde, was allgemein als die industrielle Revolution bezeichnet wird. Die wachsende Bedeutung von Technologie und produzierten Waren verringerte den Einfluss des Wetters auf die Wirtschaftszyklen.

Auch heute sollte man jedoch nicht unterschätzen, welche Auswirkungen plötzlich kälteres Wetter auf die Senkung der realen Einkommen haben kann -- sogar in wohlhabenden Regionen wie Nordamerika. Es besteht eine starke Tendenz bei Gesellschaften, sich selbst krisenanfällig zu machen, wenn die bestehende Struktur der Institutionen ihr Potenzial erschöpft hat. In der Vergangenheit hat sich diese Neigung oft durch Bevölkerungszunahmen manifestiert, die die Tragfähigkeit des Landes an ihre Grenzen brachten. Dies geschah sowohl vor dem Übergang zum Jahr 1000 als auch erneut am Ende des fünfzehnten Jahrhunderts. Der Rückgang des realen Einkommens, verursacht durch Missernten und niedrigere Erträge, spielte in beiden Fällen eine bedeutende Rolle bei der Zerstörung der vorherrschenden Institutionen. Heute manifestiert sich die Marginalisierung in den Kreditmärkten für Verbraucher. Wenn plötzlich kälteres Wetter die Ernteerträge verringern und die verfügbaren Einkommen senken würde, könnte dies zu Schuldenausfällen sowie zu Steuerrevolten führen. Wenn die Vergangenheit uns einen Leitfaden gibt, könnten sowohl wirtschaftlicher Stillstand als auch politische Instabilität die Folge sein.

3\. Mikroben übertragen die Fähigkeit, Schaden anzurichten oder sich vor Schaden zu immunisieren, auf eine Art und Weise, die oft die Art der Machtausübung bestimmt hat. Dies war sicherlich bei der europäischen Eroberung der neuen Welt der Fall, wie wir in *The Great Reckoning* untersucht haben. Die europäischen Siedler, die aus sesshaften, von Krankheiten geplagten Agrargesellschaften kamen, brachten eine relative Immunität gegen Kinderkrankheiten wie Masern mit. Die Indianer, auf die sie trafen, lebten größtenteils in dünn besiedelten Gruppen von Sammlern. Sie besaßen diese Immunität nicht und wurden dezimiert. Die höchste Sterblichkeitsrate trat oft schon vor der vermehrten Ankunft der Weißen auf, da die Indianer, die an den Küsten auf Europäer trafen, mit Infektionen ins Landesinnere reisten.

Es gibt auch mikrobiologische Barrieren für die Ausübung von Macht. In *Blood in the Streets* haben wir die Rolle diskutiert, welche potente Malaria-Stämme dabei spielten, das tropische Afrika über viele Jahrhunderte hinweg unverletzlich gegenüber Invasionen durch weiße Männer zu machen. Vor der Entdeckung von Chinin, Mitte des neunzehnten Jahrhunderts, konnten weiße Armeen in malariagefährdeten Regionen nicht überleben, egal wie überlegen ihre Waffen gewesen sein mögen.

Die Wechselwirkung zwischen Menschen und Mikroben hat auch wichtige demographische Effekte hervorgebracht, die die Kosten und Belohnungen von Gewalt veränderten. Wenn Schwankungen in der Sterblichkeit aufgrund von Epidemien, Hungersnöten oder anderen Ursachen hoch sind, sinkt die relative Todesrate im Krieg. Die abnehmende Häufigkeit von Sterbefällen seit dem 16. Jahrhundert trägt zur Erklärung von kleineren Familien und letztlich der weitaus geringeren Toleranz gegenüber plötzlichem Tod im Krieg im Vergleich zu früher bei. Dies hat den Effekt gehabt, die Toleranz für Imperialismus zu senken und die Kosten für die Durchsetzung von Macht in Gesellschaften mit niedrigen Geburtenraten zu erhöhen.

Zeitgenössische Gesellschaften, die aus kleinen Familien bestehen, finden selbst geringe Zahlen von Gefallenen in einer Schlacht oft unerträglich. Im Gegensatz dazu zeigten sich frühere Gesellschaften den mortalitätsbedingten Kosten des Imperialismus gegenüber viel toleranter. Vor diesem Jahrhundert brachten die meisten Eltern viele Kinder zur Welt, von denen einige erwartungsgemäß plötzlich und unerwartet durch Krankheiten sterben würden. In einer Ära, in der der frühe Tod an der Tagesordnung war, stellten sich angehende Soldaten und ihre Familien den Gefahren des Schlachtfeldes mit weniger Widerstand.

„Die Maschinerie ist aggressiv. Der Weber wird zu einem Netz, der Maschinist zu einer Maschine. Wenn du keine Werkzeuge benutzt, benutzen sie dich.“ - Emerson

4\. Technologie hat bei der Bestimmung von Kosten und Belohnungen der Machtausübung in den modernen Jahrhunderten bei weitem die größte Rolle gespielt. Die Argumentation dieses Buches geht davon aus, dass dies auch weiterhin der Fall sein wird. Technologie hat mehrere entscheidende Dimensionen:

A. Gleichgewicht zwischen Angriff und Verteidigung. Das Gleichgewicht zwischen Angriff und Verteidigung, das durch die vorherrschende Waffentechnologie impliziert wird, hilft dabei, das Ausmaß der politischen Organisation zu bestimmen. Wenn die Angriffsfähigkeiten steigen, dominiert die Fähigkeit, Macht auf Distanz zu projizieren, Jurisdiktionen neigen dazu sich zu konsolidieren, und es entstehen in größerem Maßstab Regierungen. In anderen Zeiten, wie den jetzigen, steigt die Verteidigungsfähigkeit. Das macht es teurer, Macht außerhalb der Kerngebiete zu projizieren. Jurisdiktionen neigen dazu, sich aufzulösen, und große Regierungen zerbrechen in kleinere Einheiten.

B. Gleichheit und die Vorherrschaft der Infanterie. Ein Hauptmerkmal, das den Grad der Gleichheit unter den Bürgern bestimmt, ist die Art der Waffentechnologie. Waffen, die vergleichsweise billig sind, von Laien verwendet werden können und die militärische Bedeutung der Infanterie erhöhen, tendieren dazu, die Machtverhältnisse auszugleichen. Als Thomas Jefferson schrieb, dass „alle Menschen gleich geschaffen sind“, sagte er etwas, was viel wahrer war als eine ähnliche Aussage Jahrhunderte zuvor hätte scheinen können. Ein Bauer mit seinem Jagdgewehr war nicht nur so gut bewaffnet wie der typische britische Soldat mit seiner Brown Bess, er war sogar besser bewaffnet. Der Bauer konnte mit dem Gewehr aus größerer Distanz und mit größerer Genauigkeit auf den Soldaten schießen, als der Soldat zurückfeuern konnte. Dies war ein deutlich anderer Umstand als im Mittelalter, als ein Bauer mit einer Mistgabel -- mehr hätte er sich nicht leisten können -- kaum darauf hoffen konnte, gegen einen schwer bewaffneten Ritter zu Pferde Stand zu halten. Niemand schrieb 1276, dass „alle Menschen gleich geschaffen sind“. Zu dieser Zeit waren die Menschen im offensichtlichsten Sinne nicht gleich. Ein einzelner Ritter übte viel mehr rohe Gewalt aus als Dutzende von Bauern zusammen.

C. Vorteile und Nachteile der Skalierung von Gewalt. Eine weitere Variable, die hilft zu bestimmen, ob es wenige große Regierungen oder viele kleine gibt, ist die Skalierung der Organisation, die zur Entfaltung der vorherrschenden Waffen benötigt wird. Wenn es steigende Erträge durch Gewalt gibt, ist es lohnender, Regierungen in großem Maßstab zu betreiben, und diese neigen dazu, größer zu werden. Wenn eine kleine Gruppe effektive Mittel zur Abwehr eines Angriffs durch eine große Gruppe hat, was im Mittelalter der Fall war, neigt die Souveränität dazu, zu zerbrechen. Kleine, unabhängige Autoritäten übernehmen viele Funktionen der Regierung. Wie wir in einem späteren Kapitel näher ausführen, glauben wir, dass das Informationszeitalter die Ära der Cybersoldaten einläuten wird, die Vorboten der Dezentralisierung sein werden. Cybersoldaten könnten nicht nur von Nationalstaaten, sondern auch von sehr kleinen Organisationen und sogar Einzelpersonen eingesetzt werden. Die Kriege des nächsten Jahrtausends werden einige fast blutlose Schlachten beinhalten, die mit Computern geführt werden.

D. Skaleneffekte in der Produktion. Ein weiterer wichtiger Faktor, der Einfluss darauf hat, ob die letztendliche Macht lokal oder aus der Ferne ausgeübt wird, ist die Rate der vorherrschenden Unternehmen, durch die die Menschen ihren Lebensunterhalt verdienen. Wenn entscheidende Unternehmen nur dann optimal funktionieren können, wenn sie in einem umfassenden Handelsgebiet großflächig organisiert sind, können Regierungen, die sich ausweiten, um ein solches Umfeld für die unter ihrem Schutz stehenden Unternehmen bereitzustellen, genug zusätzlichen Reichtum abschöpfen, um die Kosten für die Aufrechterhaltung eines großen politischen Systems zu decken. Unter solchen Bedingungen funktioniert die gesamte Weltwirtschaft in der Regel effektiver, wenn eine höchste Weltmacht alle anderen dominiert, wie es das Britische Empire im neunzehnten Jahrhundert tat. Aber manchmal kombinieren sich die megapolitischen Variablen, um fallende Skaleneffekte zu erzeugen. Wenn die wirtschaftlichen Vorteile der Aufrechterhaltung eines großen Handelsraums schwinden, können größere Regierungen, die zuvor von den Vorteilen größerer Handelsgebiete profitierten, damit beginnen auseinanderzubrechen -- selbst wenn die Balance der Waffentechnik zwischen Angriff und Verteidigung ansonsten weitgehend erhalten bleibt.

E. Verbreitung der Technologie. Ein weiterer Faktor, der zur Machtangleichung beiträgt, ist das Ausmaß der Verbreitung entscheidender Technologien. Wenn Waffen oder Produktionsmittel effektiv gehortet oder monopolisiert werden können, neigen sie dazu, die Macht zu zentralisieren. Sogar Technologien, die im Wesentlichen defensiven Charakter haben, wie das Maschinengewehr, erwiesen sich als potente Angriffswaffen, die während der Zeit, in der sie nicht weit verbreitet waren, zu einer steigenden Größe der Regierung beitrugen.

Als die europäischen Mächte Ende des neunzehnten Jahrhunderts ein Monopol auf Maschinengewehre besaßen, konnten sie diese Waffen gegen Völker in der Peripherie einsetzen, um ihre kolonialen Reiche dramatisch zu erweitern. Später, im zwanzigsten Jahrhundert, als Maschinengewehre, insbesondere nach dem Zweiten Weltkrieg, weit verbreitet waren, wurden sie eingesetzt, um die Macht der Imperien zu zerstören. Unter ansonsten gleichen Bedingungen tendiert Macht dazu, umso breiter verteilt zu sein, je weitflächiger entscheidende Technologien verteilt sind und umso kleiner ist die optimale Größe der Regierung.

## DIE GESCHWINDIGKEIT MEGAPOLITISCHER VERÄNDERUNGEN

Obwohl Technologie heute bei weitem der wichtigste Faktor ist und anscheinend immer mehr an Bedeutung gewinnt, haben alle vier großen megapolitischen Faktoren in der Vergangenheit eine Rolle dabei gespielt, den Umfang zu bestimmen, in dem Macht ausgeübt werden konnte.

Zusammen bestimmen diese Faktoren, ob die Rendite von Gewalt weiter steigt, wenn Gewalt in größerem Ausmaß angewendet wird. Dies bestimmt die Bedeutung des Ausmaßes der Feuerkraft gegenüber der Effizienz in der Nutzung von Ressourcen. Es beeinflusst auch stark die Einkommensverteilung auf dem Markt. Die Frage lautet: Welche Rolle werden sie in der Zukunft innehaben? Ein Schlüssel zur Abschätzung einer Antwort liegt in der Erkenntnis, dass diese megapolitischen Variablen sich mit dramatisch unterschiedlichen Geschwindigkeiten verändern.

Die Topographie ist durch die gesamte aufgezeichnete Geschichte hindurch fast unverändert geblieben. Abgesehen von geringfügigen lokalen Auswirkungen durch die Versandung von Häfen, Geländeauffüllung oder Erosion, ist die Topographie der Erde fast dieselbe wie zu der Zeit, als Adam und Eva aus dem Garten Eden auszogen. Und es ist wahrscheinlich, dass es so bleiben wird, bis eine weitere Eiszeit die Landschaften der Kontinente neu formt oder irgendein anderes dramatisches Ereignis die Oberfläche der Erde stört. Auf einer tieferen Skala scheinen geologische Zeitalter sich zu verschieben, vielleicht als Reaktion auf große Meteoriteneinschläge, über einen Zeitraum von 10 bis 40 Millionen Jahren. Irgendwann könnte es erneut geologische Umwälzungen geben, die die Topographie unseres Planeten erheblich verändern. Wenn das passiert, können Sie sicher davon ausgehen, dass sowohl die Fußball- als auch die Ski-Saison abgesagt werden.

Das Klima schwankt weitaus aktiver als die Topographie. In den letzten Millionen Jahren war der Klimawandel für den Großteil der bekannten Variationen in den Merkmalen der Erdoberfläche verantwortlich. Während der Eiszeiten schnitten Gletscher neue Täler, veränderten den Verlauf der Flüsse, trennten Inseln von Kontinenten oder verbanden sie durch Absenkung des Meeresspiegels miteinander.

Schwankungen im Klima haben in der Geschichte eine bedeutende Rolle gespielt, zunächst durch die Auslösung der Agrarrevolution nach dem Ende der letzten Eiszeit und später durch die Destabilisierung von Regierungen in Zeiten kälterer Temperaturen und Dürren.

In letzter Zeit gab es Bedenken hinsichtlich der möglichen Auswirkungen der „globalen Erwärmung“. Diese Bedenken können nicht einfach abgetan werden. Doch aus einem langfristigen Blickwinkel erscheint das Risiko einer Verschiebung hin zu einem kälteren, nicht zu einem wärmeren Klima wahrscheinlicher. Studien von Temperaturschwankungen, basierend auf der Analyse von Sauerstoffisotopen in Kernproben vom Meeresboden, zeigen, dass die gegenwärtige Periode die zweitwärmste seit mehr als 2 Millionen Jahren ist.[^50] Sollten sich die Temperaturen abkühlen, wie sie es im siebzehnten Jahrhundert taten, könnte dies megapolitisch destabilisierend wirken. Aktuelle Alarmmeldungen über die globale Erwärmung könnten in diesem Sinne beruhigen. In dem Maße, in dem sie wahr sind, gewährleisten sie, dass die Temperaturen weiterhin innerhalb des ungewöhnlich warmen und relativ harmlosen Bereichs schwanken, den wir in den letzten drei Jahrhunderten erlebt haben.

Die Geschwindigkeit, mit der sich der Einfluss von Mikroben auf die Ausübung von Macht verändert, ist ein größeres Rätsel. Mikroben können sehr schnell mutieren. Dies gilt insbesondere für Viren. Die gewöhnliche Erkältung zum Beispiel mutiert auf nahezu kaleidoskopische Weise. Obwohl diese Mutationen schnell voranschreiten, war ihre Auswirkung auf die Verschiebung der Grenzen, innerhalb derer Macht ausgeübt wird, weit weniger abrupt als technologische Veränderungen. Warum? Ein Teil der Antwort liegt darin, dass das natürliche Gleichgewicht dazu neigt, es für Mikroben vorteilhaft zu machen, Wirtspopulationen zu infizieren, aber nicht zu zerstören. Sehr aggressive Infektionen, die ihre Wirte zu schnell töten, neigen dazu, sich im Prozess selbst zu eliminieren. Das Überleben von Mikroparasiten hängt davon ab, dass sie für die Wirte, in die sie eindringen, nicht zu schnell oder gleichmäßig tödlich sind.

Das bedeutet natürlich nicht, dass es keine tödlichen Ausbrüche von Krankheiten geben kann, die das Gleichgewicht der Macht verändern. Solche Episoden haben in der Geschichte eine hervorgehobene Rolle gespielt. Der schwarze Tod raffte große Teile der Bevölkerung von Eurasien hinweg und versetzte der internationalen Wirtschaft des vierzehnten Jahrhunderts einen vernichtenden Schlag.

### Was hätte sein können

Die Geschichte kann sowohl in Bezug auf das, was hätte sein können, als auch auf das, was war, verstanden werden. Wir wissen nicht, warum Mikroparasiten nicht weiterhin Unheil in der menschlichen Gesellschaft während der Neuzeit anrichten können sollten. Beispielsweise ist es möglich, dass sich mikrobiologische Barrieren für die Ausübung von Macht, vergleichbar mit Malaria aber virulenter, hätten aufbauen können und so die westliche Invasion der Peripherie aufgehalten hätten. Die ersten mutigen portugiesischen Abenteurer, die in afrikanische Gewässer segelten, hätten sich beispielsweise ein tödliches Retrovirus, eine ansteckendere Version von AIDS, einfangen können, das die Eröffnung der neuen Handelsroute nach Asien gestoppt hätte, bevor sie überhaupt begonnen hatte. Auch Kolumbus und die ersten Wellen von Siedlern in der neuen Welt hätten auf Krankheiten stoßen können, die sie auf die gleiche Weise dezimiert hätten, wie die indigenen lokalen Bevölkerungen durch Masern und andere westliche Kinderkrankheiten betroffen waren. Doch nichts dergleichen geschah, was die Intuition unterstreicht, dass die Geschichte ein Schicksal hat.

Mikroben haben in der modernen Ära viel weniger zur Behinderung der Machtkonsolidierung beigetragen als zu deren Förderung. Westliche Truppen und Siedler in der Peripherie fanden oft heraus, dass die technologischen Vorteile, die es ihnen ermöglichten, Macht auszuüben, von mikrobiologischen unterstrichen wurden. Die Westler waren mit unsichtbaren biologischen Waffen ausgestattet, ihrer relativen Immunität gegen Kinderkrankheiten, die die einheimischen Völker häufig verwüsteten. Dies gab Reisenden aus dem Westen einen deutlichen Vorteil, den ihre Gegner aus weniger dicht besiedelten Gebieten nicht besaßen. Wie sich die Ereignisse entwickelten, erfolgte der Krankheitstransfer fast ausschließlich in eine Richtung - von Europa nach außen. Es gab keine äquivalente Übertragung von Krankheiten in die andere Richtung, vom Rand zum Kern.

Als mögliches Gegenbeispiel haben einige behauptet, dass westliche Entdecker die Syphilis aus der neuen Welt nach Europa brachten. Dies ist umstritten. Wenn dies jedoch wahr wäre, stellte es kein signifikantes Hindernis für die Ausübung von Macht dar. Der Haupteffekt der Syphilis bestand darin, die sexuellen Moralvorstellungen im Westen zu verändern. Vom Ende des fünfzehnten Jahrhunderts bis zum letzten Viertel des zwanzigsten Jahrhunderts wurde der Einfluss von Mikroben auf die industrielle Gesellschaft immer harmloser. Ungeachtet der persönlichen Tragödien und des Unglücks, die durch Ausbrüche von Tuberkulose, Polio und Grippe verursacht wurden, traten in der modernen Zeit keine neuen Krankheiten auf, die annähernd den megapolitischen Einfluss der Antoninischen Pest oder des Schwarzen Todes hatten. Die Verbesserung der öffentlichen Gesundheit sowie das Aufkommen von Impfungen und Gegenmitteln reduzierten im Allgemeinen die Bedeutung von infektiösen Mikroben während der modernen Periode und erhöhten dadurch die relative Bedeutung der Technologie bei der Festlegung der Grenzen, innerhalb derer Macht ausgeübt wurde.

Das kürzliche Auftauchen von AIDS und die Warnungen vor der potenziellen Ausbreitung exotischer Viren sind Hinweise darauf, dass die Rolle von Mikroben in der Zukunft möglicherweise nicht so megapolitisch harmlos sein könnte, wie sie es in den letzten fünfhundert Jahren war. Aber wann oder ob eine neue Pandemie die Welt befallen wird, ist unbekannt. Eine Eruption von Mikroparasiten, wie einer viralen Pandemie, würde wahrscheinlich eher die megapolitische Dominanz der Technologie stören als drastische Veränderungen im Klima oder in der Topographie.

Wir haben keine Möglichkeit, drastische Abweichungen von der Natur des Lebens auf der Erde, wie wir sie kennen, zu überwachen oder vorauszusehen. Wir drücken die Daumen und gehen davon aus, dass die wesentlichen megapolitischen Variablen im nächsten Jahrtausend eher technologischer als mikrobiologischer Natur sein werden. Wenn das Glück weiterhin auf der Seite der Menschheit steht, wird Technologie weiterhin als die führende megapolitische Variable an Bedeutung zunehmen.

Das war jedoch nicht immer so, wie eine Überprüfung der ersten großen Megapolitik-Transformation, der Agrarrevolution, klar zeigt.

[^29]: Huizinga, ebenda, S. 7.

[^30]: *The Compact Edition of the Oxford English Dictionary*, Vol. 1 (Oxford: Oxford University Press, 1971), S. 1828.

[^31]: Michael Hicks, *Bastard Feudalism* (London: Longmans, 1995), S. 1.

[^32]: Ebenda, S. 102.

[^33]: Siehe S. A. Cook et al., eds., *The Cambridge Ancient History*, Vol. 12 (Cambridge: Cambridge University Press, 1971), pp. 208-22.

[^34]: Ebenda, pp. 209-20.

[^35]: Will Durant, *The Story of Civilization*, Vol. 4, *The Age of Faith* (New York: Simon & Schuster, 1950), S. 43.

[^36]: C. W. Previte-Orton, *The Shorter Cambridge Medieval History*, Vol. 1 (Cambridge: Cambridge University Press, 1971), S. 102.

[^37]: Ebenda, S. 131.

[^38]: Ebenda, S. 137.

[^39]: Ebenda.

[^40]: Durant, ebenda, S. 43.

[^41]: Ramsay MacMullen, *Corruption and the Decline of Rome* (New Haven: Yale University Press, 1988), S. 192.

[^42]: Zitiert ebenda, S. 193.

[^43]: Zitiert aus David Kline und Daniel Burstein, *Is Government Obsolete?*, Wired, Januar 1996, S. 105.

[^44]: Lane, *Economic Consequences of Organized Violence*, ebenda.

[^45]: Ebenda.

[^46]: Susan AIling Gregg, *Foragers and Farmers: Population Interaction and Agricultural Expansion in Prehistoric Europe* (Chicago: University of Chicago Press, 1988), S. 9.

[^47]: Stephen Boyden, *Western Civilization in Biological Perspective* (Oxford: Clarendon Press, 1987), S. 89. Siehe ebenfalls Marvin Harris, *Cannibals and Kings* (New York: Vintage, 1978), pp. 29-32.

[^48]: Geoffrey Parker und Lesley Ni. Smith, eds., *The General Crisis of the Seventeenth Century* (London: Routledge & Kegan Paul, 1985), S. 8.

[^49]: See Charles Woolsey Cole, *French Mercantilism: 1683-1700* (New York: Octagon Books, 197.1), S. 6.

[^50]: Chris Scarre, ed., *Past Worlds: The Times Atlas of Archaeology* (New York: Random House, 1995), S. 58.
