# Vorwort von Titus Gebel {.unnumbered}

Prognosen sind bekanntlich schwierig, insbesondere, je weiter entfernt die Zukunft ist, die sie betreffen. Wenn aber ein politisches Buch, das solche Prognosen macht, 25 Jahre nach seinem Erscheinen immer noch aufgelegt und sogar erstmals ins Deutsche übertragen wird, dann lagen seine Autoren offenbar in entscheidenden Punkten richtig. Und so ist es auch hier. Diese Punkte betreffen Demokratie, Nationalstaat, Politik, Kryptowährungen und den Machtzuwachs des selbstbestimmten Einzelnen. Der vorhergesagte Wandel hat vielleicht etwas später eingesetzt, als die Autoren seinerzeit vermutet haben; aber er ist gerade jetzt im vollen Gange und deshalb ist dieses Buch so bedeutend.

Während der politisch-mediale Hauptstrom der Neunzigerjahre, verkörpert durch Francis Fukuyama, der Ansicht war, die westlichen Demokratien seien das Ende der Geschichte, vertreten die Autoren dieses Buches das genaue Gegenteil: „*Wir gehen davon aus, dass die repräsentative Demokratie, so wie wir sie heute kennen, verschwinden und durch die neue Demokratie der Wahlfreiheit ... ersetzt werden wird."*

Davon ist in der Tat auszugehen, und zwar im Wesentlichen aus drei Gründen: Erstens enden herkömmliche Demokratien, ohne Ausnahme, früher oder später in einer Art von Sozialismus, nämlich nachdem die Mehrheit herausgefunden hat, dass sie sich Geld in die eigene Tasche wählen kann. Deshalb wird auch kein Unternehmen auf dieser Welt demokratisch geführt. Zweitens sind umverteilende Systeme, denen nicht jeder Betroffene vorab zugestimmt hat, illegitim. Sie sind Verträge zulasten Dritter, eine Rechtsfigur, die in sämtlichen Privatrechtsordnungen dieser Welt unzulässig ist. Drittens gibt es keinen ethisch-moralischen Grund, einem Gesetz unterworfen zu sein, dessen Geltung man nicht zugestimmt hat. Dafür gibt es keine stichhaltige philosophische Rechtfertigung, wenn wir von der Gleichwertigkeit aller erwachsenen Menschen ausgehen.

Die historische Entwicklung staatlicher Systeme belegt die Schlussfolgerung von Davidson und Rees-Mogg ebenfalls: Früher bestimmte der König, wie ich zu leben habe, jetzt bestimmt die Mehrheit, wie ich zu leben habe, und in Zukunft werde ich selbst bestimmen, wie ich leben möchte. Vom Untertanen zum Bürger, vom Bürger zum Kunden.

Auch die Macht der Nationalstaaten schwindet vielerorts und wie von den Autoren vorhergesagt, zerteilen sich manche in kleinere Einheiten. Es gibt heute mehr unabhängige Staaten und Gebiete als noch zum Zeitpunkt des Erscheinens des Buches. Hinzu kommt, dass internationale Organisation mehr und mehr Entscheidungsbefugnis an sich ziehen, und den Nationalstaat so auch von außen immer weiter entmachten. Grenzen von Nationalstaaten spielen immer weniger eine Rolle, wenn von überall online gearbeitet werden kann. Das ist bereits im großen Maßstab möglich und erschwert zunehmend die Besteuerung. Selbst wenn China momentan als gefestigter Nationalstaat erscheint, der vor Kraft kaum laufen kann: ein verlorener Krieg, etwa um Taiwan, könnte das sehr schnell ändern.

Auch die Prognose, dass wir mehr kleinere Rechtsordnungen sehen werden, die wie Hongkong nach dem Modell „Ein Land - Zwei Systeme" funktionieren, war richtig. Zwar wird Hongkong vom Mutterland China zunehmend wieder absorbiert, aber global gesehen ist das Modell auf dem Vormarsch. Als das Buch 1999 erstmals erschien, gab es etwa 500 Sonderwirtschaftszonen, die Sonderregelungen in bestimmten Bereichen vorsehen, heute sind es fast 8000! Jede einzelne Sonderwirtschaftszone ist dabei bereits ein stillschweigendes Eingeständnis des Staates, dass seine Regelungen offenbar nicht für alle optimal sind.

Die innovativsten dieser Zonen gehen bereits in Richtung eines echten Parallelsystems, man denke etwa an das *Dubai International Financial Center* mit eigener Gerichtsbarkeit und eigenem Common-Law-System, die Honduranischen ZEDEs, welche erlauben, ein komplettes Rechtssystem mitsamt eigener Institutionen neu zu schaffen, oder das Megaprojekt NEOM in Saudi-Arabien, wo der Staat selbst ein zweites System innerhalb seines Gebietes errichtet, das ausdrücklich liberalere Regelungen als das Mutterland haben soll.

Auch wenn es derzeit noch nicht so aussieht: auf lange Sicht wird die Politik, also das Erheben von Wünschen einzelner zum Maßstab für alle, zurückgehen. Denn Politik ist in jeder Form, die sie annimmt, kooperationshemmende Intervention. Es kann im Sinne der Freiheit und Selbstbestimmung daher keine „richtige" Politik geben. Freiheitsfördernd ist nur der größtmögliche Verzicht auf Politik.

Die Entstehung von digitalem Geld, das staatlichem Einfluss nicht unterliegt, wurde von den Autoren bereits mehr als zehn Jahre vor der Schaffung von Bitcoin vorhergesagt. Noch haben Kryptowährungen das staatliche Fiat-Geld nicht als Hauptzahlungsmittel abgelöst, aber nach der nächsten Hyperinflation werden die Karten neu gemischt.

Im Informationszeitalter führen die neuen technischen Entwicklungen zwar dazu, dass der Staat umfassender überwachen kann. Auf der anderen Seite ermöglichen sie dem Einzelnen aber auch, durch Verschlüsselung und die Nutzung von VPNs etc. wirksame Gegenmittel zu entwickeln. Heute erreichen einzelne Podcaster mehr Menschen als große Fernsehsender mit ihren Milliardenbudgets. Insgesamt kann der Einzelne mithilfe der Informationstechnologie deutlich mehr Schlagkraft und Reichweite entwickeln als noch vor 25 Jahren, und genau das war die Prognose von Davidson und Rees-Mogg.

Die Autoren haben weiter gewarnt, dass der Nationalstaat all das nicht kampflos hinnehmen werde. Betrachtet man die Einschränkung der Grundrechte während der COVID-Zeit, die Klima-Planwirtschaft, die immer anmaßenderen Anti-Geldwäsche-Maßnahmen, die ein Hundertfaches von dem kosten, was sie finanziell einbringen, der Versuch, die Meinungsfreiheit massiv zu beschneiden und die kartellartigen Bemühungen, eine globale Mindeststeuer einzuführen, wird klar, dass jetzt die schweren Geschütze aufgefahren werden, um den Bedeutungsverlust des Staates und seiner zahllosen Kostgänger abzuwenden. Willfährige Wissenschaftler haben bereits Theorien bereitgestellt, wonach grenzenloses Gelddrucken überhaupt kein Problem sei. Und wenn gar nichts mehr hilft, wird eben ein Krieg vom Zaun gebrochen.

Mit keiner dieser Maßnahmen zum Machterhalt wird aber der erreichte Wohlstand aufrechterhalten werden können. Wissen ist dezentral und je mehr Freiheit der Einzelne hat, desto mehr Produktivität wird freigesetzt. Je enger der Würgegriff der Regulierung an den Menschen und Märkten anliegt, desto geringer wird der Output. Jeder Staat, der das nicht versteht, ist ein *Ancien Régime* und wird das Schicksal seiner Vorgänger teilen.

Die meisten Menschen wollen sich nicht Regeln und Vorschriften unterwerfen, denen sie nicht zugestimmt haben. Die meisten Menschen wollen nicht für Dinge bezahlen, die sie nicht bestellt haben. Und vernünftige Menschen brauchen nicht Hunderte oder Tausende von Gesetzen, um friedlich zusammenzuleben. Stattdessen benötigen die Menschen einen sicheren Raum, in dem sie leben und mit anderen zusammenarbeiten können, aber ansonsten in Ruhe gelassen werden.

Die bestehenden politischen Systeme können diese Wünsche nicht mehr erfüllen. Aus diesem Grund haben neue, kundenorientierte Konzepte wie Freie Privatstädte eine Chance auf Erfolg, wie von den Autoren vorhergesagt. Am Ende gehen die Menschen nämlich dorthin, wo sie am besten behandelt werden. Oder, um mit dem Titel des Buches zu sprechen, wo sie souveräne Individuen sein können.

\vspace{2em}

--- **Titus Gebel**
