# ÖSTLICH VON EDEN

:::{.content-hidden when-format=latex}
*Die Landwirtschaftliche Revolution und die Kultivierung der Gewalt*
:::

> \“Und der Herr sprach zu Kain: Wo ist Abel, dein Bruder? Und er antwortete: Ich weiß es nicht: Bin ich meines Bruders Hüter? Und er sagte: Was hast du getan? Die Stimme des Blutes deines Bruders schreit zu mir aus dem Erdboden.\“ - GENESIS 4:9-10

Vor fünfhundert Generationen begann die erste grundlegende Veränderung in der Organisation der menschlichen Gesellschaft.[^51] Unsere Vorfahren in mehreren Regionen haben widerwillig grobe Werkzeuge, geschärfte Pfähle und improvisierte Hacken aufgenommen und sind zur Arbeit gegangen. Als sie die ersten Kulturen säten, legten sie auch ein neues Fundament für die Macht in der Welt. Die Agrarrevolution war die erste große ökonomische und soziale Revolution. Sie begann mit der Vertreibung aus Eden und schritt so langsam voran, dass die Landwirtschaft zu Beginn des zwanzigsten Jahrhunderts das Jagen und Sammeln in allen geeigneten Gebieten der Welt noch nicht völlig verdrängt hatte. Experten glauben, dass selbst im Nahen Osten, wo die Landwirtschaft zuerst entstand, sie in einem „langen inkrementellen Prozess“ eingeführt wurde, der „möglicherweise fünftausend Jahre oder länger“ gedauert hat.[^52]

Es mag übertrieben erscheinen, einen Prozess, der über Jahrtausende hinweg stattfand, als „Revolution“ zu bezeichnen. Dennoch war genau das der Beginn der Landwirtschaft: eine langsame Revolution, die das menschliche Leben veränderte, indem sie die Logik der Gewalt veränderte. Überall dort, wo die Landwirtschaft Wurzeln schlug, wurde Gewalt zu einem wichtigeren Merkmal des sozialen Lebens. Hierarchien, die geschickt darin waren, Gewalt zu manipulieren oder zu kontrollieren, begannen, die Gesellschaft zu dominieren.

Das Verständnis der Agrarrevolution ist der erste Schritt zum Verständnis der Informationsrevolution. Die Einführung von Bodenbearbeitung und Ernte ist ein Paradigma dafür, wie eine scheinbar einfache Verschiebung in der Beschaffenheit von Arbeit die Organisation der Gesellschaft radikal verändern kann. Schaut man diese vergangene Revolution im richtigen Licht an, ist man viel besser in der Lage, Vorhersagen zu treffen, wie die Geschichte sich aufgrund der neuen Logik der Gewalt entwickeln könnte, die mit Mikroprozessoren eingeführt wurde.

Um die revolutionäre Natur der Landwirtschaft zu würdigen, benötigt man zuerst ein Bild davon, wie die urzeitliche Gesellschaft funktionierte, bevor der Ackerbau eingeführt wurde. Wir haben dies in *The Great Reckoning* untersucht und bieten unten einen weiteren Überblick. Jäger- und Sammlergesellschaften waren die einzigen Formen sozialer Organisation während eines langen, prähistorischen Dornröschenschlafs, in dem das menschliche Leben sich von Generation zu Generation wenig oder gar nicht veränderte. Anthropologen behaupten, dass die Menschen seit ihrem Auftreten auf der Erde zu 99 Prozent Jäger und Sammler waren. Entscheidend für den langen Erfolg und letztendlichen Misserfolg der Jäger- und Sammlergruppen ist die Tatsache, dass sie in kleiner Zahl über ein sehr weites Gebiet operieren mussten.

Jäger und Sammler konnten nur dort überleben, wo die Bevölkerungsdichte gering war. Um zu verstehen warum, denken Sie über die Probleme nach, die größere Gruppen verursacht hätten. Zum einen hätte eine Gruppe von tausend Jägern, die sich gemeinsam durch eine Landschaft bewegten, ein solches Getöse gemacht, dass sie das Wild, das sie zu fangen suchten, weggescheucht hätten. Noch schlimmer, wenn eine kleine Armee von Jägern es gelegentlich geschafft hätte, eine riesige Herde Wild zu stellen, hätte die Nahrung, die sie geerntet hätten, einschließlich Früchten und essbarer Pflanzen, die in freier Wildbahn gefunden wurden, nicht lange ausreichend bleiben können. Eine große Gruppe von Sammlern hätte die Landschaft durch Überernte verwüstet, genau wie eine hungernde Armee im Dreißigjährigen Krieg. Daher mussten Jagdgruppen, um Übermaß zu vermeiden, klein sein. Wie Stephen Boyden in „Western Civilization in Biological Perspective“ schreibt, „bestehen die meisten Jäger-und-Sammler-Gruppen aus zwanzig bis fünfzig Einzelpersonen.“ [^53]

Auf zehntausend Hektar in einem gemäßigten Klima zu leben ist heute ein Luxus, den sich nur die sehr reichen leisten können. Eine Familie von Jägern und Sammlern hätte kaum mit weniger überleben können. Sie benötigten im Allgemeinen Tausende von Hektar pro Person, selbst in den Gebieten, die am fruchtbarsten waren. Dies legt nahe, warum das Wachstum der menschlichen Bevölkerung in besonders landwirtschaftlich günstigen Perioden die Grundlage für Bevölkerungskrisen geschaffen haben könnte. Da zur Unterstützung einer einzelnen Person so viel Land benötigt wurde, mussten die Bevölkerungsdichten der Jagd- und Sammelgesellschaften unglaublich gering sein. Vor der Landwirtschaft siedelten Menschen etwa so dicht wie Bären.

Mit geringfügigen Unterschieden ähnelte die menschliche Ernährung der von Bären. Sammlergesellschaften waren auf Nahrung angewiesen, die im offenen Gelände oder in nahe gelegenen Gewässern gesammelt wurde. Obwohl einige Sammler Fischer waren, waren die meisten Jäger, die für ein Drittel bis ein Fünftel ihrer Ernährung auf Proteine aus großen Säugetieren angewiesen waren. Mit Ausnahme einiger weniger einfacher Werkzeuge und Gegenstände, die sie bei sich trugen, hatten Jäger und Sammler kaum Technologie zur Verfügung. Sie hatten meistens keine Möglichkeit, große Mengen Fleisch oder andere Lebensmittel für die spätere Verwendung effektiv zu lagern. Die meisten Lebensmittel mussten bald konsumiert oder zum Verderben übrig gelassen werden. Das bedeutet natürlich nicht, dass nicht einige Jäger und Sammler verdorbenes Essen gegessen haben. Eskimos, so berichtet Boyden, „sollen eine besondere Vorliebe für verdorbenes Essen haben.“ [^54] Er wiederholt Beobachtungen von Experten, dass Eskimos „Fischköpfe vergraben und sie verfaulen lassen, bis die Knochen die gleiche Konsistenz wie das Fleisch erreichen. Sie kneten dann die stinkende Masse zu einer Paste und essen sie“; sie genießen auch die „fetten, madigen Larven der Karibufliege, die roh serviert werden\... Hirschexkremente, die wie Beeren gekaut werden\... und Knochenmark, das älter als ein Jahr ist, wimmelt von Maden.“ [^55]

Neben solchen Delikatessen entwickelten Jäger und Sammler kaum Nahrungsüberschüsse. Wie der Anthropologe Gregg anmerkt: „Mobile Bevölkerungsgruppen lagern generell keine Nahrungsmittel für saisonale oder unerwartete Mängel an Ressourcen ein“. Folglich hatten Jäger und Sammler wenig zu stehlen. Eine Arbeitsteilung, die eine Spezialisierung auf den Einsatz von Gewalt einschloss, war in Situationen, in denen überschüssige Nahrung nicht gespeichert werden konnte, untragbar. Die Logik der Jagd verlangte auch, dass Gewalt innerhalb von Jäger- und Sammlergruppen nie über einen kleinen Rahmen hinaus ansteigen konnte, da die Gruppen selbst klein bleiben mussten.

Die geringe Größe der Sammlergruppen war auf eine andere Weise von Vorteil. Mitglieder solcher kleinen Gruppen hätten sich gegenseitig genauestens gekannt, ein Faktor, der sie effektiver in der Zusammenarbeit machte. Entscheidungsfindung wird schwieriger, wenn die Anzahl steigt, denn die Gefahr von Meinungsverschiedenheiten nimmt zu. Man braucht nur darüber nachzudenken, wie schwierig es ist, ein Dutzend Leute dafür zu organisieren, essen zu gehen. Man stelle sich vor, wie aussichtslos es gewesen wäre, Hunderte oder Tausende von Personen zu organisieren, die auf einem beweglichen Fest herumlaufen sollten. Da sie keine längerfristige und separate politische Organisation oder Bürokratie hatten, die durch die Spezialisierung für den Krieg benötigt wird, mussten Jäger- und Sammlergruppen auf Überzeugungsarbeit und Konsensbildung angewiesen sein. Diese Prinzipien funktionieren am besten in kleinen Gruppen mit einer relativ gelassenen Einstellung.

Ob Jäger- und Sammlergruppen gelassen waren, ist umstritten. Sir Henry Maine spricht von der „universellen Kriegsführung des primitiven Menschen“. In seinen Worten: „Es ist nicht der Frieden, der natürlich und primitiv ist, sondern der Krieg.“ [^56] Diese Ansicht wurde durch die Arbeit von Evolutionsbiologen bestätigt. R. Paul Shaw und Yuwa Wong bemerken: „Es gibt starke Anhaltspunkte dafür, dass viele Verletzungen, die an den Überresten von Australopithecus, Homo erectus und Homo sapiens aus und vor der vierten Eiszeit Europas sichtbar sind, auf Kämpfe zurückzuführen sind.“ [^57] Aber andere bezweifeln das. Experten wie Stephen Boyden argumentieren, dass primitive Gruppen in der Regel nicht kriegerisch oder gewalttätig waren. Soziale Konventionen wurden entwickelt, um interne Spannungen zu verringern und das Teilen der Jagdbeute zu erleichtern. Insbesondere in Gebieten, in denen Menschen größere Beutetiere jagten, die für einen einzelnen Jäger schwer zu erlegen waren, entstanden religiöse und soziale Lehren, um die Umverteilung von erjagtem Wild innerhalb der gesamten Gruppe zu erleichtern. Die oberste Priorität beim Teilen der kalorienhaltigen Ressourcen galt den anderen Jägern. Die Notwendigkeit, nicht das Mitgefühl, war der Ansporn. Der erste Anspruch auf die Ressourcen wurde von den wirtschaftlich kompetentesten und militärisch stärksten ausgeübt, nicht von den Kranken und Schwachen. Zweifellos war ein wichtiger Einflussfaktor für diese Priorität die Tatsache, dass Jäger in der Blüte ihres Lebens auch die militärisch stärksten Mitglieder der kleinen Gruppe waren. Durch die Garantie eines ersten Anspruchs auf die Jagdbeute minimierte die Gruppe potenziell tödliche interne Streitereien.

Solange die Bevölkerungsdichten gering blieben, waren die Götter der Jäger und Sammler keine kriegerischen Götter, sondern Verkörperungen von natürlichen Kräften oder den Tieren, die sie jagten. Der Mangel an Kapital und offene Grenzen machten Krieg in den meisten Fällen überflüssig. Es gab wenige Nachbarn außerhalb der eigenen kleinen Familie oder des Clans, die eine Bedrohung darstellten. Da die Jäger und Sammler ständig auf der Suche nach Nahrung umherwanderten, wurden persönliche Besitztümer über das absolute Minimum hinaus zu einer Belastung. Diejenigen mit wenigen Besitztümern waren zwangsläufig wenig von Eigentumsdelikten betroffen. Wenn Konflikte aufkamen, waren die strittigen Parteien oft bereit, einfach weiterzuziehen, da sie wenig in einen bestimmten Ort investiert hatten. Flucht war eine einfache Lösung für persönliche Fehden oder übertriebene Forderungen anderer Art. Doch das bedeutet nicht, dass die frühen Menschen friedlich waren. Sie könnten gewalttätig und unangenehm gewesen sein, in einem Ausmaß, das wir uns kaum vorstellen können. Aber wenn sie Gewalt anwendeten, dann meist aus persönlichen Gründen oder, was noch schlimmer sein könnte, zum Spaß.

Die Lebensweise der Jäger und Sammler hing davon ab, dass sie in kleinen Gruppen lebten, die kaum Spielraum für eine Arbeitsteilung jenseits der Geschlechterrollen ließen. Sie verfügten über keine organisierten Regierungen, meistens gab es keine dauerhaften Siedlungen und keine Möglichkeiten, Reichtum anzuhäufen. Selbst derart grundlegende Elemente einer Zivilisation wie eine geschriebene Sprache waren in der ursprünglichen Wirtschaft unbekannt. Ohne eine geschriebene Sprache gab es keine formalen Dokumente und keine Geschichte.

### Übermaß

Die Dynamik des Sammelns und Jagens schuf völlig unterschiedliche Anreize zur Arbeit als jene, an die wir uns seit dem Aufkommen der Landwirtschaft gewöhnt haben. Die Kapitalerfordernisse für ein Leben als Sammler und Jäger waren minimal. Einige primitive Werkzeuge und Waffen genügten. Es gab keinen Anlass für Investitionen, nicht einmal Privatgrundbesitz, außer gelegentlich in Steinbrüchen, in denen Feuerstein oder Speckstein abgebaut wurde.[^58] Wie die Anthropologin Susan Alling Gregg in „Foragers and Farmers“ schrieb, wurde „Eigentum und Zugang zu Ressourcen von der Gruppe gemeinschaftlich gehalten“.[^59] Mit wenigen Ausnahmen, wie Fischern, die an Seen wohnen, zogen Sammler und Jäger meistens umher, hatten also keine feste Bleibe. Da sie keine permanenten Heime hatten, hatten sie wenig Notwendigkeit, schwer zu arbeiten um Besitz zu erwerben oder zu erhalten. Sie hatten weder Hypotheken noch Steuern zu zahlen oder Möbel zu kaufen. Ihre wenigen Konsumgüter waren Tierhäute und persönlicher Schmuck, hergestellt von Mitgliedern der eigenen Gruppe. Es gab wenig Anreiz, etwas zu erwerben oder anzuhäufen, was man als Geld hätte betrachten können, weil es kaum etwas zu kaufen gab. Unter solchen Bedingungen war das Sparen für die Sammler und Jäger kaum mehr als ein rudimentäres Konzept.

Ohne Grund zum Verdienen und fast keiner Arbeitsteilung, muss das Konzept von schwerer Arbeit als Tugend den Jagd- und Sammelgruppen fremd gewesen sein. Außer in Zeiten von ungewöhnlichen Entbehrungen, wenn anhaltende Anstrengungen erforderlich waren, um etwas zu Essen zu finden, wurde wenig Arbeit geleistet, da wenig benötigt wurde. Es war buchstäblich nichts zu gewinnen, indem man über das absolute Minimum hinaus arbeitete, das für das Überleben erforderlich war. Für die Mitglieder einer typischen Jagd- und Sammelgruppe bedeutete das, nur etwa acht bis fünfzehn Stunden pro Woche zu arbeiten. Da die Arbeit eines Jägers das Nahrungsangebot nicht erhöhte, sondern nur verringern konnte, trug jemand, der übermäßig arbeitete, um mehr Tiere zu töten oder mehr Früchte zu pflücken, als vor dem Verderben gegessen werden konnten, nichts zum Wohlstand bei. Im Gegenteil, übermäßiges Töten verringerte die Aussichten auf Nahrung in der Zukunft und hatte somit einen nachteiligen Einfluss auf das Wohlbefinden der Gruppe. Deshalb wurden einige Sammler, zum Beispiel bei den Eskimos, bestraft oder ausgestoßen, wenn sie übermäßig viele Tiere töteten.

Das Beispiel der Eskimos, die das Übermaß bestrafen, ist besonders aufschlussreich, denn sie hätten weit mehr als andere in der Lage sein können, Fleisch durch Einfrieren zu lagern. Außerdem wäre es machbar gewesen, zumindest eine gewisse Lagerung für Öle bereitzustellen, die aus großen Meereslebewesen gewonnen wurden. Die Tatsache, dass die Sammler allgemein entschieden, dies nicht zu tun, spiegelt ihre weitaus passivere Interaktionen mit der Natur wider. Es kann auch den Grad aufzeigen, inwieweit kognitive und geistige Prozesse durch Kultur beeinflusst sind. Beschränkungen beim Lernen und Verhalten in komplexen Umgebungen machen die Übernahme mancher Strategien weitaus schwieriger, als es sonst erscheinen mag. Wie R. Paul Shaw und Yuwa Wong geschrieben haben: „Da sich Lebensräume in vielerlei Hinsicht unterscheiden, variiert auch die Lernverzerrung.“

Aus dieser Perspektive gesehen, brachte das Aufkommen der Landwirtschaft mehr als nur eine Änderung in der Ernährung mit sich; es leitete auch eine große Revolution in der Organisation des wirtschaftlichen Lebens und der Kultur ein und verwandelte die Logik der Gewalt. Die Landwirtschaft schuf groß angelegte Kapitalanlagen in Form von Land und manchmal in Bewässerungssystemen. Die von den Bauern angelegten Getreidevorräte und domestizierten Tiere waren wertvolle Vermögenswerte. Sie konnten gelagert, gehortet und gestohlen werden. Da die Anbauflächen während der gesamten Wachstumsperiode, von der Aussaat bis zur Ernte, gepflegt werden mussten, wurde eine Flucht vor Bedrohungen, insbesondere in trockenen Regionen, in denen die Möglichkeiten zum Anbau begrenzt waren, wenig attraktiv. Da die Flucht schwieriger wurde, nahmen die Möglichkeiten für organisierte Erpressungen und Plünderungen zu. Bauern waren Ernteräubern ausgesetzt, was allmählich das Ausmaß der Kriegsführung erhöhte.

Dies führte dazu, dass die Größe von Gesellschaften zunahm, da Gewaltkonflikte meistens von der größeren Gruppe gewonnen wurden. Als der Wettbewerb um Land und die Kontrolle über dessen Ertrag intensiver wurde, wurden Gesellschaften sesshafter. Eine Arbeitsteilung wurde deutlicher. Beschäftigung und Sklaverei entstanden zum ersten Mal. Bauern und Hirten spezialisierten sich auf die Nahrungsmittelproduktion, Töpfer produzierten Behälter zur Lagerung von Nahrungsmitteln, Priester beteten für Regen und ertragreiche Ernten. Gewaltspezialisten, die Vorläufer von Regierungen, widmeten sich zunehmend der Plünderung und dem Schutz vor Plünderungen. Zusammen mit den Priestern wurden sie zu den ersten reichen Personen in der Geschichte.

In den frühen Stadien landwirtschaftlicher Gesellschaften kamen diese Krieger dazu, einen Teil der jährlichen Ernte als Preis für ihren Schutz zu kontrollieren. In Gegenden, in denen die Bedrohungen minimal waren, konnten selbstständige Bauern manchmal einen relativ großen Grad an Autonomie bewahren. Mit steigender Bevölkerungsdichte und intensiverem Wettbewerb um Nahrung, vor allem in Regionen um Wüsten, wo fruchtbares Land sehr wertvoll war, konnte die Kriegergruppe einen großen Anteil der Gesamtproduktion einnehmen. Mit den Einnahmen aus dieser Abgabe gründeten diese Krieger die ersten Staaten, welche bis zu 25 Prozent der Getreideernte und die Hälfte des Zuwachses an Nutztierherden übernahmen. Die Landwirtschaft erhöhte daher dramatisch die Bedeutung von Zwang und Gewalt. Der Anstieg an Ressourcen, die geplündert werden konnten, führte auch zu einem großen Anstieg an Plünderungen.

Es dauerte Jahrtausende, bis sich die vollständige Logik der Agrarrevolution entfaltete. Eine lange Zeit lebten dünn siedelnde Bevölkerungen von Bauern in gemäßigten Regionen vielleicht noch ähnlich wie ihre Vorfahren, die noch sammelten und jagten. Dort, wo Land und Niederschläge reichlich waren, bewirtschafteten Bauern kleinere Kulturen ohne viel gewaltsame Einmischung. Doch als im Laufe von mehreren tausend Jahren die Bevölkerungszahlen stiegen, wurden selbst Bauern in dünn besiedelten Regionen von gelegentlichen Plünderungen heimgesucht, was manchmal dazu führte, dass sie nicht genug Saatgut hatten, um die Ernte des nächsten Jahres neu zu säen. Wettbewerbsgetriebenes Plündern oder Anarchie waren ein mögliches Extrem, ebenso wie ungeschützte Gemeinschaften, die ohne eine spezialisierte Organisation lebten, um die Gewalt zu monopolisieren.

Im Verlauf der Zeit setzte sich die in der Landwirtschaft inne liegende Gewaltlogik über ein immer größer werdendes Gebiet durch. Die Regionen, in denen Ackerbau und Viehzucht ohne die Raubzüge der Regierung fortgesetzt werden konnten, zogen sich auf wenige wirklich entlegene Gebiete zurück. Die Kafir-Regionen in Afghanistan, um ein extremes Beispiel zu nennen, leisteten bis zum letzten Jahrzehnt des neunzehnten Jahrhunderts Widerstand gegen die Einführung einer Regierung. Aber dadurch wurden sie Jahrhunderte zuvor in eine ziemlich militante Gesellschaft umgewandelt, die entlang von Verwandtschaftslinien organisiert war. Solche Vereinbarungen waren nicht fähig, Kräfte im großen Maßstab zu mobilisieren. Bis die Briten moderne Waffen in die Region brachten, blieben die Kafire in ihren abgelegenen Tälern Bashgal und Waigal unabhängig, weil ihre Zufluchtsorte durch topografische Besonderheiten, hohe Berge und Wüsten vor Eindringlingen von außen geschützt waren.[^62]

Mit der Zeit hinterließ die grundlegende Logik der Agrarrevolution ihre Spuren in den Gesellschaften, in denen die Landwirtschaft Fuß fasste. Die Landwirtschaft erhöhte drastisch den Rahmen, in dem menschliche Gemeinschaften entstehen konnten. Vor etwa zehntausend Jahren begannen die ersten Städte zu entstehen. Obwohl sie nach heutigen Maßstäben winzig waren, bildeten sie die Zentren der ersten „Zivilisationen“, ein Wort, das von „civis“ abgeleitet ist, was auf Latein „Bürger“ oder „Stadtbewohner“ bedeutet. Da die Landwirtschaft Vermögenswerte schuf, die es zu plündern, beziehungsweise zu schützen galt, entstand auch ein Bedarf an Inventarbuchhaltung. Man kann nicht besteuern, wenn man nicht in der Lage ist, Aufzeichnungen zu führen und Quittungen auszustellen. Die in der Buchhaltung verwendeten Symbole wurden die Grundlagen der geschriebenen Sprache, eine Innovation, die es unter Jägern und Sammlern nie gegeben hatte.

Die Landwirtschaft erweiterte auch den Horizont, innerhalb dessen Menschen Probleme lösen mussten. Jagdbanden lebten innerhalb eines unmittelbaren Zeithorizonts. Sie unternahmen selten Projekte, die länger als ein paar Tage dauerten. Aber das Pflanzen und Einbringen einer Ernte dauerte Monate. Längerfristige Projekte zwangen die Landwirte dazu, ihre Aufmerksamkeit auf die Sterne zu richten. Detaillierte astronomische Beobachtungen waren eine Voraussetzung für die Erstellung von Almanachen und Kalendern, die als Leitfaden dienten, wann am besten gepflanzt und geerntet werden sollte. Mit dem Aufkommen der Landwirtschaft erweiterten sich die Horizonte der Jäger.

## EIGENTUM

Der Übergang zu einer sesshaften landwirtschaftlichen Gesellschaft führte zur Entstehung von Privateigentum. Natürlich würde niemand zufrieden sein, eine ganze Wachstumsperiode durchzuarbeiten, um eine Ernte zu produzieren, nur um zu sehen, dass jemand anders daherkam und erntete, was er produziert hatte. Die Idee des Eigentums entstand als unvermeidliche Folge der Landwirtschaft. Aber die Klarheit des Konzepts des Privateigentums wurde durch die Logik der Gewalt getrübt, die auch die Einführung der Landwirtschaft begleitete. Die Entstehung des Eigentums wurde durcheinander gebracht durch die Tatsache, dass die megapolitische Macht von Einzelpersonen nicht mehr in der Art gleich war, wie sie es in Sammlergesellschaften gewesen war, wo jeder gesunde erwachsene Mann ein Jäger war, so gut bewaffnet wie jeder andere. Landwirtschaft führte zur Spezialisierung von Gewalt. Gerade weil es nun etwas zum Stehlen gab, machte Landwirtschaft Investitionen in bessere Waffen rentabel. Das Ergebnis war Raub, in vielerlei Hinsicht hoch organisiert.

Die Mächtigen waren nun in der Lage, eine neue Form des Raubes zu organisieren: ein Monopol auf Gewalt, beziehungsweise eine Regierung. Dies unterschied die Gesellschaften deutlich und schuf völlig verschiedene Umstände für diejenigen, die von der Plünderung profitierten, und die große Masse an Armen, die die Felder bearbeiteten. Die wenigen, die die militärische Macht kontrollierten, konnten nun reich werden, zusammen mit anderen, die bei ihnen in der Gunst standen. Die Gott-Könige und ihre Verbündeten, die verschiedenen kleineren, lokalen Machthaber, die die ersten Nahoststaaten regierten, genossen eine nahezu moderne Form des Eigentums verglichen mit der großen Masse, die unter ihnen arbeitete.

Natürlich ist es anachronistisch, in den frühen landwirtschaftlichen Gesellschaften einen Unterschied zwischen privatem und öffentlichem Reichtum zu sehen. Der regierende Gott-König hatte die vollen Ressourcen des Staates in einer Weise zu seiner Verfügung, die kaum vom Besitz eines weitläufigen Anwesens zu unterscheiden war. Ganz wie in der feudalen Periode der europäischen Geschichte war jeglicher Besitz der Oberherrschaft höherer Machthaber unterworfen. Diejenigen weiter unten in der Hierarchiekette mussten mit einer Verringerung ihres Eigentums nach den Launen des Herrschers rechnen.

Doch zu sagen, dass der Machthaber nicht durch das Gesetz eingeschränkt war, bedeutet nicht, dass er sich leisten konnte, alles zu nehmen, was ihm gefiel. Kosten und Belohnungen wirkten genauso stark auf die Freiheit des Pharaos ein wie heute auf den Premierminister von Kanada. Und der Pharao war durch die Schwierigkeiten von Transport und Kommunikation weitaus stärker eingeschränkt als heutige Führer. Einfach nur die Beute von einem Ort zum nächsten zu transportieren, insbesondere wenn die Beute hauptsächlich in Form von landwirtschaftlichen Erzeugnissen gemessen wurde, ging häufig mit Verlusten durch Verderb und Diebstahl einher. Die Ausweitung der Zahl von Beamten, die einander überprüften, reduzierte zwar den Verlust durch Diebstahl, erhöhte jedoch die Gesamtkosten, die der Pharao tragen musste. Dezentrale Autorität, welche unter bestimmten Umständen die Produktion optimierte, führte auch zu stärkeren lokalen Mächten, die manchmal zu vollwertigen Herausforderern um die Kontrolle der Dynastie heranwuchsen. Selbst orientalische Despoten waren keineswegs frei, zu tun und zu lassen, was sie wollten. Sie hatten keine Wahl, als das Gleichgewicht der reinen Macht zu erkennen, wie sie es vorfanden.

Obwohl alle, einschließlich der Reichen, einer willkürlichen Enteignung unterlagen, konnten einige eigenes Eigentum ansammeln. Damals wie heute widmete der Staat einen Großteil seiner Einnahmen den öffentlichen Arbeiten. Projekte wie Bewässerungssysteme, religiöse Denkmäler und Krypten für die Könige boten Architekten und Handwerkern Einkommensmöglichkeiten. Einige gut situierte Individuen konnten beträchtliches privates Eigentum ansammeln. Tatsächlich zeichnet ein großer Teil der überlebenden Keilschrifttafeln aus Sumer, einer frühen mesopotamischen Zivilisation, verschiedene Handelsakte auf, von denen die meisten den Übergang von Eigentumstiteln beinhalteten.

Es gab privates Eigentum in den frühen landwirtschaftlichen Gesellschaften, jedoch selten am unteren Ende der sozialen Pyramide. Die übergroße Mehrheit der Bevölkerung bestand aus Bauern, die zu arm waren, um viel Reichtum anzuhäufen. Tatsächlich waren, bis auf wenige Ausnahmen, die meisten Bauern bis in die Neuzeit hinein so arm, dass sie ständig Gefahr liefen, an Hunger zu sterben, sobald Trockenheit, Überschwemmungen oder Schädlinge die Ernteerträge reduzierten. Daher waren die Bauern gezwungen, ihre Angelegenheiten so zu organisieren, dass sie die Risiken in schlechten Jahren minimierten. In der weitläufigen und verarmten Bevölkerungsschicht galt eine primitivere Organisation des Eigentums. Sie erhöhte die Überlebenschance auf Kosten der Einschränkung der Möglichkeit, Kapital anzuhäufen und im Wirtschaftssystem aufzusteigen.

### Bauernversicherung

Die Form, die dieser Handel annahm, war die Annahme dessen, was Anthropologen und Sozialhistoriker als das „geschlossene Dorf“ beschreiben. Fast jede bäuerliche Gesellschaft in vorindustriellen Zeiten hatte als Hauptform der Wirtschaftsorganisation das „geschlossene Dorf“. Im Unterschied zu moderneren Formen der Wirtschaftsorganisation, in denen Individuen dazu neigen, mit vielen Käufern und Verkäufern auf einem offenen Markt zu handeln, schlossen sich die Haushalte des geschlossenen Dorfes zusammen, um wie eine informelle Körperschaft oder eine große Familie zu agieren, nicht auf einem offenen Markt, sondern in einem geschlossenen System, in dem alle wirtschaftlichen Transaktionen des Dorfes dazu neigten, mit einem einzelnen Monopolisten getätigt zu werden - dem örtlichen Grundbesitzer oder seinen Beauftragten unter den Dorfhäuptlingen. Das Dorf als Ganzes schloss mit dem Grundherrn einen Vertrag über einen hohen Anteil an der Ernte und nicht über einen festen Pachtzins ab, in der Regel gegen Sachleistungen. Die prozentuale Miete bedeutete, dass der Pächter einen Teil des Risikos einer schlechten Ernte übernahm. Natürlich nahm der Pächter auch den größeren Teil des potenziellen Gewinns. Typischerweise stellten Vermieter auch das Saatgut bereit.

Diese Praxis minimierte auch die Gefahr von Hungersnöten. Sie verlangte, dass der Gutsherr, anstatt des Bauern, einen überproportionalen Anteil seiner Ernte sparte. Da die landwirtschaftlichen Erträge in der Vergangenheit in vielen Gebieten erschreckend niedrig waren, mussten oft zwei ausgesäte Samen für drei geerntete gepflanzt werden. Unter solchen Bedingungen würde eine schlechte Ernte Hungersnot bedeuten. Die Bauern bevorzugten vernünftigerweise eine Regelung, die den Gutsherren dazu verpflichtete, in ihr Überleben zu investieren. Auf Kosten des Kaufs zu monopolisierten Preisen, des günstigen Verkaufs und der Bereitstellung von Naturallohn erhöhten die Bauern ihre Überlebenschancen. Ein ähnlicher Impuls führte bei den typischen Bauern in einer geschlossenen Dorfwirtschaft dazu, auf die Sicherheit des freien Eigentums zu verzichten. Indem sie sich dem Dorfoberhaupt auslieferte, verbesserte eine Bauernfamilie ihre Chancen, von der regelmäßigen Neuverteilung der Felder zu profitieren. Nicht selten nahm das Dorfoberhaupt die besten Felder für sich und seine Begünstigten. Aber das war ein Risiko, das die Bauern in Kauf nehmen mussten, um die Überlebensversicherung zu genießen, die das durcheinandergebrachte dörfliche Eigentum der Felder bot. In Zeiten, in denen die Ernteerträge erbärmlich niedrig waren, könnte der Unterschied in den Wachstumsbedingungen von Feldern, die nur hundert Meter voneinander entfernt waren, zwischen Hunger und Überleben entscheiden. Bauern entschieden sich häufig für die Regelung, die das Risiko minimierte, auch auf Kosten der Aufgabe jeglicher Hoffnung auf gesteigerten Wohlstand.

Im Allgemeinen war risikoscheues Verhalten bei allen Gruppen, die am Rande des Überlebens agierten, weit verbreitet. Die bloße Herausforderung des Überlebens in vorindustriellen Gesellschaften beschränkte stets das Verhalten der Armen. Ein interessantes Merkmal dieser Risikoaversion, das wir in *The Great Reckoning* untersuchen, ist, dass sie die Bandbreite friedlicher wirtschaftlicher Verhaltensweisen einschränkte, die den Einzelnen gesellschaftlich gestattet waren. Tabus und soziale Beschränkungen limitierten Experimente und innovatives Verhalten, selbst zu den offensichtlichen Kosten, potenziell vorteilhafte Veränderungen in festgelegten Vorgehensweisen aufzugeben. Dies war eine rationale Reaktion auf die Tatsache, dass Experimente die Variabilität der Ergebnisse vermehren.

Größere Variabilität bedeutet nicht nur potenziell größere Gewinne, sondern - was für diejenigen, die am Rande des Überlebens stehen, noch bedrohlicher ist - potenziell ruinöse Verluste. Ein großer Teil der kulturellen Energie armer Bauerngesellschaften wurde immer darauf verwendet, die Experimentierfreudigkeit zu unterdrücken. Diese Unterdrückung war gewissermaßen ihr Ersatz für Versicherungspolicen. Hätten sie Versicherungen oder ausreichende Ersparnisse, um ihre Experimente selbst zu versichern, wären solch starke soziale Tabus nicht notwendig, um das Überleben zu gewährleisten.

Kulturen sind keine Geschmacksfragen, sondern Anpassungssysteme an spezifische Umstände, die in anderen Kontexten irrelevant oder sogar kontraproduktiv sein können. Menschen leben in einer Vielzahl von Lebensräumen. Die große Anzahl potenzieller Nischen, in denen wir leben, erfordert Verhaltensvariationen, die zu komplex sind, um durch Instinkt bestimmt zu werden. Daher ist das Verhalten kulturell programmiert. Für die überwiegende Mehrheit in vielen landwirtschaftlichen Gesellschaften hat die Kultur sie auf das Überleben programmiert, jedoch nur auf ein Überleben in einer Umgebung, in der der Luxus der Teilnahme an offenen Märkten anderen vorbehalten war.

Persönliche Fähigkeiten und persönliche Entscheidungen - das individuelle „Streben nach Glück“ im modernen Sinne - wurden durch Tabus und soziale Einschränkungen unterdrückt, die unter den Armen immer am stärksten waren. Solche Einschränkungen wurden nur unter großen Schwierigkeiten in Gesellschaften mit begrenzter Produktivität überwunden. Dort wo die landwirtschaftliche Produktivität höher war, wie zum Beispiel im antiken Griechenland, traten kleinere megapolitische Revolutionen auf. Besitz nahm modernere Formen an. „Allod“, oder freies Eigen, entstand. Land neigte dazu, gegen eine feste Gebühr verpachtet zu werden und der Pächter trug das wirtschaftliche Risiko sowie einen höheren Anteil am Gewinn, wenn die Ernte gut war. Höhere Ersparnisse ermöglichen eine Selbstversicherung für risikoreicheres Verhalten. Unter solchen Bedingungen konnten freie Bauern über den Stand der Bauernschaft hinaussteigen und manchmal sogar unabhängigen Reichtum ansammeln.

Die Tendenz, dass sich marktähnliche Eigentumsrechte und Beziehungen nahe der Spitze einer wirtschaftlichen Hierarchie oder in selteneren Fällen in der gesamten Wirtschaft entwickeln, während Gesellschaften aus der Armut hervorgehen, ist ein wichtiges Merkmal der sozialen Organisation. Es ist genauso wichtig zu bemerken, dass die gängigste Organisation der Agrargesellschaft in der Geschichte grundsätzlich feudal war, mit Marktbeziehungen an der Spitze und einem geschlossenen Dorfsystem am unteren Ende. Die große Mehrheit der Bauern war fast in allen vormodernen Agrargesellschaften an das Land gebunden. Solange die landwirtschaftliche Produktivität niedrig blieb, oder höhere Produktivität vom Zugang zu zentralisierten hydraulischen Systemen abhing, blieben Freiheit und Eigentumsrechte der einzelnen Bauern am unteren Ende minimal. Unter solchen Bedingungen herrschten feudale Formen von Eigentum. Das Land wurde durch Pachtverträge und nicht durch Freilanderwerb gehalten. In der Regel waren Verkaufs-, Schenkungs- und Erbschaftsrechte eingeschränkt.

Feudalismus in seinen verschiedenen Formen war nicht nur eine Reaktion auf die ständig vorhandene Gefahr von räuberischer Gewalt. Es war auch eine Reaktion auf erschreckend niedrige Produktivitätsraten. Die beiden Aspekte gingen in landwirtschaftlichen Gesellschaften häufig Hand in Hand. Das eine trug häufig zum anderen bei. Wenn die öffentliche Autorität zusammenbrach, neigten Eigentumsrechte und Wohlstand dazu, entsprechend zurückzugehen. Ein Zusammenbruch der Produktivität untergrub auch oft die Autorität. Obwohl nicht jede Dürre oder klimatische Veränderung zum Zusammenbruch der öffentlichen Autorität führte, geschah dies doch in vielen Fällen.

## DIE FEUDALE REVOLUTION DES JAHRES 1000

So war es auch bei der Transformation um das Jahr 1000, die die feudale Revolution auslöste.[^64] Zu dieser Zeit unterschieden sich die megapolitischen und wirtschaftlichen Bedingungen in wichtigen Punkten von denen, die wir normalerweise mit dem Mittelalter assoziieren. In den ersten Jahrhunderten nach dem Fall Roms schrumpfte die Wirtschaft Westeuropas. Die germanischen Königreiche, die in den Gebieten des ehemaligen Römischen Reiches Wurzeln schlugen, übernahmen viele Funktionen des römischen Staates, jedoch auf einem viel weniger ambitionierten Niveau. Die Infrastruktur wurde mehr oder weniger vernachlässigt. Mit den Jahrhunderten verfielen Brücken und Aquädukte und wurden unbrauchbar. Römische Münzen wurden zwar noch verwendet, verschwanden aber praktisch aus dem Umlauf. Grundstücksmärkte, die in der Römerzeit geblüht hatten, trockneten mehr oder weniger aus. Städte, die Zentren der römischen Verwaltung gewesen waren, verschwanden praktisch zusammen mit der Besteuerungskraft des Staates. Und so verschwand fast jedes andere Anhängsel der Zivilisation.

Das sogenannte „Dunkle Zeitalter“ wurde aus gutem Grund so genannt. Die Alphabetisierungsrate sank so sehr, dass jeder, der lesen und schreiben konnte, nahezu Straffreiheit für fast jedes Verbrechen erwarten konnte, einschließlich Mord. Künstlerische, wissenschaftliche und technische Fähigkeiten, die zu römischen Zeiten hochentwickelt waren, verschwanden. Von Straßenbau bis hin zu Veredelungstechniken für Reben und Obstbäume stellte Westeuropa viele Techniken ein, die einst gut bekannt waren und auf hohem Niveau praktiziert wurden. Selbst so alte Gerätschaften wie die Töpferscheiben verschwanden an vielen Orten. Bergbaubetriebe wurden zurückgefahren. Die Metallurgie ging zurück. Bewässerungsanlagen im Mittelmeerraum verfielen aufgrund von fehlender Instandhaltung.[^65] Wie der Historiker Georges Duby feststellte, „war Europa am Ende des sechsten Jahrhunderts ein zutiefst unzivilisierter Ort.“ [^66] Obwohl es eine kurze Renaissance der zentralen Autorität unter der Herrschaft von Karl dem Großen um das Jahr 800 gab, zerfiel alles bald wieder nach seinem Tod.

Ein überraschender Nebeneffekt dieser trostlosen Landschaft war die Tatsache, dass der Zusammenbruch des römischen Staates wahrscheinlich über mehrere Jahrhunderte den Lebensstandard der Kleinbauern erhöhte. Die germanischen Königreiche, die während des Dunklen Zeitalters Westeuropa dominierten, integrierten einige der relativ entspannten sozialen Merkmale, die ihren Stammesvorfahren gemeinsam waren, wie zum Beispiel die rechtliche Gleichstellung der Freibauern. Infolgedessen waren die Kleinbauern im dunklen Zeitalter weitaus freier als sie es in den feudalistischen Jahrhunderten sein sollten. Daraus können wir auch schließen, dass sie wohlhabender waren. Wie wir weiter oben bei der Untersuchung der Logik von Eigentumsformen unter verschiedenen Produktivitätsbedingungen analysiert haben, ging Eigentum in freier Haltung historisch gesehen Hand in Hand mit dem relativen Wohlstand von Kleinbauern. Die geschlossenen Dorf- und Feudalformen des Eigentums tendierten dazu, dort aufzutreten, wo die Fähigkeit der Kleinbauern, ihren Lebensunterhalt zu verdienen, zweifelhafter war.

Sicherlich kostete der Quasi-Zusammenbruch des Handels während des Dunklen Zeitalters den Kleinbauern die Vorteile von Handel und größeren Märkten. Der Niedergang der Städte untergrub die Geldwirtschaft, aber es bedeutete auch, dass die ländliche Bevölkerung nicht mehr aufgerufen war, die erdrückende Last der Bürokratie zu unterstützen. Wie Guy Bois schrieb, war die römische Stadt eine parasitäre Gemeinschaft, kein Zentrum der Produktion: „Im römischen Zeitalter war die dominante Funktion einer Stadt politischer Art. Sie lebte hauptsächlich von den Einnahmen, die sie durch die Landsteuer aus ihrer Umgebung abzweigten. Die Stadt selbst produzierte wenig oder nichts zum Wohl der umliegenden Landschaft.“ [^67] Der Zusammenbruch der römischen Autorität befreite die Landwirte im Wesentlichen von Steuern, die „zwischen einem Viertel und einem Drittel des Bruttoertrages des Landes absaugten, ohne dabei die verschiedenen Eintreibungen zu berücksichtigen, die kleine und mittlere Landbesitzer erlitten.“ [^68] Die Steuern waren so belastend, dass sie manchmal durch Hinrichtung durchgesetzt wurden und das Verlassen der Eigentümer ihrer eigenen Grundstücke (Deserti agri) weit verbreitet war. Die Barbaren ließen diese Steuern barmherzig verfallen.

### Deserti agri

Die von einer Regierung verursachten Lasten wurden durch die barbarischen Eroberungen so stark reduziert, dass eine Möglichkeit geschaffen wurde, dass die Armen Grundbesitz erwerben und behalten konnten. Einige der Deserti agri, beziehungsweise verlassenen Bauernhöfe, die von Besitzern aufgrund von Raubsteuern in den letzten Jahren des Römischen Reiches aufgegeben wurden, wurden wieder in die Produktion gebracht. Trotz der rauen Umstände der Zeit und der Tatsache, dass die Erträge nach heutigen Maßstäben lächerlich niedrig waren, waren die dunklen Jahrhunderte eine Zeit relativer Prosperität für Europas Kleinbauern. Tatsächlich waren sie in einer stärkeren Position, als sie es bis zur modernen Epoche wieder sein würden. Einerseits waren weniger Hände verfügbar, um das fruchtbare Land zu bestellen, da große Teile davon aus dem Anbau genommen worden waren. Pest, Kriege und die Flucht von Besitzern vor dem zusammenbrechenden Römischen Reich hatten Gebiete, die zuvor unter Anbau standen, erheblich entvölkert. Ein weiterer Vorteil, den Kleinbauern im Dunklen Zeitalter genossen, entstand aus der Einführung neuer Landwirtschaftstechnologie im sechsten Jahrhundert: dem schweren Pflug, der oft auf Rädern montiert wurde. In Kombination mit einem verbesserten Geschirr, das es den Bauern erlaubte, mehrere Ochsen einzusetzen, machte die neue Technologie das Roden von Waldland in Nordeuropa wesentlich einfacher.[^69]

Unter solchen Bedingungen schrumpfte der Markt für Landwirtschaftsflächen fast bis zur Unkenntlichkeit. Neues Land für den Anbau konnte einfach durch Abholzung gewonnen und ein Teil jeder neuen Parzelle mit den zuständigen örtlichen Behörden geteilt werden. Dieser Prozess, bekannt als Rodung, ermöglichte nach dem Fall Roms jahrhundertelang ein bequemes Bevölkerungswachstum. Mit den wärmeren Temperaturen im achten Jahrhundert wurde die Landwirtschaft in den dünn besiedelten nördlichen Regionen produktiver und das Roden besonders attraktiv.

Die Anführer der germanischen Stämme, die ehemalige römische Gebiete erobert hatten, hatten sich als Großgrundbesitzer etabliert. Der Großteil der restlichen Bevölkerung bewirtschaftete kleine Flächen, allerdings unter ganz anderen Bedingungen als später im Feudalismus. Die wohlhabenderen Landbesitzer oder Meister stellten etwa 7-10 Prozent der Bevölkerung. Es war wohl so, dass vor dem Jahr 1000 zwei Drittel der Dorfbewohner in einem typischen Gebiet Frankreichs Grundbesitzer waren.[^70] Sie besaßen etwa die Hälfte des gesamten kultivierten Landes.[^71] Leibeigene gab es nur wenige. Coloni oder Pachtbauern machten nicht mehr als 5 Prozent der Bevölkerung aus. Die Sklaverei gab es immer noch, aber in viel kleinerem Maßstab als in der Römerzeit.

Die germanischen Königreiche in der Nachfolge Roms wurden militärisch von allen freien Männern verteidigt, die dem Aufruf des örtlichen Vertreters des Königs, des Grafen, nachkamen, um Waffen zu tragen. Selbst von „kleinen und mittleren Grundbesitzern“ wurde erwartet, dass sie sich zusammenschließen und einen aus ihrer Mitte zum Kampf in der Infanterie senden.[^72] Im Edikt von Pitres befahl Karl der Kahlköpfige allen, die es sich leisten konnten, beritten zur Schlacht zu erscheinen. Papst Gregor II. hatte ein Jahrhundert zuvor versucht, dieses militärische Gebot voranzutreiben, indem er 732 den menschlichen Verzehr von Pferdefleisch verbot.[^73] Aber es gab bislang wenig Unterschied im Status oder Recht zwischen der Infanterie der Freigrundbesitzer und der Kavallerie. Alle freien Männer nahmen an lokalen Gerichtsversammlungen teil und konnten den Grafen, ein Amt, das seit der spätrömischen Zeit existierte, um die Beilegung von Streitigkeiten bitten. Es gab keinen Adel im eigentlichen Sinne.

> \“Ein soziales Phänomen, das als Massenphänomen plötzlich neu am Horizont in den 980ern auftauchte, war der soziale Abwärtstrend. Seine ersten Opfer waren die kleinen Allod-Inhaber.\“ [^74] - Guy Bois

Im Verlauf des Dunklen Zeitalters kam es jedoch zu einigen Entwicklungen, die die Beziehungen, die die Unabhängigkeit der freien Bauern und Grundeigentümer in den germanischen Königreichen, die nach dem Fall Roms an die Macht kamen, gewährleistet hatten, destabilisierten:

1.  Die Bevölkerung erholte sich allmählich, was zu einem größeren Druck auf die Landnutzung führte. Über mehrere Jahrhunderte hinweg wurde viel von dem fruchtbarsten, noch unbeanspruchten Land, insbesondere in Nordeuropa, in Produktion gebracht. Die steigende Bevölkerungszahl der Bauern im Verhältnis zur verfügbaren Landmenge verringerte den Wert der einzelnen Landarbeiter. Die meisten Grundeigentumstitel wurden durch Erbschaft in immer kleinere Parzellen zerlegt. Während des Dunklen Zeitalters neigten die Kinder dazu, gleichberechtigt an den Nachlässen ihrer Eltern teilzuhaben. Die Fragmentierung des Besitzes zu Zeiten steigender Bevölkerungszahlen führte dazu, dass Land wieder eine kostbare Ressource wurde, und führte zur Wiederbelebung aktiver Landmärkte um die Mitte des zehnten Jahrhunderts.

2.  In den letzten Jahrzehnten des zehnten Jahrhunderts wurde das Wetter plötzlich kälter, mit verheerenden Auswirkungen auf die landwirtschaftliche Produktion. Drei aufeinanderfolgende Missernten führten von 982 bis 984 zu einer schweren Hungersnot. Eine weitere Hungersnot folgte nach einer weiteren Missernte im Jahr 994.[^75] Dann verschlimmerte sich das Problem der sinkenden Ernteerträge im Jahr 997 durch eine Pestepidemie, die besonders kleine Familienbetriebe hart traf, da diesen die Ressourcen fehlten, um die Arbeitskraft verlorener Familienmitglieder zu ersetzen. Diese geballten Misserfolge und Katastrophen trieben die freien Bauern zunächst in die Verschuldung. Als sich die Erträge nicht erholten, konnten sie ihre Hypotheken nicht mehr bedienen.

3.  Die Machtverhältnisse wurden zunehmend durch die wachsende Bedeutung der schweren Kavallerie destabilisiert. Die mittelalterliche Historikerin Frances Gies beschreibt die Transformation des gepanzerten Kavalleristen zum mittelalterlichen Ritter:

> Ursprünglich war der Ritter eine Persönlichkeit von mittlerem Status, die durch sein teures Pferd und seine Rüstung emporgehoben wurde und langsam seine Position in der Gesellschaft verbesserte, bis er Teil des Adels wurde. Obwohl die Ritter die niedrigste Rangordnung der Oberschicht bildeten, erwarb die Ritterschaft einen einzigartigen Ruf, der die Erhebung in den Ritterstand zu einer vom Hochadel und sogar vom Königtum begehrten Ehre machte. Dieser Ruf war hauptsächlich das Produkt der Politik der Kirche, die Ritterschaft zu christianisieren, indem sie die Zeremonie des Ritterschlags heiligte und einen Verhaltenskodex unterstützte, der als Rittertum bekannt ist - ein Kodex, der vielleicht öfter verletzt als geehrt wurde, aber einen unbestreitbaren Einfluss auf das Denken und Verhalten der Nachwelt ausübte.[^76]

Wie wir in *The Great Reckoning* erzählt haben, hat die Erfindung des Steigbügels dem bewaffneten Ritter zu Pferd eine bemerkenswerte Angriffsfähigkeit verliehen. Er konnte nun mit voller Geschwindigkeit angreifen und wurde beim Aufprall seiner Lanze auf ein Ziel nicht aus dem Sattel geworfen. Der militärische Wert der schweren Kavallerie wurde durch eine asiatische Erfindung, dem genagelten Hufeisen, weiter erhöht, das im zehnten Jahrhundert nach Westeuropa vordrang. Dies verbesserte die Strapazierfähigkeit des Pferdes auf der Straße zusätzlich.[^77] Auch der Kontursattel, der den Umgang mit schweren Waffen erleichterte, der Sporn und das Kandarengebiss, mit dem ein Reiter das Pferd mit einer Hand lenken konnte während er kämpfte, trugen zur erhöhten Wirksamkeit des bewaffneten Ritters bei.[^78] Zusammen haben diese augenscheinlich geringen technologischen Innovationen die militärische Bedeutung der Kleinbauern stark abgewertet, die es sich nicht leisten konnten, Kriegspferde zu halten und sich zu bewaffnen. Die kostengünstigeren der speziell für den Krieg gezüchteten Pferde, die großen Streitrosse, genannt Destrier, waren vier Ochsen oder vierzig Schafe wert. Die teureren Kriegspferde kosteten zehn Ochsen oder hundert Schafe. Rüstungen kosteten ebenfalls einen Betrag, den sich kein Kleinbauer leisten konnte, vergleichbar mit einem Preis von sechzig Schafen.[^79]

4.  Die Tatsache, dass das kalte Wetter, Missernten, Hungersnöte und Seuchen im Vorfeld des Jahres 1000 auftraten, spielte ebenfalls eine Rolle für das Verhalten vieler Menschen, die davon überzeugt waren, dass das Ende der Welt oder die Wiederkunft nahe bevorstanden. Fromme oder verängstigte Groß- und Kleingrundbesitzer schenkten ihr Land der Kirche, um sich auf die Apokalypse vorzubereiten.

### „Nur ein Armer verkauft Land“

Die instabilen Bedingungen des späten zehnten Jahrhunderts ebneten den Weg für die feudale Revolution. Häufige Missernten und Katastrophen ließen die freien Kleinbauern in Schulden versinken. Als sich die Ernteerträge nicht erholten, standen die Freibauern vor einer verzweifelten Situation. Märkte üben immer den größten Druck auf die schwächsten Teilnehmer aus. Tatsächlich ist das ein Teil ihrer Tugend. Sie fördern die Effizienz, indem sie Vermögenswerte aus schwachen Händen entfernen. Aber im Europa des späten zehnten Jahrhunderts war subsistenzbasierte Landwirtschaft praktisch die einzige Beschäftigung. Familien, die ihr Land verloren, verloren ihre einzige Überlebensmöglichkeit. Angesichts dieser unappetitlichen Aussicht, entschieden viele oder die meisten der Grundbesitzer während der Feudalrevolution, ihre Felder wegzugeben. In den Worten von Guy Bois: „Der einzige sichere Weg für einen Bauern, das Land, das er bearbeitete, zu behalten, war es, das Eigentum daran der Kirche zu überlassen, damit er seinen Nutzen daran behalten konnte.“ [^80] Andere gaben einen Teil oder all ihr Land an wohlhabendere Bauern ab, denen sie vertrauten, entweder freundliche Nachbarn oder Verwandte.

Diese Eigentumsübergaben wurden unter der Bedingung getätigt, dass der Bauer, seine Familie und seine Nachkommen auf den Feldern zum Arbeiten blieben. Die armen Bauern genossen auch die gegenseitige Unterstützung der mächtigeren Besitzer, nun der „Adligen“, die sich Pferde und Rüstungen leisten konnten und so die vergrößerten Ländereien schützten. Ein solches Angebot kann aus Sicht des neuen Leibeigenen als Mittelweg zwischen fortlaufendem wirtschaftlichem Besitz und Zwangsvollstreckung angesehen werden. Meistens war es ein Angebot, das er nicht ablehnen konnte.

Der Produktivitätsrückgang brachte die armen Bauern nicht nur in eine verzweifelte wirtschaftliche Lage; er löste auch einen Anstieg der räuberischen Gewalt aus, der die Sicherheit des Eigentums untergrub. Diejenigen, die nicht über die Mittel verfügten, um sich einen Teil der verfügbaren und unzureichenden Versorgung mit Pferden und Futter zu sichern, sahen sich und ihren Besitz plötzlich nicht mehr in Sicherheit. Um ihr Dilemma in heutigen Begriffen auszudrücken, wäre es so, als würden Sie gezwungen, sich heute mit einer neuen Art von Waffe auszustatten, aber die Kosten dafür wären 100.000 Dollar. Wenn Sie diesen Preis nicht bezahlen können, wären Sie der Gnade derjenigen ausgeliefert, die es können.

Innerhalb weniger Jahre brach die Fähigkeit des Königs und der Gerichte, Ordnung durchzusetzen, zusammen.[^81] Jeder mit Rüstung und Pferd konnte nun sein eigenes Gesetz werden. Das Ergebnis war eine spätmittelalterliche Version von Blade Runner, eine Auseinandersetzung und Plünderung, gegen die die rechtmäßigen Behörden machtlos waren. Plünderungen und Angriffe durch bewaffnete Ritter störten das Landleben. Es ist jedoch keineswegs offensichtlich, dass alle Opfer dieser Plünderungen die Armen waren. Im Gegenteil, die älteren, körperlich schwächeren oder schlecht vorbereiteten unter den größeren Landbesitzern stellten attraktivere Ziele dar. Sie hatten mehr zum Stehlen.

Es war kein Zufall, dass dies gerade in dem Moment geschah, als durch kälteres Wetter, Hungersnöte und Pest ein knappes Angebot an Ressourcen entstand. Die megapolitischen Bedingungen, die den Zusammenbruch der Autorität begünstigten, hatten schon einige Zeit bestanden. Ihr Potenzial, die Machtverhältnisse in der Gesellschaft zu verändern, wurde jedoch erst realisiert, als eine Krise ausgelöst wurde. Missernten und Hungersnöte scheinen genau das getan zu haben. Obwohl die genaue Abfolge der Ereignisse schwer zu rekonstruieren ist, scheint es so, dass das Plündern zumindest teilweise durch eine verzweifelte Lage ausgelöst wurde. Einmal entfesselt, wurde offensichtlich, dass niemand die Kraft mobilisieren konnte, um die Gewalt zu stoppen. Die überwiegende Mehrheit der schlecht bewaffneten Bauern konnte sicherlich wenig tun. Selbst Dutzende von Bauern zu Fuß wären von einem einzigen bewaffneten Ritter zu Pferd übertroffen worden. Die Freibauern, ebenso wie die bestehenden Autoritäten, die Könige mit ihren Grafen, waren machtlos, um zu verhindern, dass lokales Land von bewaffneten Kriegern beschlagnahmt wurde.

### „Der Friede Gottes“

In diesen verzweifelten Bedingungen half die Kirche, den Feudalismus zu starten, durch ihre Bemühungen, einen Waffenstillstand auf dem gewalttätigen Land zu verhandeln. Der Historiker Guy Bois beschrieb die Situation auf diese Weise: „Die Ohnmacht der politischen Behörden war so groß, dass die Kirche einsprang, um den Versuch zur Wiederherstellung der Ordnung zu unterstützen, die in einer Bewegung als ‚Der Friede Gottes' bekannt wurde. ‚Friedensräte' verhängten eine Reihe von Verboten, die mit Bannflüchen sanktioniert wurden; große ‚Friedensversammlungen' nahmen die Eide der Krieger entgegen. Die Bewegung hatte ihren Ursprung im Süden Frankreichs (Rat von Charroux im Jahr 989, Rat von Narbonne im Jahr 990), bevor sie sich allmählich ausbreitete\...“ [^82]

Der Kompromiss, den die Kirche einging, beinhaltete die Anerkennung der Oberherrschaft bewaffneter Ritter in lokalen Gemeinschaften im Austausch gegen ein Ende oder eine Mäßigung der Gewalt und des Plünderns. Grundbuchtitel, die nach der Welle der Gewalt im späten zehnten Jahrhundert plötzlich verfasst wurden, trugen plötzlich den Titel „nobilis“ oder „miles“ als Zeichen der Herrschaft. Der Adel als eine separate Sphäre wurde durch die feudale Revolution geschaffen. Eigentumshandel, der ein paar Jahre zuvor den gleichen Personen zugeordnet war, hatte eine solche Unterscheidung nicht aufgelistet.[^83]

Angesichts der sinkenden Produktivität und der wirtschaftlichen Unsicherheit der Kleinbauern führte die megapolitische Macht der bewaffneten Ritter unweigerlich zu Eigentumsbesitz durch feudale Pacht. Bis zum Ende des ersten Viertels des elften Jahrhunderts waren die freien Bauern weitgehend verschwunden. Ihre freien Ländereien betrugen nur noch einen Bruchteil ihrer früheren Größe und wurden nun nur noch in Teilzeit bewirtschaftet. Die kleinen Bauern oder ihre Nachkommen waren Leibeigene, die den Großteil ihrer Zeit damit verbrachten, auf den Anwesen der feudalen und kirchlichen Herren zu arbeiten.

Das Zerfallen der Ordnung, die die feudale Revolution begleitete, führte zu Anpassungen im Verhalten, die den Feudalismus stärkten. Darunter ein Anstieg im Burgenbau. Burgen waren im Gefolge von Wikingerüberfällen im 9. Jahrhundert erstmals als primitive hölzerne Strukturen in Nordwesteuropa aufgetaucht. Ursprünglich waren sie Kommandozentren für karolingische Beamte, nach der feudalen Revolution wurden sie jedoch zu Erbbesitz. Diese frühen Festungen waren weit primitiver als sie später werden würden, aber sie waren dennoch schwer anzugreifen. Einmal errichtet, konnten Burgen nur mit größter Mühe niedergebrannt werden. Mit der Ausbreitung der Burgen auf dem Land wurde es immer unwahrscheinlicher, dass der König oder seine Grafen die lokale Vorherrschaft der Herren wirksam angreifen konnten.

### Beiträge der Kirche zur Produktivität

Feudalismus war die Reaktion der Agrargesellschaft auf den Zusammenbruch der Ordnung in Zeiten niedriger Produktivität. Während der frühen Stadien des Feudalismus spielte die Kirche eine wichtige und wirtschaftlich produktive Rolle. Zu den Beiträgen der Kirche gehörten:

1.  In einem Umfeld, in dem die militärische Macht dezentralisiert war, war die Kirche in einzigartiger Weise in der Lage, den Frieden aufrechtzuerhalten und Ordnungsregeln zu entwickeln, die über zersplitterte, lokale Souveränitäten hinausgingen. Dies ist eine Aufgabe, die keine weltliche Macht zu erfüllen vermochte. Die Beobachtungen der großen religiösen Autorität A. R. Radcliffe-Brown sind hier unmittelbar relevant. Er wies darauf hin, dass „die soziale Funktion einer Religion unabhängig von ihrer Wahrheit oder Falschheit ist.“ Selbst solche, die „absurd und abstoßend sind, wie die einiger wilder Stämme, können wichtige und wirksame Teile der sozialen Maschinerie sein.“ [^84] Dies war bei der Kirche in der Frühphase des Feudalismus sicherlich der Fall. Sie trug dazu bei, Regeln zu schaffen, wie es nur eine Religion konnte, die es den Menschen ermöglichte, Anreizfallen und Verhaltensdilemmata zu überwinden. Einige dieser Dilemmas waren moralische Dilemmas, die für das gesamte menschliche Leben gelten. Bei anderen handelte es sich um lokale Dilemmata, die nur unter den vorherrschenden megapolitischen Bedingungen auftraten. Der mittelalterlichen Kirche kam bei der Wiederherstellung der Ordnung auf dem Lande in den letzten Jahren des zehnten Jahrhunderts eine besondere Rolle zu. Indem sie den lokalen Behörden religiöse und zeremonielle Unterstützung gewährte, senkte die Kirche die Kosten für die Errichtung zumindest schwacher lokaler Gewaltmonopole. Indem sie auf diese Weise half, Ordnung zu schaffen, trug die Kirche zu den Bedingungen bei, die letztlich zu stabileren Machtkonstellationen führten.

Die Kirche spielte auch eine lange Zeit danach noch eine Rolle bei der Eindämmung der privaten Kriege und Ausschreitungen, die sonst von den weltlichen Behörden nicht in den Griff zu bekommen waren. Die relative Bedeutung der Kirche im Vergleich zu weltlichen Behörden spiegelt sich in der Tatsache wider, dass bis zum elften Jahrhundert die wichtigste administrative Einheit in den meisten Teilen Westeuropas die Pfarrei und nicht länger die alten zivilen Einheiten, der Ager und Pagus (Stadt), die seit der Römerzeit bis ins dunkle Mittelalter fortbestanden hatten, waren.[^85]

2.  Die Kirche war die Hauptquelle für den Erhalt und die Vermittlung technischen Wissens und Informationen. Die Kirche unterstützte Universitäten und bot die minimale Bildung, die die mittelalterliche Gesellschaft genoss. Die Kirche stellte auch einen Mechanismus zum Vervielfältigen von Büchern und Handschriften zur Verfügung, einschließlich fast aller zeitgenössischen Informationen über Landwirtschaft und Tierhaltung. Die Skriptorien der Benediktinerklöster können als eine alternative Technologie zu Druckerpressen verstanden werden, die noch nicht existierten. So kostspielig und ineffizient die Skriptorien auch waren, sie waren praktisch der einzige Mechanismus zur Vervielfältigung und Bewahrung von schriftlichem Wissen in der feudalen Periode.

3.  Teilweise, weil ihre Hofverwalter lesen konnten, leistete die Kirche einen großen Beitrag zur Steigerung der Produktivität der europäischen Landwirtschaft, insbesondere in den frühen Stufen des Feudalismus. Vor dem dreizehnten Jahrhundert konnten fast alle Hofverwalter von Laienherren, die fast alle Analphabeten waren, sich nur durch ein ausgeklügeltes Markierungssystem Notizen machen. Auch wenn sie vielleicht geschickte Landwirte waren, waren sie nicht in der Lage, von Verbesserungen in den Produktionsmethoden zu profitieren, die sie nicht selbst erfinden oder mit eigenen Augen sehen konnten. Die Kirche war daher unerlässlich für die Verbesserung der Qualität von Getreide, Früchten und Zuchtbetrieben. Aufgrund ihres ausgedehnten Besitzes, der sich über den gesamten europäischen Kontinent erstreckte, konnte die Kirche das produktivste Saatgut und den besten Zuchtbestand in Gebiete schicken, in denen die Produktion hinterherhinkte. Der Bedarf an sakramentalem Wein im Norden Europas veranlasste die Mönche, mit robusten Traubensorten zu experimentieren, die in kälteren Klimazonen überleben konnten. Die Kirche half auch auf andere Weise, die Produktivität der mittelalterlichen Landwirtschaft zu erhöhen. Viele der der Kirche während der feudalen Revolution gespendeten wirtschaftlich kleinen Parzellen wurden umgestaltet, um sie leichter bewirtschaften zu können. Die Kirche bot auch zusätzliche Dienstleistungen an, die kleine landwirtschaftliche Gemeinschaften benötigten. In vielen Gebieten mahlten kircheneigene Mühlen Getreide zu Mehl.

4.  Die Kirche übernahm viele Funktionen, die heute von der Regierung ausgeführt werden, einschließlich der Bereitstellung öffentlicher Infrastruktur. Dies war ein Teil der Art und Weise, wie die Kirche dazu beigetragen hat, das zu überwinden, was Wirtschaftswissenschaftler „Die Tragik der Allmende“ in einer Zeit fragmentierter Autorität nennen. Spezifische religiöse Orden der frühmittelalterlichen Kirche widmeten sich angewandten technischen Aufgaben, wie dem Öffnen von Straßen, dem Wiederaufbau gefallener Brücken und der Reparatur verfallener römischer Aquädukte. Sie rodeten auch Land, bauten Dämme und entwässerten Sümpfe. Ein neuer klösterlicher Orden, die Kartäuser, bohrte den ersten „artesischen“ Brunnen in Artois, Frankreich. Mit Hilfe der Schlagbohrtechnik gruben sie ein kleines Loch tief genug, um einen Brunnen zu schaffen, der keine Pumpe benötigte.[^86] Die Zisterzienser übernahmen den Bau und die Wartung von unsicheren Seemauern und Deichen in den Tieflandgebieten Europas. Bauern überschrieben Land an Zisterzienserklöster und mieteten es zurück, während die Mönche die volle Verantwortung für die Instandhaltung und Reparatur übernahmen. Die Zisterzienser waren auch führend bei der Entwicklung wasserbetriebener Maschinen, die für so verbreitete Zwecke wie „Stampfen, Heben, Mahlen und Pressen“ eingesetzt wurden.[^87] Das Kloster von Clairvaux grub einen zwei Meilen langen Kanal vom Fluss Aube aus.[^88] Die Kirche intervenierte auch, um neue Straßen und Brücken zu bauen, wo sich die Bevölkerungszentren außerhalb des Bereichs der alten römischen Garnisonsstraßen verlagert hatten. Bischöfe gewährten Ablässe an lokale Herren, die Flussübergänge bauen oder reparieren und Hospize für Reisende unterhalten würden. Ein Orden von Mönchen, der von St. Benezet gegründet wurde, die Freres Pontifes, oder „Brüder der Brücke“, bauten einige der längsten Brücken, die es damals gab, einschließlich der Pont d\'Avignon, eine massive zwanzigbogige Struktur über die Rhone mit einer kombinierten Kapelle und Mautstelle an einem Ende. Sogar die Londoner Brücke, die bis ins neunzehnte Jahrhundert stand, wurde von einem Kaplan gebaut und teilweise durch einen Beitrag von 1.000 Mark vom päpstlichen Legaten finanziert.[^89]

5.  Die Kirche half auch bei der Entstehung eines komplexeren Marktes. Der Bau von Kathedralen unterscheidet sich beispielsweise in seiner Art von der öffentlichen Infrastruktur, wie Brücken und Aquädukten. Im Prinzip wurden Kirchenstrukturen zumeist nur für religiöse Dienste genutzt und nicht als Durchgangsstraßen für den Handel. Dennoch sollte nicht vergessen werden, dass der Bau von Kirchen und Kathedralen half, Märkte für viele handwerkliche und ingenieurtechnische Fähigkeiten zu schaffen und zu vertiefen. Genauso wie die Militärausgaben des Nationalstaates während des Kalten Krieges unbeabsichtigt zur Entstehung des Internets beitrugen, so führte der Bau der mittelalterlichen Kathedralen zu anderen Auswirkungen, der Inkubation des Handels. Die Kirche war ein Hauptkunde der Bauhandwerke und Handwerkskunst. Kirchliche Käufe von Silber für Abendmahlsdienste, Leuchter und Kunstwerke zur Dekoration von Kirchen halfen, einen Markt für Luxusgüter zu schaffen, der sonst nicht existiert hätte.

In vielerlei Hinsicht half die Kirche dabei, die Heftigkeit der von bewaffneten Rittern während und nach der „feudalen Revolution“ entfesselten Gewalt zu mildern. Vor allem in den frühen Jahrhunderten des Feudalismus trug die Kirche erheblich dazu bei, die Produktivität der Agrarökonomie zu verbessern. Sie war eine essenzielle Institution, perfekt angepasst an die Bedürfnisse der Agrargesellschaft am Ende des Dunklen Zeitalters.

### Verletzlichkeit gegenüber Gewalt

In „dreißig oder vierzig Jahren heftiger Unruhen war die Feudalrevolution des Jahres 1000“ [^90], ebenso wie der Fall Roms fünf Jahrhunderte zuvor, ein einzigartiges Ereignis, verursacht durch ein komplexes Zusammenspiel von Einflüssen. Doch in einer Hinsicht spiegeln der Triumph von bösen Männern und die von ihnen verursachten Unterdrückungen die grundsätzliche Verwundbarkeit der Agrargesellschaft gegenüber Gewalt perfekt wider. Im Gegensatz zur Phase der menschlichen Existenz, in der das Leben vom Sammeln und Jagen geprägt war, führte die Landwirtschaft zu einem Quantensprung in organisierter Gewalt und Unterdrückung.

Dies spiegelte sich schon in den frühesten Zeiten in den kämpferischeren Kulturen der Bauernvölker wider. Die Götter der frühen landwirtschaftlichen Gesellschaften waren Regen- und Flutgötter, deren Funktionen das Interesse dieser Gesellschaften an Faktoren widerspiegelten, die den Ernteertrag bestimmten. Der Bringer von Regen oder Wasser war oft auch der Kriegsgott, den die ersten Könige, die vor allem Kriegsherren waren, anriefen.[^91]

Die enge Verbindung zwischen Landwirtschaft und Kriegsführung spiegelte sich in der religiösen Vorstellungskraft von Menschen wider, deren Leben durch die Innovationen der Agrarrevolution verwandelt wurde. Die Vertreibung aus dem Garten Eden kann als symbolische Darstellung der gesellschaftlichen Transformation von der Nahrungssuche zur Landwirtschaft gesehen werden, von einem freien Leben mit Nahrung, die mit wenig Aufwand aus der Fülle der Natur gepflückt wurde, zu einem Leben mit harter Arbeit.

## DAS VERLORENE PARADIES

Die Landwirtschaft hat die Menschheit auf einen völlig neuen Kurs gebracht. Die ersten Bauern pflanzten tatsächlich die Samen der Zivilisation. Aus ihrer harten Arbeit entstanden Städte, Armeen, Arithmetik, Astronomie, Verliese, Wein und Whisky, das geschriebene Wort, Könige, Sklaverei und Krieg. Trotz aller Dramatik, die die Landwirtschaft dem Leben verleihen sollte, scheint der Abschied von der urzeitlichen Wirtschaft von Anfang an rundweg unbeliebt gewesen zu sein. Zeugnis dafür gibt die Erzählung, die im Buch Genesis erhalten ist, welche die Verstoßung aus dem Paradies erzählt. Die biblische Parabel vom Garten Eden ist eine liebevolle Erinnerung an das bequeme Leben des Sammlers in der Wildnis. Gelehrte deuten darauf hin, dass das Wort „Eden“ aus einem sumerischen Wort für „Wildnis“ abgeleitet zu sein scheint.[^92]

Der Übergang vom freien und spärlich besiedelten Leben in der Wildnis zu einem sesshaften Leben in einem landwirtschaftlichen Dorf war Thema tiefen Bedauerns, das nicht nur in der Bibel zum Ausdruck kam, sondern sich auch in der anhaltenden Verärgerung der Menschheit zeigt, morgens aufzustehen und zur Arbeit zu gehen. Wie Stephen Boyden in „Western Civilization in Biological Perspective“ schrieb, war die neue Art zu leben, die mit der Landwirtschaft einherging, „evodeviant“ [^93]. Vor dem Beginn der Landwirtschaft lebten Tausende von menschlichen Generationen wie Adam im Garten Eden, eingeladen von seinem Schöpfer: „Von jedem Baum des Gartens darfst du einfach essen.“ Jäger und Sammler hatten keine Felder zu pflegen, keine Herde zu hüten, keine Steuern zu zahlen. Wie Landstreicher gingen die Jäger und Sammler, wohin sie wollten, arbeiteten wenig und waren niemandem Rechenschaft schuldig.

Mit der Landwirtschaft begann eine neue Lebensweise, und zwar unter ganz anderen Bedingungen. „Dornen und Disteln lässt sie auch für dich wachsen; und du musst die Pflanzen des Feldes essen; Mit Schweiß auf deinem Gesicht wirst du Brot essen.“ Die Landwirtschaft war harte Arbeit. Die Erinnerung an das Leben vor dem Ackerbau war die eines verlorenen Paradieses.

Viel mehr als sie es sich hätten vorstellen können, haben Bauern neue Bedingungen geschaffen, die die Logik der Gewalt drastisch veränderten. Es ist kein Zufall, dass das Buch Genesis Kain, den ersten Mörder, als „einen Bearbeiter des Bodens“ darstellt. Tatsächlich ist es Teil der unheimlichen prophetischen Kraft der Bibel, dass ihre Geschichte Hirten anvertraut wurde, die sofort verstanden, wie die Landwirtschaft der Gewalt Auftrieb gab. In wenigen Versen fasst die biblische Erzählung Logiken zusammen, die Tausende von Jahren zur Umsetzung brauchten. Die Landwirtschaft war ein Brutkasten für Streitigkeiten. Sie schuf immobilisiertes Kapital in großem Maßstab, steigerte dadurch den Gewinn aus Gewalt und erhöhte dramatisch die Herausforderung, Vermögenswerte zu schützen. Die Landwirtschaft machte sowohl Kriminalität als auch Regierungen zum ersten Mal zu lohnenden Unternehmungen.

[^51]: Boyden, ebenda, S. 4

[^52]: Gregg, ebenda, xv.

[^53]: Boyden, ebenda, S. 62

[^54]: Ebenda, S. 67

[^55]: Ebenda

[^56]: Zitiert in E. J. P Veale, *Advance to Barbarism: The Development of Total Warfore* (New York: Devin-Adair, 1968), S. 37

[^57]: R. Paul Shaw und Yuwa Wong, *Genetic Seeds of Warfare: Evolution, Nationalism and Patriotism* (Boston: Unwin Hyman, 1989), S. 4

[^58]: Siehe Carleton S. Coon, *The Hunting Peoples* (New York: Nick Lyons Books, 1971), S. 275

[^59]: Gregg, ebenda, S. 23

[^62]: Für weitere Details über die Kafire, siehe Schuyler Jones, *Men of Influence in Nuristan* (London: Seminar Press, 1974).

[^64]: Siehe Bois, ebenda.

[^65]: Siehe Frances und Joseph Gies, *Cathedral, Forge, und Waterwheel: Technology and Invention in the Middle Ages* (New York: HarperCollins, 1994), S. 40.

[^66]: Zitiert ebenda, S. 42.

[^67]: Bois, ebenda, S. 78.

[^68]: Ebenda, S. 118.

[^69]: Gies, ebenda, S. 45.

[^70]: Bois, ebenda, S. 116.

[^71]: Ebenda, S. 26.

[^72]: Ebenda, S. 64.

[^73]: Gies, ebenda, S. 47.

[^74]: Bois, ebenda, S. 52.

[^75]: Ebenda, S. 150.

[^76]: Gies, ebenda, S. 2.

[^77]: Ebenda, S. 46.

[^78]: Ebenda, S. 56f.

[^79]: Ebenda, S. 58.

[^80]: Bois, ebenda, S. 87.

[^81]: Ebenda. Auch wenn die genaue Abfolge der Ereignisse während der feudalen Revolution aufgrund der spärlichen Aufzeichnungen schwer zu rekonstruieren ist, erscheint uns die von Guy Bois vorgeschlagene These in ihren Grundzügen als wahrscheinlich richtig. Sie ist nicht nur an sich plausibel, sondern ergibt auch aus den ansonsten anomalen Fakten einen Sinn und passt außerdem zu unseren Theorien.

[^82]: Ebenda, S. 136.

[^83]: Ebenda, S. 57ff und passim.

[^84]: A. R. Radcliffe-Brown, Religion and Society,\“ in *Structure and Function in Primitive Society* (London: Cohen & West, 1952), S. 153ff.

[^85]: Bois, ebenda, S. 36.

[^86]: Gies, ebenda, S. 112.

[^87]: Ebenda, S. 114.

[^88]: Ebenda, S. 117.

[^89]: Die Details über Brücken und Infrastruktur stammt hauptsächlich aus ebenda, S. 148ff.

[^90]: Bois, ebenda, S. 136.

[^91]: Siehe Norman Cohn, *Cosmos, Chaos, and the World to Come: The Ancient Roots of the Apocalyptic Faith* (New Haven: Yale University Press, 1993), Kapitel. 1-3, insbesondere S. 60.

[^92]: Bruce Ni. Metzger und Michael D. Coogan, eds., *The Oxford Companion to the Bible* (Oxford: Oxford University Press, 1993), p.178.

[^93]: Boyden, ebenda, S. 118.

::: {.content-visible when-format=latex}
\setsubtitle{Parallelen zwischen dem altersschwachen Niedergang der Heiligen Mutter Kirche und dem Nanny-Staat}
:::