# DIE LETZTEN TAGE DER POLITIK

:::{.content-hidden when-format=latex}
*Parallelen zwischen dem altersschwachen Niedergang der Heiligen Mutter Kirche und dem Nanny-Staat*
:::

> „Ich glaube auch - und hoffe, dass Politik und Wirtschaft in Zukunft nicht mehr so wichtig sein werden wie in der Vergangenheit; es wird die Zeit kommen, in der die meisten unserer heutigen Kontroversen über diese Themen so trivial und bedeutungslos erscheinen werden wie die theologischen Debatten, in denen die eifrigsten Köpfe des Mittelalters ihre Energien vergeudeten.“ [^94] Arthur C. Clarke

Vom bevorstehenden Tod der Politik zu sprechen, kann je nach Veranlagung lächerlich oder optimistisch erscheinen. Doch genau das ist es, was die Informationsrevolution wahrscheinlich bringen wird. Für Leser, die in einem politikdurchtränkten Jahrhundert aufgewachsen sind, mag die Vorstellung, dass das Leben ohne Politik ablaufen könnte, wie ein Hirngespinst erscheinen, so als würde man behaupten, man könne leben, indem man nur Nährstoffe aus der Luft aufnimmt. Doch die Politik im modernen Sinne, also die Beschäftigung mit der Kontrolle und Rationalisierung der Staatsgewalt, ist größtenteils eine moderne Erfindung. Wir glauben, dass sie mit der modernen Welt enden wird, so wie das Gewirr von feudalen Pflichten und Verpflichtungen, das die Aufmerksamkeit der Menschen im Mittelalter in Anspruch nahm, mit dem Mittelalter endete. Während der Feudalzeit, so der Historiker Martin van Creveld, „gab es keine Politik (der Begriff selbst musste erst noch erfunden werden und geht erst auf das sechzehnte Jahrhundert zurück)“.[^95]

Der Gedanke, dass die Politik, wie wir sie heute kennen, vor der Neuzeit nicht existierte, mag überraschen, vor allem wenn man bedenkt, dass Aristoteles zu Zeiten Alexanders des Großen einen Aufsatz mit diesem Titel verfasst hatte. Aber sehen Sie genau hin. Wörter, die in antiken Texten verwendet werden, sind nicht unbedingt zeitgenössische Konzepte. Aristoteles schrieb auch eine Abhandlung mit dem Titel Sophistische Widerlegungen, ein Begriff, der heute ungefähr so bedeutungslos ist wie Politik im Mittelalter. Das Wort war einfach nicht in Gebrauch. Es ist im englischen Wortschatz das erste Mal im Jahr 1529 aufgetaucht.[^96] Schon damals schien „Politik“ abwertend gemeint gewesen zu sein, abgeleitet von dem altfranzösischen Wort politique, mit dem man „Opportunisten und Rückgratlose“ bezeichnete.[^97]

Es dauerte fast zweitausend Jahre, bis Aristoteles' latentes Konzept mit der Bedeutung auftauchte, die wir heute kennen. Warum? Bevor die moderne Welt Aristoteles' Wort sinnvoll nutzen konnte, waren megapolitische Bedingungen erforderlich, die den Ertrag von Gewalt dramatisch erhöhten. Die Schießpulverrevolution, die wir in The Great Reckoning analysiert haben, hat genau das bewirkt. Sie steigerte die Rendite von Gewalt weit über das hinaus, was sie jemals gewesen war. Dadurch wurde die Frage, wer den Staat kontrolliert, wichtiger als je zuvor. Logischerweise und unweigerlich entstand die Politik aus dem Kampf um die Kontrolle der stark gestiegenen Beute der Macht.

Die Politik begann vor fünf Jahrhunderten mit der Frühphase der Industrialisierung. Jetzt liegt sie im Sterben. Eine weit verbreitete Abneigung gegen Politik und Politiker durchzieht die Welt. Man sieht es an den Nachrichten und Spekulationen über die verborgenen Details von Whitewater und den schlecht getarnten Mord an Vincent Foster. Sie sehen es in zahlreichen anderen Skandalen, die Präsident Bill Clinton betreffen. Sie sehen es in Berichten über die Veruntreuung von Geldern aus dem Postamt durch führende Kongressabgeordnete. Sie sehen es in Skandalen, die zu Rücktritten im Umfeld von John Major führten, und in ähnlichen Skandalen in Frankreich, die zwei aktuelle Premierminister, Eduard Balladur und Alain Juppe, betrafen. Noch größere Skandale wurden in Italien aufgedeckt, wo der siebenmalige Ministerpräsident Giulio Andreotti auf die Anklagebank gebracht wurde, um sich unter anderem wegen Verbindungen zur Mafia und der Anordnung des Mordes an Mino Pecorelli, einem Enthüllungsjournalisten, vor Gericht zu verantworten. Weitere Skandale haben den Ruf des spanischen Premierministers Filipe Gonzales beschädigt. Korruptionsvorwürfe kosteten vier japanische Premierminister in den ersten fünf Jahren der 1990er Jahre ihr Amt. Das kanadische Justizministerium beschuldigte in einem Schreiben an die Schweizer Behörden den ehemaligen Premierminister Brian Mulroney, beim Verkauf von Airbus-Flugzeugen an Air Canada im Wert von 1,8 Milliarden Dollar Schmiergelder erhalten zu haben.[^98] Willy Claes, der Generalsekretär der NATO, wurde aufgrund von Korruptionsvorwürfen zum Rücktritt gezwungen. Selbst in Schweden musste Mona Sahlm, stellvertretende Ministerpräsidentin und voraussichtliche Ministerpräsidentin, zurücktreten, nachdem ihr vorgeworfen wurde, mit den Kreditkarten der Regierung Windeln und andere Haushaltswaren gekauft zu haben. Fast überall, wo man sich in Ländern mit reifen Wohlfahrtsstaaten, die einst als gut regiert galten, hinwendet, hassen die Menschen ihre politischen Führer.

### Verachtung als Frühindikator

Moralische Empörung gegen korrupte Führer ist kein isoliertes historisches Phänomen, sondern ein häufiger Vorläufer des Wandels. Sie tritt immer wieder auf, wenn eine Epoche einer anderen weicht. Immer dann, wenn der technologische Wandel die alten Formen von den neuen bewegenden Kräften der Wirtschaft abgekoppelt hat, verschieben sich die moralischen Maßstäbe, und die Menschen beginnen, diejenigen, die die alten Institutionen leiten, mit wachsender Verachtung zu begegnen. Diese weit verbreitete Abscheu zeigt sich, lange bevor die Menschen eine neue kohärente Ideologie des Wandels entwickeln. Während wir schreiben, gibt es noch kaum Anzeichen für eine artikulierte Ablehnung der Politik. Das wird später kommen. Die meisten ihrer Zeitgenossen sind noch nicht auf die Idee gekommen, dass ein Leben ohne Politik möglich ist. Was wir in den letzten Jahren des zwanzigsten Jahrhunderts haben, ist unartikulierte Verachtung.

Etwas Ähnliches geschah im späten fünfzehnten Jahrhundert, aber damals war es eher die Religion als die Politik, die sich im Prozess der Verkleinerung befand. Trotz des weit verbreiteten Glaubens an die „Heiligkeit des geistlichen Amtes“ [^99] wurden sowohl die höheren als auch die niederen Ränge des Klerus in höchstem Maße verachtet, nicht unähnlich der Haltung der Bevölkerung gegenüber Politikern und Bürokraten heute. Es wurde weithin angenommen, dass der höhere Klerus korrupt, weltlich und käuflich sei. Und das nicht ohne Grund. Mehrere Päpste des fünfzehnten Jahrhunderts prahlten offen mit ihren unehelichen Kindern. Der niedere Klerus genoss ein noch geringeres Ansehen, denn er wucherte auf dem Land und in der Stadt, bettelte um Almosen und bot häufig an, Gottes Gnade und die Vergebung der Sünden an jeden zu verkaufen, der dafür Geld hinblätterte.

Unter der „Kruste der oberflächlichen Frömmigkeit“ [^100] befand sich ein korruptes und immer schlechter funktionierendes System. Viele verloren den Respekt vor denen, die es leiteten, lange bevor jemand sich traute offen zu sagen, dass es nicht funktionierte. Ein von Religion durchdrungenes Leben, das keinen Unterschied zwischen dem Geistlichen und dem Zeitlichen machte, hatte seine Möglichkeiten erschöpft. Sein Ende war unvermeidlich, lange bevor Luther seine 95 Thesen an die Kirchentür in Wittenberg nagelte.

## EINE SÄKULARE REFORMATION

Wir glauben, dass die Reaktion gegen die Sättigungspolitik einen ähnlichen Weg einschlägt.

Der Untergang der Sowjetunion und die Ablehnung des Sozialismus sind Teil eines umfassenden Musters der Entpolitisierung, das die Welt durchzieht. Dies zeigt sich jetzt am deutlichsten in einer wachsenden Verachtung für diejenigen, die die Regierungen der Welt führen. Sie wird nur zum Teil von der Erkenntnis angetrieben, dass sie korrupt sind und dazu neigen, „Ablässe“ aus politischen Schwierigkeiten im Austausch für Wahlkampfspenden oder besondere Hilfe bei Rohstoffgeschäften zu verkaufen, um ihre persönlichen Finanzen aufzubessern.

Die Reaktion gegen Politiker ist auch durch die zunehmende Erkenntnis motiviert, dass vieles von dem, was sie mit großem Aufwand tun, sinnlos ist, so wie die Organisation einer weiteren Bußwallfahrt, bei der die Menschen barfuß durch den Schnee laufen, oder die Gründung eines weiteren Bettelmönchsordens im späten 15. Jahrhundert wenig dazu beigetragen hätte, die Produktivität zu erhöhen oder den Druck auf den Lebensstandard zu erleichtern.

### Die letzten Tage der Heiligen Mutter Kirche

Am Ende des Mittelalters war die monolithische Kirche als Institution altersschwach und kontraproduktiv geworden - ein deutlicher Unterschied zu ihrem positiven wirtschaftlichen Beitrag fünf Jahrhunderte zuvor. Wie wir im letzten Kapitel untersucht haben, spielte die Kirche Ende des zehnten Jahrhunderts eine führende Rolle bei der Herstellung von Ordnung und der Erleichterung des wirtschaftlichen Aufschwungs nach der Anarchie, die das Ende des Dunklen Zeitalters gekennzeichnet hatte. Zu dieser Zeit war die Kirche für das Überleben einer großen Zahl von kleinen Grundbesitzern und Leibeigenen, die den Großteil der westeuropäischen Bevölkerung ausmachten, unverzichtbar. Am Ende des fünfzehnten Jahrhunderts war die Kirche zu einem großen Hemmschuh für die Produktivität geworden. Die Lasten, die sie der Bevölkerung aufbürdete, drückten den Lebensstandard nach unten.

Das Gleiche kann man heute über den Nationalstaat sagen. Er war eine notwendige Anpassung an die neuen megapolitischen Bedingungen, die durch die Schießpulverrevolution vor fünf Jahrhunderten geschaffen wurden. Der Nationalstaat erweiterte die Reichweite der Märkte und verdrängte die zersplitterten lokalen Autoritäten zu einer Zeit, als umfassendere Handelsgebiete große Gewinne brachten. Die Tatsache, dass sich die Kaufleute fast überall in Europa spontan mit dem Monarchen im Zentrum verbündeten, als dieser versuchte, seine Autorität zu festigen, ist an sich schon ein deutlicher Beweis dafür, dass der Nationalstaat in seiner frühen Form gut für das Geschäft war. Er trug dazu bei, den Handel von den Lasten zu befreien, die ihm von Feudalherren und lokalen Magnaten aufgebürdet wurden.

In einer Welt, in der die Renditen für Gewalt hoch waren und weiter stiegen, war der Nationalstaat eine nützliche Institution. Doch fünf Jahrhunderte später, am Ende dieses Jahrtausends, haben sich die megapolitischen Bedingungen geändert. Die Gewaltrenditen sinken, und der Nationalstaat ist, wie die Kirche in der Dämmerung des Mittelalters, ein Anachronismus, der zu einem Hemmschuh für Wachstum und Produktivität geworden ist.

Wie die Kirche damals hat auch der Nationalstaat heute seine Möglichkeiten ausgeschöpft. Er ist bankrott, eine Institution, die sich zu einem senilen Extrem entwickelt hat. Wie die Kirche damals war er fünf Jahrhunderte lang die vorherrschende Form der sozialen Organisation. Da er die Bedingungen, die ihn ins Leben gerufen haben, überlebt hat, ist er reif für den Untergang. Und sie wird fallen. Die Technologie ist dabei, eine Revolution in der Machtausübung auszulösen, die den Nationalstaat ebenso sicher zerstören wird, wie das Schießpulver und der Buchdruck das Monopol der mittelalterlichen Kirche zerstört haben.

Wenn unsere Überlegungen richtig sind, wird der Nationalstaat durch neue Formen der Souveränität ersetzt werden, von denen einige in der Geschichte einzigartig sind, andere an die Stadtstaaten und mittelalterlichen Handelsrepubliken der vormodernen Welt erinnern. Was alt war, wird nach dem Jahr 2000 neu sein. Und was unvorstellbar war, wird alltäglich sein. In dem Maße, in dem die Technologie an Bedeutung gewinnt, werden die Regierungen feststellen, dass sie wie Unternehmen um Einkommen konkurrieren müssen und für ihre Dienstleistungen nicht mehr verlangen dürfen, als sie den Menschen, die dafür bezahlen, wert sind. Die vollen Auswirkungen dieses Wandels sind nahezu unvorstellbar.

## DAMALS UND HEUTE

Etwas Ähnliches hätte man auch vor fünfhundert Jahren, an der Wende zum fünfzehnten Jahrhundert, sagen können. Damals wie heute stand die westliche Zivilisation an der Schwelle zu einem bedeutsamen Wandel. Obwohl es kaum jemand wusste, lag die mittelalterliche Gesellschaft im Sterben. Ihr Tod wurde weder allgemein erwartet noch verstanden. Nichtsdestotrotz war die vorherrschende Stimmung von tiefer Niedergeschlagenheit geprägt. Dies ist am Ende einer Epoche üblich, wenn die konventionellen Denker spüren, dass die Dinge auseinanderfallen, dass „der Falke den Falkner nicht hören kann“. Doch ihre geistige Trägheit ist oft zu groß, um die Auswirkungen der sich abzeichnenden Machtkonstellationen zu begreifen. Der Mittelalterhistoriker Johan Huizinga schrieb über die ausklingenden Tage des Mittelalters: „Die Chronisten des fünfzehnten Jahrhunderts sind fast alle die Dummköpfe einer absoluten Fehleinschätzung ihrer Zeit gewesen, deren wirkliche bewegende Kräfte ihnen entgangen sind.“ [^101]

### Betrogene Mythen

Größere Veränderungen in der zugrundeliegenden Dynamik der Macht neigen dazu, konventionelle Denker zu verwirren, weil sie Mythen entlarven, die die alte Ordnung rationalisieren, aber keine wirkliche Erklärungskraft haben. Am Ende des Mittelalters, wie auch heute, klaffte eine besonders große Lücke zwischen den überlieferten Mythen und der Realität. Huizinga sagte über die Europäer im späten fünfzehnten Jahrhundert: „Ihr ganzes Ideensystem war von der Fiktion durchdrungen, dass das Rittertum die Welt beherrscht“.[^102] Dies wird von der heutigen Annahme, dass sie von Abstimmungen und Beliebtheitswettbewerben beherrscht wird, noch übertroffen. Beide Behauptungen halten einer genauen Prüfung nicht stand. In der Tat ist die Vorstellung, dass der Lauf der Geschichte durch demokratische Abstimmungen bestimmt wird, genauso albern wie die mittelalterliche Vorstellung, dass sie durch einen ausgefeilten Kodex der Sitten, genannt Ritterlichkeit, bestimmt wird.

Die Tatsache, dass diese Behauptung an Ketzerei grenzt, zeigt, wie weit das konventionelle Denken von einem realistischen Verständnis der Machtdynamik in der spätindustriellen Gesellschaft entfernt ist. Dies ist ein Thema, das wir in diesem Buch genau untersuchen. Unserer Ansicht nach war das Wahlrecht eher eine Folge als eine Ursache der megapolitischen Bedingungen, die den modernen Nationalstaat hervorgebracht haben. Die Massendemokratie und das Konzept der Staatsbürgerschaft blühten auf, als der Nationalstaat wuchs. Sie werden ins Wanken geraten, wenn der Nationalstaat ins Wanken gerät, was in Washington ebenso viel Bestürzung hervorrufen wird, wie die Erosion des Rittertums am Hof des Herzogs von Burgund vor fünfhundert Jahren.

## PARALLELEN ZWISCHEN RITTERLICHKEIT UND STAATSBÜRGERSCHAFT

Wenn Sie verstehen können, wie und warum die Bedeutung ritterlicher Eide mit dem Übergang zu einer industriellen Organisation der Gesellschaft schwand, werden Sie besser in der Lage sein zu erkennen, wie die Staatsbürgerschaft, wie wir sie heute kennen, im Informationszeitalter schwinden könnte. Beide dienten einer ähnlichen Funktion. Sie erleichterten die Ausübung von Macht unter zwei ganz unterschiedlichen megapolitischen Bedingungen.

Feudale Eide herrschten in einer Zeit vor, in der die Verteidigungstechnik im Vordergrund stand, die Souveränität zersplittert war und Privatpersonen und Körperschaften ihre eigene militärische Macht ausübten. Vor der Schießpulverrevolution wurden Kriege normalerweise von kleinen Kontingenten bewaffneter Männer geführt. Selbst die mächtigsten Monarchen verfügten nicht über ein militum perpetuum, ein stehendes Heer. Sie bezogen ihre militärische Unterstützung von ihren Vasallen, den Großfürsten, die sich wiederum auf ihre Vasallen, die Kleinfürsten, stützten, die wiederum auf ihre Vasallen, die Ritter, zurückgriffen. Die gesamte Loyalitätskette reichte von der Hierarchie bis hinunter zur Person mit dem niedrigsten sozialen Status, die als würdig erachtet wurde, Waffen zu tragen.

### Uniformen oder Abweichungen?

Im Gegensatz zu einem modernen Heer marschierte ein mittelalterliches Heer, vor der Einführung des Bürgerrechts, nicht in Uniformen auf das Schlachtfeld. Im Gegenteil, jeder Gefolgsmann oder Vasall, jeder Ritter, Baron oder Lord unterschiedlichen Ranges hatte seine eigene unverwechselbare Tracht, die seinen Platz in der Hierarchie widerspiegelte. Anstelle von Uniformen gab es Unterschiede, die die vertikale Struktur der Gesellschaft betonten, in der jeder Stand unterschiedlich war. Wie Huizinga sagte, unterschieden sich die mittelalterlichen Krieger durch „äußere Zeichen von \... Unterschieden: Trachten, Farben, Abzeichen, Schlachtrufe.“ [^103]

Kriege wurden auch nicht nur von Regierungen oder Nationen geführt. Martin van Creveld hat darauf hingewiesen, dass die moderne Vorstellung vom Krieg, wie sie von Strategen wie Carl von Clausewitz stilisiert wurde, die Realität vormoderner Konflikte falsch wiedergibt. Van Creveld schreibt:

> Tausend Jahre lang nach dem Fall Roms wurden bewaffnete Konflikte von verschiedenen gesellschaftlichen Gruppen ausgetragen. Dazu gehörten barbarische Stämme, die Kirche, Feudalherren jeden Ranges, freie Städte und sogar Privatpersonen. Auch die „Armeen“ jener Zeit entsprachen nicht denen, die wir heute kennen; es ist sogar schwierig, ein Wort zu finden, das ihnen gerecht wird. Die Kriege wurden von Scharen von Gefolgsleuten geführt, die sich militärische Gewänder anzogen und ihrem Herrn folgten.[^104]

Unter diesen Bedingungen war es für den Fürsten offensichtlich von entscheidender Bedeutung, dass seine Gefolgsleute tatsächlich „ihr militärisches Gewand anzogen und folgten“. Daher die starke Betonung des ritterlichen Eides.

Die Ehre des mittelalterlichen Ritters und die Pflicht des wehrpflichtigen Soldaten hatten parallele Funktionen. Der mittelalterliche Mensch war durch Eide an Einzelpersonen und die Kirche gebunden, so wie der moderne Mensch durch seine Staatsbürgerschaft an den Nationalstaat gebunden ist. Die Verletzung eines Eides war im Mittelalter gleichbedeutend mit Verrat. Die Menschen im Spätmittelalter gingen bis zum Äußersten, um die Verletzung von Eiden zu vermeiden, so wie Millionen moderner Bürger in den Weltkriegen bis zum Äußersten gingen und Maschinengewehrnester angriffen, um ihre Pflichten als Staatsbürger zu erfüllen.

Sowohl die Ritterlichkeit als auch das Bürgertum fügten dem einfachen Kalkül eine zusätzliche Dimension hinzu, die ansonsten uninformierte Menschen davon abhalten würde, sich auf ein Schlachtfeld zu begeben und dort zu bleiben, wenn es schwierig wird. Sowohl Ritterlichkeit als auch Staatsbürgerschaft verleiteten die Menschen dazu, zu töten und den Tod zu riskieren. Nur anspruchsvolle und überzogene Werte, die durch führende Institutionen stark gestärkt werden, können diese Funktion erfüllen.

### Umgehung der Kosten-Nutzen-Analyse

Der Erfolg und das Überleben eines jeden Systems hängen von seiner Fähigkeit ab, in Konflikt- und Krisenzeiten militärische Anstrengungen zu unternehmen. Es liegt auf der Hand, dass die Entscheidung eines mittelalterlichen Ritters oder eines Gefreiten in den Schützengräben des Ersten Weltkriegs, sein Leben in der Schlacht zu riskieren, wahrscheinlich nicht auf einer nüchternen Kosten-Nutzen-Rechnung beruhte. Selten sind Kriege so einfach zu führen, oder die Belohnungen für diejenigen, die die Hauptlast der Kämpfe tragen, überschatten die möglichen Kosten so sehr, dass ein Heer von Wirtschaftsoptimierern rekrutiert werden könnte, um auf das Schlachtfeld zu eilen. In fast jedem Krieg und in der Tat in den meisten Schlachten gibt es Momente, in denen sich das Blatt innerhalb eines Herzschlags wenden kann. Studenten der Militärgeschichte wissen, dass der Unterschied zwischen Niederlage und Sieg oft durch den Mut, die Tapferkeit und die Grausamkeit, mit der einzelne Soldaten ihre Aufgabe angehen, bestimmt wird. Wenn die kämpfenden Männer nicht bereit sind, für ein Stück Boden zu sterben, das nach dem Ende der Schlacht keinen Pfifferling mehr wert ist, dann werden sie sich wahrscheinlich nicht gegen einen ansonsten ebenbürtigen Gegner durchsetzen.

Dies hat wichtige Auswirkungen. Je wirksamer Souveränitäten die Abtrünnigkeit begrenzen und militärische Anstrengungen fördern, desto wahrscheinlicher ist es, dass sie sich militärisch durchsetzen. In der Kriegsführung veranlassen die nützlichsten Wertesysteme die Menschen dazu, sich so zu verhalten, wie es kurzfristiges rationales Kalkül ausschließen würde. Keine Organisation könnte militärische Kräfte wirksam mobilisieren, wenn die Menschen, die sie in die Schlacht schickt, sich frei fühlen würden, zu berechnen, wo ihr eigener Vorteil liegt, und sich dementsprechend dem Kampf anzuschließen oder wegzulaufen. In diesem Fall würden sie fast nie kämpfen. Nur unter den günstigsten Umständen oder in der größten Verzweiflung würde sich ein vernünftiger Mensch auf der Grundlage einer kurzfristigen Kosten-Nutzen-Analyse auf eine potenziell tödliche Schlacht einlassen. Vielleicht würde der Homo oeconomicus an einem sonnigen Tag kämpfen, wenn die Kräfte auf seiner Seite überwältigend, der Feind schwach und die potenziellen Vorteile einer Schlacht verlockend wären. Mag sein. Vielleicht würde er aber auch kämpfen, wenn er von marodierenden Kannibalen in die Enge getrieben wird.

Aber das sind extreme Umstände. Was ist mit den häufigeren Bedingungen der Kriegsführung, die weder so attraktiv sind, dass sie einer Kosten-Nutzen-Analyse standhalten würden, noch so verzweifelt, dass sie keinen Ausweg bieten? Hier leisten Konzepte wie Ritterlichkeit und Staatsbürgerschaft einen wichtigen Beitrag zum erfolgreichen Einsatz militärischer Macht. Lange bevor eine Schlacht beginnt, müssen die herrschenden Organisationen den Einzelnen davon überzeugen, dass die Einhaltung bestimmter Pflichten gegenüber dem Herrn oder dem Nationalstaat wichtiger ist als das Leben selbst. Die Mythen und Rationalisierungen, die Gesellschaften einsetzen, um die Risikobereitschaft auf dem Schlachtfeld zu fördern, sind ein wesentlicher Bestandteil ihrer militärischen Stärke.

Um wirksam zu sein, müssen diese Mythen auf die vorherrschenden megapolitischen Bedingungen zugeschnitten sein. Die Fiktion, dass das Rittertum die Welt regiert, hat heute keine Bedeutung mehr, vor allem nicht in einer Stadt wie New York. Aber es war der hochgehaltene Mythos des Feudalismus. Er rechtfertigte und rationalisierte das Schuldverhältnis, das jeden unter der Herrschaft der Kirche und eines kriegerischen Adels band. In einer Zeit, in der private Kriege der Habgier an der Tagesordnung waren,[^105] hingen die Ausübung von Macht und das Überleben des Einzelnen von der Bereitschaft anderer ab, ihre Versprechen zum Militärdienst unter Zwang zu erfüllen. Es war offensichtlich entscheidend, dass diese Versprechen verlässlich waren.

### Vor der Nationalität

Anders als heute spielte das Konzept der Nationalität im Mittelalter bei der Begründung von Souveränität keine oder nur eine geringe Rolle. Monarchen, aber auch einige Kirchenfürsten und mächtige Herren besaßen Territorien aus privatem Recht. In einer Weise, die keine moderne Entsprechung hat, konnten diese Herren Gebiete verkaufen oder verschenken oder neue Gebiete durch Übertragung oder Heirat sowie durch Eroberung erwerben. Man kann sich heute kaum vorstellen, dass die Vereinigten Staaten unter die Souveränität eines nicht englischsprachigen portugiesischen Präsidenten fallen, weil er zufällig die Tochter des früheren amerikanischen Präsidenten geheiratet hat. Doch etwas Ähnliches war im mittelalterlichen Europa Gang und Gäbe. Die Macht wurde durch Vererbung weitergegeben. Städte und Länder wechselten die Herrscher, so wie Antiquitäten den Besitzer wechseln. In vielen Fällen stammten die Herrscher nicht aus den Regionen, in denen ihr Besitz lag. Manchmal beherrschten sie die Landessprache nicht oder sprachen sie schlecht und mit starkem Akzent. Doch für die persönlichen Verpflichtungen machte es kaum einen Unterschied, ob ein Spanier König von Athen oder ein Österreicher König von Spanien war.

### Körperschaftliche Souveränität

Die Souveränität wurde auch von religiösen Körperschaften wie den Tempelrittern, den Johannitern und dem Deutschen Orden ausgeübt. Diese hybriden Institutionen haben keine modernen Entsprechungen. Sie verbanden religiöse, soziale, gerichtliche und finanzielle Aktivitäten mit der Souveränität über lokale Gebiete.[^106] Sie übten zwar eine territoriale Gerichtsbarkeit aus, waren aber fast das Gegenteil der heutigen Regierungen, da die Nationalität keine Rolle bei der Mobilisierung ihrer Unterstützung oder ihrem Regierungssystem spielte. Die Mitglieder und Amtsträger dieser Orden stammten aus allen Teilen des christlichen Europas, der so genannten „Christenheit“.

Niemand hielt es für angemessen oder notwendig, dass die Regierenden aus der lokalen Bevölkerung stammten. Die Mobilisierung von Unterstützung im zersplitterten mittelalterlichen Regierungssystem hing nicht wie in der Neuzeit von einer nationalen Identität oder einer Verpflichtung gegenüber dem Staat ab, sondern von persönlicher Loyalität und gewohnheitsmäßigen Bindungen, die als eine Frage der persönlichen Ehre aufrechterhalten werden mussten. Diese Eide konnte jeder schwören, egal woher er kam, sofern er aufgrund seines Standes als würdig erachtet wurde.

### Das Gelübde

Ritterliche Gelübde banden Menschen aneinander und wurden auf die Ehre der Beteiligten geschworen. Wie Huizinga schrieb, „legten die Menschen bei der Ablegung eines Gelübdes einige Entbehrungen auf sich, die sie anspornten, die Handlungen, zu denen sie sich verpflichtet hatten, zu vollenden“.[^107] Der Einhaltung von Gelübden wurde so viel Bedeutung beigemessen, dass die Menschen häufig den Tod riskierten oder schwerwiegende Folgen in Kauf nahmen, um ihre Gelübde nicht zu brechen. Die Eide selbst verpflichteten die Menschen oft zu Handlungen, die Ihnen und den meisten Lesern dieses Buches wahrscheinlich lächerlich vorkommen würden, weil sie eine Frage der Ehre sind.

So schworen die Ritter des Sterns beispielsweise einen Eid, sich niemals „mehr als vier Morgen vom Schlachtfeld zurückzuziehen, wodurch bald darauf mehr als neunzig von ihnen ihr Leben verloren“.[^108] Das Verbot, sich auch nur taktisch zurückzuziehen, ist als militärische Strategie irrational. Aber es war ein allgemeines Gebot der ritterlichen Gelübde. Vor der Schlacht von Agincourt ordnete der englische König an, dass die Ritter auf Patrouille ihre Rüstung ablegen sollten, da es mit ihrer Ehre unvereinbar gewesen wäre, sich in ihrer Rüstung aus den feindlichen Linien zurückzuziehen. So kam es, dass sich der König selbst verirrte und an dem Dorf vorbeikam, in dem die Vorhut seines Heeres übernachtet hatte. Da er eine Rüstung trug, verbot ihm seine ritterliche Ehre, einfach umzukehren, als er seinen Fehler entdeckte, und zum Dorf zurückzukehren. Er verbrachte die Nacht in einer exponierten Lage.

So albern dieses Beispiel auch erscheinen mag, König Heinrich hat sich wahrscheinlich nicht verkalkuliert, als er dachte, dass er durch den Rückzug seine Ehre mehr riskiert hätte, als wenn er hinter den feindlichen Linien schlief und damit ein demoralisierendes Beispiel für seine gesamte Armee gegeben hätte.

Die Geschichte des Mittelalters ist voll von Beispielen prominenter Personen, die Gelübde erfüllten, die uns lächerlich erscheinen würden. In vielen Fällen standen die vorgeschlagenen Handlungen in keinem objektiven Zusammenhang mit irgendeinem Nutzen, sondern waren nur eine anschauliche Demonstration der Bedeutung, die die Betreffenden dem Gelübde selbst beimaßen. Zu den üblichen Gelübden gehörten: ein Auge geschlossen zu halten, nur im Stehen zu essen und zu trinken und ein selbst auferlegter Krüppel zu werden, indem man sich in eine Ein-Mann-Kettenbande begibt. Es war ein weit verbreiteter Brauch, schmerzhafte Fußfesseln zu tragen. Wenn Sie heute jemanden mit einem schweren Fußeisen auf der Straße strampeln sähen, würden Sie wahrscheinlich annehmen, dass er geisteskrank ist, und nicht, dass er ein Mann von großer Tugendhaftigkeit ist. Doch im Kontext der Ritterlichkeit war das freiwillige Anlegen eines solchen Geräts ein Ehrenabzeichen. Und es gab viele ähnliche Bräuche, die heute ebenso lächerlich erscheinen würden. Wie Huizinga beschreibt, legten viele ein Gelübde ab, „am Samstag nicht in einem Bett zu schlafen, am Freitag keine tierische Nahrung zu sich zu nehmen, etc. Ein Akt der Askese jagt den anderen: ein Adliger verspricht, keine Rüstung zu tragen, an einem Tag in der Woche keinen Wein zu trinken, nicht in einem Bett zu schlafen, sich nicht zu den Mahlzeiten zu setzen oder das Cilicium zu tragen“.[^109]

Die Fastenzeit ist eine stark abgemilderte Version dieses selbst auferlegten Unbehagens.

Viele Liebhaber von Gelübden bildeten Orden, die ihren Mitgliedern besonders schwere Entbehrungen als Ehrenprüfungen auferlegten. Der Orden der Clalois und Galoises zum Beispiel kleidete sich im Sommer mit „Pelzen und pelzgefütterten Hauben und zündete ein Feuer im Herd an, während sie im Winter nur einen einfachen Mantel ohne Pelz tragen durften, weder Mantel, noch Hut, noch Handschuhe, und nur sehr leichte Bettwäsche hatten.“ Wie Huizinga berichtet, „ist es nicht verwunderlich, dass viele Mitglieder an der Kälte starben.“ [^110]

> „Die mittelalterliche Selbstgeißelung war eine grausame Folter, die sich die Menschen selbst zufügten, in der Hoffnung, einen richtenden und strafenden Gott dazu zu bewegen, seine Rute wegzulegen, ihre Sünden zu vergeben und ihnen die größeren Strafen zu ersparen, die ihnen sonst in dieser und der nächsten Welt drohten.“ [^111] - Norman Cohn

### Geißelung, damals und heute

Vom Gelübde, das Gefahren und Entbehrungen mit sich brachte, war es nur ein kleiner Schritt zu Prüfungen, Pilgerfahrten, Kasteiungen, Unannehmlichkeiten und sogar absichtlich selbst zugefügten Verletzungen. Dies konnte im Mittelalter als äußerst nützlich und lobenswert angesehen werden. Sie waren Gesten der Ernsthaftigkeit, mit der Gelübde abgelegt wurden, eine Logik, die auch heute noch bei der Aufnahme von Studentenverbindungen nicht völlig fremd ist.

Im Sommer zu schwitzen, im Winter zu frieren oder barfuß durch den Schnee zu pilgern, war relativ harmlos im Vergleich zu der „grimmigen Folter“ der Selbstgeißelung. Dies war eine speziell mittelalterliche Form der Buße, die fast zeitgleich mit dem Beginn des Feudalismus aufkam. Sie wurde erstmals „von Einsiedlern in den Klostergemeinschaften von Camaldoli und Fonte Avellana zu Beginn des elften Jahrhunderts übernommen.“ [^112]

Anstatt bei kaltem Wetter nur barfuß zu laufen, organisierten die Geißler Prozessionen, bei denen sie Tag und Nacht von einer Stadt zur nächsten zogen. „Und jedes Mal, wenn sie in eine Stadt kamen, stellten sie sich in Gruppen vor der Kirche auf und peitschten sich stundenlang aus.“ [^113]

Wir glauben, dass Menschen in der Zukunft, die auf die Ära des Nationalstaates zurückblicken, einige der Unternehmungen, die im zwanzigsten Jahrhundert im Namen der Staatsbürgerschaft unternommen wurden, ebenso lächerlich finden werden wie wir die Selbstgeißelung. Aus der Sicht der Informationsgesellschaft wird das Spektakel von Soldaten in der Neuzeit, die um die halbe Welt reisen, um aus Loyalität zum Nationalstaat den Tod in Kauf zu nehmen, als grotesk und lächerlich empfunden werden. Es wird nicht viel anders erscheinen als einige der außergewöhnlichen und übertriebenen Riten des Rittertums, wie z.B. das Herumlaufen in Fußfesseln, auf das ansonsten vernünftige Menschen während der Feudalzeit stolz waren.

### Die Ritterlichkeit weicht der Staatsbürgerschaft

Das Rittertum verblasste und wurde durch die Staatsbürgerschaft ersetzt, als die megapolitischen Bedingungen sich änderten, und der militärische Zweck des Gelübdes gegenüber seinem Herrn war antiquiert. In der Welt der Schießpulverwaffen und der industriellen Armeen bestanden ganz andere Beziehungen zwischen den Menschen, die kämpften, und ihren Befehlshabern. Das Bürgertum entstand zu einer Zeit, als die Erträge aus der Gewalttätigkeit hoch waren und weiter stiegen, und der Staat verfügte über weitaus größere Ressourcen als die sozialen Einheiten, die im Mittelalter Krieg führten. Aufgrund seiner großen Macht und seines Reichtums konnte der Nationalstaat direkt mit der Masse der einfachen Soldaten verhandeln, die in seiner Uniform kämpften.

Solche Geschäfte erwiesen sich für den Staat als weitaus billiger und weniger mühsam als der Versuch, durch Verhandlungen mit mächtigen Fürsten und lokalen Würdenträgern militärische Kräfte aufzustellen, von denen jeder in der Lage war, sich gegen Forderungen zu wehren, die seinen Interessen zuwiderliefen, wie es kein einzelner Bürger des Nationalstaates vermochte.

Aus Gründen, auf die wir später näher eingehen werden, hing die Staatsbürgerschaft entscheidend von der Tatsache ab, dass kein Individuum oder keine kleine Gruppe von Individuen megapolitisch in der Lage war, unabhängig militärische Macht auszuüben. In dem Maße, wie die Informationstechnologie die Logik des Kampfes verändert, wird sie die Mythen der Staatsbürgerschaft ebenso sicher antiquieren, wie das Schießpulver das mittelalterliche Rittertum antiquierte.

### Die Hell's Angels zu Pferde

Die Aristokraten der berittenen Krieger, die Westeuropa jahrhundertelang beherrschte, waren kaum die Gentlemen, zu denen ihre Nachkommen wurden. Sie waren rau und gewalttätig. Aus heutiger Sicht könnte man sie eher als das mittelalterliche Äquivalent von Motorradclubs verstehen. Die Sittenregeln und die vorgetäuschte Ritterlichkeit dienten eher dazu, ihre Exzesse zu zügeln, als ihr tatsächliches Verhalten zu beschreiben. Selbst eine enzyklopädische Darstellung der Regeln und Pflichten des Rittertums hätte wenig oder nichts über die Grundlagen der Macht des Adels verraten.

### Perfektion als Synonym für Erschöpfung

Das Aufkommen effektiver Schießpulverwaffen am Ende des fünfzehnten Jahrhunderts sorgte für eine gewaltige Explosion unter ihren Füßen - gerade als die bewaffneten Ritter ihre Kunst wie nie zuvor perfektioniert hatten. Zu diesem Zeitpunkt hatte die sorgfältige Zucht endlich ein 1,60 m großes Schlachtpferd hervorgebracht, ein Pferd, das die Statur hatte, einen berittenen Ritter in voller Rüstung bequem zu tragen. Doch „Perfektion“, wie C. Northcote Parkinson scharfsinnig bemerkte, „wird nur von Institutionen erreicht, die kurz vor dem Zusammenbruch stehen.“ [^114] Gerade als das neue Schlachtross perfektioniert war, wurden neue Waffen eingesetzt, um Pferd und Ritter vom Schlachtfeld zu vertreiben. Diese neuen Schießpulverwaffen konnten von einfachen Leuten abgefeuert werden. Sie erforderten wenig Geschicklichkeit, waren aber teuer in der Beschaffung. Durch ihre Verbreitung gewann der Handel gegenüber der Landwirtschaft, die die Grundlage der Feudalwirtschaft gewesen war, immer mehr an Bedeutung.

### Krieg in größerem Maßstab

Wie konnten die Schießpulverwaffen einen solchen Wandel herbeiführen? Zum einen erhöhten sie das Ausmaß der Kämpfe, was bedeutete, dass das Führen von Kriegen bald viel kostspieliger wurde als im Mittelalter. Vor der Schießpulverrevolution wurden Kriege in der Regel von so kleinen Gruppen geführt, dass sie über ein kleines und armes Gebiet geführt werden konnten. Das Schießpulver verschaffte dem Kampf in größerem Maßstab einen neuen Vorteil. Nur Herrscher mit Ansprüchen auf reiche Untertanen konnten es sich leisten, unter den neuen Bedingungen wirksame Streitkräfte aufzustellen. Diejenigen Herrscher, die dem Wachstum des Handels am besten Rechnung trugen, in der Regel Monarchen, die sich mit den städtischen Kaufleuten verbündeten, hatten auf dem Schlachtfeld einen Wettbewerbsvorteil. Nach van Creveld „konnten sie, auch dank der ihnen zur Verfügung stehenden überlegenen finanziellen Mittel, mehr Kanonen als alle anderen kaufen und den Gegner in Stücke sprengen.“ [^115]

Auch wenn es noch Jahrhunderte dauern sollte, bis die volle Logik der Schießpulverwaffen in den Bürgerarmeen der Französischen Revolution zum Tragen kam, war die Einführung von Militäruniformen in der Renaissance ein früher Hinweis auf die Umgestaltung der Kriegsführung durch das Schießpulver. Die Uniformen symbolisieren auf treffende Weise die neuen Beziehungen zwischen dem Krieger und dem Nationalstaat, die mit dem Übergang vom Rittertum zum Bürgertum Hand in Hand gingen. Der neue Nationalstaat würde mit seinen Bürgern eine „einheitliche“ Vereinbarung treffen, im Gegensatz zu den speziellen, abweichenden Vereinbarungen, die der Monarch oder der Papst mit einer langen Kette von Vasallen im Feudalismus getroffen hatte. In dem alten System hatte jeder einen anderen Platz in einer architektonischen Hierarchie. Jeder hatte einen Vertrag, der so einzigartig war wie sein Wappen und die bunten Wimpel, die er trug.

### Senkung der Opportunitätskosten von Reichtum

Die Schießpulverwaffen veränderten das Wesen der Gesellschaft noch auf eine andere Weise radikal. Sie trennten die Ausübung von Macht von körperlicher Kraft und senkten so die Opportunitätskosten der Handelsaktivitäten. Reiche Kaufleute mussten sich nicht mehr auf ihre eigene Geschicklichkeit und Stärke im Nahkampf oder auf Söldner mit ungewisser Loyalität verlassen, um sich zu verteidigen. Sie konnten darauf hoffen, von den neuen, größeren Armeen der großen Monarchen verteidigt zu werden. William Playfair sagte über das Mittelalter: „Während menschliche Kraft die Macht war, mit der Menschen im Falle von Feindseligkeiten belästigt wurden, \... war es damals unmöglich, lange Zeit gleichzeitig reich und mächtig zu sein.“ [^116] Als das Schießpulver aufkam, war es unmöglich, mächtig zu sein, ohne reich zu sein.

### Status und statisches Verstehen

Aus vielen der gleichen Gründe, aus denen die meisten Menschen heute schlecht darauf vorbereitet sind, die neue Dynamik der Informationsgesellschaft zu antizipieren, waren die führenden Denker der mittelalterlichen Gesellschaft nicht in der Lage, den Aufstieg des Handels, der eine so wichtige Rolle bei der Gestaltung der modernen Zeit spielte, vorherzusehen oder zu verstehen. Die meisten Menschen vor fünf Jahrhunderten betrachteten ihre sich verändernde Gesellschaft in statischen Begriffen. Wie Huizinga sagte: „Nur sehr wenig Besitz ist im modernen Sinne flüssig, während Macht noch nicht überwiegend mit Geld verbunden ist; sie ist vielmehr noch der Person inhärent und hängt von einer Art religiöser Ehrfurcht ab, die sie erweckt; sie macht sich durch Prunk und Pracht oder eine zahlreiche Schar treuer Gefolgsleute bemerkbar. Das feudale oder hierarchische Denken drückt die Idee der Größe durch sichtbare Zeichen aus\...“ [^117] Da die Menschen im Spätmittelalter vor allem an ihren Status dachten, waren sie nicht darauf vorbereitet, dass Kaufleute irgendetwas Wichtiges zum Leben des Reiches beitragen könnten. Die Kaufleute waren fast ausnahmslos Bürgerliche. Sie standen am unteren Ende der drei Stände, unterhalb des Adels und des Klerus.

Selbst die scharfsinnigeren Denker der spätmittelalterlichen Gesellschaft erkannten nicht die Bedeutung des Handels und anderer Formen des Unternehmertums außerhalb der Landwirtschaft für die Anhäufung von Reichtum. Für sie war die Armut eine apostolische Tugend. Sie machten buchstäblich keinen Unterschied zwischen einem wohlhabenden Bankier und einem Bettler. In Huizingas Worten: „Im dritten Stand wurde im Prinzip weder zwischen reichen und armen Bürgern noch zwischen Stadt- und Landbewohnern unterschieden“.[^118] Weder Beruf noch Reichtum spielten in ihrem System eine Rolle, sondern lediglich der ritterliche Status.

Diese Blindheit gegenüber der wirtschaftlichen Dimension des Lebens wurde von den Kirchenmännern verstärkt, die die ideologischen Hüter des mittelalterlichen Lebens waren. Sie waren so weit davon entfernt, die Bedeutung des Handels zu begreifen, dass ein weithin beachtetes Reformprogramm aus dem 15. Jahrhundert vorschlug, alle Personen ohne adligen Status sollten sich ausschließlich dem Handwerk oder der Landarbeit widmen. Für den Handel war überhaupt keine Rolle vorgesehen.[^119]

> „Das Datum 1492, das üblicherweise verwendet wird, um die mittelalterliche von der neuzeitlichen Geschichte zu trennen, eignet sich so gut wie jeder andere Trennungspunkt, denn in der Perspektive der Weltgeschichte symbolisiert die Reise von Kolumbus den Beginn einer neuen Beziehung zwischen Westeuropa und dem Rest der Welt.“ [^120] - Frederic C. Lane

## DIE GEBURT DES INDUSTRIEZEITALTERS

Viele der schärfsten Köpfe des fünfzehnten Jahrhunderts haben eine der wichtigsten Entwicklungen der Geschichte, die vor ihren Augen begann, völlig übersehen. Der Untergang des Feudalismus markiert den Beginn der großen modernen Phase der westlichen Vorherrschaft. Es war eine Zeit, in der die Rendite der Gewalt und die Größe der Unternehmen zunahmen. In den letzten zweieinhalb Jahrhunderten hat die moderne Wirtschaft dem Teil der Welt, der am meisten von ihr profitierte, einen beispiellosen Anstieg des Lebensstandards beschert. Die Katalysatoren für diese Veränderungen waren neue Technologien, von Schießpulverwaffen bis zur Druckerpresse, die die Grenzen des Lebens auf eine Weise veränderten, die nur wenige begreifen konnten.

Im letzten Jahrzehnt des fünfzehnten Jahrhunderts begannen Entdecker wie Kolumbus gerade erst, den Zugang zu riesigen, unbekannten Kontinenten zu eröffnen. Zum ersten Mal in der langen Geschichte der Menschheit wurde die ganze Welt umsegelt. Galeonen, neue, hochmastige Improvisationen der mediterranen Galeeren, umrundeten den Globus und kartographierten die Passagen, die zu Handelswegen und Durchgangsstraßen für Krankheiten und Eroberungen werden sollten. Konquistadoren, die ihre neuen Bronzekanonen zu Wasser und zu Lande einsetzten, eröffneten neue Horizonte. Sie fanden Reichtümer in Gold und Gewürzen, pflanzten die Saat für neue Nutzpflanzen, von Tabak bis Kartoffeln, und steckten neue Weideflächen für ihr Vieh ab.

### Die erste industrielle Technologie

So wie die Kanone neue wirtschaftliche Horizonte eröffnete, eröffnete die Druckerpresse neue geistige Horizonte. Sie war die erste Maschine für die Massenproduktion, eine charakteristische Technologie, die den Beginn der Industrialisierung markierte. Damit teilen wir die Ansicht von Adam Smith in Der Wohlstand der Nationen, dass die industrielle Revolution bereits lange vor seiner Niederschrift stattgefunden hat. Sie war zwar noch nicht ausgereift, aber die Prinzipien der Massenproduktion und des Fabriksystems waren bereits etabliert. Sein berühmtes Beispiel der Stecknadelhersteller verdeutlicht dies. Smith erklärt, wie achtzehn verschiedene Arbeitsgänge zur Herstellung von Stecknadeln eingesetzt werden. Aufgrund der spezialisierten Technik und der Arbeitsteilung konnte jeder Mitarbeiter an einem Tag 4.800 mal mehr Stecknadeln herstellen als ein Einzelner.[^121]

Smiths Beispiel unterstreicht die Tatsache, dass die industrielle Revolution Jahrhunderte früher begann, als die Historiker üblicherweise annehmen. Die meisten Lehrbücher datieren ihre Anfänge auf die Mitte des achtzehnten Jahrhunderts. Das ist als Datum für die Startphase der Verbesserung des Lebensstandards nicht unangemessen. Der eigentliche megapolitische Übergang vom Feudalismus zum Industrialismus begann jedoch schon viel früher, nämlich Ende des fünfzehnten Jahrhunderts. Seine Auswirkungen zeigten sich fast unmittelbar in der Umwandlung der herrschenden Institutionen, insbesondere in der Verfinsterung der mittelalterlichen Kirche.

Die Historiker, die die Industrielle Revolution später ansetzen, messen in Wirklichkeit etwas anderes, nämlich den Anstieg des Lebensstandards, der auf die von Maschinen angetriebene Massenproduktion zurückzuführen ist. Dadurch stieg der Wert ungelernter Arbeit und die Preise für eine Vielzahl von Konsumgütern sanken. Die Tatsache, dass der Lebensstandard in den verschiedenen Ländern zu unterschiedlichen Zeiten stark anstieg, ist ein Hinweis darauf, dass etwas anderes gemessen wird als der Übergang zur Megapolitik. Die Cambridge Economic History of Europe spricht von „Industriellen Revolutionen“ im Plural und verbindet sie ausdrücklich mit dem anhaltenden Wachstum der nationalen Einkommen.[^122] In Japan und Russland verzögerte sich dieser Einkommensanstieg bis zum Ende des 19. Jahrhunderts. Der Anstieg des Lebensstandards und das nachhaltige Wachstum des Volkseinkommens in anderen Teilen Asiens und einigen Teilen Afrikas war ein Phänomen des 20. Jahrhunderts. In einigen Teilen Afrikas ist ein nachhaltiges Wachstum bis heute ein Traum geblieben. Das bedeutet jedoch nicht, dass diese Regionen nicht in der Moderne leben.

### Sinkende Einkommen im Wandel

Das Einkommenswachstum ist nicht gleichbedeutend mit dem Beginn der Industrialisierung. Der Übergang zur Industriegesellschaft war ein megapolitisches Ereignis, das in den Einkommensstatistiken nicht direkt messbar ist. In der Tat sanken die Realeinkommen der meisten Europäer in den ersten beiden Jahrhunderten des Industriezeitalters. Sie begannen erst nach Beginn des achtzehnten Jahrhunderts zu steigen und erreichten erst um 1750 wieder das Niveau von 1250. Wir datieren den Beginn des Industriezeitalters auf das Ende des fünfzehnten Jahrhunderts. Es waren die industriellen Merkmale der frühmodernen Technologie, einschließlich chemisch betriebener Waffen und Druckerpressen, die den Zusammenbruch des Feudalismus auslösten.

### Senkung der Kosten des Wissens

Die Fähigkeit zur Massenproduktion von Büchern war für die mittelalterlichen Institutionen unglaublich subversiv, so wie sich die Mikrotechnologie für den modernen Nationalstaat als subversiv erweisen wird. Der Druck untergrub rasch das Monopol der Kirche auf das Wort Gottes, während er gleichzeitig einen neuen Markt für Ketzerei schuf. Ideen, die der geschlossenen Feudalgesellschaft zuwiderliefen, verbreiteten sich rasch, und bis zum letzten Jahrzehnt des fünfzehnten Jahrhunderts wurden 10 Millionen Bücher veröffentlicht. Da die Kirche versuchte, den Buchdruck zu unterdrücken, wurden die meisten neuen Bücher in den Gebieten Europas veröffentlicht, in denen der Einfluss der etablierten Autorität am schwächsten war. Dies könnte eine enge Analogie zu den heutigen Versuchen der US-Regierung sein, die Verschlüsselungstechnologie zu unterdrücken. Die Kirche stellte fest, dass die Zensur die Verbreitung subversiver Technologien nicht unterdrückte, sondern lediglich dafür sorgte, dass sie in ihrer subversivsten Form eingesetzt wurden.

### Der Verfall der Klöster

Viele scheinbar harmlose Verwendungen der Druckerpresse waren aufgrund ihres Inhalts subversiv. Allein die Verbreitung des Wissens über die Vermögen, die unerschrockene Abenteurer und Kaufleute verdienen konnten, war ein starkes Lösungsmittel, das die Fesseln der feudalen Verpflichtungen auflöste. Die Verlockung neuer Märkte sowie die Notwendigkeit und Möglichkeit, Armeen und Flotten in großem Umfang zu finanzieren, verliehen dem Geld einen Wert, der ihm in den feudalen Jahrhunderten gefehlt hatte. Diese neuen Investitionsmöglichkeiten, verstärkt durch mächtige Waffen, die den Ertrag der Gewalttätigkeit erhöhten, machten es für den Grundherrn im Hinterland oder den Kaufmann in der Stadt immer kostspieliger, sein Kapital der Kirche zu spenden. So destabilisierte die Schaffung von Investitionsmöglichkeiten außerhalb des Grundbesitzes die Institutionen des Feudalismus und untergrub seine Ideologie.

Eine weitere subversive Folge des Buchdrucks war die drastische Senkung der Kosten für die Vervielfältigung von Informationen. Ein wesentlicher Grund dafür, dass die Alphabetisierung und der wirtschaftliche Fortschritt im Mittelalter so gering waren, waren die hohen Kosten für die Vervielfältigung von Manuskripten von Hand. Wie wir gesehen haben, war die Vervielfältigung von Büchern und Manuskripten in den Benediktinerklöstern eine der wichtigsten produktiven Aufgaben, die die Kirche nach dem Fall Roms übernahm. Dies war ein äußerst kostspieliges Unterfangen. Eine der dramatischsten Folgen des Buchdrucks war die Entwertung der Skriptorien, in denen die Mönche Tag für Tag, Monat für Monat arbeiteten, um Manuskripte zu erstellen, die mit Hilfe von Druckerpressen innerhalb von Stunden vervielfältigt werden konnten. Die neue Technologie machte das benediktinische Skriptorium zu einem veralteten und kostspieligen Mittel der Wissensvervielfältigung. Dadurch verloren die religiösen Orden und die Kirche, die die Schreiber unterstützten, an wirtschaftlicher Bedeutung.

Die Massenproduktion von Büchern beendete das Monopol der Kirche auf die Heilige Schrift wie auch auf andere Formen der Information. Die größere Verfügbarkeit von Büchern senkte die Kosten für die Alphabetisierung und vervielfachte so die Zahl der Denker, die in der Lage waren, ihre eigene Meinung zu wichtigen Themen, insbesondere zu theologischen Themen, zu äußern. Wie der Theologiehistoriker Euan Cameron es ausdrückt, legte „eine Reihe von Meilensteinen im Verlagswesen“ in den ersten beiden Jahrzehnten des sechzehnten Jahrhunderts den Grundstein für die Anwendung der „modernen Textkritik auf die Heilige Schrift“.[^123] Dies „bedrohte das Monopol“ der Kirche, „indem es korrupte Lesarten von Texten in Frage stellte, die zur Stützung traditioneller Dogmen verwendet worden waren.“ [^124] Dieses neue Wissen förderte die Entstehung konkurrierender protestantischer Sekten, die versuchten, ihre eigenen Interpretationen der Bibel zu formulieren. Die Massenproduktion von Büchern senkte die Kosten der Ketzerei und verschaffte den Häretikern ein großes Publikum von Lesern.

Auch das Verlagswesen trug zur Zerstörung des mittelalterlichen Weltbildes bei. Die größere Verfügbarkeit und die niedrigeren Kosten für Informationen führten zu einer Abkehr von einem Weltbild, das eher durch Symbolik als durch kausale Zusammenhänge verbunden war. „Das symbolische Weltbild zeichnet sich durch tadellose Ordnung, architektonische Struktur und hierarchische Unterordnung aus. Denn jede symbolische Verbindung impliziert einen Unterschied im Rang oder in der Heiligkeit\.... Die Walnuss bedeutet Christus; der süße Kern ist seine göttliche Natur, die grüne und breiige äußere Schale ist seine Menschlichkeit, die hölzerne Schale dazwischen ist das Kreuz. So erheben alle Dinge die Gedanken auf das Ewige\...“ [^125]

Eine symbolische Denkweise passte nicht nur zu einer hierarchischen Gesellschaftsstruktur, sondern auch zum Analphabetismus. Ideen, die durch Symbole in Holzschnitten vermittelt wurden, waren für eine ungebildete Bevölkerung zugänglich. Im Gegensatz dazu führte das Aufkommen des Buchdrucks in der Neuzeit dazu, dass eine gebildete Bevölkerung kausale Zusammenhänge mit Hilfe der wissenschaftlichen Methode entwickeln konnte.

## EINE PARALLELE ZU HEUTE

Die mittelalterliche Gesellschaft, die in der Mitte des fünfzehnten Jahrhunderts scheinbar so stabil und sicher in ihrem Glauben war, wandelte sich rasch. Ihre wichtigste Institution, die Kirche, sah ihre Monopolstellung in Frage gestellt und erschüttert. Die Autorität, die jahrhundertelang unangefochten war, wurde plötzlich in Frage gestellt. Überzeugungen und Loyalitäten, die heiliger waren als die, die heute jeden Bürger an einen Nationalstaat binden, wurden innerhalb weniger Jahre überdacht und aufgegeben, und das alles aufgrund einer technologischen Revolution, die im letzten Jahrzehnt des 15. Jahrhunderts ihren Lauf nahm.

Wir glauben, dass sich ein ähnlich dramatischer Wandel wie vor fünfhundert Jahren wiederholen wird. Die Informationsrevolution wird das Machtmonopol des Nationalstaates ebenso sicher zerstören wie die Schießpulverrevolution das Monopol der Kirche. Es besteht eine auffällige Analogie zwischen der Situation am Ende des fünfzehnten Jahrhunderts, als das Leben durch und durch von der organisierten Religion durchdrungen war, und der heutigen Situation, in der die Welt von der Politik durchdrungen ist. Die Kirche von damals und der Nationalstaat von heute sind beides Beispiele für Institutionen, die sich zu einem altersschwachen Extrem entwickelt haben. Wie die spätmittelalterliche Kirche ist auch der Nationalstaat am Ende des zwanzigsten Jahrhunderts eine hoch verschuldete Institution, die ihren Lebensunterhalt nicht mehr bestreiten kann. Seine Aktivitäten werden immer irrelevanter und sind sogar kontraproduktiv für den Wohlstand derjenigen, die vor nicht allzu langer Zeit noch zu seinen treuesten Anhängern zählten.

### „Verarmt, habgierig und verschwenderisch“

Genauso wie der Staat heute einen schlechten Gegenwert für das eingenommene Geld bietet, tat dies die Kirche am Ende des fünfzehnten Jahrhunderts. Der Kirchenhistoriker Euan Cameron drückt es so aus: „Eine verarmte lokale Priesterschaft schien für das Geld, das sie verlangte, einen schlechten Dienst zu leisten; ein Großteil der Abgaben ‚verschwand' in geschlossenen Klöstern oder in den geheimnisvollen Bereichen der höheren Bildung oder der Verwaltung. Trotz der üppigen Schenkungen an einige Bereiche der Kirche gelang es der Institution als Ganzes, gleichzeitig verarmt, habgierig und verschwenderisch zu erscheinen.“ [^126] Die Parallele zur Regierung des späten zwanzigsten Jahrhunderts lässt sich nur schwer leugnen.

Im späten fünfzehnten Jahrhundert wuchsen die religiösen Observanzen wie heute die Programme in den Wohlfahrtsstaaten. Nicht nur, dass sich besondere Segnungen endlos vervielfachten, ebenso wie der Vorrat an Heiligen und Heiligengebeinen, es gab auch jedes Jahr mehr Kirchen, mehr Klöster, mehr Konvente, mehr Ordensgemeinschaften, mehr Beichtväter (ansässige Hauspriester), mehr Predigerstellen, mehr Domkapitel, mehr gestiftete Kantoreien, mehr Reliquienkulte, mehr religiöse Bruderschaften, mehr religiöse Feste und neue heilige Tage. Die Gottesdienste wurden länger. Gebete und Hymnen wurden immer komplizierter. Nacheinander tauchten neue Bettelorden auf, die um Almosen baten. Das Ergebnis war eine institutionelle Überlastung, die derjenigen ähnelte, die heute stark politisierte Gesellschaften kennzeichnet.

Religiöse Feste und Feiertage wuchsen auf allen Seiten. Die Gottesdienste wurden zahlreicher, mit besonderen Festen zu Ehren der sieben Schmerzen Mariens, ihrer Schwestern und aller Heiligen aus dem Stammbaum Jesu.[^127] Für die Gläubigen wurde die Erfüllung ihrer religiösen Pflichten immer kostspieliger und beschwerlicher, ähnlich wie die Kosten für die Einhaltung des Gesetzes heute gestiegen sind.

### Die Zahlungslasten der Unschuldigen

Damals wie heute trugen die Produktiven eine wachsende Last der Einkommensumverteilung. Diese Kosten stiegen stärker als von den Verantwortlichen erkannt, weil sich die Nutzung des Kapitals verschob. Der relative Vorteil des Landbesitzes gegenüber dem Geldkapital nahm ab. Dennoch dachte man im Mittelalter weiterhin in Begriffen einer statusgebundenen Gesellschaft, in der die soziale Stellung dadurch bestimmt wurde, wer man war, und nicht durch die Fähigkeit, das Kapital effektiv einzusetzen. Die steigenden Opportunitätskosten, die mit der Inszenierung übertriebener religiöser Observanzen verbunden waren, wurden kaum oder gar nicht berücksichtigt. Diese Kosten trafen vor allem die ehrgeizigeren und fleißigeren Bauern, Bürger und Freibauern, die mehr als der Adel darauf angewiesen waren, ihr Kapital nutzbringend einzusetzen. Sie mussten einen unverhältnismäßig großen Teil der Kosten für die Ausstattung der Tische bei den endlosen Festen und Feiertagen sowie für den Unterhalt einer verschwenderischen Kirchenbürokratie aufbringen.

### Kontraproduktive Regulierung

Am Ende des fünfzehnten Jahrhunderts kontrollierte die Kirche weitgehend die Regelungsbefugnisse, die seither von den Regierungen übernommen wurden. Die Kirche beherrschte wichtige Rechtsbereiche, indem sie Urkunden ausstellte, Ehen registrierte, Testamente unterzeichnete, Gewerbe zuließ, Grundstücke überschrieb und die Bedingungen für den Handel festlegte. Die Einzelheiten des Lebens wurden durch das Kirchenrecht fast ebenso gründlich geregelt wie heute durch die Bürokratie, und zwar mit demselben Ziel. So wie die politische Regulierung heute von Verwirrungen und Widersprüchen durchsetzt ist, so war es auch das Kirchenrecht vor fünfhundert Jahren. Diese Vorschriften unterdrückten und verkomplizierten den Handel oft auf eine Art und Weise, die erkennen ließ, dass die Erleichterung der Produktivität nicht im Sinne der Regulierer war.

So war es beispielsweise ein ganzes Jahr lang verboten, Geschäfte an dem Wochentag zu tätigen, auf den der letzte achtundzwanzigste Dezember fiel. Fiel dieser Tag auf einen Dienstag, so durften dienstags keine Geschäfte getätigt werden, da dies ein obligatorischer Ausdruck der Frömmigkeit zu Ehren der Schlachtung der Unschuldigen war. In den Jahren, in denen der 28. Dezember auf einen anderen Tag als einen Sonntag fiel, behinderte diese Vorschrift viele Arten des Handels und erhöhte die Kosten, indem sie Transaktionen verzögerte oder gänzlich verhinderte.

### Monopolpreisbildung

Das Kirchenrecht wurde auch zur Stärkung der Monopolpreise eingeführt. Die Kirche erzielte beträchtliche Einnahmen aus dem Verkauf von Alaun, der auf ihren Grundstücken in Tolfa, Italien, abgebaut wurde. Als einige ihrer Kunden in der Textilindustrie den billigeren, aus der Türkei importierten Alaun bevorzugten, versuchte der Vatikan, seine Monopolpreise durch das Kirchenrecht aufrechtzuerhalten, indem er die Verwendung des billigeren Alauns für sündhaft erklärte. Händler, die darauf bestanden, das billigere türkische Produkt zu kaufen, wurden exkommuniziert. Das berühmte Verbot, am Freitag Fleisch zu essen, entsprang demselben Geist. Die Kirche war nicht nur der größte feudale Grundbesitzer, sondern besaß auch bedeutende Fischereien. Die Kirchenväter entdeckten eine theologische Notwendigkeit für die Frommen, Fisch zu essen, was nicht zuletzt die Nachfrage nach ihrem Produkt zu einer Zeit sicherte, in der die Transport- und Hygienebedingungen vom Fischkonsum abrieten.

Wie der heutige Nationalstaat regulierte die spätmittelalterliche Kirche nicht nur bestimmte Wirtschaftszweige, um ihre eigenen Interessen direkt zu unterstützen, sondern sie nutzte ihre Regulierungsbefugnisse auch, um sich auf andere Weise Einnahmen zu verschaffen. Die Kleriker gaben sich besondere Mühe, Vorschriften und Edikte zu erlassen, die nur schwer zu befolgen waren. So wurde beispielsweise der Begriff Inzest sehr weit gefasst, so dass selbst entfernte Cousins und Personen, die nur durch Heirat miteinander verwandt waren, eine Sondergenehmigung der Kirche benötigten, um zu heiraten. Da dies in vielen kleinen europäischen Dörfern vor dem Zeitalter des modernen Reisens fast jeden betraf, wurde der Verkauf von Befreiungen für inzestuöse Ehen zu einer florierenden Einnahmequelle der Kirche. Sogar der Sex in der Ehe selbst war durch kirchliche Vorschriften stark eingeschränkt. Sexuelle Beziehungen zwischen Ehepartnern waren sonntags, mittwochs und freitags sowie in den vierzig Tagen vor Ostern und Weihnachten verboten. Außerdem mussten sich die Eheleute vor dem Empfang der Kommunion drei Tage lang des Geschlechtsverkehrs enthalten. Mit anderen Worten: Ehepaaren war es verboten, an mindestens 55 Prozent der Tage im Jahr ohne Ablass Sex zu haben. In The Bishop\'s Brothels (Die Bordelle des Bischofs) legt der Historiker E. J. Burford nahe, dass diese „idiotischen“ Vorschriften für die Ehe dazu beitrugen, das Wachstum der mittelalterlichen Prostitution anzukurbeln, wovon die Kirche mächtig profitierte.[^128] Burford berichtet, dass der Bischof von Winchester viele Jahrhunderte lang der Direktor der Londoner Bankside-Bordelle in Southwark war. Außerdem war der kirchliche Profit aus der Prostitution keineswegs nur eine lokale englische Angelegenheit:

> Papst Sixtus IV. (ca. 1471), der sich angeblich bei einer seiner zahlreichen Mätressen mit Syphilis angesteckt hatte, war der erste Papst, der Lizenzen für Prostituierte ausstellte und eine Steuer auf deren Einkünfte erhob, wodurch sich die päpstlichen Einnahmen beträchtlich vermehrten. In der Tat finanzierte die römische Kurie den Bau des Petersdoms teilweise durch diese Steuer und den Verkauf von Lizenzen. Sein Nachfolger, Papst Leo X., soll durch den Verkauf von Lizenzen etwa zweiundzwanzigtausend Golddukaten eingenommen haben, viermal so viel wie durch den Verkauf von Ablassbriefen in Deutschland.[^129]

Selbst die berühmte Zölibatsregel, die den Priestern auferlegt wurde, war eine lukrative Einnahmequelle für die mittelalterliche Kirche. Wie Burford berichtet, verhängte die Kirche „eine Gaunerei, die als cullagium bekannt ist“, eine Gebühr, die „konkubinären Priestern“ auferlegt wurde.[^130] Dies erwies sich als so lukrativ, dass sie von den Bischöfen in Frankreich und Deutschland einheitlich allen Priestern auferlegt wurde, obwohl das Laterankonzil 1215 „diesen schändlichen Handel, durch den solche Prälaten regelmäßig die Erlaubnis zur Sünde verkaufen“ angeprangert hatte.[^131] Es handelte sich lediglich um einen von vielen lukrativen Märkten für den Verkauf von Lizenzen zur Verletzung des kanonischen Rechts und der kirchlichen Vorschriften, ein Handel, der von der gleichen Logik motiviert war, die habgierige Politiker dazu treibt, willkürliche Regulierungsbefugnisse über den Handel anzustreben.

### Ablässe

Die Befugnis, willkürlich zu regulieren, ist auch die Befugnis, eine Befreiung von dem Schaden zu verkaufen, den solche Regulierungen anrichten können. Die Kirche verkaufte Genehmigungen oder „Ablässe“, die alles erlaubten, von der Befreiung von geringfügigen Belastungen des Handels bis zur Erlaubnis, in der Fastenzeit Milchprodukte zu essen. Diese „Ablässe“ wurden nicht nur zu hohen Preisen an den Adel und die reichen Bürger verkauft. Sie wurden auch als Lotteriepreise verpackt, ähnlich wie die staatlichen Lotterien von heute, um die Pfennige der Armen anzulocken.[^132] Der Handel mit Ablassbriefen nahm zu, als die Ausgaben der Kirche ihre Einnahmen überstiegen. Daraus schlossen viele auf das Offensichtliche, dass die institutionelle Kirche ihre Macht in erster Linie dazu nutzte, Einnahmen zu erzielen. Ein zeitgenössischer Kritiker drückte es so aus: „Das Kirchenrecht wurde einzig und allein zu dem Zweck eingeführt, viel Geld zu verdienen; wer ein Christ sein will, muss sich von seinen Bestimmungen freikaufen.“ [^133]

### Bürokratische Überlast

Die Kosten für die Unterstützung der institutionalisierten Religion hatten am Ende des fünfzehnten Jahrhunderts ein historisches Extrem erreicht, ähnlich wie die Kosten für die Unterstützung der Regierung heute ein altersschwaches Extrem erreicht haben. Je mehr das Leben von der Religion gesättigt war, desto teurer und bürokratischer wurde die Kirche. In Camerons Worten: „Es war viel einfacher, Menschen zu finden, die die enorm gestiegene Zahl der kirchlichen Ämter am Ende des Mittelalters besetzen konnten, als Geld zu finden, um sie zu bezahlen.“ [^134] So wie bankrotte Regierungen heute auf kontraproduktive Weise nach Einnahmen suchen, tat dies die Kirche vor fünfhundert Jahren. In der Tat bedienten sich die Kirchenmänner einiger der gleichen räuberischen Tricks, die die Politiker heute beherrschen.

Die mittelalterliche Kirche vor fünfhundert Jahren verbrauchte ebenso wie der heutige Nationalstaat mehr Ressourcen der Gesellschaft als je zuvor und jemals wieder. Die Kirche schien damals, wie der Staat heute, selbst mit Rekordeinnahmen nicht in der Lage zu sein zu funktionieren und sich selbst zu erhalten. So wie der Staat die spätindustriellen Volkswirtschaften dominiert und in einigen westeuropäischen Ländern mehr als die Hälfte aller Einnahmen ausgibt, so dominierte die Kirche die spätfeudale Wirtschaft, verschlang Ressourcen und bremste das Wachstum.

### Defizit-Ausgaben im fünfzehnten Jahrhundert

Die Kirche griff zu allen erdenklichen Mitteln, um mehr Geld aus ihren Einnahmen herauszupressen und ihre überbordende Bürokratie zu füttern. Die Regionen, die direkt der Kirche unterstellt waren, mussten immer höhere Steuern zahlen. In Provinzen und Königreichen, in denen die Kirche keine direkte Besteuerungsbefugnis besaß, erließ der Vatikan „Annaten“, eine Zahlung, die der örtliche Herrscher anstelle der direkten Kirchensteuern zu leisten hatte.

Wie heute der Staat, so plünderte auch die Kirche ihre eigenen Kassen, indem sie Gelder aus zweckgebundenen Wohltaten zur Deckung allgemeiner Gemeinkosten abzweigte. Benefizien und käufliche religiöse Ämter wurden offen verkauft, ebenso wie die Einnahmen aus dem Zehnten. In der Tat wurden die Zinsen auf den Zehnten zum kirchlichen Äquivalent der Anleihen, die von modernen Regierungen zur Finanzierung ihrer chronischen Defizite ausgegeben wurden.

Während die Kirche als ideologische Verteidigerin des Feudalismus und Kritikerin von Handel und Kapitalismus auftrat, bediente sie sich, wie heute der Nationalstaat, jeder verfügbaren Marketingtechnik, um ihre eigenen Einnahmen zu optimieren. Die Kirche betrieb ein florierendes Geschäft mit dem Verkauf von Sakramentalien, darunter geweihte Kerzen, Palmen, die am Palmsonntag gesegnet wurden, „Kräuter, die am Fest Mariä Himmelfahrt gesegnet wurden, und vor allem die verschiedenen Arten von Weihwasser.“ [^135]

Ähnlich wie heutige Politiker, die ihren Wählern mit der Einschränkung der Müllabfuhr und anderen Demütigungen drohen, wenn sie sich weigern, höhere Steuern zu zahlen, neigten auch religiöse Autoritäten im fünfzehnten Jahrhundert dazu, Gottesdienste zu unterbrechen, um Gemeinden zur Zahlung willkürlicher Geldstrafen zu erpressen. Oft wurden die Bußgelder für ein geringfügiges Vergehen einiger weniger Personen verhängt, die nicht einmal Mitglieder der betreffenden Gemeinde gewesen sein mussten. Im Jahr 1436 schloss Bischof Jacques Du Chatelier, „ein sehr prahlerischer und habgieriger Mann“, die Kirche der Unschuldigen in Paris für zweiundzwanzig Tage und unterbrach alle Gottesdienste, um auf die Zahlung einer unvorstellbar hohen Geldstrafe durch zwei Bettler zu warten. Die Männer hatten sich in der Kirche gestritten und einige Blutstropfen vergossen, von denen der Bischof behauptete, sie hätten die Kirche entweiht. Er erlaubte niemandem, die Kirche für Hochzeiten, Beerdigungen oder die normalen Sakramente des Kalenders zu benutzen, bis die Geldstrafe bezahlt war.[^136]

> Die italienischen Stewes (um zu bringen dem Papst seinen Spaß)\
> zahlten gar zwanzigtausend Dukaten während eines Jahrs.\
> Außerdem geben sie einem Priester (in die Tasche hinein)\
> den Profit einer Hure, vielleicht auch von zweien oder dreien\....\
> Mich dünkt, es muss bald eine Pause machen\
> wer es mit den Stewes derartig lässt krachen.[^137]
>
> \- Englische Ballade des fünfzehnten Jahrhunderts

### Hass auf Kirchenführer

Kein Wunder, dass die allgemeine Meinung des späten fünfzehnten Jahrhunderts den höheren und niederen Klerus verachtete, so wie die allgemeine Meinung in hoch politisierten Gesellschaften heute die Bürokratie und die Politiker verachtet. Johan Huizinga drückte es so aus: „Hass ist das richtige Wort in diesem Zusammenhang, denn der Hass war latent, aber allgemein und anhaltend. Das Volk wurde nicht müde, die Laster des Klerus anzuklagen.“ [^138] Die allgemeine Überzeugung, dass die Kirche „habgierig und verschwenderisch“ sei, war auch deshalb richtig, weil sie stimmte. „Die Weltlichkeit der höheren Ränge des Klerus und der Verfall der unteren Klassen“ [^139] waren zu offensichtlich, um sie zu übersehen. Vom Pfarrer bis zum Papst selbst scheint der Klerus korrupt zu sein, wie es nur das Personal einer herrschenden Institution sein kann.

Vor fünfhundert Jahren ließ Papst Alexander VI. sogar Giulio Andreotti und Bill Clinton wie Vorbilder der Integrität erscheinen. Alexander VI. war für seine wilden Partys berühmt. Als Kardinal in Siena veranstaltete er eine berühmte Orgie, zu der nur „die schönsten jungen Frauen Sienas eingeladen, ihre ‚Ehemänner, Väter und Brüder' aber ausgeschlossen waren.“ [^140] Die Orgie in Siena war berühmt, aber sie erwies sich später als zahm im Vergleich zu denen, die Alexander veranstaltete, nachdem er Papst wurde. Die vielleicht reißerischste dieser Orgien war das so genannte Kastanienballett, bei dem die „fünfzig schönsten Huren Roms“ in einen Kopulationswettbewerb mit den Kirchenvätern und anderen wichtigen Römern verwickelt waren. William Manchester beschreibt es so: „Die Diener führten Buch über die Orgasmen jedes Mannes, denn der Papst bewunderte die Potenz sehr\... Nachdem alle erschöpft waren, verteilte Seine Heiligkeit Preise - Mäntel, Stiefel, Mützen und feine seidene Tuniken. Die Gewinner, so notierte der Tagebuchschreiber, waren diejenigen, die am häufigsten mit den Kurtisanen geschlafen hatten.“ [^141]

Alexander zeugte mindestens sieben, vielleicht sogar acht uneheliche Kinder. Einer seiner angeblichen Söhne, Giovanni, war der so genannte Infans Romanus, der von Alexanders unehelicher Tochter Lucrezia Borgia geboren wurde, als diese achtzehn Jahre alt war. In einer geheimen päpstlichen Bulle gab Alexander zu, Giovanni gezeugt zu haben. Wenn er nicht der Vater war, war er mit Sicherheit der Großvater auf beiden Seiten. Der Papst war in eine inzestuöse Dreierbeziehung mit Lucrezia verwickelt, die auch die Geliebte von Juan, Herzog von Gandia, Alexanders ältestem unehelichen Sohn, sowie die Geliebte eines anderen unehelichen Sohnes, Kardinal Cesare Borgia, war. Cesare war der Kirchenfürst, der Niccolo Machiavelli als Inspiration für Der Fürst diente. Cesare war ein Mörder, ebenso wie der Papst, von dem bekannt war, dass er mehrere Morde geplant hatte. Der eine oder andere von ihnen wurde offenbar eifersüchtig auf Juan, dessen lebloser Körper am 15. Juni l497 aus dem Tiber gefischt wurde.[^142]

Die Führung der spätmittelalterlichen Kirche war ebenso korrupt wie die Führung des heutigen Nationalstaates.

> „Heute bin ich zweimal Vater geworden, mit dem Segen der Götter.“ [^143] - Rodolph Acricola, als er hörte, dass seine Konkubine an dem Tag, an dem er zum Abt gewählt wurde, einen Sohn zur Welt gebracht hatte.

## HEUCHELEI

Unter einer „oberflächlichen Kruste der Frömmigkeit“ war die spätmittelalterliche Gesellschaft bemerkenswert blasphemisch, respektlos und ausschweifend. Die Kirchen waren die bevorzugten Treffpunkte junger Männer und Frauen und häufige Treffpunkte von Prostituierten und Verkäufern obszöner Bilder. Historiker berichten, dass „die Respektlosigkeit der täglichen religiösen Praxis fast grenzenlos war.“ [^144] Chorsänger, die für die Seelen der Verstorbenen angeheuert wurden, ersetzten in der Regel profane Worte in der Messe. Vigilien und Prozessionen, die in der religiösen Praxis des Mittelalters eine weitaus größere Rolle spielten als heute, wurden dennoch „durch Schimpfworte, Spott und Trinkgelage entehrt.“ So sagte die führende theologische Autorität des spätmittelalterlichen Europas, Denis der Kartäuser.[^145]

Auch wenn man einen solchen Bericht als das Gezeter eines steifen Moralisten abtun könnte, so ist er doch nur einer von vielen Berichten, die das gleiche Bild zeichnen. Es gibt reichlich Grund zu der Annahme, dass das Unzüchtige und das Heilige im mittelalterlichen Leben häufig eng miteinander verbunden waren. Pilgerfahrten zum Beispiel arteten so oft in Krawall und Ausschweifungen aus, dass hochgesinnte Reformer erfolglos dafür plädierten, sie zu unterbinden. Auch lokale religiöse Prozessionen boten dem Mob regelmäßig Gelegenheit zu Vandalismus, Plünderungen und allgemein zu allen möglichen betrunkenen Vergnügungen. Selbst wenn die Menschen still saßen, um die Messe zu hören, war dies häufig keine nüchterne Erfahrung. Vor allem in den Festnächten wurden in der Kirche gewaltige Mengen Wein konsumiert. Aus Berichten des Straßburger Konzils geht hervor, dass die „Betenden“ in der St. Adolphus-Nacht 1.100 Liter Wein tranken, den das Konzil zu Ehren des Heiligen spendiert hatte.

Jean Gerson, ein bedeutender Theologe des 15. Jahrhunderts, berichtet, dass „die heiligsten Feste, sogar die Weihnachtsnacht mit Ausschweifungen, Kartenspielen, Fluchen und Gotteslästerung“ verbracht wurden. Wenn das gemeine Volk wegen dieser Verfehlungen „ermahnt wird, beruft es sich auf das Beispiel des Adels und des Klerus, die sich ungestraft in gleicher Weise verhalten.“ [^146]

### Frömmigkeit und Barmherzigkeit

Die Frömmigkeit, die im späten Mittelalter die Sättigung der Gesellschaft durch die organisierte Religion rationalisierte, diente demselben Zweck wie die „Barmherzigkeit“, die heute die politische Beherrschung des Lebens rechtfertigen soll. Der Verkauf von Ablassbriefen, zur Befriedigung des Wunsches nach Frömmigkeit ohne Moral, ist vergleichbar mit den verschwenderischen Ausgaben für die Wohlfahrt, die den Anschein von Barmherzigkeit ohne Wohltätigkeit erwecken sollen. Es war weitgehend unerheblich, ob die tatsächliche Wirkung der empfangenen Praktiken darin bestand, den moralischen Charakter zu verbessern oder Seelen zu retten, so wie es weitgehend unerheblich ist, ob ein Wohlfahrtsprogramm tatsächlich das Leben der Menschen verbessert, an die es gerichtet ist. „Frömmigkeit“ war ebenso wie „Barmherzigkeit“ eine fast abergläubische Beschwörung.

In einer Zeit, in der kausale Zusammenhänge kaum verstanden wurden, durchdrangen die Rituale und Sakramente der Kirche jede Phase des Lebens. „. . . Eine Reise, eine Aufgabe, ein Besuch waren gleichermaßen von tausend Formalitäten begleitet: Segnungen, Zeremonien, Formeln.“ [^147] Auf Pergamentstücke geschriebene Gebete wurden den Fieberkranken wie Halsketten umgehängt. Unterernährte Mädchen drapierten ihre Haarsträhnen vor dem Bild des Heiligen Urban, um weiteren Haarausfall zu verhindern. In Navarra zogen die Bauern in Prozessionen hinter einem Bild des Heiligen Petrus her, um bei Dürreperioden Regen zu erbitten.[^148] Diese und andere „unwirksame Techniken zur Linderung von Ängsten, wenn wirksame nicht zur Verfügung standen“, wurden von den Menschen eifrig angenommen.[^149]

### Zwei Unrechte für einen Ritus

Die Menschen waren so fest von den wundertätigen Eigenschaften der Reliquien von Heiligen überzeugt, dass der Tod einer besonders frommen Person häufig Anlass zu einem wahnsinnigen Ansturm auf die Teilung des Leichnams war. Nachdem Thomas von Aquin im Kloster Fossanuova gestorben war, enthaupteten die Mönche dort seinen Körper und kochten ihn, um in den Besitz seiner Gebeine zu gelangen. Als die heilige Elisabeth von Ungarn aufgebahrt war, „kam eine Schar von Verehrern und schnitt oder riss Streifen aus dem Leinen, das ihr Gesicht umhüllte; sie schnitten das Haar, die Nägel und sogar die Brustwarzen ab.“ [^150]

### Frömmigkeit ohne Tugend

Der mittelalterliche Geist betrachtete die Heiligen und ihre Reliquien als Teil des Arsenals des Glaubens in einer Welt, die im Winter kälter, nachts dunkler und angesichts von Krankheiten verzweifelter war, als jeder Leser dieses Buches wahrscheinlich je erlebt hat. Stärker als in der Neuzeit glaubten die Menschen im Mittelalter an die Existenz von Dämonen, an ein aktives Eingreifen Gottes in die Welt und daran, dass Gebet, Buße und Pilgerfahrten göttliche Gunst einbringen.

Einfach zu sagen, dass die Menschen an Gott glaubten, könnte weder die Intensität ihres Bekenntnisses noch die scheinbare Leichtigkeit vermitteln, mit der sich die mittelalterliche Frömmigkeit mit der Sünde zu arrangieren schien. Der Glaube an die Wirksamkeit von Riten, Ritualen und Sakramenten war so allgegenwärtig, dass er die Dringlichkeit eines tugendhaften Verhaltens vielleicht zwangsläufig untergrub. Für jede Sünde oder jeden geistigen Defekt gab es ein Heilmittel, eine Buße, die die Schiefertafel reinigte, was zu einer „Heilsmathematik“ wurde.[^151] Die Religion wurde so allgegenwärtig, dass ihre Aufrichtigkeit zwangsläufig zu schwinden begann. Wie Huizinga es formulierte: „Die Religion, die alle Beziehungen im Leben durchdringt, bedeutet eine ständige Vermischung der Sphären des heiligen und des profanen Denkens. Heilige Dinge werden zu gewöhnlich, um tief empfunden zu werden.“ [^152] Und so war es auch.

## VERKLEINERUNG DER KIRCHE

Am Ende des fünfzehnten Jahrhunderts war die Kirche nicht nur so korrupt wie heute der Nationalstaat, sie war auch ein großer Hemmschuh für das Wirtschaftswachstum. Die Kirche verschlang große Mengen an Kapital auf unproduktive Weise, indem sie Lasten auferlegte, die die Leistung der Gesellschaft begrenzten und den Handel unterdrückten. Diese Belastungen waren ebenso zahlreich wie die, die der Nationalstaat heute auferlegt. Wir wissen, was mit der organisierten Religion im Gefolge der Schießpulverrevolution geschah: Sie schuf starke Anreize, die religiösen Institutionen zu verkleinern und ihre Kosten zu senken. Als die traditionelle Kirche sich weigerte, dies zu tun, ergriffen protestantische Sekten die Gelegenheit, um zu konkurrieren. Dabei setzten sie fast jedes erdenkliche Mittel ein, um die Kosten für ein frommes Leben zu senken:

- Sie bauten sparsame neue Kirchen und entfernten manchmal die Altäre älterer Kirchen, um Kapital für andere Zwecke freizusetzen.

- Sie revidierten die christliche Lehre in einer Weise, die die Kosten senkte, und betonten den Glauben gegenüber guten Taten als Schlüssel zur Erlösung.

- Sie entwickelten eine neue, knappe Liturgie, reduzierten oder schafften Festtage ab und schafften zahlreiche Sakramente ab.

- Sie schlossen Klöster und Nonnenklöster und hörten auf, Almosen an Bettelorden zu geben. Die Armut wurde von einer apostolischen Tugend zu einem unerwünschten und oft tadelnswerten sozialen Problem.[^153]

Um zu verstehen, wie die Verkleinerung der Kirche die Produktivität freigesetzt hat, muss man sich vor dem Brechen des Monopols der Kirche die zahlreichen Hindernisse vor Augen führen, die sie dem Wachstum in den Weg gelegt hat. Ähnlich wie heute der Nationalstaat erlegte die Kirche am Ende des fünfzehnten Jahrhunderts eine unglaubliche Last an überschüssigen Kosten auf.

1. Direkte Kosten wie Zehnten, Steuern und Gebühren finanzierten die ausufernde kirchliche Bürokratie. Der Zehnte war auch in den protestantischen Kirchen üblich, die die mittelalterliche „Heilige Mutter Kirche“ ablösten, aber in städtischen Gebieten war er in der Regel nicht zu erheben. Das Ende des kirchlichen Monopols führte dazu, dass die Grenzsteuersätze in den Regionen mit dem am stärksten entwickelten Handel sanken.

2. Religiöse Doktrinen machten das Sparen schwierig. Der Erzbösewicht der mittelalterlichen Kirche war der „Geizhals“, der sein Gold auf Kosten seiner Seele sparte. Die Forderung an die Gläubigen, „gute Taten“ zu finanzieren, hatte kostspielige Beiträge an die Kirche zur Folge. Die Lehre von den „Erfüllungen“ verpflichtete die um ihr Seelenheil Besorgten, Gottesdienste oder „Totenmessen“ zu stiften, um das Fegefeuer zu vermeiden. Luther griff dies in der achten und dreizehnten seiner fünfundneunzig Thesen direkt an. Er schrieb, dass „die Sterbenden alle ihre Schulden durch ihren Tod bezahlen werden.“ [^154] Mit anderen Worten: Das Kapital des protestantischen Gläubigen stand zur Verfügung, um es an seine Erben weiterzugeben. Nach der protestantischen Lehre brauchte man keine Kantoreien zu stiften, um Messen zu wiederholen, in der Regel für dreißig Jahre, und manchmal, bei sehr wohlhabenden Personen, für immer.

3. Die Ideologie der mittelalterlichen Kirche förderte auch die Umleitung von Kapital in den Erwerb von Reliquien. Zahlreiche Reliquienkulte wurden mit großen Summen ausgestattet, um physische Gegenstände zu erwerben, die mit Christus oder verschiedenen Heiligen in Verbindung gebracht wurden. Die sehr wohlhabenden Menschen legten sogar persönliche Reliquiensammlungen an. Kurfürst Friedrich von Sachsen beispielsweise trug eine Sammlung von neunzehntausend Reliquien zusammen, von denen er einige 1493 auf einer Pilgerreise nach Jerusalem erwarb. In seiner Sammlung befanden sich unter anderem, wie er glaubte, „der Leib einer heiligen Unschuldigen, die Milch Marias und Stroh aus dem Stall der Geburt Christi“.[^155] Vermutlich war die Rendite für das in diese Reliquien investierte Kapital gering. Die Verlagerung auf den Glauben und die Vorstellung von den Auserwählten verringerte die Bedeutung des Erwerbs von Gegenständen des christlichen Lebens, die als Amulette verwendet werden konnten, und ermutigte das Geld, produktivere Kanäle zu finden, die eine Rendite abwarfen, die der Monarch nutzen konnte.

4. Das Aufkommen der protestantischen Konfessionen brach die wirtschaftlichen Monopole der mittelalterlichen Kirche und führte zu einer erheblichen Schwächung der Regulierung. Wie wir gesehen haben, wurde das kanonische Recht häufig zur Unterstützung kirchlicher Monopole und wirtschaftlicher Interessen gebogen. Da die neuen Konfessionen weniger wirtschaftliche Interessen zu schützen und zu fördern hatten, führte ihre Version der religiösen Lehre tendenziell zu einem freieren System mit weniger Hemmungen für den Handel.

5. Die protestantische Revolution schaffte viele der Riten und Rituale der mittelalterlichen Kirche ab, die die Zeit der Gläubigen belasteten. Riten, Sakramente und heilige Tage waren so ausgearbeitet worden, dass sie im späten fünfzehnten Jahrhundert fast den gesamten Kalender ausfüllten. Diese zeremonielle Überfrachtung war eine logische Folge des Beharrens der Kirche darauf, „dass man Gebets- oder Gottesdiensthandlungen beliebig oft wiederholen und daraus Nutzen ziehen könne.“ [^156] Das taten sie auch. Die Produktivität wurde durch längere und aufwändigere Gottesdienste, durch die Verpflichtung, wiederholte Gebete zur Buße zu sprechen, und durch die zunehmende Zahl von Heiligenfesten, an denen nicht gearbeitet werden durfte, belastet. Zahlreiche Vorschriften und Zeremonien unterbrachen den Tag und die Jahreszeiten und schränkten die für produktive Aufgaben zur Verfügung stehende Zeit erheblich ein. Dies mag den Rhythmus der mittelalterlichen Landwirtschaft, in der 90 Prozent oder mehr der Bevölkerung tätig waren, kaum unterbrochen haben. Während der Jahreszeiten gab es viele Perioden, in denen die Feldarbeit nicht täglich erforderlich war. Die Ernteerträge schwankten unter mittelalterlichen Bedingungen wahrscheinlich mehr mit dem Wetter und unkontrollierbaren Schädlingsbefall als mit einer geringfügigen zusätzlichen Arbeit, die über das im Kirchenkalender vorgesehene Minimum hinausging.

    Das größere Problem der Produktivitätseinbußen betraf nicht so sehr die Landwirtschaft, sondern andere Bereiche. Die zeitlichen Anforderungen der Kirche waren weit weniger kompatibel mit dem Handwerk, der Industrie, dem Transportwesen, dem Handel oder anderen Unternehmen, bei denen Produktivität und Rentabilität entscheidend von der für die Aufgabe aufgewendeten Zeit bestimmt wurden.

    Es wird wohl kein Zufall sein, dass der große Übergang am Ende des 15. Jahrhunderts zu einer Zeit stattfand, in der die Grundstückspachten stiegen und die Reallöhne der Bauern sanken. Der zunehmende Bevölkerungsdruck hatte die Erträge des Gemeindelandes verringert, das oft in der Nähe von Flüssen und Bächen lag und von dem die Bauern für die Weidehaltung ihres Viehs und in einigen Fällen für Fisch und Brennholz abhängig waren. Die Verringerung des Lebensstandards setzte die Bauern zunehmend unter Druck, alternative Einkommensquellen zu finden. Infolgedessen „wandte sich ein immer größerer Teil der Landbevölkerung der Kleinproduktion für den Markt zu, vor allem der Textilherstellung, einem Prozess, der als ‚Auslagerung' oder ‚Protoindustrialisierung' bekannt ist“.[^157] Die von der Kirche auferlegten zeremoniellen Zeitlasten standen den Bemühungen der ehrgeizigeren Bauern im Wege, ihr bäuerliches Einkommen durch handwerkliche Arbeit aufzubessern, denn sie verhinderten jede Umschichtung der Anstrengungen in neue wirtschaftliche Richtungen.

    Einer der wichtigsten Beiträge der protestantischen Sekten zur Produktivität war die Abschaffung von vierzig Festtagen. Dies sparte nicht nur die beträchtlichen Kosten für die Durchführung der Feste, einschließlich der Ausstattung der Dorftische mit Speisen und Getränken, sondern setzte auch viel wertvolle Zeit frei. Jeder, der die vierzig verbannten Festtage nicht mehr feierte, konnte seine jährliche Produktivität um dreihundert oder mehr Arbeitsstunden erhöhen. Kurz gesagt, die Abschaffung der zeremoniellen Überlastung in der mittelalterlichen Kirche machte den Weg frei für eine beträchtliche Steigerung der Produktion, einfach dadurch, dass Zeit frei wurde, die sonst für den Handel verloren gegangen wäre.

6. Durch den Bruch des kirchlichen Monopols wurden große Mengen an Vermögenswerten freigesetzt, die unter kirchlicher Verwaltung nur geringe Renditen abwarfen - eine Situation, die offensichtliche Parallelen zu den staatlichen Betrieben Ende des 20. Jahrhunderts aufweist. Die Kirche war der mit Abstand größte feudale Grundbesitzer. Ihr Zugriff auf den Grund und Boden entsprach dem des Staates in stark politisierten Gesellschaften - in einigen europäischen Ländern wie Böhmen überstieg er 50 Prozent des gesamten Grundbesitzes. Nach kanonischem Recht konnte ein Grundstück, das einmal in den Besitz der Kirche übergegangen war, nicht mehr veräußert werden. So wuchs der kirchliche Grundbesitz stetig an, da die Kirche immer mehr testamentarische Schenkungen von den Gläubigen erhielt, um verschiedene soziale Einrichtungen, Kantoreien und andere Aktivitäten zu finanzieren.

    Obwohl es schwierig ist, die relative Produktivität der kirchlichen Betriebe genau zu messen, muss sie am Ende des Mittelalters weitaus geringer gewesen sein als in der ersten Hälfte dieser Epoche. Im vierzehnten Jahrhundert hatte die zunehmende Betonung der Produktion für den Markt gegenüber der Subsistenzlandwirtschaft dazu geführt, dass die meisten weltlichen Grundherren von ungebildeten Vorstehern zu professionellen Managern wurden, um den Ertrag ihrer Höfe zu optimieren. Ihre Anreize führten wahrscheinlich dazu, dass sie den Ertrag der kirchlichen Güter, der theoretisch niemandem zum privaten Gewinn gereicht hätte, schnell übertrafen. Zweifellos bewirtschafteten einige der weltlicheren Fürstbischöfe ihre Güter auf eine Art und Weise, die sich von derjenigen der weltlichen Herren nicht unterschied. Doch die Produktivität anderer kirchlicher Besitztümer hätte sicherlich unter den Fehlern einer gleichgültigen Verwaltung durch eine riesige, weit verstreute Institution gelitten, deren Nachteile den Nachteilen des staatlichen und kommunalen Eigentums heute ähnlich gewesen wären. Es liegt auch auf der Hand, dass die Beschlagnahmung der Klöster Ressourcen freisetzte, die nach dem Aufkommen des Buchdrucks nicht mehr für die Reproduktion von Büchern und Manuskripten benötigt wurden.

7. Wie wir in The Great Reckoning beschrieben haben, reagierten einige protestantische Sekten sofort auf die Schießpulverrevolution, indem sie ihre Lehren in einer Weise änderten, die den Handel förderte, z. B. durch die Aufhebung des Verbots des Wuchers oder der Kreditvergabe gegen Zinsen. Die ideologische Opposition der mittelalterlichen Kirche gegen den Kapitalismus war ein Hemmschuh für das Wachstum. Die ideologische Hauptstoßrichtung der kirchlichen Lehren bestand darin, den Feudalismus zu stärken, an dem die Kirche als größter Feudalgrundbesitzer einen großen Anteil hatte. Bewusst oder unbewusst neigte die Kirche dazu, aus ihren eigenen wirtschaftlichen Interessen religiöse Tugenden zu machen, während sie gegen die Entwicklung der Industrie und des unabhängigen kommerziellen Reichtums kämpfte, die dazu bestimmt waren, das feudale System zu destabilisieren. Die Verbote von „Avancen“ zum Beispiel galten hauptsächlich für Handelsgeschäfte und nicht für feudale Abgaben, und niemals für den Verkauf von Ablässen. Die berüchtigten Versuche der Kirche, einen „gerechten Preis“ für Waren im Handel festzulegen, führten dazu, dass die wirtschaftliche Rentabilität derjenigen Produkte und Dienstleistungen, bei denen die Kirche nicht selbst als Produzent auftrat, unterdrückt wurde.

    Das Verbot des „Wuchers“ war ein deutliches Beispiel für den Widerstand der Kirche gegen kommerzielle Innovationen. Banken und Kredite waren für die Entwicklung größerer Handelsunternehmen von entscheidender Bedeutung. Indem die Kirche die Verfügbarkeit von Krediten einschränkte, bremste sie das Wachstum.

8. Auf subtilere Weise trug die Konzentration der neuen Konfessionen auf die Bibel als Text dazu bei, sowohl die Denkweise der mittelalterlichen Kirche als auch ihre Ideologie zu zerstören. Beide stellten Hindernisse für das Wachstum dar. Die kulturelle Programmierung des späten Mittelalters ermutigte die Menschen, die Welt in Begriffen der symbolischen Ähnlichkeit zu sehen und nicht in Ursache und Wirkung. Dies führte zu einem Kurzschluss des Denkens. Es wies auch weg von einer kaufmännischen Auffassung des Lebens. Das Denken in symbolischen Äquivalenzen lässt sich nicht ohne Weiteres in ein Denken in Marktwerten übertragen. „Die drei Stände stehen für die Eigenschaften der Jungfrau. Die sieben Kurfürsten des Reiches stehen für die Tugenden; die fünf Städte des Artois und des Hennegau, die 1477 dem Haus Burgund treu blieben, sind die fünf klugen Jungfrauen... Ebenso stehen die Schuhe für Sorgfalt und Fleiß, die Strümpfe für Ausdauer, das Strumpfband für Entschlossenheit usw.“ [^158] Wie dieses Beispiel des bedeutenden mittelalterlichen Historikers Johan Huizinga andeutet, wurde das Denken von Dogmen, starren Symbolen und Allegorien beherrscht, die jeden Aspekt des Lebens im Sinne einer hierarchischen Unterordnung miteinander verbanden. Jeder Beruf, jedes Teil, jede Farbe, jede Zahl, sogar jedes Element der Grammatik war in ein großes System religiöser Vorstellungen eingebunden.

    So wurden die alltäglichen Dinge des Lebens nicht im Hinblick auf ihre kausalen Zusammenhänge, sondern in Form von statischen Symbolen und Allegorien gedeutet. Manchmal wurden Tugenden und Laster personifiziert, und jedes Ding stand für etwas, das wiederum für etwas anderes stand, und zwar auf eine Art und Weise, die Ursache und Wirkung oft eher blockierte als klärte. Um die Dinge noch weiter zu verwirren, wurden Beziehungen oft willkürlich in Zahlensystemen verknüpft. Die Sieben spielte dabei eine besonders wichtige Rolle. Es gab die sieben Tugenden, die sieben Todsünden, die sieben Bitten des Vaterunsers, die sieben Gaben des Heiligen Geistes, die sieben Momente der Passion, die sieben Seligpreisungen und die sieben Sakramente, „dargestellt durch die sieben Tiere und gefolgt von den sieben Krankheiten.“ [^159]

### Journalismus im fünfzehnten Jahrhundert

Eine Nachrichtensendung aus dem fünfzehnten Jahrhundert hätte, wenn sie denn geschrieben worden wäre, keine der klassischen Fragen der Tatsachenberichterstattung beantwortet, außer indirekt durch allegorische Personifizierung. Nehmen wir diesen Bericht in einem privaten Tagebuch über die Burgundermorde im Paris des fünfzehnten Jahrhunderts:

> Da erhob sich die Göttin der Zwietracht, die im Turm des bösen Rates wohnte, und erweckte den Zorn, das wahnsinnige Weib, und die Begierde und den Zorn und die Rache, und sie griffen zu den Waffen aller Art und vertrieben die Vernunft, die Gerechtigkeit, das Gedenken an Gott und die Mäßigung auf das schändlichste. Dann wütete der Wahnsinn, und Mord und Totschlag töteten, schlugen nieder, töteten, massakrierten alles, was sie in den Gefängnissen fanden. \... und Habgier steckte ihre Röcke in den Gürtel zusammen mit Vergewaltigung, ihrer Tochter, und Diebstahl, ihrem Sohn. \... Danach zogen die benannten Leute unter der Führung ihrer Göttinnen, nämlich des Zorns, der Habgier und der Rache, die sie durch alle öffentlichen Gefängnisse von Paris führten, usw.[^160]

Die Abkehr vom mittelalterlichen Paradigma trug dazu bei, die Menschen darauf vorzubereiten, in „modernen“ Begriffen über Ursache und Wirkung zu denken, statt in Begriffen symbolischer Verknüpfungen und allegorischer Personifikationen.

Man muss nicht behaupten, dass die Lehre und die Denkweise der spätmittelalterlichen Kirche unaufrichtig waren, um zu erkennen, dass sie sich eng an die Bedürfnisse des Agrarfeudalismus anlehnten und dem Handel, geschweige denn der industriellen Entwicklung, nur wenig Raum ließen. Vielmehr war es so, dass die Kirche als vorherrschende Institution moralische, kulturelle und rechtliche Zwänge in einer Weise formte, die eng an die Erfordernisse des Feudalismus angepasst war. Genau aus diesem Grund waren sie für die Bedürfnisse der Industriegesellschaft schlecht geeignet, so wie die moralischen, kulturellen und rechtlichen Zwänge des modernen Nationalstaates für die Erleichterung des Handels im Informationszeitalter schlecht geeignet sind. Wir glauben, dass der Staat ebenso wie die Kirche revolutioniert werden muss, um die Verwirklichung des neuen Potenzials zu ermöglichen.

Die protestantische Doktrin, dass der Himmel allein durch den Glauben und ohne den Nutzen gestifteter Gebete für die Toten erreicht werden kann, wurde als theologische Frage dargestellt. Doch es war eine Theologie, die den wirtschaftlichen Gegebenheiten eines neuen Zeitalters entsprach. Sie entsprach dem offensichtlichen Bedürfnis nach einem kosteneffizienteren Weg zum Heil in einer Zeit, in der die Opportunitätskosten, zusätzliches Kapital in die aufgeblähte kirchliche Bürokratie zu stecken, plötzlich gestiegen waren. Die Menschen störten sich weniger daran, ihr Geld der Kirche zu geben, wenn es keinen anderen Ausweg gab. Aber als sie plötzlich die Chance sahen, das Hundertfache ihres Kapitals für die Finanzierung einer Gewürzreise in den Osten zu bekommen oder mit einer geringeren, aber immer noch vielversprechenden Summe von 40 Prozent pro Jahr ein Bataillon für den König zu finanzieren, suchten sie verständlicherweise die Gnade Gottes dort, wo ihre eigenen Interessen lagen.

Viele Kaufleute und andere Bürgerliche wurden bald viel reicher, als es ihre Vorfahren im Feudalismus gewesen waren. Die drastische Erhöhung des Lebensstandards unter den Kaufleuten und kleinen Manufakturen in der frühen Neuzeit war bei denjenigen, deren Einkommen und Lebensweise mit dem Feudalismus zusammengebrochen waren, weitgehend unpopulär. Die Schwächung des kirchlichen Monopols und die zunehmende politische Macht der Reichen führten zu einem starken Rückgang der Einkommensumverteilung. Die Bauern und städtischen Armen, die nicht unmittelbar von dem neuen System profitierten, waren bitterlich neidisch auf diejenigen, die profitierten. Huizinga beschrieb die vorherrschende Haltung, was eine wichtige Parallele zur Informationsrevolution sein könnte: „Der Hass auf die Reichen, insbesondere auf die Neureichen, die damals sehr zahlreich waren, ist allgemein.“ [^161]

Eine ebenso auffällige Parallele ergab sich aus einem enormen Anstieg der Kriminalität. Der Zusammenbruch der alten Ordnung führt fast immer zu einem Anstieg der Kriminalität, wenn nicht sogar zur völligen Anarchie der feudalen Revolution, die wir im letzten Kapitel untersucht haben. Am Ende des Mittelalters schnellte die Kriminalität ebenfalls in die Höhe, als die alten Systeme der sozialen Kontrolle zusammenbrachen. In Huizingas Worten: „Die Kriminalität wurde als eine Bedrohung für die Ordnung und die Gesellschaft angesehen.“ [^162] Sie könnte in Zukunft ebenso bedrohlich sein.

Die moderne Welt entstand in einem Wirrwarr aus neuen Technologien, neuen Ideen und dem Gestank von Schwarzpulver. Schießpulverwaffen und eine verbesserte Schifffahrt destabilisierten die militärische Grundlage des Feudalismus, während neue Kommunikationstechnologien dessen Ideologie untergruben. Zu den Elementen, die durch die neue Technologie des Drucks zum Vorschein kamen, gehörte auch die Korruption der Kirche, deren Hierarchie wie auch deren Mitglieder ohnehin schon ein geringes Ansehen genossen, in einer Gesellschaft, die paradoxerweise die Religion in den Mittelpunkt von allem stellte. Es ist ein Paradoxon mit einer offensichtlichen Parallele in der Ernüchterung über Politiker und Bürokraten in einer Gesellschaft, die die Politik in den Mittelpunkt von allem stellt.

Das Ende des fünfzehnten Jahrhunderts war eine Zeit der Desillusionierung, der Verwirrung, des Pessimismus und der Verzweiflung. Eine Zeit, die der heutigen sehr ähnlich ist.

[^94]: Clarke, ebenda, S. 9.

[^95]: Martin van Creveld, *The Transformation of War* (New York: The Free Press, 1991), S. 52.

[^96]: *The Compact Edition of The Oxford English Dictionary*, ebenda, S. 1074.

[^97]: Siehe T.C. Onions, ed., *The Oxford Dictionary of English Etymology* (Oxford: Oxford University Press, 1966), S. 693.

[^98]: John Urquhart, *Former Premier Sues Canada for Libel in Probe of Alleged Airbus Kickbacks*, Wall Street Journal, 21. November 1995, S. A11.

[^99]: Huizinga, ebenda, S.172.

[^100]: Ebenda, S. 150.

[^101]: Ebenda, S. 56.

[^102]: Ebenda, S. 65.

[^103]: Ebenda, S. 22.

[^104]: van Creveld, ebenda, S. 52.

[^105]: Huizinga, ebenda, S. 21.

[^109]: Ebenda, S. 90.

[^110]: Ebenda, S. 87.

[^111]: Norman Cohn, *The Pursuit of the Millennium: Revolutionary Millenarians and Mystical Anarchists of the Middle Ages*, überarbeitete und erweiterte Ausgabe (Oxford: Oxford University Press, 1970), S. 127.

[^112]: Ebenda.

[^113]: Ebenda, S. 128.

[^114]: C. Northcote Parkinson, *Parkinson\'s Law and Other Studies in Administration* (Boston: Houghton Mifflin, 1957), S. 60, zitiert in Tilly, S. 4.

[^115]: van Creveld, ebenda, S. 50.

[^116]: Playfair, ebenda, S. 72.

[^117]: Huizinga, ebenda, S. 26.

[^118]: Ebenda, S. 57.

[^119]: Ebenda.

[^120]: Frederic C. Lane, *Venice: A Maritime Republic* (Baltimore: Johns Hopkins University Press, 1973), S. 275.

[^121]: Adam Smith, *An Inquiry into the Nature and Causes of the Wealth of Nations* (Chicago: University of Chicago Press, 1976), S. 8-9.

[^122]: Siehe H. J. Habakkuk und M. Postan, Hrsg., *The Cambridge Economic History of Europe*, vol.6, *The Industrial Revolution and After: Incomes, Population and Technological Change* (Cambridge: Cambridge University Press, 1966).

[^125]: Huizinga, ebenda, S. 198.

[^126]: Cameron, ebenda, S. 26-27.

[^129]: Ebenda, S. 102.

[^130]: Ebenda.

[^131]: Ebenda, S. 103.

[^132]: Huizinga, ebenda, S. 151.

[^133]: Cameron, ebenda, S. 31.

[^134]: Ebenda, S. 24.

[^135]: Ebenda, S. 15.

[^136]: Huizinga, ebenda, S. 27.

[^137]: Burford, ebenda, S. 103.

[^138]: Huizinga, ebenda, S. 173.

[^139]: Ebenda.

[^140]: William Manchester, *A World Lit Only by Fire: The Medieval Mind and the Renaissance* (Boston: Little, Brown, 1992), S. 75-76.

[^141]: Ebenda., S. 79.

[^142]: Ebenda, S. 82-84.

[^143]: Huizinga, ebenda, S. 154.

[^144]: Ebenda.

[^146]: Ebenda.

[^147]: Ebenda., S. 9.

[^148]: Diese Beispiele religiöser Rituale stammen von Cameron, ebenda, S. 10-11.

[^149]: Keith Thomas, *Religion and the Decline of Magic* (London: Penguin, 1971), S. .800, zitiert in Cameron, ebenda, S. 10.

[^150]: Huizinga, ebenda, S. 161.

[^152]: Huizinga, ebenda, S. 148.

[^153]: Für weitere Details zu den deutlichen Unterschieden zwischen den Perspektiven des fünfzehnten und sechzehnten Jahrhunderts in Bezug auf Armut, siehe Robert Jutte, *Poverty and Deviance in Early Modern Europe* (Cambridge: Cambridge University Press, 1994), S. 15-17.

[^156]: Ebenda., S. 11.

[^157]: Ebenda, S. 5.

[^158]: Huizinga, ebenda.

[^159]: Ebenda., S. 199.

[^160]: Ebenda., S. 203.

[^161]: Ebenda., S. 27.

[^162]: Ebenda., S. 22.

::: {.content-visible when-format=latex}
\setsubtitle{Demokratie und Nationalismus als Ressourcenstrategien im Zeitalter der Gewalt}
:::
